import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Inca Trail Hotel
export const theIncaTrailHotelRooms: RoomOption[] = [
  {
    id: "hotel-lima-5-room-4-Double-MountainView",
    name: "Superior Double Villa",
    description: "Our inviting Superior-themed villa offers where you can enjoy the mountains' majestic presence, roomy comfort, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 2059,
    currency: "PEN",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-lima-5-room-4-Single-MountainView",
    name: "Machu Picchu Single Suite",
    description: "A upscale single retreat overlooking spectacular mountain ranges, offering warm and inviting interiors.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 1695,
    currency: "PEN",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-lima-5-room-4-Single-CityView",
    name: "Machu Picchu Single Studio",
    description: "This contemporary single accommodation offers where the city skyline meets the horizon, blending rich cultural heritage with comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 1414,
    currency: "PEN",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-lima-5-room-4-Twin-GardenView",
    name: "Superior Twin Studio",
    description: "Enjoy a room-filled stay in our Superior-themed twin studio, offering with a view of shaded garden paths, with high-speed internet access, and unique touches of featuring Andean-inspired patterns and textures.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 1838,
    currency: "PEN",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-lima-5-room-4-Queen-CityView",
    name: "Classic Queen Apartment",
    description: "This refreshing queen apartment promises overlooking the vibrant cityscape, enriched by Classic-themed details and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 2283,
    currency: "PEN",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  }
];
