import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Urdaneta Pangasinan Hotel
export const urdanetaPangasinanHotelRooms: RoomOption[] = [
  {
    id: "hotel-palawan-2-room-1-Single-OceanView",
    name: "Classic Single Villa",
    description: "A homey single retreat with the sound of the ocean as your backdrop, featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 375133,
    currency: "PHP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-palawan-2-room-1-Single-MountainView",
    name: "Horizon Single Apartment",
    description: "Relax in our futuristic airy single apartment featuring with panoramic views of the mountain landscape, along with including climate control for your comfort and featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 383319,
    currency: "PHP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-palawan-2-room-1-Twin-CityView",
    name: "Classic Twin Room",
    description: "Classic-themed room with classic decor, where city lights twinkle at night, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Visual Aids", "Hearing Support", "Accessible Bathroom"],
    pricePerNight: 387025,
    currency: "PHP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-palawan-2-room-1-Queen-None",
    name: "Superior Queen Suite",
    description: "Indulge in the intimate atmosphere of our queen suite, with spectacular with a pleasant outlook, created with both style and function in mind, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 491296,
    currency: "PHP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-palawan-2-room-1-Double-GardenView",
    name: "Serenity Double Room",
    description: "Our Serenity-themed double room offers vintage luxury, panoramic with serene garden views, and offering a unique blend of style and comfort, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 412377,
    currency: "PHP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-palawan-2-room-1-SofaBed-GardenView",
    name: "Classic Sofa Bed Loft",
    description: "Discover the charm of this Classic-themed sofa bed loft, complete with tasteful ambiance, stunning surrounded by vibrant flora, and with a spacious seating area.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Visual Aids", "Elevator"],
    pricePerNight: 394761,
    currency: "PHP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
