import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Bremen Seaside Inn
export const bremenSeasideInnRooms: RoomOption[] = [
  {
    id: "hotel-berlin-10-room-9-Twin-None",
    name: "Harmony Twin Loft",
    description: "Harmony-themed loft with comfy decor, with a pleasant outlook, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 77,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-berlin-10-room-9-Twin-GardenView",
    name: "Harmony Twin Villa",
    description: "Harmony-themed villa with voluminous decor, where you can find solace in nature's embrace, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 95,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-berlin-10-room-9-King-OceanView",
    name: "Tranquility King Apartment",
    description: "A soothing king apartment designed for commodious comfort, with where you can enjoy stunning sunsets over the water and including climate control for your comfort, reflecting created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 170,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-berlin-10-room-9-King-MountainView",
    name: "Deluxe King Penthouse",
    description: "A intimate king retreat where you can enjoy the mountains' majestic presence, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 144,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-berlin-10-room-9-SofaBed-CityView",
    name: "Horizon Sofa Bed Apartment",
    description: "Enjoy a majestic stay in our Horizon-themed sofa bed apartment, offering where you can enjoy the city's energy, including climate control for your comfort, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 92,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-berlin-10-room-9-Queen-GardenView",
    name: "Tranquility Queen Apartment",
    description: "A restful queen retreat with a view of the garden's lush greenery, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 124,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-berlin-10-room-9-Queen-None",
    name: "Classic Queen Room",
    description: "Our Classic-themed queen room offers chic luxury, panoramic with a pleasant outlook, and featuring a curated minibar selection, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 95,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  }
];
