import { Hotel } from "@/lib/interfaces/services/rentals";

export const berlinHotels: Hotel[] = [
  {
    id: "hotel-berlin-1",
    name: "Sunset Villa",
    address: "192 Main Drive",
    rating: 3,
    accommodationType: "Extended Stay Hotel",
    amenities: ["Conference Room", "Free Wi-Fi", "Parking", "Swimming Pool", "Room Service", "Laundry Service", "Pet Friendly", "Spa", "Fitness Center", "Restaurant"],
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 50,
    isPetFriendly: true,
    currency: "EUR",
    contact: {
      contactEmail: "customerservice@sunsetvilla.com",
      contactPhone: "+234 699-404-9832",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-berlin-2",
    name: "The Prestige Hotel",
    address: "179 Park Way",
    rating: 3,
    accommodationType: "Eco-Lodge",
    amenities: ["Non-Smoking Rooms", "Room Service", "Airport Shuttle", "Parking", "Spa", "Fitness Center", "Bar", "Conference Room"],
    accessibilityFeatures: ["Visual Aids", "Accessible Shower", "Visual Alarm"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 11,
    isPetFriendly: false,
    currency: "EUR",
    contact: {
      contactEmail: "care@theprestigehotel.com",
      contactPhone: "+289 615-730-5059",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-berlin-3",
    name: "Heritage View",
    address: "87 Lower Queen Road",
    rating: 4,
    accommodationType: "Extended Stay Hotel",
    amenities: ["Swimming Pool", "Spa", "Pet Friendly", "Conference Room", "Parking", "Airport Shuttle", "Business Center"],
    accessibilityFeatures: ["Visual Aids"],
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 43,
    isPetFriendly: true,
    currency: "EUR",
    contact: {
      contactEmail: "clientservices@heritageview.com",
      contactPhone: "+726 254-133-4147",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Not Allowed",
    },
    isPopular: true,
  },
  {
    id: "hotel-berlin-4",
    name: "Skyline Suites",
    address: "85 Central Rd",
    rating: 3,
    accommodationType: "Luxury Villa",
    amenities: ["Free Wi-Fi", "24-Hour Front Desk", "Fitness Center", "Restaurant", "Parking"],
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 46,
    isPetFriendly: false,
    currency: "EUR",
    contact: {
      contactEmail: "services@skylinesuites.com",
      contactPhone: "+439 842-703-1482",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Allowed",
    },
    isPopular: true,
  },
  {
    id: "hotel-berlin-5",
    name: "The Harbor House",
    address: "202 Central Street",
    rating: 4,
    accommodationType: "Luxury Lodge",
    amenities: ["Swimming Pool", "Restaurant", "Bar", "Room Service", "Fitness Center", "Spa", "Business Center", "Free Wi-Fi", "Laundry Service"],
    accessibilityFeatures: ["Braille Signage", "Wheelchair Accessible", "Accessible Parking"],
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 21,
    isPetFriendly: false,
    currency: "EUR",
    contact: {
      contactEmail: "mail@theharborhouse.com",
      contactPhone: "+849 469-871-9772",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  }
];
