import { CrewMember } from "@/lib/interfaces/people/staff";

export const kyotojapanasiaPacificCrew: CrewMember[] = [
  {
    id: "crew-kyoto-1",
    name: "John Williams",
    role: "Deckhand",
    experienceYears: 19,
    certifications: ["First Aid", "Security Training"],
    languagesSpoken: ["Vietnamese", "Norwegian", "Finnish"],
    isAvailable: true,
    contactEmail: "john.williams@paragontrails.com",
    contactPhone: "+1-149-911-8003",
  },
  {
    id: "crew-kyoto-2",
    name: "Fatima Hassan",
    role: "Host/Hostess",
    experienceYears: 8,
    certifications: ["First Aid", "STCW"],
    languagesSpoken: ["Swedish"],
    isAvailable: true,
    contactEmail: "fatima.hassan@paragontrails.com",
    contactPhone: "+1-135-852-8471",
  },
  {
    id: "crew-kyoto-3",
    name: "Pedro Santos",
    role: "Engineer",
    experienceYears: 7,
    certifications: ["Fire Safety", "First Aid"],
    languagesSpoken: ["Turkish", "German"],
    isAvailable: false,
    contactEmail: "pedro.santos@paragontrails.com",
    contactPhone: "+1-360-293-9424",
  },
  {
    id: "crew-kyoto-4",
    name: "Olga Ivanova",
    role: "Engineer",
    experienceYears: 3,
    certifications: ["Fire Safety", "Marine Radio Operator", "Dive Master"],
    languagesSpoken: ["Russian", "Spanish"],
    isAvailable: true,
    contactEmail: "olga.ivanova@paragontrails.com",
    contactPhone: "+1-724-563-0120",
  },
  {
    id: "crew-kyoto-5",
    name: "Pedro Santos",
    role: "Deckhand",
    experienceYears: 9,
    certifications: [
      "First Aid",
      "Marine Radio Operator",
      "Hospitality Training",
    ],
    languagesSpoken: ["Italian", "Thai", "Dutch"],
    isAvailable: true,
    contactEmail: "pedro.santos@paragontrails.com",
    contactPhone: "+1-658-917-9854",
  },
  {
    id: "crew-kyoto-6",
    name: "Daniel Müller",
    role: "Dive Instructor",
    experienceYears: 14,
    certifications: [
      "Marine Radio Operator",
      "Environmental Awareness",
      "First Aid",
    ],
    languagesSpoken: ["Finnish"],
    isAvailable: true,
    contactEmail: "daniel.müller@paragontrails.com",
    contactPhone: "+1-667-155-9475",
  },
];
