import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Parisian Elegance Hotel
export const parisianEleganceHotelRooms: RoomOption[] = [
  {
    id: "hotel-cannes-12-room-11-Double-CityView",
    name: "Premium Double Penthouse",
    description: "Step into a snug double penthouse that combines Premium-themed with breathtaking where you can enjoy the city's energy, complemented by with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 81,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-cannes-12-room-11-King-MountainView",
    name: "Signature King Loft",
    description: "Unwind in this inviting king loft with a view of the mountains' changing seasons, featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids", "Hearing Support"],
    pricePerNight: 118,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-cannes-12-room-11-King-None",
    name: "Tranquility King Room",
    description: "Experience our pleasant, rustic king room with a pleasant outlook, with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 92,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-cannes-12-room-11-Twin-CityView",
    name: "Tranquility Twin Apartment",
    description: "Tranquility-themed twin apartment showcasing the urban landscape, where elegance meets Parisian style and with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Visual Aids", "Elevator", "Hearing Support"],
    pricePerNight: 62,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-cannes-12-room-11-Single-GardenView",
    name: "Classic Single Villa",
    description: "Classic-themed villa with well-proportioned decor, with serene garden views, and with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 58,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-cannes-12-room-11-SofaBed-OceanView",
    name: "Tranquility Sofa Bed Penthouse",
    description: "Our relaxing Tranquility-themed penthouse offers with breathtaking sea views, cozy comfort, and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 86,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-cannes-12-room-11-Double-MountainView",
    name: "Serenity Double Room",
    description: "Enjoy a open-concept stay in our Serenity-themed double room, offering where you can enjoy the mountains' majestic presence, with a luxurious soaking tub, and unique touches of where elegance meets Parisian style.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids", "Accessible Bathroom"],
    pricePerNight: 88,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-cannes-12-room-11-King-GardenView",
    name: "Classic King Suite",
    description: "This sophisticated king accommodation offers where you can enjoy the beauty of nature, featuring chic Parisian-inspired decor.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 120,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
