import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Somerset Village Suites
export const somersetVillageSuitesRooms: RoomOption[] = [
  {
    id: "hotel-bermuda-2-room-1-Twin-MountainView",
    name: "Atlantic Twin Penthouse",
    description: "Our Atlantic-themed twin penthouse offers ornate luxury, panoramic where you can escape to the mountains, and with high-speed internet access, inspired by featuring pastel colors and colonial influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 122,
    currency: "BMD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-bermuda-2-room-1-Twin-OceanView",
    name: "Premium Twin Room",
    description: "A room-filled twin room designed for pleasant comfort, with with the sound of the ocean as your backdrop and equipped with all the modern conveniences, reflecting offering tranquil and elegant interiors.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 109,
    currency: "BMD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-bermuda-2-room-1-Double-GardenView",
    name: "Executive Double Studio",
    description: "This inviting double accommodation offers where you can escape to a green sanctuary, blending seaside charm with refined comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 113,
    currency: "BMD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-bermuda-2-room-1-SofaBed-GardenView",
    name: "Reefside Sofa Bed Villa",
    description: "Discover the charm of this Reefside-themed sofa bed villa, complete with gentle ambiance, stunning where you can enjoy the serenity of a garden retreat, and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 108,
    currency: "BMD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-bermuda-2-room-1-King-GardenView",
    name: "Luxury King Villa",
    description: "Our contemporary Luxury-themed villa offers where you can enjoy the sights and sounds of nature, sophisticated comfort, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 177,
    currency: "BMD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-bermuda-2-room-1-Queen-GardenView",
    name: "Deluxe Queen Penthouse",
    description: "Discover the charm of this Deluxe-themed queen penthouse, complete with extravagant ambiance, stunning featuring a peaceful garden setting, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 140,
    currency: "BMD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-bermuda-2-room-1-King-MountainView",
    name: "Superior King Villa",
    description: "Superior-themed king villa with a view of the mountains' natural beauty, offering tranquil and elegant interiors and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 184,
    currency: "BMD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-bermuda-2-room-1-Queen-MountainView",
    name: "Deluxe Queen Apartment",
    description: "This modern queen apartment promises where you can enjoy the tranquility of the mountains, enriched by Deluxe-themed details and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 151,
    currency: "BMD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-bermuda-2-room-1-Single-MountainView",
    name: "Pink Sand Single Apartment",
    description: "This ornate single accommodation offers where you can enjoy the tranquility of the mountains, offering tranquil and elegant interiors.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 95,
    currency: "BMD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  }
];
