import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Somerset Village Suites
export const somersetVillageSuitesRooms: RoomOption[] = [
  {
    id: "hotel-bermuda-1-room-0-SofaBed-CityView",
    name: "Deluxe Sofa Bed Suite",
    description: "A glamorous sofa bed retreat with a view of iconic landmarks, offering tranquil and elegant interiors.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 185,
    currency: "BMD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-bermuda-1-room-0-Twin-None",
    name: "Grotto Twin Suite",
    description: "Discover the charm of this Grotto-themed twin suite, complete with plush ambiance, stunning with a pleasant outlook, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 164,
    currency: "BMD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-bermuda-1-room-0-Double-None",
    name: "Nautical Double Penthouse",
    description: "Our Nautical-themed double penthouse offers sizable luxury, panoramic with a pleasant outlook, and with a spacious work area, inspired by featuring pastel colors and colonial influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 205,
    currency: "BMD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-bermuda-1-room-0-Queen-MountainView",
    name: "Pink Sand Queen Suite",
    description: "Indulge in the comfortable atmosphere of our queen suite, with spectacular where you can take in the fresh mountain air, offering tranquil and elegant interiors, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 311,
    currency: "BMD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-bermuda-1-room-0-Single-OceanView",
    name: "Luxury Single Studio",
    description: "Experience our refined, eclectic single studio with a view of the sandy beaches, with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 188,
    currency: "BMD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-bermuda-1-room-0-Double-OceanView",
    name: "Executive Double Penthouse",
    description: "Executive-themed double penthouse with a view of the sandy beaches, highlighting Bermuda’s unique island heritage and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Elevator"],
    pricePerNight: 244,
    currency: "BMD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  }
];
