import { Attraction } from "@/lib/interfaces/services/attractions";

export const amsterdamnetherlandsnorthernEuropeAttractions: Attraction[] = [
  {
    title: "amsterdam Cathedral",
    description: "A beautiful cathedral in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-cathedral.jpg",
    location: "74 Main Street, amsterdam",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["Monument"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Square",
    description: "A beautiful square in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-square.jpg",
    location: "173 Main Street, amsterdam",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 4.7,
    tags: ["Cultural Center", "Religious Site"],
    accessibilityFeatures: ["accessible entrance", "elevator access"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Temple",
    description: "A beautiful temple in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-temple.jpg",
    location: "101 Main Street, amsterdam",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "evening",
    rating: 4.5,
    tags: ["Family Friendly", "Cultural Center"],
    accessibilityFeatures: ["limited accessibility", "wheelchair accessible"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "amsterdam Garden",
    description: "A beautiful garden in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-garden.jpg",
    location: "187 Main Street, amsterdam",
    openingHours: "Open 24 hours",
    entryFee: "€104",
    entryFeeCategory: "luxury",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["Garden", "Religious Site", "Cultural Center"],
    accessibilityFeatures: ["accessible entrance", "elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Gallery",
    description: "A beautiful gallery in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-gallery.jpg",
    location: "142 Main Street, amsterdam",
    openingHours: "9 AM - 5 PM",
    entryFee: "$7",
    entryFeeCategory: "budget",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.3,
    tags: ["Historical Site", "Shopping", "Hidden Gem"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Temple",
    description: "A beautiful temple in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-temple.jpg",
    location: "115 Main Street, amsterdam",
    openingHours: "Open 24 hours",
    entryFee: "¥65",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "night",
    rating: 4.6,
    tags: ["Garden", "Landmark", "Park"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Monument",
    description: "A beautiful monument in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-monument.jpg",
    location: "138 Main Street, amsterdam",
    openingHours: "Open 24 hours",
    entryFee: "€52",
    entryFeeCategory: "expensive",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "evening",
    rating: 4.4,
    tags: ["Luxury", "Landmark"],
    accessibilityFeatures: ["limited accessibility", "accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Tower",
    description: "A beautiful tower in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-tower.jpg",
    location: "20 Main Street, amsterdam",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.9,
    tags: ["Gallery", "Luxury"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Park",
    description: "A beautiful park in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-park.jpg",
    location: "57 Main Street, amsterdam",
    openingHours: "10 AM - 6 PM",
    entryFee: "€20",
    entryFeeCategory: "moderate",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["Iconic"],
    accessibilityFeatures: ["elevator access", "accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Park",
    description: "A beautiful park in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-park.jpg",
    location: "59 Main Street, amsterdam",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "evening",
    rating: 4.9,
    tags: ["Landmark", "Gallery", "Garden"],
    accessibilityFeatures: ["elevator access", "accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Park",
    description: "A beautiful park in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-park.jpg",
    location: "79 Main Street, amsterdam",
    openingHours: "10 AM - 6 PM",
    entryFee: "€99",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.7,
    tags: ["Scenic Spot", "Monument"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Monument",
    description: "A beautiful monument in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-monument.jpg",
    location: "45 Main Street, amsterdam",
    openingHours: "10 AM - 6 PM",
    entryFee: "€89",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "night",
    rating: 4.8,
    tags: ["Iconic", "Landmark", "Market"],
    accessibilityFeatures: ["accessible restrooms", "accessible entrance"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "amsterdam Gallery",
    description: "A beautiful gallery in amsterdam offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/amsterdam-gallery.jpg",
    location: "123 Main Street, amsterdam",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "night",
    rating: 4.3,
    tags: ["Museum", "Monument", "Gallery"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  }
];
