import { Attraction } from "@/lib/interfaces/services/attractions";

export const florenceitalymediterraneanAttractions: Attraction[] = [
  {
    title: "florence Garden",
    description: "A beautiful garden in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-garden.jpg",
    location: "162 Main Street, florence",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: ["Garden", "Free Entry"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "florence Museum",
    description: "A beautiful museum in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-museum.jpg",
    location: "109 Main Street, florence",
    openingHours: "10 AM - 6 PM",
    entryFee: "¥36",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.4,
    tags: ["Religious Site"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "florence Monument",
    description: "A beautiful monument in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-monument.jpg",
    location: "194 Main Street, florence",
    openingHours: "10 AM - 6 PM",
    entryFee: "€25",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.5,
    tags: ["Museum", "Luxury", "Religious Site"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "florence Square",
    description: "A beautiful square in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-square.jpg",
    location: "174 Main Street, florence",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "night",
    rating: 4.3,
    tags: ["Romantic", "Free Entry", "City View"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "florence Bridge",
    description: "A beautiful bridge in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-bridge.jpg",
    location: "35 Main Street, florence",
    openingHours: "9 AM - 5 PM",
    entryFee: "¥12",
    entryFeeCategory: "budget",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.7,
    tags: ["Garden", "Free Entry"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "florence Zoo",
    description: "A beautiful zoo in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-zoo.jpg",
    location: "170 Main Street, florence",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "evening",
    rating: 4.5,
    tags: ["Park"],
    accessibilityFeatures: ["accessible entrance", "accessible restrooms"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "florence Castle",
    description: "A beautiful castle in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-castle.jpg",
    location: "62 Main Street, florence",
    openingHours: "9 AM - 5 PM",
    entryFee: "£62",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.4,
    tags: ["City View", "Cultural Center", "Shopping"],
    accessibilityFeatures: ["elevator access", "accessible entrance"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "florence Temple",
    description: "A beautiful temple in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-temple.jpg",
    location: "6 Main Street, florence",
    openingHours: "9 AM - 5 PM",
    entryFee: "€62",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 4.2,
    tags: ["Hidden Gem", "Market"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "florence Palace",
    description: "A beautiful palace in florence offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/florence-palace.jpg",
    location: "62 Main Street, florence",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "all day",
    rating: 5,
    tags: ["Gallery", "City View", "Museum"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  }
];
