import { Attraction } from "@/lib/interfaces/services/attractions";

export const galapagosIslandsGalapagosEcuador: Attraction[] = [
  {
    title: "Tortuga Bay",
    description:
      "A pristine white sand beach accessible by a picturesque 30-minute trail from Puerto Ayora. The bay is divided into two areas: a protected calm-water cove perfect for swimming and snorkeling, and a surfing beach with impressive waves.",
    imageUrl: "/images/attractions/galapagos/tortuga-bay.jpg",
    location: "Santa Cruz Island, Galapagos Islands, Ecuador",
    openingHours: "6:00 AM - 6:00 PM daily",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: ["beach", "nature", "wildlife", "swimming", "hiking"],
    isPopular: true,

    isFree: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Charles Darwin Research Station",
    description:
      "A scientific research center focused on conservation and the restoration of Galapagos ecosystems. Visitors can see giant tortoise breeding programs in action and learn about conservation efforts for endangered species.",
    imageUrl: "/images/attractions/galapagos/darwin-research-station.jpg",
    location: "Puerto Ayora, Santa Cruz Island, Galapagos Islands, Ecuador",
    openingHours: "8:00 AM - 5:00 PM daily",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.6,
    tags: ["conservation", "educational", "wildlife", "science", "tortoises"],
    accessibilityFeatures: [
      "accessible paths",
      "wheelchair accessible facilities",
    ],
    isPopular: true,

    isFree: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isHistorical: true,
    isAdventure: false,
    isRomantic: false,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: true,
    isDining: false,
    isOutdoor: true,
    isIndoor: true,
  },
  {
    title: "Bartolomé Island",
    description:
      "A volcanic islet featuring one of the most iconic landscapes of the Galapagos - Pinnacle Rock. Visitors can climb to a summit viewpoint via wooden stairs and boardwalks for spectacular panoramas, and snorkel with penguins and tropical fish.",
    imageUrl: "/images/attractions/galapagos/bartolome-island.jpg",
    location: "Bartolomé Island, Galapagos Islands, Ecuador",
    entryFee: "$100 USD (National Park fee) + tour cost",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: [
      "volcanic landscape",
      "viewpoint",
      "snorkeling",
      "wildlife",
      "hiking",
    ],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Kicker Rock (León Dormido)",
    description:
      "A dramatic volcanic rock formation rising 140 meters from the ocean just off San Cristóbal Island. The channel between the rocks creates ideal conditions for snorkeling and diving with sharks, rays, turtles, and tropical fish.",
    imageUrl: "/images/attractions/galapagos/kicker-rock.jpg",
    location: "Near San Cristóbal Island, Galapagos Islands, Ecuador",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["snorkeling", "diving", "marine life", "geology", "boat tour"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "North Seymour Island",
    description:
      "A small island famous for its large colonies of blue-footed boobies and magnificent frigate birds. The flat, rocky terrain makes it easy to observe mating rituals, nesting behavior, and land iguanas in their natural habitat.",
    imageUrl: "/images/attractions/galapagos/north-seymour.jpg",
    location: "North Seymour Island, Galapagos Islands, Ecuador",
    entryFee: "Tour cost (varies by operator)",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["wildlife", "bird watching", "nature", "hiking", "photography"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: false,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Los Tuneles (The Tunnels)",
    description:
      "A unique volcanic landscape of arched lava formations, tunnels, and crystal-clear pools near Isabela Island. One of the best snorkeling spots in the Galapagos to see marine life including sea turtles, sharks, seahorses, and penguins.",
    imageUrl: "/images/attractions/galapagos/los-tuneles.jpg",
    location: "Isabela Island, Galapagos Islands, Ecuador",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: [
      "snorkeling",
      "lava formations",
      "marine life",
      "boat tour",
      "photography",
    ],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: true,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "El Chato Tortoise Reserve",
    description:
      "A highland reserve on Santa Cruz Island where visitors can observe Galapagos giant tortoises in their natural habitat. The area features lush vegetation, lava tunnels, and opportunities to see these ancient creatures up close.",
    imageUrl: "/images/attractions/galapagos/el-chato-reserve.jpg",
    location: "Santa Cruz Island, Galapagos Islands, Ecuador",
    openingHours: "8:00 AM - 5:00 PM daily",
    entryFee: "$3-5 USD entrance fee",
    entryFeeCategory: "budget",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["wildlife", "tortoises", "nature", "conservation", "hiking"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: false,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Sierra Negra Volcano",
    description:
      "An active volcano on Isabela Island featuring one of the largest volcanic calderas in the world (10km in diameter). The moderately challenging hike to the rim offers stunning views of the caldera, lava fields, and on clear days, neighboring islands.",
    imageUrl: "/images/attractions/galapagos/sierra-negra.jpg",
    location: "Isabela Island, Galapagos Islands, Ecuador",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["hiking", "volcano", "nature", "views", "geology"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Las Grietas",
    description:
      "A series of dramatic crevices filled with clear blue water, nestled between towering lava cliffs near Puerto Ayora. A popular spot for swimming and snorkeling in the unique mixture of fresh and saltwater with surprising depth and fish species.",
    imageUrl: "/images/attractions/galapagos/las-grietas.jpg",
    location: "Santa Cruz Island, Galapagos Islands, Ecuador",
    openingHours: "Open during daylight hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.6,
    tags: ["swimming", "snorkeling", "nature", "geological", "hiking"],
    isPopular: true,

    isFree: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Post Office Bay",
    description:
      "A historic site on Floreana Island where 18th-century whalers established an unofficial mail system using a wooden barrel. Visitors continue the tradition by leaving postcards and taking others to hand-deliver, creating unique human connections.",
    imageUrl: "/images/attractions/galapagos/post-office-bay.jpg",
    location: "Floreana Island, Galapagos Islands, Ecuador",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.5,
    tags: ["historical", "cultural", "tradition", "beach", "unique"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: true,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: true,
    isLocalExperience: true,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
];
