import { Attraction } from "@/lib/interfaces/services/attractions";

export const londonunitedKingdomnorthernEuropeAttractions: Attraction[] = [
  {
    title: "london Monument",
    description: "A beautiful monument in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-monument.jpg",
    location: "22 Main Street, london",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "evening",
    rating: 4.2,
    tags: ["Shopping", "Religious Site"],
    accessibilityFeatures: ["accessible restrooms", "limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: true,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "london Gallery",
    description: "A beautiful gallery in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-gallery.jpg",
    location: "129 Main Street, london",
    openingHours: "Open 24 hours",
    entryFee: "¥27",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.5,
    tags: ["Landmark"],
    accessibilityFeatures: ["elevator access", "wheelchair accessible"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "london Market",
    description: "A beautiful market in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-market.jpg",
    location: "167 Main Street, london",
    openingHours: "10 AM - 6 PM",
    entryFee: "£38",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "night",
    rating: 4.4,
    tags: ["Park", "Market"],
    accessibilityFeatures: ["accessible entrance", "limited accessibility"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "london Museum",
    description: "A beautiful museum in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-museum.jpg",
    location: "127 Main Street, london",
    openingHours: "Open 24 hours",
    entryFee: "€26",
    entryFeeCategory: "moderate",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "evening",
    rating: 4.9,
    tags: ["Monument", "Free Entry"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "london Park",
    description: "A beautiful park in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-park.jpg",
    location: "169 Main Street, london",
    openingHours: "Open 24 hours",
    entryFee: "¥16",
    entryFeeCategory: "moderate",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: ["Historical Site", "Romantic"],
    accessibilityFeatures: ["limited accessibility", "accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "london Garden",
    description: "A beautiful garden in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-garden.jpg",
    location: "94 Main Street, london",
    openingHours: "9 AM - 5 PM",
    entryFee: "£26",
    entryFeeCategory: "moderate",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 4.8,
    tags: ["Iconic", "Monument"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "london Square",
    description: "A beautiful square in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-square.jpg",
    location: "47 Main Street, london",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.5,
    tags: ["Cultural Center", "Shopping"],
    accessibilityFeatures: ["wheelchair accessible", "limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "london Gallery",
    description: "A beautiful gallery in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-gallery.jpg",
    location: "200 Main Street, london",
    openingHours: "10 AM - 6 PM",
    entryFee: "¥81",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.7,
    tags: ["Historical Site", "Gallery", "Monument"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "london Park",
    description: "A beautiful park in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-park.jpg",
    location: "152 Main Street, london",
    openingHours: "Open 24 hours",
    entryFee: "£77",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["City View", "Religious Site", "Garden"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "london Bridge",
    description: "A beautiful bridge in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-bridge.jpg",
    location: "137 Main Street, london",
    openingHours: "10 AM - 6 PM",
    entryFee: "¥92",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "night",
    rating: 4.5,
    tags: ["Free Entry"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "london Palace",
    description: "A beautiful palace in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-palace.jpg",
    location: "38 Main Street, london",
    openingHours: "Open 24 hours",
    entryFee: "€5",
    entryFeeCategory: "budget",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "evening",
    rating: 4.7,
    tags: ["Historical Site", "Religious Site"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "london Park",
    description: "A beautiful park in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-park.jpg",
    location: "73 Main Street, london",
    openingHours: "9 AM - 5 PM",
    entryFee: "¥65",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "night",
    rating: 4.7,
    tags: ["Religious Site", "City View", "Family Friendly"],
    accessibilityFeatures: ["accessible entrance", "accessible restrooms"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "london Market",
    description: "A beautiful market in london offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/london-market.jpg",
    location: "162 Main Street, london",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "evening",
    rating: 4.8,
    tags: ["Park", "Free Entry"],
    accessibilityFeatures: ["accessible entrance", "wheelchair accessible"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  }
];
