import { Attraction } from "@/lib/interfaces/services/attractions";

export const melbourneAttractions: Attraction[] = [
  {
    title: "Discover Top Attractions in Melbourne",
    description: "A beautiful park in Melbourne offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://images.unsplash.com/melbourne-park.jpg",
    location: "114 Main Street, Melbourne",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "night",
    rating: 4.8,
    tags: ["Garden", "UNESCO Site"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "Discover Top Attractions in Melbourne",
    description: "A beautiful gallery in Melbourne offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://images.unsplash.com/melbourne-gallery.jpg",
    location: "38 Main Street, Melbourne",
    openingHours: "9 AM - 5 PM",
    entryFee: "¥92",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: ["Monument"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "Discover Top Attractions in Melbourne",
    description: "A beautiful temple in Melbourne offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://images.unsplash.com/melbourne-temple.jpg",
    location: "194 Main Street, Melbourne",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "night",
    rating: 4.2,
    tags: ["Scenic Spot", "Landmark"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "Discover Top Attractions in Melbourne",
    description: "A beautiful palace in Melbourne offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://images.unsplash.com/melbourne-palace.jpg",
    location: "28 Main Street, Melbourne",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "night",
    rating: 5,
    tags: ["Cultural Center"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  }
];
