import { Attraction } from "@/lib/interfaces/services/attractions";

export const newYorkCityunitedStateseastCoastUsaAttractions: Attraction[] = [
  {
    title: "new-york-city Park",
    description: "A beautiful park in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-park.jpg",
    location: "165 Main Street, new-york-city",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "evening",
    rating: 4.9,
    tags: ["Luxury", "Historical Site"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Park",
    description: "A beautiful park in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-park.jpg",
    location: "151 Main Street, new-york-city",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.3,
    tags: ["Romantic"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Tower",
    description: "A beautiful tower in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-tower.jpg",
    location: "69 Main Street, new-york-city",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["Family Friendly", "Iconic", "Gallery"],
    accessibilityFeatures: ["accessible entrance", "wheelchair accessible"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "new-york-city Temple",
    description: "A beautiful temple in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-temple.jpg",
    location: "135 Main Street, new-york-city",
    openingHours: "Open 24 hours",
    entryFee: "$37",
    entryFeeCategory: "moderate",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.8,
    tags: ["Market"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "new-york-city Castle",
    description: "A beautiful castle in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-castle.jpg",
    location: "171 Main Street, new-york-city",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.5,
    tags: ["Free Entry", "Garden"],
    accessibilityFeatures: ["limited accessibility", "accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Zoo",
    description: "A beautiful zoo in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-zoo.jpg",
    location: "23 Main Street, new-york-city",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 5,
    tags: ["Historical Site", "Monument"],
    accessibilityFeatures: ["limited accessibility", "wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "new-york-city Bridge",
    description: "A beautiful bridge in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-bridge.jpg",
    location: "125 Main Street, new-york-city",
    openingHours: "9 AM - 5 PM",
    entryFee: "$51",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "night",
    rating: 4.3,
    tags: ["Religious Site", "Scenic Spot", "Luxury"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "new-york-city Cathedral",
    description: "A beautiful cathedral in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-cathedral.jpg",
    location: "13 Main Street, new-york-city",
    openingHours: "9 AM - 5 PM",
    entryFee: "£28",
    entryFeeCategory: "moderate",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.7,
    tags: ["Monument", "Family Friendly", "Park"],
    accessibilityFeatures: ["elevator access", "wheelchair accessible"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: true,
    isNightlife: true,
    isLuxury: true,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "new-york-city Zoo",
    description: "A beautiful zoo in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-zoo.jpg",
    location: "107 Main Street, new-york-city",
    openingHours: "9 AM - 5 PM",
    entryFee: "€82",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 4.3,
    tags: ["Landmark"],
    accessibilityFeatures: ["accessible restrooms", "limited accessibility"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Bridge",
    description: "A beautiful bridge in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-bridge.jpg",
    location: "6 Main Street, new-york-city",
    openingHours: "10 AM - 6 PM",
    entryFee: "€82",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.9,
    tags: ["Hidden Gem", "Park"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "new-york-city Monument",
    description: "A beautiful monument in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-monument.jpg",
    location: "25 Main Street, new-york-city",
    openingHours: "10 AM - 6 PM",
    entryFee: "$86",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.6,
    tags: ["Monument", "Family Friendly"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Garden",
    description: "A beautiful garden in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-garden.jpg",
    location: "51 Main Street, new-york-city",
    openingHours: "9 AM - 5 PM",
    entryFee: "$11",
    entryFeeCategory: "budget",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "evening",
    rating: 5,
    tags: ["Landmark", "Monument"],
    accessibilityFeatures: ["limited accessibility", "elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Garden",
    description: "A beautiful garden in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-garden.jpg",
    location: "87 Main Street, new-york-city",
    openingHours: "9 AM - 5 PM",
    entryFee: "£99",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.5,
    tags: ["Market"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Square",
    description: "A beautiful square in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-square.jpg",
    location: "157 Main Street, new-york-city",
    openingHours: "9 AM - 5 PM",
    entryFee: "$16",
    entryFeeCategory: "moderate",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "all day",
    rating: 4.8,
    tags: ["Hidden Gem"],
    accessibilityFeatures: ["accessible entrance", "elevator access"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Palace",
    description: "A beautiful palace in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-palace.jpg",
    location: "46 Main Street, new-york-city",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "night",
    rating: 4.2,
    tags: ["Gallery", "Landmark"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "new-york-city Garden",
    description: "A beautiful garden in new-york-city offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/new-york-city-garden.jpg",
    location: "79 Main Street, new-york-city",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "daytime",
    rating: 4.6,
    tags: ["Gallery"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  }
];
