import { Attraction } from "@/lib/interfaces/services/attractions";

export const newYorkNyUnitedStates: Attraction[] = [
  {
    title: "Statue of Liberty",
    description:
      "An iconic symbol of freedom and democracy, this colossal statue is located on Liberty Island.",
    imageUrl: "https://plus.unsplash.com/statue-of-liberty.jpg",
    location: "Liberty Island, New York, NY, USA",
    openingHours: "8:30 AM - 4 PM",
    entryFee: "$23.50",
    priceRange: "$$",
    entryFeeCategory: "moderate",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["historical", "cultural", "iconic"],
    accessibilityFeatures: ["wheelchair accessible"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isHistorical: true,
  },
  {
    title: "Central Park",
    description:
      "A sprawling urban park offering a peaceful escape with walking paths, lakes, and recreational areas.",
    imageUrl: "https://plus.unsplash.com/central-park.jpg",
    location: "Central Park, New York, NY, USA",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    priceRange: "free",
    entryFeeCategory: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.9,
    tags: ["nature", "recreation", "scenic"],
    accessibilityFeatures: ["wheelchair accessible"],
    isPopular: true,

    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "Times Square",
    description:
      "A bustling commercial and entertainment hub known for its bright lights and vibrant atmosphere.",
    imageUrl: "https://plus.unsplash.com/times-square.jpg",
    location: "Times Square, New York, NY, USA",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    priceRange: "free",
    entryFeeCategory: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.7,
    tags: ["entertainment", "cultural", "iconic"],
    accessibilityFeatures: ["wheelchair accessible"],
    isPopular: true,

    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
    isHistorical: false,
  },
  {
    title: "Metropolitan Museum of Art",
    description:
      "One of the largest and most prestigious art museums in the world, featuring a vast collection of art from various cultures and time periods.",
    imageUrl: "https://plus.unsplash.com/metropolitan-museum-of-art.jpg",
    location: "1000 5th Ave, New York, NY, USA",
    openingHours: "10 AM - 5:30 PM",
    entryFee: "$25",
    priceRange: "$$",
    entryFeeCategory: "moderate",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: ["cultural", "historical", "art"],
    accessibilityFeatures: ["wheelchair accessible"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "Brooklyn Bridge",
    description:
      "A historic suspension bridge connecting Manhattan and Brooklyn, offering stunning views of the skyline.",
    imageUrl: "https://plus.unsplash.com/brooklyn-bridge.jpg",
    location: "Brooklyn Bridge, New York, NY, USA",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    priceRange: "free",
    entryFeeCategory: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.8,
    tags: ["historical", "scenic", "iconic"],
    accessibilityFeatures: ["wheelchair accessible"],
    isPopular: true,

    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "Empire State Building",
    description:
      "An iconic skyscraper offering panoramic views of the city from its observation decks.",
    imageUrl: "https://plus.unsplash.com/empire-state-building.jpg",
    location: "20 W 34th St, New York, NY, USA",
    openingHours: "8 AM - 2 AM",
    entryFee: "$42",
    priceRange: "$$",
    entryFeeCategory: "moderate",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["cultural", "historical", "views"],
    accessibilityFeatures: ["wheelchair accessible"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "The Edge Observation Deck",
    description:
      "The highest outdoor sky deck in the Western Hemisphere, offering 360-degree views of New York City from 100 stories high with a glass floor and angled glass walls.",
    imageUrl: "https://plus.unsplash.com/edge-hudson-yards.jpg",
    location: "30 Hudson Yards, New York, NY, USA",
    openingHours: "10 AM - 10 PM",
    entryFee: "$38",
    priceRange: "$$",
    entryFeeCategory: "moderate",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.8,
    tags: ["viewpoint", "modern", "photography"],
    accessibilityFeatures: ["wheelchair accessible", "elevator access"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "Eleven Madison Park",
    description:
      "A three-Michelin-starred restaurant offering an innovative plant-based tasting menu showcasing the finest ingredients through sophisticated techniques in an elegant Art Deco setting.",
    imageUrl: "https://plus.unsplash.com/eleven-madison-park.jpg",
    location: "11 Madison Avenue, New York, NY, USA",
    openingHours: "5:30 PM - 10:00 PM, Closed Sundays and Mondays",
    entryFee: "$335 per person for tasting menu",
    priceRange: "$$$",
    entryFeeCategory: "expensive",
    priceCategory: "expensive",
    timeOfDay: "evening",
    rating: 4.9,
    tags: ["dining", "luxury", "gourmet"],
    accessibilityFeatures: ["wheelchair accessible"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isDining: true,
  },
];
