import { Attraction } from "@/lib/interfaces/services/attractions";

export const panautiBagmatiProvinceNepal: Attraction[] = [
  {
    title: "Panauti Durbar Square",
    description:
      "A historical square featuring ancient temples and traditional Newari architecture, showcasing the rich cultural heritage of Panauti.",
    imageUrl: "https://plus.unsplash.com/panauti-durbar-square.jpg",
    location: "Panauti, Bagmati Province, Nepal",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    priceRange: "free",
    entryFeeCategory: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.6,
    tags: ["cultural", "historical", "architecture"],
    accessibilityFeatures: ["limited accessibility"],
    isPopular: true,

    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "Indreshwar Mahadev Temple",
    description:
      "An ancient Hindu temple dedicated to Lord Shiva, known for its intricate carvings and spiritual significance.",
    imageUrl: "https://plus.unsplash.com/indreshwar-mahadev-temple.jpg",
    location: "Indreshwar Mahadev Temple, Panauti",
    openingHours: "6 AM - 7 PM",
    entryFee: "Free",
    priceCategory: "free",
    priceRange: "free",
    entryFeeCategory: "free",
    timeOfDay: "daytime",
    rating: 4.5,
    tags: ["religious", "cultural", "historical"],
    accessibilityFeatures: ["limited accessibility"],
    isPopular: true,

    isFree: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "Panauti Eco Park",
    description:
      "A serene park offering lush greenery, walking trails, and a peaceful environment for relaxation and nature walks.",
    imageUrl: "https://plus.unsplash.com/panauti-eco-park.jpg",
    location: "Panauti Eco Park, Panauti",
    openingHours: "Open 24 hours",
    entryFee: "$1 per person",
    priceCategory: "moderate",
    priceRange: "$$",
    entryFeeCategory: "budget",
    timeOfDay: "all day",
    rating: 4.4,
    tags: ["nature", "outdoor", "recreation"],
    accessibilityFeatures: ["wheelchair accessible"],
    isPopular: true,

    isFree: false,
    isPetFriendly: true,
    isWheelchairAccessible: true,
    isHistorical: false,
  },
  {
    title: "Buddha Stupa",
    description:
      "A peaceful Buddhist stupa offering a tranquil atmosphere for meditation and reflection, surrounded by beautiful gardens.",
    imageUrl: "https://plus.unsplash.com/buddha-stupa.jpg",
    location: "Buddha Stupa, Panauti",
    openingHours: "6 AM - 6 PM",
    entryFee: "Free",
    priceCategory: "free",
    priceRange: "free",
    entryFeeCategory: "free",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["religious", "cultural", "peaceful"],
    accessibilityFeatures: ["limited accessibility"],
    isPopular: true,

    isFree: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "Panauti Community Homestay",
    description:
      "An authentic cultural experience where visitors can stay with local families, learn about their traditions, participate in daily activities, and enjoy traditional Newari cuisine.",
    imageUrl: "https://plus.unsplash.com/panauti-homestay.jpg",
    location: "Panauti Town, Bagmati Province, Nepal",
    openingHours: "Open 24 hours",
    entryFee: "$25-35 per night including meals",
    priceRange: "$$",
    priceCategory: "moderate",
    entryFeeCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.8,
    tags: ["cultural", "local experience", "homestay"],
    accessibilityFeatures: ["limited accessibility"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isLocalExperience: true,
  },
  {
    title: "Triveni Ghat",
    description:
      "A sacred confluence of three rivers where pilgrims gather for religious ceremonies and rituals, especially during festivals.",
    imageUrl: "https://plus.unsplash.com/triveni-ghat.jpg",
    location: "Southern edge of Panauti, Bagmati Province, Nepal",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    priceRange: "free",
    priceCategory: "free",
    entryFeeCategory: "free",
    timeOfDay: "daytime",
    rating: 4.6,
    tags: ["religious", "cultural", "spiritual"],
    accessibilityFeatures: ["limited accessibility"],
    isPopular: true,

    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
    isHistorical: true,
  },
];
