import { Attraction } from "@/lib/interfaces/services/attractions";

export const patagoniaSouthernChileAndArgentinaChileArgentina: Attraction[] = [
  {
    title: "Torres del Paine National Park",
    description:
      "One of South America's most spectacular national parks featuring iconic granite towers, turquoise lakes, glaciers, and diverse wildlife. The park offers world-class hiking trails including the famous W and O circuits.",
    imageUrl: "/images/attractions/patagonia/torres-del-paine.jpg",
    location: "Magallanes Region, Chile",
    openingHours:
      "Open year-round, 8:30 AM - 8:30 PM (summer), 8:30 AM - 5:00 PM (winter)",
    entryFee: "$30-45 USD for foreign visitors",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.9,
    tags: ["hiking", "mountains", "glaciers", "wildlife", "trekking", "nature"],
    accessibilityFeatures: [
      "some accessible viewpoints",
      "accessible visitor center",
    ],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Perito Moreno Glacier",
    description:
      "One of the world's few advancing glaciers and most accessible ice fields. This massive ice formation regularly calves huge icebergs into Lake Argentino, creating a spectacular natural show. Visitors can view from platforms or take boat tours and ice treks.",
    imageUrl: "/images/attractions/patagonia/perito-moreno-glacier.jpg",
    location: "Los Glaciares National Park, Santa Cruz Province, Argentina",
    openingHours: "8:00 AM - 6:00 PM daily",
    entryFee: "3100 Argentine Pesos (~$35 USD)",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: [
      "glacier",
      "ice trek",
      "boat tours",
      "national park",
      "natural wonder",
    ],
    accessibilityFeatures: [
      "wheelchair accessible walkways",
      "accessible viewpoints",
    ],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Mount Fitz Roy",
    description:
      "An iconic peak in the Southern Patagonian Ice Field and a mecca for mountaineers and photographers. The area around El Chaltén offers day hikes with stunning views of the mountain's distinctive silhouette and pristine alpine lakes.",
    imageUrl: "/images/attractions/patagonia/mount-fitz-roy.jpg",
    location: "El Chaltén, Santa Cruz Province, Argentina",
    openingHours: "Always open, best visited October-April",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: ["hiking", "mountains", "photography", "trekking", "nature"],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Tierra del Fuego National Park",
    description:
      "The southernmost national park in the world featuring subpolar forests, mountains, glaciers, and access to the Beagle Channel. Home to diverse wildlife and the terminus of the Pan-American Highway.",
    imageUrl: "/images/attractions/patagonia/tierra-del-fuego.jpg",
    location: "Ushuaia, Tierra del Fuego, Argentina",
    openingHours: "8:00 AM - 8:00 PM (summer), 10:00 AM - 5:00 PM (winter)",
    entryFee: "700 Argentine Pesos (~$8 USD)",
    entryFeeCategory: "budget",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.6,
    tags: ["hiking", "forests", "wildlife", "canoeing", "end of the world"],
    accessibilityFeatures: [
      "some accessible paths",
      "accessible visitor center",
    ],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isHistorical: true,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Bariloche and the Lake District",
    description:
      "A picturesque alpine-style town surrounded by lakes and mountains, offering skiing in winter and hiking, mountain biking, and water activities in summer. Known for its Swiss-like architecture, chocolate shops, and breweries.",
    imageUrl: "/images/attractions/patagonia/bariloche.jpg",
    location: "Río Negro Province, Argentina",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.7,
    tags: ["lakes", "mountains", "skiing", "chocolate", "brewing", "hiking"],
    accessibilityFeatures: [
      "accessible accommodation options",
      "some accessible activities",
    ],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isNightlife: true,
    isShopping: true,
    isDining: true,
    isOutdoor: true,
    isIndoor: true,
  },
  {
    title: "Península Valdés",
    description:
      "A UNESCO World Heritage site and wildlife sanctuary where visitors can observe southern right whales, elephant seals, sea lions, orcas, and Magellanic penguins in their natural habitat.",
    imageUrl: "/images/attractions/patagonia/peninsula-valdes.jpg",
    location: "Chubut Province, Argentina",
    openingHours: "8:00 AM - 8:00 PM daily",
    entryFee: "1100 Argentine Pesos (~$12 USD)",
    entryFeeCategory: "budget",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["wildlife", "whales", "penguins", "nature reserve", "coastal"],
    accessibilityFeatures: [
      "some accessible viewpoints",
      "accessible visitor center",
    ],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Marble Caves (Capillas de Mármol)",
    description:
      "Stunning natural marble formations accessible only by boat on General Carrera Lake. The swirling patterns of blue and gray marble have been shaped by water erosion over thousands of years, creating cathedral-like spaces.",
    imageUrl: "/images/attractions/patagonia/marble-caves.jpg",
    location: "General Carrera Lake, Chile Chico, Aysén Region, Chile",
    openingHours: "Tours typically run 9:00 AM - 5:00 PM (weather dependent)",
    entryFee: "$30-50 USD for boat tours",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["caves", "boat tours", "natural wonder", "photography", "geology"],
    accessibilityFeatures: [
      "some accessible viewpoints",
      "accessible visitor center",
    ],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: true,
    isLocalExperience: true,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Ushuaia - End of the World",
    description:
      "The southernmost city in the world and gateway to Antarctica, offering unique maritime history, Antarctic expedition departures, and the iconic 'End of the World' sign. Features mountain and coastal activities with dramatic landscapes.",
    imageUrl: "/images/attractions/patagonia/ushuaia.jpg",
    location: "Tierra del Fuego Province, Argentina",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.5,
    tags: [
      "southernmost city",
      "end of the world",
      "Antarctica",
      "maritime",
      "hiking",
    ],
    accessibilityFeatures: [
      "some accessible attractions",
      "accessible downtown area",
    ],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
    isHistorical: true,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isNightlife: true,
    isShopping: true,
    isDining: true,
    isOutdoor: true,
    isIndoor: true,
  },
  {
    title: "Carretera Austral",
    description:
      "Chile's legendary Southern Highway stretching 1,240 kilometers through pristine Patagonian wilderness, connecting remote communities and providing access to national parks, fjords, glaciers, and hot springs.",
    imageUrl: "/images/attractions/patagonia/carretera-austral.jpg",
    location: "Los Lagos and Aysén Regions, Chile",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "all day",
    rating: 4.7,
    tags: ["road trip", "scenic drive", "adventure", "remote", "wilderness"],
    accessibilityFeatures: [
      "some accessible viewpoints",
      "accessible visitor center",
    ],
    isPopular: false,
    isFamilyFriendly: true,
    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: true,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: true,
    isLocalExperience: true,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Punta Tombo Penguin Colony",
    description:
      "The largest Magellanic penguin colony in South America where over a million penguins gather annually to breed. Visitors can walk among the penguins on designated paths from September to April.",
    imageUrl: "/images/attractions/patagonia/punta-tombo.jpg",
    location: "Chubut Province, Argentina",
    openingHours: "8:00 AM - 6:00 PM (September-April)",
    entryFee: "850 Argentine Pesos (~$9 USD)",
    entryFeeCategory: "budget",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.6,
    tags: [
      "wildlife",
      "penguins",
      "nature reserve",
      "bird watching",
      "coastal",
    ],
    accessibilityFeatures: [
      "some accessible viewpoints",
      "accessible visitor center",
    ],
    isPopular: true,
    isFamilyFriendly: true,
    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isHistorical: false,
    isAdventure: false,
    isRomantic: true,
    isLuxury: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isNightlife: false,
    isShopping: false,
    isDining: false,
    isOutdoor: true,
    isIndoor: false,
  },
];
