import { Attraction } from "@/lib/interfaces/services/attractions";

export const sanFranciscounitedStateswestCoastUsaAttractions: Attraction[] = [
  {
    title: "san-francisco Garden",
    description: "A beautiful garden in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-garden.jpg",
    location: "41 Main Street, san-francisco",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.2,
    tags: ["City View", "Scenic Spot", "Market"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-francisco Cathedral",
    description: "A beautiful cathedral in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-cathedral.jpg",
    location: "138 Main Street, san-francisco",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["Gallery", "Cultural Center", "Market"],
    accessibilityFeatures: ["accessible entrance", "limited accessibility"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-francisco Museum",
    description: "A beautiful museum in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-museum.jpg",
    location: "81 Main Street, san-francisco",
    openingHours: "Open 24 hours",
    entryFee: "$39",
    entryFeeCategory: "moderate",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "all day",
    rating: 4.3,
    tags: ["Cultural Center"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "san-francisco Garden",
    description: "A beautiful garden in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-garden.jpg",
    location: "101 Main Street, san-francisco",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "evening",
    rating: 4.3,
    tags: ["Gallery", "Hidden Gem", "Museum"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-francisco Castle",
    description: "A beautiful castle in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-castle.jpg",
    location: "14 Main Street, san-francisco",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "night",
    rating: 4.3,
    tags: ["Cultural Center", "Market", "Family Friendly"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: true,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-francisco Garden",
    description: "A beautiful garden in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-garden.jpg",
    location: "31 Main Street, san-francisco",
    openingHours: "10 AM - 6 PM",
    entryFee: "$100",
    entryFeeCategory: "luxury",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "evening",
    rating: 4.3,
    tags: ["Landmark", "Hidden Gem", "Luxury"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-francisco Palace",
    description: "A beautiful palace in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-palace.jpg",
    location: "75 Main Street, san-francisco",
    openingHours: "9 AM - 5 PM",
    entryFee: "¥7",
    entryFeeCategory: "budget",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["Gallery", "Park", "Romantic"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "san-francisco Zoo",
    description: "A beautiful zoo in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-zoo.jpg",
    location: "19 Main Street, san-francisco",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.4,
    tags: ["Shopping"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "san-francisco Park",
    description: "A beautiful park in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-park.jpg",
    location: "180 Main Street, san-francisco",
    openingHours: "10 AM - 6 PM",
    entryFee: "£86",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "night",
    rating: 5,
    tags: ["Museum", "Free Entry", "Cultural Center"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "san-francisco Bridge",
    description: "A beautiful bridge in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-bridge.jpg",
    location: "11 Main Street, san-francisco",
    openingHours: "Open 24 hours",
    entryFee: "$69",
    entryFeeCategory: "expensive",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.4,
    tags: ["Luxury"],
    accessibilityFeatures: ["elevator access", "accessible restrooms"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-francisco Park",
    description: "A beautiful park in san-francisco offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-francisco-park.jpg",
    location: "22 Main Street, san-francisco",
    openingHours: "Open 24 hours",
    entryFee: "¥101",
    entryFeeCategory: "luxury",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: ["City View", "Monument", "Scenic Spot"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  }
];
