import { Attraction } from "@/lib/interfaces/services/attractions";

export const sanJuanpuertoRicocaribbeanAttractions: Attraction[] = [
  {
    title: "san-juan Temple",
    description: "A beautiful temple in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-temple.jpg",
    location: "37 Main Street, san-juan",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.5,
    tags: ["Museum"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: true,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "san-juan Palace",
    description: "A beautiful palace in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-palace.jpg",
    location: "78 Main Street, san-juan",
    openingHours: "10 AM - 6 PM",
    entryFee: "¥57",
    entryFeeCategory: "expensive",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "daytime",
    rating: 4.4,
    tags: ["Garden", "Museum"],
    accessibilityFeatures: ["elevator access", "wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: true,
    isNightlife: true,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "san-juan Tower",
    description: "A beautiful tower in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-tower.jpg",
    location: "171 Main Street, san-juan",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.2,
    tags: ["Romantic"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-juan Garden",
    description: "A beautiful garden in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-garden.jpg",
    location: "135 Main Street, san-juan",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["Museum", "Cultural Center", "Gallery"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-juan Zoo",
    description: "A beautiful zoo in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-zoo.jpg",
    location: "187 Main Street, san-juan",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "evening",
    rating: 4.3,
    tags: ["Historical Site"],
    accessibilityFeatures: ["wheelchair accessible", "accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "san-juan Castle",
    description: "A beautiful castle in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-castle.jpg",
    location: "133 Main Street, san-juan",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["Landmark", "Family Friendly"],
    accessibilityFeatures: ["accessible entrance", "accessible restrooms"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "san-juan Market",
    description: "A beautiful market in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-market.jpg",
    location: "16 Main Street, san-juan",
    openingHours: "9 AM - 5 PM",
    entryFee: "£47",
    entryFeeCategory: "moderate",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.3,
    tags: ["Shopping", "City View"],
    accessibilityFeatures: ["limited accessibility", "elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "san-juan Temple",
    description: "A beautiful temple in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-temple.jpg",
    location: "58 Main Street, san-juan",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.5,
    tags: ["City View", "Cultural Center"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "san-juan Temple",
    description: "A beautiful temple in san-juan offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/san-juan-temple.jpg",
    location: "129 Main Street, san-juan",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.2,
    tags: ["Shopping"],
    accessibilityFeatures: ["accessible restrooms", "wheelchair accessible"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  }
];
