import { Attraction } from "@/lib/interfaces/services/attractions";

export const santoriniAttractions: Attraction[] = [
  {
    title: "santorini Tower",
    description: "A beautiful tower in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-tower.jpg",
    location: "16 Main Street, santorini",
    openingHours: "Open 24 hours",
    entryFee: "£49",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 5,
    tags: ["Park", "Shopping"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Zoo",
    description: "A beautiful zoo in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-zoo.jpg",
    location: "141 Main Street, santorini",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["Scenic Spot"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Museum",
    description: "A beautiful museum in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-museum.jpg",
    location: "71 Main Street, santorini",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "evening",
    rating: 4.7,
    tags: ["Cultural Center"],
    accessibilityFeatures: ["accessible restrooms", "accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Zoo",
    description: "A beautiful zoo in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-zoo.jpg",
    location: "54 Main Street, santorini",
    openingHours: "9 AM - 5 PM",
    entryFee: "€50",
    entryFeeCategory: "expensive",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "night",
    rating: 5,
    tags: ["Historical Site", "Religious Site", "Landmark"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Castle",
    description: "A beautiful castle in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-castle.jpg",
    location: "13 Main Street, santorini",
    openingHours: "10 AM - 6 PM",
    entryFee: "£55",
    entryFeeCategory: "expensive",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["Free Entry", "Cultural Center"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Square",
    description: "A beautiful square in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-square.jpg",
    location: "184 Main Street, santorini",
    openingHours: "Open 24 hours",
    entryFee: "¥66",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "all day",
    rating: 4.3,
    tags: ["Park", "Romantic", "Shopping"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: true,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Palace",
    description: "A beautiful palace in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-palace.jpg",
    location: "82 Main Street, santorini",
    openingHours: "Open 24 hours",
    entryFee: "$48",
    entryFeeCategory: "moderate",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "all day",
    rating: 4.4,
    tags: ["Park"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Garden",
    description: "A beautiful garden in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-garden.jpg",
    location: "91 Main Street, santorini",
    openingHours: "9 AM - 5 PM",
    entryFee: "£64",
    entryFeeCategory: "expensive",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.3,
    tags: ["Park", "Historical Site"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Tower",
    description: "A beautiful tower in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-tower.jpg",
    location: "30 Main Street, santorini",
    openingHours: "Open 24 hours",
    entryFee: "$30",
    entryFeeCategory: "moderate",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "night",
    rating: 4.9,
    tags: ["City View", "Free Entry"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Museum",
    description: "A beautiful museum in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-museum.jpg",
    location: "7 Main Street, santorini",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "night",
    rating: 5,
    tags: ["Free Entry", "Market"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "santorini Temple",
    description: "A beautiful temple in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-temple.jpg",
    location: "43 Main Street, santorini",
    openingHours: "10 AM - 6 PM",
    entryFee: "£88",
    entryFeeCategory: "expensive",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "night",
    rating: 4.3,
    tags: ["Park", "Market"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Square",
    description: "A beautiful square in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-square.jpg",
    location: "133 Main Street, santorini",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.7,
    tags: ["Monument", "Romantic", "Landmark"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: true,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Museum",
    description: "A beautiful museum in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-museum.jpg",
    location: "182 Main Street, santorini",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 4.3,
    tags: ["Museum", "Garden"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Castle",
    description: "A beautiful castle in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-castle.jpg",
    location: "139 Main Street, santorini",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "evening",
    rating: 4.9,
    tags: ["Gallery", "Free Entry", "Religious Site"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: true,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Garden",
    description: "A beautiful garden in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-garden.jpg",
    location: "17 Main Street, santorini",
    openingHours: "Open 24 hours",
    entryFee: "€7",
    entryFeeCategory: "budget",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "all day",
    rating: 4.8,
    tags: ["Cultural Center", "Romantic"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Cathedral",
    description: "A beautiful cathedral in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-cathedral.jpg",
    location: "39 Main Street, santorini",
    openingHours: "9 AM - 5 PM",
    entryFee: "$84",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 4.5,
    tags: ["Gallery"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "santorini Temple",
    description: "A beautiful temple in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-temple.jpg",
    location: "66 Main Street, santorini",
    openingHours: "9 AM - 5 PM",
    entryFee: "£74",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["Family Friendly", "Romantic", "Scenic Spot"],
    accessibilityFeatures: ["accessible entrance", "wheelchair accessible"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "santorini Bridge",
    description: "A beautiful bridge in santorini offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/santorini-bridge.jpg",
    location: "176 Main Street, santorini",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 4.8,
    tags: ["Scenic Spot"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  }
];
