import { Attraction } from "@/lib/interfaces/services/attractions";

export const stThomasAttractions: Attraction[] = [
  {
    title: "st-thomas Square",
    description:
      "A beautiful square in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-square.jpg",
    location: "16 Main Street, st-thomas",
    openingHours: "Open 24 hours",
    entryFee: "$24",
    entryFeeCategory: "moderate",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "night",
    rating: 4.7,
    tags: ["Iconic", "Local Market"],
    accessibilityFeatures: ["elevator access", "accessible restrooms"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Park",
    description:
      "A beautiful park in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-park.jpg",
    location: "99 Main Street, st-thomas",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.9,
    tags: ["Historical Site"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "st-thomas Gallery",
    description:
      "A beautiful gallery in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-gallery.jpg",
    location: "107 Main Street, st-thomas",
    openingHours: "10 AM - 6 PM",
    entryFee: "€73",
    entryFeeCategory: "expensive",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "daytime",
    rating: 4.3,
    tags: ["Museum"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Square",
    description:
      "A beautiful square in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-square.jpg",
    location: "184 Main Street, st-thomas",
    openingHours: "9 AM - 5 PM",
    entryFee: "€51",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.2,
    tags: ["Monument"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "st-thomas Square",
    description:
      "A beautiful square in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-square.jpg",
    location: "148 Main Street, st-thomas",
    openingHours: "9 AM - 5 PM",
    entryFee: "£71",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "all day",
    rating: 4.9,
    tags: ["Cultural Center", "Hidden Gem"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Tower",
    description:
      "A beautiful tower in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-tower.jpg",
    location: "189 Main Street, st-thomas",
    openingHours: "Open 24 hours",
    entryFee: "$93",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "all day",
    rating: 4.5,
    tags: ["Gallery", "Landmark", "Photography Spot"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Gallery",
    description:
      "A beautiful gallery in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-gallery.jpg",
    location: "136 Main Street, st-thomas",
    openingHours: "10 AM - 6 PM",
    entryFee: "$20",
    entryFeeCategory: "moderate",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "evening",
    rating: 4.2,
    tags: ["Historical Site", "UNESCO Site"],
    accessibilityFeatures: ["wheelchair accessible", "limited accessibility"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "st-thomas Castle",
    description:
      "A beautiful castle in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-castle.jpg",
    location: "28 Main Street, st-thomas",
    openingHours: "Open 24 hours",
    entryFee: "¥56",
    entryFeeCategory: "expensive",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.6,
    tags: ["Iconic", "Local Market", "Scenic Spot"],
    accessibilityFeatures: ["elevator access", "limited accessibility"],
    isHistorical: false,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Park",
    description:
      "A beautiful park in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-park.jpg",
    location: "157 Main Street, st-thomas",
    openingHours: "Open 24 hours",
    entryFee: "$21",
    entryFeeCategory: "moderate",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 5,
    tags: ["Gallery", "Hidden Gem"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Castle",
    description:
      "A beautiful castle in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-castle.jpg",
    location: "17 Main Street, st-thomas",
    openingHours: "Open 24 hours",
    entryFee: "£69",
    entryFeeCategory: "expensive",
    priceRange: "$",
    priceCategory: "budget",
    timeOfDay: "night",
    rating: 4.6,
    tags: ["Garden", "Cultural Center"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Park",
    description:
      "A beautiful park in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-park.jpg",
    location: "110 Main Street, st-thomas",
    openingHours: "10 AM - 6 PM",
    entryFee: "£60",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.6,
    tags: ["Park", "Religious Site", "Cultural Center"],
    accessibilityFeatures: ["limited accessibility", "accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Castle",
    description:
      "A beautiful castle in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-castle.jpg",
    location: "141 Main Street, st-thomas",
    openingHours: "9 AM - 5 PM",
    entryFee: "$54",
    entryFeeCategory: "expensive",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.8,
    tags: ["Park", "Hidden Gem"],
    accessibilityFeatures: ["accessible restrooms", "elevator access"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: true,
    isSpiritual: true,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Museum",
    description:
      "A beautiful museum in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-museum.jpg",
    location: "36 Main Street, st-thomas",
    openingHours: "9 AM - 5 PM",
    entryFee: "£65",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "night",
    rating: 4.2,
    tags: ["Garden", "UNESCO Site", "Cultural Center"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "st-thomas Castle",
    description:
      "A beautiful castle in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-castle.jpg",
    location: "40 Main Street, st-thomas",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "night",
    rating: 4.8,
    tags: ["Park", "UNESCO Site"],
    accessibilityFeatures: ["elevator access", "accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: true,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Park",
    description:
      "A beautiful park in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-park.jpg",
    location: "80 Main Street, st-thomas",
    openingHours: "9 AM - 5 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "night",
    rating: 4.4,
    tags: ["Iconic", "Monument", "Market"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: true,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: true,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Temple",
    description:
      "A beautiful temple in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-temple.jpg",
    location: "168 Main Street, st-thomas",
    openingHours: "10 AM - 6 PM",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "evening",
    rating: 4.6,
    tags: ["Garden", "Museum"],
    accessibilityFeatures: ["wheelchair accessible", "elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
  },
  {
    title: "st-thomas Castle",
    description:
      "A beautiful castle in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-castle.jpg",
    location: "126 Main Street, st-thomas",
    openingHours: "10 AM - 6 PM",
    entryFee: "$13",
    entryFeeCategory: "budget",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "evening",
    rating: 4.8,
    tags: ["Park"],
    accessibilityFeatures: ["accessible entrance"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: false,
  },
  {
    title: "st-thomas Temple",
    description:
      "A beautiful temple in st-thomas offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://plus.unsplash.com/st-thomas-temple.jpg",
    location: "50 Main Street, st-thomas",
    openingHours: "9 AM - 5 PM",
    entryFee: "$48",
    entryFeeCategory: "moderate",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "all day",
    rating: 4.9,
    tags: ["Garden", "Park", "Cultural Center"],
    accessibilityFeatures: ["accessible restrooms"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
];
