import { Attraction } from "@/lib/interfaces/services/attractions";

export const tahitiSocietyIslandsFrenchPolynesia: Attraction[] = [
  {
    title: "Plage de Matira",
    description:
      "One of the most beautiful beaches in French Polynesia featuring powdery white sand and crystal-clear turquoise waters perfect for swimming and snorkeling.",
    imageUrl: "https://plus.unsplash.com/matira-beach-tahiti.jpg",
    location: "Matira Beach, Bora Bora, French Polynesia",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "all day",
    rating: 4.9,
    tags: ["adventure", "local"],
    accessibilityFeatures: ["firm sand in some areas"],
    isPopular: true,

    isFree: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
    isRomantic: true,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Lagoonarium",
    description:
      "A natural aquarium where visitors can swim and snorkel among tropical fish, rays, and small sharks in a controlled section of the lagoon.",
    imageUrl: "https://plus.unsplash.com/lagoonarium-tahiti.jpg",
    location: "Lagoonarium, Bora Bora, French Polynesia",
    openingHours: "9:00 AM - 5:00 PM daily",
    entryFee: "3,000 XPF (approximately $28)",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "daytime",
    rating: 4.7,
    tags: ["local", "adventure"],
    accessibilityFeatures: ["staff assistance available"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isAdventure: true,
    isRomantic: true,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Mount Otemanu",
    description:
      "The iconic volcanic remnant that forms the dramatic centerpiece of Bora Bora, offering hiking opportunities and breathtaking views of the island and lagoon.",
    imageUrl: "https://plus.unsplash.com/mount-otemanu-tahiti.jpg",
    location: "Mount Otemanu, Bora Bora, French Polynesia",
    openingHours: "Best visited from 7:00 AM - 5:00 PM",
    entryFee: "Free (guided hikes from 10,000 XPF)",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.8,
    tags: ["local", "wellness", "adventure"],
    accessibilityFeatures: ["difficult terrain"],
    isPopular: true,

    isFree: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isAdventure: true,
    isRomantic: true,
    isOffTheBeatenPath: true,
    isLocalExperience: true,
    isOutdoor: true,
    isIndoor: false,
  },
  {
    title: "Marché de Papeete",
    description:
      "The colorful central market of Tahiti's capital where locals sell fresh produce, flowers, handcrafts, monoi oils, and Tahitian vanilla, offering an authentic glimpse into everyday island life.",
    imageUrl: "https://plus.unsplash.com/papeete-market.jpg",
    location: "Rue du Marché, Papeete, Tahiti",
    openingHours: "7:30 AM - 5:00 PM (Mon-Sat), 7:30 AM - 9:00 AM (Sun)",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.6,
    tags: ["cultural", "local"],
    accessibilityFeatures: ["ground level access", "crowded spaces"],
    isPopular: true,

    isFree: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isRomantic: false,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isOutdoor: false,
    isIndoor: true,
  },
  {
    title: "Traditional Polynesian Dance Show",
    description:
      "Experience the vibrant culture of French Polynesia through traditional dance performances featuring colorful costumes, rhythmic drums, and mesmerizing fire dancing.",
    imageUrl: "https://plus.unsplash.com/polynesian-dance-tahiti.jpg",
    location: "Various resorts and cultural centers throughout Tahiti",
    openingHours: "Usually 7:00 PM - 9:00 PM on select days",
    entryFee: "5,000-10,000 XPF (approximately $45-90)",
    entryFeeCategory: "moderate",
    priceRange: "$$",
    priceCategory: "moderate",
    timeOfDay: "evening",
    rating: 4.8,
    tags: ["cultural", "art-and-music", "local"],
    accessibilityFeatures: ["seating available", "well-lit venues"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isRomantic: true,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isNightlife: true,
    isOutdoor: false,
    isIndoor: true,
  },
  {
    title: "Overwater Bungalow Experience",
    description:
      "Stay in an iconic overwater bungalow with direct lagoon access, glass floor sections to view marine life, and private terraces for unparalleled sunset views over Mount Otemanu.",
    imageUrl: "https://plus.unsplash.com/overwater-bungalow-tahiti.jpg",
    location: "Various luxury resorts in Bora Bora, French Polynesia",
    openingHours: "24 hours (accommodation)",
    entryFee: "From 100,000 XPF (approximately $900) per night",
    entryFeeCategory: "luxury",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.9,
    tags: ["adventure", "luxury", "local"],
    accessibilityFeatures: ["staff assistance available"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isLuxury: true,
    isRomantic: true,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isOutdoor: true,
    isIndoor: true,
  },
  {
    title: "Private Motu Picnic",
    description:
      "A luxurious private picnic experience on your own small islet (motu) featuring fresh Polynesian cuisine, champagne, and perfect snorkeling conditions in the surrounding crystal-clear waters.",
    imageUrl: "https://plus.unsplash.com/motu-picnic-tahiti.jpg",
    location: "Private motus around Bora Bora, French Polynesia",
    openingHours: "Typically 10:00 AM - 3:00 PM by reservation",
    entryFee: "From 25,000 XPF (approximately $225) per person",
    entryFeeCategory: "expensive",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "daytime",
    rating: 4.9,
    tags: ["local", "romantic", "culinary"],
    accessibilityFeatures: ["boat transfer required"],
    isPopular: true,

    isFree: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isLuxury: true,
    isRomantic: true,
    isOffTheBeatenPath: true,
    isLocalExperience: true,
    isOutdoor: true,
    isIndoor: false,
  },
];
