import { Attraction } from "@/lib/interfaces/services/attractions";

export const tampaAttractions: Attraction[] = [
  {
    title: "Discover Top Attractions in Tampa",
    description: "A beautiful garden in Tampa offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://images.unsplash.com/tampa-garden.jpg",
    location: "165 Main Street, Tampa",
    openingHours: "10 AM - 6 PM",
    entryFee: "¥32",
    entryFeeCategory: "moderate",
    priceRange: "$$$",
    priceCategory: "expensive",
    timeOfDay: "evening",
    rating: 4.4,
    tags: ["Religious Site", "Historical Site", "Cultural Center"],
    accessibilityFeatures: ["wheelchair accessible"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
  },
  {
    title: "Discover Top Attractions in Tampa",
    description: "A beautiful zoo in Tampa offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://images.unsplash.com/tampa-zoo.jpg",
    location: "125 Main Street, Tampa",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "$$$$",
    priceCategory: "luxury",
    timeOfDay: "all day",
    rating: 4.2,
    tags: ["Historical Site"],
    accessibilityFeatures: ["elevator access"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  },
  {
    title: "Discover Top Attractions in Tampa",
    description: "A beautiful palace in Tampa offering visitors a unique cultural experience and stunning views.",
    imageUrl: "https://images.unsplash.com/tampa-palace.jpg",
    location: "93 Main Street, Tampa",
    openingHours: "Open 24 hours",
    entryFee: "Free",
    entryFeeCategory: "free",
    priceRange: "free",
    priceCategory: "free",
    timeOfDay: "daytime",
    rating: 4.3,
    tags: ["Scenic Spot", "Monument"],
    accessibilityFeatures: ["limited accessibility"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: true,
    isPopular: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
  }
];
