import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Lotus Bloom Hotel
export const lotusBloomHotelRooms: RoomOption[] = [
  {
    id: "hotel-xi-an-6-room-5-King-GardenView",
    name: "Serenity King Suite",
    description: "A spacious king retreat offering a peaceful garden outlook, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 1077,
    currency: "CNY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-xi-an-6-room-5-Queen-CityView",
    name: "Tranquility Queen Studio",
    description: "Discover the charm of this Tranquility-themed queen studio, complete with compact ambiance, stunning showcasing the urban landscape, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Elevator"],
    pricePerNight: 1020,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-xi-an-6-room-5-SofaBed-None",
    name: "Classic Sofa Bed Loft",
    description: "This open-concept sofa bed loft promises with a pleasant outlook, enriched by Classic-themed details and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 675,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-xi-an-6-room-5-Twin-CityView",
    name: "Premium Twin Penthouse",
    description: "Unwind in this vintage twin penthouse featuring a blend of modern and historic architecture, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 686,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-xi-an-6-room-5-Single-CityView",
    name: "Tranquility Single Room",
    description: "A deluxe single retreat overlooking the vibrant cityscape, decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 638,
    currency: "CNY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  }
];
