import { Tour } from "@/lib/interfaces/services/tours";

export const baliindonesiaasiaPacificTours: Tour[] = [
  {
    id: "tour-bali-1",
    guideId: "guide-bali-1",
    title: "Historic Landmarks Tour",
    description:
      "Journey through the history of bali on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "bali",
    country: "Indonesia",
    region: "Asia Pacific",
    languagesOffered: ["English", "Arabic"],
    durationInHours: 6,
    price: "€136",
    tags: ["Historical", "Eco"],
    type: "LGBTQ+ Friendly Tour",
    schedule: [
      {
        attractionId: "attraction-bali-17-2",
        dayOfWeek: "Wednesday",
        startTime: "5:00 PM",
        endTime: "9:00 PM",
      },
      {
        attractionId: "attraction-bali-17-1",
        dayOfWeek: "Tuesday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 136,
    currency: "EUR",
    maxGroupSize: 7,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 54,
    included: [
      "Transportation during tour",
      "Coffee and/or Tea",
      "Entrance fees",
      "Welcome drink",
    ],
    notIncluded: ["Luggage storage", "Hotel pickup and drop-off"],
    requirements: ["Language proficiency recommended"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.1,
  },
  {
    id: "tour-bali-2",
    guideId: "guide-bali-1",
    title: "Panoramic Hiking Journey",
    description:
      "Uncover the secrets of bali on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "bali",
    country: "Indonesia",
    region: "Asia Pacific",
    languagesOffered: ["English", "Arabic"],
    durationInHours: 12,
    price: "¥132",
    tags: ["Hiking", "Local Market"],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-bali-17-2",
        dayOfWeek: "Monday",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 132,
    currency: "JPY",
    maxGroupSize: 6,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 28,
    included: [
      "Cooking demonstration",
      "Food samples",
      "Audio guide",
      "Use of helmet",
    ],
    notIncluded: [
      "Additional entrance fees",
      "Transportation to/from attractions",
    ],
    requirements: ["Wheelchair accessible"],
    cancellationPolicy:
      "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.4,
  },
  {
    id: "tour-bali-3",
    guideId: "guide-bali-2",
    title: "Bargain Hunter's Experience",
    description:
      "Discover the best of bali on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "bali",
    country: "Indonesia",
    region: "Asia Pacific",
    languagesOffered: ["English", "French"],
    durationInHours: 8,
    price: "£27",
    tags: ["Local Market", "Eco", "Religious", "Beach"],
    type: "Helicopter Tour",
    schedule: [
      {
        attractionId: "attraction-bali-17-1",
        dayOfWeek: "Sunday",
        startTime: "11:00 AM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-bali-17-2",
        dayOfWeek: "Monday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 27,
    currency: "GBP",
    maxGroupSize: 10,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 67,
    included: [
      "Live entertainment",
      "Use of bicycle",
      "WiFi on board",
      "Gratuities",
      "Lunch",
    ],
    notIncluded: ["Luggage storage", "Hotel pickup and drop-off"],
    requirements: [
      "Credit/debit cards accepted",
      "Arrive 15 minutes early",
      "Valid ID required",
    ],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 3.9,
  },
];
