// Auto-generated file for bermuda tours
// Country: Bermuda, Region: Bermuda

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const bermudabermudabermudaTours: Tour[] = [
  {
    id: "tour-bermuda-1",
    guideId: "guide-bermuda-2",
    title: "From Canvases to Cathedrals",
    description: "Journey through the history of bermuda on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "bermuda",
    country: "Bermuda",
    region: "Bermuda",
    languagesOffered: [
      "English",
    ],
    price: "BD$46",
    tags: [
      "Art And Culture",
      "City Highlights And History",
      "Nature And Scenic",
      "Family Friendly",
    ],
    type: "Nature Tour",
    schedule: [
      {
        attractionId: "attraction-bermuda-20-2",
        dayOfWeek: "Thursday",
        startTime: "1:00 PM",
        endTime: "4:00 PM",
      },
    ],
    pricePerPerson: 46,
    currency: "BMD",
    maxGroupSize: 21,
    minGroupSize: 6,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 15,
    included: [
      "Transportation during tour (if applicable)",
      "Food samples",
      "Snacks",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Optional activities not included in the tour",
      "Transportation to/from the tour start point",
      "Parking fees",
    ],
    requirements: [
      "Bring own headphones",
      "Minimum age: 12",
    ],
    cancellationPolicy: "50% refund if canceled 48 hours before the experience",
    rating: 5,
  },
  {
    id: "tour-bermuda-2",
    guideId: "guide-bermuda-6",
    title: "Nocturnal City Adventure",
    description: "Explore the vibrant streets of bermuda with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "bermuda",
    country: "Bermuda",
    region: "Bermuda",
    languagesOffered: [
      "English",
    ],
    price: "BD$110",
    tags: [
      "Nightlife And Entertainment",
      "Adventure And Thrill",
    ],
    type: "Mystery Tours",
    schedule: [
      {
        attractionId: "attraction-bermuda-20-3",
        dayOfWeek: "Monday",
        startTime: "8:00 AM",
        endTime: "9:00 AM",
      },
      {
        attractionId: "attraction-bermuda-20-1",
        dayOfWeek: "Saturday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-bermuda-20-5",
        dayOfWeek: "Tuesday",
        startTime: "11:00 AM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-bermuda-20-2",
        dayOfWeek: "Wednesday",
        startTime: "11:00 AM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 110,
    currency: "BMD",
    maxGroupSize: 33,
    minGroupSize: 6,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 53,
    included: [
      "Souvenir photos",
      "Entrance fees (if applicable)",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Travel insurance",
      "Personal expenses",
      "Parking fees",
    ],
    requirements: [
      "Valid ID required",
      "Passport required",
      "Advanced fitness level required",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4.3,
  },
  {
    id: "tour-bermuda-3",
    guideId: "guide-bermuda-4",
    title: "Petals and Pagodas",
    description: "Uncover the secrets of bermuda on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "bermuda",
    country: "Bermuda",
    region: "Bermuda",
    languagesOffered: [
      "English",
    ],
    price: "BD$36",
    tags: [
      "Poetic And Whimsical",
      "Nature And Scenic",
    ],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-bermuda-20-5",
        dayOfWeek: "Sunday",
        startTime: "9:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-bermuda-20-3",
        dayOfWeek: "Monday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-bermuda-20-1",
        dayOfWeek: "Tuesday",
        startTime: "11:00 AM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 36,
    currency: "BMD",
    maxGroupSize: 35,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 63,
    included: [
      "Souvenir photos",
      "Coffee and/or Tea",
      "Bottled water",
    ],
    notIncluded: [
      "Transportation to/from the tour start point",
      "Airport transfers",
      "Travel insurance",
    ],
    requirements: [
      "Basic fitness level required",
      "COVID-19 vaccination required",
      "Minimum age: 12",
      "Minimum age: 18",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 4.7,
  },
  {
    id: "tour-bermuda-4",
    guideId: "guide-bermuda-5",
    title: "Edge of the Earth Expedition",
    description: "Uncover the secrets of bermuda on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "bermuda",
    country: "Bermuda",
    region: "Bermuda",
    languagesOffered: [
      "English",
    ],
    price: "BD$116",
    tags: [
      "Adventure And Thrill",
    ],
    type: "Religious Tours",
    schedule: [
      {
        attractionId: "attraction-bermuda-20-4",
        dayOfWeek: "Saturday",
        startTime: "3:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-bermuda-20-1",
        dayOfWeek: "Sunday",
        startTime: "5:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-bermuda-20-2",
        dayOfWeek: "Thursday",
        startTime: "5:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-bermuda-20-3",
        dayOfWeek: "Wednesday",
        startTime: "8:00 AM",
        endTime: "10:00 AM",
      },
    ],
    pricePerPerson: 116,
    currency: "BMD",
    maxGroupSize: 44,
    minGroupSize: 14,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 5,
    included: [
      "Hotel pickup and drop-off",
      "Headsets to hear the guide",
      "Transportation during tour (if applicable)",
      "Food samples",
      "Coffee and/or Tea",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Travel insurance",
    ],
    requirements: [
      "Signed waiver required",
      "Minimum age: 12",
      "Passport required",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-bermuda-5",
    guideId: "guide-bermuda-1",
    title: "Food and Culture Fusion",
    description: "Uncover the secrets of bermuda on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "bermuda",
    country: "Bermuda",
    region: "Bermuda",
    languagesOffered: [
      "English",
    ],
    price: "BD$172",
    tags: [
      "Culinary And Food",
      "Adventure And Thrill",
    ],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-bermuda-20-3",
        dayOfWeek: "Wednesday",
        startTime: "4:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 172,
    currency: "BMD",
    maxGroupSize: 31,
    minGroupSize: 14,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 32,
    included: [
      "Transportation during tour (if applicable)",
      "Coffee and/or Tea",
      "Gratuities",
      "Food samples",
      "Snacks",
    ],
    notIncluded: [
      "Travel insurance",
      "Food and drinks at restaurants and/or cafes",
      "Personal expenses",
    ],
    requirements: [
      "No pets allowed",
      "Minimum age: 18",
      "Tickets must be printed",
    ],
    cancellationPolicy: "No refunds for cancellations within 24 hours",
    rating: 4.5,
  },
  {
    id: "tour-bermuda-6",
    guideId: "guide-bermuda-2",
    title: "Nocturnal City Adventure",
    description: "Uncover the secrets of bermuda on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "bermuda",
    country: "Bermuda",
    region: "Bermuda",
    languagesOffered: [
      "English",
    ],
    price: "BD$45",
    tags: [
      "Nightlife And Entertainment",
      "City Highlights And History",
      "Culinary And Food",
    ],
    type: "Mystery Tours",
    schedule: [
      {
        attractionId: "attraction-bermuda-20-2",
        dayOfWeek: "Tuesday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 45,
    currency: "BMD",
    maxGroupSize: 39,
    minGroupSize: 13,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 94,
    included: [
      "Food samples",
      "Local taxes",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Travel insurance",
    ],
    requirements: [
      "Tickets must be printed",
      "Arrive 15 minutes early",
      "No pets allowed",
    ],
    cancellationPolicy: "50% refund if canceled 48 hours before the experience",
    rating: 4.6,
  },
];
