// Auto-generated file for cape-town tours
// Country: South Africa, Region: Africa

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const cape-townsouthAfricaafricaTours: Tour[] = [
  {
    id: "tour-cape-town-1",
    guideId: "guide-cape-town-2",
    title: "City Below the Surface",
    description: "Immerse yourself in the local culture of cape-town with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "cape-town",
    country: "South Africa",
    region: "Africa",
    languagesOffered: [
      "English",
    ],
    price: "R558",
    tags: [
      "Sightseeing",
      "Luxury",
      "Historical",
    ],
    type: "Underground Tour",
    schedule: [
      {
        attractionId: "attraction-cape-town-22-1",
        dayOfWeek: "Saturday",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-2",
        dayOfWeek: "Friday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-3",
        dayOfWeek: "Thursday",
        startTime: "9:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 558,
    currency: "ZAR",
    maxGroupSize: 46,
    minGroupSize: 7,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 6,
    included: [
      "Hotel pickup and drop-off",
      "Coffee and/or Tea",
      "Gratuities",
    ],
    notIncluded: [
      "Luggage storage",
      "Personal expenses",
    ],
    requirements: [
      "Arrive 15 minutes early",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.4,
  },
  {
    id: "tour-cape-town-2",
    guideId: "guide-cape-town-2",
    title: "Handpicked Highlights Tour",
    description: "Journey through the history of cape-town on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "cape-town",
    country: "South Africa",
    region: "Africa",
    languagesOffered: [
      "English",
    ],
    price: "R446.4",
    tags: [
      "Food & Drink",
      "Family",
      "Art",
      "Adventure",
    ],
    type: "Private Tour",
    schedule: [
      {
        attractionId: "attraction-cape-town-22-1",
        dayOfWeek: "Thursday",
        startTime: "10:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-3",
        dayOfWeek: "Friday",
        startTime: "9:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 446.4,
    currency: "ZAR",
    maxGroupSize: 47,
    minGroupSize: 10,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 29,
    included: [
      "Gratuities",
      "Local taxes",
      "Entrance fees (if applicable)",
      "Headsets to hear the guide",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Personal expenses",
      "Gratuities",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Arrive 15 minutes early",
      "Minimum age: 12",
      "Service animals permitted",
      "Bring own headphones",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 4.8,
  },
  {
    id: "tour-cape-town-3",
    guideId: "guide-cape-town-10",
    title: "Street-Level Stories",
    description: "Immerse yourself in the local culture of cape-town with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "cape-town",
    country: "South Africa",
    region: "Africa",
    languagesOffered: [
      "English",
    ],
    price: "R818.4",
    tags: [
      "Historical",
      "Sports",
      "Religious",
      "Romantic",
    ],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-cape-town-22-1",
        dayOfWeek: "Sunday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-2",
        dayOfWeek: "Monday",
        startTime: "1:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-3",
        dayOfWeek: "Saturday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 818.4,
    currency: "ZAR",
    maxGroupSize: 34,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 33,
    included: [
      "Snacks",
      "Hotel pickup and drop-off",
      "Souvenir photos",
      "Local taxes",
      "Bottled water",
      "Gratuities",
    ],
    notIncluded: [
      "Luggage storage",
      "Personal expenses",
      "Food and drinks at restaurants and/or cafes",
      "Travel insurance",
    ],
    requirements: [
      "Government-issued ID for entry",
      "Advanced fitness level required",
      "Cash only",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.8,
  },
  {
    id: "tour-cape-town-4",
    guideId: "guide-cape-town-2",
    title: "Brewery Backstage Pass",
    description: "Journey through the history of cape-town on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "cape-town",
    country: "South Africa",
    region: "Africa",
    languagesOffered: [
      "English",
      "Afrikaans",
      "Xhosa",
    ],
    price: "R334.8",
    tags: [
      "Scenic",
      "Art",
      "Cruise Stop",
    ],
    type: "Brewery Tour",
    schedule: [
      {
        attractionId: "attraction-cape-town-22-3",
        dayOfWeek: "Sunday",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-2",
        dayOfWeek: "Monday",
        startTime: "3:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-1",
        dayOfWeek: "Thursday",
        startTime: "11:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 334.8,
    currency: "ZAR",
    maxGroupSize: 34,
    minGroupSize: 14,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 103,
    included: [
      "Headsets to hear the guide",
      "Souvenir photos",
      "Rain ponchos (if needed)",
    ],
    notIncluded: [
      "Gratuities",
      "Parking fees",
    ],
    requirements: [
      "No pets allowed",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4.9,
  },
  {
    id: "tour-cape-town-5",
    guideId: "guide-cape-town-12",
    title: "Market & Mall Tour",
    description: "Uncover the secrets of cape-town on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "cape-town",
    country: "South Africa",
    region: "Africa",
    languagesOffered: [
      "English",
    ],
    price: "R334.8",
    tags: [
      "Culture",
      "Volunteer",
    ],
    type: "Shopping Tour",
    schedule: [
      {
        attractionId: "attraction-cape-town-22-3",
        dayOfWeek: "Sunday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-1",
        dayOfWeek: "Saturday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-2",
        dayOfWeek: "Monday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 334.8,
    currency: "ZAR",
    maxGroupSize: 26,
    minGroupSize: 10,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 103,
    included: [
      "Entrance fees (if applicable)",
      "Rain ponchos (if needed)",
      "Hotel pickup and drop-off",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Gratuities",
      "Travel insurance",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Face masks required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.2,
  },
  {
    id: "tour-cape-town-6",
    guideId: "guide-cape-town-9",
    title: "Kid-Friendly Exploration",
    description: "Discover the best of cape-town on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "cape-town",
    country: "South Africa",
    region: "Africa",
    languagesOffered: [
      "English",
      "Xhosa",
    ],
    price: "R1078.8",
    tags: [
      "Family",
      "Religious",
      "Nature & Wildlife",
    ],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-cape-town-22-3",
        dayOfWeek: "Tuesday",
        startTime: "2:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-2",
        dayOfWeek: "Thursday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-cape-town-22-1",
        dayOfWeek: "Friday",
        startTime: "4:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 1078.8,
    currency: "ZAR",
    maxGroupSize: 48,
    minGroupSize: 14,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 32,
    included: [
      "Souvenir photos",
      "Food samples",
      "Bottled water",
      "Entrance fees (if applicable)",
      "Gratuities",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Parking fees",
    ],
    requirements: [
      "Advanced fitness level required",
      "No flash photography",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.8,
  },
];
