import { Tour } from "@/lib/interfaces/services/tours";

export const charlestonunitedStateseastCoastUsaTours: Tour[] = [
  {
    id: "tour-charleston-1",
    guideId: "guide-charleston-1",
    title: "Charleston Wine Tasting Experience",
    description: "Discover the best of charleston on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "charleston",
    country: "United States",
    region: "East Coast USA",
    languagesOffered: ["English"],
    durationInHours: 3,
    price: "A$110",
    tags: ["Educational", "Nature & Wildlife", "Wellness", "Local Life"],
    type: "Relocation Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "11:00",
        endTime: "17:00",
      }
    ],
    pricePerPerson: 110,
    currency: "AUD",
    maxGroupSize: 17,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 14,
    included: ["Lunch", "Headsets to hear the guide", "Souvenir photos", "Wine tasting", "Hotel pickup and drop-off", "Gratuities", "Recipe booklet"],
    notIncluded: ["Transportation to/from attractions", "Travel insurance", "Personal expenses"],
    requirements: ["Cash only", "Valid ID required", "Credit/debit cards accepted", "Headphones provided"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.6,
  },
  {
    id: "tour-charleston-2",
    guideId: "guide-charleston-2",
    title: "Charleston Art Galleries Crawl",
    description: "Discover the best of charleston on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "charleston",
    country: "United States",
    region: "East Coast USA",
    languagesOffered: ["English"],
    durationInHours: 1,
    price: "C$117",
    tags: ["Culture", "Food & Drink", "Music"],
    type: "Wine Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "11:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "15:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 117,
    currency: "CAD",
    maxGroupSize: 7,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 13,
    included: ["Gratuities", "Entry/Admission tickets", "Souvenir photos", "Guided commentary"],
    notIncluded: ["Food and drinks", "Personal expenses", "Souvenir photos"],
    requirements: ["Stairs involved", "Weather-appropriate clothing", "Arrive 15 minutes early"],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4,
  },
  {
    id: "tour-charleston-3",
    guideId: "guide-charleston-2",
    title: "Charleston Sunset Landmarks Tour",
    description: "Discover the best of charleston on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "charleston",
    country: "United States",
    region: "East Coast USA",
    languagesOffered: ["English"],
    durationInHours: 2,
    price: "£74",
    tags: ["Music", "Culture", "Street Food", "Beach"],
    type: "Wine Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "09:00",
        endTime: "11:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "12:00",
        endTime: "15:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "13:00",
        endTime: "14:00",
      }
    ],
    pricePerPerson: 74,
    currency: "GBP",
    maxGroupSize: 7,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 21,
    included: ["Cooking demonstration", "Local taxes", "Use of helmet"],
    notIncluded: ["Food and drinks", "Gratuities", "Luggage storage"],
    requirements: ["Advanced fitness level required", "No flash photography", "Government-issued ID for entry"],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 3.9,
  },
  {
    id: "tour-charleston-4",
    guideId: "guide-charleston-1",
    title: "Charleston Ghost Stories Walk",
    description: "Immerse yourself in the local culture of charleston with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "charleston",
    country: "United States",
    region: "East Coast USA",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 3,
    price: "£72",
    tags: ["Food & Drink", "Sports", "Family"],
    type: "Craft Workshop",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "16:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "12:00",
        endTime: "20:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "16:00",
        endTime: "21:00",
      }
    ],
    pricePerPerson: 72,
    currency: "GBP",
    maxGroupSize: 16,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 88,
    included: ["WiFi on board", "Guided commentary", "Entrance fees", "Local taxes"],
    notIncluded: ["Transportation to/from attractions", "Alcoholic drinks", "Hotel pickup and drop-off"],
    requirements: ["Parental consent required", "Local SIM card recommended"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.5,
  },
  {
    id: "tour-charleston-5",
    guideId: "guide-charleston-1",
    title: "Charleston Sunset Landmarks Tour",
    description: "Discover the best of charleston on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "charleston",
    country: "United States",
    region: "East Coast USA",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 1.5,
    price: "C$168",
    tags: ["Beach", "Religious"],
    type: "Boat Tour",
    schedule: [
      {
        dayOfWeek: "Monday",
        startTime: "13:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 168,
    currency: "CAD",
    maxGroupSize: 5,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 62,
    included: ["Audio guide", "Rain ponchos", "Entry/Admission tickets", "Local taxes", "Headsets to hear the guide"],
    notIncluded: ["Additional entrance fees", "Hotel pickup and drop-off"],
    requirements: ["COVID-19 vaccination required"],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.7,
  },
  {
    id: "tour-charleston-6",
    guideId: "guide-charleston-1",
    title: "Charleston Religious Sites Pilgrimage",
    description: "Journey through the history of charleston on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "charleston",
    country: "United States",
    region: "East Coast USA",
    languagesOffered: ["English", "Mandarin"],
    durationInHours: 10,
    price: "€41",
    tags: ["Wellness", "Art", "Food & Drink", "Religious"],
    type: "Family-Friendly Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "16:00",
        endTime: "21:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "17:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "12:00",
        endTime: "14:00",
      }
    ],
    pricePerPerson: 41,
    currency: "EUR",
    maxGroupSize: 5,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 77,
    included: ["Entry/Admission tickets", "Entrance fees", "Use of helmet", "WiFi on board", "Guided commentary", "Headsets to hear the guide"],
    notIncluded: ["Transportation to/from attractions", "Souvenir photos"],
    requirements: ["Minimum age: 12", "Signed waiver required", "Face masks required"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 3.9,
  },
  {
    id: "tour-charleston-7",
    guideId: "guide-charleston-7",
    title: "Charleston Essential City Highlights",
    description: "Journey through the history of charleston on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "charleston",
    country: "United States",
    region: "East Coast USA",
    languagesOffered: ["English"],
    durationInHours: 3,
    price: "C$70",
    tags: ["Off the Beaten Path", "Adventure"],
    type: "Religious Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "09:00",
        endTime: "11:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "13:00",
        endTime: "21:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "14:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "14:00",
        endTime: "20:00",
      }
    ],
    pricePerPerson: 70,
    currency: "CAD",
    maxGroupSize: 11,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 74,
    included: ["Food samples", "Lunch", "Rain ponchos", "Skip-the-line access", "Entry/Admission tickets", "Cooking demonstration"],
    notIncluded: ["Gratuities", "Transportation to/from attractions"],
    requirements: ["Weather-appropriate clothing", "No flash photography", "Dress code enforced", "Not wheelchair accessible"],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4.9,
  }
];
