import { Tour } from "@/lib/interfaces/services/tours";

export const dubaiunitedArabEmiratesmiddleEastTours: Tour[] = [
  {
    id: "tour-dubai-1",
    guideId: "guide-dubai-2",
    title: "dubai Ghost Stories Walk",
    description:
      "Journey through the history of dubai on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    languagesOffered: ["English", "French"],
    durationInHours: 6,
    price: "$33",
    tags: ["Street Food", "Local Market", "Religious", "Nightlife"],
    type: "Scenic Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "14:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "14:00",
        endTime: "15:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "10:00",
        endTime: "11:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "14:00",
        endTime: "22:00",
      },
    ],
    pricePerPerson: 33,
    currency: "USD",
    maxGroupSize: 12,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 97,
    included: [
      "Food samples",
      "Transportation during tour",
      "Skip-the-line access",
      "Coffee and/or Tea",
      "Welcome drink",
    ],
    notIncluded: [
      "Personal expenses",
      "Gratuities",
      "Alcoholic drinks",
      "Travel insurance",
    ],
    requirements: [
      "No pets allowed",
      "Tickets must be printed",
      "Service animals permitted",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.1,
  },
  {
    id: "tour-dubai-2",
    guideId: "guide-dubai-4",
    title: "dubai Off-the-Beaten-Path Adventure",
    description:
      "Uncover the secrets of dubai on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    languagesOffered: ["English"],
    durationInHours: 10,
    price: "£93",
    tags: ["Luxury", "Solo", "Nightlife", "Festival"],
    type: "Luxury Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "11:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "16:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "08:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "14:00",
        endTime: "23:00",
      },
    ],
    pricePerPerson: 93,
    currency: "GBP",
    maxGroupSize: 9,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 35,
    included: [
      "Use of bicycle",
      "Wine tasting",
      "Welcome drink",
      "Live entertainment",
      "Professional guide",
    ],
    notIncluded: ["Luggage storage", "Souvenir photos"],
    requirements: [
      "Local SIM card recommended",
      "Bring water and snacks",
      "Basic fitness level required",
      "Credit/debit cards accepted",
    ],
    cancellationPolicy:
      "Group bookings: Free cancellation up to 7 days in advance",
    rating: 3.8,
  },
  {
    id: "tour-dubai-3",
    guideId: "guide-dubai-1",
    title: "dubai Hidden Gems Discovery",
    description:
      "Explore the vibrant streets of dubai with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 5,
    price: "C$89",
    tags: ["Scenic", "Eco", "Festival"],
    type: "Ghost Tour",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "13:00",
        endTime: "16:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "10:00",
        endTime: "12:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "11:00",
        endTime: "12:30",
      },
    ],
    pricePerPerson: 89,
    currency: "CAD",
    maxGroupSize: 19,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 20,
    included: [
      "Lunch",
      "Local taxes",
      "Entry/Admission tickets",
      "Rain ponchos",
      "Cooking demonstration",
      "Coffee and/or Tea",
    ],
    notIncluded: ["Travel insurance", "Gratuities"],
    requirements: ["Advanced fitness level required", "Wheelchair accessible"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.2,
  },
  {
    id: "tour-dubai-4",
    guideId: "guide-dubai-1",
    title: "dubai Nightlife Exploration",
    description:
      "Immerse yourself in the local culture of dubai with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 12,
    price: "£160",
    tags: ["Nightlife", "Shopping", "Historical"],
    type: "Wildlife Safari",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "14:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "16:00",
        endTime: "21:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "16:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "16:00",
        endTime: "18:00",
      },
    ],
    pricePerPerson: 160,
    currency: "GBP",
    maxGroupSize: 19,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 80,
    included: [
      "Wine tasting",
      "Use of helmet",
      "Headsets to hear the guide",
      "Entry/Admission tickets",
    ],
    notIncluded: [
      "Luggage storage",
      "Transportation to/from attractions",
      "Travel insurance",
    ],
    requirements: [
      "No mobility restrictions",
      "No pets allowed",
      "Signed waiver required",
    ],
    cancellationPolicy:
      "Free cancellation up to 48 hours before the experience starts",
    rating: 3.7,
  },
  {
    id: "tour-dubai-5",
    guideId: "guide-dubai-4",
    title: "dubai Luxury Shopping Experience",
    description:
      "Explore the vibrant streets of dubai with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 8,
    price: "A$33",
    tags: ["Hiking"],
    type: "Market Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "10:00",
        endTime: "22:00",
      },
    ],
    pricePerPerson: 33,
    currency: "AUD",
    maxGroupSize: 16,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 88,
    included: [
      "Gratuities",
      "Professional guide",
      "Food samples",
      "Transportation during tour",
    ],
    notIncluded: [
      "Transportation to/from attractions",
      "Hotel pickup and drop-off",
      "Luggage storage",
    ],
    requirements: [
      "Wheelchair accessible",
      "Valid ID required",
      "All ages welcome",
      "Swimming required",
    ],
    cancellationPolicy:
      "Free cancellation up to 48 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-dubai-6",
    guideId: "guide-dubai-1",
    title: "dubai Scenic Views Tour",
    description:
      "Journey through the history of dubai on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    languagesOffered: ["English", "Italian"],
    durationInHours: 3,
    price: "£103",
    tags: ["Eco", "LGBTQ+ Friendly"],
    type: "Audio Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "08:00",
        endTime: "16:00",
      },
    ],
    pricePerPerson: 103,
    currency: "GBP",
    maxGroupSize: 13,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 6,
    included: [
      "Use of helmet",
      "Audio guide",
      "Bottled water",
      "Live entertainment",
      "WiFi on board",
      "Recipe booklet",
      "Lunch",
    ],
    notIncluded: [
      "Additional entrance fees",
      "Personal expenses",
      "Travel insurance",
      "Souvenir photos",
    ],
    requirements: [
      "Signed waiver required",
      "No pets allowed",
      "Bring own headphones",
    ],
    cancellationPolicy:
      "Free cancellation up to 72 hours before the experience starts",
    rating: 4.2,
  },
];
