// Auto-generated file for dublin tours
// Country: Ireland, Region: Ireland

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const dublinirelandirelandTours: Tour[] = [
  {
    id: "tour-dublin-1",
    guideId: "guide-dublin-2",
    title: "All Aboard: Family Rail Adventure",
    description: "Uncover the secrets of dublin on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "dublin",
    country: "Ireland",
    region: "Ireland",
    languagesOffered: [
      "English",
    ],
    price: "€140",
    tags: [
      "Family Friendly",
      "Art And Culture",
      "Nature And Scenic",
      "Adventure And Thrill",
    ],
    type: "Romantic Tour",
    schedule: [
      {
        attractionId: "attraction-dublin-26-2",
        dayOfWeek: "Thursday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-dublin-26-1",
        dayOfWeek: "Monday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 140,
    currency: "EUR",
    maxGroupSize: 26,
    minGroupSize: 7,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 43,
    included: [
      "Snacks",
      "Souvenir photos",
      "Rain ponchos (if needed)",
      "Local taxes",
      "Food samples",
    ],
    notIncluded: [
      "Hotel accommodations",
      "Travel insurance",
    ],
    requirements: [
      "Swimming required",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.1,
  },
  {
    id: "tour-dublin-2",
    guideId: "guide-dublin-6",
    title: "The Summit Seekers Journey",
    description: "Explore the vibrant streets of dublin with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "dublin",
    country: "Ireland",
    region: "Ireland",
    languagesOffered: [
      "English",
    ],
    price: "€165",
    tags: [
      "Nightlife And Entertainment",
      "Adventure And Thrill",
    ],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-dublin-26-3",
        dayOfWeek: "Tuesday",
        startTime: "1:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-dublin-26-2",
        dayOfWeek: "Wednesday",
        startTime: "5:00 PM",
        endTime: "9:00 PM",
      },
    ],
    pricePerPerson: 165,
    currency: "EUR",
    maxGroupSize: 29,
    minGroupSize: 14,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 20,
    included: [
      "Rain ponchos (if needed)",
      "Transportation during tour (if applicable)",
      "Souvenir photos",
      "Hotel pickup and drop-off",
      "Coffee and/or Tea",
      "Entrance fees (if applicable)",
    ],
    notIncluded: [
      "Hotel accommodations",
      "Airport transfers",
      "Parking fees",
    ],
    requirements: [
      "Basic fitness level required",
      "Face masks required",
      "Arrive 15 minutes early",
      "Signed waiver required",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.6,
  },
  {
    id: "tour-dublin-3",
    guideId: "guide-dublin-1",
    title: "Beyond the Map: Off-Grid Escapes",
    description: "Explore the vibrant streets of dublin with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "dublin",
    country: "Ireland",
    region: "Ireland",
    languagesOffered: [
      "English",
    ],
    price: "€100",
    tags: [
      "Adventure And Thrill",
      "Culinary And Food",
      "Nature And Scenic",
    ],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-dublin-26-2",
        dayOfWeek: "Friday",
        startTime: "12:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-dublin-26-3",
        dayOfWeek: "Saturday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-dublin-26-1",
        dayOfWeek: "Sunday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 100,
    currency: "EUR",
    maxGroupSize: 23,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 44,
    included: [
      "Local taxes",
      "Snacks",
      "Gratuities",
      "Souvenir photos",
    ],
    notIncluded: [
      "Airport transfers",
      "Food and drinks at restaurants and/or cafes",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Tickets must be printed",
      "Face masks required",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.6,
  },
  {
    id: "tour-dublin-4",
    guideId: "guide-dublin-2",
    title: "Lakeside Legends & Campfire Nights",
    description: "Immerse yourself in the local culture of dublin with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "dublin",
    country: "Ireland",
    region: "Ireland",
    languagesOffered: [
      "English",
    ],
    price: "€96",
    tags: [
      "Family Friendly",
      "Nature And Scenic",
    ],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-dublin-26-3",
        dayOfWeek: "Sunday",
        startTime: "11:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-dublin-26-2",
        dayOfWeek: "Wednesday",
        startTime: "8:00 AM",
        endTime: "10:00 AM",
      },
    ],
    pricePerPerson: 96,
    currency: "EUR",
    maxGroupSize: 22,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 23,
    included: [
      "Snacks",
      "Transportation during tour (if applicable)",
      "Entrance fees (if applicable)",
    ],
    notIncluded: [
      "Airport transfers",
      "Parking fees",
    ],
    requirements: [
      "Swimming required",
      "Minimum age: 18",
      "Basic fitness level required",
      "Valid ID required",
    ],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.6,
  },
];
