// Auto-generated file for dubrovnik tours
// Country: Croatia, Region: Croatian Coast

// This file is auto-generated. Do not edit manually.
// Generated on: 2025-06-08T04:09:38.399Z

import { Tour } from "@/lib/interfaces/services/tours";

export const dubrovnikcroatiacroatianCoastTours: Tour[] = [
  {
    id: "tour-dubrovnik-1",
    guideId: "guide-dubrovnik-5",
    title: "Boulevards and Backstories",
    description: "Uncover the secrets of dubrovnik on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Croatian Coast",
    languagesOffered: [],
    price: "€152",
    tags: [
      "City Highlights And History",
      "Adventure And Thrill",
      "Nature And Scenic",
    ],
    type: "Food Tour",
    schedule: [
      {
        attractionId: "attraction-dubrovnik-12-4",
        dayOfWeek: "Friday",
        startTime: "11:00 AM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 152,
    currency: "EUR",
    maxGroupSize: 46,
    minGroupSize: 14,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 95,
    included: [
      "Headsets to hear the guide",
      "Snacks",
      "Souvenir photos",
    ],
    notIncluded: [
      "Gratuities",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Minimum age: 18",
      "Advanced fitness level required",
    ],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.1,
  },
  {
    id: "tour-dubrovnik-2",
    guideId: "guide-dubrovnik-6",
    title: "Gourmet Food Walk",
    description: "Explore the vibrant streets of dubrovnik with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Croatian Coast",
    languagesOffered: [],
    price: "€151",
    tags: [
      "Culinary And Food",
      "Nightlife And Entertainment",
      "Family Friendly",
    ],
    type: "Historical Tour",
    schedule: [
      {
        attractionId: "attraction-dubrovnik-12-3",
        dayOfWeek: "Monday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 151,
    currency: "EUR",
    maxGroupSize: 39,
    minGroupSize: 5,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 71,
    included: [
      "Transportation during tour (if applicable)",
      "Bottled water",
      "Food samples",
    ],
    notIncluded: [
      "Airport transfers",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "Valid ID required",
      "Cash only",
      "Signed waiver required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.2,
  },
  {
    id: "tour-dubrovnik-3",
    guideId: "guide-dubrovnik-5",
    title: "Temples, Thrones & Timelines",
    description: "Journey through the history of dubrovnik on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Croatian Coast",
    languagesOffered: [
      "Croatian",
    ],
    price: "€166",
    tags: [
      "Nature And Scenic",
      "Poetic And Whimsical",
    ],
    type: "Religious Tours",
    schedule: [
      {
        attractionId: "attraction-dubrovnik-12-4",
        dayOfWeek: "Saturday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-dubrovnik-12-1",
        dayOfWeek: "Wednesday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 166,
    currency: "EUR",
    maxGroupSize: 39,
    minGroupSize: 5,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 53,
    included: [
      "Food samples",
      "Coffee and/or Tea",
      "Headsets to hear the guide",
      "Bottled water",
      "Local taxes",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Parking fees",
    ],
    requirements: [
      "Valid ID required",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 4.9,
  },
  {
    id: "tour-dubrovnik-4",
    guideId: "guide-dubrovnik-7",
    title: "Secret Recipe Exploration",
    description: "Explore the vibrant streets of dubrovnik with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Croatian Coast",
    languagesOffered: [
      "Croatian",
    ],
    price: "€60",
    tags: [
      "Culinary And Food",
      "Nightlife And Entertainment",
    ],
    type: "Mystery Tours",
    schedule: [
      {
        attractionId: "attraction-dubrovnik-12-1",
        dayOfWeek: "Tuesday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-dubrovnik-12-2",
        dayOfWeek: "Saturday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-dubrovnik-12-4",
        dayOfWeek: "Thursday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 60,
    currency: "EUR",
    maxGroupSize: 31,
    minGroupSize: 5,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 80,
    included: [
      "Souvenir photos",
      "Headsets to hear the guide",
      "Hotel pickup and drop-off",
      "Snacks",
    ],
    notIncluded: [
      "Hotel accommodations",
      "Parking fees",
    ],
    requirements: [
      "Government-issued ID for entry",
      "Minimum age: 12",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 5,
  },
  {
    id: "tour-dubrovnik-5",
    guideId: "guide-dubrovnik-3",
    title: "Crater Lakes & Cloud Forests",
    description: "Discover the best of dubrovnik on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Croatian Coast",
    languagesOffered: [],
    price: "€164",
    tags: [
      "Nature And Scenic",
    ],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-dubrovnik-12-4",
        dayOfWeek: "Wednesday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-dubrovnik-12-3",
        dayOfWeek: "Tuesday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 164,
    currency: "EUR",
    maxGroupSize: 44,
    minGroupSize: 10,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 35,
    included: [
      "Gratuities",
      "Snacks",
      "Food samples",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Hotel accommodations",
      "Food and drinks at restaurants and/or cafes",
      "Transportation to/from the tour start point",
    ],
    requirements: [
      "Service animals permitted",
      "Dress code enforced",
    ],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.7,
  },
];
