import { Tour } from "@/lib/interfaces/services/tours";

export const dubrovnikcroatiamediterraneanTours: Tour[] = [
  {
    id: "tour-dubrovnik-1",
    guideId: "guide-dubrovnik-7",
    title: "dubrovnik Ghost Stories Walk",
    description:
      "Uncover the secrets of dubrovnik on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 5,
    price: "€31",
    tags: ["Luxury", "Sports", "Eco"],
    type: "LGBTQ+ Friendly Tour",
    schedule: [],
    pricePerPerson: 31,
    currency: "EUR",
    maxGroupSize: 17,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 89,
    included: [
      "Rain ponchos",
      "Audio guide",
      "Wine tasting",
      "Souvenir photos",
    ],
    notIncluded: ["Additional entrance fees", "Gratuities"],
    requirements: [
      "No flash photography",
      "All ages welcome",
      "Must be 21+ to consume alcohol",
      "Minimum age: 18",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.2,
  },
  {
    id: "tour-dubrovnik-2",
    guideId: "guide-dubrovnik-5",
    title: "dubrovnik Essential City Highlights",
    description:
      "Uncover the secrets of dubrovnik on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 1,
    price: "C$169",
    tags: ["Adventure"],
    type: "LGBTQ+ Friendly Tour",
    schedule: [],
    pricePerPerson: 169,
    currency: "CAD",
    maxGroupSize: 16,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 97,
    included: [
      "WiFi on board",
      "Wine tasting",
      "Hotel pickup and drop-off",
      "Audio guide",
    ],
    notIncluded: [
      "Hotel pickup and drop-off",
      "Alcoholic drinks",
      "Transportation to/from attractions",
    ],
    requirements: [
      "Arrive 15 minutes early",
      "COVID-19 vaccination required",
      "Tickets must be printed",
    ],
    cancellationPolicy:
      "Free cancellation up to 72 hours before the experience starts",
    rating: 4.7,
  },
  {
    id: "tour-dubrovnik-3",
    guideId: "guide-dubrovnik-7",
    title: "dubrovnik Culinary Delights Experience",
    description:
      "Immerse yourself in the local culture of dubrovnik with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 10,
    price: "A$28",
    tags: ["Cruise Stop", "Wine & Spirits", "Adventure", "Scenic"],
    type: "Self-Guided Tour",
    schedule: [],
    pricePerPerson: 28,
    currency: "AUD",
    maxGroupSize: 14,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 24,
    included: [
      "Entry/Admission tickets",
      "Use of helmet",
      "WiFi on board",
      "Professional guide",
      "Wine tasting",
    ],
    notIncluded: ["Gratuities", "Additional entrance fees"],
    requirements: [
      "Not wheelchair accessible",
      "Minimum age: 12",
      "Bring water and snacks",
      "Credit/debit cards accepted",
    ],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 4.8,
  },
  {
    id: "tour-dubrovnik-4",
    guideId: "guide-dubrovnik-3",
    title: "dubrovnik Religious Sites Pilgrimage",
    description:
      "Discover the best of dubrovnik on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 4,
    price: "£135",
    tags: ["Adventure", "Nature & Wildlife", "Historical"],
    type: "Private Tour",
    schedule: [],
    pricePerPerson: 135,
    currency: "GBP",
    maxGroupSize: 19,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 21,
    included: ["Cooking demonstration", "Wine tasting"],
    notIncluded: [
      "Hotel pickup and drop-off",
      "Personal expenses",
      "Travel insurance",
    ],
    requirements: ["Passport required"],
    cancellationPolicy:
      "Free cancellation up to 48 hours before the experience starts",
    rating: 4.3,
  },
  {
    id: "tour-dubrovnik-5",
    guideId: "guide-dubrovnik-7",
    title: "dubrovnik Architecture Masterpieces Tour",
    description:
      "Immerse yourself in the local culture of dubrovnik with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English", "Italian"],
    durationInHours: 12,
    price: "A$51",
    tags: ["Historical", "Adventure", "Music", "Religious"],
    type: "Boat Tour",
    schedule: [],
    pricePerPerson: 51,
    currency: "AUD",
    maxGroupSize: 5,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 55,
    included: [
      "Guided commentary",
      "Recipe booklet",
      "Transportation during tour",
    ],
    notIncluded: [
      "Travel insurance",
      "Hotel pickup and drop-off",
      "Additional entrance fees",
    ],
    requirements: ["No pets allowed", "Tickets must be printed"],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 4.6,
  },
  {
    id: "tour-dubrovnik-6",
    guideId: "guide-dubrovnik-2",
    title: "dubrovnik Historical Walking Tour",
    description:
      "Journey through the history of dubrovnik on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 8,
    price: "€116",
    tags: ["Off the Beaten Path", "Solo", "Romantic", "Scenic"],
    type: "Photography Tour",
    schedule: [],
    pricePerPerson: 116,
    currency: "EUR",
    maxGroupSize: 19,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 33,
    included: [
      "Recipe booklet",
      "Professional guide",
      "Headsets to hear the guide",
      "Rain ponchos",
    ],
    notIncluded: [
      "Hotel pickup and drop-off",
      "Luggage storage",
      "Travel insurance",
    ],
    requirements: ["No pets allowed", "Basic fitness level required"],
    cancellationPolicy:
      "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.3,
  },
  {
    id: "tour-dubrovnik-7",
    guideId: "guide-dubrovnik-1",
    title: "dubrovnik Urban Legends Tour",
    description:
      "Explore the vibrant streets of dubrovnik with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English", "Italian"],
    durationInHours: 2.5,
    price: "C$20",
    tags: ["Music", "Wellness", "Photography", "Street Food"],
    type: "Religious Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "10:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "09:00",
        endTime: "13:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "13:00",
        endTime: "15:00",
      },
    ],
    pricePerPerson: 20,
    currency: "CAD",
    maxGroupSize: 18,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 59,
    included: [
      "Entrance fees",
      "Food samples",
      "Gratuities",
      "Hotel pickup and drop-off",
      "Local taxes",
    ],
    notIncluded: [
      "Additional entrance fees",
      "Hotel pickup and drop-off",
      "Souvenir photos",
    ],
    requirements: ["Photography allowed"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.3,
  },
  {
    id: "tour-dubrovnik-8",
    guideId: "guide-dubrovnik-4",
    title: "dubrovnik Street Food Adventure",
    description:
      "Uncover the secrets of dubrovnik on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English", "Arabic"],
    durationInHours: 8,
    price: "A$133",
    tags: ["Beach", "Nature & Wildlife", "Architecture"],
    type: "Private Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "10:00",
        endTime: "13:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "14:00",
        endTime: "15:30",
      },
      {
        dayOfWeek: "Monday",
        startTime: "14:00",
        endTime: "20:00",
      },
    ],
    pricePerPerson: 133,
    currency: "AUD",
    maxGroupSize: 9,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 41,
    included: ["Gratuities", "Headsets to hear the guide", "Local taxes"],
    notIncluded: [
      "Hotel pickup and drop-off",
      "Souvenir photos",
      "Travel insurance",
    ],
    requirements: ["Signed waiver required"],
    cancellationPolicy:
      "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.5,
  },
  {
    id: "tour-dubrovnik-9",
    guideId: "guide-dubrovnik-1",
    title: "dubrovnik Cultural Heritage Tour",
    description:
      "Discover the best of dubrovnik on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "dubrovnik",
    country: "Croatia",
    region: "Mediterranean",
    languagesOffered: ["English", "French"],
    durationInHours: 2.5,
    price: "A$98",
    tags: ["Nightlife", "Beach", "Photography"],
    type: "Underground Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "10:00",
        endTime: "12:30",
      },
      {
        dayOfWeek: "Friday",
        startTime: "08:00",
        endTime: "13:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "13:00",
        endTime: "14:30",
      },
      {
        dayOfWeek: "Monday",
        startTime: "11:00",
        endTime: "16:00",
      },
    ],
    pricePerPerson: 98,
    currency: "AUD",
    maxGroupSize: 11,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 22,
    included: [
      "Entrance fees",
      "Guided commentary",
      "Welcome drink",
      "Recipe booklet",
      "Rain ponchos",
      "Professional guide",
    ],
    notIncluded: [
      "Hotel pickup and drop-off",
      "Personal expenses",
      "Gratuities",
    ],
    requirements: ["Minimum age: 12"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.2,
  },
];
