import { Tour } from "@/lib/interfaces/services/tours";

export const florenceitalymediterraneanTours: Tour[] = [
  {
    id: "tour-florence-1",
    guideId: "guide-florence-1",
    title: "florence Off-the-Beaten-Path Adventure",
    description:
      "Journey through the history of florence on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "florence",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 2.5,
    price: "$28",
    tags: ["Spiritual", "Photography"],
    type: "Adventure Tour",
    schedule: [
      {
        dayOfWeek: "Monday",
        startTime: "09:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "11:00",
        endTime: "12:30",
      },
      {
        dayOfWeek: "Friday",
        startTime: "11:00",
        endTime: "13:30",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "08:00",
        endTime: "14:00",
      },
    ],
    pricePerPerson: 28,
    currency: "USD",
    maxGroupSize: 13,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 48,
    included: [
      "Entry/Admission tickets",
      "Snacks",
      "Headsets to hear the guide",
      "Entrance fees",
      "Recipe booklet",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Alcoholic drinks",
      "Transportation to/from attractions",
      "Hotel pickup and drop-off",
      "Gratuities",
    ],
    requirements: [
      "Service animals permitted",
      "E-tickets accepted",
      "Pre-booking required",
    ],
    cancellationPolicy:
      "Free cancellation up to 48 hours before the experience starts",
    rating: 3.8,
  },
  {
    id: "tour-florence-2",
    guideId: "guide-florence-1",
    title: "florence Art Galleries Crawl",
    description:
      "Uncover the secrets of florence on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "florence",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 2,
    price: "A$98",
    tags: ["Shopping", "Scenic", "Nature & Wildlife"],
    type: "Audio Tour",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "13:00",
        endTime: "21:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "16:00",
        endTime: "22:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "13:00",
        endTime: "23:00",
      },
    ],
    pricePerPerson: 98,
    currency: "AUD",
    maxGroupSize: 8,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 59,
    included: [
      "Dinner",
      "Entry/Admission tickets",
      "Hotel pickup and drop-off",
      "WiFi on board",
      "Souvenir photos",
    ],
    notIncluded: ["Gratuities", "Travel insurance", "Souvenir photos"],
    requirements: ["Bring water and snacks"],
    cancellationPolicy:
      "Free cancellation up to 48 hours before the experience starts",
    rating: 4.3,
  },
  {
    id: "tour-florence-3",
    guideId: "guide-florence-4",
    title: "florence Urban Photography Journey",
    description:
      "Immerse yourself in the local culture of florence with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "florence",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 10,
    price: "A$120",
    tags: ["Educational", "Art", "Architecture", "Eco"],
    type: "Group Tour",
    schedule: [
      {
        dayOfWeek: "Thursday",
        startTime: "12:00",
        endTime: "13:30",
      },
    ],
    pricePerPerson: 120,
    currency: "AUD",
    maxGroupSize: 13,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 57,
    included: [
      "Snacks",
      "Headsets to hear the guide",
      "Gratuities",
      "Audio guide",
      "Dinner",
      "Guided commentary",
    ],
    notIncluded: ["Additional entrance fees", "Food and drinks"],
    requirements: [
      "Local SIM card recommended",
      "Swimming required",
      "Bring water and snacks",
      "Advanced fitness level required",
    ],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 3.7,
  },
  {
    id: "tour-florence-4",
    guideId: "guide-florence-1",
    title: "florence Architecture Masterpieces Tour",
    description:
      "Uncover the secrets of florence on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "florence",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 12,
    price: "¥155",
    tags: ["Family", "Off the Beaten Path", "Art"],
    type: "Street Art Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "11:00",
        endTime: "19:00",
      },
    ],
    pricePerPerson: 155,
    currency: "JPY",
    maxGroupSize: 12,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 67,
    included: [
      "Welcome drink",
      "Gratuities",
      "Coffee and/or Tea",
      "Wine tasting",
    ],
    notIncluded: [
      "Alcoholic drinks",
      "Souvenir photos",
      "Transportation to/from attractions",
      "Gratuities",
    ],
    requirements: [
      "Headphones provided",
      "Tickets must be printed",
      "Signed waiver required",
    ],
    cancellationPolicy:
      "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.4,
  },
  {
    id: "tour-florence-5",
    guideId: "guide-florence-1",
    title: "florence Essential City Highlights",
    description:
      "Uncover the secrets of florence on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "florence",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English", "Arabic"],
    durationInHours: 1.5,
    price: "£123",
    tags: ["Architecture", "Cruise Stop", "Scenic", "Educational"],
    type: "Scenic Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "10:00",
        endTime: "11:00",
      },
    ],
    pricePerPerson: 123,
    currency: "GBP",
    maxGroupSize: 8,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 74,
    included: [
      "Live entertainment",
      "Welcome drink",
      "Bottled water",
      "Gratuities",
      "Guided commentary",
      "Professional guide",
    ],
    notIncluded: [
      "Transportation to/from attractions",
      "Gratuities",
      "Alcoholic drinks",
    ],
    requirements: ["Minimum age: 18", "Photography allowed", "No pets allowed"],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 4.9,
  },
  {
    id: "tour-florence-6",
    guideId: "guide-florence-2",
    title: "florence Underground Secrets Tour",
    description:
      "Uncover the secrets of florence on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "florence",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 2,
    price: "C$125",
    tags: ["Shopping", "Local Market", "Cruise Stop", "Luxury"],
    type: "Craft Workshop",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "17:00",
        endTime: "20:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "15:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "08:00",
        endTime: "13:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "09:00",
        endTime: "13:00",
      },
    ],
    pricePerPerson: 125,
    currency: "CAD",
    maxGroupSize: 16,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 55,
    included: ["Recipe booklet", "Use of bicycle", "Coffee and/or Tea"],
    notIncluded: ["Food and drinks", "Travel insurance", "Personal expenses"],
    requirements: ["Headphones provided"],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.4,
  },
];
