import { Tour } from "@/lib/interfaces/services/tours";

export const fortLauderdaleunitedStatescaribbeanTours: Tour[] = [
  {
    id: "tour-fort-lauderdale-1",
    guideId: "guide-fort-lauderdale-6",
    title: "Fort Lauderdale Nature Escape",
    description: "Uncover the secrets of fort-lauderdale on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "fort-lauderdale",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 1.5,
    price: "A$71",
    tags: ["Wine & Spirits", "Nature & Wildlife", "Nightlife"],
    type: "Historical Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "16:00",
        endTime: "18:30",
      }
    ],
    pricePerPerson: 71,
    currency: "AUD",
    maxGroupSize: 8,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 16,
    included: ["Professional guide", "Rain ponchos", "Snacks"],
    notIncluded: ["Alcoholic drinks", "Additional entrance fees"],
    requirements: ["Tickets must be printed", "Advanced fitness level required", "COVID-19 vaccination required"],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.3,
  },
  {
    id: "tour-fort-lauderdale-2",
    guideId: "guide-fort-lauderdale-4",
    title: "Fort Lauderdale Scenic Views Tour",
    description: "Discover the best of fort-lauderdale on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "fort-lauderdale",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 8,
    price: "$140",
    tags: ["Scenic", "Hiking"],
    type: "Relocation Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "10:00",
        endTime: "13:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "16:00",
        endTime: "17:30",
      },
      {
        dayOfWeek: "Monday",
        startTime: "16:00",
        endTime: "22:00",
      }
    ],
    pricePerPerson: 140,
    currency: "USD",
    maxGroupSize: 19,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 5,
    included: ["Food samples", "Bottled water", "Rain ponchos", "Hotel pickup and drop-off", "Audio guide"],
    notIncluded: ["Luggage storage", "Food and drinks", "Transportation to/from attractions", "Gratuities"],
    requirements: ["Minimum age: 12"],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.3,
  },
  {
    id: "tour-fort-lauderdale-3",
    guideId: "guide-fort-lauderdale-5",
    title: "Fort Lauderdale Art Galleries Crawl",
    description: "Journey through the history of fort-lauderdale on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "fort-lauderdale",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English", "Mandarin"],
    durationInHours: 10,
    price: "$98",
    tags: ["Solo", "Educational", "Architecture"],
    type: "Craft Workshop",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "09:00",
        endTime: "11:30",
      }
    ],
    pricePerPerson: 98,
    currency: "USD",
    maxGroupSize: 11,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 52,
    included: ["Use of helmet", "Snacks", "Skip-the-line access", "Welcome drink", "Lunch"],
    notIncluded: ["Transportation to/from attractions", "Hotel pickup and drop-off", "Personal expenses", "Food and drinks"],
    requirements: ["COVID-19 vaccination required", "Photography allowed"],
    cancellationPolicy: "Free cancellation up to 72 hours before the experience starts",
    rating: 5,
  },
  {
    id: "tour-fort-lauderdale-4",
    guideId: "guide-fort-lauderdale-3",
    title: "Fort Lauderdale Religious Sites Pilgrimage",
    description: "Immerse yourself in the local culture of fort-lauderdale with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "fort-lauderdale",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English", "Mandarin"],
    durationInHours: 4,
    price: "£96",
    tags: ["Off the Beaten Path", "Solo"],
    type: "Street Art Tour",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "09:00",
        endTime: "17:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "16:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "17:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "09:00",
        endTime: "10:00",
      }
    ],
    pricePerPerson: 96,
    currency: "GBP",
    maxGroupSize: 8,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 80,
    included: ["Lunch", "Coffee and/or Tea", "Dinner"],
    notIncluded: ["Hotel pickup and drop-off", "Transportation to/from attractions"],
    requirements: ["Service animals permitted"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.6,
  }
];
