// Auto-generated file for galveston tours
// Country: United States, Region: Texas

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const galvestonunitedStatestexasTours: Tour[] = [
  {
    id: "tour-galveston-1",
    guideId: "guide-galveston-4",
    title: "Wonders for All Ages",
    description: "Explore the vibrant streets of galveston with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "galveston",
    country: "United States",
    region: "Texas",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$182",
    tags: [
      "Family Friendly",
      "Art And Culture",
    ],
    type: "Cultural Tour",
    schedule: [
      {
        attractionId: "attraction-galveston-57-1",
        dayOfWeek: "Thursday",
        startTime: "10:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-3",
        dayOfWeek: "Wednesday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-2",
        dayOfWeek: "Saturday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
    ],
    pricePerPerson: 182,
    currency: "USD",
    maxGroupSize: 45,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 23,
    included: [
      "Gratuities",
      "Rain ponchos (if needed)",
      "Transportation during tour (if applicable)",
      "Bottled water",
    ],
    notIncluded: [
      "Airport transfers",
      "Transportation to/from the tour start point",
      "Additional tickets for attractions",
    ],
    requirements: [
      "COVID-19 vaccination required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.5,
  },
  {
    id: "tour-galveston-2",
    guideId: "guide-galveston-2",
    title: "Food and Culture Fusion",
    description: "Immerse yourself in the local culture of galveston with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "galveston",
    country: "United States",
    region: "Texas",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$80",
    tags: [
      "Culinary And Food",
      "Nature And Scenic",
      "Poetic And Whimsical",
    ],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-galveston-57-1",
        dayOfWeek: "Thursday",
        startTime: "1:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-3",
        dayOfWeek: "Sunday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-2",
        dayOfWeek: "Monday",
        startTime: "4:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 80,
    currency: "USD",
    maxGroupSize: 22,
    minGroupSize: 9,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 67,
    included: [
      "Snacks",
      "Bottled water",
      "Food samples",
      "Hotel pickup and drop-off",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Airport transfers",
      "Parking fees",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Bring own headphones",
      "COVID-19 vaccination required",
      "Basic fitness level required",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 24-hour notice",
    rating: 4.6,
  },
  {
    id: "tour-galveston-3",
    guideId: "guide-galveston-4",
    title: "Natural Wonders Walk",
    description: "Journey through the history of galveston on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "galveston",
    country: "United States",
    region: "Texas",
    languagesOffered: [
      "English",
    ],
    price: "$118",
    tags: [
      "Nature And Scenic",
      "City Highlights And History",
      "Culinary And Food",
    ],
    type: "Family Tours",
    schedule: [
      {
        attractionId: "attraction-galveston-57-2",
        dayOfWeek: "Thursday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-1",
        dayOfWeek: "Friday",
        startTime: "5:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-3",
        dayOfWeek: "Saturday",
        startTime: "11:00 AM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 118,
    currency: "USD",
    maxGroupSize: 42,
    minGroupSize: 11,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 5,
    included: [
      "Transportation during tour (if applicable)",
      "Coffee and/or Tea",
    ],
    notIncluded: [
      "Airport transfers",
      "Optional activities not included in the tour",
      "Gratuities",
    ],
    requirements: [
      "Not wheelchair accessible",
    ],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.7,
  },
  {
    id: "tour-galveston-4",
    guideId: "guide-galveston-3",
    title: "Oceanfront Odyssey for Families",
    description: "Uncover the secrets of galveston on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "galveston",
    country: "United States",
    region: "Texas",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$110",
    tags: [
      "Nature And Scenic",
      "City Highlights And History",
    ],
    type: "Family Tours",
    schedule: [
      {
        attractionId: "attraction-galveston-57-1",
        dayOfWeek: "Monday",
        startTime: "10:00 AM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-3",
        dayOfWeek: "Tuesday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-2",
        dayOfWeek: "Wednesday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 110,
    currency: "USD",
    maxGroupSize: 48,
    minGroupSize: 7,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 94,
    included: [
      "Rain ponchos (if needed)",
      "Local taxes",
      "Food samples",
      "Entrance fees (if applicable)",
      "Snacks",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Airport transfers",
      "Food and drinks at restaurants and/or cafes",
    ],
    requirements: [
      "Minimum age: 12",
      "Cash only",
      "Passport required",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.1,
  },
  {
    id: "tour-galveston-5",
    guideId: "guide-galveston-1",
    title: "Starlight Streets: The Night Walk",
    description: "Explore the vibrant streets of galveston with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "galveston",
    country: "United States",
    region: "Texas",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$129",
    tags: [
      "Nightlife And Entertainment",
      "Family Friendly",
      "City Highlights And History",
    ],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-galveston-57-3",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-galveston-57-2",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
    ],
    pricePerPerson: 129,
    currency: "USD",
    maxGroupSize: 29,
    minGroupSize: 6,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 52,
    included: [
      "Local taxes",
      "Headsets to hear the guide",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Parking fees",
    ],
    requirements: [
      "Arrive 15 minutes early",
      "No flash photography",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 4.7,
  },
];
