import { Tour } from "@/lib/interfaces/services/tours";

export const georgeTowncaymanIslandscaribbeanTours: Tour[] = [
  {
    id: "tour-george-town-1",
    guideId: "guide-george-town-1",
    title: "Historical Significance Tour",
    description:
      "Journey through the history of george-town on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "george-town",
    country: "Cayman Islands",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 5,
    price: "€154",
    tags: ["Historical", "Adventure"],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-george-town-55-2",
        dayOfWeek: "Tuesday",
        startTime: "9:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 154,
    currency: "EUR",
    maxGroupSize: 5,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 37,
    included: [
      "Bottled water",
      "Entrance fees",
      "Snacks",
      "Transportation during tour",
      "Use of helmet",
      "Professional guide",
      "Headsets to hear the guide",
    ],
    notIncluded: [
      "Additional entrance fees",
      "Gratuities",
      "Alcoholic drinks",
      "Souvenir photos",
    ],
    requirements: ["Face masks required"],
    cancellationPolicy:
      "Free cancellation up to 48 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-george-town-2",
    guideId: "guide-george-town-3",
    title: "Local Street Eats Tour",
    description:
      "Journey through the history of george-town on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "george-town",
    country: "Cayman Islands",
    region: "Caribbean",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 1,
    price: "A$131",
    tags: ["Street Food", "Festival"],
    type: "LGBTQ+ Friendly Tour",
    schedule: [
      {
        attractionId: "attraction-george-town-55-1",
        dayOfWeek: "Tuesday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 131,
    currency: "AUD",
    maxGroupSize: 12,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 86,
    included: [
      "Recipe booklet",
      "WiFi on board",
      "Local taxes",
      "Food samples",
      "Wine tasting",
      "Souvenir photos",
    ],
    notIncluded: ["Gratuities", "Luggage storage", "Souvenir photos"],
    requirements: ["Must be 21+ to consume alcohol"],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-george-town-3",
    guideId: "guide-george-town-7",
    title: "Environmental Learning Tour",
    description:
      "Discover the best of george-town on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "george-town",
    country: "Cayman Islands",
    region: "Caribbean",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 12,
    price: "$92",
    tags: ["Eco", "Hiking"],
    type: "Audio Tour",
    schedule: [
      {
        attractionId: "attraction-george-town-55-3",
        dayOfWeek: "Friday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 92,
    currency: "USD",
    maxGroupSize: 11,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 66,
    included: ["Entrance fees", "Hotel pickup and drop-off", "Gratuities"],
    notIncluded: [
      "Food and drinks",
      "Alcoholic drinks",
      "Transportation to/from attractions",
      "Hotel pickup and drop-off",
    ],
    requirements: [
      "Swimming required",
      "Photography allowed",
      "Valid ID required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.1,
  },
  {
    id: "tour-george-town-4",
    guideId: "guide-george-town-2",
    title: "Academic Insights Journey",
    description:
      "Journey through the history of george-town on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "george-town",
    country: "Cayman Islands",
    region: "Caribbean",
    languagesOffered: ["English", "Italian"],
    durationInHours: 2.5,
    price: "$113",
    tags: ["Educational", "Scenic", "Nightlife"],
    type: "Cooking Class",
    schedule: [
      {
        attractionId: "attraction-george-town-55-1",
        dayOfWeek: "Sunday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 113,
    currency: "USD",
    maxGroupSize: 7,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 69,
    included: [
      "Use of helmet",
      "Local taxes",
      "Use of bicycle",
      "Recipe booklet",
      "Snacks",
      "Food samples",
    ],
    notIncluded: ["Personal expenses", "Additional entrance fees"],
    requirements: ["COVID-19 vaccination required"],
    cancellationPolicy:
      "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4,
  },
  {
    id: "tour-george-town-5",
    guideId: "guide-george-town-5",
    title: "Extreme Adventure Challenge",
    description:
      "Immerse yourself in the local culture of george-town with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "george-town",
    country: "Cayman Islands",
    region: "Caribbean",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 2.5,
    price: "$111",
    tags: ["Adventure", "Romantic", "Scenic"],
    type: "Underground Tour",
    schedule: [
      {
        attractionId: "attraction-george-town-55-2",
        dayOfWeek: "Wednesday",
        startTime: "5:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-george-town-55-3",
        dayOfWeek: "Monday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-george-town-55-1",
        dayOfWeek: "Saturday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 111,
    currency: "USD",
    maxGroupSize: 10,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 66,
    included: [
      "Food samples",
      "Gratuities",
      "Souvenir photos",
      "Audio guide",
      "Hotel pickup and drop-off",
      "Headsets to hear the guide",
    ],
    notIncluded: [
      "Alcoholic drinks",
      "Additional entrance fees",
      "Luggage storage",
    ],
    requirements: [
      "Cash only",
      "Basic fitness level required",
      "E-tickets accepted",
    ],
    cancellationPolicy:
      "Free cancellation up to 72 hours before the experience starts",
    rating: 4.2,
  },
  {
    id: "tour-george-town-6",
    guideId: "guide-george-town-3",
    title: "Food Connoisseur's Tour",
    description:
      "Journey through the history of george-town on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "george-town",
    country: "Cayman Islands",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 12,
    price: "€44",
    tags: ["Culinary", "Adventure", "Scenic", "Culture"],
    type: "Wine Tour",
    schedule: [
      {
        attractionId: "attraction-george-town-55-3",
        dayOfWeek: "Saturday",
        startTime: "10:00 AM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-george-town-55-1",
        dayOfWeek: "Friday",
        startTime: "2:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-george-town-55-2",
        dayOfWeek: "Thursday",
        startTime: "3:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 44,
    currency: "EUR",
    maxGroupSize: 12,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 100,
    included: [
      "Hotel pickup and drop-off",
      "Headsets to hear the guide",
      "Use of helmet",
    ],
    notIncluded: [
      "Alcoholic drinks",
      "Transportation to/from attractions",
      "Souvenir photos",
    ],
    requirements: ["Arrive 15 minutes early"],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 4,
  },
];
