import { Tour } from "@/lib/interfaces/services/tours";

export const helsinkifinlandnorthernEuropeTours: Tour[] = [
  {
    id: "tour-helsinki-1",
    guideId: "guide-helsinki-6",
    title: "Helsinki Cultural Heritage Tour",
    description: "Uncover the secrets of helsinki on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "helsinki",
    country: "Finland",
    region: "Northern Europe",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 1.5,
    price: "C$31",
    tags: ["Family", "Beach"],
    type: "Walking Tour",
    schedule: [
      {
        dayOfWeek: "Sunday",
        startTime: "14:00",
        endTime: "16:00",
      }
    ],
    pricePerPerson: 31,
    currency: "CAD",
    maxGroupSize: 18,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 93,
    included: ["Local taxes", "Audio guide", "Lunch", "Headsets to hear the guide", "Entry/Admission tickets", "Guided commentary"],
    notIncluded: ["Travel insurance", "Gratuities", "Souvenir photos", "Transportation to/from attractions"],
    requirements: ["No mobility restrictions", "Bring water and snacks", "No pets allowed"],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.2,
  },
  {
    id: "tour-helsinki-2",
    guideId: "guide-helsinki-10",
    title: "Helsinki Luxury Shopping Experience",
    description: "Explore the vibrant streets of helsinki with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "helsinki",
    country: "Finland",
    region: "Northern Europe",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 3,
    price: "C$152",
    tags: ["Wine & Spirits", "Wellness", "Local Market"],
    type: "Self-Guided Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "10:00",
        endTime: "11:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "11:00",
        endTime: "12:30",
      },
      {
        dayOfWeek: "Monday",
        startTime: "10:00",
        endTime: "20:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "13:00",
        endTime: "14:30",
      }
    ],
    pricePerPerson: 152,
    currency: "CAD",
    maxGroupSize: 8,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 81,
    included: ["Entry/Admission tickets", "Dinner", "Local taxes", "Snacks", "Guided commentary"],
    notIncluded: ["Travel insurance", "Alcoholic drinks"],
    requirements: ["Comfortable walking shoes required", "No pets allowed", "Swimming required", "Bring own headphones"],
    cancellationPolicy: "Free cancellation up to 72 hours before the experience starts",
    rating: 4.3,
  },
  {
    id: "tour-helsinki-3",
    guideId: "guide-helsinki-6",
    title: "Helsinki Urban Photography Journey",
    description: "Discover the best of helsinki on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "helsinki",
    country: "Finland",
    region: "Northern Europe",
    languagesOffered: ["English"],
    durationInHours: 2.5,
    price: "€45",
    tags: ["Hiking", "Adventure", "Food & Drink", "Off the Beaten Path"],
    type: "Wine Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "17:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "13:00",
        endTime: "18:00",
      }
    ],
    pricePerPerson: 45,
    currency: "EUR",
    maxGroupSize: 11,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 42,
    included: ["Bottled water", "Wine tasting", "Lunch", "Entry/Admission tickets"],
    notIncluded: ["Gratuities", "Travel insurance"],
    requirements: ["Passport required"],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4.4,
  },
  {
    id: "tour-helsinki-4",
    guideId: "guide-helsinki-5",
    title: "Helsinki Nature Escape",
    description: "Immerse yourself in the local culture of helsinki with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "helsinki",
    country: "Finland",
    region: "Northern Europe",
    languagesOffered: ["English", "French"],
    durationInHours: 12,
    price: "¥44",
    tags: ["Culture", "Romantic", "Food & Drink", "Hiking"],
    type: "Relocation Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "08:00",
        endTime: "12:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "13:00",
        endTime: "17:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "13:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "15:00",
        endTime: "20:00",
      }
    ],
    pricePerPerson: 44,
    currency: "JPY",
    maxGroupSize: 16,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 62,
    included: ["Use of bicycle", "Rain ponchos", "Entrance fees", "Cooking demonstration"],
    notIncluded: ["Personal expenses", "Luggage storage"],
    requirements: ["Parental consent required", "Passport required", "Tickets must be printed", "Must be 21+ to consume alcohol"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.6,
  }
];
