import { Tour } from "@/lib/interfaces/services/tours";

export const ketchikanunitedStatesalaskaTours: Tour[] = [
  {
    id: "tour-ketchikan-1",
    guideId: "guide-ketchikan-6",
    title: "Panoramic Vista Expedition",
    description:
      "Uncover the secrets of ketchikan on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 1,
    price: "$95",
    tags: ["Scenic", "Volunteer"],
    type: "Eco Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-2",
        dayOfWeek: "Wednesday",
        startTime: "2:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Friday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Tuesday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 95,
    currency: "USD",
    maxGroupSize: 13,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 88,
    included: [
      "Dinner",
      "Cooking demonstration",
      "Transportation during tour",
      "Headsets to hear the guide",
      "Local taxes",
      "Gratuities",
      "Entry/Admission tickets",
    ],
    notIncluded: ["Souvenir photos", "Hotel pickup and drop-off"],
    requirements: ["Stairs involved"],
    cancellationPolicy:
      "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.7,
  },
  {
    id: "tour-ketchikan-2",
    guideId: "guide-ketchikan-2",
    title: "Sound & Culture Journey",
    description:
      "Discover the best of ketchikan on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 2,
    price: "€72",
    tags: ["Music", "Family", "Volunteer", "Culture"],
    type: "Street Art Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Monday",
        startTime: "2:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Tuesday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-2",
        dayOfWeek: "Saturday",
        startTime: "3:00 PM",
        endTime: "4:00 PM",
      },
    ],
    pricePerPerson: 72,
    currency: "EUR",
    maxGroupSize: 11,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 57,
    included: [
      "Food samples",
      "Entrance fees",
      "Use of helmet",
      "Lunch",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Travel insurance",
      "Food and drinks",
      "Additional entrance fees",
      "Alcoholic drinks",
    ],
    requirements: [
      "No mobility restrictions",
      "Must be 21+ to consume alcohol",
    ],
    cancellationPolicy:
      "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 3.9,
  },
  {
    id: "tour-ketchikan-3",
    guideId: "guide-ketchikan-3",
    title: "Ancient Ruins Expedition",
    description:
      "Immerse yourself in the local culture of ketchikan with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 2.5,
    price: "¥41",
    tags: ["Historical", "LGBTQ+ Friendly"],
    type: "Boat Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Thursday",
        startTime: "10:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 41,
    currency: "JPY",
    maxGroupSize: 17,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 39,
    included: [
      "Lunch",
      "Dinner",
      "Audio guide",
      "Skip-the-line access",
      "Wine tasting",
      "Recipe booklet",
    ],
    notIncluded: [
      "Luggage storage",
      "Additional entrance fees",
      "Alcoholic drinks",
      "Gratuities",
    ],
    requirements: ["Swimming required"],
    cancellationPolicy:
      "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.6,
  },
  {
    id: "tour-ketchikan-4",
    guideId: "guide-ketchikan-2",
    title: "Environmental Learning Tour",
    description:
      "Journey through the history of ketchikan on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 12,
    price: "C$108",
    tags: ["Eco", "Scenic"],
    type: "Market Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-2",
        dayOfWeek: "Thursday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Wednesday",
        startTime: "5:00 PM",
        endTime: "9:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Tuesday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 108,
    currency: "CAD",
    maxGroupSize: 13,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 71,
    included: [
      "Skip-the-line access",
      "Live entertainment",
      "Entry/Admission tickets",
      "Local taxes",
      "Gratuities",
      "WiFi on board",
    ],
    notIncluded: ["Gratuities", "Transportation to/from attractions"],
    requirements: [
      "Passport required",
      "COVID-19 vaccination required",
      "All ages welcome",
    ],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 4.2,
  },
  {
    id: "tour-ketchikan-5",
    guideId: "guide-ketchikan-3",
    title: "Personal Discovery Tour",
    description:
      "Uncover the secrets of ketchikan on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English", "Mandarin"],
    durationInHours: 2,
    price: "¥57",
    tags: ["Solo", "Local Life"],
    type: "Cruise Excursion",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Friday",
        startTime: "10:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-2",
        dayOfWeek: "Sunday",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 57,
    currency: "JPY",
    maxGroupSize: 9,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 60,
    included: [
      "Live entertainment",
      "Souvenir photos",
      "Transportation during tour",
      "Wine tasting",
    ],
    notIncluded: ["Luggage storage", "Gratuities"],
    requirements: [
      "Cash only",
      "Advanced fitness level required",
      "Wheelchair accessible",
    ],
    cancellationPolicy:
      "Group bookings: Free cancellation up to 7 days in advance",
    rating: 3.7,
  },
  {
    id: "tour-ketchikan-6",
    guideId: "guide-ketchikan-1",
    title: "Cooking Class & Food Tour",
    description:
      "Explore the vibrant streets of ketchikan with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 4,
    price: "£120",
    tags: ["Culinary", "Art"],
    type: "Nature Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Monday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 120,
    currency: "GBP",
    maxGroupSize: 10,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 68,
    included: [
      "Skip-the-line access",
      "Entry/Admission tickets",
      "Dinner",
      "Bottled water",
      "Food samples",
      "Recipe booklet",
    ],
    notIncluded: [
      "Souvenir photos",
      "Luggage storage",
      "Transportation to/from attractions",
      "Hotel pickup and drop-off",
    ],
    requirements: [
      "Comfortable walking shoes required",
      "Cash only",
      "Signed waiver required",
      "Tickets must be printed",
    ],
    cancellationPolicy:
      "Free cancellation up to 72 hours before the experience starts",
    rating: 4.5,
  },
  {
    id: "tour-ketchikan-7",
    guideId: "guide-ketchikan-6",
    title: "Shore Excursion Tour",
    description:
      "Journey through the history of ketchikan on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English", "Italian"],
    durationInHours: 4,
    price: "€20",
    tags: ["Cruise Stop"],
    type: "Cooking Class",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Sunday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 20,
    currency: "EUR",
    maxGroupSize: 17,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 101,
    included: [
      "WiFi on board",
      "Use of bicycle",
      "Wine tasting",
      "Skip-the-line access",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Personal expenses",
      "Hotel pickup and drop-off",
      "Luggage storage",
      "Alcoholic drinks",
    ],
    requirements: ["Advanced fitness level required"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.5,
  },
];
