import { Tour } from "@/lib/interfaces/services/tours";

export const ketchikanunitedStatesalaskaTours: Tour[] = [
  {
    id: "tour-ketchikan-1",
    guideId: "guide-ketchikan-1",
    title: "Ketchikan Craft Breweries Tour",
    description: "Immerse yourself in the local culture of ketchikan with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 1.5,
    price: "¥86",
    tags: ["Historical", "Wellness", "Adventure"],
    type: "Historical Tour",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "12:00",
        endTime: "17:00",
      }
    ],
    pricePerPerson: 86,
    currency: "JPY",
    maxGroupSize: 6,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 19,
    included: ["Professional guide", "WiFi on board", "Headsets to hear the guide"],
    notIncluded: ["Luggage storage", "Hotel pickup and drop-off", "Travel insurance"],
    requirements: ["Basic fitness level required"],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.2,
  },
  {
    id: "tour-ketchikan-2",
    guideId: "guide-ketchikan-1",
    title: "Ketchikan Nightlife Exploration",
    description: "Uncover the secrets of ketchikan on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 1.5,
    price: "¥95",
    tags: ["Family", "Educational"],
    type: "Street Art Tour",
    schedule: [
      {
        dayOfWeek: "Thursday",
        startTime: "15:00",
        endTime: "17:30",
      },
      {
        dayOfWeek: "Monday",
        startTime: "14:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 95,
    currency: "JPY",
    maxGroupSize: 17,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 59,
    included: ["Audio guide", "Bottled water", "Gratuities", "Lunch", "Wine tasting"],
    notIncluded: ["Gratuities", "Transportation to/from attractions"],
    requirements: ["Comfortable walking shoes required", "Weather-appropriate clothing"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.9,
  },
  {
    id: "tour-ketchikan-3",
    guideId: "guide-ketchikan-2",
    title: "Ketchikan Family Fun Adventure",
    description: "Uncover the secrets of ketchikan on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 8,
    price: "$122",
    tags: ["Historical", "Romantic", "Family", "Food & Drink"],
    type: "Cruise Excursion",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "09:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "16:00",
        endTime: "22:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "10:00",
        endTime: "14:00",
      }
    ],
    pricePerPerson: 122,
    currency: "USD",
    maxGroupSize: 8,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 73,
    included: ["Snacks", "Local taxes", "Bottled water", "Transportation during tour", "Welcome drink", "Souvenir photos", "Wine tasting"],
    notIncluded: ["Additional entrance fees", "Travel insurance", "Personal expenses"],
    requirements: ["Cash only", "Tickets must be printed", "Advanced fitness level required"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 3.9,
  },
  {
    id: "tour-ketchikan-4",
    guideId: "guide-ketchikan-6",
    title: "Ketchikan Nature Escape",
    description: "Discover the best of ketchikan on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 3,
    price: "A$111",
    tags: ["Festival", "Music"],
    type: "Walking Tour",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "15:00",
        endTime: "17:30",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "14:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "17:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 111,
    currency: "AUD",
    maxGroupSize: 12,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 83,
    included: ["Entry/Admission tickets", "Snacks", "Welcome drink"],
    notIncluded: ["Luggage storage", "Gratuities", "Food and drinks"],
    requirements: ["Credit/debit cards accepted", "Swimming required"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.8,
  },
  {
    id: "tour-ketchikan-5",
    guideId: "guide-ketchikan-3",
    title: "Ketchikan Off-the-Beaten-Path Adventure",
    description: "Discover the best of ketchikan on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 12,
    price: "£142",
    tags: ["Luxury", "Off the Beaten Path"],
    type: "Nature Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "15:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "08:00",
        endTime: "10:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "12:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "13:00",
        endTime: "15:30",
      }
    ],
    pricePerPerson: 142,
    currency: "GBP",
    maxGroupSize: 8,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 64,
    included: ["Use of helmet", "Entrance fees", "Guided commentary", "Headsets to hear the guide", "Skip-the-line access"],
    notIncluded: ["Transportation to/from attractions", "Hotel pickup and drop-off", "Souvenir photos"],
    requirements: ["Not wheelchair accessible", "Advanced fitness level required"],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.6,
  },
  {
    id: "tour-ketchikan-6",
    guideId: "guide-ketchikan-2",
    title: "Ketchikan Scenic Views Tour",
    description: "Journey through the history of ketchikan on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English"],
    durationInHours: 6,
    price: "¥75",
    tags: ["Beach", "Local Market", "Food & Drink", "Culture"],
    type: "Photography Tour",
    schedule: [
      {
        dayOfWeek: "Monday",
        startTime: "15:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 75,
    currency: "JPY",
    maxGroupSize: 7,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 92,
    included: ["Audio guide", "Use of helmet", "Professional guide", "Snacks", "Headsets to hear the guide", "Skip-the-line access"],
    notIncluded: ["Additional entrance fees", "Food and drinks", "Transportation to/from attractions"],
    requirements: ["Parental consent required", "Signed waiver required", "COVID-19 vaccination required"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.7,
  },
  {
    id: "tour-ketchikan-7",
    guideId: "guide-ketchikan-5",
    title: "Ketchikan Ghost Stories Walk",
    description: "Explore the vibrant streets of ketchikan with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: ["English", "Italian"],
    durationInHours: 6,
    price: "¥84",
    tags: ["Music", "Luxury", "Spiritual", "Local Life"],
    type: "Underground Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "08:00",
        endTime: "13:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "15:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "15:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 84,
    currency: "JPY",
    maxGroupSize: 10,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 48,
    included: ["Souvenir photos", "Live entertainment", "Gratuities", "Local taxes", "Audio guide", "Snacks"],
    notIncluded: ["Additional entrance fees", "Alcoholic drinks"],
    requirements: ["Bring own headphones", "Minimum age: 18", "Signed waiver required"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 3.8,
  }
];
