// Auto-generated file for ketchikan tours
// Country: United States, Region: Alaska

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const ketchikanunitedStatesalaskaTours: Tour[] = [
  {
    id: "tour-ketchikan-1",
    guideId: "guide-ketchikan-9",
    title: "Bridges & Monuments Walk",
    description: "Immerse yourself in the local culture of ketchikan with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: [
      "English",
    ],
    price: "$98",
    tags: [
      "Food & Drink",
      "Wellness",
    ],
    type: "Architecture Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Wednesday",
        startTime: "12:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-2",
        dayOfWeek: "Monday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Friday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 98,
    currency: "USD",
    maxGroupSize: 32,
    minGroupSize: 11,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 43,
    included: [
      "Headsets to hear the guide",
      "Souvenir photos",
      "Bottled water",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Swimming required",
      "Government-issued ID for entry",
      "Passport required",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 3.8,
  },
  {
    id: "tour-ketchikan-2",
    guideId: "guide-ketchikan-3",
    title: "Wine Region Discovery",
    description: "Journey through the history of ketchikan on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$100",
    tags: [
      "Wine & Spirits",
      "Cruise Stop",
      "LGBTQ+ Friendly",
      "Family",
    ],
    type: "Photography Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-2",
        dayOfWeek: "Sunday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
    ],
    pricePerPerson: 100,
    currency: "USD",
    maxGroupSize: 22,
    minGroupSize: 12,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 46,
    included: [
      "Headsets to hear the guide",
      "Entrance fees (if applicable)",
      "Gratuities",
      "Local taxes",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Travel insurance",
      "Gratuities",
    ],
    requirements: [
      "Comfortable walking shoes required",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.6,
  },
  {
    id: "tour-ketchikan-3",
    guideId: "guide-ketchikan-10",
    title: "Local Traditions Tour",
    description: "Journey through the history of ketchikan on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$160",
    tags: [
      "Culture",
      "Cruise Stop",
    ],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Wednesday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 160,
    currency: "USD",
    maxGroupSize: 35,
    minGroupSize: 5,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 55,
    included: [
      "Rain ponchos (if needed)",
      "Souvenir photos",
      "Gratuities",
      "Entrance fees (if applicable)",
      "Bottled water",
    ],
    notIncluded: [
      "Parking fees",
      "Additional tickets for attractions",
      "Personal expenses",
    ],
    requirements: [
      "Signed waiver required",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 3.9,
  },
  {
    id: "tour-ketchikan-4",
    guideId: "guide-ketchikan-11",
    title: "Panoramic City Tour",
    description: "Uncover the secrets of ketchikan on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: [
      "English",
    ],
    price: "$106",
    tags: [
      "Sightseeing",
      "Food & Drink",
      "Historical",
      "Eco",
    ],
    type: "Underground Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Monday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-2",
        dayOfWeek: "Tuesday",
        startTime: "5:00 PM",
        endTime: "9:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Friday",
        startTime: "3:00 PM",
        endTime: "4:00 PM",
      },
    ],
    pricePerPerson: 106,
    currency: "USD",
    maxGroupSize: 48,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 93,
    included: [
      "Rain ponchos (if needed)",
      "Food samples",
      "Local taxes",
      "Transportation during tour (if applicable)",
      "Snacks",
      "Bottled water",
    ],
    notIncluded: [
      "Personal expenses",
      "Travel insurance",
    ],
    requirements: [
      "Service animals permitted",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 4.9,
  },
  {
    id: "tour-ketchikan-5",
    guideId: "guide-ketchikan-7",
    title: "Local Artists Showcase",
    description: "Discover the best of ketchikan on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$170",
    tags: [
      "Art",
      "Sports",
      "Culinary",
      "Cruise Stop",
    ],
    type: "Street Art Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-3",
        dayOfWeek: "Sunday",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Thursday",
        startTime: "9:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-ketchikan-47-2",
        dayOfWeek: "Wednesday",
        startTime: "5:00 PM",
        endTime: "8:00 PM",
      },
    ],
    pricePerPerson: 170,
    currency: "USD",
    maxGroupSize: 24,
    minGroupSize: 14,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 54,
    included: [
      "Bottled water",
      "Hotel pickup and drop-off",
      "Snacks",
      "Souvenir photos",
    ],
    notIncluded: [
      "Personal expenses",
      "Gratuities",
      "Luggage storage",
      "Food and drinks at restaurants and/or cafes",
    ],
    requirements: [
      "Valid ID required",
      "Passport required",
      "Swimming required",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.9,
  },
  {
    id: "tour-ketchikan-6",
    guideId: "guide-ketchikan-3",
    title: "Scenic Photo Expedition",
    description: "Discover the best of ketchikan on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$134",
    tags: [
      "Photography",
      "Culinary",
      "Architecture",
      "Art",
    ],
    type: "Shopping Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Thursday",
        startTime: "10:00 AM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 134,
    currency: "USD",
    maxGroupSize: 22,
    minGroupSize: 14,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 72,
    included: [
      "Coffee and/or Tea",
      "Snacks",
      "Food samples",
      "Rain ponchos (if needed)",
      "Transportation during tour (if applicable)",
      "Bottled water",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Additional tickets for attractions",
    ],
    requirements: [
      "No pets allowed",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.5,
  },
  {
    id: "tour-ketchikan-7",
    guideId: "guide-ketchikan-8",
    title: "Holistic Wellness Journey",
    description: "Immerse yourself in the local culture of ketchikan with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "ketchikan",
    country: "United States",
    region: "Alaska",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$42",
    tags: [
      "Wellness",
      "Eco",
      "Culinary",
      "Shopping",
    ],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-ketchikan-47-1",
        dayOfWeek: "Wednesday",
        startTime: "11:00 AM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 42,
    currency: "USD",
    maxGroupSize: 32,
    minGroupSize: 7,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 6,
    included: [
      "Entrance fees (if applicable)",
      "Rain ponchos (if needed)",
      "Gratuities",
      "Bottled water",
      "Local taxes",
    ],
    notIncluded: [
      "Gratuities",
      "Parking fees",
    ],
    requirements: [
      "Face masks required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 3.8,
  },
];
