import { Tour } from "@/lib/interfaces/services/tours";

export const kyotojapanasiaPacificTours: Tour[] = [
  {
    id: "tour-kyoto-1",
    guideId: "guide-kyoto-3",
    title: "Art & Artifact Journey",
    description: "Journey through the history of kyoto on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "kyoto",
    country: "Japan",
    region: "Asia Pacific",
    languagesOffered: ["English", "French"],
    price: "£34",
    tags: ["Historical", "Festival"],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-kyoto-66-3",
        dayOfWeek: "Saturday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-kyoto-66-2",
        dayOfWeek: "Friday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      }
    ],
    pricePerPerson: 34,
    currency: "GBP",
    maxGroupSize: 6,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 25,
    included: ["Transportation during tour", "Live entertainment", "Wine tasting"],
    notIncluded: ["Personal expenses", "Luggage storage", "Additional entrance fees"],
    requirements: ["COVID-19 vaccination required"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.8,
  },
  {
    id: "tour-kyoto-2",
    guideId: "guide-kyoto-4",
    title: "Step-by-Step Journey",
    description: "Explore the vibrant streets of kyoto with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "kyoto",
    country: "Japan",
    region: "Asia Pacific",
    languagesOffered: ["English"],
    price: "C$26",
    tags: ["Sightseeing", "Photography", "Local Market"],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-kyoto-66-3",
        dayOfWeek: "Wednesday",
        startTime: "10:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-kyoto-66-1",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-kyoto-66-2",
        dayOfWeek: "Thursday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      }
    ],
    pricePerPerson: 26,
    currency: "CAD",
    maxGroupSize: 8,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 17,
    included: ["Professional guide", "Skip-the-line access", "Coffee and/or Tea", "Transportation during tour", "Audio guide"],
    notIncluded: ["Alcoholic drinks", "Gratuities", "Additional entrance fees", "Luggage storage"],
    requirements: ["Headphones provided", "Swimming required"],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.6,
  },
  {
    id: "tour-kyoto-3",
    guideId: "guide-kyoto-2",
    title: "Food Connoisseur's Tour",
    description: "Journey through the history of kyoto on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "kyoto",
    country: "Japan",
    region: "Asia Pacific",
    languagesOffered: ["English"],
    price: "£120",
    tags: ["Culinary", "Festival", "Culture"],
    type: "Festival Tour",
    schedule: [
      {
        attractionId: "attraction-kyoto-66-2",
        dayOfWeek: "Sunday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-kyoto-66-1",
        dayOfWeek: "Monday",
        startTime: "2:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-kyoto-66-3",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "6:00 PM",
      }
    ],
    pricePerPerson: 120,
    currency: "GBP",
    maxGroupSize: 15,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 78,
    included: ["Souvenir photos", "Guided commentary", "Recipe booklet"],
    notIncluded: ["Alcoholic drinks", "Souvenir photos"],
    requirements: ["Not wheelchair accessible"],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4.5,
  }
];
