// Auto-generated file for lisbon tours
// Country: Portugal, Region: Mediterranean

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const lisbonportugalmediterraneanTours: Tour[] = [
  {
    id: "tour-lisbon-1",
    guideId: "guide-lisbon-11",
    title: "Hidden Street Art Gems",
    description: "Explore the vibrant streets of lisbon with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "lisbon",
    country: "Portugal",
    region: "Mediterranean",
    languagesOffered: [
      "Portuguese",
    ],
    price: "€48",
    tags: [
      "Hiking",
      "Sports",
    ],
    type: "Street Art Tour",
    schedule: [
      {
        attractionId: "attraction-lisbon-30-2",
        dayOfWeek: "Saturday",
        startTime: "4:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-lisbon-30-1",
        dayOfWeek: "Sunday",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-lisbon-30-3",
        dayOfWeek: "Friday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
    ],
    pricePerPerson: 48,
    currency: "EUR",
    maxGroupSize: 32,
    minGroupSize: 10,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 47,
    included: [
      "Hotel pickup and drop-off",
      "Rain ponchos (if needed)",
      "Bottled water",
      "Local taxes",
    ],
    notIncluded: [
      "Travel insurance",
      "Food and drinks at restaurants and/or cafes",
      "Gratuities",
    ],
    requirements: [
      "No flash photography",
      "Dress code enforced",
      "Service animals permitted",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.5,
  },
  {
    id: "tour-lisbon-2",
    guideId: "guide-lisbon-14",
    title: "Street Food Safari",
    description: "Discover the best of lisbon on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "lisbon",
    country: "Portugal",
    region: "Mediterranean",
    languagesOffered: [],
    price: "€27",
    tags: [
      "Food & Drink",
      "Eco",
      "Spiritual",
      "Solo",
    ],
    type: "Architecture Tour",
    schedule: [
      {
        attractionId: "attraction-lisbon-30-3",
        dayOfWeek: "Tuesday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 27,
    currency: "EUR",
    maxGroupSize: 30,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 51,
    included: [
      "Local taxes",
      "Entrance fees (if applicable)",
      "Headsets to hear the guide",
      "Souvenir photos",
      "Snacks",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Luggage storage",
    ],
    requirements: [
      "Arrive 15 minutes early",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.7,
  },
  {
    id: "tour-lisbon-3",
    guideId: "guide-lisbon-7",
    title: "Barrel to Tap Tour",
    description: "Explore the vibrant streets of lisbon with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "lisbon",
    country: "Portugal",
    region: "Mediterranean",
    languagesOffered: [],
    price: "€48",
    tags: [
      "Shopping",
      "Beach",
      "Art",
      "Wellness",
    ],
    type: "Brewery Tour",
    schedule: [
      {
        attractionId: "attraction-lisbon-30-2",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-lisbon-30-3",
        dayOfWeek: "Wednesday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 48,
    currency: "EUR",
    maxGroupSize: 39,
    minGroupSize: 11,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 8,
    included: [
      "Food samples",
      "Local taxes",
      "Headsets to hear the guide",
      "Gratuities",
    ],
    notIncluded: [
      "Personal expenses",
      "Gratuities",
      "Parking fees",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Government-issued ID for entry",
      "Swimming required",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.6,
  },
  {
    id: "tour-lisbon-4",
    guideId: "guide-lisbon-14",
    title: "Extreme Off-Road Challenge",
    description: "Explore the vibrant streets of lisbon with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "lisbon",
    country: "Portugal",
    region: "Mediterranean",
    languagesOffered: [
      "Portuguese",
    ],
    price: "€50",
    tags: [
      "Beach",
      "Historical",
      "Spiritual",
      "Volunteer",
    ],
    type: "Off-Road Tour",
    schedule: [
      {
        attractionId: "attraction-lisbon-30-1",
        dayOfWeek: "Thursday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 50,
    currency: "EUR",
    maxGroupSize: 27,
    minGroupSize: 11,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 68,
    included: [
      "Rain ponchos (if needed)",
      "Souvenir photos",
      "Gratuities",
      "Transportation during tour (if applicable)",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Luggage storage",
      "Food and drinks at restaurants and/or cafes",
    ],
    requirements: [
      "Swimming required",
      "Government-issued ID for entry",
    ],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 3.8,
  },
];
