// Auto-generated file for mekong-delta tours
// Country: Vietnam, Region: Vietnam

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const mekongDeltavietnamvietnamTours: Tour[] = [
  {
    id: "tour-mekong-delta-1",
    guideId: "guide-mekong-delta-2",
    title: "Rhythms of the Underground",
    description: "Immerse yourself in the local culture of mekong-delta with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "mekong-delta",
    country: "Vietnam",
    region: "Vietnam",
    languagesOffered: [],
    price: "₫1128000",
    tags: [
      "Nightlife And Entertainment",
      "Poetic And Whimsical",
      "Adventure And Thrill",
    ],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-mekong-delta-120-3",
        dayOfWeek: "Monday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 1128000,
    currency: "VND",
    maxGroupSize: 38,
    minGroupSize: 9,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 36,
    included: [
      "Hotel pickup and drop-off",
      "Bottled water",
      "Headsets to hear the guide",
      "Snacks",
      "Rain ponchos (if needed)",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Luggage storage",
      "Parking fees",
    ],
    requirements: [
      "Minimum age: 12",
    ],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.1,
  },
  {
    id: "tour-mekong-delta-2",
    guideId: "guide-mekong-delta-1",
    title: "Castles, Creatures & Carousel Days",
    description: "Uncover the secrets of mekong-delta on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "mekong-delta",
    country: "Vietnam",
    region: "Vietnam",
    languagesOffered: [
      "Vietnamese",
    ],
    price: "₫1272000",
    tags: [
      "Family Friendly",
      "Nature And Scenic",
    ],
    type: "Mystery Tours",
    schedule: [
      {
        attractionId: "attraction-mekong-delta-120-2",
        dayOfWeek: "Friday",
        startTime: "12:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-1",
        dayOfWeek: "Thursday",
        startTime: "12:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-4",
        dayOfWeek: "Wednesday",
        startTime: "5:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-3",
        dayOfWeek: "Sunday",
        startTime: "4:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 1272000,
    currency: "VND",
    maxGroupSize: 26,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 40,
    included: [
      "Headsets to hear the guide",
      "Hotel pickup and drop-off",
      "Rain ponchos (if needed)",
      "Souvenir photos",
    ],
    notIncluded: [
      "Personal expenses",
      "Hotel accommodations",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Cash only",
      "Minimum age: 18",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 3.9,
  },
  {
    id: "tour-mekong-delta-3",
    guideId: "guide-mekong-delta-1",
    title: "The Great Family Escape",
    description: "Journey through the history of mekong-delta on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "mekong-delta",
    country: "Vietnam",
    region: "Vietnam",
    languagesOffered: [],
    price: "₫1464000",
    tags: [
      "Family Friendly",
      "Culinary And Food",
    ],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-mekong-delta-120-3",
        dayOfWeek: "Tuesday",
        startTime: "3:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-1",
        dayOfWeek: "Monday",
        startTime: "1:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-4",
        dayOfWeek: "Friday",
        startTime: "11:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-2",
        dayOfWeek: "Saturday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 1464000,
    currency: "VND",
    maxGroupSize: 33,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 66,
    included: [
      "Food samples",
      "Transportation during tour (if applicable)",
      "Souvenir photos",
      "Headsets to hear the guide",
    ],
    notIncluded: [
      "Hotel accommodations",
      "Travel insurance",
    ],
    requirements: [
      "Cash only",
      "Tickets must be printed",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 3.7,
  },
  {
    id: "tour-mekong-delta-4",
    guideId: "guide-mekong-delta-2",
    title: "No Limits: Adventure Reloaded",
    description: "Explore the vibrant streets of mekong-delta with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "mekong-delta",
    country: "Vietnam",
    region: "Vietnam",
    languagesOffered: [],
    price: "₫912000",
    tags: [
      "Art And Culture",
      "Culinary And Food",
    ],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-mekong-delta-120-1",
        dayOfWeek: "Monday",
        startTime: "11:00 AM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-3",
        dayOfWeek: "Tuesday",
        startTime: "12:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-4",
        dayOfWeek: "Saturday",
        startTime: "10:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-2",
        dayOfWeek: "Friday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 912000,
    currency: "VND",
    maxGroupSize: 31,
    minGroupSize: 14,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 94,
    included: [
      "Souvenir photos",
      "Entrance fees (if applicable)",
      "Hotel pickup and drop-off",
      "Local taxes",
      "Coffee and/or Tea",
      "Snacks",
    ],
    notIncluded: [
      "Parking fees",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "Bring own headphones",
      "Dress code enforced",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 3.7,
  },
  {
    id: "tour-mekong-delta-5",
    guideId: "guide-mekong-delta-2",
    title: "Highland Spirits Trek",
    description: "Immerse yourself in the local culture of mekong-delta with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "mekong-delta",
    country: "Vietnam",
    region: "Vietnam",
    languagesOffered: [
      "Vietnamese",
    ],
    price: "₫2256000",
    tags: [
      "Nature And Scenic",
      "Family Friendly",
    ],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-mekong-delta-120-3",
        dayOfWeek: "Tuesday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-mekong-delta-120-2",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 2256000,
    currency: "VND",
    maxGroupSize: 40,
    minGroupSize: 7,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 52,
    included: [
      "Headsets to hear the guide",
      "Coffee and/or Tea",
      "Snacks",
    ],
    notIncluded: [
      "Luggage storage",
      "Travel insurance",
      "Personal expenses",
    ],
    requirements: [
      "Minimum age: 12",
    ],
    cancellationPolicy: "Free cancellation up to 72 hours before the experience starts",
    rating: 3.9,
  },
];
