// Auto-generated file for melbourne tours
// Country: Australia, Region: Asia Pacific

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const melbourneaustraliaasiaPacificTours: Tour[] = [
  {
    id: "tour-melbourne-1",
    guideId: "guide-melbourne-3",
    title: "Food Cart Expedition",
    description: "Journey through the history of melbourne on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "melbourne",
    country: "Australia",
    region: "Asia Pacific",
    languagesOffered: [
      "English",
    ],
    price: "A$135",
    tags: [
      "Street Food",
      "LGBTQ+ Friendly",
      "Photography",
    ],
    type: "Private Tour",
    schedule: [
      {
        attractionId: "attraction-melbourne-59-1",
        dayOfWeek: "Sunday",
        startTime: "3:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-melbourne-59-3",
        dayOfWeek: "Saturday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-melbourne-59-2",
        dayOfWeek: "Friday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 135,
    currency: "AUD",
    maxGroupSize: 28,
    minGroupSize: 8,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 21,
    included: [
      "Hotel pickup and drop-off",
      "Souvenir photos",
      "Gratuities",
      "Coffee and/or Tea",
      "Bottled water",
      "Snacks",
      "Entrance fees (if applicable)",
    ],
    notIncluded: [
      "Travel insurance",
      "Gratuities",
    ],
    requirements: [
      "No flash photography",
      "Face masks required",
    ],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.2,
  },
  {
    id: "tour-melbourne-2",
    guideId: "guide-melbourne-9",
    title: "Scenic Trails Expedition",
    description: "Uncover the secrets of melbourne on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "melbourne",
    country: "Australia",
    region: "Asia Pacific",
    languagesOffered: [
      "English",
    ],
    price: "A$246",
    tags: [
      "Hiking",
      "Wine & Spirits",
    ],
    type: "Cultural Tour",
    schedule: [
      {
        attractionId: "attraction-melbourne-59-3",
        dayOfWeek: "Saturday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-melbourne-59-1",
        dayOfWeek: "Thursday",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 246,
    currency: "AUD",
    maxGroupSize: 23,
    minGroupSize: 9,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 40,
    included: [
      "Snacks",
      "Food samples",
      "Rain ponchos (if needed)",
      "Souvenir photos",
      "Hotel pickup and drop-off",
      "Bottled water",
      "Gratuities",
    ],
    notIncluded: [
      "Personal expenses",
      "Additional tickets for attractions",
      "Parking fees",
      "Gratuities",
    ],
    requirements: [
      "Cash only",
      "Arrive 15 minutes early",
      "Valid ID required",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.7,
  },
  {
    id: "tour-melbourne-3",
    guideId: "guide-melbourne-3",
    title: "Wildlife Safari Experience",
    description: "Immerse yourself in the local culture of melbourne with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "melbourne",
    country: "Australia",
    region: "Asia Pacific",
    languagesOffered: [
      "English",
    ],
    price: "A$128",
    tags: [
      "Nature & Wildlife",
      "Culture",
      "Spiritual",
      "Cruise Stop",
    ],
    type: "Ghost Tour",
    schedule: [
      {
        attractionId: "attraction-melbourne-59-1",
        dayOfWeek: "Thursday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-melbourne-59-2",
        dayOfWeek: "Wednesday",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-melbourne-59-3",
        dayOfWeek: "Tuesday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 128,
    currency: "AUD",
    maxGroupSize: 39,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 84,
    included: [
      "Hotel pickup and drop-off",
      "Snacks",
      "Bottled water",
      "Headsets to hear the guide",
      "Gratuities",
      "Souvenir photos",
    ],
    notIncluded: [
      "Personal expenses",
      "Travel insurance",
      "Gratuities",
    ],
    requirements: [
      "No flash photography",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 3.8,
  },
  {
    id: "tour-melbourne-4",
    guideId: "guide-melbourne-6",
    title: "Mind-Body Balance Tour",
    description: "Discover the best of melbourne on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "melbourne",
    country: "Australia",
    region: "Asia Pacific",
    languagesOffered: [
      "English",
    ],
    price: "A$210",
    tags: [
      "Wellness",
      "Shopping",
      "Family",
      "LGBTQ+ Friendly",
    ],
    type: "Wine Tour",
    schedule: [
      {
        attractionId: "attraction-melbourne-59-1",
        dayOfWeek: "Sunday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-melbourne-59-3",
        dayOfWeek: "Saturday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-melbourne-59-2",
        dayOfWeek: "Friday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 210,
    currency: "AUD",
    maxGroupSize: 22,
    minGroupSize: 5,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 46,
    included: [
      "Rain ponchos (if needed)",
      "Hotel pickup and drop-off",
      "Bottled water",
      "Local taxes",
      "Entrance fees (if applicable)",
    ],
    notIncluded: [
      "Personal expenses",
      "Gratuities",
      "Travel insurance",
    ],
    requirements: [
      "Service animals permitted",
      "Face masks required",
      "No flash photography",
      "Minimum age: 18",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4.9,
  },
  {
    id: "tour-melbourne-5",
    guideId: "guide-melbourne-6",
    title: "Traditional Festivities Tour",
    description: "Immerse yourself in the local culture of melbourne with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "melbourne",
    country: "Australia",
    region: "Asia Pacific",
    languagesOffered: [
      "English",
    ],
    price: "A$223",
    tags: [
      "Festival",
      "Shopping",
      "Architecture",
      "Volunteer",
    ],
    type: "Photography Tour",
    schedule: [
      {
        attractionId: "attraction-melbourne-59-3",
        dayOfWeek: "Friday",
        startTime: "8:00 AM",
        endTime: "9:00 AM",
      },
      {
        attractionId: "attraction-melbourne-59-2",
        dayOfWeek: "Monday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-melbourne-59-1",
        dayOfWeek: "Tuesday",
        startTime: "11:00 AM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 223,
    currency: "AUD",
    maxGroupSize: 43,
    minGroupSize: 5,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 28,
    included: [
      "Rain ponchos (if needed)",
      "Entrance fees (if applicable)",
      "Headsets to hear the guide",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Additional tickets for attractions",
      "Luggage storage",
    ],
    requirements: [
      "Arrive 15 minutes early",
    ],
    cancellationPolicy: "No refunds for no-shows",
    rating: 4.9,
  },
  {
    id: "tour-melbourne-6",
    guideId: "guide-melbourne-9",
    title: "Panoramic City Tour",
    description: "Discover the best of melbourne on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "melbourne",
    country: "Australia",
    region: "Asia Pacific",
    languagesOffered: [
      "English",
    ],
    price: "A$102",
    tags: [
      "Sightseeing",
      "Eco",
      "Food & Drink",
    ],
    type: "Brewery Tour",
    schedule: [
      {
        attractionId: "attraction-melbourne-59-2",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-melbourne-59-3",
        dayOfWeek: "Tuesday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-melbourne-59-1",
        dayOfWeek: "Monday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 102,
    currency: "AUD",
    maxGroupSize: 23,
    minGroupSize: 9,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 80,
    included: [
      "Entrance fees (if applicable)",
      "Snacks",
      "Food samples",
      "Local taxes",
      "Bottled water",
    ],
    notIncluded: [
      "Personal expenses",
      "Travel insurance",
    ],
    requirements: [
      "Valid ID required",
      "Cash only",
      "Dress code enforced",
    ],
    cancellationPolicy: "No refunds for no-shows",
    rating: 3.9,
  },
];
