import { Tour } from "@/lib/interfaces/services/tours";

export const montrealcanadaeastCoastCanadaTours: Tour[] = [
  {
    id: "tour-montreal-1",
    guideId: "guide-montreal-7",
    title: "Montreal Local Markets Exploration",
    description: "Uncover the secrets of montreal on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "montreal",
    country: "Canada",
    region: "East Coast Canada",
    languagesOffered: ["English"],
    durationInHours: 5,
    price: "A$135",
    tags: ["Adventure", "Cruise Stop"],
    type: "Brewery Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "08:00",
        endTime: "10:00",
      }
    ],
    pricePerPerson: 135,
    currency: "AUD",
    maxGroupSize: 8,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 92,
    included: ["Use of helmet", "Snacks", "Professional guide", "Entrance fees"],
    notIncluded: ["Transportation to/from attractions", "Hotel pickup and drop-off"],
    requirements: ["Swimming required", "Tickets must be printed"],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 3.8,
  },
  {
    id: "tour-montreal-2",
    guideId: "guide-montreal-4",
    title: "Montreal Ghost Stories Walk",
    description: "Uncover the secrets of montreal on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "montreal",
    country: "Canada",
    region: "East Coast Canada",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 1.5,
    price: "€124",
    tags: ["Wellness", "Family"],
    type: "Wine Tour",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "11:00",
        endTime: "16:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "14:00",
        endTime: "16:30",
      },
      {
        dayOfWeek: "Monday",
        startTime: "09:00",
        endTime: "21:00",
      }
    ],
    pricePerPerson: 124,
    currency: "EUR",
    maxGroupSize: 9,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 53,
    included: ["Snacks", "Cooking demonstration", "Lunch", "Use of helmet", "Recipe booklet"],
    notIncluded: ["Luggage storage", "Additional entrance fees", "Travel insurance"],
    requirements: ["Dress code enforced"],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.2,
  },
  {
    id: "tour-montreal-3",
    guideId: "guide-montreal-5",
    title: "Montreal Sunset Landmarks Tour",
    description: "Explore the vibrant streets of montreal with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "montreal",
    country: "Canada",
    region: "East Coast Canada",
    languagesOffered: ["English"],
    durationInHours: 10,
    price: "£20",
    tags: ["Religious", "Nature & Wildlife", "Festival", "Photography"],
    type: "Off-Road Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "17:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "13:00",
        endTime: "15:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "13:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
      }
    ],
    pricePerPerson: 20,
    currency: "GBP",
    maxGroupSize: 8,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 90,
    included: ["Snacks", "Use of helmet", "Recipe booklet", "Gratuities"],
    notIncluded: ["Hotel pickup and drop-off", "Souvenir photos", "Transportation to/from attractions"],
    requirements: ["Must be 21+ to consume alcohol", "No mobility restrictions", "Credit/debit cards accepted", "Tickets must be printed"],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4,
  },
  {
    id: "tour-montreal-4",
    guideId: "guide-montreal-2",
    title: "Montreal Scenic Views Tour",
    description: "Journey through the history of montreal on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "montreal",
    country: "Canada",
    region: "East Coast Canada",
    languagesOffered: ["English"],
    durationInHours: 3,
    price: "A$116",
    tags: ["Culture", "Nature & Wildlife", "Adventure"],
    type: "Museum Tour",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "15:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "14:00",
        endTime: "16:30",
      },
      {
        dayOfWeek: "Friday",
        startTime: "13:00",
        endTime: "15:30",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "16:00",
        endTime: "18:30",
      }
    ],
    pricePerPerson: 116,
    currency: "AUD",
    maxGroupSize: 7,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 40,
    included: ["Entry/Admission tickets", "Local taxes", "Headsets to hear the guide", "Dinner", "Audio guide", "Food samples"],
    notIncluded: ["Hotel pickup and drop-off", "Personal expenses", "Souvenir photos"],
    requirements: ["Photography allowed", "Weather-appropriate clothing"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.8,
  },
  {
    id: "tour-montreal-5",
    guideId: "guide-montreal-3",
    title: "Montreal Nightlife Exploration",
    description: "Immerse yourself in the local culture of montreal with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "montreal",
    country: "Canada",
    region: "East Coast Canada",
    languagesOffered: ["English"],
    durationInHours: 5,
    price: "¥49",
    tags: ["Music", "LGBTQ+ Friendly", "Eco"],
    type: "Walking Tour",
    schedule: [
      {
        dayOfWeek: "Thursday",
        startTime: "16:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "14:00",
        endTime: "20:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "14:00",
        endTime: "19:00",
      }
    ],
    pricePerPerson: 49,
    currency: "JPY",
    maxGroupSize: 7,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 51,
    included: ["WiFi on board", "Use of helmet", "Hotel pickup and drop-off", "Coffee and/or Tea"],
    notIncluded: ["Hotel pickup and drop-off", "Additional entrance fees"],
    requirements: ["Government-issued ID for entry"],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 3.7,
  }
];
