import { Tour } from "@/lib/interfaces/services/tours";

export const munichTours: Tour[] = [
  {
    title: "Beer & Brewery Heritage Tour",
    description:
      "Discover Munich's rich brewing history with visits to traditional beer halls, historic breweries, and the famous Hofbräuhaus. Learn about the 500-year-old Bavarian Purity Law while sampling distinctive beer styles.",
    city: "Munich",
    country: "Germany",
    region: "Bavaria",
    images: [
      "/images/tours/munich/beer-hall.jpg",
      "/images/tours/munich/brewery-tour.jpg",
    ],
    duration: "4 hours",
    price: "$75",
    rating: 4.8,
    tags: ["Beer", "Cultural", "History"],
    isHistorical: true,
    isRomantic: false,
    isAdventure: false,
    isCultural: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: false,
    isArtOrMusic: false,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isOutdoor: true,
    isIndoor: true,
    meetingPoint: {
      address: "Marienplatz, in front of the New Town Hall, Munich",
      coordinates: {
        latitude: 48.1371,
        longitude: 11.5753,
      },
      instructions:
        "Meet at the Marienplatz in front of the New Town Hall. Look for your guide holding a sign that says 'Beer & Brewery Tour'.",
      contactNumber: "+49 89 1234567",
    },
    tourCategoryId: "culinary",
    faqs: [
      {
        question: "Is this tour suitable for non-drinkers?",
        answer:
          "Yes, while beer tasting is a highlight, the tour focuses on cultural and historical aspects of brewing. Non-alcoholic alternatives are available at each stop, and the historical commentary is engaging for all participants.",
      },
      {
        question: "How much beer is included in the tastings?",
        answer:
          "The tour includes samples of 5-6 different beer styles, totaling approximately 1-1.5 liters. Food pairings are provided to complement the tastings.",
      },
    ],
    highlights: [
      "Visit the iconic Hofbräuhaus and learn about its history",
      "Explore a traditional brewery and see the brewing process",
      "Sample a variety of local beer styles, including Hefeweizen and Dunkel",
      "Enjoy a guided walk through Munich's historic beer gardens",
      "Learn about the Bavarian Purity Law and its significance",
      "Experience the vibrant beer culture of Munich",
      "Discover hidden gems and local favorites off the tourist path",
      "Capture memorable photos in the heart of Munich's beer scene",
    ],
    inclusions: [
      "Guided tour by a local beer expert",
      "Beer tastings at multiple locations",
      "Traditional Bavarian pretzel",
      "Historical insights into Munich's brewing heritage",
      "Small group experience for personalized attention",
      "Recommendations for local beer halls and breweries to visit after the tour",
      "Souvenir beer mug to take home",
      "Access to exclusive brewery areas not open to the public",
      "Transportation between locations (if applicable)",
      "Optional food pairings available for purchase",
    ],
    exclusions: [
      "Additional food and drinks not specified in the inclusions",
      "Gratuities for the guide (optional but appreciated)",
      "Transportation to and from the meeting point",
      "Personal expenses such as souvenirs or snacks",
      "Travel insurance (recommended but not included)",
      "Any additional tours or experiences not mentioned in the itinerary",
      "Special requests or dietary accommodations (please inform in advance)",
      "Parking fees if you arrive by car",
      "Entrance fees to any additional attractions not included in the tour",
      "Photography services (if desired, please bring your own camera)",
      "Any costs associated with lost or damaged items during the tour",
    ],
    itinerary: [
      "10:00 - Meet at Marienplatz, in front of the New Town Hall",
      "10:15 - Visit Hofbräuhaus and learn about its history",
      "11:00 - Tour a traditional brewery and see the brewing process",
      "12:00 - Sample various local beer styles with food pairings",
      "13:00 - Explore a historic beer garden and enjoy the atmosphere",
      "14:00 - Conclude the tour with recommendations for further exploration",
    ],
  },
  {
    title: "Munich Gourmet Food Walk",
    description:
      "Stroll through Munich’s Viktualienmarkt and surrounding old town as you sample local gourmet specialties. From artisan cheeses and cured meats to handmade pralines and small-batch mustards, this tour is a feast for the senses.",
    city: "Munich",
    country: "Germany",
    region: "Bavaria",
    images: [
      "/images/tours/munich/viktualienmarkt.jpg",
      "/images/tours/munich/gourmet-food.jpg",
    ],
    duration: "3 hours",
    price: "$65",
    rating: 4.7,
    tags: ["Food", "Gourmet", "Walking Tour"],
    isCulinary: true,
    isCultural: true,
    isLocalExperience: true,
    isOutdoor: true,
    isIndoor: true,
    meetingPoint: {
      address: "Viktualienmarkt Main Fountain, Munich",
      coordinates: {
        latitude: 48.1351,
        longitude: 11.5769,
      },
      instructions:
        "Meet near the central fountain. Your guide will hold a 'Gourmet Walk' placard.",
      contactNumber: "+49 89 9876543",
    },
    tourCategoryId: "culinary",
    faqs: [
      {
        question: "Are vegetarian options available?",
        answer:
          "Yes, vegetarian alternatives are provided upon request. Please inform us when booking.",
      },
    ],
    highlights: [
      "Sample artisan Bavarian cheeses and meats",
      "Enjoy locally made pralines and desserts",
      "Explore Viktualienmarkt's vibrant stalls",
      "Meet specialty vendors and learn their stories",
    ],
    inclusions: [
      "Guided food tour with 6–7 tasting stops",
      "Small group setting",
      "Printed food guide to take home",
    ],
    exclusions: [
      "Transportation to/from meeting point",
      "Additional food purchases",
    ],
    itinerary: [
      "11:00 - Introduction and overview at Viktualienmarkt",
      "11:20 - Tasting stops at artisan cheese and charcuterie vendors",
      "12:10 - Sweets and local condiments sampling",
      "13:00 - End of tour with tips on gourmet food shops nearby",
    ],
  },

  {
    title: "Bavarian Cooking Class & Market Tour",
    description:
      "Join a professional Bavarian chef for an immersive market-to-table experience. Begin by shopping for fresh ingredients at a local market, then prepare traditional dishes like Weisswurst, Obatzda, and Kaiserschmarrn in a hands-on cooking session.",
    city: "Munich",
    country: "Germany",
    region: "Bavaria",
    images: [
      "/images/tours/munich/cooking-class.jpg",
      "/images/tours/munich/bavarian-dishes.jpg",
    ],
    duration: "5 hours",
    price: "$110",
    rating: 4.9,
    tags: ["Cooking Class", "Hands-on", "Traditional Food"],
    isCulinary: true,
    isCultural: true,
    isIndoor: true,
    isOutdoor: false,
    isFamilyFriendly: true,
    isRomantic: false,
    isLocalExperience: true,
    isPopular: true,
    meetingPoint: {
      address: "Elisabethmarkt, Munich",
      coordinates: {
        latitude: 48.1581,
        longitude: 11.5752,
      },
      instructions:
        "Meet at the northern gate of Elisabethmarkt. Look for the sign 'Cooking Tour Guide'.",
      contactNumber: "+49 89 7890123",
    },
    tourCategoryId: "culinary",
    faqs: [
      {
        question: "Do I need cooking experience to join?",
        answer:
          "No experience necessary! The chef will guide you step-by-step in an enjoyable and educational atmosphere.",
      },
    ],
    highlights: [
      "Shop for fresh ingredients at a local market",
      "Learn how to cook classic Bavarian recipes",
      "Enjoy the dishes you prepare in a communal meal",
      "Get recipe cards to take home",
    ],
    inclusions: [
      "Market tour and all ingredients",
      "Cooking class with a professional chef",
      "Meal with wine or non-alcoholic beverage",
      "Recipes and souvenir apron",
    ],
    exclusions: ["Transportation to the meeting point", "Gratuities"],
    itinerary: [
      "09:30 - Meet and introduction at Elisabethmarkt",
      "10:00 - Guided market shopping experience",
      "11:00 - Cooking class begins",
      "13:30 - Sit-down meal of prepared dishes",
      "14:30 - Wrap-up and souvenir distribution",
    ],
  },

  {
    title: "Evening Bavarian Food & Drink Crawl",
    description:
      "Unwind in the heart of Munich with this evening culinary crawl through traditional Wirtshäuser and local favorites. Enjoy hearty Bavarian dishes, craft beers, and schnapps, while your guide shares stories of local customs and folklore.",
    city: "Munich",
    country: "Germany",
    region: "Bavaria",
    images: [
      "/images/tours/munich/food-crawl.jpg",
      "/images/tours/munich/schnapps.jpg",
    ],
    duration: "3.5 hours",
    price: "$80",
    rating: 4.6,
    tags: ["Nightlife", "Food", "Beer", "Schnapps"],
    isCulinary: true,
    isNightlife: true,
    isLocalExperience: true,
    isOutdoor: true,
    isRomantic: false,
    isPopular: true,
    isFamilyFriendly: false,
    meetingPoint: {
      address: "Sendlinger Tor, Munich",
      coordinates: {
        latitude: 48.1321,
        longitude: 11.5676,
      },
      instructions:
        "Meet at the main square near Sendlinger Tor U-Bahn exit. Look for your guide with a lantern.",
      contactNumber: "+49 89 8765432",
    },
    tourCategoryId: "culinary",
    faqs: [
      {
        question: "How many stops are included?",
        answer:
          "You will visit 4–5 establishments, each offering a specialty item, beer, or schnapps tasting.",
      },
    ],
    highlights: [
      "Taste hearty Bavarian dishes like Schweinshaxe and Knödel",
      "Enjoy local beers and fruit schnapps at traditional pubs",
      "Hear local legends and culinary history from your guide",
      "Experience Munich’s food scene like a local",
    ],
    inclusions: [
      "Guided evening food crawl",
      "Tasting portions of 4–5 dishes",
      "3 drinks (beer or schnapps)",
      "Local storytelling guide",
    ],
    exclusions: [
      "Transportation to/from meeting point",
      "Extra drinks beyond the included tastings",
    ],
    itinerary: [
      "18:00 - Meet at Sendlinger Tor",
      "18:15 - First food stop and welcome beer",
      "19:00 - Second and third food stops with stories",
      "20:00 - Final drink stop and wrap-up",
    ],
  },
  {
    title: "Munich Art & Expression Walk",
    description:
      "Explore Munich’s vibrant art scene with guided visits to cutting-edge galleries, street art installations, and the historic Lenbachhaus. Gain insight into local artistic movements and enjoy live music performances in hidden courtyards.",
    city: "Munich",
    country: "Germany",
    region: "Bavaria",
    images: [
      "/images/tours/munich/art-tour.jpg",
      "/images/tours/munich/lenbachhaus.jpg",
    ],
    duration: "5 hours",
    price: "$95",
    rating: 4.7,
    tags: ["Art", "Culture", "Music"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCultural: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: false,
    isArtOrMusic: true,
    isOffTheBeatenPath: true,
    isLocalExperience: true,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isOutdoor: true,
    isIndoor: true,
    meetingPoint: {
      address: "Kunstareal District, Munich",
      coordinates: { latitude: 48.1472, longitude: 11.5656 },
      instructions:
        "Meet near the entrance of the Lenbachhaus museum. Your guide will be holding a colorful sign that says 'Munich Art Walk'.",
      contactNumber: "+49 89 99887766",
    },
    tourCategoryId: "art-and-music",
    faqs: [
      {
        question: "Are the gallery entries included?",
        answer: "Yes, all standard entry fees are covered in the tour price.",
      },
    ],
    highlights: [
      "Visit Lenbachhaus and explore the Blue Rider collection",
      "Discover Munich's street art culture in the Gärtnerplatz district",
      "Attend a live acoustic performance in a hidden courtyard",
      "Meet local artists and gallery curators",
    ],
    inclusions: [
      "Gallery admissions",
      "Guided walking tour by an art historian",
      "Live music session",
      "Local art map souvenir",
    ],
    exclusions: [
      "Meals and beverages",
      "Transport to/from meeting point",
      "Additional artwork purchases",
    ],
    itinerary: [
      "10:00 - Meet at Lenbachhaus",
      "10:30 - Explore modern art galleries",
      "12:00 - Break and local coffee stop",
      "13:00 - Street art walking segment",
      "14:00 - Live music performance and conclusion",
    ],
  },
  {
    title: "Munich English Garden Nature Walk",
    description:
      "Stroll through one of Europe’s largest urban parks with a local naturalist. Discover native flora, spot birdlife, and unwind by the tranquil streams and traditional tea house.",
    city: "Munich",
    country: "Germany",
    region: "Bavaria",
    images: [
      "/images/tours/munich/english-garden.jpg",
      "/images/tours/munich/japanese-tea-house.jpg",
    ],
    duration: "3 hours",
    price: "$60",
    rating: 4.6,
    tags: ["Nature", "Wellness", "Walking"],
    isHistorical: false,
    isRomantic: false,
    isAdventure: false,
    isCultural: false,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isWellness: true,
    isLuxury: false,
    isArtOrMusic: false,
    isOffTheBeatenPath: true,
    isLocalExperience: true,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: true,
    isPetFriendly: true,
    isWheelchairAccessible: true,
    isOutdoor: true,
    isIndoor: false,
    meetingPoint: {
      address: "Main entrance to the English Garden, Munich",
      coordinates: { latitude: 48.1587, longitude: 11.5982 },
      instructions:
        "Look for the guide near the entrance gate holding a green flag labeled 'Nature Walk Munich'.",
      contactNumber: "+49 89 11223344",
    },
    tourCategoryId: "nature",
    faqs: [
      {
        question: "Is this tour family-friendly?",
        answer:
          "Yes, it's perfect for families, seniors, and anyone who enjoys a leisurely outdoor experience.",
      },
    ],
    highlights: [
      "Guided walk through the English Garden",
      "Stop at the Japanese Tea House",
      "Learn about local wildlife and botany",
      "Optional barefoot grounding section by the stream",
    ],
    inclusions: [
      "Guided walk by a nature expert",
      "Bilingual tour commentary",
      "Map of the English Garden with flora & fauna guide",
    ],
    exclusions: [
      "Snacks or meals",
      "Tea house purchases",
      "Transport to the garden",
    ],
    itinerary: [
      "09:30 - Meet at garden entrance",
      "10:00 - Begin walking tour along the Isar riverbanks",
      "11:00 - Tea house and relaxation break",
      "12:00 - Wrap-up and nature Q&A",
    ],
  },
  {
    title: "Bavarian Royal Heritage Luxury Day",
    description:
      "Enjoy an opulent day trip from Munich featuring a chauffeured visit to Neuschwanstein Castle, fine Bavarian cuisine, and a private guided tour of royal history with champagne receptions.",
    city: "Munich",
    country: "Germany",
    region: "Bavaria",
    images: [
      "/images/tours/munich/neuschwanstein-luxury.jpg",
      "/images/tours/munich/champagne-tour.jpg",
    ],
    duration: "9 hours",
    price: "$480",
    rating: 4.9,
    tags: ["Luxury", "Castle", "Day Trip"],
    isHistorical: true,
    isRomantic: true,
    isAdventure: false,
    isCultural: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: true,
    isArtOrMusic: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: false,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isOutdoor: true,
    isIndoor: true,
    meetingPoint: {
      address: "Bayerstraße 10A, 80335 München (Limousine Pickup)",
      coordinates: { latitude: 48.1371, longitude: 11.5754 },
      instructions:
        "Your private driver will meet you at the hotel or designated pickup point.",
      contactNumber: "+49 89 33445566",
    },
    tourCategoryId: "luxury",
    faqs: [
      {
        question: "Is lunch included?",
        answer:
          "Yes, a 3-course gourmet meal at a renowned restaurant is included.",
      },
    ],
    highlights: [
      "Private luxury transport to Neuschwanstein Castle",
      "Champagne welcome at scenic overlook",
      "Exclusive guided access to royal chambers",
      "Fine dining experience in Füssen",
    ],
    inclusions: [
      "Private transport and guide",
      "Castle admission and VIP access",
      "Gourmet lunch with wine pairings",
      "Personalized souvenir photo book",
    ],
    exclusions: ["Gratuities", "Hotel accommodations", "Travel insurance"],
    itinerary: [
      "08:00 - Pickup at hotel or central location",
      "10:00 - Champagne overlook and photos",
      "11:00 - Castle tour",
      "13:00 - Gourmet lunch",
      "15:00 - Leisure time in Füssen",
      "17:00 - Return to Munich",
    ],
  },
];

export default munichTours;
