import { Tour } from "@/lib/interfaces/services/tours";

export const naplesTours: Tour[] = [
  {
    title: "Ancient Pompeii & Mt. Vesuvius Adventure",
    description:
      "Explore the remarkably preserved ruins of Pompeii with an expert archaeologist, then hike to the summit of Mt. Vesuvius to peer into the crater of the still-active volcano that buried the ancient city in 79 AD.",
    city: "Naples",
    country: "Italy",
    region: "Campania",
    images: [
      "/images/tours/naples/pompeii-ruins.jpg",
      "/images/tours/naples/mt-vesuvius.jpg",
    ],
    duration: "8 hours",
    price: "$95",
    rating: 4.9,
    tags: ["Archaeological", "Hiking", "Historical"],
    meetingPoint: {
      address: "Piazza Garibaldi, 80142 Naples, Italy",
      coordinates: {
        latitude: 40.8518,
        longitude: 14.2681,
      },
      instructions:
        "Meet in front of Naples Central Station (Napoli Centrale) main entrance. Look for your guide holding a 'Pompeii & Vesuvius Tours' sign.",
      contactNumber: "+39 081 123 4567",
      contactEmail: "info@naplesadventuretours.com",
    },
    highlights: [
      "Tour the extraordinary archaeological site of Pompeii with an expert guide",
      "See incredibly preserved ancient streets, homes, shops, and even plaster casts of victims",
      "Hike to the summit of Mt. Vesuvius for panoramic views of Naples Bay",
      "Peer into the crater of Europe's only active mainland volcano",
      "Learn about the dramatic eruption that preserved Pompeii in such detail",
    ],
    inclusions: [
      "Round-trip transportation from Naples in air-conditioned vehicle",
      "Professional English-speaking archaeologist guide",
      "Skip-the-line entrance tickets to Pompeii archaeological site",
      "Entry fee to Mt. Vesuvius National Park",
      "Small group experience (maximum 12 participants)",
      "Bottled water",
    ],
    exclusions: [
      "Lunch (available for purchase at cafes near Pompeii)",
      "Personal expenses and souvenirs",
      "Gratuities (optional)",
      "Hotel pickup and drop-off (available for extra fee)",
    ],
    itinerary: [
      "8:00 AM - Meet at Naples Central Station",
      "8:30 AM - Departure for Pompeii archaeological site",
      "9:15 AM - Skip-the-line entrance to Pompeii with guided tour",
      "12:00 PM - Lunch break near Pompeii site (meal not included)",
      "1:00 PM - Transfer to Mt. Vesuvius National Park",
      "1:45 PM - Begin hike to the crater of Mt. Vesuvius",
      "2:45 PM - Time at the summit with views of the crater and Bay of Naples",
      "3:30 PM - Descent from volcano and board transportation",
      "4:00 PM - Return journey to Naples",
      "5:00 PM - Arrive at Naples Central Station",
    ],
    cancellationPolicy:
      "Full refund if canceled 48 hours in advance. 50% refund if canceled 24-48 hours before the tour. No refund for cancellations less than 24 hours before scheduled departure.",
    isHistorical: true,
    isRomantic: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isAdventure: true,
    isCultural: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isOutdoor: true,
    isIndoor: true,
    tourCategoryId: "historical",
    faqs: [
      {
        question: "How physically demanding is the hike up Mt. Vesuvius?",
        answer:
          "The hike to the summit takes approximately 30 minutes along a moderately steep, well-maintained gravel path. It requires a reasonable level of fitness, but is manageable for most people who can walk uphill. Comfortable walking shoes are essential. The elevation gain is about 200 meters (650 feet).",
      },
      {
        question: "What should I wear and bring for this tour?",
        answer:
          "Wear comfortable clothing and sturdy walking shoes suitable for archaeological ruins and a gravel volcano path. Bring sun protection (hat, sunscreen, sunglasses), a light jacket (it can be windy at the volcano summit), and a water bottle. During summer months (June-September), the archaeological site can be very hot with limited shade.",
      },
      {
        question: "Is Mt. Vesuvius safe to visit?",
        answer:
          "Yes, Mt. Vesuvius is continuously monitored by the National Institute of Geophysics and Volcanology. The hiking path is well-maintained and kept at a safe distance from the crater edge. The volcano has been mostly dormant since its last eruption in 1944, with only minor seismic activity. Tour operations are suspended in case of any unusual volcanic activity.",
      },
    ],
  },
  {
    title: "Naples Underground & Hidden Tunnels",
    description:
      "Descend 40 meters beneath the streets of Naples to discover a hidden world of ancient Greek aqueducts, Roman reservoirs, WWII air raid shelters, and forgotten subterranean wonders dating back 2,400 years.",
    city: "Naples",
    country: "Italy",
    region: "Campania",
    images: [
      "/images/tours/naples/underground-tunnels.jpg",
      "/images/tours/naples/ancient-aqueduct.jpg",
    ],
    duration: "2.5 hours",
    price: "$45",
    rating: 4.8,
    tags: ["Underground", "Historical", "Unique"],
    meetingPoint: {
      address: "Piazza San Gaetano 68, 80138 Naples, Italy",
      coordinates: {
        latitude: 40.8504,
        longitude: 14.2572,
      },
      instructions:
        "Meet in front of the entrance to Naples Underground (Napoli Sotterranea). Your guide will be waiting in the square holding a blue lantern.",
      contactNumber: "+39 081 296 944",
      contactEmail: "reservations@napoliunderground.com",
    },
    highlights: [
      "Explore a vast network of tunnels, chambers and cisterns beneath Naples",
      "Walk through ancient Greek-Roman aqueducts still containing crystal clear water",
      "Experience total darkness in narrow tunnels by candlelight (optional)",
      "See WWII air raid shelters and the remains of a Greco-Roman theater",
      "Learn about the secret history of Naples and its underground city",
    ],
    inclusions: [
      "Expert local guide",
      "Entrance fees to underground sites",
      "Guided tour in English",
      "Candles for the narrow tunnels portion",
      "Safety equipment where necessary",
    ],
    exclusions: [
      "Hotel pickup and drop-off",
      "Food and beverages",
      "Gratuities",
      "Souvenir photos",
    ],
    itinerary: [
      "10:00 AM - Meet at Piazza San Gaetano",
      "10:15 AM - Introduction to Naples underground history",
      "10:30 AM - Descend 40 meters underground to ancient Greek-Roman aqueducts",
      "11:00 AM - Explore the ancient water cisterns and learn about their engineering",
      "11:30 AM - Navigate narrow tunnels by candlelight (optional)",
      "11:45 AM - Visit WWII air raid shelters and see artifacts from that period",
      "12:15 PM - Explore the subterranean Greco-Roman theater remains",
      "12:30 PM - Return to the surface with time for questions",
      "12:45 PM - Tour ends in Piazza San Gaetano",
    ],
    cancellationPolicy:
      "Full refund if canceled 24 hours in advance. 50% refund if canceled 12-24 hours before the tour. No refund for cancellations less than 12 hours before scheduled tour.",
    isHistorical: true,
    isRomantic: false,
    isOffTheBeatenPath: true,
    isLocalExperience: false,
    isAdventure: true,
    isCultural: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isOutdoor: false,
    isIndoor: true,
    tourCategoryId: "historical",
    faqs: [
      {
        question: "Is this tour suitable for people with claustrophobia?",
        answer:
          "Some sections of the underground tour involve narrow passages and low ceilings, which may be challenging for those with severe claustrophobia. However, the main chambers are spacious, and the narrow tunnel section (about 40 meters long) is optional – you can skip it and rejoin the group afterward. The guide will always point out any upcoming confined spaces.",
      },
      {
        question: "How many stairs are there to navigate?",
        answer:
          "There are approximately 121 steps to descend at the beginning of the tour and the same number to ascend at the end. These are taken at a leisurely pace with stops for explanation, but the tour is unfortunately not suitable for those with significant mobility issues. The underground pathways themselves are mostly level once you've descended.",
      },
      {
        question: "What is the temperature underground?",
        answer:
          "The underground spaces maintain a constant temperature of around 16-18°C (61-64°F) throughout the year. This is pleasantly cool in summer but can feel chilly in winter. We recommend bringing a light jacket or sweater regardless of the season. The humidity level is higher underground than on the surface.",
      },
    ],
  },
  {
    title: "Authentic Neapolitan Pizza Masterclass",
    description:
      "Learn the art of traditional Neapolitan pizza-making with a master pizzaiolo in the birthplace of pizza. Discover the secrets behind the perfect dough, tomato sauce, and stretching technique before enjoying your own creation.",
    city: "Naples",
    country: "Italy",
    region: "Campania",
    images: [
      "/images/tours/naples/pizza-making.jpg",
      "/images/tours/naples/wood-fired-oven.jpg",
    ],
    duration: "3 hours",
    price: "$65",
    rating: 4.9,
    tags: ["Cooking Class", "Food", "Cultural"],
    meetingPoint: {
      address: "Via Tribunali 94, 80138 Naples, Italy",
      coordinates: {
        latitude: 40.8515,
        longitude: 14.2595,
      },
      instructions:
        "Meet at the entrance of 'Antica Pizzeria di Napoli'. Look for the sign with a pizza icon and the words 'Pizza Masterclass'.",
      contactNumber: "+39 081 442 2228",
      contactEmail: "booking@napolipizzaschool.it",
    },
    highlights: [
      "Learn authentic pizza-making from a certified Neapolitan pizzaiolo",
      "Master the art of perfect pizza dough with the true Neapolitan recipe",
      "Practice traditional hand-stretching techniques for the perfect thin center and puffy crust",
      "Bake your creation in a 485°C (905°F) wood-fired oven",
      "Enjoy your own pizza with local wine, dessert, and coffee",
    ],
    inclusions: [
      "All ingredients and cooking equipment",
      "Hands-on pizza making instruction",
      "Full meal including your pizza creation, dessert, and drinks",
      "Glass of local wine, water, and espresso",
      "Recipe booklet to take home",
      "Certificate of participation",
    ],
    exclusions: [
      "Hotel pickup and drop-off",
      "Additional food and beverages",
      "Gratuities",
      "Professional photos (available for purchase)",
    ],
    itinerary: [
      "5:00 PM - Meet at the pizzeria and introduction to Neapolitan pizza history",
      "5:15 PM - Learn about ingredients and their importance in authentic pizza",
      "5:30 PM - Hands-on dough preparation demonstration and practice",
      "6:00 PM - Master the art of stretching pizza dough by hand",
      "6:30 PM - Prepare toppings and assemble your pizza",
      "7:00 PM - Watch as your pizza cooks in the wood-fired oven",
      "7:15 PM - Enjoy your creation with wine and learn about Italian dining culture",
      "7:45 PM - Dessert, coffee, and certificate presentation",
      "8:00 PM - Class concludes",
    ],
    cancellationPolicy:
      "Full refund if canceled 48 hours in advance. 50% refund if canceled 24-48 hours before the class. No refund for cancellations less than 24 hours before scheduled class.",
    isHistorical: false,
    isRomantic: true,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isAdventure: false,
    isCultural: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isOutdoor: false,
    isIndoor: true,
    tourCategoryId: "culinary",
    faqs: [
      {
        question: "Do I need previous cooking experience to participate?",
        answer:
          "No prior experience is necessary! Our master pizzaiolo will guide you through every step, from mixing dough to stretching and topping your pizza. The class is designed to be accessible for complete beginners while still offering techniques that might interest more experienced home cooks.",
      },
      {
        question: "Can dietary restrictions be accommodated?",
        answer:
          "Yes, we can accommodate vegetarian, vegan, and gluten-free participants with advance notice. Please inform us of any dietary restrictions or allergies when booking, and we'll prepare alternative ingredients. For gluten-free participants, we provide separate equipment to avoid cross-contamination.",
      },
      {
        question: "Is this class suitable for children?",
        answer:
          "Yes, this is a family-friendly activity! Children ages 6 and up can participate fully in the pizza-making process. Younger children are welcome to attend but may need parental assistance. Kid-friendly soft drinks are provided instead of wine for participants under 18 years of age.",
      },
    ],
  },
  {
    title: "Amalfi Coast & Positano Day Trip",
    description:
      "Journey along one of the world's most breathtaking coastlines on this day trip from Naples. Explore the cliffside towns of Positano, Amalfi, and Ravello, with their colorful buildings, dramatic views, and Mediterranean charm.",
    city: "Naples",
    country: "Italy",
    region: "Campania",
    images: [
      "/images/tours/naples/amalfi-coast.jpg",
      "/images/tours/naples/positano-view.jpg",
    ],
    duration: "9 hours",
    price: "$125",
    rating: 4.8,
    tags: ["Coastal", "Scenic Drive", "Villages"],
    meetingPoint: {
      address: "Via Mergellina 1, 80122 Naples, Italy",
      coordinates: {
        latitude: 40.8299,
        longitude: 14.2179,
      },
      instructions:
        "Meet at the Mergellina port parking area. Your driver will be waiting next to a white Mercedes van with 'Amalfi Coast Tours' sign.",
      contactNumber: "+39 081 765 4321",
      contactEmail: "booking@amalfitours.it",
    },
    highlights: [
      "Drive along the stunning Amalfi Coast road, considered one of the world's most scenic drives",
      "Explore the vertical town of Positano with its pastel-colored houses cascading down to the sea",
      "Visit the historic maritime republic of Amalfi and its impressive cathedral",
      "Discover the elegant gardens and villas of Ravello perched high above the coast",
      "Enjoy free time for shopping, dining, and swimming at leisure",
    ],
    inclusions: [
      "Transportation in air-conditioned luxury minivan",
      "Professional English-speaking driver/guide",
      "Free time in Positano, Amalfi, and Ravello",
      "Bottled water on board",
      "Live commentary throughout the journey",
      "All parking fees and road tolls",
    ],
    exclusions: [
      "Entrance fees to attractions",
      "Lunch and personal expenses",
      "Gratuities",
      "Hotel pickup and drop-off (available for extra fee)",
      "Licensed guide inside attractions (available upon request)",
    ],
    itinerary: [
      "8:00 AM - Departure from Naples",
      "9:15 AM - Arrive in Positano with free time to explore",
      "11:00 AM - Continue to Amalfi town",
      "11:30 AM - Free time in Amalfi for lunch and exploring the cathedral",
      "2:00 PM - Drive up to Ravello",
      "2:30 PM - Free time to visit Villa Rufolo or Cimbrone gardens (optional)",
      "4:00 PM - Begin return journey to Naples",
      "5:00 PM - Arrive back in Naples",
    ],
    cancellationPolicy:
      "Full refund if canceled 48 hours in advance. 50% refund if canceled 24-48 hours before the tour. No refund for cancellations less than 24 hours before scheduled departure.",
    isHistorical: true,
    isRomantic: true,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isAdventure: false,
    isCultural: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: true,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isOutdoor: true,
    isIndoor: false,
    tourCategoryId: "day-trip",
    faqs: [
      {
        question: "Is the Amalfi Coast road safe?",
        answer:
          "The coastal road is perfectly safe but quite winding. Our professional drivers navigate it daily and are experts at handling its curves. If you're prone to motion sickness, we recommend taking appropriate medication before the trip and sitting near the front of the vehicle. The spectacular views make any minor discomfort well worth it.",
      },
      {
        question: "How much free time do we get in each town?",
        answer:
          "You'll have approximately 1.5 hours in Positano, 2 hours in Amalfi (which includes time for lunch), and 1.5 hours in Ravello. This gives you enough time to explore the main attractions of each town while keeping to our schedule. The driver will clearly communicate meeting points and times in each location.",
      },
      {
        question: "What should I wear for this day trip?",
        answer:
          "Comfortable walking shoes are essential as the towns involve uphill walking and many steps. Casual, light clothing is suitable in summer, with a hat and sunscreen. A light jacket may be needed in spring/fall. If you plan to visit the Amalfi Cathedral, shoulders and knees should be covered. Bring a swimsuit and towel if you'd like to swim during free time.",
      },
    ],
  },
  {
    title: "Naples Street Food & Local Markets Tour",
    description:
      "Savor the authentic flavors of Naples on this guided food tour through the city's historic neighborhoods. Sample local specialties like sfogliatella, pizza fritta, and espresso while exploring vibrant markets and meeting the passionate vendors who preserve Neapolitan culinary traditions.",
    city: "Naples",
    country: "Italy",
    region: "Campania",
    images: [
      "/images/tours/naples/street-food.jpg",
      "/images/tours/naples/local-market.jpg",
    ],
    duration: "3.5 hours",
    price: "$55",
    rating: 4.9,
    tags: ["Food", "Markets", "Walking Tour"],
    meetingPoint: {
      address: "Piazza Dante 1, 80135 Naples, Italy",
      coordinates: {
        latitude: 40.8484,
        longitude: 14.2506,
      },
      instructions:
        "Meet at the center of Piazza Dante by the statue of Dante Alighieri. Your guide will be holding a sign reading 'Naples Food Tour'.",
      contactNumber: "+39 081 887 6543",
      contactEmail: "tastings@naplesfoodtours.com",
    },
    highlights: [
      "Sample 8-10 authentic Neapolitan foods across different neighborhoods",
      "Visit the historic Pignasecca Market, Naples' oldest street market",
      "Try traditional sfogliatella pastry from a century-old bakery",
      "Taste authentic street foods like pizza fritta, arancini, and cuoppo",
      "Learn about Neapolitan coffee culture with an espresso tasting",
    ],
    inclusions: [
      "8-10 food tastings (equivalent to a full meal)",
      "Local expert food guide",
      "Small group experience (maximum 10 people)",
      "One glass of local wine",
      "Bottled water",
      "Food map with recommendations for further exploration",
    ],
    exclusions: [
      "Hotel pickup and drop-off",
      "Additional food and drinks beyond included tastings",
      "Gratuities",
      "Souvenirs and personal shopping",
    ],
    itinerary: [
      "10:00 AM - Meet at Piazza Dante",
      "10:15 AM - Visit traditional pasticceria for sfogliatella and coffee",
      "10:45 AM - Explore Pignasecca Market with fresh mozzarella tasting",
      "11:30 AM - Sample pizza fritta in the Spanish Quarter",
      "12:00 PM - Try traditional fried snacks (cuoppo) from street vendor",
      "12:30 PM - Cheese and salumi tasting with glass of local wine",
      "1:00 PM - Visit family-run restaurant for pasta sample",
      "1:30 PM - Conclude with traditional dessert and limoncello",
    ],
    cancellationPolicy:
      "Full refund if canceled 48 hours in advance. 50% refund if canceled 24-48 hours before the tour. No refund for cancellations less than 24 hours before scheduled tour.",
    isHistorical: false,
    isRomantic: false,
    isOffTheBeatenPath: false,
    isLocalExperience: true,
    isAdventure: false,
    isCultural: true,
    isCulinary: true,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: false,
    isArtOrMusic: false,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: true,
    isPetFriendly: false,
    isWheelchairAccessible: false,
    isOutdoor: true,
    isIndoor: true,
    tourCategoryId: "culinary",
    faqs: [
      {
        question: "Can dietary restrictions be accommodated?",
        answer:
          "Yes, we can accommodate vegetarians with advance notice. Due to the nature of traditional Neapolitan cuisine, vegan and gluten-free diets are more challenging but can be partially accommodated with at least 48 hours' notice. Please inform us of any food allergies or restrictions when booking.",
      },
      {
        question: "How much walking is involved?",
        answer:
          "The tour covers approximately 2.5 km (1.5 miles) at a leisurely pace with frequent stops for food tastings. The route includes some uneven surfaces and occasional steps as we navigate the historic center of Naples. Comfortable walking shoes are recommended.",
      },
      {
        question: "Is this tour suitable for children?",
        answer:
          "Yes, children are welcome! Naples street food is generally kid-friendly, and most children enjoy the pizza, pasta, and dessert tastings. We offer a reduced price for children aged 6-12, and children under 6 can join for free if they share food with parents.",
      },
    ],
  },
  {
    title: "Naples Archaeological Museum & Downtown Highlights",
    description:
      "Discover the extraordinary treasures of ancient Pompeii and Herculaneum preserved in the Naples Archaeological Museum, then explore the historic center with its remarkable churches, piazzas, and underground ruins.",
    city: "Naples",
    country: "Italy",
    region: "Campania",
    images: [
      "/images/tours/naples/archaeological-museum.jpg",
      "/images/tours/naples/historic-center.jpg",
    ],
    duration: "4 hours",
    price: "$60",
    rating: 4.7,
    tags: ["Museum", "History", "Art"],
    meetingPoint: {
      address: "Piazza Museo Nazionale 19, 80135 Naples, Italy",
      coordinates: {
        latitude: 40.8532,
        longitude: 14.2504,
      },
      instructions:
        "Meet at the main entrance of the Naples National Archaeological Museum. Your guide will be waiting with a sign bearing a gladiator image.",
      contactNumber: "+39 081 564 9898",
      contactEmail: "bookings@naplesguidedtours.it",
    },
    highlights: [
      "Explore the world's finest collection of Roman artifacts with an expert archaeologist",
      "See spectacular mosaics and frescoes recovered from Pompeii and Herculaneum",
      "View the famous Secret Cabinet collection of ancient erotic art",
      "Walk through Naples' historic center, a UNESCO World Heritage site",
      "Visit the remarkable Cappella Sansevero to see the sculptural masterpiece 'Veiled Christ'",
    ],
    inclusions: [
      "Skip-the-line entrance to Naples Archaeological Museum",
      "Expert archaeologist guide with specialist knowledge",
      "Entrance to Cappella Sansevero",
      "Small group experience (maximum 8 people)",
      "Audio headsets to hear the guide clearly",
      "Informative historical booklet",
    ],
    exclusions: [
      "Hotel pickup and drop-off",
      "Food and beverages",
      "Gratuities",
      "Additional museum entrance fees not specified",
    ],
    itinerary: [
      "9:00 AM - Meet at National Archaeological Museum",
      "9:15 AM - Skip-the-line entrance and introduction",
      "9:30 AM - Guided tour of the Pompeii and Herculaneum collections",
      "10:30 AM - Visit the Farnese collection of classical sculpture",
      "11:00 AM - Tour the Secret Cabinet collection",
      "11:30 AM - Walk through the historic center to Cappella Sansevero",
      "12:00 PM - Visit Cappella Sansevero and the Veiled Christ",
      "12:45 PM - Conclusion of tour with recommendations for lunch",
    ],
    cancellationPolicy:
      "Full refund if canceled 24 hours in advance. 50% refund if canceled 12-24 hours before the tour. No refund for cancellations less than 12 hours before scheduled tour.",
    isHistorical: true,
    isRomantic: false,
    isOffTheBeatenPath: false,
    isLocalExperience: false,
    isAdventure: false,
    isCultural: true,
    isCulinary: false,
    isSpiritual: false,
    isNightlife: false,
    isWellness: false,
    isLuxury: false,
    isArtOrMusic: true,
    isFree: false,
    isPopular: true,
    isFamilyFriendly: true,
    isPetFriendly: false,
    isWheelchairAccessible: true,
    isOutdoor: false,
    isIndoor: true,
    tourCategoryId: "cultural",
    faqs: [
      {
        question: "Is the Secret Cabinet collection appropriate for children?",
        answer:
          "The Secret Cabinet contains ancient Roman erotic art that some parents might consider inappropriate for young children. Families with children under 14 can choose to skip this section of the museum. Please inform your guide of your preference at the start of the tour.",
      },
      {
        question: "How much walking is involved?",
        answer:
          "This tour includes approximately 2 hours of standing and walking in the museum, plus about 1 kilometer (0.6 miles) of walking through the historic center on uneven surfaces. There are opportunities to sit and rest in the museum. Comfortable shoes are recommended.",
      },
      {
        question: "Is photography allowed in the museum and chapel?",
        answer:
          "Photography without flash is permitted in most areas of the Archaeological Museum. Photography is not allowed inside the Cappella Sansevero to protect the delicate artworks and maintain the sacred atmosphere. Your guide will advise on specific restrictions throughout the tour.",
      },
    ],
  },
];

export default naplesTours;
