import { Tour } from "@/lib/interfaces/services/tours";

export const nassaubahamascaribbeanTours: Tour[] = [
  {
    id: "tour-nassau-1",
    guideId: "guide-nassau-3",
    title: "Nassau Urban Photography Journey",
    description: "Journey through the history of nassau on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "nassau",
    country: "Bahamas",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 5,
    price: "A$91",
    tags: ["Music", "Local Life", "Wellness", "Sightseeing"],
    type: "Romantic Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "14:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "11:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 91,
    currency: "AUD",
    maxGroupSize: 11,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 7,
    included: ["WiFi on board", "Professional guide", "Headsets to hear the guide", "Wine tasting"],
    notIncluded: ["Additional entrance fees", "Luggage storage", "Souvenir photos"],
    requirements: ["Dress code enforced", "E-tickets accepted", "Language proficiency recommended", "COVID-19 vaccination required"],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.4,
  },
  {
    id: "tour-nassau-2",
    guideId: "guide-nassau-2",
    title: "Nassau Essential City Highlights",
    description: "Discover the best of nassau on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "nassau",
    country: "Bahamas",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 8,
    price: "£37",
    tags: ["Local Life", "Beach", "Sightseeing"],
    type: "Market Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "11:00",
        endTime: "14:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "14:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "10:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "09:00",
        endTime: "17:00",
      }
    ],
    pricePerPerson: 37,
    currency: "GBP",
    maxGroupSize: 12,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 7,
    included: ["Gratuities", "Entrance fees", "Snacks"],
    notIncluded: ["Luggage storage", "Personal expenses", "Gratuities", "Souvenir photos"],
    requirements: ["No pets allowed", "Valid ID required", "Bring water and snacks"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 3.7,
  },
  {
    id: "tour-nassau-3",
    guideId: "guide-nassau-3",
    title: "Nassau Historical Walking Tour",
    description: "Discover the best of nassau on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "nassau",
    country: "Bahamas",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 1,
    price: "$79",
    tags: ["Adventure", "Cruise Stop"],
    type: "Accessible Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "13:00",
        endTime: "15:30",
      },
      {
        dayOfWeek: "Monday",
        startTime: "16:00",
        endTime: "22:00",
      }
    ],
    pricePerPerson: 79,
    currency: "USD",
    maxGroupSize: 12,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 48,
    included: ["Food samples", "Use of bicycle", "Professional guide", "Snacks"],
    notIncluded: ["Additional entrance fees", "Travel insurance", "Personal expenses"],
    requirements: ["Language proficiency recommended"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.8,
  },
  {
    id: "tour-nassau-4",
    guideId: "guide-nassau-3",
    title: "Nassau Essential City Highlights",
    description: "Discover the best of nassau on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "nassau",
    country: "Bahamas",
    region: "Caribbean",
    languagesOffered: ["English", "Arabic"],
    durationInHours: 1,
    price: "C$54",
    tags: ["Food & Drink", "Wine & Spirits", "Local Market"],
    type: "Eco Tour",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "14:00",
        endTime: "15:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "16:00",
        endTime: "18:00",
      }
    ],
    pricePerPerson: 54,
    currency: "CAD",
    maxGroupSize: 5,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 45,
    included: ["Lunch", "Entry/Admission tickets", "Audio guide", "Cooking demonstration"],
    notIncluded: ["Food and drinks", "Luggage storage"],
    requirements: ["Advanced fitness level required", "Face masks required", "No pets allowed"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 3.9,
  }
];
