// Auto-generated file for paris tours
// Country: France, Region: France

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const parisfrancefranceTours: Tour[] = [
  {
    id: "tour-paris-1",
    guideId: "guide-paris-5",
    title: "Culinary Heritage Tour",
    description: "Explore the vibrant streets of paris with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "paris",
    country: "France",
    region: "France",
    languagesOffered: [
      "French",
    ],
    price: "€265",
    tags: [
      "Culinary And Food",
      "Family Friendly",
      "Art And Culture",
    ],
    type: "Historical Tour",
    schedule: [
      {
        attractionId: "attraction-paris-4-3",
        dayOfWeek: "Monday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-paris-4-2",
        dayOfWeek: "Friday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-paris-4-6",
        dayOfWeek: "Tuesday",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 265,
    currency: "EUR",
    maxGroupSize: 44,
    minGroupSize: 11,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 26,
    included: [
      "Rain ponchos (if needed)",
      "Entrance fees (if applicable)",
      "Headsets to hear the guide",
      "Gratuities",
      "Local taxes",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Gratuities",
      "Food and drinks at restaurants and/or cafes",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "Tickets must be printed",
      "Face masks required",
      "Passport required",
      "Service animals permitted",
    ],
    cancellationPolicy: "Changes allowed up to 24 hours before the experience starts",
    rating: 4.6,
  },
  {
    id: "tour-paris-2",
    guideId: "guide-paris-3",
    title: "Wildlife Watch Walk",
    description: "Discover the best of paris on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "paris",
    country: "France",
    region: "France",
    languagesOffered: [
      "French",
    ],
    price: "€242",
    tags: [
      "Nature And Scenic",
      "Nightlife And Entertainment",
      "Family Friendly",
    ],
    type: "Cultural Tour",
    schedule: [
      {
        attractionId: "attraction-paris-4-8",
        dayOfWeek: "Wednesday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-paris-4-3",
        dayOfWeek: "Tuesday",
        startTime: "10:00 AM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-paris-4-7",
        dayOfWeek: "Monday",
        startTime: "11:00 AM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 242,
    currency: "EUR",
    maxGroupSize: 29,
    minGroupSize: 14,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 74,
    included: [
      "Entrance fees (if applicable)",
      "Headsets to hear the guide",
      "Snacks",
      "Local taxes",
      "Bottled water",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Hotel accommodations",
      "Transportation to/from the tour start point",
    ],
    requirements: [
      "Valid ID required",
    ],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.4,
  },
  {
    id: "tour-paris-3",
    guideId: "guide-paris-4",
    title: "Visual Arts Discovery",
    description: "Journey through the history of paris on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "paris",
    country: "France",
    region: "France",
    languagesOffered: [
      "French",
    ],
    price: "€180",
    tags: [
      "Art And Culture",
      "Adventure And Thrill",
      "Poetic And Whimsical",
    ],
    type: "Food Tour",
    schedule: [
      {
        attractionId: "attraction-paris-4-7",
        dayOfWeek: "Wednesday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-paris-4-3",
        dayOfWeek: "Thursday",
        startTime: "1:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-paris-4-5",
        dayOfWeek: "Friday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-paris-4-4",
        dayOfWeek: "Sunday",
        startTime: "9:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 180,
    currency: "EUR",
    maxGroupSize: 44,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 103,
    included: [
      "Headsets to hear the guide",
      "Entrance fees (if applicable)",
      "Coffee and/or Tea",
      "Snacks",
      "Gratuities",
      "Souvenir photos",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Optional activities not included in the tour",
      "Airport transfers",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Tickets must be printed",
      "No pets allowed",
    ],
    cancellationPolicy: "50% refund if canceled 48 hours before the experience",
    rating: 4.3,
  },
  {
    id: "tour-paris-4",
    guideId: "guide-paris-5",
    title: "Moonlit Stroll",
    description: "Journey through the history of paris on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "paris",
    country: "France",
    region: "France",
    languagesOffered: [
      "French",
    ],
    price: "€229",
    tags: [
      "Nightlife And Entertainment",
    ],
    type: "Nature Tour",
    schedule: [
      {
        attractionId: "attraction-paris-4-1",
        dayOfWeek: "Tuesday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-paris-4-5",
        dayOfWeek: "Friday",
        startTime: "10:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-paris-4-8",
        dayOfWeek: "Saturday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-paris-4-7",
        dayOfWeek: "Thursday",
        startTime: "10:00 AM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 229,
    currency: "EUR",
    maxGroupSize: 47,
    minGroupSize: 14,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 64,
    included: [
      "Food samples",
      "Coffee and/or Tea",
      "Entrance fees (if applicable)",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Transportation to/from the tour start point",
      "Parking fees",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Not wheelchair accessible",
      "Comfortable walking shoes required",
    ],
    cancellationPolicy: "No refunds for cancellations within 24 hours",
    rating: 4.2,
  },
  {
    id: "tour-paris-5",
    guideId: "guide-paris-5",
    title: "Crater Lakes & Cloud Forests",
    description: "Explore the vibrant streets of paris with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "paris",
    country: "France",
    region: "France",
    languagesOffered: [
      "French",
    ],
    price: "€278",
    tags: [
      "Nature And Scenic",
      "Adventure And Thrill",
      "Nightlife And Entertainment",
    ],
    type: "Mystery Tours",
    schedule: [
      {
        attractionId: "attraction-paris-4-7",
        dayOfWeek: "Tuesday",
        startTime: "10:00 AM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-paris-4-3",
        dayOfWeek: "Monday",
        startTime: "9:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-paris-4-6",
        dayOfWeek: "Friday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-paris-4-8",
        dayOfWeek: "Saturday",
        startTime: "5:00 PM",
        endTime: "8:00 PM",
      },
    ],
    pricePerPerson: 278,
    currency: "EUR",
    maxGroupSize: 26,
    minGroupSize: 11,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 57,
    included: [
      "Rain ponchos (if needed)",
      "Food samples",
      "Hotel pickup and drop-off",
      "Transportation during tour (if applicable)",
      "Souvenir photos",
      "Snacks",
    ],
    notIncluded: [
      "Travel insurance",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "Arrive 15 minutes early",
      "Dress code enforced",
      "Comfortable walking shoes required",
      "Cash only",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 3.8,
  },
  {
    id: "tour-paris-6",
    guideId: "guide-paris-5",
    title: "Cultural Icons and Artifacts Tour",
    description: "Discover the best of paris on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "paris",
    country: "France",
    region: "France",
    languagesOffered: [],
    price: "€140",
    tags: [
      "Art And Culture",
      "City Highlights And History",
    ],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-paris-4-4",
        dayOfWeek: "Wednesday",
        startTime: "8:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-paris-4-6",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
    ],
    pricePerPerson: 140,
    currency: "EUR",
    maxGroupSize: 49,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 54,
    included: [
      "Local taxes",
      "Souvenir photos",
      "Bottled water",
    ],
    notIncluded: [
      "Parking fees",
      "Luggage storage",
    ],
    requirements: [
      "Signed waiver required",
      "Government-issued ID for entry",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 24-hour notice",
    rating: 4.1,
  },
];
