// Auto-generated file for piraeus tours
// Country: Greece, Region: Mainland Greece

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const piraeusgreecemainlandGreeceTours: Tour[] = [
  {
    id: "tour-piraeus-1",
    guideId: "guide-piraeus-3",
    title: "Sunset Landmarks Tour",
    description: "Explore the vibrant streets of piraeus with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "piraeus",
    country: "Greece",
    region: "Mainland Greece",
    languagesOffered: [
      "Greek",
    ],
    price: "€132",
    tags: [
      "Nature And Scenic",
      "Adventure And Thrill",
      "Nightlife And Entertainment",
    ],
    type: "Private Tour",
    schedule: [
      {
        attractionId: "attraction-piraeus-138-1",
        dayOfWeek: "Wednesday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 132,
    currency: "EUR",
    maxGroupSize: 21,
    minGroupSize: 9,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 39,
    included: [
      "Rain ponchos (if needed)",
      "Food samples",
      "Headsets to hear the guide",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Travel insurance",
      "Hotel accommodations",
    ],
    requirements: [
      "No flash photography",
      "Minimum age: 18",
    ],
    cancellationPolicy: "50% refund if canceled 48 hours before the experience",
    rating: 4.2,
  },
  {
    id: "tour-piraeus-2",
    guideId: "guide-piraeus-3",
    title: "The Urban Explorer's Quest",
    description: "Immerse yourself in the local culture of piraeus with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "piraeus",
    country: "Greece",
    region: "Mainland Greece",
    languagesOffered: [
      "Greek",
    ],
    price: "€140",
    tags: [
      "City Highlights And History",
      "Nightlife And Entertainment",
    ],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-piraeus-138-4",
        dayOfWeek: "Sunday",
        startTime: "8:00 AM",
        endTime: "9:00 AM",
      },
      {
        attractionId: "attraction-piraeus-138-3",
        dayOfWeek: "Monday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-1",
        dayOfWeek: "Thursday",
        startTime: "1:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 140,
    currency: "EUR",
    maxGroupSize: 47,
    minGroupSize: 14,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 55,
    included: [
      "Entrance fees (if applicable)",
      "Local taxes",
      "Snacks",
      "Coffee and/or Tea",
    ],
    notIncluded: [
      "Hotel accommodations",
      "Food and drinks at restaurants and/or cafes",
      "Airport transfers",
    ],
    requirements: [
      "COVID-19 vaccination required",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.6,
  },
  {
    id: "tour-piraeus-3",
    guideId: "guide-piraeus-3",
    title: "Street Art & Sidewalk Stories",
    description: "Journey through the history of piraeus on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "piraeus",
    country: "Greece",
    region: "Mainland Greece",
    languagesOffered: [],
    price: "€65",
    tags: [
      "Art And Culture",
    ],
    type: "Nightlife Tours",
    schedule: [
      {
        attractionId: "attraction-piraeus-138-4",
        dayOfWeek: "Monday",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-2",
        dayOfWeek: "Tuesday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-1",
        dayOfWeek: "Wednesday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-3",
        dayOfWeek: "Thursday",
        startTime: "5:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 65,
    currency: "EUR",
    maxGroupSize: 26,
    minGroupSize: 7,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 100,
    included: [
      "Food samples",
      "Headsets to hear the guide",
      "Snacks",
    ],
    notIncluded: [
      "Gratuities",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "COVID-19 vaccination required",
      "Face masks required",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 4.3,
  },
  {
    id: "tour-piraeus-4",
    guideId: "guide-piraeus-4",
    title: "Gravity Defiers: Air & Earth",
    description: "Uncover the secrets of piraeus on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "piraeus",
    country: "Greece",
    region: "Mainland Greece",
    languagesOffered: [],
    price: "€141",
    tags: [
      "Family Friendly",
      "Nightlife And Entertainment",
    ],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-piraeus-138-2",
        dayOfWeek: "Thursday",
        startTime: "10:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-1",
        dayOfWeek: "Saturday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 141,
    currency: "EUR",
    maxGroupSize: 21,
    minGroupSize: 11,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 49,
    included: [
      "Transportation during tour (if applicable)",
      "Bottled water",
      "Rain ponchos (if needed)",
      "Souvenir photos",
      "Food samples",
      "Local taxes",
    ],
    notIncluded: [
      "Luggage storage",
      "Transportation to/from the tour start point",
    ],
    requirements: [
      "Comfortable walking shoes required",
      "Face masks required",
      "COVID-19 vaccination required",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.2,
  },
  {
    id: "tour-piraeus-5",
    guideId: "guide-piraeus-4",
    title: "Crater Lakes & Cloud Forests",
    description: "Immerse yourself in the local culture of piraeus with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "piraeus",
    country: "Greece",
    region: "Mainland Greece",
    languagesOffered: [
      "Greek",
    ],
    price: "€159",
    tags: [
      "Nature And Scenic",
    ],
    type: "Romantic Tour",
    schedule: [
      {
        attractionId: "attraction-piraeus-138-4",
        dayOfWeek: "Thursday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-3",
        dayOfWeek: "Monday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-2",
        dayOfWeek: "Tuesday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-1",
        dayOfWeek: "Wednesday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 159,
    currency: "EUR",
    maxGroupSize: 36,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 23,
    included: [
      "Rain ponchos (if needed)",
      "Snacks",
      "Entrance fees (if applicable)",
      "Gratuities",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Travel insurance",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "No pets allowed",
      "Arrive 15 minutes early",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 24-hour notice",
    rating: 4.8,
  },
  {
    id: "tour-piraeus-6",
    guideId: "guide-piraeus-4",
    title: "Forks and Footpaths",
    description: "Immerse yourself in the local culture of piraeus with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "piraeus",
    country: "Greece",
    region: "Mainland Greece",
    languagesOffered: [
      "Greek",
    ],
    price: "€61",
    tags: [
      "Culinary And Food",
      "City Highlights And History",
      "Nature And Scenic",
      "Nightlife And Entertainment",
    ],
    type: "Nature Tour",
    schedule: [
      {
        attractionId: "attraction-piraeus-138-1",
        dayOfWeek: "Sunday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-4",
        dayOfWeek: "Friday",
        startTime: "1:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-2",
        dayOfWeek: "Monday",
        startTime: "5:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-piraeus-138-3",
        dayOfWeek: "Tuesday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 61,
    currency: "EUR",
    maxGroupSize: 26,
    minGroupSize: 6,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 5,
    included: [
      "Hotel pickup and drop-off",
      "Transportation during tour (if applicable)",
      "Coffee and/or Tea",
    ],
    notIncluded: [
      "Transportation to/from the tour start point",
      "Optional activities not included in the tour",
      "Airport transfers",
    ],
    requirements: [
      "Passport required",
      "COVID-19 vaccination required",
      "Minimum age: 18",
      "No pets allowed",
    ],
    cancellationPolicy: "Changes allowed up to 48 hours before the experience starts",
    rating: 3.9,
  },
];
