// Auto-generated file for punta-cana tours
// Country: Dominican Republic, Region: Dominican Republic

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const puntaCanadominicanRepublicdominicanRepublicTours: Tour[] = [
  {
    id: "tour-punta-cana-1",
    guideId: "guide-punta-cana-4",
    title: "Impressionist Journeys",
    description: "Uncover the secrets of punta-cana on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "punta-cana",
    country: "Dominican Republic",
    region: "Dominican Republic",
    languagesOffered: [
      "English",
    ],
    price: "$110",
    tags: [
      "Art And Culture",
      "Culinary And Food",
      "Family Friendly",
      "Nature And Scenic",
    ],
    type: "Mystery Tours",
    schedule: [
      {
        attractionId: "attraction-punta-cana-146-4",
        dayOfWeek: "Thursday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 110,
    currency: "USD",
    maxGroupSize: 32,
    minGroupSize: 13,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 24,
    included: [
      "Bottled water",
      "Gratuities",
      "Transportation during tour (if applicable)",
      "Entrance fees (if applicable)",
      "Food samples",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Food and drinks at restaurants and/or cafes",
      "Personal expenses",
    ],
    requirements: [
      "Minimum age: 18",
      "No pets allowed",
    ],
    cancellationPolicy: "Changes allowed up to 24 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-punta-cana-2",
    guideId: "guide-punta-cana-3",
    title: "Time Travelers Family Quest",
    description: "Immerse yourself in the local culture of punta-cana with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "punta-cana",
    country: "Dominican Republic",
    region: "Dominican Republic",
    languagesOffered: [
      "English",
    ],
    price: "$99",
    tags: [
      "Family Friendly",
      "Art And Culture",
      "Nature And Scenic",
      "Adventure And Thrill",
    ],
    type: "Food Tour",
    schedule: [
      {
        attractionId: "attraction-punta-cana-146-2",
        dayOfWeek: "Monday",
        startTime: "1:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-punta-cana-146-3",
        dayOfWeek: "Saturday",
        startTime: "2:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-punta-cana-146-1",
        dayOfWeek: "Tuesday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-punta-cana-146-4",
        dayOfWeek: "Wednesday",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 99,
    currency: "USD",
    maxGroupSize: 36,
    minGroupSize: 7,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 90,
    included: [
      "Gratuities",
      "Coffee and/or Tea",
      "Souvenir photos",
      "Food samples",
      "Hotel pickup and drop-off",
      "Headsets to hear the guide",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "Basic fitness level required",
      "Government-issued ID for entry",
      "Bring own headphones",
      "Face masks required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.7,
  },
  {
    id: "tour-punta-cana-3",
    guideId: "guide-punta-cana-4",
    title: "Kid-Friendly Discovery Walk",
    description: "Discover the best of punta-cana on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "punta-cana",
    country: "Dominican Republic",
    region: "Dominican Republic",
    languagesOffered: [
      "English",
    ],
    price: "$68",
    tags: [
      "Family Friendly",
      "Culinary And Food",
      "Nightlife And Entertainment",
    ],
    type: "Religious Tours",
    schedule: [
      {
        attractionId: "attraction-punta-cana-146-1",
        dayOfWeek: "Thursday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 68,
    currency: "USD",
    maxGroupSize: 38,
    minGroupSize: 9,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 7,
    included: [
      "Entrance fees (if applicable)",
      "Food samples",
    ],
    notIncluded: [
      "Parking fees",
      "Travel insurance",
    ],
    requirements: [
      "Bring own headphones",
      "Advanced fitness level required",
    ],
    cancellationPolicy: "Changes allowed up to 24 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-punta-cana-4",
    guideId: "guide-punta-cana-5",
    title: "No Limits: Adventure Reloaded",
    description: "Uncover the secrets of punta-cana on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "punta-cana",
    country: "Dominican Republic",
    region: "Dominican Republic",
    languagesOffered: [
      "English",
    ],
    price: "$39",
    tags: [
      "Adventure And Thrill",
      "Nightlife And Entertainment",
      "Poetic And Whimsical",
    ],
    type: "Cultural Tour",
    schedule: [
      {
        attractionId: "attraction-punta-cana-146-4",
        dayOfWeek: "Wednesday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-punta-cana-146-3",
        dayOfWeek: "Tuesday",
        startTime: "8:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-punta-cana-146-2",
        dayOfWeek: "Saturday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-punta-cana-146-1",
        dayOfWeek: "Sunday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 39,
    currency: "USD",
    maxGroupSize: 34,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 6,
    included: [
      "Hotel pickup and drop-off",
      "Transportation during tour (if applicable)",
      "Rain ponchos (if needed)",
      "Souvenir photos",
      "Food samples",
      "Bottled water",
    ],
    notIncluded: [
      "Travel insurance",
      "Luggage storage",
    ],
    requirements: [
      "Service animals permitted",
      "Valid ID required",
      "Bring own headphones",
      "Signed waiver required",
    ],
    cancellationPolicy: "50% refund if canceled 48 hours before the experience",
    rating: 4.5,
  },
];
