// Auto-generated file for santiago tours
// Country: Chile, Region: Chile

// This file is auto-generated. Do not edit manually.
// Generated on: 2025-06-08T04:09:38.412Z

import { Tour } from "@/lib/interfaces/services/tours";

export const santiagochilechileTours: Tour[] = [
  {
    id: "tour-santiago-1",
    guideId: "guide-santiago-4",
    title: "Nightlife Exploration",
    description: "Explore the vibrant streets of santiago with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "santiago",
    country: "Chile",
    region: "Chile",
    languagesOffered: [
      "Spanish",
    ],
    price: "$43500",
    tags: [
      "Nightlife And Entertainment",
      "Family Friendly",
    ],
    type: "Food Tour",
    schedule: [
      {
        attractionId: "attraction-santiago-37-2",
        dayOfWeek: "Sunday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
    ],
    pricePerPerson: 43500,
    currency: "CLP",
    maxGroupSize: 24,
    minGroupSize: 11,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 91,
    included: [
      "Entrance fees (if applicable)",
      "Headsets to hear the guide",
      "Transportation during tour (if applicable)",
      "Food samples",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Hotel accommodations",
      "Personal expenses",
      "Travel insurance",
    ],
    requirements: [
      "Signed waiver required",
      "Service animals permitted",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4,
  },
  {
    id: "tour-santiago-2",
    guideId: "guide-santiago-3",
    title: "The Velvet Night Circuit",
    description: "Journey through the history of santiago on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "santiago",
    country: "Chile",
    region: "Chile",
    languagesOffered: [
      "Spanish",
    ],
    price: "$95100",
    tags: [
      "Family Friendly",
    ],
    type: "Nightlife Tours",
    schedule: [
      {
        attractionId: "attraction-santiago-37-1",
        dayOfWeek: "Thursday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-santiago-37-2",
        dayOfWeek: "Wednesday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-santiago-37-3",
        dayOfWeek: "Saturday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
    ],
    pricePerPerson: 95100,
    currency: "CLP",
    maxGroupSize: 34,
    minGroupSize: 9,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 15,
    included: [
      "Entrance fees (if applicable)",
      "Local taxes",
      "Food samples",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Parking fees",
      "Optional activities not included in the tour",
      "Gratuities",
    ],
    requirements: [
      "Face masks required",
      "Minimum age: 18",
      "Minimum age: 12",
    ],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 3.9,
  },
  {
    id: "tour-santiago-3",
    guideId: "guide-santiago-1",
    title: "Tea Houses & Temple Bells",
    description: "Discover the best of santiago on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "santiago",
    country: "Chile",
    region: "Chile",
    languagesOffered: [
      "Spanish",
    ],
    price: "$53300",
    tags: [
      "Art And Culture",
      "Nature And Scenic",
      "Family Friendly",
    ],
    type: "Religious Tours",
    schedule: [
      {
        attractionId: "attraction-santiago-37-3",
        dayOfWeek: "Sunday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 53300,
    currency: "CLP",
    maxGroupSize: 48,
    minGroupSize: 5,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 68,
    included: [
      "Hotel pickup and drop-off",
      "Rain ponchos (if needed)",
      "Transportation during tour (if applicable)",
      "Snacks",
      "Bottled water",
    ],
    notIncluded: [
      "Gratuities",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "Cash only",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 24-hour notice",
    rating: 4.1,
  },
  {
    id: "tour-santiago-4",
    guideId: "guide-santiago-5",
    title: "Ink & Ivory: The Calligraphy Circuit",
    description: "Explore the vibrant streets of santiago with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "santiago",
    country: "Chile",
    region: "Chile",
    languagesOffered: [],
    price: "$127900",
    tags: [
      "Art And Culture",
      "City Highlights And History",
      "Nightlife And Entertainment",
    ],
    type: "Romantic Tour",
    schedule: [
      {
        attractionId: "attraction-santiago-37-1",
        dayOfWeek: "Thursday",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-santiago-37-2",
        dayOfWeek: "Wednesday",
        startTime: "11:00 AM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 127900,
    currency: "CLP",
    maxGroupSize: 20,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 15,
    included: [
      "Local taxes",
      "Coffee and/or Tea",
      "Entrance fees (if applicable)",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Travel insurance",
    ],
    requirements: [
      "Valid ID required",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 24-hour notice",
    rating: 4.2,
  },
  {
    id: "tour-santiago-5",
    guideId: "guide-santiago-3",
    title: "Pilgrims & Palaces",
    description: "Uncover the secrets of santiago on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "santiago",
    country: "Chile",
    region: "Chile",
    languagesOffered: [
      "Spanish",
    ],
    price: "$31200",
    tags: [
      "Culinary And Food",
      "Poetic And Whimsical",
      "Nature And Scenic",
      "Art And Culture",
    ],
    type: "Religious Tours",
    schedule: [
      {
        attractionId: "attraction-santiago-37-2",
        dayOfWeek: "Friday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-santiago-37-3",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-santiago-37-1",
        dayOfWeek: "Sunday",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 31200,
    currency: "CLP",
    maxGroupSize: 32,
    minGroupSize: 5,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 42,
    included: [
      "Food samples",
      "Headsets to hear the guide",
      "Local taxes",
      "Rain ponchos (if needed)",
      "Souvenir photos",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Parking fees",
      "Gratuities",
    ],
    requirements: [
      "Bring own headphones",
      "Basic fitness level required",
    ],
    cancellationPolicy: "Changes allowed up to 24 hours before the experience starts",
    rating: 4,
  },
];
