import { Tour } from "@/lib/interfaces/services/tours";

export const santorinigreecemediterraneanTours: Tour[] = [
  {
    id: "tour-santorini-1",
    guideId: "guide-santorini-1",
    title: "santorini Local Markets Exploration",
    description:
      "Explore the vibrant streets of santorini with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "santorini",
    country: "Greece",
    region: "Mediterranean",
    languagesOffered: ["English", "German"],
    durationInHours: 2.5,
    price: "€132",
    tags: ["Local Market", "Nightlife", "Romantic", "LGBTQ+ Friendly"],
    type: "Wildlife Safari",
    schedule: [],
    pricePerPerson: 132,
    currency: "EUR",
    maxGroupSize: 5,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 24,
    included: ["Souvenir photos", "Bottled water", "Entry/Admission tickets"],
    notIncluded: [
      "Food and drinks",
      "Hotel pickup and drop-off",
      "Transportation to/from attractions",
    ],
    requirements: ["Minimum age: 12"],
    cancellationPolicy:
      "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.6,
  },
  {
    id: "tour-santorini-2",
    guideId: "guide-santorini-3",
    title: "santorini Off-the-Beaten-Path Adventure",
    description:
      "Journey through the history of santorini on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "santorini",
    country: "Greece",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 4,
    price: "¥51",
    tags: ["Local Life", "Off the Beaten Path"],
    type: "Scenic Tour",
    schedule: [],
    pricePerPerson: 51,
    currency: "JPY",
    maxGroupSize: 13,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 65,
    included: ["Food samples", "Snacks", "Gratuities"],
    notIncluded: ["Gratuities", "Personal expenses"],
    requirements: ["Service animals permitted"],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 4.7,
  },
  {
    id: "tour-santorini-3",
    guideId: "guide-santorini-3",
    title: "santorini Historical Walking Tour",
    description:
      "Immerse yourself in the local culture of santorini with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "santorini",
    country: "Greece",
    region: "Mediterranean",
    languagesOffered: ["English", "Italian"],
    durationInHours: 2,
    price: "¥24",
    tags: ["Educational", "Adventure", "Cruise Stop"],
    type: "Farm Visit",
    schedule: [],
    pricePerPerson: 24,
    currency: "JPY",
    maxGroupSize: 16,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 62,
    included: ["Lunch", "Food samples", "Snacks", "Bottled water"],
    notIncluded: ["Personal expenses", "Luggage storage"],
    requirements: [
      "Language proficiency recommended",
      "Basic fitness level required",
      "Bring water and snacks",
      "Weather-appropriate clothing",
    ],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-santorini-4",
    guideId: "guide-santorini-3",
    title: "santorini Local Markets Exploration",
    description:
      "Immerse yourself in the local culture of santorini with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "santorini",
    country: "Greece",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 8,
    price: "A$128",
    tags: ["Sightseeing", "Adventure"],
    type: "Underground Tour",
    schedule: [],
    pricePerPerson: 128,
    currency: "AUD",
    maxGroupSize: 7,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 99,
    included: [
      "Snacks",
      "Use of bicycle",
      "Gratuities",
      "Cooking demonstration",
    ],
    notIncluded: ["Transportation to/from attractions", "Food and drinks"],
    requirements: [
      "Swimming required",
      "Advanced fitness level required",
      "Signed waiver required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4,
  },
  {
    id: "tour-santorini-5",
    guideId: "guide-santorini-1",
    title: "santorini Art Galleries Crawl",
    description:
      "Discover the best of santorini on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "santorini",
    country: "Greece",
    region: "Mediterranean",
    languagesOffered: ["English", "Arabic"],
    durationInHours: 2,
    price: "€68",
    tags: ["Art", "Food & Drink", "Culture", "Shopping"],
    type: "Relocation Tour",
    schedule: [
      {
        dayOfWeek: "Monday",
        startTime: "09:00",
        endTime: "15:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "16:00",
        endTime: "23:00",
      },
    ],
    pricePerPerson: 68,
    currency: "EUR",
    maxGroupSize: 18,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 97,
    included: ["Use of bicycle", "Local taxes", "Wine tasting"],
    notIncluded: ["Alcoholic drinks", "Personal expenses"],
    requirements: [
      "Parental consent required",
      "Bring own headphones",
      "Swimming required",
      "Government-issued ID for entry",
    ],
    cancellationPolicy:
      "Free cancellation up to 48 hours before the experience starts",
    rating: 4,
  },
  {
    id: "tour-santorini-6",
    guideId: "guide-santorini-1",
    title: "santorini Local Markets Exploration",
    description:
      "Immerse yourself in the local culture of santorini with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "santorini",
    country: "Greece",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 2,
    price: "$71",
    tags: ["Art", "Adventure", "Hiking"],
    type: "Wine Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "09:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "10:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "16:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "08:00",
        endTime: "20:00",
      },
    ],
    pricePerPerson: 71,
    currency: "USD",
    maxGroupSize: 13,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 99,
    included: [
      "Wine tasting",
      "Skip-the-line access",
      "Rain ponchos",
      "Entry/Admission tickets",
    ],
    notIncluded: [
      "Personal expenses",
      "Hotel pickup and drop-off",
      "Travel insurance",
      "Luggage storage",
    ],
    requirements: ["Government-issued ID for entry"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.7,
  },
  {
    id: "tour-santorini-7",
    guideId: "guide-santorini-1",
    title: "santorini Scenic Views Tour",
    description:
      "Immerse yourself in the local culture of santorini with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "santorini",
    country: "Greece",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 1,
    price: "$21",
    tags: ["Architecture", "Cruise Stop", "Eco", "Family"],
    type: "Ghost Tour",
    schedule: [
      {
        dayOfWeek: "Monday",
        startTime: "09:00",
        endTime: "11:30",
      },
    ],
    pricePerPerson: 21,
    currency: "USD",
    maxGroupSize: 15,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 92,
    included: [
      "Entrance fees",
      "Snacks",
      "Guided commentary",
      "Entry/Admission tickets",
      "WiFi on board",
    ],
    notIncluded: [
      "Hotel pickup and drop-off",
      "Additional entrance fees",
      "Alcoholic drinks",
      "Food and drinks",
    ],
    requirements: ["Credit/debit cards accepted", "Service animals permitted"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.7,
  },
];
