// Auto-generated file for seattle tours
// Country: United States, Region: Washington

// This file is auto-generated. Do not edit manually.
// Generated on: 2025-06-08T04:09:38.413Z

import { Tour } from "@/lib/interfaces/services/tours";

export const seattleunitedStateswashingtonTours: Tour[] = [
  {
    id: "tour-seattle-1",
    guideId: "guide-seattle-2",
    title: "Legends & Laughter Trail",
    description: "Explore the vibrant streets of seattle with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "seattle",
    country: "United States",
    region: "Washington",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$135",
    tags: [
      "Family Friendly",
      "Nature And Scenic",
    ],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-seattle-39-1",
        dayOfWeek: "Wednesday",
        startTime: "3:00 PM",
        endTime: "4:00 PM",
      },
    ],
    pricePerPerson: 135,
    currency: "USD",
    maxGroupSize: 32,
    minGroupSize: 5,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 79,
    included: [
      "Hotel pickup and drop-off",
      "Food samples",
      "Coffee and/or Tea",
    ],
    notIncluded: [
      "Travel insurance",
      "Luggage storage",
      "Airport transfers",
    ],
    requirements: [
      "No flash photography",
      "Service animals permitted",
      "Basic fitness level required",
      "Dress code enforced",
    ],
    cancellationPolicy: "Changes allowed up to 24 hours before the experience starts",
    rating: 3.8,
  },
  {
    id: "tour-seattle-2",
    guideId: "guide-seattle-5",
    title: "Gallery and Studio Walk",
    description: "Explore the vibrant streets of seattle with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "seattle",
    country: "United States",
    region: "Washington",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$178",
    tags: [
      "Art And Culture",
      "Adventure And Thrill",
    ],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-seattle-39-3",
        dayOfWeek: "Monday",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-seattle-39-2",
        dayOfWeek: "Sunday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-seattle-39-1",
        dayOfWeek: "Tuesday",
        startTime: "9:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 178,
    currency: "USD",
    maxGroupSize: 25,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 54,
    included: [
      "Rain ponchos (if needed)",
      "Transportation during tour (if applicable)",
      "Bottled water",
      "Headsets to hear the guide",
      "Coffee and/or Tea",
      "Entrance fees (if applicable)",
      "Snacks",
    ],
    notIncluded: [
      "Personal expenses",
      "Parking fees",
      "Transportation to/from the tour start point",
    ],
    requirements: [
      "Government-issued ID for entry",
      "Swimming required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.6,
  },
  {
    id: "tour-seattle-3",
    guideId: "guide-seattle-1",
    title: "The Falcon's Drop: A Descent Into Sky",
    description: "Immerse yourself in the local culture of seattle with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "seattle",
    country: "United States",
    region: "Washington",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$96",
    tags: [
      "Poetic And Whimsical",
      "Nightlife And Entertainment",
    ],
    type: "Nightlife Tours",
    schedule: [
      {
        attractionId: "attraction-seattle-39-2",
        dayOfWeek: "Monday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 96,
    currency: "USD",
    maxGroupSize: 43,
    minGroupSize: 5,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 22,
    included: [
      "Food samples",
      "Gratuities",
      "Transportation during tour (if applicable)",
      "Bottled water",
    ],
    notIncluded: [
      "Luggage storage",
      "Personal expenses",
    ],
    requirements: [
      "Government-issued ID for entry",
      "Tickets must be printed",
      "Face masks required",
    ],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4,
  },
  {
    id: "tour-seattle-4",
    guideId: "guide-seattle-2",
    title: "The Wild Coast Adventure",
    description: "Journey through the history of seattle on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "seattle",
    country: "United States",
    region: "Washington",
    languagesOffered: [
      "English",
    ],
    price: "$63",
    tags: [
      "Adventure And Thrill",
      "Art And Culture",
      "Nature And Scenic",
    ],
    type: "Food Tour",
    schedule: [
      {
        attractionId: "attraction-seattle-39-3",
        dayOfWeek: "Monday",
        startTime: "8:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-seattle-39-2",
        dayOfWeek: "Friday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
    ],
    pricePerPerson: 63,
    currency: "USD",
    maxGroupSize: 47,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 56,
    included: [
      "Souvenir photos",
      "Bottled water",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Gratuities",
      "Transportation to/from the tour start point",
    ],
    requirements: [
      "Passport required",
      "No pets allowed",
      "Arrive 15 minutes early",
    ],
    cancellationPolicy: "No refunds for cancellations within 24 hours",
    rating: 4.7,
  },
  {
    id: "tour-seattle-5",
    guideId: "guide-seattle-5",
    title: "Moonlit Markets & Midnight Meals",
    description: "Discover the best of seattle on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "seattle",
    country: "United States",
    region: "Washington",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$53",
    tags: [
      "Nightlife And Entertainment",
      "Nature And Scenic",
      "Family Friendly",
      "Poetic And Whimsical",
    ],
    type: "Historical Tour",
    schedule: [
      {
        attractionId: "attraction-seattle-39-2",
        dayOfWeek: "Tuesday",
        startTime: "2:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-seattle-39-1",
        dayOfWeek: "Monday",
        startTime: "8:00 AM",
        endTime: "9:00 AM",
      },
    ],
    pricePerPerson: 53,
    currency: "USD",
    maxGroupSize: 21,
    minGroupSize: 14,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 74,
    included: [
      "Transportation during tour (if applicable)",
      "Coffee and/or Tea",
      "Food samples",
    ],
    notIncluded: [
      "Transportation to/from the tour start point",
      "Additional tickets for attractions",
      "Luggage storage",
      "Gratuities",
    ],
    requirements: [
      "Cash only",
    ],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.1,
  },
  {
    id: "tour-seattle-6",
    guideId: "guide-seattle-5",
    title: "The Great Family Escape",
    description: "Uncover the secrets of seattle on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "seattle",
    country: "United States",
    region: "Washington",
    languagesOffered: [
      "English",
    ],
    price: "$68",
    tags: [
      "Family Friendly",
      "Adventure And Thrill",
    ],
    type: "Historical Tour",
    schedule: [
      {
        attractionId: "attraction-seattle-39-2",
        dayOfWeek: "Tuesday",
        startTime: "12:00 PM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-seattle-39-3",
        dayOfWeek: "Friday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
    ],
    pricePerPerson: 68,
    currency: "USD",
    maxGroupSize: 27,
    minGroupSize: 10,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 38,
    included: [
      "Transportation during tour (if applicable)",
      "Local taxes",
    ],
    notIncluded: [
      "Gratuities",
      "Food and drinks at restaurants and/or cafes",
      "Travel insurance",
    ],
    requirements: [
      "Dress code enforced",
    ],
    cancellationPolicy: "No refunds for cancellations within 24 hours",
    rating: 4.2,
  },
];
