// Auto-generated file for shanghai tours
// Country: China, Region: Asia Pacific

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const shanghaichinaasiaPacificTours: Tour[] = [
  {
    id: "tour-shanghai-1",
    guideId: "guide-shanghai-14",
    title: "Extreme Adventure Challenge",
    description: "Uncover the secrets of shanghai on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "shanghai",
    country: "China",
    region: "Asia Pacific",
    languagesOffered: [
      "Mandarin",
    ],
    price: "¥1068.56",
    tags: [
      "Adventure",
      "Music",
      "Wellness",
    ],
    type: "Cultural Tour",
    schedule: [
      {
        attractionId: "attraction-shanghai-40-2",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-shanghai-40-1",
        dayOfWeek: "Thursday",
        startTime: "1:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 1068.56,
    currency: "CNY",
    maxGroupSize: 40,
    minGroupSize: 11,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 34,
    included: [
      "Transportation during tour (if applicable)",
      "Gratuities",
      "Food samples",
    ],
    notIncluded: [
      "Personal expenses",
      "Travel insurance",
    ],
    requirements: [
      "Cash only",
      "No pets allowed",
      "Swimming required",
    ],
    cancellationPolicy: "No refunds for no-shows",
    rating: 4.1,
  },
  {
    id: "tour-shanghai-2",
    guideId: "guide-shanghai-13",
    title: "Local Artists Showcase",
    description: "Immerse yourself in the local culture of shanghai with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "shanghai",
    country: "China",
    region: "Asia Pacific",
    languagesOffered: [
      "Mandarin",
    ],
    price: "¥953.04",
    tags: [
      "Art",
      "Solo",
      "Wine & Spirits",
    ],
    type: "Architecture Tour",
    schedule: [
      {
        attractionId: "attraction-shanghai-40-3",
        dayOfWeek: "Wednesday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-shanghai-40-1",
        dayOfWeek: "Tuesday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-shanghai-40-2",
        dayOfWeek: "Saturday",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 953.04,
    currency: "CNY",
    maxGroupSize: 48,
    minGroupSize: 5,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 13,
    included: [
      "Snacks",
      "Bottled water",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Personal expenses",
    ],
    requirements: [
      "COVID-19 vaccination required",
      "Arrive 15 minutes early",
      "Minimum age: 18",
    ],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4.9,
  },
  {
    id: "tour-shanghai-3",
    guideId: "guide-shanghai-24",
    title: "Secret Gardens of Love Tour",
    description: "Uncover the secrets of shanghai on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "shanghai",
    country: "China",
    region: "Asia Pacific",
    languagesOffered: [
      "Mandarin",
    ],
    price: "¥1292.38",
    tags: [
      "Sightseeing",
      "Culture",
      "Photography",
    ],
    type: "Romantic Tour",
    schedule: [
      {
        attractionId: "attraction-shanghai-40-1",
        dayOfWeek: "Saturday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-shanghai-40-3",
        dayOfWeek: "Sunday",
        startTime: "12:00 PM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-shanghai-40-2",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "3:00 PM",
      },
    ],
    pricePerPerson: 1292.38,
    currency: "CNY",
    maxGroupSize: 24,
    minGroupSize: 9,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 104,
    included: [
      "Bottled water",
      "Gratuities",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Gratuities",
      "Parking fees",
    ],
    requirements: [
      "COVID-19 vaccination required",
      "Advanced fitness level required",
      "Minimum age: 12",
      "Not wheelchair accessible",
    ],
    cancellationPolicy: "Free cancellation up to 72 hours before the experience starts",
    rating: 4.2,
  },
  {
    id: "tour-shanghai-4",
    guideId: "guide-shanghai-22",
    title: "Mysteries Beneath Tour",
    description: "Explore the vibrant streets of shanghai with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "shanghai",
    country: "China",
    region: "Asia Pacific",
    languagesOffered: [
      "Mandarin",
    ],
    price: "¥281.58",
    tags: [
      "Adventure",
      "Off the Beaten Path",
    ],
    type: "Underground Tour",
    schedule: [
      {
        attractionId: "attraction-shanghai-40-2",
        dayOfWeek: "Thursday",
        startTime: "9:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-shanghai-40-1",
        dayOfWeek: "Sunday",
        startTime: "8:00 AM",
        endTime: "9:00 AM",
      },
    ],
    pricePerPerson: 281.58,
    currency: "CNY",
    maxGroupSize: 23,
    minGroupSize: 5,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 13,
    included: [
      "Snacks",
      "Hotel pickup and drop-off",
      "Entrance fees (if applicable)",
      "Coffee and/or Tea",
      "Local taxes",
    ],
    notIncluded: [
      "Luggage storage",
      "Additional tickets for attractions",
      "Gratuities",
    ],
    requirements: [
      "No flash photography",
      "Comfortable walking shoes required",
      "Passport required",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.5,
  },
  {
    id: "tour-shanghai-5",
    guideId: "guide-shanghai-4",
    title: "Guided Walking Adventure",
    description: "Journey through the history of shanghai on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "shanghai",
    country: "China",
    region: "Asia Pacific",
    languagesOffered: [],
    price: "¥1039.68",
    tags: [
      "Beach",
      "Sightseeing",
      "Spiritual",
    ],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-shanghai-40-3",
        dayOfWeek: "Saturday",
        startTime: "3:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-shanghai-40-2",
        dayOfWeek: "Thursday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-shanghai-40-1",
        dayOfWeek: "Monday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 1039.68,
    currency: "CNY",
    maxGroupSize: 38,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 56,
    included: [
      "Local taxes",
      "Headsets to hear the guide",
      "Gratuities",
    ],
    notIncluded: [
      "Personal expenses",
      "Travel insurance",
      "Additional tickets for attractions",
      "Food and drinks at restaurants and/or cafes",
    ],
    requirements: [
      "Signed waiver required",
      "No flash photography",
    ],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.5,
  },
  {
    id: "tour-shanghai-6",
    guideId: "guide-shanghai-8",
    title: "City Below the Surface",
    description: "Uncover the secrets of shanghai on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "shanghai",
    country: "China",
    region: "Asia Pacific",
    languagesOffered: [],
    price: "¥722",
    tags: [
      "Spiritual",
      "Photography",
      "Educational",
      "Solo",
    ],
    type: "Underground Tour",
    schedule: [
      {
        attractionId: "attraction-shanghai-40-1",
        dayOfWeek: "Thursday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-shanghai-40-3",
        dayOfWeek: "Saturday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
    ],
    pricePerPerson: 722,
    currency: "CNY",
    maxGroupSize: 44,
    minGroupSize: 11,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 33,
    included: [
      "Bottled water",
      "Snacks",
      "Souvenir photos",
      "Gratuities",
      "Coffee and/or Tea",
    ],
    notIncluded: [
      "Gratuities",
      "Parking fees",
    ],
    requirements: [
      "Dress code enforced",
      "Advanced fitness level required",
    ],
    cancellationPolicy: "No changes allowed after booking",
    rating: 4.7,
  },
];
