// Auto-generated file for singapore tours
// Country: Singapore, Region: Singapore

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const singaporesingaporesingaporeTours: Tour[] = [
  {
    id: "tour-singapore-1",
    guideId: "guide-singapore-6",
    title: "Sizzle & Serenity Journey",
    description: "Discover the best of singapore on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "singapore",
    country: "Singapore",
    region: "Singapore",
    languagesOffered: [
      "English",
      "Tamil",
    ],
    price: "S$335",
    tags: [
      "Culinary And Food",
      "Nature And Scenic",
    ],
    type: "Private Tour",
    schedule: [
      {
        attractionId: "attraction-singapore-41-2",
        dayOfWeek: "Saturday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-singapore-41-3",
        dayOfWeek: "Friday",
        startTime: "8:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-singapore-41-1",
        dayOfWeek: "Thursday",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 335,
    currency: "SGD",
    maxGroupSize: 31,
    minGroupSize: 5,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 36,
    included: [
      "Gratuities",
      "Bottled water",
      "Rain ponchos (if needed)",
      "Entrance fees (if applicable)",
    ],
    notIncluded: [
      "Airport transfers",
      "Additional tickets for attractions",
      "Food and drinks at restaurants and/or cafes",
    ],
    requirements: [
      "No pets allowed",
      "Government-issued ID for entry",
      "Swimming required",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 24-hour notice",
    rating: 4.3,
  },
  {
    id: "tour-singapore-2",
    guideId: "guide-singapore-4",
    title: "Nocturnal Nature Walk",
    description: "Journey through the history of singapore on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "singapore",
    country: "Singapore",
    region: "Singapore",
    languagesOffered: [
      "English",
    ],
    price: "S$225",
    tags: [
      "Nightlife And Entertainment",
      "Art And Culture",
    ],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-singapore-41-1",
        dayOfWeek: "Monday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 225,
    currency: "SGD",
    maxGroupSize: 25,
    minGroupSize: 5,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 43,
    included: [
      "Entrance fees (if applicable)",
      "Headsets to hear the guide",
      "Hotel pickup and drop-off",
      "Transportation during tour (if applicable)",
      "Bottled water",
      "Snacks",
    ],
    notIncluded: [
      "Transportation to/from the tour start point",
      "Hotel accommodations",
    ],
    requirements: [
      "Comfortable walking shoes required",
      "No pets allowed",
    ],
    cancellationPolicy: "Free cancellation up to 72 hours before the experience starts",
    rating: 4.2,
  },
  {
    id: "tour-singapore-3",
    guideId: "guide-singapore-4",
    title: "The Summit Seekers Journey",
    description: "Immerse yourself in the local culture of singapore with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "singapore",
    country: "Singapore",
    region: "Singapore",
    languagesOffered: [
      "English",
    ],
    price: "S$211",
    tags: [
      "Adventure And Thrill",
      "Nightlife And Entertainment",
      "Poetic And Whimsical",
    ],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-singapore-41-2",
        dayOfWeek: "Wednesday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 211,
    currency: "SGD",
    maxGroupSize: 30,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: true,
    reviewsCount: 57,
    included: [
      "Bottled water",
      "Entrance fees (if applicable)",
      "Snacks",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Hotel accommodations",
      "Gratuities",
    ],
    requirements: [
      "Not wheelchair accessible",
      "Tickets must be printed",
    ],
    cancellationPolicy: "No refunds for cancellations within 24 hours",
    rating: 3.8,
  },
  {
    id: "tour-singapore-4",
    guideId: "guide-singapore-7",
    title: "Street Art & Sidewalk Stories",
    description: "Uncover the secrets of singapore on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "singapore",
    country: "Singapore",
    region: "Singapore",
    languagesOffered: [
      "English",
      "Malay",
      "Tamil",
    ],
    price: "S$289",
    tags: [
      "Art And Culture",
      "Poetic And Whimsical",
    ],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-singapore-41-1",
        dayOfWeek: "Saturday",
        startTime: "10:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-singapore-41-3",
        dayOfWeek: "Sunday",
        startTime: "11:00 AM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 289,
    currency: "SGD",
    maxGroupSize: 36,
    minGroupSize: 9,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 78,
    included: [
      "Souvenir photos",
      "Gratuities",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Hotel accommodations",
      "Parking fees",
    ],
    requirements: [
      "Cash only",
      "Advanced fitness level required",
      "No flash photography",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.2,
  },
  {
    id: "tour-singapore-5",
    guideId: "guide-singapore-1",
    title: "Gourmet Food Walk",
    description: "Immerse yourself in the local culture of singapore with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "singapore",
    country: "Singapore",
    region: "Singapore",
    languagesOffered: [
      "English",
    ],
    price: "S$161",
    tags: [
      "Culinary And Food",
      "Family Friendly",
    ],
    type: "Historical Tour",
    schedule: [
      {
        attractionId: "attraction-singapore-41-3",
        dayOfWeek: "Monday",
        startTime: "9:00 AM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 161,
    currency: "SGD",
    maxGroupSize: 38,
    minGroupSize: 11,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 57,
    included: [
      "Local taxes",
      "Hotel pickup and drop-off",
      "Transportation during tour (if applicable)",
      "Bottled water",
      "Coffee and/or Tea",
    ],
    notIncluded: [
      "Transportation to/from the tour start point",
      "Personal expenses",
      "Hotel accommodations",
    ],
    requirements: [
      "Service animals permitted",
      "Tickets must be printed",
    ],
    cancellationPolicy: "50% refund if canceled 48 hours before the experience",
    rating: 4,
  },
  {
    id: "tour-singapore-6",
    guideId: "guide-singapore-4",
    title: "Night Markets and Food Tour",
    description: "Journey through the history of singapore on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "singapore",
    country: "Singapore",
    region: "Singapore",
    languagesOffered: [
      "English",
      "Tamil",
    ],
    price: "S$435",
    tags: [
      "Nightlife And Entertainment",
      "Adventure And Thrill",
      "City Highlights And History",
    ],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-singapore-41-2",
        dayOfWeek: "Thursday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 435,
    currency: "SGD",
    maxGroupSize: 36,
    minGroupSize: 10,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 22,
    included: [
      "Entrance fees (if applicable)",
      "Bottled water",
      "Local taxes",
      "Food samples",
    ],
    notIncluded: [
      "Luggage storage",
      "Additional tickets for attractions",
      "Hotel accommodations",
      "Transportation to/from the tour start point",
    ],
    requirements: [
      "Swimming required",
      "Minimum age: 18",
      "Arrive 15 minutes early",
    ],
    cancellationPolicy: "Changes allowed up to 48 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-singapore-7",
    guideId: "guide-singapore-1",
    title: "City Pulse After Hours",
    description: "Journey through the history of singapore on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "singapore",
    country: "Singapore",
    region: "Singapore",
    languagesOffered: [
      "English",
      "Tamil",
    ],
    price: "S$352",
    tags: [
      "Nightlife And Entertainment",
      "Poetic And Whimsical",
    ],
    type: "Nightlife Tours",
    schedule: [
      {
        attractionId: "attraction-singapore-41-3",
        dayOfWeek: "Monday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
    ],
    pricePerPerson: 352,
    currency: "SGD",
    maxGroupSize: 38,
    minGroupSize: 6,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 72,
    included: [
      "Food samples",
      "Local taxes",
      "Snacks",
      "Headsets to hear the guide",
    ],
    notIncluded: [
      "Luggage storage",
      "Gratuities",
      "Food and drinks at restaurants and/or cafes",
    ],
    requirements: [
      "Comfortable walking shoes required",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.7,
  },
];
