// Auto-generated file for southampton tours
// Country: United Kingdom, Region: Northern Europe

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const southamptonunitedKingdomnorthernEuropeTours: Tour[] = [
  {
    id: "tour-southampton-1",
    guideId: "guide-southampton-9",
    title: "Green Tourism Journey",
    description: "Discover the best of southampton on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "southampton",
    country: "United Kingdom",
    region: "Northern Europe",
    languagesOffered: [
      "English",
    ],
    price: "£35",
    tags: [
      "Eco",
      "Educational",
    ],
    type: "Market Tour",
    schedule: [
      {
        attractionId: "attraction-southampton-72-3",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 35,
    currency: "GBP",
    maxGroupSize: 38,
    minGroupSize: 9,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 26,
    included: [
      "Rain ponchos (if needed)",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Luggage storage",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Passport required",
      "Advanced fitness level required",
    ],
    cancellationPolicy: "No refunds for no-shows",
    rating: 4,
  },
  {
    id: "tour-southampton-2",
    guideId: "guide-southampton-2",
    title: "Personal Discovery Tour",
    description: "Uncover the secrets of southampton on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "southampton",
    country: "United Kingdom",
    region: "Northern Europe",
    languagesOffered: [
      "English",
    ],
    price: "£123",
    tags: [
      "Solo",
      "Culinary",
      "Family",
      "Educational",
    ],
    type: "Brewery Tour",
    schedule: [
      {
        attractionId: "attraction-southampton-72-5",
        dayOfWeek: "Saturday",
        startTime: "1:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-southampton-72-4",
        dayOfWeek: "Monday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 123,
    currency: "GBP",
    maxGroupSize: 26,
    minGroupSize: 9,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 49,
    included: [
      "Souvenir photos",
      "Snacks",
      "Food samples",
      "Entrance fees (if applicable)",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Luggage storage",
    ],
    requirements: [
      "Cash only",
      "Not wheelchair accessible",
      "Minimum age: 18",
      "Minimum age: 12",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.1,
  },
  {
    id: "tour-southampton-3",
    guideId: "guide-southampton-1",
    title: "Perfect Shot Tour",
    description: "Uncover the secrets of southampton on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "southampton",
    country: "United Kingdom",
    region: "Northern Europe",
    languagesOffered: [
      "English",
    ],
    price: "£90",
    tags: [
      "Photography",
      "Historical",
      "Religious",
    ],
    type: "Underground Tour",
    schedule: [
      {
        attractionId: "attraction-southampton-72-5",
        dayOfWeek: "Friday",
        startTime: "11:00 AM",
        endTime: "3:00 PM",
      },
      {
        attractionId: "attraction-southampton-72-3",
        dayOfWeek: "Wednesday",
        startTime: "3:00 PM",
        endTime: "4:00 PM",
      },
    ],
    pricePerPerson: 90,
    currency: "GBP",
    maxGroupSize: 25,
    minGroupSize: 13,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 102,
    included: [
      "Hotel pickup and drop-off",
      "Souvenir photos",
      "Local taxes",
      "Bottled water",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Travel insurance",
      "Food and drinks at restaurants and/or cafes",
    ],
    requirements: [
      "Cash only",
      "Swimming required",
      "Not wheelchair accessible",
      "No pets allowed",
    ],
    cancellationPolicy: "Free cancellation up to 72 hours before the experience starts",
    rating: 4,
  },
];
