import { Tour } from "@/lib/interfaces/services/tours";

export const tampaunitedStatescaribbeanTours: Tour[] = [
  {
    id: "tour-tampa-1",
    guideId: "guide-tampa-3",
    title: "Off the Tourist Path Tour",
    description:
      "Discover the best of tampa on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "tampa",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English", "Mandarin"],
    durationInHours: 4,
    price: "$20",
    tags: ["Local Life", "Cruise Stop", "Food & Drink", "Sports"],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-tampa-42-3",
        dayOfWeek: "Sunday",
        startTime: "5:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-tampa-42-1",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 20,
    currency: "USD",
    maxGroupSize: 17,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 5,
    included: [
      "Live entertainment",
      "Bottled water",
      "Use of bicycle",
      "Welcome drink",
    ],
    notIncluded: [
      "Transportation to/from attractions",
      "Additional entrance fees",
      "Alcoholic drinks",
      "Travel insurance",
    ],
    requirements: ["COVID-19 vaccination required", "No flash photography"],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the experience starts",
    rating: 3.9,
  },
  {
    id: "tour-tampa-2",
    guideId: "guide-tampa-2",
    title: "Food & Beverage Pairing Tour",
    description:
      "Explore the vibrant streets of tampa with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "tampa",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English", "French"],
    durationInHours: 1.5,
    price: "£105",
    tags: ["Food & Drink", "Hiking"],
    type: "Scenic Tour",
    schedule: [
      {
        attractionId: "attraction-tampa-42-3",
        dayOfWeek: "Wednesday",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-tampa-42-1",
        dayOfWeek: "Monday",
        startTime: "10:00 AM",
        endTime: "1:00 PM",
      },
      {
        attractionId: "attraction-tampa-42-2",
        dayOfWeek: "Saturday",
        startTime: "4:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 105,
    currency: "GBP",
    maxGroupSize: 8,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 21,
    included: ["Live entertainment", "Entrance fees", "Souvenir photos"],
    notIncluded: ["Travel insurance", "Luggage storage", "Food and drinks"],
    requirements: ["Local SIM card recommended", "Tickets must be printed"],
    cancellationPolicy:
      "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.7,
  },
  {
    id: "tour-tampa-3",
    guideId: "guide-tampa-2",
    title: "Sunset Beach Experience",
    description:
      "Explore the vibrant streets of tampa with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "tampa",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 12,
    price: "A$20",
    tags: ["Beach", "Scenic", "Architecture"],
    type: "Walking Tour",
    schedule: [
      {
        attractionId: "attraction-tampa-42-1",
        dayOfWeek: "Sunday",
        startTime: "5:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-tampa-42-2",
        dayOfWeek: "Saturday",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-tampa-42-3",
        dayOfWeek: "Friday",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 20,
    currency: "AUD",
    maxGroupSize: 19,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 44,
    included: [
      "Skip-the-line access",
      "Headsets to hear the guide",
      "Welcome drink",
      "Live entertainment",
      "Snacks",
    ],
    notIncluded: ["Gratuities"],
    requirements: ["Not wheelchair accessible", "Valid ID required"],
    cancellationPolicy:
      "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.2,
  },
  {
    id: "tour-tampa-4",
    guideId: "guide-tampa-5",
    title: "Collection Explorer",
    description:
      "Uncover the secrets of tampa on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "tampa",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English", "Mandarin"],
    durationInHours: 10,
    price: "$96",
    tags: ["Nature & Wildlife", "Sightseeing", "Shopping"],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-tampa-42-3",
        dayOfWeek: "Tuesday",
        startTime: "8:00 AM",
        endTime: "10:00 AM",
      },
      {
        attractionId: "attraction-tampa-42-1",
        dayOfWeek: "Friday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-tampa-42-2",
        dayOfWeek: "Monday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 96,
    currency: "USD",
    maxGroupSize: 11,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 84,
    included: ["Gratuities", "Souvenir photos", "Rain ponchos"],
    notIncluded: ["Transportation to/from attractions", "Food and drinks"],
    requirements: ["Wheelchair accessible"],
    cancellationPolicy:
      "Free cancellation up to 48 hours before the experience starts",
    rating: 4.6,
  },
  {
    id: "tour-tampa-5",
    guideId: "guide-tampa-5",
    title: "City Lights Night Tour",
    description:
      "Explore the vibrant streets of tampa with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "tampa",
    country: "United States",
    region: "Caribbean",
    languagesOffered: ["English", "Italian"],
    durationInHours: 4,
    price: "¥83",
    tags: ["Nightlife", "Street Food", "Culture", "Nature & Wildlife"],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-tampa-42-1",
        dayOfWeek: "Thursday",
        startTime: "3:00 PM",
        endTime: "5:00 PM",
      },
      {
        attractionId: "attraction-tampa-42-3",
        dayOfWeek: "Tuesday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 83,
    currency: "JPY",
    maxGroupSize: 13,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 55,
    included: [
      "Rain ponchos",
      "Cooking demonstration",
      "Professional guide",
      "Food samples",
    ],
    notIncluded: [
      "Additional entrance fees",
      "Souvenir photos",
      "Food and drinks",
    ],
    requirements: [
      "Local SIM card recommended",
      "No flash photography",
      "Parental consent required",
    ],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 4.1,
  },
];
