import { Tour } from "@/lib/interfaces/services/tours";

export const tokyojapanasiaPacificTours: Tour[] = [
  {
    id: "tour-tokyo-1",
    guideId: "guide-tokyo-1",
    title: "Educational Exploration",
    description:
      "Immerse yourself in the local culture of tokyo with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "tokyo",
    country: "Japan",
    region: "Asia Pacific",
    languagesOffered: ["English"],
    durationInHours: 2.5,
    price: "C$84",
    tags: ["Educational", "Culture", "Scenic"],
    type: "Nature Tour",
    schedule: [
      {
        attractionId: "attraction-tokyo-7-1",
        dayOfWeek: "Saturday",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-tokyo-7-3",
        dayOfWeek: "Monday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-tokyo-7-2",
        dayOfWeek: "Thursday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
    ],
    pricePerPerson: 84,
    currency: "CAD",
    maxGroupSize: 5,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 70,
    included: [
      "Souvenir photos",
      "Professional guide",
      "Local taxes",
      "Rain ponchos",
    ],
    notIncluded: [
      "Transportation to/from attractions",
      "Gratuities",
      "Food and drinks",
      "Luggage storage",
    ],
    requirements: [
      "Not wheelchair accessible",
      "Arrive 15 minutes early",
      "E-tickets accepted",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.6,
  },
  {
    id: "tour-tokyo-2",
    guideId: "guide-tokyo-3",
    title: "Athletic Legacy Tour",
    description:
      "Discover the best of tokyo on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "tokyo",
    country: "Japan",
    region: "Asia Pacific",
    languagesOffered: ["English"],
    durationInHours: 3,
    price: "A$85",
    tags: ["Sports", "Hiking", "LGBTQ+ Friendly"],
    type: "Wildlife Safari",
    schedule: [
      {
        attractionId: "attraction-tokyo-7-3",
        dayOfWeek: "Sunday",
        startTime: "2:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-tokyo-7-1",
        dayOfWeek: "Saturday",
        startTime: "5:00 PM",
        endTime: "8:00 PM",
      },
      {
        attractionId: "attraction-tokyo-7-2",
        dayOfWeek: "Friday",
        startTime: "1:00 PM",
        endTime: "4:00 PM",
      },
    ],
    pricePerPerson: 85,
    currency: "AUD",
    maxGroupSize: 14,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 49,
    included: ["Use of helmet", "Guided commentary", "Entrance fees"],
    notIncluded: [
      "Personal expenses",
      "Luggage storage",
      "Transportation to/from attractions",
      "Gratuities",
    ],
    requirements: [
      "Comfortable walking shoes required",
      "Government-issued ID for entry",
    ],
    cancellationPolicy:
      "Free cancellation up to 72 hours before the experience starts",
    rating: 4.3,
  },
  {
    id: "tour-tokyo-3",
    guideId: "guide-tokyo-6",
    title: "Port-of-Call Journey",
    description:
      "Immerse yourself in the local culture of tokyo with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "tokyo",
    country: "Japan",
    region: "Asia Pacific",
    languagesOffered: ["English"],
    durationInHours: 3,
    price: "£60",
    tags: ["Cruise Stop", "Historical", "Wine & Spirits"],
    type: "Family-Friendly Tour",
    schedule: [
      {
        attractionId: "attraction-tokyo-7-2",
        dayOfWeek: "Friday",
        startTime: "10:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 60,
    currency: "GBP",
    maxGroupSize: 8,
    minGroupSize: 1,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 35,
    included: [
      "Cooking demonstration",
      "Gratuities",
      "Entry/Admission tickets",
      "Headsets to hear the guide",
      "Welcome drink",
      "Bottled water",
      "Live entertainment",
    ],
    notIncluded: ["Transportation to/from attractions"],
    requirements: [
      "COVID-19 vaccination required",
      "Face masks required",
      "Photography allowed",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 3.9,
  },
  {
    id: "tour-tokyo-4",
    guideId: "guide-tokyo-1",
    title: "Kid-Friendly Exploration",
    description:
      "Discover the best of tokyo on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "tokyo",
    country: "Japan",
    region: "Asia Pacific",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 8,
    price: "¥146",
    tags: ["Family", "Luxury", "Eco", "Beach"],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-tokyo-7-3",
        dayOfWeek: "Friday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-tokyo-7-2",
        dayOfWeek: "Tuesday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-tokyo-7-1",
        dayOfWeek: "Wednesday",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 146,
    currency: "JPY",
    maxGroupSize: 19,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 85,
    included: [
      "Professional guide",
      "Guided commentary",
      "Use of helmet",
      "Food samples",
      "Entry/Admission tickets",
      "WiFi on board",
    ],
    notIncluded: ["Gratuities", "Additional entrance fees"],
    requirements: [
      "Basic fitness level required",
      "Must be 21+ to consume alcohol",
      "No pets allowed",
      "Service animals permitted",
    ],
    cancellationPolicy:
      "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4,
  },
];
