// Auto-generated file for washington tours
// Country: United States, Region: District of Columbia

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const washingtonunitedStatesdistrictOfColumbiaTours: Tour[] = [
  {
    id: "tour-washington-1",
    guideId: "guide-washington-2",
    title: "Oaths in Ice and Ember",
    description: "Discover the best of washington on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "washington",
    country: "United States",
    region: "District of Columbia",
    languagesOffered: [
      "English",
    ],
    price: "$184",
    tags: [
      "Poetic And Whimsical",
      "Family Friendly",
      "Nature And Scenic",
    ],
    type: "Cultural Tour",
    schedule: [
      {
        attractionId: "attraction-washington-170-1",
        dayOfWeek: "Monday",
        startTime: "11:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 184,
    currency: "USD",
    maxGroupSize: 41,
    minGroupSize: 8,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 56,
    included: [
      "Snacks",
      "Coffee and/or Tea",
      "Souvenir photos",
      "Local taxes",
      "Transportation during tour (if applicable)",
    ],
    notIncluded: [
      "Food and drinks at restaurants and/or cafes",
      "Parking fees",
    ],
    requirements: [
      "Government-issued ID for entry",
      "Minimum age: 12",
      "Cash only",
      "COVID-19 vaccination required",
    ],
    cancellationPolicy: "No refunds for cancellations within 24 hours",
    rating: 4.3,
  },
  {
    id: "tour-washington-2",
    guideId: "guide-washington-3",
    title: "Starlight Streets: The Night Walk",
    description: "Immerse yourself in the local culture of washington with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "washington",
    country: "United States",
    region: "District of Columbia",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$125",
    tags: [
      "Nightlife And Entertainment",
      "Culinary And Food",
    ],
    type: "Adventure Tour",
    schedule: [
      {
        attractionId: "attraction-washington-170-2",
        dayOfWeek: "Monday",
        startTime: "12:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-washington-170-4",
        dayOfWeek: "Tuesday",
        startTime: "12:00 PM",
        endTime: "4:00 PM",
      },
      {
        attractionId: "attraction-washington-170-3",
        dayOfWeek: "Wednesday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
    ],
    pricePerPerson: 125,
    currency: "USD",
    maxGroupSize: 22,
    minGroupSize: 7,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 104,
    included: [
      "Souvenir photos",
      "Coffee and/or Tea",
      "Food samples",
      "Local taxes",
    ],
    notIncluded: [
      "Gratuities",
      "Travel insurance",
      "Luggage storage",
    ],
    requirements: [
      "Basic fitness level required",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.8,
  },
  {
    id: "tour-washington-3",
    guideId: "guide-washington-6",
    title: "Sunset Landmarks Tour",
    description: "Journey through the history of washington on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "washington",
    country: "United States",
    region: "District of Columbia",
    languagesOffered: [
      "English",
    ],
    price: "$112",
    tags: [
      "Nature And Scenic",
      "Culinary And Food",
    ],
    type: "Cultural Tour",
    schedule: [
      {
        attractionId: "attraction-washington-170-4",
        dayOfWeek: "Wednesday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-washington-170-3",
        dayOfWeek: "Sunday",
        startTime: "10:00 AM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-washington-170-2",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
      },
    ],
    pricePerPerson: 112,
    currency: "USD",
    maxGroupSize: 21,
    minGroupSize: 6,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 14,
    included: [
      "Food samples",
      "Local taxes",
      "Headsets to hear the guide",
    ],
    notIncluded: [
      "Luggage storage",
      "Travel insurance",
    ],
    requirements: [
      "Government-issued ID for entry",
      "No flash photography",
      "Service animals permitted",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4,
  },
  {
    id: "tour-washington-4",
    guideId: "guide-washington-3",
    title: "Lakeside Legends & Campfire Nights",
    description: "Uncover the secrets of washington on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "washington",
    country: "United States",
    region: "District of Columbia",
    languagesOffered: [
      "English",
      "Spanish",
    ],
    price: "$136",
    tags: [
      "Adventure And Thrill",
      "Nature And Scenic",
    ],
    type: "Family Tours",
    schedule: [
      {
        attractionId: "attraction-washington-170-1",
        dayOfWeek: "Friday",
        startTime: "9:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-washington-170-2",
        dayOfWeek: "Monday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      },
    ],
    pricePerPerson: 136,
    currency: "USD",
    maxGroupSize: 42,
    minGroupSize: 9,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 32,
    included: [
      "Headsets to hear the guide",
      "Hotel pickup and drop-off",
      "Local taxes",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Airport transfers",
      "Gratuities",
    ],
    requirements: [
      "Arrive 15 minutes early",
      "COVID-19 vaccination required",
    ],
    cancellationPolicy: "Flexible cancellation policy: full refund with 12-hour notice",
    rating: 4.3,
  },
  {
    id: "tour-washington-5",
    guideId: "guide-washington-1",
    title: "Pilgrims & Palaces",
    description: "Immerse yourself in the local culture of washington with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "washington",
    country: "United States",
    region: "District of Columbia",
    languagesOffered: [
      "English",
    ],
    price: "$105",
    tags: [
      "City Highlights And History",
      "Family Friendly",
    ],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-washington-170-3",
        dayOfWeek: "Monday",
        startTime: "1:00 PM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 105,
    currency: "USD",
    maxGroupSize: 47,
    minGroupSize: 14,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 68,
    included: [
      "Souvenir photos",
      "Transportation during tour (if applicable)",
      "Gratuities",
      "Food samples",
      "Bottled water",
    ],
    notIncluded: [
      "Personal expenses",
      "Gratuities",
    ],
    requirements: [
      "Swimming required",
      "Service animals permitted",
      "Signed waiver required",
      "Minimum age: 12",
    ],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4,
  },
  {
    id: "tour-washington-6",
    guideId: "guide-washington-5",
    title: "Highland Spirits Trek",
    description: "Discover the best of washington on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "washington",
    country: "United States",
    region: "District of Columbia",
    languagesOffered: [
      "English",
    ],
    price: "$68",
    tags: [
      "Nature And Scenic",
      "Culinary And Food",
      "Art And Culture",
      "Family Friendly",
    ],
    type: "Historical Tour",
    schedule: [
      {
        attractionId: "attraction-washington-170-2",
        dayOfWeek: "Thursday",
        startTime: "4:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-washington-170-1",
        dayOfWeek: "Wednesday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-washington-170-3",
        dayOfWeek: "Tuesday",
        startTime: "9:00 AM",
        endTime: "1:00 PM",
      },
    ],
    pricePerPerson: 68,
    currency: "USD",
    maxGroupSize: 41,
    minGroupSize: 8,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 75,
    included: [
      "Bottled water",
      "Rain ponchos (if needed)",
      "Entrance fees (if applicable)",
      "Hotel pickup and drop-off",
      "Snacks",
    ],
    notIncluded: [
      "Airport transfers",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "Cash only",
      "Signed waiver required",
    ],
    cancellationPolicy: "50% refund if canceled 48 hours before the experience",
    rating: 4.6,
  },
];
