// Auto-generated file for yokohama tours
// Country: Japan, Region: Japan

// This file is auto-generated. Do not edit manually.
import { Tour } from "@/lib/interfaces/services/tours";

export const yokohamajapanjapanTours: Tour[] = [
  {
    id: "tour-yokohama-1",
    guideId: "guide-yokohama-2",
    title: "Sunset Landmarks Tour",
    description: "Discover the best of yokohama on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "yokohama",
    country: "Japan",
    region: "Japan",
    languagesOffered: [],
    price: "¥21100",
    tags: [
      "Nature And Scenic",
      "Nightlife And Entertainment",
      "Adventure And Thrill",
    ],
    type: "Family Tours",
    schedule: [
      {
        attractionId: "attraction-yokohama-62-6",
        dayOfWeek: "Wednesday",
        startTime: "11:00 AM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-yokohama-62-5",
        dayOfWeek: "Sunday",
        startTime: "8:00 AM",
        endTime: "11:00 AM",
      },
      {
        attractionId: "attraction-yokohama-62-2",
        dayOfWeek: "Saturday",
        startTime: "9:00 AM",
        endTime: "12:00 PM",
      },
      {
        attractionId: "attraction-yokohama-62-3",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "8:00 PM",
      },
    ],
    pricePerPerson: 21100,
    currency: "JPY",
    maxGroupSize: 31,
    minGroupSize: 10,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 33,
    included: [
      "Snacks",
      "Bottled water",
    ],
    notIncluded: [
      "Optional activities not included in the tour",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Service animals permitted",
      "Signed waiver required",
      "Basic fitness level required",
    ],
    cancellationPolicy: "No refunds for no-shows",
    rating: 4.1,
  },
  {
    id: "tour-yokohama-2",
    guideId: "guide-yokohama-1",
    title: "Cultural Canvas Exploration",
    description: "Discover the best of yokohama on this immersive tour. Experience local culture, history, and cuisine while exploring iconic landmarks and hidden gems.",
    city: "yokohama",
    country: "Japan",
    region: "Japan",
    languagesOffered: [],
    price: "¥17900",
    tags: [
      "Art And Culture",
      "Adventure And Thrill",
      "Nightlife And Entertainment",
    ],
    type: "Bike Tour",
    schedule: [
      {
        attractionId: "attraction-yokohama-62-1",
        dayOfWeek: "Tuesday",
        startTime: "5:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-yokohama-62-6",
        dayOfWeek: "Friday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
      {
        attractionId: "attraction-yokohama-62-2",
        dayOfWeek: "Monday",
        startTime: "9:00 AM",
        endTime: "12:00 PM",
      },
    ],
    pricePerPerson: 17900,
    currency: "JPY",
    maxGroupSize: 49,
    minGroupSize: 5,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 97,
    included: [
      "Gratuities",
      "Bottled water",
      "Transportation during tour (if applicable)",
      "Hotel pickup and drop-off",
    ],
    notIncluded: [
      "Additional tickets for attractions",
      "Food and drinks at restaurants and/or cafes",
      "Optional activities not included in the tour",
    ],
    requirements: [
      "Advanced fitness level required",
      "Passport required",
    ],
    cancellationPolicy: "No refunds for cancellations within 24 hours",
    rating: 3.8,
  },
  {
    id: "tour-yokohama-3",
    guideId: "guide-yokohama-4",
    title: "No Limits: Adventure Reloaded",
    description: "Immerse yourself in the local culture of yokohama with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "yokohama",
    country: "Japan",
    region: "Japan",
    languagesOffered: [
      "Japanese",
    ],
    price: "¥18200",
    tags: [
      "Adventure And Thrill",
      "Poetic And Whimsical",
      "Nature And Scenic",
      "City Highlights And History",
    ],
    type: "Museum Tour",
    schedule: [
      {
        attractionId: "attraction-yokohama-62-4",
        dayOfWeek: "Tuesday",
        startTime: "4:00 PM",
        endTime: "7:00 PM",
      },
      {
        attractionId: "attraction-yokohama-62-2",
        dayOfWeek: "Sunday",
        startTime: "2:00 PM",
        endTime: "6:00 PM",
      },
      {
        attractionId: "attraction-yokohama-62-7",
        dayOfWeek: "Friday",
        startTime: "12:00 PM",
        endTime: "2:00 PM",
      },
    ],
    pricePerPerson: 18200,
    currency: "JPY",
    maxGroupSize: 23,
    minGroupSize: 14,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 94,
    included: [
      "Hotel pickup and drop-off",
      "Headsets to hear the guide",
      "Local taxes",
      "Rain ponchos (if needed)",
    ],
    notIncluded: [
      "Travel insurance",
      "Optional activities not included in the tour",
      "Airport transfers",
      "Additional tickets for attractions",
    ],
    requirements: [
      "Face masks required",
      "Government-issued ID for entry",
    ],
    cancellationPolicy: "Changes allowed up to 24 hours before the experience starts",
    rating: 4.6,
  },
];
