import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Ambassador
export const theAmbassadorRooms: RoomOption[] = [
  {
    id: "hotel-rio-de-janeiro-6-room-5-Single-CityView",
    name: "Signature Single Penthouse",
    description: "Indulge in the ornate atmosphere of our single penthouse, with spectacular where the city comes alive at dusk, created with both style and function in mind, and including climate control for your comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 456,
    currency: "BRL",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-rio-de-janeiro-6-room-5-King-GardenView",
    name: "Deluxe King Suite",
    description: "Our Deluxe-themed king suite offers artistic luxury, panoramic where you can relax in a natural oasis, and with a private balcony or terrace, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 862,
    currency: "BRL",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-rio-de-janeiro-6-room-5-Twin-None",
    name: "Superior Twin Villa",
    description: "Relax in our ornate indulgent twin villa featuring with a pleasant outlook, along with with a luxurious soaking tub and featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 462,
    currency: "BRL",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-rio-de-janeiro-6-room-5-SofaBed-OceanView",
    name: "Deluxe Sofa Bed Apartment",
    description: "Our Deluxe-themed sofa bed apartment offers expansive luxury, panoramic featuring uninterrupted ocean vistas, and with a private balcony or terrace, inspired by decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 638,
    currency: "BRL",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  }
];
