import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Belo Horizonte Grand
export const theBeloHorizonteGrandRooms: RoomOption[] = [
  {
    id: "hotel-rio-de-janeiro-1-room-0-Queen-OceanView",
    name: "Executive Queen Loft",
    description: "A traditional queen retreat with a view of the ocean's horizon, featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 937,
    currency: "BRL",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-rio-de-janeiro-1-room-0-Twin-None",
    name: "Standard Twin Room",
    description: "Relax in our serene vintage twin room featuring with a pleasant outlook, along with including climate control for your comfort and designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 605,
    currency: "BRL",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-rio-de-janeiro-1-room-0-Single-CityView",
    name: "Horizon Single Suite",
    description: "Horizon-themed suite with exquisite decor, where city lights twinkle at night, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 583,
    currency: "BRL",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-rio-de-janeiro-1-room-0-Queen-CityView",
    name: "Deluxe Queen Room",
    description: "Our Deluxe-themed queen room offers traditional luxury, panoramic where the city comes alive at dusk, and with high-speed internet access, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 769,
    currency: "BRL",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-rio-de-janeiro-1-room-0-Twin-MountainView",
    name: "Classic Twin Villa",
    description: "Enjoy a indulgent stay in our Classic-themed twin villa, offering where you can enjoy the serenity of mountain life, with a spacious seating area, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 693,
    currency: "BRL",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-rio-de-janeiro-1-room-0-Double-OceanView",
    name: "Luxury Double Penthouse",
    description: "Our soothing Luxury-themed penthouse offers with a view of the ocean's changing tides, sophisticated comfort, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 864,
    currency: "BRL",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  }
];
