import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Barcelona Sea View
export const barcelonaSeaViewRooms: RoomOption[] = [
  {
    id: "hotel-madrid-9-room-8-King-OceanView",
    name: "Standard King Apartment",
    description: "Experience our refined, eclectic king apartment where you can hear the soothing sound of the sea, featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 145,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-madrid-9-room-8-SofaBed-CityView",
    name: "Modern Sofa Bed Studio",
    description: "Enjoy a homey stay in our Modern-themed sofa bed studio, offering showcasing the urban landscape, with a luxurious soaking tub, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 78,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-madrid-9-room-8-King-CityView",
    name: "Superior King Penthouse",
    description: "Enjoy a sleek stay in our Superior-themed king penthouse, offering where the city comes alive at dusk, with blackout curtains for a perfect night's sleep, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 145,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-madrid-9-room-8-King-MountainView",
    name: "Premium King Apartment",
    description: "Premium-themed apartment with comfortable decor, where you can escape to the mountains, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 162,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-madrid-9-room-8-King-GardenView",
    name: "Luxury King Room",
    description: "Our relaxing Luxury-themed room offers with a view of shaded garden paths, serene comfort, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 139,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-madrid-9-room-8-Single-GardenView",
    name: "Standard Single Room",
    description: "Relax in our comfortable modern single room featuring where you can enjoy the sights and sounds of nature, along with including climate control for your comfort and created with both style and function in mind.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 76,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-madrid-9-room-8-Double-MountainView",
    name: "Deluxe Double Penthouse",
    description: "Step into a well-proportioned double penthouse that combines Deluxe-themed with breathtaking where you can enjoy the mountains' majestic presence, complemented by featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 99,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-madrid-9-room-8-Single-OceanView",
    name: "Luxury Single Penthouse",
    description: "Indulge in the industrial atmosphere of our single penthouse, with spectacular with a view of the sandy beaches, created with both style and function in mind, and with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 95,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-madrid-9-room-8-Double-CityView",
    name: "Premium Double Suite",
    description: "Discover the charm of this Premium-themed double suite, complete with rustic ambiance, stunning with a view of iconic landmarks, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 102,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-madrid-9-room-8-Twin-CityView",
    name: "Deluxe Twin Loft",
    description: "Relax in our peaceful elegant twin loft featuring with stunning views of the city skyline, along with with a spacious work area and featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 86,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  }
];
