import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Seville Flamenco Inn
export const sevilleFlamencoInnRooms: RoomOption[] = [
  {
    id: "hotel-madrid-10-room-9-Double-OceanView",
    name: "Deluxe Double Studio",
    description: "A fashionable double studio designed for glamorous comfort, with where the horizon meets the ocean and featuring premium bath amenities, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 261,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-madrid-10-room-9-Single-GardenView",
    name: "Luxury Single Suite",
    description: "Luxury-themed suite with sophisticated decor, where you can relax in a garden haven, and with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 209,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-madrid-10-room-9-King-MountainView",
    name: "Classic King Villa",
    description: "Relax in our refined bohemian king villa featuring with a view of the mountains' natural beauty, along with complete with a well-appointed bathroom and featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 340,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-madrid-10-room-9-Single-MountainView",
    name: "Executive Single Loft",
    description: "Relax in our futuristic gentle single loft featuring overlooking spectacular mountain ranges, along with equipped with all the modern conveniences and designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 204,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-madrid-10-room-9-SofaBed-None",
    name: "Horizon Sofa Bed Loft",
    description: "Experience our soft, intimate sofa bed loft with a pleasant outlook, with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 189,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-madrid-10-room-9-Double-None",
    name: "Tranquility Double Room",
    description: "A minimalist double room designed for bohemian comfort, with with a pleasant outlook and featuring premium bath amenities, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 201,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-madrid-10-room-9-Double-MountainView",
    name: "Luxury Double Apartment",
    description: "Unwind in this spacious double apartment where you can enjoy the peace of the highlands, including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 272,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-madrid-10-room-9-Double-CityView",
    name: "Horizon Double Apartment",
    description: "Discover the charm of this Horizon-themed double apartment, complete with pleasant ambiance, stunning where you can watch the city wake up, and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 242,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-madrid-10-room-9-Queen-GardenView",
    name: "Modern Queen Studio",
    description: "Experience our glamorous, spacious queen studio with a view of the garden's peaceful ambiance, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 309,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-madrid-10-room-9-Single-OceanView",
    name: "Serenity Single Apartment",
    description: "A traditional single retreat where the horizon meets the ocean, featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Hearing Support", "Wheelchair Accessible"],
    pricePerNight: 227,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  }
];
