import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Franz Josef Glacier Inn
export const franzJosefGlacierInnRooms: RoomOption[] = [
  {
    id: "hotel-queenstown-5-room-4-King-OceanView",
    name: "Signature King Studio",
    description: "A expansive king retreat featuring uninterrupted ocean vistas, with Maori-inspired motifs.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 1072,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-queenstown-5-room-4-Single-MountainView",
    name: "Executive Single Suite",
    description: "Enjoy a contemporary stay in our Executive-themed single suite, offering where you can escape to the mountains, with carefully selected furnishings, and unique touches of showcasing the serene beauty of New Zealand landscapes.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 560,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-queenstown-5-room-4-SofaBed-CityView",
    name: "Alpine Sofa Bed Studio",
    description: "Relax in our comfortable expansive sofa bed studio featuring with a view of the city's waterfront, along with offering a unique blend of style and comfort and showcasing the serene beauty of New Zealand landscapes.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 570,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-queenstown-5-room-4-King-MountainView",
    name: "Bayview King Apartment",
    description: "Indulge in the futuristic atmosphere of our king apartment, with spectacular with panoramic views of the surrounding mountains, showcasing the serene beauty of New Zealand landscapes, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 1088,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-queenstown-5-room-4-Single-CityView",
    name: "Alpine Single Penthouse",
    description: "Unwind in this avant-garde single penthouse where you can enjoy the city's energy, with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Hearing Support"],
    pricePerNight: 538,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
