import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Radisson Collection Hotel, Moscow
export const radissonCollectionHotelMoscowRooms: RoomOption[] = [
  {
    id: "hotel-moscow-7-room-6-Queen-GardenView",
    name: "Kremlin Queen Room",
    description: "Our homey Kremlin-themed room offers with a view of the garden's peaceful ambiance, broad comfort, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Hearing Support", "Elevator", "Wheelchair Accessible"],
    pricePerNight: 621346,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-moscow-7-room-6-King-CityView",
    name: "Tsar King Studio",
    description: "Our comfy Tsar-themed studio offers with a view of iconic landmarks, commodious comfort, and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 720549,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-moscow-7-room-6-Queen-None",
    name: "Premium Queen Penthouse",
    description: "Enjoy a ample stay in our Premium-themed queen penthouse, offering with a pleasant outlook, featuring a curated minibar selection, and unique touches of featuring opulent, imperial-inspired decor.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 560179,
    currency: "RUB",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-moscow-7-room-6-Double-CityView",
    name: "Signature Double Suite",
    description: "Relax in our heartwarming upscale double suite featuring with a front-row seat to the city's heartbeat, along with complete with a well-appointed bathroom and offering a warm retreat from the cold outside.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 542521,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-moscow-7-room-6-SofaBed-MountainView",
    name: "Snowflake Sofa Bed Loft",
    description: "Unwind in this traditional sofa bed loft with a view of the mountains' rugged terrain, featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 608797,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-moscow-7-room-6-SofaBed-None",
    name: "Snowflake Sofa Bed Room",
    description: "Relax in our inviting heartwarming sofa bed room featuring with a pleasant outlook, along with with a spacious work area and featuring opulent, imperial-inspired decor.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 418092,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-moscow-7-room-6-King-None",
    name: "Amber King Room",
    description: "Enjoy a palatial stay in our Amber-themed king room, offering with a pleasant outlook, with a spacious seating area, and unique touches of blending historic grandeur with modern luxury.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 708726,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-moscow-7-room-6-King-OceanView",
    name: "Classic King Loft",
    description: "Indulge in the voluminous atmosphere of our king loft, with spectacular with a panoramic view of the coastline, with rich fabrics and ornate details, and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 918721,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  }
];
