import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Grand Central Hotel
export const grandCentralHotelRooms: RoomOption[] = [
  {
    id: "hotel-buenos-aires-1-room-0",
    name: "Luxury Single Loft",
    description: "Step into a well-proportioned single loft that combines Luxury-themed with breathtaking where city lights twinkle at night, complemented by including climate control for your comfort.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Blackout Curtains", "Soundproofing", "Seating Area"],
    pricePerNight: 187,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-buenos-aires-1-room-0",
    name: "Tranquility Double Penthouse",
    description: "Unwind in this extensive double penthouse with a pleasant outlook, with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Bathtub", "Refrigerator", "Board Games", "Family Room", "Jacuzzi Tub"],
    pricePerNight: 189,
    currency: "ARS",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-buenos-aires-1-room-0",
    name: "Modern Double Villa",
    description: "Experience our peaceful, regal double villa featuring awe-inspiring mountain scenery, with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "In-Room Safe", "Outdoor Furniture", "Wake-Up Service"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 233,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-buenos-aires-1-room-0",
    name: "Tranquility Queen Apartment",
    description: "Step into a room-filled queen apartment that combines Tranquility-themed with breathtaking with a view of the mountains' serene beauty, complemented by with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Bathtub", "Connecting Rooms", "In-Room Safe", "Luggage Rack", "Fireplace", "Sauna"],
    pricePerNight: 287,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-buenos-aires-1-room-0",
    name: "Tranquility Queen Studio",
    description: "Relax in our majestic retro queen studio featuring with a view of shaded garden paths, along with with a spacious work area and featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Mini Bar", "Connecting Rooms", "Refrigerator", "Fitness Equipment", "Dining Table", "Kitchenette"],
    pricePerNight: 276,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-buenos-aires-1-room-0",
    name: "Modern King Villa",
    description: "Relax in our roomy homey king villa featuring where you can relax in a natural oasis, along with with carefully selected furnishings and featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Connecting Rooms", "Mini Bar", "Dining Table", "Complimentary Bottled Water"],
    pricePerNight: 316,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
