import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Harbor House
export const theHarborHouseRooms: RoomOption[] = [
  {
    id: "hotel-buenos-aires-1-room-0",
    name: "Premium King Room",
    description:
      "This sleek king accommodation offers where you can find solace in nature's embrace, featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Seating Area",
      "Smoke Detector",
      "Refrigerator",
      "Dining Table",
      "Accessible Room",
      "Fireplace",
    ],
    pricePerNight: 288,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-buenos-aires-1-room-0",
    name: "Horizon King Villa",
    description:
      "Horizon-themed villa with exquisite decor, where the horizon meets the ocean, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Seating Area",
      "Fitness Equipment",
      "Luggage Rack",
      "Bathtub",
    ],
    pricePerNight: 317,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
];
