// Auto-generated file for montreal hotels
// Do not edit manually, use scripts/generate-hotels.mjs to update

// Generated on: 2025-06-08T04:09:38.933Z

import { Hotel } from "@/lib/interfaces/services/rentals";

export const montrealHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "help@banffspringsretreat.com",
      contactPhone: "+671 445-957-8129",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Designated Areas",
    },
    id: "hotel-montreal-1",
    name: "Banff Springs Retreat",
    address: "176 Dundas Pl",
    rating: 4,
    accommodationType: "Resort",
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 32,
    isPetFriendly: true,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "office@kamloopsthompsonhotel.com",
      contactPhone: "+391 821-129-2500",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Allowed",
    },
    id: "hotel-montreal-2",
    name: "Kamloops Thompson Hotel",
    address: "82 Scenic Queen Dr",
    rating: 4,
    accommodationType: "Boutique Inn",
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 56,
    isPetFriendly: false,
    currency: "CAD",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reachus@saskatooncitylodge.com",
      contactPhone: "+238 170-719-7021",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Allowed",
    },
    id: "hotel-montreal-3",
    name: "Saskatoon City Lodge",
    address: "131 Yonge Cres",
    rating: 4,
    accommodationType: "Luxury Hotel",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 48,
    isPetFriendly: false,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "info@quebeccityinn.com",
      contactPhone: "+369 531-629-1193",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-montreal-4",
    name: "Quebec City Inn",
    address: "153 Dundas Rd",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 20,
    isPetFriendly: true,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "office@thelaurentian.com",
      contactPhone: "+803 137-511-7146",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-montreal-5",
    name: "The Laurentian",
    address: "25 Queen Way",
    rating: 3,
    accommodationType: "Luxury Lodge",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 26,
    isPetFriendly: false,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reception@thelaurentian.com",
      contactPhone: "+103 334-346-9042",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Not Allowed",
    },
    id: "hotel-montreal-6",
    name: "The Laurentian",
    address: "46 Jasper Cres",
    rating: 4,
    accommodationType: "Luxury Villa",
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 56,
    isPetFriendly: false,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "customerservice@timberlineinn.com",
      contactPhone: "+254 294-932-5166",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-montreal-7",
    name: "Timberline Inn",
    address: "5 Stanley Way",
    rating: 4,
    accommodationType: "Hostel",
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 47,
    isPetFriendly: true,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hi@bayviewharborhotel.com",
      contactPhone: "+767 912-947-2976",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Allowed",
    },
    id: "hotel-montreal-8",
    name: "Bayview Harbor Hotel",
    address: "96 Rideau Rd",
    rating: 4,
    accommodationType: "Luxury Hotel",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 35,
    isPetFriendly: true,
    currency: "CAD",
    isPopular: false,
  },
  {
    id: "hotel-montreal-9",
    name: "The Laurentian",
    address: "184 King Pl",
    rating: 3,
    accommodationType: "Family Resort",
    amenities: ["Parking", "Spa", "Room Service", "Bar", "Conference Room", "Restaurant", "Business Center", "Fitness Center", "Airport Shuttle", "24-Hour Front Desk"],
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 33,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "inquiries@thelaurentian.com",
      contactPhone: "+703 715-739-6414",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-montreal-10",
    name: "St. John's Harbour Inn",
    address: "220 Historic Wellington Pl",
    rating: 4,
    accommodationType: "Hotel",
    amenities: ["Fitness Center", "Conference Room", "Swimming Pool", "Room Service", "Parking", "Non-Smoking Rooms"],
    accessibilityFeatures: ["Visual Aids"],
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 47,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "customerservice@st.john'sharbourinn.com",
      contactPhone: "+672 692-339-2283",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-montreal-11",
    name: "Winnipeg Prairie Suites",
    address: "245 Elgin Blvd",
    rating: 4,
    accommodationType: "Luxury Lodge",
    amenities: ["Non-Smoking Rooms", "Free Wi-Fi", "Spa", "Conference Room", "Swimming Pool", "Room Service", "Parking"],
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 32,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "admin@winnipegprairiesuites.com",
      contactPhone: "+527 906-940-2424",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  }
];
