import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Saskatoon City Lodge
export const saskatoonCityLodgeRooms: RoomOption[] = [
  {
    id: "hotel-montreal-3-room-2-King-OceanView",
    name: "Deluxe King Studio",
    description: "Deluxe-themed studio with classic decor, with the sound of the ocean as your backdrop, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 707,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-montreal-3-room-2-Twin-CityView",
    name: "Aurora Twin Suite",
    description: "This majestic twin accommodation offers with a view of iconic landmarks, inspired by the rugged beauty of Canadian landscapes.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator"],
    pricePerNight: 370,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-montreal-3-room-2-SofaBed-GardenView",
    name: "Premium Sofa Bed Loft",
    description: "Discover the charm of this Premium-themed sofa bed loft, complete with classic ambiance, stunning where you can relax in a garden haven, and with a spacious seating area.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 355,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-montreal-3-room-2-Queen-CityView",
    name: "Standard Queen Apartment",
    description: "A tranquil queen apartment designed for refreshing comfort, with featuring a blend of modern and historic architecture and featuring premium bath amenities, reflecting with cozy, nature-inspired themes.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 494,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-montreal-3-room-2-Twin-GardenView",
    name: "Rockies Twin Apartment",
    description: "Our bohemian Rockies-themed apartment offers where you can enjoy the beauty of nature, generous comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 397,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-montreal-3-room-2-Double-GardenView",
    name: "Executive Double Apartment",
    description: "Experience our comfy, contemporary double apartment where you can unwind in a garden paradise, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Accessible Bathroom", "Wheelchair Accessible", "Hearing Support"],
    pricePerNight: 410,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-montreal-3-room-2-Queen-GardenView",
    name: "Executive Queen Suite",
    description: "This refined queen suite promises where you can enjoy the serenity of a garden retreat, enriched by Executive-themed details and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 524,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  }
];
