import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for St. John's Harbour Inn
export const stJohnsHarbourInnRooms: RoomOption[] = [
  {
    id: "hotel-montreal-10-room-9-Double-OceanView",
    name: "Deluxe Double Loft",
    description: "Discover the charm of this Deluxe-themed double loft, complete with open-concept ambiance, stunning where you can feel the ocean breeze, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 504,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-montreal-10-room-9-King-None",
    name: "Frontier King Studio",
    description: "Indulge in the deluxe atmosphere of our king studio, with spectacular with a pleasant outlook, inspired by the rugged beauty of Canadian landscapes, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 472,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-montreal-10-room-9-Twin-None",
    name: "Timber Twin Room",
    description: "This broad twin accommodation offers with a pleasant outlook, blending urban sophistication with wilderness charm.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 332,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-montreal-10-room-9-King-GardenView",
    name: "Deluxe King Apartment",
    description: "A futuristic king apartment designed for serene comfort, with with serene garden views and with plush bedding for ultimate comfort, reflecting with cozy, nature-inspired themes.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 571,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-montreal-10-room-9-King-OceanView",
    name: "Rockies King Studio",
    description: "This generous king accommodation offers with the sound of the ocean as your backdrop, blending urban sophistication with wilderness charm.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 701,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-montreal-10-room-9-Single-CityView",
    name: "Executive Single Villa",
    description: "This palatial single accommodation offers with a backdrop of city parks and green spaces, inspired by the rugged beauty of Canadian landscapes.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 301,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-montreal-10-room-9-Queen-OceanView",
    name: "Superior Queen Studio",
    description: "A ample queen studio designed for upscale comfort, with featuring uninterrupted ocean vistas and with a spacious seating area, reflecting with cozy, nature-inspired themes.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 569,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-montreal-10-room-9-SofaBed-OceanView",
    name: "Classic Sofa Bed Villa",
    description: "Experience our roomy, contemporary sofa bed villa with a panoramic view of the coastline, with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 424,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-montreal-10-room-9-SofaBed-None",
    name: "Northern Lights Sofa Bed Villa",
    description: "A soothing sofa bed villa designed for grandiose comfort, with with a pleasant outlook and with a spacious seating area, reflecting inspired by the rugged beauty of Canadian landscapes.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 312,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-montreal-10-room-9-King-MountainView",
    name: "Maple King Room",
    description: "Unwind in this grandiose king room with a view of the mountains' rugged terrain, with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 639,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  }
];
