import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Northern Lights Inn
export const theNorthernLightsInnRooms: RoomOption[] = [
  {
    id: "hotel-montreal-1-room-0",
    name: "Luxury Queen Loft",
    description: "Unwind in this tranquil queen loft with a window to the bustling city below, with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Bathtub", "Dining Table", "Kitchenette"],
    pricePerNight: 370,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-montreal-1-room-0",
    name: "Superior Queen Apartment",
    description: "A luxurious queen apartment designed for snug comfort, with where you can watch the waves roll in and with a spacious seating area, reflecting blending urban sophistication with wilderness charm.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Seating Area", "Jacuzzi Tub", "Dining Table", "Fitness Equipment", "Fireplace"],
    pricePerNight: 427,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-montreal-1-room-0",
    name: "Rockies Double Penthouse",
    description: "A classic double penthouse designed for inviting comfort, with where you can enjoy the garden's seasonal blooms and equipped with all the modern conveniences, reflecting inspired by the rugged beauty of Canadian landscapes.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "In-Room Safe", "Bathtub", "Soundproofing", "Ironing Facilities", "Blackout Curtains"],
    pricePerNight: 285,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-montreal-1-room-0",
    name: "Luxury Double Studio",
    description: "Enjoy a modern stay in our Luxury-themed double studio, offering with a view of the ocean's horizon, offering a unique blend of style and comfort, and unique touches of featuring warm wood and stone accents.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Complimentary Bottled Water", "Outdoor Furniture", "Balcony", "Accessible Room", "Kitchenette"],
    pricePerNight: 358,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  }
];
