import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Whispering Wren
export const theWhisperingWrenRooms: RoomOption[] = [
  {
    id: "hotel-glacier-bay-5-room-4-Double-CityView",
    name: "Modern Double Suite",
    description: "A commodious double retreat showcasing the urban landscape, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 102,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-glacier-bay-5-room-4-SofaBed-MountainView",
    name: "Standard Sofa Bed Suite",
    description: "Our Standard-themed sofa bed suite offers commodious luxury, panoramic with a view of snow-capped peaks, and with carefully selected furnishings, inspired by decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 103,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-glacier-bay-5-room-4-Single-GardenView",
    name: "Serenity Single Loft",
    description: "Relax in our fashionable expansive single loft featuring where you can take in the fresh air, along with offering a unique blend of style and comfort and designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids"],
    pricePerNight: 87,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-glacier-bay-5-room-4-Queen-GardenView",
    name: "Serenity Queen Penthouse",
    description: "Our extravagant Serenity-themed penthouse offers with a view of the garden's lush greenery, bohemian comfort, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 141,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-glacier-bay-5-room-4-Queen-OceanView",
    name: "Horizon Queen Apartment",
    description: "Experience our retro, sumptuous queen apartment with a private balcony overlooking the sea, equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 142,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  }
];
