import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Sakura Palace
export const sakuraPalaceRooms: RoomOption[] = [
  {
    id: "hotel-tokyo-5-room-4-King-OceanView",
    name: "Superior King Room",
    description: "Experience our relaxing, open-concept king room where you can enjoy the ocean's beauty, with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 7587772,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-tokyo-5-room-4-Double-None",
    name: "Signature Double Suite",
    description: "Our industrial Signature-themed suite offers with a pleasant outlook, welcoming comfort, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 4394047,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-tokyo-5-room-4-Single-CityView",
    name: "Zen Single Loft",
    description: "Zen-themed loft with plush decor, with stunning views of the city skyline, and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 4372546,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-tokyo-5-room-4-Twin-CityView",
    name: "Classic Twin Room",
    description: "Enjoy a elegant stay in our Classic-themed twin room, offering with a view of the city's cultural landmarks, with plush bedding for ultimate comfort, and unique touches of offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 4562155,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-tokyo-5-room-4-King-None",
    name: "Signature King Apartment",
    description: "A airy king apartment designed for welcoming comfort, with with a pleasant outlook and with high-speed internet access, reflecting offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 6866943,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  }
];
