import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Sapporo Snow Festival Hotel
export const sapporoSnowFestivalHotelRooms: RoomOption[] = [
  {
    id: "hotel-tokyo-5-room-4-Double-None",
    name: "Bamboo Double Apartment",
    description: "This voluminous double accommodation offers with a pleasant outlook, combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 4895404,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-tokyo-5-room-4-SofaBed-CityView",
    name: "Harmony Sofa Bed Apartment",
    description: "Enjoy a room-filled stay in our Harmony-themed sofa bed apartment, offering offering panoramic city vistas, with a modern en-suite bathroom, and unique touches of offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 5789206,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-tokyo-5-room-4-Double-MountainView",
    name: "Zen Double Suite",
    description: "Enjoy a peaceful stay in our Zen-themed double suite, offering where you can enjoy the serenity of mountain life, including climate control for your comfort, and unique touches of offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 6144857,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-tokyo-5-room-4-Twin-OceanView",
    name: "Sakura Twin Suite",
    description: "Sakura-themed twin suite overlooking the sparkling ocean waves, offering the perfect balance of Eastern serenity and Western comfort and with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 6573050,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-tokyo-5-room-4-King-CityView",
    name: "Sakura King Apartment",
    description: "Our soothing Sakura-themed apartment offers where you can enjoy the city's energy, expansive comfort, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator", "Hearing Support"],
    pricePerNight: 9038525,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-tokyo-5-room-4-Queen-MountainView",
    name: "Bamboo Queen Apartment",
    description: "This wide-ranging queen accommodation offers with a view of the rugged mountain landscape, combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids"],
    pricePerNight: 7585355,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-tokyo-5-room-4-Double-GardenView",
    name: "Lotus Double Apartment",
    description: "A bohemian double apartment designed for elegant comfort, with where you can relax in a garden haven and offering a unique blend of style and comfort, reflecting featuring traditional tatami elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator"],
    pricePerNight: 6420522,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-tokyo-5-room-4-King-GardenView",
    name: "Classic King Loft",
    description: "Enjoy a refined stay in our Classic-themed king loft, offering where you can take in the fresh air, featuring a curated minibar selection, and unique touches of combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 8766122,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  }
];
