import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Mossy Mushroom Retreat
export const mossyMushroomRetreatRooms: RoomOption[] = [
  {
    id: "hotel-tampa-5-room-4-Twin-None",
    name: "Golden Gate Twin Studio",
    description: "Relax in our wide-ranging intimate twin studio featuring with a pleasant outlook, along with with a modern en-suite bathroom and featuring sleek urban design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 296,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-tampa-5-room-4-SofaBed-OceanView",
    name: "Golden Gate Sofa Bed Room",
    description: "A regal sofa bed retreat where you can relax to the sound of the waves, highlighting contemporary American style.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 342,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-tampa-5-room-4-Single-None",
    name: "Liberty Single Suite",
    description: "Liberty-themed single suite with a pleasant outlook, highlighting contemporary American style and featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 242,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-tampa-5-room-4-King-GardenView",
    name: "Executive King Studio",
    description: "This ornate king studio promises with a view of shaded garden paths, enriched by Executive-themed details and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 535,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-tampa-5-room-4-Twin-GardenView",
    name: "Heritage Twin Room",
    description: "Heritage-themed twin room where you can enjoy the tranquility of nature, highlighting contemporary American style and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 336,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-tampa-5-room-4-Twin-MountainView",
    name: "Heritage Twin Penthouse",
    description: "Relax in our soothing pleasant twin penthouse featuring where mountains paint the horizon, along with with carefully selected furnishings and offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 319,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  }
];
