import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Lighthouse Court
export const theLighthouseCourtRooms: RoomOption[] = [
  {
    id: "hotel-tampa-2-room-1-Single-OceanView",
    name: "Luxury Single Penthouse",
    description: "Enjoy a expansive stay in our Luxury-themed single penthouse, offering overlooking the sparkling ocean waves, including climate control for your comfort, and unique touches of highlighting contemporary American style.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 81,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-tampa-2-room-1-Single-CityView",
    name: "Standard Single Room",
    description: "Relax in our broad plush single room featuring where the city skyline meets the horizon, along with with a private balcony or terrace and highlighting contemporary American style.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Elevator", "Wheelchair Accessible", "Accessible Bathroom"],
    pricePerNight: 74,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-tampa-2-room-1-Queen-CityView",
    name: "Pioneer Queen Villa",
    description: "Pioneer-themed villa with wide-ranging decor, where the city skyline meets the horizon, and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom", "Elevator"],
    pricePerNight: 116,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-tampa-2-room-1-Twin-CityView",
    name: "Colonial Twin Loft",
    description: "Indulge in the stylish atmosphere of our twin loft, with spectacular with stunning views of the city skyline, with rustic and modern influences, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 75,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  }
];
