import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Whispering Woods
export const theWhisperingWoodsRooms: RoomOption[] = [
  {
    id: "hotel-tampa-12-room-11-SofaBed-None",
    name: "Luxury Sofa Bed Studio",
    description: "Experience our cozy, luxurious sofa bed studio with a pleasant outlook, with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 203,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-tampa-12-room-11-Single-None",
    name: "Premium Single Villa",
    description: "Our opulent Premium-themed villa offers with a pleasant outlook, soft comfort, and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 189,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-tampa-12-room-11-SofaBed-CityView",
    name: "Premium Sofa Bed Penthouse",
    description: "Step into a pleasant sofa bed penthouse that combines Premium-themed with breathtaking showcasing the urban landscape, complemented by with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 234,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-tampa-12-room-11-Queen-CityView",
    name: "Signature Queen Villa",
    description: "This futuristic queen villa promises where the city comes alive at dusk, enriched by Signature-themed details and with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 291,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-tampa-12-room-11-King-None",
    name: "Superior King Apartment",
    description: "Relax in our broad grandiose king apartment featuring with a pleasant outlook, along with including climate control for your comfort and offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 365,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-tampa-12-room-11-SofaBed-MountainView",
    name: "Superior Sofa Bed Studio",
    description: "Unwind in this avant-garde sofa bed studio with a view of the mountains' changing seasons, featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Hearing Support", "Elevator", "Visual Aids"],
    pricePerNight: 282,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-tampa-12-room-11-Single-CityView",
    name: "Classic Single Suite",
    description: "Experience our futuristic, chic single suite with a view of the city's waterfront, equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Visual Aids"],
    pricePerNight: 201,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-tampa-12-room-11-Twin-GardenView",
    name: "Golden Gate Twin Room",
    description: "This artistic twin accommodation offers where you can find solace in nature's embrace, featuring sleek urban design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 272,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
