import { Tour } from "@/lib/interfaces/services/tours";

export const sanJuanpuertoRicocaribbeanTours: Tour[] = [
  {
    id: "tour-san-juan-1",
    guideId: "guide-san-juan-4",
    title: "san-juan Off-the-Beaten-Path Adventure",
    description: "Explore the vibrant streets of san-juan with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "san-juan",
    country: "Puerto Rico",
    region: "Caribbean",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 3,
    price: "£26",
    tags: ["Photography", "Off the Beaten Path"],
    type: "Adventure Tour",
    schedule: [
      {
        dayOfWeek: "Friday",
        startTime: "17:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "10:00",
        endTime: "22:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "09:00",
        endTime: "10:30",
      }
    ],
    pricePerPerson: 26,
    currency: "GBP",
    maxGroupSize: 7,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 46,
    included: ["Local taxes", "Recipe booklet", "Souvenir photos", "Dinner", "Professional guide", "Cooking demonstration"],
    notIncluded: ["Food and drinks", "Luggage storage"],
    requirements: ["Parental consent required", "Headphones provided"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4,
  },
  {
    id: "tour-san-juan-2",
    guideId: "guide-san-juan-1",
    title: "san-juan Wine Tasting Experience",
    description: "Uncover the secrets of san-juan on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "san-juan",
    country: "Puerto Rico",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 12,
    price: "¥97",
    tags: ["Educational", "Nature & Wildlife"],
    type: "Shopping Tour",
    schedule: [
      {
        dayOfWeek: "Thursday",
        startTime: "15:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "15:00",
        endTime: "16:30",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "13:00",
        endTime: "18:00",
      }
    ],
    pricePerPerson: 97,
    currency: "JPY",
    maxGroupSize: 8,
    minGroupSize: 1,
    privateAvailable: false,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 17,
    included: ["Transportation during tour", "Welcome drink", "Bottled water", "Lunch", "WiFi on board", "Coffee and/or Tea"],
    notIncluded: ["Personal expenses", "Souvenir photos", "Food and drinks"],
    requirements: ["Headphones provided"],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4.9,
  },
  {
    id: "tour-san-juan-3",
    guideId: "guide-san-juan-6",
    title: "san-juan Art Galleries Crawl",
    description: "Immerse yourself in the local culture of san-juan with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "san-juan",
    country: "Puerto Rico",
    region: "Caribbean",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 1,
    price: "€102",
    tags: ["Luxury", "Spiritual", "Local Life"],
    type: "Walking Tour",
    schedule: [
      {
        dayOfWeek: "Thursday",
        startTime: "13:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "13:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "16:00",
        endTime: "18:30",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "12:00",
        endTime: "13:00",
      }
    ],
    pricePerPerson: 102,
    currency: "EUR",
    maxGroupSize: 18,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 75,
    included: ["Rain ponchos", "Hotel pickup and drop-off", "Cooking demonstration"],
    notIncluded: ["Food and drinks"],
    requirements: ["Credit/debit cards accepted", "Minimum age: 12", "E-tickets accepted"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.5,
  },
  {
    id: "tour-san-juan-4",
    guideId: "guide-san-juan-5",
    title: "san-juan Ghost Stories Walk",
    description: "Explore the vibrant streets of san-juan with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "san-juan",
    country: "Puerto Rico",
    region: "Caribbean",
    languagesOffered: ["English", "Spanish"],
    durationInHours: 2,
    price: "C$145",
    tags: ["Culinary", "Off the Beaten Path"],
    type: "Bike Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "09:00",
        endTime: "15:00",
      }
    ],
    pricePerPerson: 145,
    currency: "CAD",
    maxGroupSize: 18,
    minGroupSize: 3,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 39,
    included: ["Coffee and/or Tea", "Wine tasting", "Use of helmet", "Cooking demonstration", "Souvenir photos", "Entrance fees"],
    notIncluded: ["Food and drinks", "Souvenir photos"],
    requirements: ["Parental consent required", "Bring own headphones", "Basic fitness level required"],
    cancellationPolicy: "Free cancellation up to 24 hours before the experience starts",
    rating: 4.4,
  },
  {
    id: "tour-san-juan-5",
    guideId: "guide-san-juan-2",
    title: "san-juan Cultural Heritage Tour",
    description: "Explore the vibrant streets of san-juan with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "san-juan",
    country: "Puerto Rico",
    region: "Caribbean",
    languagesOffered: ["English", "Arabic"],
    durationInHours: 3,
    price: "$139",
    tags: ["Nightlife", "Cruise Stop"],
    type: "Romantic Tour",
    schedule: [
      {
        dayOfWeek: "Saturday",
        startTime: "15:00",
        endTime: "21:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "14:00",
        endTime: "16:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "13:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 139,
    currency: "USD",
    maxGroupSize: 6,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 80,
    included: ["Rain ponchos", "Food samples", "Entry/Admission tickets", "Entrance fees", "Professional guide", "Use of bicycle"],
    notIncluded: ["Gratuities", "Transportation to/from attractions", "Food and drinks", "Personal expenses"],
    requirements: ["Basic fitness level required"],
    cancellationPolicy: "Free cancellation up to 48 hours before the experience starts",
    rating: 4,
  },
  {
    id: "tour-san-juan-6",
    guideId: "guide-san-juan-1",
    title: "san-juan Essential City Highlights",
    description: "Uncover the secrets of san-juan on this unforgettable experience. Visit top attractions and off-the-beaten-path locations that most tourists never see.",
    city: "san-juan",
    country: "Puerto Rico",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 5,
    price: "¥91",
    tags: ["Culture", "Local Life", "Religious", "Wine & Spirits"],
    type: "Scenic Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "12:00",
        endTime: "15:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "08:00",
        endTime: "10:00",
      }
    ],
    pricePerPerson: 91,
    currency: "JPY",
    maxGroupSize: 6,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 71,
    included: ["Audio guide", "Headsets to hear the guide"],
    notIncluded: ["Hotel pickup and drop-off", "Food and drinks", "Souvenir photos", "Transportation to/from attractions"],
    requirements: ["Face masks required", "Photography allowed", "Arrive 15 minutes early"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 3.8,
  },
  {
    id: "tour-san-juan-7",
    guideId: "guide-san-juan-6",
    title: "san-juan Architecture Masterpieces Tour",
    description: "Journey through the history of san-juan on this engaging tour. Learn fascinating stories and discover architectural masterpieces that shaped this incredible destination.",
    city: "san-juan",
    country: "Puerto Rico",
    region: "Caribbean",
    languagesOffered: ["English"],
    durationInHours: 2.5,
    price: "¥62",
    tags: ["Architecture", "Culture", "Historical", "Spiritual"],
    type: "Underground Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "16:00",
        endTime: "23:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "15:00",
        endTime: "16:00",
      },
      {
        dayOfWeek: "Tuesday",
        startTime: "14:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "08:00",
        endTime: "09:30",
      }
    ],
    pricePerPerson: 62,
    currency: "JPY",
    maxGroupSize: 19,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 39,
    included: ["Use of bicycle", "Snacks", "Gratuities", "Transportation during tour"],
    notIncluded: ["Travel insurance", "Hotel pickup and drop-off"],
    requirements: ["No flash photography"],
    cancellationPolicy: "Group bookings: Free cancellation up to 7 days in advance",
    rating: 4.7,
  }
];
