import { Tour } from "@/lib/interfaces/services/tours";

export const veniceitalymediterraneanTours: Tour[] = [
  {
    id: "tour-venice-1",
    guideId: "guide-venice-3",
    title: "venice Urban Legends Tour",
    description: "Immerse yourself in the local culture of venice with this comprehensive tour. Sample regional cuisine, meet friendly locals, and create lasting memories.",
    city: "venice",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English", "Japanese"],
    durationInHours: 3,
    price: "¥142",
    tags: ["Hiking", "Wine & Spirits", "Wellness"],
    type: "Cooking Class",
    schedule: [
      {
        dayOfWeek: "Tuesday",
        startTime: "11:00",
        endTime: "19:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "13:00",
        endTime: "14:00",
      }
    ],
    pricePerPerson: 142,
    currency: "JPY",
    maxGroupSize: 9,
    minGroupSize: 2,
    privateAvailable: false,
    isPopular: false,
    isPetFriendly: true,
    reviewsCount: 61,
    included: ["Live entertainment", "Lunch", "Use of helmet", "Guided commentary", "Wine tasting", "Transportation during tour"],
    notIncluded: ["Transportation to/from attractions", "Additional entrance fees", "Travel insurance"],
    requirements: ["Bring own headphones", "Minimum age: 12"],
    cancellationPolicy: "Free cancellation up to 72 hours before the experience starts",
    rating: 5,
  },
  {
    id: "tour-venice-2",
    guideId: "guide-venice-1",
    title: "venice Wine Tasting Experience",
    description: "Explore the vibrant streets of venice with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "venice",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 2,
    price: "C$114",
    tags: ["Spiritual", "Scenic"],
    type: "Nature Tour",
    schedule: [
      {
        dayOfWeek: "Monday",
        startTime: "11:00",
        endTime: "14:00",
      },
      {
        dayOfWeek: "Friday",
        startTime: "17:00",
        endTime: "21:00",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "08:00",
        endTime: "14:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "17:00",
        endTime: "21:00",
      }
    ],
    pricePerPerson: 114,
    currency: "CAD",
    maxGroupSize: 11,
    minGroupSize: 2,
    privateAvailable: true,
    isPopular: true,
    isPetFriendly: false,
    reviewsCount: 12,
    included: ["Use of helmet", "Welcome drink", "Wine tasting"],
    notIncluded: ["Gratuities", "Additional entrance fees"],
    requirements: ["Comfortable walking shoes required", "Arrive 15 minutes early", "Photography allowed", "Tickets must be printed"],
    cancellationPolicy: "50% refund if canceled 24 hours before the experience",
    rating: 4.7,
  },
  {
    id: "tour-venice-3",
    guideId: "guide-venice-4",
    title: "venice Urban Legends Tour",
    description: "Explore the vibrant streets of venice with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "venice",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English", "Arabic"],
    durationInHours: 10,
    price: "€94",
    tags: ["Music", "Food & Drink"],
    type: "Accessible Tour",
    schedule: [
      {
        dayOfWeek: "Monday",
        startTime: "10:00",
        endTime: "11:30",
      },
      {
        dayOfWeek: "Friday",
        startTime: "08:00",
        endTime: "14:00",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "14:00",
        endTime: "15:30",
      }
    ],
    pricePerPerson: 94,
    currency: "EUR",
    maxGroupSize: 11,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 68,
    included: ["Coffee and/or Tea", "Lunch", "Transportation during tour"],
    notIncluded: ["Additional entrance fees", "Food and drinks", "Souvenir photos", "Travel insurance"],
    requirements: ["COVID-19 vaccination required", "Service animals permitted"],
    cancellationPolicy: "Non-refundable. No cancellation allowed.",
    rating: 3.8,
  },
  {
    id: "tour-venice-4",
    guideId: "guide-venice-2",
    title: "venice Essential City Highlights",
    description: "Explore the vibrant streets of venice with a knowledgeable local guide. This tour offers an authentic taste of the city's unique atmosphere and cultural heritage.",
    city: "venice",
    country: "Italy",
    region: "Mediterranean",
    languagesOffered: ["English"],
    durationInHours: 10,
    price: "¥72",
    tags: ["Religious", "Romantic", "Wellness"],
    type: "Photography Tour",
    schedule: [
      {
        dayOfWeek: "Wednesday",
        startTime: "15:00",
        endTime: "18:00",
      },
      {
        dayOfWeek: "Monday",
        startTime: "14:00",
        endTime: "16:30",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "09:00",
        endTime: "15:00",
      },
      {
        dayOfWeek: "Sunday",
        startTime: "17:00",
        endTime: "23:00",
      }
    ],
    pricePerPerson: 72,
    currency: "JPY",
    maxGroupSize: 17,
    minGroupSize: 3,
    privateAvailable: true,
    isPopular: false,
    isPetFriendly: false,
    reviewsCount: 31,
    included: ["WiFi on board", "Bottled water", "Transportation during tour", "Welcome drink"],
    notIncluded: ["Alcoholic drinks"],
    requirements: ["Not wheelchair accessible", "No flash photography"],
    cancellationPolicy: "Full refund if canceled due to weather",
    rating: 4,
  }
];
