// Auto-generated file for juneau hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const juneauHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "services@lavenderlullabylodge.com",
      contactPhone: "+869 962-541-7069",
    },
    policies: {
      cancellation: "Full refund if cancelled within 48 hours of booking, minus service fees.",
      smoking: "Allowed",
    },
    id: "hotel-juneau-1",
    name: "Lavender Lullaby Lodge",
    address: "201 Park Way",
    rating: 3,
    accommodationType: "Family Resort",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 10,
    isPetFriendly: true,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "welcome@oceanfrontescape.com",
      contactPhone: "+128 125-368-5838",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-juneau-2",
    name: "Oceanfront Escape",
    address: "68 SE Washington Ter",
    rating: 4,
    accommodationType: "Chalet",
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 13,
    isPetFriendly: false,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "care@theredwoodretreat.com",
      contactPhone: "+520 915-632-8673",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Allowed",
    },
    id: "hotel-juneau-3",
    name: "The Redwood Retreat",
    address: "164 Washington Pkwy",
    rating: 3,
    accommodationType: "Eco-Lodge",
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 11,
    isPetFriendly: false,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "communications@whisperingpinesinn.com",
      contactPhone: "+327 107-352-9688",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Designated Areas",
    },
    id: "hotel-juneau-4",
    name: "Whispering Pines Inn",
    address: "16 SW Elm Cres",
    rating: 4,
    accommodationType: "Luxury Lodge",
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 24,
    isPetFriendly: false,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "connect@pacifichorizonhotel.com",
      contactPhone: "+447 402-256-6249",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Not Allowed",
    },
    id: "hotel-juneau-5",
    name: "Pacific Horizon Hotel",
    address: "18 Lincoln Rd",
    rating: 3,
    accommodationType: "Eco-Lodge",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 29,
    isPetFriendly: false,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hello@thebumblebee’srest.com",
      contactPhone: "+672 996-626-1208",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Designated Areas",
    },
    id: "hotel-juneau-6",
    name: "The Bumblebee’s Rest",
    address: "248 Oak Cir",
    rating: 4,
    accommodationType: "Spa Hotel",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 12,
    isPetFriendly: true,
    currency: "USD",
    isPopular: true,
  },
  {
    id: "hotel-juneau-7",
    name: "The Playful Pine",
    address: "207 Park Blvd",
    rating: 3,
    accommodationType: "Spa Hotel",
    amenities: ["Airport Shuttle", "Free Wi-Fi", "Business Center", "Restaurant", "Swimming Pool", "Fitness Center", "Laundry Service", "Non-Smoking Rooms", "Room Service", "Conference Room"],
    accessibilityFeatures: ["Visual Aids"],
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 55,
    isPetFriendly: false,
    currency: "USD",
    contact: {
      contactEmail: "support@theplayfulpine.com",
      contactPhone: "+541 563-671-5076",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  },
  {
    id: "hotel-juneau-8",
    name: "Celestial Bay Inn",
    address: "21 Washington Ter",
    rating: 4,
    accommodationType: "Family Resort",
    amenities: ["Room Service", "Airport Shuttle", "Bar", "Swimming Pool", "Non-Smoking Rooms", "Spa"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 34,
    isPetFriendly: false,
    currency: "USD",
    contact: {
      contactEmail: "contact@celestialbayinn.com",
      contactPhone: "+628 251-672-8629",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  },
  {
    id: "hotel-juneau-9",
    name: "Pixie Hollow Suites",
    address: "168 E Oak Ln",
    rating: 3,
    accommodationType: "Boutique Hotel",
    amenities: ["Swimming Pool", "Parking", "Bar", "Room Service", "Business Center", "Laundry Service", "Fitness Center", "Free Wi-Fi"],
    accessibilityFeatures: ["Sign Language Interpretation", "Braille Signage", "Visual Aids"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 46,
    isPetFriendly: true,
    currency: "USD",
    contact: {
      contactEmail: "inquiries@pixiehollowsuites.com",
      contactPhone: "+633 387-952-5697",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Allowed",
    },
    isPopular: true,
  }
];
