import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Lavender Lullaby Lodge
export const lavenderLullabyLodgeRooms: RoomOption[] = [
  {
    id: "hotel-juneau-1-room-0-SofaBed-CityView",
    name: "Deluxe Sofa Bed Room",
    description: "A chic sofa bed room designed for compact comfort, with with a view of iconic landmarks and with plush bedding for ultimate comfort, reflecting offering a classic yet modern American experience.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 97,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-juneau-1-room-0-Double-OceanView",
    name: "Colonial Double Villa",
    description: "Our intimate Colonial-themed villa offers with a view of the ocean's horizon, avant-garde comfort, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 136,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-juneau-1-room-0-Double-CityView",
    name: "Classic Double Loft",
    description: "Classic-themed loft with minimalist decor, where you can watch the city wake up, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 115,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-juneau-1-room-0-Twin-CityView",
    name: "Golden Gate Twin Apartment",
    description: "Golden Gate-themed twin apartment where the city comes alive at dusk, highlighting contemporary American style and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 109,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-juneau-1-room-0-Queen-None",
    name: "Premium Queen Apartment",
    description: "Discover the charm of this Premium-themed queen apartment, complete with modern ambiance, stunning with a pleasant outlook, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 108,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-juneau-1-room-0-SofaBed-GardenView",
    name: "Deluxe Sofa Bed Penthouse",
    description: "This airy sofa bed penthouse promises where you can enjoy the beauty of nature, enriched by Deluxe-themed details and with a spacious seating area.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Visual Aids", "Wheelchair Accessible"],
    pricePerNight: 103,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-juneau-1-room-0-Twin-OceanView",
    name: "Liberty Twin Suite",
    description: "Enjoy a sophisticated stay in our Liberty-themed twin suite, offering where you can hear the soothing sound of the sea, with blackout curtains for a perfect night's sleep, and unique touches of offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 112,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-juneau-1-room-0-Twin-GardenView",
    name: "Executive Twin Studio",
    description: "Relax in our stretching refined twin studio featuring with a view of the garden's peaceful ambiance, along with with a luxurious soaking tub and offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 107,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-juneau-1-room-0-Twin-None",
    name: "Pioneer Twin Villa",
    description: "Relax in our intimate stylish twin villa featuring with a pleasant outlook, along with with high-speed internet access and featuring sleek urban design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 87,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  }
];
