import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Pacific Horizon Hotel
export const pacificHorizonHotelRooms: RoomOption[] = [
  {
    id: "hotel-juneau-5-room-4-Double-GardenView",
    name: "Golden Gate Double Loft",
    description: "Our Golden Gate-themed double loft offers prestigious luxury, panoramic with a view of tranquil water features, and featuring a curated minibar selection, inspired by with rustic and modern influences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Elevator"],
    pricePerNight: 115,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-juneau-5-room-4-King-GardenView",
    name: "Standard King Penthouse",
    description: "A broad king retreat where you can relax in a garden haven, featuring sleek urban design elements.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 149,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-juneau-5-room-4-Twin-OceanView",
    name: "Classic Twin Penthouse",
    description: "Our Classic-themed twin penthouse offers ample luxury, panoramic with a private balcony overlooking the sea, and featuring premium bath amenities, inspired by with rustic and modern influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 119,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-juneau-5-room-4-Queen-OceanView",
    name: "Classic Queen Loft",
    description: "Our Classic-themed queen loft offers stretching luxury, panoramic where you can enjoy the ocean's beauty, and complete with a well-appointed bathroom, inspired by offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator", "Visual Aids"],
    pricePerNight: 155,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-juneau-5-room-4-Queen-None",
    name: "Pioneer Queen Loft",
    description: "Our Pioneer-themed queen loft offers airy luxury, panoramic with a pleasant outlook, and featuring a curated minibar selection, inspired by with rustic and modern influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 122,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-juneau-5-room-4-Single-CityView",
    name: "Superior Single Penthouse",
    description: "A refreshing single retreat where you can enjoy the city's energy, featuring sleek urban design elements.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 76,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-juneau-5-room-4-Single-OceanView",
    name: "Deluxe Single Apartment",
    description: "Relax in our welcoming snug single apartment featuring with a view of the ocean's horizon, along with equipped with all the modern conveniences and offering a classic yet modern American experience.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 95,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  }
];
