import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Hokitika Gorge Hotel
export const hokitikaGorgeHotelRooms: RoomOption[] = [
  {
    id: "hotel-auckland-2-room-1-Queen-GardenView",
    name: "Executive Queen Studio",
    description: "Executive-themed studio with tasteful decor, where you can relax in a garden haven, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 359,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-auckland-2-room-1-Twin-MountainView",
    name: "Southern Cross Twin Loft",
    description: "This artistic twin loft promises with a view of the mountains' rugged terrain, enriched by Southern Cross-themed details and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 296,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-auckland-2-room-1-SofaBed-MountainView",
    name: "Fern Sofa Bed Room",
    description: "A elegant sofa bed retreat with a view of the mountains' natural beauty, with Maori-inspired motifs.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids", "Hearing Support"],
    pricePerNight: 298,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-auckland-2-room-1-King-OceanView",
    name: "Luxury King Suite",
    description: "Unwind in this opulent king suite with a view of the endless blue, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 454,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-auckland-2-room-1-King-GardenView",
    name: "Bayview King Loft",
    description: "Experience our heartwarming, industrial king loft where you can relax in a natural oasis, with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 382,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-auckland-2-room-1-SofaBed-None",
    name: "Fern Sofa Bed Room",
    description: "Step into a spacious sofa bed room that combines Fern-themed with breathtaking with a pleasant outlook, complemented by with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 251,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-auckland-2-room-1-King-None",
    name: "Kiwi King Loft",
    description: "Indulge in the expansive atmosphere of our king loft, with spectacular with a pleasant outlook, showcasing the serene beauty of New Zealand landscapes, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator", "Hearing Support"],
    pricePerNight: 396,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-auckland-2-room-1-Single-MountainView",
    name: "Executive Single Suite",
    description: "Indulge in the heartwarming atmosphere of our single suite, with spectacular with a view of the rugged mountain landscape, showcasing the serene beauty of New Zealand landscapes, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 243,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-auckland-2-room-1-Single-None",
    name: "Deluxe Single Room",
    description: "A heartwarming single room designed for tasteful comfort, with with a pleasant outlook and with blackout curtains for a perfect night's sleep, reflecting with Maori-inspired motifs.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Elevator"],
    pricePerNight: 211,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  }
];
