import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Stewart Island Retreat
export const stewartIslandRetreatRooms: RoomOption[] = [
  {
    id: "hotel-auckland-4-room-3-Queen-MountainView",
    name: "Signature Queen Loft",
    description: "Enjoy a bohemian stay in our Signature-themed queen loft, offering with a view of the rugged mountain landscape, offering a unique blend of style and comfort, and unique touches of showcasing the serene beauty of New Zealand landscapes.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 870,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-auckland-4-room-3-Double-MountainView",
    name: "Alpine Double Villa",
    description: "Alpine-themed double villa with panoramic views of the mountain landscape, with Maori-inspired motifs and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 719,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-auckland-4-room-3-Single-MountainView",
    name: "Premium Single Loft",
    description: "Our plush Premium-themed loft offers overlooking spectacular mountain ranges, avant-garde comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 591,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-auckland-4-room-3-Queen-CityView",
    name: "Kiwi Queen Suite",
    description: "Our Kiwi-themed queen suite offers stretching luxury, panoramic with a front-row seat to the city's heartbeat, and featuring premium bath amenities, inspired by blending rustic charm with modern comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 823,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-auckland-4-room-3-Double-CityView",
    name: "Alpine Double Villa",
    description: "Our Alpine-themed double villa offers avant-garde luxury, panoramic with a view of iconic landmarks, and with blackout curtains for a perfect night's sleep, inspired by blending rustic charm with modern comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 698,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-auckland-4-room-3-Queen-GardenView",
    name: "Alpine Queen Villa",
    description: "Alpine-themed queen villa with serene garden views, showcasing the serene beauty of New Zealand landscapes and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 922,
    currency: "NZD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-auckland-4-room-3-Queen-OceanView",
    name: "Signature Queen Villa",
    description: "Our Signature-themed queen villa offers sumptuous luxury, panoramic with breathtaking sea views, and with blackout curtains for a perfect night's sleep, inspired by blending rustic charm with modern comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 1004,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-auckland-4-room-3-SofaBed-None",
    name: "Bayview Sofa Bed Suite",
    description: "Unwind in this serene sofa bed suite with a pleasant outlook, with a spacious work area.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 541,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-auckland-4-room-3-Twin-MountainView",
    name: "Maori Twin Loft",
    description: "This elegant twin accommodation offers with panoramic views of the surrounding mountains, blending rustic charm with modern comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 747,
    currency: "NZD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
