// Auto-generated file for seattle hotels
// Do not edit manually, use scripts/generate-hotels.mjs to update

// Generated on: 2025-06-08T04:09:38.939Z

import { Hotel } from "@/lib/interfaces/services/rentals";

export const seattleHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "general@thetranquilreef.com",
      contactPhone: "+418 472-506-2813",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Allowed",
    },
    id: "hotel-seattle-1",
    name: "The Tranquil Reef",
    address: "2 Oak Cir",
    rating: 3,
    accommodationType: "Luxury Lodge",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 46,
    isPetFriendly: true,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "info@evergreenheights.com",
      contactPhone: "+17 185-157-5872",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Allowed",
    },
    id: "hotel-seattle-2",
    name: "Evergreen Heights",
    address: "198 Main Cir",
    rating: 3,
    accommodationType: "Boutique Hotel",
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 40,
    isPetFriendly: false,
    currency: "USD",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hi@crimsoncloverinn.com",
      contactPhone: "+453 607-204-7997",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Designated Areas",
    },
    id: "hotel-seattle-3",
    name: "Crimson Clover Inn",
    address: "98 Old Broadway Ave",
    rating: 4,
    accommodationType: "Boutique Hotel",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 49,
    isPetFriendly: false,
    currency: "USD",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "contact@thegoldenmarlin.com",
      contactPhone: "+716 357-710-2422",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-seattle-4",
    name: "The Golden Marlin",
    address: "98 E Park Pl",
    rating: 4,
    accommodationType: "Vacation Rental",
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 28,
    isPetFriendly: false,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "team@lavenderlullabylodge.com",
      contactPhone: "+891 761-836-5136",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Designated Areas",
    },
    id: "hotel-seattle-5",
    name: "Lavender Lullaby Lodge",
    address: "72 NW Lincoln Blvd",
    rating: 3,
    accommodationType: "Motel",
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 51,
    isPetFriendly: false,
    currency: "USD",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reception@thesnugglyseahorse.com",
      contactPhone: "+275 350-352-6318",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-seattle-6",
    name: "The Snuggly Seahorse",
    address: "85 Broadway Sq",
    rating: 4,
    accommodationType: "Luxury Villa",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 49,
    isPetFriendly: true,
    currency: "USD",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "mail@theredwoodretreat.com",
      contactPhone: "+696 639-961-8118",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Allowed",
    },
    id: "hotel-seattle-7",
    name: "The Redwood Retreat",
    address: "193 NE Lincoln Pl",
    rating: 3,
    accommodationType: "Serviced Apartment",
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 27,
    isPetFriendly: true,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hi@thevelvetunicorn.com",
      contactPhone: "+471 706-843-1021",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-seattle-8",
    name: "The Velvet Unicorn",
    address: "259 Park Sq",
    rating: 4,
    accommodationType: "Extended Stay Hotel",
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 46,
    isPetFriendly: true,
    currency: "USD",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hello@gildedgriffininn.com",
      contactPhone: "+33 798-735-4856",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-seattle-9",
    name: "Gilded Griffin Inn",
    address: "160 Cedar Hwy",
    rating: 3,
    accommodationType: "Eco-Lodge",
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 10,
    isPetFriendly: false,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hi@dewdropdreamhouse.com",
      contactPhone: "+652 110-303-8826",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-seattle-10",
    name: "Dewdrop Dreamhouse",
    address: "206 NE Broadway Ave",
    rating: 4,
    accommodationType: "Guesthouse",
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 25,
    isPetFriendly: false,
    currency: "USD",
    isPopular: true,
  },
  {
    id: "hotel-seattle-11",
    name: "The Sapphire Shores",
    address: "99 NW Maple Pkwy",
    rating: 4,
    accommodationType: "Hotel",
    amenities: ["Swimming Pool", "Room Service", "24-Hour Front Desk", "Free Wi-Fi", "Bar", "Airport Shuttle", "Fitness Center", "Conference Room"],
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 54,
    isPetFriendly: true,
    currency: "USD",
    contact: {
      contactEmail: "help@thesapphireshores.com",
      contactPhone: "+361 627-855-8709",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  },
  {
    id: "hotel-seattle-12",
    name: "The Regency",
    address: "149 Maple Ln",
    rating: 3,
    accommodationType: "Vacation Rental",
    amenities: ["Free Wi-Fi", "Business Center", "Airport Shuttle", "Spa", "24-Hour Front Desk", "Laundry Service", "Non-Smoking Rooms", "Conference Room", "Room Service", "Restaurant"],
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 20,
    isPetFriendly: false,
    currency: "USD",
    contact: {
      contactEmail: "customerservice@theregency.com",
      contactPhone: "+780 676-732-5303",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  },
  {
    id: "hotel-seattle-13",
    name: "The Velvet Vine",
    address: "143 Sunset Pl",
    rating: 3,
    accommodationType: "Luxury Lodge",
    amenities: ["Fitness Center", "Spa", "Restaurant", "Room Service", "Business Center", "24-Hour Front Desk"],
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 56,
    isPetFriendly: false,
    currency: "USD",
    contact: {
      contactEmail: "hello@thevelvetvine.com",
      contactPhone: "+377 971-688-1289",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  }
];
