import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Pagoda Retreat
export const thePagodaRetreatRooms: RoomOption[] = [
  {
    id: "hotel-nagasaki-12-room-11-SofaBed-OceanView",
    name: "Executive Sofa Bed Apartment",
    description: "A vast sofa bed apartment designed for vintage comfort, with overlooking the sparkling ocean waves and including climate control for your comfort, reflecting offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids", "Hearing Support"],
    pricePerNight: 5559869,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-nagasaki-12-room-11-Queen-MountainView",
    name: "Classic Queen Studio",
    description: "Relax in our bohemian intimate queen studio featuring where you can experience the beauty of nature, along with with blackout curtains for a perfect night's sleep and offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 6306385,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-nagasaki-12-room-11-Queen-CityView",
    name: "Harmony Queen Room",
    description: "Enjoy a traditional stay in our Harmony-themed queen room, offering with stunning views of the city skyline, complete with a well-appointed bathroom, and unique touches of with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 5417169,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-nagasaki-12-room-11-Twin-GardenView",
    name: "Fuji Twin Villa",
    description: "Enjoy a traditional stay in our Fuji-themed twin villa, offering with a view of manicured lawns and gardens, including climate control for your comfort, and unique touches of combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 4995533,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-nagasaki-12-room-11-King-None",
    name: "Classic King Villa",
    description: "Enjoy a futuristic stay in our Classic-themed king villa, offering with a pleasant outlook, with a private balcony or terrace, and unique touches of featuring traditional tatami elements.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Visual Aids"],
    pricePerNight: 6120446,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-nagasaki-12-room-11-SofaBed-MountainView",
    name: "Superior Sofa Bed Room",
    description: "A intimate sofa bed retreat with a view of the mountains' serene beauty, with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 5565442,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  }
];
