import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Oceanview Inn
export const oceanviewInnRooms: RoomOption[] = [
  {
    id: "hotel-cape-town-6-room-5-Single-None",
    name: "Deluxe Single Villa",
    description: "This industrial single villa promises with a pleasant outlook, enriched by Deluxe-themed details and with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 1647,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-cape-town-6-room-5-King-OceanView",
    name: "Luxury King Suite",
    description: "A spacious king retreat where you can enjoy stunning sunsets over the water, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 3660,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-cape-town-6-room-5-Single-MountainView",
    name: "Classic Single Loft",
    description: "This room-filled single loft promises overlooking spectacular mountain ranges, enriched by Classic-themed details and with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 2426,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-cape-town-6-room-5-Twin-OceanView",
    name: "Luxury Twin Studio",
    description: "Unwind in this comfortable twin studio with a private balcony overlooking the sea, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 2627,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-cape-town-6-room-5-Twin-CityView",
    name: "Luxury Twin Loft",
    description: "This elegant twin loft promises offering panoramic city vistas, enriched by Luxury-themed details and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 2046,
    currency: "ZAR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
