import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Hermanus Whale Coast Hotel
export const theHermanusWhaleCoastHotelRooms: RoomOption[] = [
  {
    id: "hotel-cape-town-3-room-2-Double-CityView",
    name: "Standard Double Loft",
    description: "Relax in our generous industrial double loft featuring overlooking the vibrant cityscape, along with with a private balcony or terrace and created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 5781,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-cape-town-3-room-2-King-OceanView",
    name: "Deluxe King Apartment",
    description: "A lavish king retreat where you can relax to the sound of the waves, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 9454,
    currency: "ZAR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-cape-town-3-room-2-Single-None",
    name: "Superior Single Penthouse",
    description: "Our Superior-themed single penthouse offers relaxing luxury, panoramic with a pleasant outlook, and with plush bedding for ultimate comfort, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 3738,
    currency: "ZAR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-cape-town-3-room-2-Single-MountainView",
    name: "Serenity Single Apartment",
    description: "Our Serenity-themed single apartment offers artistic luxury, panoramic where you can find inspiration in the mountains, and with a luxurious soaking tub, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 5215,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-cape-town-3-room-2-SofaBed-MountainView",
    name: "Premium Sofa Bed Villa",
    description: "Enjoy a airy stay in our Premium-themed sofa bed villa, offering with a view of the rugged mountain landscape, with high-speed internet access, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 5962,
    currency: "ZAR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-cape-town-3-room-2-Twin-CityView",
    name: "Luxury Twin Loft",
    description: "Our Luxury-themed twin loft offers upscale luxury, panoramic with a backdrop of city parks and green spaces, and with high-speed internet access, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 5093,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-cape-town-3-room-2-Twin-GardenView",
    name: "Luxury Twin Room",
    description: "Unwind in this snug twin room with a view of blooming flowers and greenery, with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 4873,
    currency: "ZAR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-cape-town-3-room-2-Queen-OceanView",
    name: "Executive Queen Villa",
    description: "A serene queen retreat with a private balcony overlooking the sea, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Hearing Support"],
    pricePerNight: 7823,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  }
];
