import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Pretoria Grand
export const thePretoriaGrandRooms: RoomOption[] = [
  {
    id: "hotel-cape-town-5-room-4-Twin-MountainView",
    name: "Serenity Twin Loft",
    description: "Experience our inviting, tasteful twin loft where you can take in the fresh mountain air, with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 4089,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-cape-town-5-room-4-SofaBed-CityView",
    name: "Tranquility Sofa Bed Penthouse",
    description: "A soft sofa bed retreat with a front-row seat to the city's heartbeat, created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Wheelchair Accessible", "Accessible Bathroom", "Hearing Support"],
    pricePerNight: 3818,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-cape-town-5-room-4-King-CityView",
    name: "Executive King Apartment",
    description: "Discover the charm of this Executive-themed king apartment, complete with spacious ambiance, stunning where the city comes alive at dusk, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 5750,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-cape-town-5-room-4-Queen-OceanView",
    name: "Tranquility Queen Suite",
    description: "A exquisite queen retreat with a view of the endless blue, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 6288,
    currency: "ZAR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-cape-town-5-room-4-Double-CityView",
    name: "Premium Double Suite",
    description: "Our Premium-themed double suite offers room-filled luxury, panoramic featuring a blend of modern and historic architecture, and with carefully selected furnishings, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 4212,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-cape-town-5-room-4-Single-OceanView",
    name: "Standard Single Villa",
    description: "Enjoy a relaxing stay in our Standard-themed single villa, offering where the ocean meets the sky, with carefully selected furnishings, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 3767,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-cape-town-5-room-4-Queen-None",
    name: "Standard Queen Studio",
    description: "This plush queen accommodation offers with a pleasant outlook, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 4856,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-cape-town-5-room-4-Single-None",
    name: "Executive Single Penthouse",
    description: "Our Executive-themed single penthouse offers exquisite luxury, panoramic with a pleasant outlook, and offering a unique blend of style and comfort, inspired by decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 2985,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-cape-town-5-room-4-King-OceanView",
    name: "Executive King Loft",
    description: "A stretching king retreat featuring uninterrupted ocean vistas, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 6451,
    currency: "ZAR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-cape-town-5-room-4-King-MountainView",
    name: "Executive King Room",
    description: "Step into a elegant king room that combines Executive-themed with breathtaking where you can enjoy the tranquility of the mountains, complemented by with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 6251,
    currency: "ZAR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  }
];
