// Auto-generated file for toronto hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const torontoHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "info@rockiesresort.com",
      contactPhone: "+848 519-188-5617",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Not Allowed",
    },
    id: "hotel-toronto-1",
    name: "Rockies Resort",
    address: "53 East Broadway Place",
    rating: 3,
    accommodationType: "Resort",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 18,
    isPetFriendly: true,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "mail@rockiesresort.com",
      contactPhone: "+138 370-467-7728",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Allowed",
    },
    id: "hotel-toronto-2",
    name: "Rockies Resort",
    address: "268 King Way",
    rating: 4,
    accommodationType: "Serviced Apartment",
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 41,
    isPetFriendly: false,
    currency: "CAD",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "care@timberlineinn.com",
      contactPhone: "+622 832-123-9203",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Allowed",
    },
    id: "hotel-toronto-3",
    name: "Timberline Inn",
    address: "288 Queen Blvd",
    rating: 4,
    accommodationType: "Luxury Hotel",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 23,
    isPetFriendly: false,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "welcome@niagarasuites.com",
      contactPhone: "+345 276-425-7001",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    id: "hotel-toronto-4",
    name: "Niagara Suites",
    address: "111 Queen St",
    rating: 3,
    accommodationType: "Luxury Villa",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 37,
    isPetFriendly: false,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "communications@thelaurentian.com",
      contactPhone: "+896 209-561-7243",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-toronto-5",
    name: "The Laurentian",
    address: "155 Liberty Drive",
    rating: 3,
    accommodationType: "Boutique Inn",
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 29,
    isPetFriendly: false,
    currency: "CAD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "customerservice@mapleleaflodge.com",
      contactPhone: "+66 234-611-9329",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Not Allowed",
    },
    id: "hotel-toronto-6",
    name: "Maple Leaf Lodge",
    address: "287 West Queen Road",
    rating: 3,
    accommodationType: "Vacation Rental",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 14,
    isPetFriendly: true,
    currency: "CAD",
    isPopular: false,
  },
  {
    id: "hotel-toronto-7",
    name: "The Laurentian",
    address: "152 Main Avenue",
    rating: 3,
    accommodationType: "Luxury Lodge",
    amenities: ["Restaurant", "Swimming Pool", "Fitness Center", "24-Hour Front Desk", "Business Center", "Non-Smoking Rooms", "Free Wi-Fi"],
    accessibilityFeatures: ["Accessible Pathways"],
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 55,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "hello@thelaurentian.com",
      contactPhone: "+659 313-702-9701",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  },
  {
    id: "hotel-toronto-8",
    name: "Lakeview Retreat",
    address: "51 Main St",
    rating: 4,
    accommodationType: "Guesthouse",
    amenities: ["24-Hour Front Desk", "Room Service", "Restaurant", "Laundry Service", "Free Wi-Fi"],
    accessibilityFeatures: ["Visual Aids"],
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 18,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "help@lakeviewretreat.com",
      contactPhone: "+81 960-502-5541",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-toronto-9",
    name: "Maple Leaf Lodge",
    address: "152 Upper Liberty Way",
    rating: 4,
    accommodationType: "Vacation Rental",
    amenities: ["Swimming Pool", "Spa", "Laundry Service", "Non-Smoking Rooms", "Bar", "Conference Room", "Restaurant", "Business Center", "Room Service"],
    accessibilityFeatures: ["Elevator"],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 12,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "support@mapleleaflodge.com",
      contactPhone: "+566 115-270-9649",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  }
];
