import { Hotel } from "@/lib/interfaces/services/rentals";

export const torontoHotels: Hotel[] = [
  {
    id: "hotel-toronto-1",
    name: "Maple Leaf Lodge",
    address: "32 Liberty Way",
    rating: 4,
    accommodationType: "Resort",
    amenities: ["Laundry Service", "24-Hour Front Desk", "Bar", "Business Center", "Room Service", "Restaurant", "Fitness Center", "Free Wi-Fi", "Spa"],
    accessibilityFeatures: ["Tactile Maps"],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 18,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "info@mapleleaflodge.com",
      contactPhone: "+425 499-611-2496",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  },
  {
    id: "hotel-toronto-2",
    name: "Aurora Grand",
    address: "52 Broadway Drive",
    rating: 4,
    accommodationType: "Luxury Lodge",
    amenities: ["Spa", "Free Wi-Fi", "Swimming Pool", "Restaurant", "Laundry Service", "Fitness Center", "Bar", "24-Hour Front Desk", "Non-Smoking Rooms"],
    accessibilityFeatures: ["Hearing Loop", "Braille Signage"],
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 19,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "hello@auroragrand.com",
      contactPhone: "+252 138-148-8217",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-toronto-3",
    name: "Maple Leaf Lodge",
    address: "169 Liberty Road",
    rating: 4,
    accommodationType: "Chalet",
    amenities: ["Conference Room", "Parking", "Restaurant", "Non-Smoking Rooms", "Room Service", "Spa"],
    accessibilityFeatures: ["Visual Alarm", "Wheelchair Accessible"],
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 19,
    isPetFriendly: true,
    currency: "CAD",
    contact: {
      contactEmail: "reception@mapleleaflodge.com",
      contactPhone: "+134 412-970-8889",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-toronto-4",
    name: "Rockies Resort",
    address: "45 Upper Park Terrace",
    rating: 3,
    accommodationType: "Motel",
    amenities: ["Restaurant", "Fitness Center", "Bar", "Airport Shuttle", "24-Hour Front Desk", "Free Wi-Fi", "Spa", "Business Center", "Parking", "Swimming Pool"],
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 25,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "connect@rockiesresort.com",
      contactPhone: "+584 593-609-1266",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-toronto-5",
    name: "The Northern Lights Inn",
    address: "200 North King Place",
    rating: 3,
    accommodationType: "Guesthouse",
    amenities: ["Spa", "Fitness Center", "Restaurant", "Room Service", "Laundry Service", "Swimming Pool", "Business Center", "Non-Smoking Rooms"],
    accessibilityFeatures: ["Hearing Support", "Grab Bars"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 44,
    isPetFriendly: false,
    currency: "CAD",
    contact: {
      contactEmail: "info@thenorthernlightsinn.com",
      contactPhone: "+163 111-883-5371",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  }
];
