import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Saskatoon City Lodge
export const saskatoonCityLodgeRooms: RoomOption[] = [
  {
    id: "hotel-toronto-6-room-5-Single-OceanView",
    name: "Signature Single Suite",
    description: "Our Signature-themed single suite offers voluminous luxury, panoramic where you can hear the soothing sound of the sea, and with a private balcony or terrace, inspired by with cozy, nature-inspired themes.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 354,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-toronto-6-room-5-Double-MountainView",
    name: "Maple Double Apartment",
    description: "Our Maple-themed double apartment offers generous luxury, panoramic where the mountains touch the sky, and including climate control for your comfort, inspired by blending urban sophistication with wilderness charm.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Hearing Support"],
    pricePerNight: 501,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-toronto-6-room-5-Twin-GardenView",
    name: "Maple Twin Room",
    description: "Indulge in the artistic atmosphere of our twin room, with spectacular where you can enjoy the garden's seasonal blooms, blending urban sophistication with wilderness charm, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Hearing Support", "Elevator"],
    pricePerNight: 365,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-toronto-6-room-5-King-CityView",
    name: "Signature King Villa",
    description: "A elegant king villa designed for comfy comfort, with with a backdrop of city parks and green spaces and including climate control for your comfort, reflecting with cozy, nature-inspired themes.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 570,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-toronto-6-room-5-Double-None",
    name: "Classic Double Studio",
    description: "Step into a opulent double studio that combines Classic-themed with breathtaking with a pleasant outlook, complemented by with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 396,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-toronto-6-room-5-Twin-None",
    name: "Signature Twin Apartment",
    description: "Signature-themed twin apartment with a pleasant outlook, inspired by the rugged beauty of Canadian landscapes and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 331,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-toronto-6-room-5-King-GardenView",
    name: "Rockies King Studio",
    description: "This soothing king studio promises offering a peaceful garden outlook, enriched by Rockies-themed details and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 602,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-toronto-6-room-5-King-None",
    name: "Timber King Apartment",
    description: "Discover the charm of this Timber-themed king apartment, complete with well-proportioned ambiance, stunning with a pleasant outlook, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 473,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-toronto-6-room-5-Queen-GardenView",
    name: "Timber Queen Apartment",
    description: "A soothing queen apartment designed for peaceful comfort, with with a view of manicured lawns and gardens and with blackout curtains for a perfect night's sleep, reflecting inspired by the rugged beauty of Canadian landscapes.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 519,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-toronto-6-room-5-Single-GardenView",
    name: "Standard Single Studio",
    description: "Our Standard-themed single studio offers majestic luxury, panoramic where you can take in the fresh air, and offering a unique blend of style and comfort, inspired by with cozy, nature-inspired themes.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 352,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  }
];
