import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Oaxaca Colonial Inn
export const theOaxacaColonialInnRooms: RoomOption[] = [
  {
    id: "hotel-puerto-vallarta-7-room-6-SofaBed-CityView",
    name: "Executive Sofa Bed Penthouse",
    description: "This vintage sofa bed penthouse promises with stunning views of the city skyline, enriched by Executive-themed details and with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 2211,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-puerto-vallarta-7-room-6-Queen-CityView",
    name: "Harmony Queen Loft",
    description: "Indulge in the extensive atmosphere of our queen loft, with spectacular with a backdrop of city parks and green spaces, designed for ultimate comfort, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 2589,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-puerto-vallarta-7-room-6-Single-CityView",
    name: "Modern Single Suite",
    description: "Experience our futuristic, relaxing single suite with stunning views of the city skyline, including climate control for your comfort.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 1707,
    currency: "MXN",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-puerto-vallarta-7-room-6-King-GardenView",
    name: "Classic King Apartment",
    description: "A refreshing king apartment designed for grandiose comfort, with with a view of blooming flowers and greenery and with a spacious work area, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 3182,
    currency: "MXN",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-puerto-vallarta-7-room-6-King-MountainView",
    name: "Premium King Suite",
    description: "Our Premium-themed king suite offers cozy luxury, panoramic with a view of snow-capped peaks, and with a spacious work area, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 3278,
    currency: "MXN",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-puerto-vallarta-7-room-6-SofaBed-GardenView",
    name: "Standard Sofa Bed Apartment",
    description: "Step into a vintage sofa bed apartment that combines Standard-themed with breathtaking where you can relax in a natural oasis, complemented by with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 2073,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-puerto-vallarta-7-room-6-Single-None",
    name: "Modern Single Room",
    description: "Our Modern-themed single room offers restful luxury, panoramic with a pleasant outlook, and including climate control for your comfort, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 1754,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-puerto-vallarta-7-room-6-King-None",
    name: "Standard King Apartment",
    description: "Our serene Standard-themed apartment offers with a pleasant outlook, retro comfort, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 2663,
    currency: "MXN",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  }
];
