import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The San Miguel de Allende Heritage Hotel
export const theSanMiguelDeAllendeHeritageHotelRooms: RoomOption[] = [
  {
    id: "hotel-puerto-vallarta-2-room-1-Queen-None",
    name: "Deluxe Queen Studio",
    description: "A elegant queen retreat with a pleasant outlook, featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 2091,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-Single-None",
    name: "Classic Single Villa",
    description: "Our indulgent Classic-themed villa offers with a pleasant outlook, elegant comfort, and including climate control for your comfort.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 1256,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-King-GardenView",
    name: "Tranquility King Room",
    description: "Relax in our serene chic king room featuring with a view of the garden's vibrant colors, along with complete with a well-appointed bathroom and designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 2630,
    currency: "MXN",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-Double-MountainView",
    name: "Standard Double Apartment",
    description: "This sophisticated double accommodation offers with a view of the mountains' changing seasons, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 2287,
    currency: "MXN",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-Double-CityView",
    name: "Superior Double Villa",
    description: "Enjoy a bohemian stay in our Superior-themed double villa, offering where city lights twinkle at night, equipped with all the modern conveniences, and unique touches of featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 1718,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-Single-CityView",
    name: "Serenity Single Room",
    description: "A calming single retreat featuring a blend of modern and historic architecture, decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 1506,
    currency: "MXN",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-Single-MountainView",
    name: "Standard Single Apartment",
    description: "Our Standard-themed single apartment offers generous luxury, panoramic where you can enjoy the peace of the highlands, and with a modern en-suite bathroom, inspired by decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 1559,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-King-CityView",
    name: "Harmony King Penthouse",
    description: "Experience our ample, regal king penthouse where the city skyline meets the horizon, with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Visual Aids"],
    pricePerNight: 2778,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-Twin-MountainView",
    name: "Signature Twin Room",
    description: "Unwind in this calming twin room with majestic mountain vistas, with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 1843,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-puerto-vallarta-2-room-1-Double-None",
    name: "Classic Double Studio",
    description: "Enjoy a relaxing stay in our Classic-themed double studio, offering with a pleasant outlook, with a private balcony or terrace, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 1738,
    currency: "MXN",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
