// Auto-generated luxury car rentals for amalfi-coast
// Country: Italy, Region: Mediterranean
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const amalfiCoastitalymediterraneanCars: LuxuryRentalCar[] = [
  {
    id: "car-amalfi-coast-nissan-1",
    make: "Nissan",
    model: "Premium",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 559,
    colorOptions: ["Burgundy", "Matte Gray", "British Racing Green", "Bronze", "Canyon Red"],
    features: ["Push-Button Start", "Massage Seats", "Automatic Emergency Braking", "Panoramic Roof", "Voice Control", "Heated Seats", "Cross Traffic Alert", "GPS Navigation", "Wi-Fi Hotspot"],
    rentalPricePerDay: 1129,
    currency: "EUR",
    available: false,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/nissan-premium.jpg",
    description: "Experience the luxury and power of the 2019 Nissan Premium. This stunning sports car offers an unforgettable driving experience in amalfi-coast.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3387,
  },
  {
    id: "car-amalfi-coast-rolls-royce-2",
    make: "Rolls-Royce",
    model: "Dawn Convertible",
    year: 2023,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 450,
    colorOptions: ["Lava Orange", "British Racing Green", "Carbon Black", "Diamond Black"],
    features: ["Massage Seats", "Panoramic Roof", "Heated Seats", "Rear Entertainment System", "Blind Spot Monitoring", "Heads-Up Display", "Adjustable Ride Height", "Sport Suspension", "Launch Control"],
    rentalPricePerDay: 808,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/suv/rolls-royce-dawn-convertible.jpg",
    description: "The 2023 Rolls-Royce Dawn Convertible combines elegance with performance. Enjoy premium features like Massage Seats and Panoramic Roof while exploring amalfi-coast in this remarkable suv.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2424,
  },
  {
    id: "car-amalfi-coast-lincoln-3",
    make: "Lincoln",
    model: "MKT Town Car",
    year: 2022,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 447,
    colorOptions: ["Ivory", "Matte Gray"],
    features: ["Touchscreen Display", "GPS Navigation", "Leather Seats", "Adaptive Cruise Control", "All-Wheel Drive", "Push-Button Start", "Lane Keep Assist", "Roof Rack", "Wireless Charging", "Wi-Fi Hotspot"],
    rentalPricePerDay: 756,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/limousine/lincoln-mkt-town-car.jpg",
    description: "Turn heads in amalfi-coast with the sophisticated 2022 Lincoln MKT Town Car. This exceptional limousine offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1512,
  },
  {
    id: "car-amalfi-coast-porsche-4",
    make: "Porsche",
    model: "Macan S",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 501,
    colorOptions: ["Diamond Black", "Lava Orange", "Matte Black"],
    features: ["Cross Traffic Alert", "Voice Control", "Launch Control", "Ventilated Seats", "Dual-Zone Climate Control", "Digital Cockpit"],
    rentalPricePerDay: 1491,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-macan-s.jpg",
    description: "The 2019 Porsche Macan S combines elegance with performance. Enjoy premium features like Cross Traffic Alert and Voice Control while exploring amalfi-coast in this remarkable sports car.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4473,
  },
  {
    id: "car-amalfi-coast-mercedes-benz-5",
    make: "Mercedes-Benz",
    model: "GLA",
    year: 2019,
    type: "Limousine",
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 406,
    colorOptions: ["Alpine White", "Ruby Red", "Sunset Orange", "Champagne", "Carbon Black"],
    features: ["Fog Lights", "Ambient Lighting", "Running Boards", "Sport Suspension", "Rear Entertainment System", "Electric Adjustable Seats"],
    rentalPricePerDay: 993,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/limousine/mercedes-benz-gla.jpg",
    description: "Discover amalfi-coast in style with the 2019 Mercedes-Benz GLA. With 406 horsepower and premium features, this limousine is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1986,
  },
  {
    id: "car-amalfi-coast-cadillac-6",
    make: "Cadillac",
    model: "Celestiq",
    year: 2023,
    type: "SUV",
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 333,
    colorOptions: ["Nardo Gray", "Burgundy", "Amethyst Purple", "Emerald Green"],
    features: ["Launch Control", "Massage Seats", "Third-Row Seating", "Four-Wheel Drive", "Panoramic Roof", "Fog Lights", "Parking Sensors", "Leather Seats", "Adaptive Cruise Control"],
    rentalPricePerDay: 517,
    currency: "EUR",
    available: false,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/suv/cadillac-celestiq.jpg",
    description: "The 2023 Cadillac Celestiq combines elegance with performance. Enjoy premium features like Launch Control and Massage Seats while exploring amalfi-coast in this remarkable suv.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2068,
  },
  {
    id: "car-amalfi-coast-genesis-7",
    make: "Genesis",
    model: "G90 Ultimate",
    year: 2019,
    type: "Electric",
    seats: 2,
    transmission: "Manual",
    fuelType: "Electric",
    horsepower: 593,
    colorOptions: ["Matte Black", "Sunset Orange", "Cement Gray"],
    features: ["Rear Entertainment System", "Panoramic Roof", "Running Boards", "Automatic Emergency Braking", "Convertible Roof", "Massage Seats", "Blind Spot Monitoring"],
    rentalPricePerDay: 605,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/electric/genesis-g90-ultimate.jpg",
    description: "Elevate your amalfi-coast experience with the prestigious 2019 Genesis G90 Ultimate. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2420,
  },
  {
    id: "car-amalfi-coast-aston-martin-8",
    make: "Aston Martin",
    model: "DBS Superleggera Volante",
    year: 2020,
    type: "Sports Car",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 580,
    colorOptions: ["Midnight Blue", "Diamond Black", "Champagne"],
    features: ["Bluetooth", "Sport Suspension", "LED Headlights", "Premium Sound System", "Parking Sensors"],
    rentalPricePerDay: 1453,
    currency: "EUR",
    available: false,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/sports-car/aston-martin-dbs-superleggera-volante.jpg",
    description: "Discover amalfi-coast in style with the 2020 Aston Martin DBS Superleggera Volante. With 580 horsepower and premium features, this sports car is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 5812,
  },
  {
    id: "car-amalfi-coast-mclaren-9",
    make: "McLaren",
    model: "765LT Spider",
    year: 2019,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 410,
    colorOptions: ["Metallic Silver", "Ocean Teal", "Gunmetal Gray"],
    features: ["LED Headlights", "Blind Spot Monitoring", "Remote Start", "Keyless Entry", "Fog Lights", "Ambient Lighting"],
    rentalPricePerDay: 745,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/coupe/mclaren-765lt-spider.jpg",
    description: "Turn heads in amalfi-coast with the sophisticated 2019 McLaren 765LT Spider. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 1490,
  },
  {
    id: "car-amalfi-coast-mercedes-benz-10",
    make: "Mercedes-Benz",
    model: "C63 AMG",
    year: 2022,
    type: "Hybrid",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 391,
    colorOptions: ["Ocean Teal", "Amethyst Purple", "Cement Gray", "Emerald Green"],
    features: ["Convertible Roof", "Premium Sound System", "Launch Control", "Heads-Up Display", "Voice Control"],
    rentalPricePerDay: 723,
    currency: "EUR",
    available: false,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/hybrid/mercedes-benz-c63-amg.jpg",
    description: "The 2022 Mercedes-Benz C63 AMG combines elegance with performance. Enjoy premium features like Convertible Roof and Premium Sound System while exploring amalfi-coast in this remarkable hybrid.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2892,
  },
  {
    id: "car-amalfi-coast-mclaren-11",
    make: "McLaren",
    model: "P1 GTR",
    year: 2021,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 569,
    colorOptions: ["Midnight Blue", "Matte Gray", "Gunmetal Gray", "Diamond Black", "Steel Blue"],
    features: ["Tri-Zone Climate Control", "Convertible Roof", "Sport Suspension", "Apple CarPlay", "Power Tailgate", "All-Wheel Drive", "Digital Cockpit", "Keyless Entry", "Adaptive Cruise Control"],
    rentalPricePerDay: 722,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/coupe/mclaren-p1-gtr.jpg",
    description: "Turn heads in amalfi-coast with the sophisticated 2021 McLaren P1 GTR. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2166,
  },
  {
    id: "car-amalfi-coast-lamborghini-12",
    make: "Lamborghini",
    model: "Countach LPI 800-4",
    year: 2020,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 565,
    colorOptions: ["Carbon Black", "Matte Black", "Diamond Black"],
    features: ["Dual-Zone Climate Control", "Automatic Emergency Braking", "Push-Button Start", "Power Tailgate", "GPS Navigation", "LED Headlights", "All-Wheel Drive"],
    rentalPricePerDay: 760,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/coupe/lamborghini-countach-lpi-800-4.jpg",
    description: "Elevate your amalfi-coast experience with the prestigious 2020 Lamborghini Countach LPI 800-4. This high-performance coupe delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 1520,
  },
  {
    id: "car-amalfi-coast-infiniti-13",
    make: "Infiniti",
    model: "Q50",
    year: 2023,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 382,
    colorOptions: ["Copper", "Ice Blue", "Metallic Silver", "Champagne"],
    features: ["Launch Control", "Dual-Zone Climate Control", "Parking Sensors", "Ambient Lighting", "Cross Traffic Alert", "Panoramic Roof", "LED Headlights", "Touchscreen Display", "Blind Spot Monitoring"],
    rentalPricePerDay: 528,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/suv/infiniti-q50.jpg",
    description: "Discover amalfi-coast in style with the 2023 Infiniti Q50. With 382 horsepower and premium features, this suv is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2112,
  },
  {
    id: "car-amalfi-coast-mercedes-benz-14",
    make: "Mercedes-Benz",
    model: "GLC",
    year: 2023,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 451,
    colorOptions: ["Ruby Red", "Forest Green", "Sapphire Blue"],
    features: ["Power Tailgate", "Massage Seats", "All-Wheel Drive", "Convertible Roof", "Backup Camera", "Panoramic Roof", "Cross Traffic Alert", "LED Headlights", "Blind Spot Monitoring", "Sunroof"],
    rentalPricePerDay: 780,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/convertible/mercedes-benz-glc.jpg",
    description: "Turn heads in amalfi-coast with the sophisticated 2023 Mercedes-Benz GLC. This exceptional convertible offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2340,
  },
  {
    id: "car-amalfi-coast-bmw-15",
    make: "BMW",
    model: "iX5 M50",
    year: 2021,
    type: "Limousine",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 355,
    colorOptions: ["Steel Blue", "Matte Gray", "Canyon Red"],
    features: ["Ventilated Seats", "Lane Keep Assist", "Tri-Zone Climate Control", "Push-Button Start", "Rear Entertainment System"],
    rentalPricePerDay: 968,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/limousine/bmw-ix5-m50.jpg",
    description: "Discover amalfi-coast in style with the 2021 BMW iX5 M50. With 355 horsepower and premium features, this limousine is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3872,
  },
  {
    id: "car-amalfi-coast-mercedes-benz-16",
    make: "Mercedes-Benz",
    model: "GLA",
    year: 2020,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 453,
    colorOptions: ["Gunmetal Gray", "Ocean Teal", "Sunset Orange", "Alpine White"],
    features: ["Digital Cockpit", "Cross Traffic Alert", "Ventilated Seats", "GPS Navigation", "Ambient Lighting", "Night Vision"],
    rentalPricePerDay: 709,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/electric/mercedes-benz-gla.jpg",
    description: "Experience the luxury and power of the 2020 Mercedes-Benz GLA. This stunning electric offers an unforgettable driving experience in amalfi-coast.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1418,
  },
  {
    id: "car-amalfi-coast-infiniti-17",
    make: "Infiniti",
    model: "QX55",
    year: 2023,
    type: "Sedan",
    seats: 5,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 434,
    colorOptions: ["Ocean Teal", "Sapphire Blue", "Lava Orange", "Graphite", "Metallic Silver"],
    features: ["Rear Entertainment System", "Parking Sensors", "Apple CarPlay", "Android Auto", "Running Boards", "GPS Navigation"],
    rentalPricePerDay: 433,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/sedan/infiniti-qx55.jpg",
    description: "Discover amalfi-coast in style with the 2023 Infiniti QX55. With 434 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1299,
  },
  {
    id: "car-amalfi-coast-genesis-18",
    make: "Genesis",
    model: "G60 Ultimate",
    year: 2023,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 299,
    colorOptions: ["Sapphire Blue", "Ivory", "Ocean Teal"],
    features: ["LED Headlights", "Wi-Fi Hotspot", "Push-Button Start", "Blind Spot Monitoring", "Bluetooth", "Fog Lights", "Running Boards", "Tri-Zone Climate Control"],
    rentalPricePerDay: 419,
    currency: "EUR",
    available: false,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/sedan/genesis-g60-ultimate.jpg",
    description: "The 2023 Genesis G60 Ultimate combines elegance with performance. Enjoy premium features like LED Headlights and Wi-Fi Hotspot while exploring amalfi-coast in this remarkable sedan.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1676,
  },
  {
    id: "car-amalfi-coast-cadillac-19",
    make: "Cadillac",
    model: "CT5",
    year: 2019,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 537,
    colorOptions: ["Emerald Green", "Carbon Black", "Amethyst Purple"],
    features: ["Lane Keep Assist", "Night Vision", "Wi-Fi Hotspot", "Four-Wheel Drive", "Adaptive Cruise Control", "Android Auto", "Roof Rack"],
    rentalPricePerDay: 584,
    currency: "EUR",
    available: true,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/electric/cadillac-ct5.jpg",
    description: "Experience the luxury and power of the 2019 Cadillac CT5. This stunning electric offers an unforgettable driving experience in amalfi-coast.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1752,
  },
  {
    id: "car-amalfi-coast-infiniti-20",
    make: "Infiniti",
    model: "QX50S",
    year: 2021,
    type: "Coupe",
    seats: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 555,
    colorOptions: ["Emerald Green", "Ivory", "Bronze", "Lava Orange"],
    features: ["Automatic Emergency Braking", "GPS Navigation", "Apple CarPlay", "Remote Start", "Running Boards", "Tri-Zone Climate Control", "Performance Tires", "Wireless Charging"],
    rentalPricePerDay: 459,
    currency: "EUR",
    available: false,
    pickUpCity: "Amalfi Coast",
    pickUpCountry: "Italy",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/coupe/infiniti-qx50s.jpg",
    description: "Discover amalfi-coast in style with the 2021 Infiniti QX50S. With 555 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1836,
  }
];
