// Auto-generated luxury car rentals for atlas-mountains
// Country: Morocco, Region: Morocco
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const atlasMountainsmoroccomoroccoCars: LuxuryRentalCar[] = [
  {
    id: "car-atlas-mountains-porsche-1",
    make: "Porsche",
    model: "Macan S",
    year: 2023,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 510,
    colorOptions: ["British Racing Green", "Metallic Silver", "Matte Gray"],
    features: ["Power Tailgate", "Panoramic Roof", "Blind Spot Monitoring", "Rear Entertainment System", "Tow Package", "Satellite Radio"],
    rentalPricePerDay: 9126,
    currency: "MAD",
    available: false,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/convertible/porsche-macan-s.jpg",
    description: "The 2023 Porsche Macan S combines elegance with performance. Enjoy premium features like Power Tailgate and Panoramic Roof while exploring atlas-mountains in this remarkable convertible.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 36504,
  },
  {
    id: "car-atlas-mountains-pagani-2",
    make: "Pagani",
    model: "Zonda S",
    year: 2023,
    type: "Sports Car",
    seats: 2,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 509,
    colorOptions: ["Nardo Gray", "Diamond Black", "Matte Gray", "Champagne", "Carbon Black"],
    features: ["Rear Entertainment System", "Fog Lights", "All-Wheel Drive", "Parking Sensors", "Power Tailgate", "Four-Wheel Drive", "Sunroof"],
    rentalPricePerDay: 10084,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/sports-car/pagani-zonda-s.jpg",
    description: "Elevate your atlas-mountains experience with the prestigious 2023 Pagani Zonda S. This high-performance sports car delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 20168,
  },
  {
    id: "car-atlas-mountains-audi-3",
    make: "Audi",
    model: "RS 2 Avant",
    year: 2023,
    type: "Limousine",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 500,
    colorOptions: ["Matte Black", "Ocean Teal", "Sunset Orange", "Rose Gold"],
    features: ["Running Boards", "Electric Adjustable Seats", "Blind Spot Monitoring", "Panoramic Roof", "Performance Tires", "360-Degree Camera"],
    rentalPricePerDay: 9645,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/limousine/audi-rs-2-avant.jpg",
    description: "Turn heads in atlas-mountains with the sophisticated 2023 Audi RS 2 Avant. This exceptional limousine offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 38580,
  },
  {
    id: "car-atlas-mountains-lexus-4",
    make: "Lexus",
    model: "LX 570",
    year: 2019,
    type: "Sedan",
    seats: 5,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 347,
    colorOptions: ["Cement Gray", "Rose Gold", "Ocean Teal", "Amethyst Purple", "Moonlight Silver"],
    features: ["Sport Suspension", "Launch Control", "Night Vision", "Convertible Roof", "Backup Camera", "Keyless Entry", "Android Auto"],
    rentalPricePerDay: 3637,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/sedan/lexus-lx-570.jpg",
    description: "Experience the luxury and power of the 2019 Lexus LX 570. This stunning sedan offers an unforgettable driving experience in atlas-mountains.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 7274,
  },
  {
    id: "car-atlas-mountains-lamborghini-5",
    make: "Lamborghini",
    model: "Huracán EVO Spyder",
    year: 2019,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 417,
    colorOptions: ["Diamond Black", "Carbon Black", "Gunmetal Gray"],
    features: ["Tow Package", "Panoramic Roof", "Electric Adjustable Seats", "Keyless Entry", "Blind Spot Monitoring", "Four-Wheel Drive", "Adjustable Ride Height"],
    rentalPricePerDay: 8200,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/suv/lamborghini-huracán-evo-spyder.jpg",
    description: "Turn heads in atlas-mountains with the sophisticated 2019 Lamborghini Huracán EVO Spyder. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 16400,
  },
  {
    id: "car-atlas-mountains-audi-6",
    make: "Audi",
    model: "RS Q3",
    year: 2020,
    type: "Convertible",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 355,
    colorOptions: ["Matte Black", "Cement Gray", "Ivory", "Forest Green"],
    features: ["Launch Control", "Premium Sound System", "Android Auto", "LED Headlights", "Ventilated Seats"],
    rentalPricePerDay: 7394,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/convertible/audi-rs-q3.jpg",
    description: "Elevate your atlas-mountains experience with the prestigious 2020 Audi RS Q3. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 29576,
  },
  {
    id: "car-atlas-mountains-bmw-7",
    make: "BMW",
    model: "M4",
    year: 2021,
    type: "Limousine",
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 516,
    colorOptions: ["Carbon Black", "Canyon Red", "Nardo Gray", "Ruby Red"],
    features: ["Ventilated Seats", "Wireless Charging", "Backup Camera", "Voice Control", "Heads-Up Display", "Apple CarPlay"],
    rentalPricePerDay: 9709,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/limousine/bmw-m4.jpg",
    description: "Experience the luxury and power of the 2021 BMW M4. This stunning limousine offers an unforgettable driving experience in atlas-mountains.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 19418,
  },
  {
    id: "car-atlas-mountains-ford-8",
    make: "Ford",
    model: "F-450 Super Duty",
    year: 2019,
    type: "Hybrid",
    seats: 2,
    transmission: "Manual",
    fuelType: "Hybrid",
    horsepower: 519,
    colorOptions: ["Nardo Gray", "Ice Blue", "Glacier White", "Ocean Teal"],
    features: ["Backup Camera", "Leather Seats", "Panoramic Roof", "Parking Sensors", "Fog Lights", "Performance Tires", "Tow Package"],
    rentalPricePerDay: 5104,
    currency: "MAD",
    available: false,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/hybrid/ford-f-450-super-duty.jpg",
    description: "The 2019 Ford F-450 Super Duty combines elegance with performance. Enjoy premium features like Backup Camera and Leather Seats while exploring atlas-mountains in this remarkable hybrid.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 20416,
  },
  {
    id: "car-atlas-mountains-rivian-9",
    make: "Rivian",
    model: "R1S",
    year: 2022,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 477,
    colorOptions: ["Sapphire Blue", "Ocean Teal", "Carbon Black", "Nardo Gray", "Steel Blue"],
    features: ["Performance Tires", "Tow Package", "Parking Sensors", "Electric Adjustable Seats", "Digital Cockpit", "Tri-Zone Climate Control", "Wireless Charging", "Touchscreen Display"],
    rentalPricePerDay: 4615,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/suv/rivian-r1s.jpg",
    description: "Turn heads in atlas-mountains with the sophisticated 2022 Rivian R1S. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 9230,
  },
  {
    id: "car-atlas-mountains-porsche-10",
    make: "Porsche",
    model: "Taycan Cross Turismo",
    year: 2020,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 635,
    colorOptions: ["Copper", "Graphite", "Gunmetal Gray"],
    features: ["Convertible Roof", "Ambient Lighting", "Panoramic Roof", "Heads-Up Display", "Ventilated Seats", "Remote Start", "Push-Button Start", "Dual-Zone Climate Control", "Roof Rack"],
    rentalPricePerDay: 15149,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-taycan-cross-turismo.jpg",
    description: "The 2020 Porsche Taycan Cross Turismo combines elegance with performance. Enjoy premium features like Convertible Roof and Ambient Lighting while exploring atlas-mountains in this remarkable sports car.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 60596,
  },
  {
    id: "car-atlas-mountains-koenigsegg-11",
    make: "Koenigsegg",
    model: "Agera S",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 541,
    colorOptions: ["Ocean Teal", "Midnight Blue", "Amethyst Purple"],
    features: ["Remote Start", "Lane Keep Assist", "Massage Seats", "Leather Seats", "Fog Lights", "Launch Control", "Digital Cockpit", "Wireless Charging"],
    rentalPricePerDay: 10198,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/koenigsegg-agera-s.jpg",
    description: "The 2019 Koenigsegg Agera S combines elegance with performance. Enjoy premium features like Remote Start and Lane Keep Assist while exploring atlas-mountains in this remarkable sports car.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 30594,
  },
  {
    id: "car-atlas-mountains-aston-martin-12",
    make: "Aston Martin",
    model: "Rapide AMR",
    year: 2023,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 635,
    colorOptions: ["Ocean Teal", "Steel Blue", "Metallic Silver", "Bronze"],
    features: ["Backup Camera", "Automatic Emergency Braking", "Running Boards", "Performance Tires", "Voice Control", "Heated Seats", "Lane Keep Assist"],
    rentalPricePerDay: 15057,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/sports-car/aston-martin-rapide-amr.jpg",
    description: "Elevate your atlas-mountains experience with the prestigious 2023 Aston Martin Rapide AMR. This high-performance sports car delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 60228,
  },
  {
    id: "car-atlas-mountains-porsche-13",
    make: "Porsche",
    model: "Macan",
    year: 2022,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 410,
    colorOptions: ["Ice Blue", "British Racing Green", "Bronze"],
    features: ["Backup Camera", "Rear Entertainment System", "Sport Suspension", "Satellite Radio", "Android Auto"],
    rentalPricePerDay: 6015,
    currency: "MAD",
    available: true,
    pickUpCity: "Atlas Mountains",
    pickUpCountry: "Morocco",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/coupe/porsche-macan.jpg",
    description: "Discover atlas-mountains in style with the 2022 Porsche Macan. With 410 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 12030,
  }
];
