// Auto-generated luxury car rentals for berlin
// Country: Germany, Region: Northern Europe
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const berlingermanynorthernEuropeCars: LuxuryRentalCar[] = [
  {
    id: "car-berlin-audi-1",
    make: "Audi",
    model: "Q2",
    year: 2023,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 350,
    colorOptions: ["Bronze", "Burgundy", "Champagne", "Sapphire Blue"],
    features: ["Digital Cockpit", "Convertible Roof", "Power Tailgate", "Sport Suspension", "Keyless Entry", "Bluetooth", "Fog Lights", "Backup Camera"],
    rentalPricePerDay: 1033,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/limousine/audi-q2.jpg",
    description: "Experience the luxury and power of the 2023 Audi Q2. This stunning limousine offers an unforgettable driving experience in berlin.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2066,
  },
  {
    id: "car-berlin-ferrari-2",
    make: "Ferrari",
    model: "812 Superfast",
    year: 2019,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 470,
    colorOptions: ["Emerald Green", "Alpine White", "Sunset Orange", "Moonlight Silver"],
    features: ["Lane Keep Assist", "GPS Navigation", "Blind Spot Monitoring", "Night Vision", "Heads-Up Display", "Sunroof", "Ventilated Seats"],
    rentalPricePerDay: 1043,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/convertible/ferrari-812-superfast.jpg",
    description: "Experience the luxury and power of the 2019 Ferrari 812 Superfast. This stunning convertible offers an unforgettable driving experience in berlin.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3129,
  },
  {
    id: "car-berlin-porsche-3",
    make: "Porsche",
    model: "Panamera",
    year: 2022,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 499,
    colorOptions: ["Gunmetal Gray", "Pearl White", "Glacier White"],
    features: ["Massage Seats", "Voice Control", "Roof Rack", "Dual-Zone Climate Control", "Power Tailgate", "Wi-Fi Hotspot"],
    rentalPricePerDay: 808,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/suv/porsche-panamera.jpg",
    description: "Turn heads in berlin with the sophisticated 2022 Porsche Panamera. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2424,
  },
  {
    id: "car-berlin-ferrari-4",
    make: "Ferrari",
    model: "Portofino M",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 537,
    colorOptions: ["British Racing Green", "Rose Gold", "Canyon Red"],
    features: ["Tri-Zone Climate Control", "Heated Seats", "GPS Navigation", "Panoramic Roof", "Sport Suspension", "Backup Camera", "Lane Keep Assist", "Fog Lights", "All-Wheel Drive"],
    rentalPricePerDay: 1786,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/sports-car/ferrari-portofino-m.jpg",
    description: "The 2019 Ferrari Portofino M combines elegance with performance. Enjoy premium features like Tri-Zone Climate Control and Heated Seats while exploring berlin in this remarkable sports car.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 7144,
  },
  {
    id: "car-berlin-bentley-5",
    make: "Bentley",
    model: "Bentley Continental GT V8",
    year: 2021,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 515,
    colorOptions: ["Graphite", "Matte Gray", "Nardo Gray", "Alpine White"],
    features: ["Keyless Entry", "GPS Navigation", "Tow Package", "Android Auto", "Touchscreen Display", "Performance Tires", "Sport Suspension"],
    rentalPricePerDay: 1395,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/limousine/bentley-bentley-continental-gt-v8.jpg",
    description: "Experience the luxury and power of the 2021 Bentley Bentley Continental GT V8. This stunning limousine offers an unforgettable driving experience in berlin.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 5580,
  },
  {
    id: "car-berlin-volvo-6",
    make: "Volvo",
    model: "V60 Recharge",
    year: 2020,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 348,
    colorOptions: ["Metallic Silver", "Matte Gray", "Moonlight Silver"],
    features: ["Fog Lights", "Apple CarPlay", "Power Tailgate", "Automatic Emergency Braking", "Sunroof", "Sport Suspension", "Voice Control", "Four-Wheel Drive", "Ventilated Seats"],
    rentalPricePerDay: 368,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/sedan/volvo-v60-recharge.jpg",
    description: "The 2020 Volvo V60 Recharge combines elegance with performance. Enjoy premium features like Fog Lights and Apple CarPlay while exploring berlin in this remarkable sedan.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1104,
  },
  {
    id: "car-berlin-toyota-7",
    make: "Toyota",
    model: "Corolla Hybrid",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 576,
    colorOptions: ["Cement Gray", "Moonlight Silver", "Diamond Black", "Metallic Silver"],
    features: ["Leather Seats", "Wireless Charging", "Keyless Entry", "Digital Cockpit", "Wi-Fi Hotspot", "Convertible Roof", "Running Boards", "Ambient Lighting", "Roof Rack", "Sport Suspension"],
    rentalPricePerDay: 1042,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/sports-car/toyota-corolla-hybrid.jpg",
    description: "Discover berlin in style with the 2019 Toyota Corolla Hybrid. With 576 horsepower and premium features, this sports car is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4168,
  },
  {
    id: "car-berlin-jaguar-8",
    make: "Jaguar",
    model: "F-TYPE P575",
    year: 2023,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 380,
    colorOptions: ["Steel Blue", "Sunset Orange", "Lava Orange"],
    features: ["Roof Rack", "Tri-Zone Climate Control", "Four-Wheel Drive", "Wireless Charging"],
    rentalPricePerDay: 518,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/sedan/jaguar-f-type-p575.jpg",
    description: "Elevate your berlin experience with the prestigious 2023 Jaguar F-TYPE P575. This high-performance sedan delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1554,
  },
  {
    id: "car-berlin-bmw-9",
    make: "BMW",
    model: "Z4",
    year: 2022,
    type: "Hybrid",
    seats: 3,
    transmission: "Manual",
    fuelType: "Hybrid",
    horsepower: 512,
    colorOptions: ["Steel Blue", "Ice Blue", "Alpine White", "Lava Orange"],
    features: ["Leather Seats", "Adaptive Cruise Control", "Rear Entertainment System", "Heads-Up Display", "Convertible Roof", "LED Headlights", "Four-Wheel Drive", "Ventilated Seats"],
    rentalPricePerDay: 739,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/hybrid/bmw-z4.jpg",
    description: "Discover berlin in style with the 2022 BMW Z4. With 512 horsepower and premium features, this hybrid is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1478,
  },
  {
    id: "car-berlin-volvo-10",
    make: "Volvo",
    model: "V90 T5",
    year: 2023,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 465,
    colorOptions: ["Nardo Gray", "Diamond Black", "Moonlight Silver"],
    features: ["Tri-Zone Climate Control", "Wireless Charging", "Automatic Emergency Braking", "Push-Button Start", "Ambient Lighting"],
    rentalPricePerDay: 510,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/suv/volvo-v90-t5.jpg",
    description: "Discover berlin in style with the 2023 Volvo V90 T5. With 465 horsepower and premium features, this suv is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2040,
  },
  {
    id: "car-berlin-mercedes-benz-11",
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2020,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 585,
    colorOptions: ["Canyon Red", "Diamond Black", "British Racing Green", "Metallic Silver"],
    features: ["Touchscreen Display", "Launch Control", "Heated Seats", "LED Headlights", "Premium Sound System"],
    rentalPricePerDay: 618,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/electric/mercedes-benz-c-class.jpg",
    description: "The 2020 Mercedes-Benz C-Class combines elegance with performance. Enjoy premium features like Touchscreen Display and Launch Control while exploring berlin in this remarkable electric.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2472,
  },
  {
    id: "car-berlin-lamborghini-12",
    make: "Lamborghini",
    model: "Huracán",
    year: 2020,
    type: "Hybrid",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 560,
    colorOptions: ["Sapphire Blue", "Matte Black", "Diamond Black", "Pearl White", "Glacier White"],
    features: ["Electric Adjustable Seats", "Wireless Charging", "Voice Control", "Ambient Lighting", "Launch Control", "Keyless Entry", "Wi-Fi Hotspot", "Cross Traffic Alert", "Parking Sensors"],
    rentalPricePerDay: 864,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/hybrid/lamborghini-huracán.jpg",
    description: "Turn heads in berlin with the sophisticated 2020 Lamborghini Huracán. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3456,
  },
  {
    id: "car-berlin-lexus-13",
    make: "Lexus",
    model: "LX 570",
    year: 2022,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 492,
    colorOptions: ["Midnight Blue", "Rose Gold", "Graphite", "Ruby Red"],
    features: ["Lane Keep Assist", "Four-Wheel Drive", "Automatic Emergency Braking", "Dual-Zone Climate Control", "Bluetooth", "Blind Spot Monitoring"],
    rentalPricePerDay: 626,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/suv/lexus-lx-570.jpg",
    description: "The 2022 Lexus LX 570 combines elegance with performance. Enjoy premium features like Lane Keep Assist and Four-Wheel Drive while exploring berlin in this remarkable suv.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1878,
  },
  {
    id: "car-berlin-lucid-14",
    make: "Lucid",
    model: "Air Touring",
    year: 2023,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 573,
    colorOptions: ["Amethyst Purple", "Carbon Black", "Sapphire Blue", "Matte Gray", "Emerald Green"],
    features: ["Third-Row Seating", "Satellite Radio", "Heads-Up Display", "Push-Button Start", "Driver Attention Monitoring"],
    rentalPricePerDay: 491,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/electric/lucid-air-touring.jpg",
    description: "Elevate your berlin experience with the prestigious 2023 Lucid Air Touring. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1473,
  },
  {
    id: "car-berlin-aston-martin-15",
    make: "Aston Martin",
    model: "Vantage Coupe",
    year: 2022,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 437,
    colorOptions: ["Champagne", "Moonlight Silver", "Pearl White", "Metallic Silver"],
    features: ["Dual-Zone Climate Control", "Panoramic Roof", "Sunroof", "Android Auto", "Lane Keep Assist"],
    rentalPricePerDay: 910,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/convertible/aston-martin-vantage-coupe.jpg",
    description: "Elevate your berlin experience with the prestigious 2022 Aston Martin Vantage Coupe. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 1820,
  },
  {
    id: "car-berlin-mercedes-benz-16",
    make: "Mercedes-Benz",
    model: "EQS",
    year: 2020,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 489,
    colorOptions: ["Alpine White", "Ice Blue", "Graphite", "Matte Black", "Sunset Orange"],
    features: ["Four-Wheel Drive", "Apple CarPlay", "Massage Seats", "Touchscreen Display", "Dual-Zone Climate Control", "Cross Traffic Alert", "Remote Start", "Driver Attention Monitoring"],
    rentalPricePerDay: 738,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/hybrid/mercedes-benz-eqs.jpg",
    description: "Elevate your berlin experience with the prestigious 2020 Mercedes-Benz EQS. This high-performance hybrid delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2214,
  },
  {
    id: "car-berlin-rolls-royce-17",
    make: "Rolls-Royce",
    model: "Phantom Series II Extended Wheelbase",
    year: 2020,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 488,
    colorOptions: ["Carbon Black", "Matte Black", "Ruby Red", "Ocean Teal"],
    features: ["Automatic Emergency Braking", "Rear Entertainment System", "Apple CarPlay", "Convertible Roof", "Adaptive Cruise Control", "Bluetooth", "Digital Cockpit"],
    rentalPricePerDay: 940,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/suv/rolls-royce-phantom-series-ii-extended-wheelbase.jpg",
    description: "Experience the luxury and power of the 2020 Rolls-Royce Phantom Series II Extended Wheelbase. This stunning suv offers an unforgettable driving experience in berlin.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2820,
  },
  {
    id: "car-berlin-infiniti-18",
    make: "Infiniti",
    model: "QX30S",
    year: 2023,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 525,
    colorOptions: ["Matte Gray", "Burgundy", "Alpine White", "Carbon Black"],
    features: ["Heads-Up Display", "Power Tailgate", "Blind Spot Monitoring", "LED Headlights", "Android Auto", "Driver Attention Monitoring", "Night Vision", "Keyless Entry"],
    rentalPricePerDay: 390,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/coupe/infiniti-qx30s.jpg",
    description: "Turn heads in berlin with the sophisticated 2023 Infiniti QX30S. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1170,
  },
  {
    id: "car-berlin-hyundai-19",
    make: "Hyundai",
    model: "Elantra Hybrid",
    year: 2021,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 540,
    colorOptions: ["Ivory", "Copper", "Ruby Red", "British Racing Green", "Nardo Gray"],
    features: ["Premium Sound System", "Electric Adjustable Seats", "Four-Wheel Drive", "Automatic Emergency Braking", "Blind Spot Monitoring", "Tow Package", "Keyless Entry", "Cross Traffic Alert", "Panoramic Roof", "Wi-Fi Hotspot"],
    rentalPricePerDay: 470,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/electric/hyundai-elantra-hybrid.jpg",
    description: "Discover berlin in style with the 2021 Hyundai Elantra Hybrid. With 540 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 940,
  },
  {
    id: "car-berlin-aston-martin-20",
    make: "Aston Martin",
    model: "DBX",
    year: 2023,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 662,
    colorOptions: ["Gunmetal Gray", "Forest Green", "Nardo Gray", "Burgundy"],
    features: ["360-Degree Camera", "Sport Suspension", "Voice Control", "Ambient Lighting", "Adjustable Ride Height"],
    rentalPricePerDay: 1405,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/sports-car/aston-martin-dbx.jpg",
    description: "The 2023 Aston Martin DBX combines elegance with performance. Enjoy premium features like 360-Degree Camera and Sport Suspension while exploring berlin in this remarkable sports car.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4215,
  },
  {
    id: "car-berlin-lexus-21",
    make: "Lexus",
    model: "RX L",
    year: 2023,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 391,
    colorOptions: ["Champagne", "Graphite", "Ruby Red", "Matte Black"],
    features: ["Satellite Radio", "Cross Traffic Alert", "Electric Adjustable Seats", "Convertible Roof", "All-Wheel Drive", "Performance Tires", "Android Auto", "Ambient Lighting"],
    rentalPricePerDay: 711,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/hybrid/lexus-rx-l.jpg",
    description: "The 2023 Lexus RX L combines elegance with performance. Enjoy premium features like Satellite Radio and Cross Traffic Alert while exploring berlin in this remarkable hybrid.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1422,
  },
  {
    id: "car-berlin-jaguar-22",
    make: "Jaguar",
    model: "E-PACE P300",
    year: 2020,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 484,
    colorOptions: ["Matte Black", "Glacier White", "Lava Orange"],
    features: ["Parking Sensors", "Tow Package", "All-Wheel Drive", "Launch Control", "Running Boards"],
    rentalPricePerDay: 682,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/electric/jaguar-e-pace-p300.jpg",
    description: "Discover berlin in style with the 2020 Jaguar E-PACE P300. With 484 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2728,
  },
  {
    id: "car-berlin-chrysler-23",
    make: "Chrysler",
    model: "Voyager",
    year: 2022,
    type: "Limousine",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 360,
    colorOptions: ["Metallic Silver", "Diamond Black", "Gunmetal Gray", "Moonlight Silver", "Carbon Black"],
    features: ["Electric Adjustable Seats", "Tow Package", "Four-Wheel Drive", "Launch Control", "Performance Tires", "Wi-Fi Hotspot", "Android Auto", "Apple CarPlay", "Voice Control"],
    rentalPricePerDay: 758,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/limousine/chrysler-voyager.jpg",
    description: "Experience the luxury and power of the 2022 Chrysler Voyager. This stunning limousine offers an unforgettable driving experience in berlin.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1516,
  },
  {
    id: "car-berlin-genesis-24",
    make: "Genesis",
    model: "GV70",
    year: 2023,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 540,
    colorOptions: ["Midnight Blue", "Ivory", "Canyon Red", "Graphite"],
    features: ["Driver Attention Monitoring", "Night Vision", "Heads-Up Display", "Backup Camera", "Dual-Zone Climate Control", "Electric Adjustable Seats", "Leather Seats"],
    rentalPricePerDay: 486,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/electric/genesis-gv70.jpg",
    description: "Discover berlin in style with the 2023 Genesis GV70. With 540 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1458,
  },
  {
    id: "car-berlin-lamborghini-25",
    make: "Lamborghini",
    model: "Aventador",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 554,
    colorOptions: ["Lava Orange", "Bronze", "Midnight Blue", "Matte Gray"],
    features: ["Bluetooth", "Heated Seats", "Cross Traffic Alert", "Adjustable Ride Height", "Four-Wheel Drive", "Sport Suspension"],
    rentalPricePerDay: 1754,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/lamborghini-aventador.jpg",
    description: "The 2019 Lamborghini Aventador combines elegance with performance. Enjoy premium features like Bluetooth and Heated Seats while exploring berlin in this remarkable sports car.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 5262,
  }
];
