// Auto-generated luxury car rentals for berlin
// Country: Germany, Region: Germany
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const berlingermanygermanyCars: LuxuryRentalCar[] = [
  {
    id: "car-berlin-tesla-1",
    make: "Tesla",
    model: "Model S Plaid",
    year: 2021,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 465,
    colorOptions: ["Diamond Black", "Ice Blue", "Alpine White"],
    features: ["Launch Control", "Touchscreen Display", "Roof Rack", "Keyless Entry", "LED Headlights", "Bluetooth"],
    rentalPricePerDay: 595,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/electric/tesla-model-s-plaid.jpg",
    description: "Elevate your berlin experience with the prestigious 2021 Tesla Model S Plaid. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1190,
  },
  {
    id: "car-berlin-rolls-royce-2",
    make: "Rolls-Royce",
    model: "Silver Spirit",
    year: 2021,
    type: "Limousine",
    seats: 6,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 403,
    colorOptions: ["Gunmetal Gray", "Moonlight Silver", "Lava Orange", "Pearl White", "Ocean Teal"],
    features: ["Heads-Up Display", "Sunroof", "Massage Seats", "Remote Start", "Heated Seats"],
    rentalPricePerDay: 1518,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-silver-spirit.jpg",
    description: "Experience the luxury and power of the 2021 Rolls-Royce Silver Spirit. This stunning limousine offers an unforgettable driving experience in berlin.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3036,
  },
  {
    id: "car-berlin-hyundai-3",
    make: "Hyundai",
    model: "Elantra Hybrid",
    year: 2022,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 403,
    colorOptions: ["Cement Gray", "Glacier White", "Carbon Black", "Matte Gray"],
    features: ["Driver Attention Monitoring", "Apple CarPlay", "Remote Start", "Satellite Radio", "Heads-Up Display", "Panoramic Roof", "Push-Button Start", "LED Headlights"],
    rentalPricePerDay: 656,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/hybrid/hyundai-elantra-hybrid.jpg",
    description: "Elevate your berlin experience with the prestigious 2022 Hyundai Elantra Hybrid. This high-performance hybrid delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1312,
  },
  {
    id: "car-berlin-audi-4",
    make: "Audi",
    model: "A8 L",
    year: 2019,
    type: "Convertible",
    seats: 4,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 532,
    colorOptions: ["Amethyst Purple", "Bronze", "Carbon Black", "Metallic Silver"],
    features: ["Power Tailgate", "Rear Entertainment System", "Night Vision", "GPS Navigation", "Sport Suspension"],
    rentalPricePerDay: 802,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/convertible/audi-a8-l.jpg",
    description: "Turn heads in berlin with the sophisticated 2019 Audi A8 L. This exceptional convertible offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 1604,
  },
  {
    id: "car-berlin-rolls-royce-5",
    make: "Rolls-Royce",
    model: "Ghost Black Badge",
    year: 2019,
    type: "Limousine",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 442,
    colorOptions: ["Canyon Red", "Forest Green", "Graphite", "Champagne"],
    features: ["Fog Lights", "Satellite Radio", "Voice Control", "Heads-Up Display", "Touchscreen Display", "Premium Sound System", "Dual-Zone Climate Control", "LED Headlights", "Running Boards", "Wireless Charging"],
    rentalPricePerDay: 1372,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-ghost-black-badge.jpg",
    description: "Turn heads in berlin with the sophisticated 2019 Rolls-Royce Ghost Black Badge. This exceptional limousine offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 5488,
  },
  {
    id: "car-berlin-infiniti-6",
    make: "Infiniti",
    model: "QX50",
    year: 2022,
    type: "Sedan",
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 333,
    colorOptions: ["Diamond Black", "Matte Gray", "Steel Blue", "British Racing Green", "Ice Blue"],
    features: ["Android Auto", "Third-Row Seating", "Four-Wheel Drive", "GPS Navigation", "Adjustable Ride Height"],
    rentalPricePerDay: 304,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/sedan/infiniti-qx50.jpg",
    description: "Elevate your berlin experience with the prestigious 2022 Infiniti QX50. This high-performance sedan delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1216,
  },
  {
    id: "car-berlin-bmw-7",
    make: "BMW",
    model: "iX3",
    year: 2020,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 514,
    colorOptions: ["Amethyst Purple", "Ruby Red"],
    features: ["Remote Start", "Push-Button Start", "Dual-Zone Climate Control", "Performance Tires", "Cross Traffic Alert", "Parking Sensors"],
    rentalPricePerDay: 810,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/convertible/bmw-ix3.jpg",
    description: "Discover berlin in style with the 2020 BMW iX3. With 514 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 1620,
  },
  {
    id: "car-berlin-audi-8",
    make: "Audi",
    model: "A1",
    year: 2023,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 437,
    colorOptions: ["Moonlight Silver", "Sapphire Blue", "Ocean Teal", "Pearl White"],
    features: ["Convertible Roof", "Wireless Charging", "Tow Package", "Running Boards", "Satellite Radio", "Massage Seats"],
    rentalPricePerDay: 497,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/sedan/audi-a1.jpg",
    description: "Turn heads in berlin with the sophisticated 2023 Audi A1. This exceptional sedan offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 994,
  },
  {
    id: "car-berlin-lotus-9",
    make: "Lotus",
    model: "Exige",
    year: 2021,
    type: "Convertible",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 538,
    colorOptions: ["Forest Green", "Amethyst Purple"],
    features: ["LED Headlights", "Launch Control", "Power Tailgate", "Cross Traffic Alert", "Driver Attention Monitoring", "Android Auto", "Ambient Lighting"],
    rentalPricePerDay: 636,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/convertible/lotus-exige.jpg",
    description: "Experience the luxury and power of the 2021 Lotus Exige. This stunning convertible offers an unforgettable driving experience in berlin.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2544,
  },
  {
    id: "car-berlin-toyota-10",
    make: "Toyota",
    model: "Tacoma",
    year: 2023,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 576,
    colorOptions: ["Alpine White", "Lava Orange", "Ice Blue"],
    features: ["Tri-Zone Climate Control", "Performance Tires", "Bluetooth", "Automatic Emergency Braking", "Parking Sensors"],
    rentalPricePerDay: 1125,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/sports-car/toyota-tacoma.jpg",
    description: "Elevate your berlin experience with the prestigious 2023 Toyota Tacoma. This high-performance sports car delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2250,
  },
  {
    id: "car-berlin-jaguar-11",
    make: "Jaguar",
    model: "F-PACE SVR",
    year: 2022,
    type: "Convertible",
    seats: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 358,
    colorOptions: ["Nardo Gray", "Forest Green", "Glacier White"],
    features: ["Ambient Lighting", "Convertible Roof", "Cross Traffic Alert", "Heads-Up Display", "360-Degree Camera", "Dual-Zone Climate Control", "Power Tailgate", "Lane Keep Assist", "Massage Seats"],
    rentalPricePerDay: 819,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/convertible/jaguar-f-pace-svr.jpg",
    description: "Discover berlin in style with the 2022 Jaguar F-PACE SVR. With 358 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 1638,
  },
  {
    id: "car-berlin-porsche-12",
    make: "Porsche",
    model: "Panamera Turbo",
    year: 2021,
    type: "Sports Car",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 546,
    colorOptions: ["Nardo Gray", "Copper", "Matte Gray", "Ivory"],
    features: ["Wireless Charging", "Voice Control", "Apple CarPlay", "All-Wheel Drive", "Tri-Zone Climate Control"],
    rentalPricePerDay: 1454,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-panamera-turbo.jpg",
    description: "Experience the luxury and power of the 2021 Porsche Panamera Turbo. This stunning sports car offers an unforgettable driving experience in berlin.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 5816,
  },
  {
    id: "car-berlin-lotus-13",
    make: "Lotus",
    model: "Lotus Elise Cup 250",
    year: 2021,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 536,
    colorOptions: ["Burgundy", "Ivory", "Ruby Red", "Forest Green", "Sapphire Blue"],
    features: ["Roof Rack", "Android Auto", "Leather Seats", "Apple CarPlay", "Sunroof"],
    rentalPricePerDay: 1066,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/sports-car/lotus-lotus-elise-cup-250.jpg",
    description: "Discover berlin in style with the 2021 Lotus Lotus Elise Cup 250. With 536 horsepower and premium features, this sports car is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2132,
  },
  {
    id: "car-berlin-tesla-14",
    make: "Tesla",
    model: "Model 3",
    year: 2023,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 450,
    colorOptions: ["Sapphire Blue", "Cement Gray", "Bronze", "Rose Gold"],
    features: ["Third-Row Seating", "Adaptive Cruise Control", "Roof Rack", "All-Wheel Drive", "Heated Seats", "Sport Suspension", "Bluetooth", "Power Tailgate"],
    rentalPricePerDay: 469,
    currency: "EUR",
    available: true,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/electric/tesla-model-3.jpg",
    description: "Elevate your berlin experience with the prestigious 2023 Tesla Model 3. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1407,
  },
  {
    id: "car-berlin-lincoln-15",
    make: "Lincoln",
    model: "Town Car",
    year: 2022,
    type: "Limousine",
    seats: 6,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 366,
    colorOptions: ["Cement Gray", "Champagne", "Gunmetal Gray"],
    features: ["Heated Seats", "360-Degree Camera", "Running Boards", "Parking Sensors", "Four-Wheel Drive", "Convertible Roof", "Blind Spot Monitoring", "Rear Entertainment System", "Launch Control", "Tow Package"],
    rentalPricePerDay: 748,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/limousine/lincoln-town-car.jpg",
    description: "Elevate your berlin experience with the prestigious 2022 Lincoln Town Car. This high-performance limousine delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1496,
  },
  {
    id: "car-berlin-ford-16",
    make: "Ford",
    model: "Crown Victoria",
    year: 2022,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 679,
    colorOptions: ["Cement Gray", "Matte Gray", "Ivory"],
    features: ["Digital Cockpit", "Launch Control", "Leather Seats", "Wireless Charging", "Adjustable Ride Height", "Cross Traffic Alert", "Night Vision", "Driver Attention Monitoring"],
    rentalPricePerDay: 1055,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/sports-car/ford-crown-victoria.jpg",
    description: "Discover berlin in style with the 2022 Ford Crown Victoria. With 679 horsepower and premium features, this sports car is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3165,
  }
];
