// Auto-generated luxury car rentals for bermuda
// Country: Bermuda, Region: Bermuda
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const bermudabermudabermudaCars: LuxuryRentalCar[] = [
  {
    id: "car-bermuda-mercedes-benz-1",
    make: "Mercedes-Benz",
    model: "CLS",
    year: 2021,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 411,
    colorOptions: ["Ivory", "Cement Gray", "Emerald Green"],
    features: ["Sunroof", "Heated Seats", "Fog Lights", "Cross Traffic Alert", "Parking Sensors", "Wi-Fi Hotspot"],
    rentalPricePerDay: 671,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/hybrid/mercedes-benz-cls.jpg",
    description: "Elevate your bermuda experience with the prestigious 2021 Mercedes-Benz CLS. This high-performance hybrid delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1342,
  },
  {
    id: "car-bermuda-rivian-2",
    make: "Rivian",
    model: "Rivian R1S Explore",
    year: 2020,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 407,
    colorOptions: ["Ivory", "Forest Green"],
    features: ["360-Degree Camera", "Bluetooth", "Convertible Roof", "Parking Sensors", "Touchscreen Display", "Ventilated Seats"],
    rentalPricePerDay: 588,
    currency: "BMD",
    available: false,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/suv/rivian-rivian-r1s-explore.jpg",
    description: "The 2020 Rivian Rivian R1S Explore combines elegance with performance. Enjoy premium features like 360-Degree Camera and Bluetooth while exploring bermuda in this remarkable suv.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1764,
  },
  {
    id: "car-bermuda-ford-3",
    make: "Ford",
    model: "Bronco",
    year: 2019,
    type: "Electric",
    seats: 3,
    transmission: "Manual",
    fuelType: "Electric",
    horsepower: 584,
    colorOptions: ["Copper", "Ruby Red", "Champagne", "Amethyst Purple"],
    features: ["Adjustable Ride Height", "Dual-Zone Climate Control", "Adaptive Cruise Control", "Performance Tires", "Panoramic Roof", "Heads-Up Display", "Fog Lights"],
    rentalPricePerDay: 507,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/electric/ford-bronco.jpg",
    description: "The 2019 Ford Bronco combines elegance with performance. Enjoy premium features like Adjustable Ride Height and Dual-Zone Climate Control while exploring bermuda in this remarkable electric.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2028,
  },
  {
    id: "car-bermuda-aston-martin-4",
    make: "Aston Martin",
    model: "Vantage",
    year: 2019,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 443,
    colorOptions: ["Emerald Green", "Sunset Orange", "Ruby Red", "Ivory"],
    features: ["Convertible Roof", "Wi-Fi Hotspot", "Electric Adjustable Seats", "Tow Package", "Cross Traffic Alert", "Sunroof", "Wireless Charging", "Voice Control"],
    rentalPricePerDay: 600,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/coupe/aston-martin-vantage.jpg",
    description: "Turn heads in bermuda with the sophisticated 2019 Aston Martin Vantage. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1200,
  },
  {
    id: "car-bermuda-aston-martin-5",
    make: "Aston Martin",
    model: "DBX707",
    year: 2023,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 491,
    colorOptions: ["Midnight Blue", "Carbon Black", "Graphite", "Rose Gold", "Pearl White"],
    features: ["Roof Rack", "Fog Lights", "Remote Start", "Convertible Roof", "Digital Cockpit", "Backup Camera"],
    rentalPricePerDay: 751,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/coupe/aston-martin-dbx707.jpg",
    description: "Elevate your bermuda experience with the prestigious 2023 Aston Martin DBX707. This high-performance coupe delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2253,
  },
  {
    id: "car-bermuda-lexus-6",
    make: "Lexus",
    model: "LS 500",
    year: 2020,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 424,
    colorOptions: ["Bronze", "Sunset Orange", "Forest Green"],
    features: ["Fog Lights", "Rear Entertainment System", "Wireless Charging", "360-Degree Camera", "Parking Sensors"],
    rentalPricePerDay: 492,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/coupe/lexus-ls-500.jpg",
    description: "Experience the luxury and power of the 2020 Lexus LS 500. This stunning coupe offers an unforgettable driving experience in bermuda.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 984,
  },
  {
    id: "car-bermuda-aston-martin-7",
    make: "Aston Martin",
    model: "DB11",
    year: 2021,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 533,
    colorOptions: ["Burgundy", "Midnight Blue", "Carbon Black"],
    features: ["Remote Start", "Tri-Zone Climate Control", "Panoramic Roof", "All-Wheel Drive", "Premium Sound System"],
    rentalPricePerDay: 857,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/hybrid/aston-martin-db11.jpg",
    description: "Discover bermuda in style with the 2021 Aston Martin DB11. With 533 horsepower and premium features, this hybrid is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1714,
  },
  {
    id: "car-bermuda-nissan-8",
    make: "Nissan",
    model: "Premium",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 574,
    colorOptions: ["Glacier White", "Alpine White", "Carbon Black", "Graphite", "Copper"],
    features: ["Power Tailgate", "Electric Adjustable Seats", "Dual-Zone Climate Control", "Push-Button Start", "Driver Attention Monitoring", "Remote Start", "Voice Control"],
    rentalPricePerDay: 1144,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/nissan-premium.jpg",
    description: "Turn heads in bermuda with the sophisticated 2019 Nissan Premium. This exceptional sports car offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4576,
  },
  {
    id: "car-bermuda-lincoln-9",
    make: "Lincoln",
    model: "MKT Town Car",
    year: 2021,
    type: "Sedan",
    seats: 5,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 420,
    colorOptions: ["Nardo Gray", "Carbon Black", "Moonlight Silver", "Lava Orange", "Ocean Teal"],
    features: ["Performance Tires", "Premium Sound System", "Bluetooth", "Push-Button Start", "Wi-Fi Hotspot", "Voice Control", "LED Headlights", "Backup Camera", "360-Degree Camera", "Tri-Zone Climate Control"],
    rentalPricePerDay: 310,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/sedan/lincoln-mkt-town-car.jpg",
    description: "Experience the luxury and power of the 2021 Lincoln MKT Town Car. This stunning sedan offers an unforgettable driving experience in bermuda.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 620,
  },
  {
    id: "car-bermuda-tesla-10",
    make: "Tesla",
    model: "Roadster",
    year: 2021,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 562,
    colorOptions: ["Matte Black", "Steel Blue", "Moonlight Silver"],
    features: ["Sport Suspension", "Launch Control", "Satellite Radio", "Premium Sound System", "Android Auto", "Cross Traffic Alert"],
    rentalPricePerDay: 561,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/electric/tesla-roadster.jpg",
    description: "Discover bermuda in style with the 2021 Tesla Roadster. With 562 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1122,
  },
  {
    id: "car-bermuda-lincoln-11",
    make: "Lincoln",
    model: "Navigator",
    year: 2020,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 392,
    colorOptions: ["Diamond Black", "Ice Blue"],
    features: ["LED Headlights", "Heated Seats", "Third-Row Seating", "Roof Rack", "Push-Button Start", "Rear Entertainment System", "Adaptive Cruise Control", "Ventilated Seats"],
    rentalPricePerDay: 493,
    currency: "BMD",
    available: false,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/sedan/lincoln-navigator.jpg",
    description: "Experience the luxury and power of the 2020 Lincoln Navigator. This stunning sedan offers an unforgettable driving experience in bermuda.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 986,
  },
  {
    id: "car-bermuda-chevrolet-12",
    make: "Chevrolet",
    model: "Corvette",
    year: 2020,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 459,
    colorOptions: ["Bronze", "Matte Black", "Champagne", "Steel Blue", "Emerald Green"],
    features: ["Touchscreen Display", "Heads-Up Display", "Dual-Zone Climate Control", "Android Auto", "Blind Spot Monitoring", "Keyless Entry", "Digital Cockpit"],
    rentalPricePerDay: 467,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/coupe/chevrolet-corvette.jpg",
    description: "Discover bermuda in style with the 2020 Chevrolet Corvette. With 459 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1868,
  },
  {
    id: "car-bermuda-bmw-13",
    make: "BMW",
    model: "iX6",
    year: 2023,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 552,
    colorOptions: ["Lava Orange", "Ruby Red", "Alpine White"],
    features: ["Sunroof", "Android Auto", "Dual-Zone Climate Control", "Remote Start"],
    rentalPricePerDay: 745,
    currency: "BMD",
    available: false,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/electric/bmw-ix6.jpg",
    description: "Elevate your bermuda experience with the prestigious 2023 BMW iX6. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1490,
  },
  {
    id: "car-bermuda-lexus-14",
    make: "Lexus",
    model: "RC 350",
    year: 2020,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 554,
    colorOptions: ["Cement Gray", "Emerald Green", "Ruby Red", "Pearl White"],
    features: ["Sport Suspension", "Launch Control", "Digital Cockpit", "Remote Start", "Tri-Zone Climate Control", "Wi-Fi Hotspot", "Roof Rack", "360-Degree Camera", "Blind Spot Monitoring"],
    rentalPricePerDay: 486,
    currency: "BMD",
    available: false,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/coupe/lexus-rc-350.jpg",
    description: "Experience the luxury and power of the 2020 Lexus RC 350. This stunning coupe offers an unforgettable driving experience in bermuda.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 972,
  },
  {
    id: "car-bermuda-audi-15",
    make: "Audi",
    model: "A3",
    year: 2023,
    type: "Limousine",
    seats: 6,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 454,
    colorOptions: ["Metallic Silver", "Lava Orange", "Nardo Gray"],
    features: ["Wireless Charging", "Apple CarPlay", "Tri-Zone Climate Control", "All-Wheel Drive", "Leather Seats", "Ventilated Seats", "Heated Seats"],
    rentalPricePerDay: 1055,
    currency: "BMD",
    available: false,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/limousine/audi-a3.jpg",
    description: "Elevate your bermuda experience with the prestigious 2023 Audi A3. This high-performance limousine delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2110,
  },
  {
    id: "car-bermuda-maserati-16",
    make: "Maserati",
    model: "Ghibli Trofeo",
    year: 2019,
    type: "Convertible",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 427,
    colorOptions: ["Burgundy", "Ocean Teal", "Emerald Green", "Graphite"],
    features: ["Premium Sound System", "Cross Traffic Alert", "Tri-Zone Climate Control", "Tow Package", "Massage Seats", "Wi-Fi Hotspot", "Blind Spot Monitoring", "Wireless Charging", "Satellite Radio", "Night Vision"],
    rentalPricePerDay: 1089,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/convertible/maserati-ghibli-trofeo.jpg",
    description: "Experience the luxury and power of the 2019 Maserati Ghibli Trofeo. This stunning convertible offers an unforgettable driving experience in bermuda.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2178,
  },
  {
    id: "car-bermuda-ferrari-17",
    make: "Ferrari",
    model: "F8 Tributo",
    year: 2021,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 528,
    colorOptions: ["Rose Gold", "Midnight Blue", "Matte Black", "Champagne"],
    features: ["Heads-Up Display", "Android Auto", "GPS Navigation", "Touchscreen Display", "Convertible Roof"],
    rentalPricePerDay: 1067,
    currency: "BMD",
    available: false,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/hybrid/ferrari-f8-tributo.jpg",
    description: "Elevate your bermuda experience with the prestigious 2021 Ferrari F8 Tributo. This high-performance hybrid delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4268,
  },
  {
    id: "car-bermuda-tesla-18",
    make: "Tesla",
    model: "Cybertruck Single Motor",
    year: 2021,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 492,
    colorOptions: ["Nardo Gray", "Alpine White"],
    features: ["Third-Row Seating", "Adjustable Ride Height", "Lane Keep Assist", "Satellite Radio", "Running Boards", "Massage Seats", "Backup Camera", "Four-Wheel Drive"],
    rentalPricePerDay: 604,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/electric/tesla-cybertruck-single-motor.jpg",
    description: "Elevate your bermuda experience with the prestigious 2021 Tesla Cybertruck Single Motor. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1812,
  },
  {
    id: "car-bermuda-cadillac-19",
    make: "Cadillac",
    model: "CT5 Sport",
    year: 2020,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 337,
    colorOptions: ["Emerald Green", "Sapphire Blue", "Amethyst Purple"],
    features: ["Roof Rack", "Tow Package", "Parking Sensors", "Backup Camera", "Apple CarPlay", "Bluetooth", "Leather Seats", "Android Auto"],
    rentalPricePerDay: 572,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/suv/cadillac-ct5-sport.jpg",
    description: "Turn heads in bermuda with the sophisticated 2020 Cadillac CT5 Sport. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2288,
  },
  {
    id: "car-bermuda-porsche-20",
    make: "Porsche",
    model: "Cayenne Turbo",
    year: 2020,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 514,
    colorOptions: ["Forest Green", "Burgundy", "Carbon Black"],
    features: ["Ventilated Seats", "Leather Seats", "Panoramic Roof", "Convertible Roof", "Automatic Emergency Braking", "Running Boards", "Adjustable Ride Height"],
    rentalPricePerDay: 1024,
    currency: "BMD",
    available: false,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/convertible/porsche-cayenne-turbo.jpg",
    description: "Elevate your bermuda experience with the prestigious 2020 Porsche Cayenne Turbo. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2048,
  },
  {
    id: "car-bermuda-rolls-royce-21",
    make: "Rolls-Royce",
    model: "Ghost Black Badge",
    year: 2021,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 330,
    colorOptions: ["Moonlight Silver", "Ice Blue", "Gunmetal Gray", "Alpine White"],
    features: ["All-Wheel Drive", "Satellite Radio", "Launch Control", "Convertible Roof", "Lane Keep Assist", "Sunroof", "GPS Navigation", "Tri-Zone Climate Control", "Android Auto"],
    rentalPricePerDay: 890,
    currency: "BMD",
    available: true,
    pickUpCity: "Bermuda",
    pickUpCountry: "Bermuda",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/suv/rolls-royce-ghost-black-badge.jpg",
    description: "Experience the luxury and power of the 2021 Rolls-Royce Ghost Black Badge. This stunning suv offers an unforgettable driving experience in bermuda.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2670,
  }
];
