import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const dubaiunitedArabEmiratesmiddleEastCars: LuxuryRentalCar[] = [
  {
    id: "car-dubai-mercedes-benz-1",
    make: "Mercedes-Benz",
    model: "E-Class",
    year: 2020,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 491,
    colorOptions: ["Alpine White", "Burgundy", "Champagne", "Ruby Red"],
    features: [
      "Convertible Roof",
      "Sunroof",
      "Remote Start",
      "Leather Seats",
      "Blind Spot Monitoring",
    ],
    rentalPricePerDay: 805,
    currency: "AED",
    available: true,
    pickUpCity: "dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Main Terminal",
    imageUrl:
      "https://paragon-trails-car-images.com/convertible/mercedes-benz-e-class.jpg",
    description:
      "Experience the luxury and power of the 2020 Mercedes-Benz E-Class. This stunning convertible offers an unforgettable driving experience in dubai.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3220,
  },
  {
    id: "car-dubai-aston-martin-2",
    make: "Aston Martin",
    model: "DB11",
    year: 2021,
    type: "Convertible",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 538,
    colorOptions: [
      "Pearl White",
      "Champagne",
      "Moonlight Silver",
      "Black",
      "Ivory",
    ],
    features: [
      "Heads-Up Display",
      "Electric Adjustable Seats",
      "Bluetooth",
      "Remote Start",
      "Sunroof",
      "Parking Sensors",
      "Premium Sound System",
      "Heated Seats",
    ],
    rentalPricePerDay: 951,
    currency: "AED",
    available: true,
    pickUpCity: "dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Convention Center",
    imageUrl:
      "https://paragon-trails-car-images.com/convertible/aston-martin-db11.jpg",
    description:
      "Turn heads in dubai with the sophisticated 2021 Aston Martin DB11. This exceptional convertible offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3804,
  },
  {
    id: "car-dubai-porsche-3",
    make: "Porsche",
    model: "Panamera",
    year: 2022,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 355,
    colorOptions: ["Gray", "Metallic Silver", "Burgundy"],
    features: [
      "Backup Camera",
      "Bluetooth",
      "Heads-Up Display",
      "GPS Navigation",
      "Electric Adjustable Seats",
    ],
    rentalPricePerDay: 767,
    currency: "AED",
    available: false,
    pickUpCity: "dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://paragon-trails-car-images.com/suv/porsche-panamera.jpg",
    description:
      "Turn heads in dubai with the sophisticated 2022 Porsche Panamera. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 3068,
  },
];
