// Auto-generated luxury car rentals for lima
// Country: Peru, Region: Peru
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const limaperuperuCars: LuxuryRentalCar[] = [
  {
    id: "car-lima-aston-martin-1",
    make: "Aston Martin",
    model: "DBX707 Ultimate",
    year: 2020,
    type: "Sports Car",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 620,
    colorOptions: ["Sunset Orange", "Sapphire Blue", "Matte Gray", "Cement Gray", "Pearl White"],
    features: ["Running Boards", "GPS Navigation", "Voice Control", "Fog Lights", "Tow Package", "Panoramic Roof"],
    rentalPricePerDay: 5730,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/sports-car/aston-martin-dbx707-ultimate.jpg",
    description: "Experience the luxury and power of the 2020 Aston Martin DBX707 Ultimate. This stunning sports car offers an unforgettable driving experience in lima.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 22920,
  },
  {
    id: "car-lima-toyota-2",
    make: "Toyota",
    model: "Sienna",
    year: 2021,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 544,
    colorOptions: ["Bronze", "Glacier White", "Matte Gray"],
    features: ["Premium Sound System", "Tow Package", "Adjustable Ride Height", "Electric Adjustable Seats", "360-Degree Camera", "Ambient Lighting", "Power Tailgate"],
    rentalPricePerDay: 2099,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/hybrid/toyota-sienna.jpg",
    description: "Discover lima in style with the 2021 Toyota Sienna. With 544 horsepower and premium features, this hybrid is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 8396,
  },
  {
    id: "car-lima-lucid-3",
    make: "Lucid",
    model: "Air Grand Touring",
    year: 2022,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 582,
    colorOptions: ["Copper", "Matte Black", "Amethyst Purple", "Metallic Silver", "Nardo Gray"],
    features: ["Adjustable Ride Height", "Rear Entertainment System", "Heads-Up Display", "Leather Seats", "Premium Sound System", "Wireless Charging"],
    rentalPricePerDay: 2067,
    currency: "PEN",
    available: false,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/electric/lucid-air-grand-touring.jpg",
    description: "The 2022 Lucid Air Grand Touring combines elegance with performance. Enjoy premium features like Adjustable Ride Height and Rear Entertainment System while exploring lima in this remarkable electric.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 6201,
  },
  {
    id: "car-lima-porsche-4",
    make: "Porsche",
    model: "Macan S",
    year: 2019,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 626,
    colorOptions: ["Pearl White", "Cement Gray", "Steel Blue", "Matte Black", "Ocean Teal"],
    features: ["Touchscreen Display", "Satellite Radio", "Dual-Zone Climate Control", "Night Vision", "Voice Control"],
    rentalPricePerDay: 3035,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/electric/porsche-macan-s.jpg",
    description: "Experience the luxury and power of the 2019 Porsche Macan S. This stunning electric offers an unforgettable driving experience in lima.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 9105,
  },
  {
    id: "car-lima-ford-5",
    make: "Ford",
    model: "Ranger",
    year: 2022,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 614,
    colorOptions: ["Carbon Black", "Nardo Gray"],
    features: ["Adaptive Cruise Control", "Lane Keep Assist", "Android Auto", "Blind Spot Monitoring", "Wi-Fi Hotspot", "Ventilated Seats"],
    rentalPricePerDay: 1932,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/electric/ford-ranger.jpg",
    description: "Discover lima in style with the 2022 Ford Ranger. With 614 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 5796,
  },
  {
    id: "car-lima-bentley-6",
    make: "Bentley",
    model: "Mulsanne",
    year: 2019,
    type: "Limousine",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 495,
    colorOptions: ["Metallic Silver", "Diamond Black", "Burgundy", "Ivory"],
    features: ["Voice Control", "Lane Keep Assist", "Heads-Up Display", "Running Boards", "Adjustable Ride Height", "Fog Lights", "Driver Attention Monitoring"],
    rentalPricePerDay: 5609,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/limousine/bentley-mulsanne.jpg",
    description: "Experience the luxury and power of the 2019 Bentley Mulsanne. This stunning limousine offers an unforgettable driving experience in lima.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 11218,
  },
  {
    id: "car-lima-ford-7",
    make: "Ford",
    model: "F-250 Super Duty",
    year: 2022,
    type: "Electric",
    seats: 3,
    transmission: "Manual",
    fuelType: "Electric",
    horsepower: 502,
    colorOptions: ["Moonlight Silver", "Alpine White", "Carbon Black"],
    features: ["Touchscreen Display", "Driver Attention Monitoring", "360-Degree Camera", "Leather Seats", "Android Auto", "Parking Sensors", "Wi-Fi Hotspot"],
    rentalPricePerDay: 1974,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/electric/ford-f-250-super-duty.jpg",
    description: "The 2022 Ford F-250 Super Duty combines elegance with performance. Enjoy premium features like Touchscreen Display and Driver Attention Monitoring while exploring lima in this remarkable electric.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 5922,
  },
  {
    id: "car-lima-jaguar-8",
    make: "Jaguar",
    model: "F-TYPE P300",
    year: 2020,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 581,
    colorOptions: ["Pearl White", "Emerald Green", "Ivory", "Sunset Orange", "Matte Black"],
    features: ["Tow Package", "Wi-Fi Hotspot", "360-Degree Camera", "Running Boards", "Parking Sensors"],
    rentalPricePerDay: 2377,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/electric/jaguar-f-type-p300.jpg",
    description: "The 2020 Jaguar F-TYPE P300 combines elegance with performance. Enjoy premium features like Tow Package and Wi-Fi Hotspot while exploring lima in this remarkable electric.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 9508,
  },
  {
    id: "car-lima-lotus-9",
    make: "Lotus",
    model: "Emira",
    year: 2019,
    type: "Sports Car",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 684,
    colorOptions: ["Ivory", "Burgundy", "Cement Gray"],
    features: ["Touchscreen Display", "Four-Wheel Drive", "All-Wheel Drive", "Bluetooth", "Power Tailgate", "Lane Keep Assist", "Voice Control", "Leather Seats"],
    rentalPricePerDay: 3881,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/sports-car/lotus-emira.jpg",
    description: "Experience the luxury and power of the 2019 Lotus Emira. This stunning sports car offers an unforgettable driving experience in lima.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 11643,
  },
  {
    id: "car-lima-porsche-10",
    make: "Porsche",
    model: "718 Boxster",
    year: 2019,
    type: "Coupe",
    seats: 4,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 414,
    colorOptions: ["Rose Gold", "Sunset Orange", "Copper"],
    features: ["Four-Wheel Drive", "Digital Cockpit", "Satellite Radio", "Panoramic Roof", "Leather Seats", "Adaptive Cruise Control", "Power Tailgate", "Parking Sensors"],
    rentalPricePerDay: 2363,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/coupe/porsche-718-boxster.jpg",
    description: "The 2019 Porsche 718 Boxster combines elegance with performance. Enjoy premium features like Four-Wheel Drive and Digital Cockpit while exploring lima in this remarkable coupe.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 4726,
  },
  {
    id: "car-lima-ferrari-11",
    make: "Ferrari",
    model: "GTC4Lusso",
    year: 2020,
    type: "Convertible",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 387,
    colorOptions: ["Canyon Red", "Cement Gray", "Burgundy", "Ice Blue", "British Racing Green"],
    features: ["Ventilated Seats", "Third-Row Seating", "Power Tailgate", "Heads-Up Display", "Premium Sound System", "Keyless Entry", "Leather Seats", "Automatic Emergency Braking"],
    rentalPricePerDay: 4190,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/convertible/ferrari-gtc4lusso.jpg",
    description: "The 2020 Ferrari GTC4Lusso combines elegance with performance. Enjoy premium features like Ventilated Seats and Third-Row Seating while exploring lima in this remarkable convertible.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 8380,
  },
  {
    id: "car-lima-lexus-12",
    make: "Lexus",
    model: "RC 350",
    year: 2023,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 599,
    colorOptions: ["British Racing Green", "Copper", "Rose Gold", "Steel Blue", "Forest Green"],
    features: ["Touchscreen Display", "Performance Tires", "Digital Cockpit", "Wireless Charging", "Tri-Zone Climate Control"],
    rentalPricePerDay: 1897,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/coupe/lexus-rc-350.jpg",
    description: "The 2023 Lexus RC 350 combines elegance with performance. Enjoy premium features like Touchscreen Display and Performance Tires while exploring lima in this remarkable coupe.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 3794,
  },
  {
    id: "car-lima-jaguar-13",
    make: "Jaguar",
    model: "F-TYPE P575",
    year: 2019,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 474,
    colorOptions: ["Nardo Gray", "Ivory", "Carbon Black"],
    features: ["Android Auto", "Keyless Entry", "Ambient Lighting", "Lane Keep Assist", "Roof Rack", "Performance Tires", "Parking Sensors"],
    rentalPricePerDay: 2385,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/electric/jaguar-f-type-p575.jpg",
    description: "Turn heads in lima with the sophisticated 2019 Jaguar F-TYPE P575. This exceptional electric offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 4770,
  },
  {
    id: "car-lima-ford-14",
    make: "Ford",
    model: "Maverick",
    year: 2020,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 477,
    colorOptions: ["Champagne", "Sunset Orange", "Nardo Gray", "Sapphire Blue", "Copper"],
    features: ["Roof Rack", "Parking Sensors", "Dual-Zone Climate Control", "Ambient Lighting", "360-Degree Camera", "Adaptive Cruise Control", "Power Tailgate", "Ventilated Seats"],
    rentalPricePerDay: 2096,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/electric/ford-maverick.jpg",
    description: "Experience the luxury and power of the 2020 Ford Maverick. This stunning electric offers an unforgettable driving experience in lima.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 4192,
  }
];
