// Auto-generated luxury car rentals for melbourne
// Country: Australia, Region: Australia
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const melbourneaustraliaaustraliaCars: LuxuryRentalCar[] = [
  {
    id: "car-melbourne-aston-martin-1",
    make: "Aston Martin",
    model: "Rapide S Ultimate",
    year: 2022,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 512,
    colorOptions: ["Carbon Black", "Steel Blue", "Ruby Red"],
    features: ["Third-Row Seating", "Dual-Zone Climate Control", "Voice Control", "Premium Sound System", "Cross Traffic Alert"],
    rentalPricePerDay: 932,
    currency: "AUD",
    available: true,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/coupe/aston-martin-rapide-s-ultimate.jpg",
    description: "Experience the luxury and power of the 2022 Aston Martin Rapide S Ultimate. This stunning coupe offers an unforgettable driving experience in melbourne.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3728,
  },
  {
    id: "car-melbourne-pagani-2",
    make: "Pagani",
    model: "Zonda C12",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 587,
    colorOptions: ["Canyon Red", "Amethyst Purple", "Ruby Red", "Pearl White"],
    features: ["Panoramic Roof", "Ambient Lighting", "Fog Lights", "Electric Adjustable Seats", "Massage Seats", "GPS Navigation", "Four-Wheel Drive", "Ventilated Seats"],
    rentalPricePerDay: 1568,
    currency: "AUD",
    available: true,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/sports-car/pagani-zonda-c12.jpg",
    description: "Experience the luxury and power of the 2019 Pagani Zonda C12. This stunning sports car offers an unforgettable driving experience in melbourne.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 6272,
  },
  {
    id: "car-melbourne-chevrolet-3",
    make: "Chevrolet",
    model: "Silverado 2500HD",
    year: 2020,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 486,
    colorOptions: ["Ocean Teal", "Pearl White", "Diamond Black"],
    features: ["Adaptive Cruise Control", "Four-Wheel Drive", "Cross Traffic Alert", "Convertible Roof", "LED Headlights", "Third-Row Seating"],
    rentalPricePerDay: 646,
    currency: "AUD",
    available: true,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/coupe/chevrolet-silverado-2500hd.jpg",
    description: "Experience the luxury and power of the 2020 Chevrolet Silverado 2500HD. This stunning coupe offers an unforgettable driving experience in melbourne.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1938,
  },
  {
    id: "car-melbourne-ferrari-4",
    make: "Ferrari",
    model: "812 GTS",
    year: 2019,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 503,
    colorOptions: ["Burgundy", "Ice Blue", "Nardo Gray"],
    features: ["Heads-Up Display", "All-Wheel Drive", "Performance Tires", "Automatic Emergency Braking", "Wi-Fi Hotspot", "Power Tailgate", "Electric Adjustable Seats", "Backup Camera", "Apple CarPlay", "Adjustable Ride Height"],
    rentalPricePerDay: 1503,
    currency: "AUD",
    available: true,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/hybrid/ferrari-812-gts.jpg",
    description: "Discover melbourne in style with the 2019 Ferrari 812 GTS. With 503 horsepower and premium features, this hybrid is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3006,
  },
  {
    id: "car-melbourne-ferrari-5",
    make: "Ferrari",
    model: "488 Spider",
    year: 2022,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 588,
    colorOptions: ["Amethyst Purple", "Steel Blue", "Graphite", "Forest Green", "Alpine White"],
    features: ["Push-Button Start", "Driver Attention Monitoring", "Adaptive Cruise Control", "Four-Wheel Drive", "Heads-Up Display", "Backup Camera", "Roof Rack", "Performance Tires", "Wi-Fi Hotspot"],
    rentalPricePerDay: 1120,
    currency: "AUD",
    available: true,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/coupe/ferrari-488-spider.jpg",
    description: "Discover melbourne in style with the 2022 Ferrari 488 Spider. With 588 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3360,
  },
  {
    id: "car-melbourne-maserati-6",
    make: "Maserati",
    model: "MC20 Cielo",
    year: 2022,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 357,
    colorOptions: ["Nardo Gray", "Metallic Silver", "Burgundy", "Ruby Red", "Sapphire Blue"],
    features: ["Ambient Lighting", "Electric Adjustable Seats", "Roof Rack", "Adaptive Cruise Control", "Fog Lights"],
    rentalPricePerDay: 1473,
    currency: "AUD",
    available: true,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/convertible/maserati-mc20-cielo.jpg",
    description: "Discover melbourne in style with the 2022 Maserati MC20 Cielo. With 357 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4419,
  },
  {
    id: "car-melbourne-lincoln-7",
    make: "Lincoln",
    model: "MKX",
    year: 2019,
    type: "Limousine",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 345,
    colorOptions: ["Ivory", "Emerald Green", "Champagne"],
    features: ["Rear Entertainment System", "LED Headlights", "Electric Adjustable Seats", "Power Tailgate", "Fog Lights", "Sport Suspension"],
    rentalPricePerDay: 1375,
    currency: "AUD",
    available: true,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/limousine/lincoln-mkx.jpg",
    description: "Elevate your melbourne experience with the prestigious 2019 Lincoln MKX. This high-performance limousine delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 4125,
  },
  {
    id: "car-melbourne-bentley-8",
    make: "Bentley",
    model: "Bentley Azure Coupe",
    year: 2020,
    type: "Limousine",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 514,
    colorOptions: ["Carbon Black", "Burgundy", "Steel Blue"],
    features: ["Massage Seats", "Rear Entertainment System", "Power Tailgate", "Cross Traffic Alert", "Heads-Up Display", "Remote Start", "GPS Navigation", "Automatic Emergency Braking"],
    rentalPricePerDay: 2353,
    currency: "AUD",
    available: false,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/limousine/bentley-bentley-azure-coupe.jpg",
    description: "Discover melbourne in style with the 2020 Bentley Bentley Azure Coupe. With 514 horsepower and premium features, this limousine is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 9412,
  },
  {
    id: "car-melbourne-tesla-9",
    make: "Tesla",
    model: "Cybertruck",
    year: 2021,
    type: "Sedan",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 334,
    colorOptions: ["Diamond Black", "Metallic Silver", "Alpine White"],
    features: ["Automatic Emergency Braking", "Apple CarPlay", "Power Tailgate", "Fog Lights", "Android Auto", "Ventilated Seats", "Adaptive Cruise Control", "Heated Seats"],
    rentalPricePerDay: 519,
    currency: "AUD",
    available: true,
    pickUpCity: "Melbourne",
    pickUpCountry: "Australia",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/sedan/tesla-cybertruck.jpg",
    description: "Elevate your melbourne experience with the prestigious 2021 Tesla Cybertruck. This high-performance sedan delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1038,
  }
];
