// Auto-generated luxury car rentals for miami
// Country: United States, Region: Caribbean
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const miamiunitedStatescaribbeanCars: LuxuryRentalCar[] = [
  {
    id: "car-miami-hyundai-1",
    make: "Hyundai",
    model: "Kona Hybrid",
    year: 2022,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 602,
    colorOptions: ["Amethyst Purple", "British Racing Green", "Canyon Red", "Metallic Silver"],
    features: ["Premium Sound System", "Performance Tires", "Wi-Fi Hotspot", "Driver Attention Monitoring"],
    rentalPricePerDay: 636,
    currency: "USD",
    available: true,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/electric/hyundai-kona-hybrid.jpg",
    description: "Elevate your miami experience with the prestigious 2022 Hyundai Kona Hybrid. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2544,
  },
  {
    id: "car-miami-rolls-royce-2",
    make: "Rolls-Royce",
    model: "Phantom Series II",
    year: 2019,
    type: "Limousine",
    seats: 6,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 351,
    colorOptions: ["Amethyst Purple", "Matte Gray", "Ocean Teal", "Steel Blue"],
    features: ["Android Auto", "Electric Adjustable Seats", "Voice Control", "Heads-Up Display", "Bluetooth", "Push-Button Start", "Automatic Emergency Braking"],
    rentalPricePerDay: 1532,
    currency: "USD",
    available: false,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-phantom-series-ii.jpg",
    description: "Turn heads in miami with the sophisticated 2019 Rolls-Royce Phantom Series II. This exceptional limousine offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3064,
  },
  {
    id: "car-miami-chrysler-3",
    make: "Chrysler",
    model: "300",
    year: 2019,
    type: "Sedan",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 363,
    colorOptions: ["Rose Gold", "Champagne", "Ocean Teal"],
    features: ["Convertible Roof", "Four-Wheel Drive", "Roof Rack", "Cross Traffic Alert", "Leather Seats", "Adjustable Ride Height", "Fog Lights"],
    rentalPricePerDay: 319,
    currency: "USD",
    available: true,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/sedan/chrysler-300.jpg",
    description: "Discover miami in style with the 2019 Chrysler 300. With 363 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 638,
  },
  {
    id: "car-miami-lamborghini-4",
    make: "Lamborghini",
    model: "Huracán EVO",
    year: 2021,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 591,
    colorOptions: ["Gunmetal Gray", "Midnight Blue", "Ruby Red", "Emerald Green"],
    features: ["Push-Button Start", "Sunroof", "Performance Tires", "Parking Sensors", "Wi-Fi Hotspot", "Cross Traffic Alert", "Wireless Charging", "Sport Suspension"],
    rentalPricePerDay: 795,
    currency: "USD",
    available: true,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/coupe/lamborghini-huracán-evo.jpg",
    description: "Experience the luxury and power of the 2021 Lamborghini Huracán EVO. This stunning coupe offers an unforgettable driving experience in miami.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2385,
  },
  {
    id: "car-miami-lamborghini-5",
    make: "Lamborghini",
    model: "Aventador SVJ",
    year: 2023,
    type: "Coupe",
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 486,
    colorOptions: ["Moonlight Silver", "Gunmetal Gray", "Graphite"],
    features: ["Push-Button Start", "Satellite Radio", "Automatic Emergency Braking", "Launch Control", "Lane Keep Assist"],
    rentalPricePerDay: 763,
    currency: "USD",
    available: true,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/coupe/lamborghini-aventador-svj.jpg",
    description: "Turn heads in miami with the sophisticated 2023 Lamborghini Aventador SVJ. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2289,
  },
  {
    id: "car-miami-mercedes-benz-6",
    make: "Mercedes-Benz",
    model: "GLB",
    year: 2023,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 486,
    colorOptions: ["Burgundy", "Alpine White", "Cement Gray", "Steel Blue"],
    features: ["All-Wheel Drive", "Night Vision", "Tow Package", "Sunroof", "Lane Keep Assist", "Wi-Fi Hotspot"],
    rentalPricePerDay: 610,
    currency: "USD",
    available: false,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/electric/mercedes-benz-glb.jpg",
    description: "Experience the luxury and power of the 2023 Mercedes-Benz GLB. This stunning electric offers an unforgettable driving experience in miami.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2440,
  },
  {
    id: "car-miami-porsche-7",
    make: "Porsche",
    model: "Taycan 4S",
    year: 2021,
    type: "Sports Car",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 659,
    colorOptions: ["Ocean Teal", "Nardo Gray", "Alpine White", "Forest Green"],
    features: ["Tri-Zone Climate Control", "Cross Traffic Alert", "Android Auto", "Parking Sensors", "Rear Entertainment System", "Convertible Roof", "Electric Adjustable Seats", "Touchscreen Display"],
    rentalPricePerDay: 1514,
    currency: "USD",
    available: false,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-taycan-4s.jpg",
    description: "Experience the luxury and power of the 2021 Porsche Taycan 4S. This stunning sports car offers an unforgettable driving experience in miami.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 6056,
  },
  {
    id: "car-miami-mercedes-benz-8",
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2023,
    type: "Sedan",
    seats: 5,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 304,
    colorOptions: ["Ruby Red", "Nardo Gray", "Cement Gray", "Glacier White", "Canyon Red"],
    features: ["Four-Wheel Drive", "Satellite Radio", "Voice Control", "Performance Tires", "Parking Sensors", "Remote Start", "Convertible Roof"],
    rentalPricePerDay: 533,
    currency: "USD",
    available: true,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/sedan/mercedes-benz-c-class.jpg",
    description: "The 2023 Mercedes-Benz C-Class combines elegance with performance. Enjoy premium features like Four-Wheel Drive and Satellite Radio while exploring miami in this remarkable sedan.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1066,
  },
  {
    id: "car-miami-infiniti-9",
    make: "Infiniti",
    model: "QX30S",
    year: 2019,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 408,
    colorOptions: ["Cement Gray", "Rose Gold", "Champagne"],
    features: ["Remote Start", "LED Headlights", "Panoramic Roof", "360-Degree Camera", "Driver Attention Monitoring", "Rear Entertainment System"],
    rentalPricePerDay: 433,
    currency: "USD",
    available: false,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/coupe/infiniti-qx30s.jpg",
    description: "Discover miami in style with the 2019 Infiniti QX30S. With 408 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 866,
  },
  {
    id: "car-miami-jaguar-10",
    make: "Jaguar",
    model: "XF P300",
    year: 2021,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 400,
    colorOptions: ["Moonlight Silver", "Sapphire Blue", "Midnight Blue"],
    features: ["Rear Entertainment System", "Performance Tires", "Tow Package", "All-Wheel Drive", "Premium Sound System", "Launch Control", "Electric Adjustable Seats", "Adaptive Cruise Control", "Running Boards", "Voice Control"],
    rentalPricePerDay: 978,
    currency: "USD",
    available: true,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/limousine/jaguar-xf-p300.jpg",
    description: "The 2021 Jaguar XF P300 combines elegance with performance. Enjoy premium features like Rear Entertainment System and Performance Tires while exploring miami in this remarkable limousine.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2934,
  },
  {
    id: "car-miami-aston-martin-11",
    make: "Aston Martin",
    model: "Rapide S",
    year: 2019,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 580,
    colorOptions: ["Metallic Silver", "Lava Orange", "Amethyst Purple", "Sapphire Blue"],
    features: ["Sport Suspension", "Parking Sensors", "Push-Button Start", "Running Boards", "Keyless Entry", "Launch Control", "Digital Cockpit"],
    rentalPricePerDay: 619,
    currency: "USD",
    available: true,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/coupe/aston-martin-rapide-s.jpg",
    description: "The 2019 Aston Martin Rapide S combines elegance with performance. Enjoy premium features like Sport Suspension and Parking Sensors while exploring miami in this remarkable coupe.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1238,
  },
  {
    id: "car-miami-rolls-royce-12",
    make: "Rolls-Royce",
    model: "Wraith Convertible",
    year: 2019,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 448,
    colorOptions: ["Amethyst Purple", "British Racing Green", "Ruby Red", "Ocean Teal"],
    features: ["Massage Seats", "Digital Cockpit", "Apple CarPlay", "Running Boards", "Adaptive Cruise Control", "Panoramic Roof"],
    rentalPricePerDay: 1256,
    currency: "USD",
    available: true,
    pickUpCity: "Miami",
    pickUpCountry: "United States",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/convertible/rolls-royce-wraith-convertible.jpg",
    description: "Discover miami in style with the 2019 Rolls-Royce Wraith Convertible. With 448 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3768,
  }
];
