// Auto-generated luxury car rentals for montreal
// Country: Canada, Region: East Coast Canada
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const montrealcanadaeastCoastCanadaCars: LuxuryRentalCar[] = [
  {
    id: "car-montreal-audi-1",
    make: "Audi",
    model: "RS 3 Sportback",
    year: 2022,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 612,
    colorOptions: ["Pearl White", "Lava Orange", "Glacier White"],
    features: ["Wi-Fi Hotspot", "Touchscreen Display", "Push-Button Start", "Ventilated Seats", "Keyless Entry", "GPS Navigation", "Adjustable Ride Height", "Launch Control"],
    rentalPricePerDay: 985,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/electric/audi-rs-3-sportback.jpg",
    description: "Discover montreal in style with the 2022 Audi RS 3 Sportback. With 612 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3940,
  },
  {
    id: "car-montreal-audi-2",
    make: "Audi",
    model: "Q8 e-tron",
    year: 2023,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 379,
    colorOptions: ["Lava Orange", "British Racing Green", "Champagne", "Ruby Red"],
    features: ["Apple CarPlay", "Tow Package", "Massage Seats", "Launch Control", "Cross Traffic Alert"],
    rentalPricePerDay: 656,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/sedan/audi-q8-e-tron.jpg",
    description: "Discover montreal in style with the 2023 Audi Q8 e-tron. With 379 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1968,
  },
  {
    id: "car-montreal-audi-3",
    make: "Audi",
    model: "RS Q4 Sportback",
    year: 2019,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 415,
    colorOptions: ["Emerald Green", "Burgundy", "Nardo Gray", "Lava Orange", "Copper"],
    features: ["Sport Suspension", "Night Vision", "Wi-Fi Hotspot", "360-Degree Camera", "Android Auto", "Blind Spot Monitoring"],
    rentalPricePerDay: 580,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/sedan/audi-rs-q4-sportback.jpg",
    description: "Discover montreal in style with the 2019 Audi RS Q4 Sportback. With 415 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1160,
  },
  {
    id: "car-montreal-tesla-4",
    make: "Tesla",
    model: "Model Y",
    year: 2019,
    type: "Electric",
    seats: 4,
    transmission: "Manual",
    fuelType: "Electric",
    horsepower: 496,
    colorOptions: ["Lava Orange", "Copper", "Champagne"],
    features: ["LED Headlights", "Adjustable Ride Height", "Ambient Lighting", "Driver Attention Monitoring", "Running Boards", "Rear Entertainment System", "Power Tailgate", "Lane Keep Assist", "Keyless Entry"],
    rentalPricePerDay: 879,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/electric/tesla-model-y.jpg",
    description: "Elevate your montreal experience with the prestigious 2019 Tesla Model Y. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1758,
  },
  {
    id: "car-montreal-rivian-5",
    make: "Rivian",
    model: "Rivian R1T Launch Edition",
    year: 2019,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 323,
    colorOptions: ["Ivory", "Gunmetal Gray", "Steel Blue"],
    features: ["Adaptive Cruise Control", "Four-Wheel Drive", "Wireless Charging", "Panoramic Roof", "Heads-Up Display"],
    rentalPricePerDay: 777,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/suv/rivian-rivian-r1t-launch-edition.jpg",
    description: "The 2019 Rivian Rivian R1T Launch Edition combines elegance with performance. Enjoy premium features like Adaptive Cruise Control and Four-Wheel Drive while exploring montreal in this remarkable suv.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3108,
  },
  {
    id: "car-montreal-maserati-6",
    make: "Maserati",
    model: "Levante",
    year: 2020,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 447,
    colorOptions: ["Pearl White", "Forest Green", "Diamond Black", "Matte Black"],
    features: ["Third-Row Seating", "Running Boards", "Heated Seats", "All-Wheel Drive", "Blind Spot Monitoring"],
    rentalPricePerDay: 930,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/coupe/maserati-levante.jpg",
    description: "Turn heads in montreal with the sophisticated 2020 Maserati Levante. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2790,
  },
  {
    id: "car-montreal-maserati-7",
    make: "Maserati",
    model: "Levante Trofeo",
    year: 2019,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 516,
    colorOptions: ["Matte Black", "Diamond Black", "Lava Orange", "Burgundy", "Ruby Red"],
    features: ["Rear Entertainment System", "GPS Navigation", "All-Wheel Drive", "Digital Cockpit", "Ambient Lighting", "Launch Control", "Push-Button Start", "Adjustable Ride Height", "Apple CarPlay", "360-Degree Camera"],
    rentalPricePerDay: 1271,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/convertible/maserati-levante-trofeo.jpg",
    description: "Discover montreal in style with the 2019 Maserati Levante Trofeo. With 516 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3813,
  },
  {
    id: "car-montreal-lamborghini-8",
    make: "Lamborghini",
    model: "Huracán EVO Spyder",
    year: 2023,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 423,
    colorOptions: ["Champagne", "Cement Gray", "Burgundy", "Gunmetal Gray"],
    features: ["Four-Wheel Drive", "Tri-Zone Climate Control", "Touchscreen Display", "Power Tailgate", "Ambient Lighting", "Dual-Zone Climate Control", "Roof Rack", "Rear Entertainment System", "LED Headlights", "Lane Keep Assist"],
    rentalPricePerDay: 1111,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/coupe/lamborghini-huracán-evo-spyder.jpg",
    description: "Turn heads in montreal with the sophisticated 2023 Lamborghini Huracán EVO Spyder. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4444,
  },
  {
    id: "car-montreal-corvette-9",
    make: "Corvette",
    model: "C8 Stingray",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 616,
    colorOptions: ["Alpine White", "Gunmetal Gray", "Cement Gray"],
    features: ["LED Headlights", "Four-Wheel Drive", "Touchscreen Display", "Power Tailgate", "Keyless Entry", "Tri-Zone Climate Control", "Adaptive Cruise Control", "Lane Keep Assist"],
    rentalPricePerDay: 1453,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/corvette-c8-stingray.jpg",
    description: "Experience the luxury and power of the 2019 Corvette C8 Stingray. This stunning sports car offers an unforgettable driving experience in montreal.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2906,
  },
  {
    id: "car-montreal-rivian-10",
    make: "Rivian",
    model: "R1S",
    year: 2023,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 484,
    colorOptions: ["Diamond Black", "Ruby Red", "British Racing Green", "Ocean Teal"],
    features: ["Sunroof", "Running Boards", "Android Auto", "Sport Suspension"],
    rentalPricePerDay: 713,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/electric/rivian-r1s.jpg",
    description: "Turn heads in montreal with the sophisticated 2023 Rivian R1S. This exceptional electric offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2139,
  },
  {
    id: "car-montreal-audi-11",
    make: "Audi",
    model: "RS 4",
    year: 2020,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 313,
    colorOptions: ["Copper", "Champagne", "Matte Black"],
    features: ["Launch Control", "Third-Row Seating", "Electric Adjustable Seats", "Remote Start", "Wireless Charging"],
    rentalPricePerDay: 528,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/sedan/audi-rs-4.jpg",
    description: "Discover montreal in style with the 2020 Audi RS 4. With 313 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1584,
  },
  {
    id: "car-montreal-chevrolet-12",
    make: "Chevrolet",
    model: "Equinox",
    year: 2020,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 441,
    colorOptions: ["Alpine White", "Ice Blue", "Ivory"],
    features: ["LED Headlights", "Remote Start", "Heads-Up Display", "Tri-Zone Climate Control", "Keyless Entry", "Automatic Emergency Braking", "Wi-Fi Hotspot", "Parking Sensors", "Voice Control"],
    rentalPricePerDay: 1005,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/convertible/chevrolet-equinox.jpg",
    description: "Elevate your montreal experience with the prestigious 2020 Chevrolet Equinox. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3015,
  },
  {
    id: "car-montreal-range-rover-13",
    make: "Range Rover",
    model: "Range Rover Evoque P300e",
    year: 2022,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 468,
    colorOptions: ["Matte Gray", "Nardo Gray", "Matte Black", "British Racing Green", "Sapphire Blue"],
    features: ["Voice Control", "Android Auto", "Tri-Zone Climate Control", "GPS Navigation", "Driver Attention Monitoring", "Electric Adjustable Seats", "Fog Lights", "Backup Camera", "Roof Rack", "Cross Traffic Alert"],
    rentalPricePerDay: 731,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/suv/range-rover-range-rover-evoque-p300e.jpg",
    description: "Elevate your montreal experience with the prestigious 2022 Range Rover Range Rover Evoque P300e. This high-performance suv delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2193,
  },
  {
    id: "car-montreal-audi-14",
    make: "Audi",
    model: "Q7",
    year: 2019,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 360,
    colorOptions: ["Graphite", "Sapphire Blue", "Champagne", "Gunmetal Gray"],
    features: ["Lane Keep Assist", "Sport Suspension", "Launch Control", "Wi-Fi Hotspot", "Tow Package"],
    rentalPricePerDay: 986,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/convertible/audi-q7.jpg",
    description: "Elevate your montreal experience with the prestigious 2019 Audi Q7. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 1972,
  },
  {
    id: "car-montreal-genesis-15",
    make: "Genesis",
    model: "G60 Ultimate",
    year: 2019,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 475,
    colorOptions: ["Emerald Green", "Midnight Blue", "Ocean Teal", "Forest Green", "Ice Blue"],
    features: ["Power Tailgate", "Wireless Charging", "Push-Button Start", "Android Auto", "Heads-Up Display", "Heated Seats", "GPS Navigation", "Cross Traffic Alert"],
    rentalPricePerDay: 677,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/suv/genesis-g60-ultimate.jpg",
    description: "Discover montreal in style with the 2019 Genesis G60 Ultimate. With 475 horsepower and premium features, this suv is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1354,
  },
  {
    id: "car-montreal-audi-16",
    make: "Audi",
    model: "RS 7 Sportback",
    year: 2022,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 412,
    colorOptions: ["Canyon Red", "Diamond Black", "Moonlight Silver", "Ice Blue"],
    features: ["Voice Control", "Premium Sound System", "Satellite Radio", "Panoramic Roof", "Android Auto", "Fog Lights", "Ambient Lighting", "Driver Attention Monitoring", "Launch Control", "Performance Tires"],
    rentalPricePerDay: 788,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/coupe/audi-rs-7-sportback.jpg",
    description: "Turn heads in montreal with the sophisticated 2022 Audi RS 7 Sportback. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1576,
  },
  {
    id: "car-montreal-chevrolet-17",
    make: "Chevrolet",
    model: "Trailblazer",
    year: 2019,
    type: "Convertible",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 533,
    colorOptions: ["Graphite", "Ruby Red", "Ice Blue"],
    features: ["Panoramic Roof", "Cross Traffic Alert", "Launch Control", "Running Boards", "Power Tailgate", "Roof Rack", "Android Auto", "Premium Sound System"],
    rentalPricePerDay: 952,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/convertible/chevrolet-trailblazer.jpg",
    description: "Turn heads in montreal with the sophisticated 2019 Chevrolet Trailblazer. This exceptional convertible offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3808,
  },
  {
    id: "car-montreal-lamborghini-18",
    make: "Lamborghini",
    model: "Aventador SVJ",
    year: 2020,
    type: "Hybrid",
    seats: 4,
    transmission: "Manual",
    fuelType: "Hybrid",
    horsepower: 488,
    colorOptions: ["Glacier White", "Matte Black", "Champagne"],
    features: ["Tow Package", "Keyless Entry", "Parking Sensors", "Premium Sound System", "Performance Tires", "Satellite Radio"],
    rentalPricePerDay: 1242,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/hybrid/lamborghini-aventador-svj.jpg",
    description: "Turn heads in montreal with the sophisticated 2020 Lamborghini Aventador SVJ. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3726,
  },
  {
    id: "car-montreal-infiniti-19",
    make: "Infiniti",
    model: "QX50",
    year: 2019,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 513,
    colorOptions: ["Gunmetal Gray", "Copper", "Ivory", "Pearl White", "Sapphire Blue"],
    features: ["Night Vision", "Massage Seats", "Fog Lights", "Four-Wheel Drive", "Satellite Radio", "Wireless Charging"],
    rentalPricePerDay: 568,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/coupe/infiniti-qx50.jpg",
    description: "Experience the luxury and power of the 2019 Infiniti QX50. This stunning coupe offers an unforgettable driving experience in montreal.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1136,
  },
  {
    id: "car-montreal-lincoln-20",
    make: "Lincoln",
    model: "MKT Town Car",
    year: 2022,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 344,
    colorOptions: ["Sapphire Blue", "Ocean Teal", "Alpine White", "Matte Gray"],
    features: ["Satellite Radio", "Driver Attention Monitoring", "Night Vision", "360-Degree Camera", "Parking Sensors", "Adaptive Cruise Control"],
    rentalPricePerDay: 456,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/sedan/lincoln-mkt-town-car.jpg",
    description: "Turn heads in montreal with the sophisticated 2022 Lincoln MKT Town Car. This exceptional sedan offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1824,
  },
  {
    id: "car-montreal-mercedes-benz-21",
    make: "Mercedes-Benz",
    model: "G-Class",
    year: 2022,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 407,
    colorOptions: ["Rose Gold", "Bronze", "Amethyst Purple"],
    features: ["Blind Spot Monitoring", "Power Tailgate", "Wi-Fi Hotspot", "Digital Cockpit", "Bluetooth", "Automatic Emergency Braking", "Heads-Up Display", "Voice Control", "Running Boards", "Leather Seats"],
    rentalPricePerDay: 772,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/suv/mercedes-benz-g-class.jpg",
    description: "Discover montreal in style with the 2022 Mercedes-Benz G-Class. With 407 horsepower and premium features, this suv is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2316,
  },
  {
    id: "car-montreal-porsche-22",
    make: "Porsche",
    model: "Panamera Turbo",
    year: 2020,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 643,
    colorOptions: ["Forest Green", "Ruby Red", "Ivory"],
    features: ["Automatic Emergency Braking", "Touchscreen Display", "Dual-Zone Climate Control", "Rear Entertainment System", "Roof Rack", "Electric Adjustable Seats", "Lane Keep Assist"],
    rentalPricePerDay: 2185,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-panamera-turbo.jpg",
    description: "Discover montreal in style with the 2020 Porsche Panamera Turbo. With 643 horsepower and premium features, this sports car is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 8740,
  },
  {
    id: "car-montreal-tesla-23",
    make: "Tesla",
    model: "Model 3 Performance",
    year: 2023,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 350,
    colorOptions: ["Gunmetal Gray", "Nardo Gray", "Matte Gray", "Ruby Red", "Cement Gray"],
    features: ["Rear Entertainment System", "Third-Row Seating", "Parking Sensors", "Adaptive Cruise Control", "Premium Sound System", "Ventilated Seats", "Lane Keep Assist", "Push-Button Start"],
    rentalPricePerDay: 485,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/sedan/tesla-model-3-performance.jpg",
    description: "Turn heads in montreal with the sophisticated 2023 Tesla Model 3 Performance. This exceptional sedan offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1455,
  },
  {
    id: "car-montreal-rolls-royce-24",
    make: "Rolls-Royce",
    model: "Wraith Convertible",
    year: 2020,
    type: "Limousine",
    seats: 6,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 349,
    colorOptions: ["Glacier White", "Copper", "Ocean Teal", "Rose Gold", "Canyon Red"],
    features: ["Panoramic Roof", "Bluetooth", "Remote Start", "Automatic Emergency Braking", "Satellite Radio"],
    rentalPricePerDay: 1982,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-wraith-convertible.jpg",
    description: "The 2020 Rolls-Royce Wraith Convertible combines elegance with performance. Enjoy premium features like Panoramic Roof and Bluetooth while exploring montreal in this remarkable limousine.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 7928,
  },
  {
    id: "car-montreal-lexus-25",
    make: "Lexus",
    model: "LC 500h F Sport",
    year: 2019,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 422,
    colorOptions: ["Gunmetal Gray", "British Racing Green", "Metallic Silver"],
    features: ["Tow Package", "Leather Seats", "Bluetooth", "Driver Attention Monitoring", "Touchscreen Display"],
    rentalPricePerDay: 839,
    currency: "CAD",
    available: true,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/hybrid/lexus-lc-500h-f-sport.jpg",
    description: "Turn heads in montreal with the sophisticated 2019 Lexus LC 500h F Sport. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1678,
  },
  {
    id: "car-montreal-honda-26",
    make: "Honda",
    model: "HR-V",
    year: 2022,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 511,
    colorOptions: ["Metallic Silver", "Cement Gray", "Pearl White", "Alpine White", "Steel Blue"],
    features: ["Ambient Lighting", "GPS Navigation", "Panoramic Roof", "Push-Button Start", "Voice Control", "Bluetooth", "Blind Spot Monitoring", "Premium Sound System"],
    rentalPricePerDay: 867,
    currency: "CAD",
    available: false,
    pickUpCity: "Montreal",
    pickUpCountry: "Canada",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/hybrid/honda-hr-v.jpg",
    description: "Turn heads in montreal with the sophisticated 2022 Honda HR-V. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3468,
  }
];
