// Auto-generated luxury car rentals for nassau
// Country: Bahamas, Region: Bahamas
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const nassaubahamasbahamasCars: LuxuryRentalCar[] = [
  {
    id: "car-nassau-chrysler-1",
    make: "Chrysler",
    model: "Aspen Hybrid",
    year: 2020,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 389,
    colorOptions: ["Ivory", "Emerald Green", "Canyon Red", "Forest Green"],
    features: ["Sport Suspension", "360-Degree Camera", "Premium Sound System", "Convertible Roof", "Running Boards", "Electric Adjustable Seats", "Fog Lights", "Driver Attention Monitoring", "Lane Keep Assist"],
    rentalPricePerDay: 398,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/sedan/chrysler-aspen-hybrid.jpg",
    description: "Turn heads in nassau with the sophisticated 2020 Chrysler Aspen Hybrid. This exceptional sedan offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1592,
  },
  {
    id: "car-nassau-toyota-2",
    make: "Toyota",
    model: "Hilux",
    year: 2020,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 511,
    colorOptions: ["Midnight Blue", "Burgundy", "Bronze"],
    features: ["GPS Navigation", "Convertible Roof", "Panoramic Roof", "Voice Control", "Leather Seats"],
    rentalPricePerDay: 1163,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/sports-car/toyota-hilux.jpg",
    description: "Elevate your nassau experience with the prestigious 2020 Toyota Hilux. This high-performance sports car delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 4652,
  },
  {
    id: "car-nassau-tesla-3",
    make: "Tesla",
    model: "Model X",
    year: 2019,
    type: "Sedan",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 334,
    colorOptions: ["British Racing Green", "Rose Gold", "Sapphire Blue"],
    features: ["Satellite Radio", "Touchscreen Display", "Voice Control", "Blind Spot Monitoring", "Four-Wheel Drive", "Tow Package", "Lane Keep Assist", "Apple CarPlay", "Bluetooth", "Sport Suspension"],
    rentalPricePerDay: 492,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/sedan/tesla-model-x.jpg",
    description: "The 2019 Tesla Model X combines elegance with performance. Enjoy premium features like Satellite Radio and Touchscreen Display while exploring nassau in this remarkable sedan.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1968,
  },
  {
    id: "car-nassau-volkswagen-4",
    make: "Volkswagen",
    model: "ID.6",
    year: 2021,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 596,
    colorOptions: ["Gunmetal Gray", "Champagne", "Carbon Black", "Pearl White", "Sunset Orange"],
    features: ["Tow Package", "Driver Attention Monitoring", "Running Boards", "Night Vision", "Blind Spot Monitoring", "Heated Seats", "Roof Rack", "Tri-Zone Climate Control"],
    rentalPricePerDay: 535,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/electric/volkswagen-id.6.jpg",
    description: "Elevate your nassau experience with the prestigious 2021 Volkswagen ID.6. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1605,
  },
  {
    id: "car-nassau-bmw-5",
    make: "BMW",
    model: "M8 Gran Coupe",
    year: 2023,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 492,
    colorOptions: ["Copper", "Ice Blue", "Carbon Black", "Glacier White", "Canyon Red"],
    features: ["Parking Sensors", "Convertible Roof", "Blind Spot Monitoring", "Wireless Charging", "Tri-Zone Climate Control", "Premium Sound System"],
    rentalPricePerDay: 840,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/convertible/bmw-m8-gran-coupe.jpg",
    description: "Discover nassau in style with the 2023 BMW M8 Gran Coupe. With 492 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2520,
  },
  {
    id: "car-nassau-porsche-6",
    make: "Porsche",
    model: "718 Boxster",
    year: 2021,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 449,
    colorOptions: ["Diamond Black", "Matte Black", "Sunset Orange"],
    features: ["Tow Package", "Keyless Entry", "Sport Suspension", "Leather Seats", "GPS Navigation", "Roof Rack", "Parking Sensors", "Satellite Radio"],
    rentalPricePerDay: 962,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/convertible/porsche-718-boxster.jpg",
    description: "The 2021 Porsche 718 Boxster combines elegance with performance. Enjoy premium features like Tow Package and Keyless Entry while exploring nassau in this remarkable convertible.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3848,
  },
  {
    id: "car-nassau-lincoln-7",
    make: "Lincoln",
    model: "Aviator",
    year: 2022,
    type: "Limousine",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 401,
    colorOptions: ["Rose Gold", "Glacier White", "Metallic Silver", "Matte Black", "Carbon Black"],
    features: ["Tri-Zone Climate Control", "Backup Camera", "Dual-Zone Climate Control", "Wireless Charging", "Bluetooth", "Touchscreen Display", "Android Auto", "Premium Sound System"],
    rentalPricePerDay: 840,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/limousine/lincoln-aviator.jpg",
    description: "Experience the luxury and power of the 2022 Lincoln Aviator. This stunning limousine offers an unforgettable driving experience in nassau.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 3360,
  },
  {
    id: "car-nassau-jaguar-8",
    make: "Jaguar",
    model: "F-PACE R-Dynamic",
    year: 2019,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 476,
    colorOptions: ["Alpine White", "Bronze", "Lava Orange"],
    features: ["GPS Navigation", "Third-Row Seating", "Apple CarPlay", "Remote Start", "Touchscreen Display", "Sport Suspension", "Adaptive Cruise Control"],
    rentalPricePerDay: 732,
    currency: "BSD",
    available: false,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/convertible/jaguar-f-pace-r-dynamic.jpg",
    description: "The 2019 Jaguar F-PACE R-Dynamic combines elegance with performance. Enjoy premium features like GPS Navigation and Third-Row Seating while exploring nassau in this remarkable convertible.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2928,
  },
  {
    id: "car-nassau-lamborghini-9",
    make: "Lamborghini",
    model: "Aventador",
    year: 2019,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 488,
    colorOptions: ["Cement Gray", "Lava Orange", "Bronze", "Ruby Red", "Steel Blue"],
    features: ["Fog Lights", "Driver Attention Monitoring", "Automatic Emergency Braking", "Wireless Charging", "Launch Control", "Heated Seats", "Electric Adjustable Seats", "Apple CarPlay", "Cross Traffic Alert"],
    rentalPricePerDay: 1051,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/hybrid/lamborghini-aventador.jpg",
    description: "Experience the luxury and power of the 2019 Lamborghini Aventador. This stunning hybrid offers an unforgettable driving experience in nassau.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2102,
  },
  {
    id: "car-nassau-audi-10",
    make: "Audi",
    model: "Q5 Sportback",
    year: 2019,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 420,
    colorOptions: ["Gunmetal Gray", "Sunset Orange", "Steel Blue", "Nardo Gray", "Lava Orange"],
    features: ["Cross Traffic Alert", "Fog Lights", "Convertible Roof", "Satellite Radio", "Night Vision", "Heads-Up Display", "Ventilated Seats", "Power Tailgate", "Sunroof"],
    rentalPricePerDay: 408,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/sedan/audi-q5-sportback.jpg",
    description: "Discover nassau in style with the 2019 Audi Q5 Sportback. With 420 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 816,
  },
  {
    id: "car-nassau-lamborghini-11",
    make: "Lamborghini",
    model: "Sián",
    year: 2019,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 454,
    colorOptions: ["Forest Green", "Midnight Blue", "Emerald Green", "Sapphire Blue"],
    features: ["Adaptive Cruise Control", "Adjustable Ride Height", "Dual-Zone Climate Control", "Wireless Charging", "Push-Button Start", "Premium Sound System", "Roof Rack", "Four-Wheel Drive", "Tow Package"],
    rentalPricePerDay: 795,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/coupe/lamborghini-sián.jpg",
    description: "Experience the luxury and power of the 2019 Lamborghini Sián. This stunning coupe offers an unforgettable driving experience in nassau.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3180,
  },
  {
    id: "car-nassau-porsche-12",
    make: "Porsche",
    model: "Macan S",
    year: 2020,
    type: "Sports Car",
    seats: 2,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 554,
    colorOptions: ["Ice Blue", "Rose Gold", "Metallic Silver", "Matte Gray"],
    features: ["Leather Seats", "Third-Row Seating", "Running Boards", "Keyless Entry", "Performance Tires", "Fog Lights"],
    rentalPricePerDay: 1623,
    currency: "BSD",
    available: false,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-macan-s.jpg",
    description: "Elevate your nassau experience with the prestigious 2020 Porsche Macan S. This high-performance sports car delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3246,
  },
  {
    id: "car-nassau-infiniti-13",
    make: "Infiniti",
    model: "QX70",
    year: 2020,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 360,
    colorOptions: ["Steel Blue", "Copper", "Ocean Teal", "Metallic Silver", "Nardo Gray"],
    features: ["Backup Camera", "Third-Row Seating", "Ventilated Seats", "Cross Traffic Alert", "Voice Control", "Night Vision"],
    rentalPricePerDay: 535,
    currency: "BSD",
    available: false,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/suv/infiniti-qx70.jpg",
    description: "Elevate your nassau experience with the prestigious 2020 Infiniti QX70. This high-performance suv delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1605,
  },
  {
    id: "car-nassau-nissan-14",
    make: "Nissan",
    model: "Premium",
    year: 2022,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 677,
    colorOptions: ["Steel Blue", "Matte Black", "Gunmetal Gray"],
    features: ["Bluetooth", "Leather Seats", "Heated Seats", "Sunroof", "Wireless Charging", "Running Boards", "Apple CarPlay", "Roof Rack", "Sport Suspension"],
    rentalPricePerDay: 1127,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/sports-car/nissan-premium.jpg",
    description: "Discover nassau in style with the 2022 Nissan Premium. With 677 horsepower and premium features, this sports car is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 4508,
  },
  {
    id: "car-nassau-chrysler-15",
    make: "Chrysler",
    model: "Cordoba",
    year: 2023,
    type: "Limousine",
    seats: 6,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 336,
    colorOptions: ["Ice Blue", "Lava Orange", "Matte Black"],
    features: ["Night Vision", "Adjustable Ride Height", "Leather Seats", "Tri-Zone Climate Control", "Power Tailgate", "Ventilated Seats", "Electric Adjustable Seats", "Launch Control", "Dual-Zone Climate Control"],
    rentalPricePerDay: 853,
    currency: "BSD",
    available: false,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/limousine/chrysler-cordoba.jpg",
    description: "Elevate your nassau experience with the prestigious 2023 Chrysler Cordoba. This high-performance limousine delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2559,
  },
  {
    id: "car-nassau-bmw-16",
    make: "BMW",
    model: "iX3",
    year: 2021,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 465,
    colorOptions: ["Canyon Red", "Nardo Gray", "Pearl White"],
    features: ["Four-Wheel Drive", "Heated Seats", "Performance Tires", "Ambient Lighting", "Leather Seats", "Fog Lights", "Touchscreen Display"],
    rentalPricePerDay: 672,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/coupe/bmw-ix3.jpg",
    description: "The 2021 BMW iX3 combines elegance with performance. Enjoy premium features like Four-Wheel Drive and Heated Seats while exploring nassau in this remarkable coupe.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1344,
  },
  {
    id: "car-nassau-audi-17",
    make: "Audi",
    model: "RS 1",
    year: 2022,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 410,
    colorOptions: ["Glacier White", "Canyon Red", "Gunmetal Gray", "Sapphire Blue", "Cement Gray"],
    features: ["Night Vision", "All-Wheel Drive", "360-Degree Camera", "Wi-Fi Hotspot", "Performance Tires", "Roof Rack"],
    rentalPricePerDay: 673,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/coupe/audi-rs-1.jpg",
    description: "Elevate your nassau experience with the prestigious 2022 Audi RS 1. This high-performance coupe delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2692,
  },
  {
    id: "car-nassau-chrysler-18",
    make: "Chrysler",
    model: "Imperial",
    year: 2021,
    type: "Limousine",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 443,
    colorOptions: ["Emerald Green", "Alpine White", "Nardo Gray", "Amethyst Purple"],
    features: ["LED Headlights", "Ventilated Seats", "Massage Seats", "Wireless Charging", "Satellite Radio", "Sport Suspension", "Tow Package", "Backup Camera", "Roof Rack"],
    rentalPricePerDay: 911,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/limousine/chrysler-imperial.jpg",
    description: "Discover nassau in style with the 2021 Chrysler Imperial. With 443 horsepower and premium features, this limousine is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2733,
  },
  {
    id: "car-nassau-porsche-19",
    make: "Porsche",
    model: "Taycan",
    year: 2020,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 492,
    colorOptions: ["Midnight Blue", "Champagne", "Pearl White", "Burgundy"],
    features: ["Third-Row Seating", "Tow Package", "360-Degree Camera", "Satellite Radio", "Heated Seats", "Voice Control", "Parking Sensors"],
    rentalPricePerDay: 736,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/coupe/porsche-taycan.jpg",
    description: "Discover nassau in style with the 2020 Porsche Taycan. With 492 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2208,
  },
  {
    id: "car-nassau-koenigsegg-20",
    make: "Koenigsegg",
    model: "Agera R",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 632,
    colorOptions: ["Copper", "Moonlight Silver", "Cement Gray", "Glacier White", "British Racing Green"],
    features: ["Ambient Lighting", "Running Boards", "All-Wheel Drive", "Fog Lights"],
    rentalPricePerDay: 1037,
    currency: "BSD",
    available: false,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/koenigsegg-agera-r.jpg",
    description: "Experience the luxury and power of the 2019 Koenigsegg Agera R. This stunning sports car offers an unforgettable driving experience in nassau.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2074,
  },
  {
    id: "car-nassau-lexus-21",
    make: "Lexus",
    model: "UX 200",
    year: 2023,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 476,
    colorOptions: ["Champagne", "Ocean Teal", "Forest Green", "Lava Orange"],
    features: ["Parking Sensors", "Automatic Emergency Braking", "Ambient Lighting", "Bluetooth"],
    rentalPricePerDay: 1064,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/limousine/lexus-ux-200.jpg",
    description: "Turn heads in nassau with the sophisticated 2023 Lexus UX 200. This exceptional limousine offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3192,
  },
  {
    id: "car-nassau-audi-22",
    make: "Audi",
    model: "S8",
    year: 2022,
    type: "Sedan",
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 282,
    colorOptions: ["Sapphire Blue", "Diamond Black", "Bronze", "Pearl White", "British Racing Green"],
    features: ["Electric Adjustable Seats", "Adaptive Cruise Control", "Blind Spot Monitoring", "Voice Control", "Driver Attention Monitoring", "Leather Seats", "Launch Control"],
    rentalPricePerDay: 412,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/sedan/audi-s8.jpg",
    description: "The 2022 Audi S8 combines elegance with performance. Enjoy premium features like Electric Adjustable Seats and Adaptive Cruise Control while exploring nassau in this remarkable sedan.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1648,
  },
  {
    id: "car-nassau-mclaren-23",
    make: "McLaren",
    model: "McLaren 650S Spider",
    year: 2020,
    type: "Sports Car",
    seats: 2,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 519,
    colorOptions: ["Cement Gray", "Moonlight Silver", "Rose Gold"],
    features: ["Convertible Roof", "GPS Navigation", "All-Wheel Drive", "Push-Button Start", "Adaptive Cruise Control", "Satellite Radio"],
    rentalPricePerDay: 1931,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/sports-car/mclaren-mclaren-650s-spider.jpg",
    description: "Elevate your nassau experience with the prestigious 2020 McLaren McLaren 650S Spider. This high-performance sports car delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 7724,
  },
  {
    id: "car-nassau-polestar-24",
    make: "Polestar",
    model: "Polestar 5 Long Range",
    year: 2023,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 495,
    colorOptions: ["Emerald Green", "Copper", "Metallic Silver", "Midnight Blue", "Canyon Red"],
    features: ["Ambient Lighting", "Tri-Zone Climate Control", "Parking Sensors", "Rear Entertainment System", "Leather Seats", "Heated Seats", "Tow Package", "Satellite Radio"],
    rentalPricePerDay: 606,
    currency: "BSD",
    available: false,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/electric/polestar-polestar-5-long-range.jpg",
    description: "Discover nassau in style with the 2023 Polestar Polestar 5 Long Range. With 495 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1818,
  },
  {
    id: "car-nassau-aston-martin-25",
    make: "Aston Martin",
    model: "DBX707 Ultimate",
    year: 2020,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 366,
    colorOptions: ["Nardo Gray", "Copper", "Lava Orange", "Alpine White"],
    features: ["Lane Keep Assist", "Running Boards", "Touchscreen Display", "Cross Traffic Alert", "Heads-Up Display"],
    rentalPricePerDay: 993,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/convertible/aston-martin-dbx707-ultimate.jpg",
    description: "Experience the luxury and power of the 2020 Aston Martin DBX707 Ultimate. This stunning convertible offers an unforgettable driving experience in nassau.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3972,
  },
  {
    id: "car-nassau-porsche-26",
    make: "Porsche",
    model: "911 Targa",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 517,
    colorOptions: ["Sunset Orange", "Steel Blue", "British Racing Green", "Glacier White"],
    features: ["360-Degree Camera", "Digital Cockpit", "Third-Row Seating", "Dual-Zone Climate Control", "Wireless Charging"],
    rentalPricePerDay: 1634,
    currency: "BSD",
    available: true,
    pickUpCity: "Nassau",
    pickUpCountry: "Bahamas",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-911-targa.jpg",
    description: "The 2019 Porsche 911 Targa combines elegance with performance. Enjoy premium features like 360-Degree Camera and Digital Cockpit while exploring nassau in this remarkable sports car.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 6536,
  }
];
