// Auto-generated luxury car rentals for new-york-city
// Country: United States, Region: New York
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const newYorkCityunitedStatesnewYorkCars: LuxuryRentalCar[] = [
  {
    id: "car-new-york-city-ford-1",
    make: "Ford",
    model: "Explorer Hybrid",
    year: 2023,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 642,
    colorOptions: ["Canyon Red", "Emerald Green"],
    features: ["Automatic Emergency Braking", "Tri-Zone Climate Control", "Android Auto", "Leather Seats", "Heated Seats", "Convertible Roof", "Bluetooth"],
    rentalPricePerDay: 531,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/electric/ford-explorer-hybrid.jpg",
    description: "Experience the luxury and power of the 2023 Ford Explorer Hybrid. This stunning electric offers an unforgettable driving experience in new-york-city.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1062,
  },
  {
    id: "car-new-york-city-lincoln-2",
    make: "Lincoln",
    model: "Town Car",
    year: 2020,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 418,
    colorOptions: ["Ivory", "Ice Blue", "Metallic Silver", "Graphite"],
    features: ["Massage Seats", "Bluetooth", "Performance Tires", "Ventilated Seats", "Rear Entertainment System", "Digital Cockpit"],
    rentalPricePerDay: 330,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/sedan/lincoln-town-car.jpg",
    description: "Discover new-york-city in style with the 2020 Lincoln Town Car. With 418 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1320,
  },
  {
    id: "car-new-york-city-hyundai-3",
    make: "Hyundai",
    model: "Elantra Hybrid",
    year: 2023,
    type: "Hybrid",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 403,
    colorOptions: ["Matte Gray", "Alpine White", "Sunset Orange", "Gunmetal Gray"],
    features: ["Keyless Entry", "Cross Traffic Alert", "Leather Seats", "Remote Start", "Running Boards"],
    rentalPricePerDay: 598,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/hybrid/hyundai-elantra-hybrid.jpg",
    description: "The 2023 Hyundai Elantra Hybrid combines elegance with performance. Enjoy premium features like Keyless Entry and Cross Traffic Alert while exploring new-york-city in this remarkable hybrid.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2392,
  },
  {
    id: "car-new-york-city-volkswagen-4",
    make: "Volkswagen",
    model: "Scirocco",
    year: 2022,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 620,
    colorOptions: ["Alpine White", "Champagne", "Matte Gray", "Steel Blue"],
    features: ["Parking Sensors", "Cross Traffic Alert", "Power Tailgate", "Adjustable Ride Height", "Panoramic Roof"],
    rentalPricePerDay: 582,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/electric/volkswagen-scirocco.jpg",
    description: "Discover new-york-city in style with the 2022 Volkswagen Scirocco. With 620 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1164,
  },
  {
    id: "car-new-york-city-lucid-5",
    make: "Lucid",
    model: "Air Touring",
    year: 2019,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 362,
    colorOptions: ["Amethyst Purple", "Lava Orange", "Ice Blue", "Matte Black"],
    features: ["Touchscreen Display", "Rear Entertainment System", "Sunroof", "All-Wheel Drive", "Ambient Lighting", "Ventilated Seats", "Sport Suspension", "360-Degree Camera", "Parking Sensors"],
    rentalPricePerDay: 446,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/sedan/lucid-air-touring.jpg",
    description: "The 2019 Lucid Air Touring combines elegance with performance. Enjoy premium features like Touchscreen Display and Rear Entertainment System while exploring new-york-city in this remarkable sedan.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1784,
  },
  {
    id: "car-new-york-city-cadillac-6",
    make: "Cadillac",
    model: "Escalade Luxury",
    year: 2020,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 443,
    colorOptions: ["Copper", "Glacier White", "Canyon Red", "Amethyst Purple"],
    features: ["Leather Seats", "Push-Button Start", "Wi-Fi Hotspot", "Night Vision", "Automatic Emergency Braking", "Touchscreen Display"],
    rentalPricePerDay: 451,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/suv/cadillac-escalade-luxury.jpg",
    description: "Elevate your new-york-city experience with the prestigious 2020 Cadillac Escalade Luxury. This high-performance suv delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 902,
  },
  {
    id: "car-new-york-city-porsche-7",
    make: "Porsche",
    model: "Macan S",
    year: 2020,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 369,
    colorOptions: ["Metallic Silver", "Matte Black", "Ivory"],
    features: ["Ventilated Seats", "Automatic Emergency Braking", "Parking Sensors", "Leather Seats", "Heads-Up Display", "Voice Control", "Sport Suspension"],
    rentalPricePerDay: 1013,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/convertible/porsche-macan-s.jpg",
    description: "Experience the luxury and power of the 2020 Porsche Macan S. This stunning convertible offers an unforgettable driving experience in new-york-city.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3039,
  },
  {
    id: "car-new-york-city-cadillac-8",
    make: "Cadillac",
    model: "XT5 Luxury",
    year: 2023,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 349,
    colorOptions: ["Ivory", "Sunset Orange", "Canyon Red", "Burgundy"],
    features: ["Premium Sound System", "Power Tailgate", "Heads-Up Display", "Keyless Entry", "Automatic Emergency Braking", "Backup Camera"],
    rentalPricePerDay: 499,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/suv/cadillac-xt5-luxury.jpg",
    description: "Turn heads in new-york-city with the sophisticated 2023 Cadillac XT5 Luxury. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 998,
  },
  {
    id: "car-new-york-city-bmw-9",
    make: "BMW",
    model: "i8",
    year: 2020,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 505,
    colorOptions: ["Ice Blue", "Ruby Red", "Bronze"],
    features: ["Ambient Lighting", "Automatic Emergency Braking", "Voice Control", "Lane Keep Assist", "Four-Wheel Drive", "Night Vision"],
    rentalPricePerDay: 500,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/coupe/bmw-i8.jpg",
    description: "Experience the luxury and power of the 2020 BMW i8. This stunning coupe offers an unforgettable driving experience in new-york-city.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2000,
  },
  {
    id: "car-new-york-city-volkswagen-10",
    make: "Volkswagen",
    model: "Scirocco",
    year: 2020,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 552,
    colorOptions: ["Cement Gray", "Moonlight Silver", "Amethyst Purple", "Rose Gold", "Pearl White"],
    features: ["Electric Adjustable Seats", "Digital Cockpit", "GPS Navigation", "Lane Keep Assist", "Tow Package", "Performance Tires", "Running Boards"],
    rentalPricePerDay: 667,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/electric/volkswagen-scirocco.jpg",
    description: "Turn heads in new-york-city with the sophisticated 2020 Volkswagen Scirocco. This exceptional electric offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2668,
  },
  {
    id: "car-new-york-city-genesis-11",
    make: "Genesis",
    model: "G80 Ultimate",
    year: 2020,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 443,
    colorOptions: ["Sunset Orange", "Diamond Black", "Amethyst Purple", "Champagne"],
    features: ["Heads-Up Display", "Roof Rack", "Android Auto", "Wireless Charging", "Performance Tires", "Keyless Entry", "Bluetooth", "Ambient Lighting", "Push-Button Start"],
    rentalPricePerDay: 533,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/suv/genesis-g80-ultimate.jpg",
    description: "The 2020 Genesis G80 Ultimate combines elegance with performance. Enjoy premium features like Heads-Up Display and Roof Rack while exploring new-york-city in this remarkable suv.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2132,
  },
  {
    id: "car-new-york-city-mclaren-12",
    make: "McLaren",
    model: "Senna",
    year: 2020,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 432,
    colorOptions: ["Cement Gray", "Metallic Silver", "Graphite"],
    features: ["Night Vision", "Touchscreen Display", "Dual-Zone Climate Control", "Wi-Fi Hotspot", "Panoramic Roof", "360-Degree Camera", "Massage Seats", "Ventilated Seats", "Satellite Radio", "Apple CarPlay"],
    rentalPricePerDay: 1248,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/convertible/mclaren-senna.jpg",
    description: "Discover new-york-city in style with the 2020 McLaren Senna. With 432 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3744,
  },
  {
    id: "car-new-york-city-rolls-royce-13",
    make: "Rolls-Royce",
    model: "Corniche",
    year: 2020,
    type: "Limousine",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 361,
    colorOptions: ["Champagne", "Carbon Black", "Steel Blue", "Canyon Red", "Matte Black"],
    features: ["Satellite Radio", "Night Vision", "Adaptive Cruise Control", "Touchscreen Display", "Premium Sound System"],
    rentalPricePerDay: 1627,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-corniche.jpg",
    description: "Experience the luxury and power of the 2020 Rolls-Royce Corniche. This stunning limousine offers an unforgettable driving experience in new-york-city.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 6508,
  },
  {
    id: "car-new-york-city-rolls-royce-14",
    make: "Rolls-Royce",
    model: "Ghost Series II",
    year: 2022,
    type: "Limousine",
    seats: 6,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 442,
    colorOptions: ["Ruby Red", "Glacier White", "Burgundy"],
    features: ["Lane Keep Assist", "Cross Traffic Alert", "Push-Button Start", "Performance Tires", "All-Wheel Drive"],
    rentalPricePerDay: 1516,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-ghost-series-ii.jpg",
    description: "The 2022 Rolls-Royce Ghost Series II combines elegance with performance. Enjoy premium features like Lane Keep Assist and Cross Traffic Alert while exploring new-york-city in this remarkable limousine.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 6064,
  },
  {
    id: "car-new-york-city-maserati-15",
    make: "Maserati",
    model: "Ghibli S Q4 GranLusso",
    year: 2021,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 431,
    colorOptions: ["Carbon Black", "Emerald Green", "Moonlight Silver", "Ocean Teal", "Gunmetal Gray"],
    features: ["Keyless Entry", "Wi-Fi Hotspot", "Heads-Up Display", "Sunroof"],
    rentalPricePerDay: 724,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/coupe/maserati-ghibli-s-q4-granlusso.jpg",
    description: "The 2021 Maserati Ghibli S Q4 GranLusso combines elegance with performance. Enjoy premium features like Keyless Entry and Wi-Fi Hotspot while exploring new-york-city in this remarkable coupe.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1448,
  },
  {
    id: "car-new-york-city-audi-16",
    make: "Audi",
    model: "S7",
    year: 2022,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 575,
    colorOptions: ["Amethyst Purple", "Metallic Silver"],
    features: ["Touchscreen Display", "Android Auto", "Lane Keep Assist", "Massage Seats", "Rear Entertainment System"],
    rentalPricePerDay: 600,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/coupe/audi-s7.jpg",
    description: "Discover new-york-city in style with the 2022 Audi S7. With 575 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1800,
  },
  {
    id: "car-new-york-city-chrysler-17",
    make: "Chrysler",
    model: "Aspen",
    year: 2022,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 350,
    colorOptions: ["Metallic Silver", "Matte Black", "Graphite", "British Racing Green", "Ice Blue"],
    features: ["GPS Navigation", "Electric Adjustable Seats", "Running Boards", "Adaptive Cruise Control", "Four-Wheel Drive", "Leather Seats", "Automatic Emergency Braking", "All-Wheel Drive", "Roof Rack", "Third-Row Seating"],
    rentalPricePerDay: 992,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/limousine/chrysler-aspen.jpg",
    description: "Experience the luxury and power of the 2022 Chrysler Aspen. This stunning limousine offers an unforgettable driving experience in new-york-city.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2976,
  },
  {
    id: "car-new-york-city-ferrari-18",
    make: "Ferrari",
    model: "488 Spider",
    year: 2022,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 570,
    colorOptions: ["Sunset Orange", "Ruby Red", "Lava Orange"],
    features: ["Wi-Fi Hotspot", "Push-Button Start", "Premium Sound System", "Touchscreen Display", "Backup Camera", "Rear Entertainment System", "Sunroof"],
    rentalPricePerDay: 781,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/coupe/ferrari-488-spider.jpg",
    description: "Elevate your new-york-city experience with the prestigious 2022 Ferrari 488 Spider. This high-performance coupe delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3124,
  },
  {
    id: "car-new-york-city-cadillac-19",
    make: "Cadillac",
    model: "XT5 Premium Luxury",
    year: 2023,
    type: "Limousine",
    seats: 4,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 375,
    colorOptions: ["Midnight Blue", "Sunset Orange", "Moonlight Silver"],
    features: ["Push-Button Start", "Bluetooth", "Parking Sensors", "Rear Entertainment System", "Automatic Emergency Braking", "Android Auto", "Ambient Lighting"],
    rentalPricePerDay: 805,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/limousine/cadillac-xt5-premium-luxury.jpg",
    description: "Experience the luxury and power of the 2023 Cadillac XT5 Premium Luxury. This stunning limousine offers an unforgettable driving experience in new-york-city.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1610,
  },
  {
    id: "car-new-york-city-ford-20",
    make: "Ford",
    model: "Taurus",
    year: 2023,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 578,
    colorOptions: ["Sunset Orange", "Matte Gray", "Ice Blue", "Ruby Red"],
    features: ["Blind Spot Monitoring", "Third-Row Seating", "Sport Suspension", "Automatic Emergency Braking", "Adaptive Cruise Control", "Cross Traffic Alert", "Panoramic Roof", "Digital Cockpit"],
    rentalPricePerDay: 664,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/electric/ford-taurus.jpg",
    description: "Turn heads in new-york-city with the sophisticated 2023 Ford Taurus. This exceptional electric offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2656,
  },
  {
    id: "car-new-york-city-audi-21",
    make: "Audi",
    model: "A6 L",
    year: 2020,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 473,
    colorOptions: ["Matte Gray", "British Racing Green", "Carbon Black", "Gunmetal Gray"],
    features: ["Rear Entertainment System", "Push-Button Start", "Blind Spot Monitoring", "Four-Wheel Drive", "Roof Rack", "Adaptive Cruise Control", "Digital Cockpit", "Heads-Up Display"],
    rentalPricePerDay: 805,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/convertible/audi-a6-l.jpg",
    description: "Discover new-york-city in style with the 2020 Audi A6 L. With 473 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3220,
  },
  {
    id: "car-new-york-city-porsche-22",
    make: "Porsche",
    model: "Panamera Sport Turismo",
    year: 2022,
    type: "Hybrid",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 421,
    colorOptions: ["Copper", "Lava Orange", "Alpine White", "Sunset Orange"],
    features: ["Panoramic Roof", "Sunroof", "Massage Seats", "Tow Package", "Android Auto", "Push-Button Start", "Blind Spot Monitoring", "Electric Adjustable Seats", "Wireless Charging", "Convertible Roof"],
    rentalPricePerDay: 859,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/hybrid/porsche-panamera-sport-turismo.jpg",
    description: "The 2022 Porsche Panamera Sport Turismo combines elegance with performance. Enjoy premium features like Panoramic Roof and Sunroof while exploring new-york-city in this remarkable hybrid.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1718,
  },
  {
    id: "car-new-york-city-bmw-23",
    make: "BMW",
    model: "X6",
    year: 2020,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 546,
    colorOptions: ["Glacier White", "Diamond Black", "Champagne"],
    features: ["Massage Seats", "Adjustable Ride Height", "Tri-Zone Climate Control", "Lane Keep Assist", "Rear Entertainment System", "Automatic Emergency Braking"],
    rentalPricePerDay: 562,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/coupe/bmw-x6.jpg",
    description: "Turn heads in new-york-city with the sophisticated 2020 BMW X6. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1686,
  },
  {
    id: "car-new-york-city-aston-martin-24",
    make: "Aston Martin",
    model: "DBX",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 657,
    colorOptions: ["Glacier White", "British Racing Green", "Alpine White", "Moonlight Silver"],
    features: ["Premium Sound System", "Blind Spot Monitoring", "Power Tailgate", "Third-Row Seating", "Touchscreen Display", "Fog Lights", "360-Degree Camera"],
    rentalPricePerDay: 1605,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/sports-car/aston-martin-dbx.jpg",
    description: "Elevate your new-york-city experience with the prestigious 2019 Aston Martin DBX. This high-performance sports car delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3210,
  },
  {
    id: "car-new-york-city-lincoln-25",
    make: "Lincoln",
    model: "MKS EcoBoost",
    year: 2021,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 281,
    colorOptions: ["Matte Gray", "Ice Blue", "Burgundy", "Midnight Blue", "Moonlight Silver"],
    features: ["GPS Navigation", "Dual-Zone Climate Control", "Blind Spot Monitoring", "Third-Row Seating", "Bluetooth", "Touchscreen Display", "Automatic Emergency Braking"],
    rentalPricePerDay: 399,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/sedan/lincoln-mks-ecoboost.jpg",
    description: "Discover new-york-city in style with the 2021 Lincoln MKS EcoBoost. With 281 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1596,
  },
  {
    id: "car-new-york-city-lexus-26",
    make: "Lexus",
    model: "LS 500",
    year: 2019,
    type: "Limousine",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 496,
    colorOptions: ["Champagne", "Lava Orange", "Matte Black", "British Racing Green"],
    features: ["Blind Spot Monitoring", "Parking Sensors", "GPS Navigation", "Wi-Fi Hotspot", "Massage Seats", "Adaptive Cruise Control"],
    rentalPricePerDay: 982,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/limousine/lexus-ls-500.jpg",
    description: "Elevate your new-york-city experience with the prestigious 2019 Lexus LS 500. This high-performance limousine delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2946,
  }
];
