// Auto-generated luxury car rentals for new-york-city
// Country: United States, Region: New York
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const newYorkCityunitedStatesnewYorkCars: LuxuryRentalCar[] = [
  {
    id: "car-new-york-city-toyota-1",
    make: "Toyota",
    model: "Avalon Hybrid",
    year: 2020,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 392,
    colorOptions: ["Bronze", "Ocean Teal", "Nardo Gray"],
    features: ["Running Boards", "Heads-Up Display", "Lane Keep Assist", "Electric Adjustable Seats", "Convertible Roof", "Adjustable Ride Height", "Ambient Lighting", "Automatic Emergency Braking"],
    rentalPricePerDay: 484,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/suv/toyota-avalon-hybrid.jpg",
    description: "The 2020 Toyota Avalon Hybrid combines elegance with performance. Enjoy premium features like Running Boards and Heads-Up Display while exploring new-york-city in this remarkable suv.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 968,
  },
  {
    id: "car-new-york-city-aston-martin-2",
    make: "Aston Martin",
    model: "Rapide S Ultimate",
    year: 2021,
    type: "Sports Car",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 503,
    colorOptions: ["Carbon Black", "Champagne", "Copper", "Pearl White"],
    features: ["Third-Row Seating", "Automatic Emergency Braking", "Fog Lights", "Digital Cockpit", "Massage Seats", "Electric Adjustable Seats", "Leather Seats", "Satellite Radio"],
    rentalPricePerDay: 1660,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/sports-car/aston-martin-rapide-s-ultimate.jpg",
    description: "The 2021 Aston Martin Rapide S Ultimate combines elegance with performance. Enjoy premium features like Third-Row Seating and Automatic Emergency Braking while exploring new-york-city in this remarkable sports car.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 4980,
  },
  {
    id: "car-new-york-city-rivian-3",
    make: "Rivian",
    model: "Rivian R1T Launch Edition",
    year: 2023,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 457,
    colorOptions: ["Steel Blue", "Emerald Green", "Gunmetal Gray"],
    features: ["Performance Tires", "Android Auto", "Push-Button Start", "Ambient Lighting", "Electric Adjustable Seats", "Tow Package"],
    rentalPricePerDay: 621,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/electric/rivian-rivian-r1t-launch-edition.jpg",
    description: "Experience the luxury and power of the 2023 Rivian Rivian R1T Launch Edition. This stunning electric offers an unforgettable driving experience in new-york-city.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1863,
  },
  {
    id: "car-new-york-city-cadillac-4",
    make: "Cadillac",
    model: "XT5 Platinum",
    year: 2020,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 453,
    colorOptions: ["Rose Gold", "Cement Gray", "Steel Blue", "Gunmetal Gray", "Glacier White"],
    features: ["Tow Package", "Android Auto", "Leather Seats", "Remote Start", "Driver Attention Monitoring"],
    rentalPricePerDay: 698,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/electric/cadillac-xt5-platinum.jpg",
    description: "Elevate your new-york-city experience with the prestigious 2020 Cadillac XT5 Platinum. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2094,
  },
  {
    id: "car-new-york-city-polestar-5",
    make: "Polestar",
    model: "Polestar 3 Long Range",
    year: 2021,
    type: "Sedan",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 447,
    colorOptions: ["Nardo Gray", "Diamond Black", "Champagne"],
    features: ["Automatic Emergency Braking", "Wireless Charging", "Blind Spot Monitoring", "Running Boards", "Android Auto", "LED Headlights", "Keyless Entry"],
    rentalPricePerDay: 412,
    currency: "USD",
    available: false,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/sedan/polestar-polestar-3-long-range.jpg",
    description: "Discover new-york-city in style with the 2021 Polestar Polestar 3 Long Range. With 447 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1648,
  },
  {
    id: "car-new-york-city-bmw-6",
    make: "BMW",
    model: "M8 Gran Coupe",
    year: 2021,
    type: "Sedan",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 288,
    colorOptions: ["Graphite", "Alpine White", "Pearl White", "Amethyst Purple", "Glacier White"],
    features: ["Sunroof", "Push-Button Start", "Tri-Zone Climate Control", "Launch Control", "LED Headlights", "Touchscreen Display", "Heated Seats"],
    rentalPricePerDay: 432,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/sedan/bmw-m8-gran-coupe.jpg",
    description: "Elevate your new-york-city experience with the prestigious 2021 BMW M8 Gran Coupe. This high-performance sedan delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1728,
  },
  {
    id: "car-new-york-city-ferrari-7",
    make: "Ferrari",
    model: "812 Superfast",
    year: 2023,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 623,
    colorOptions: ["Sapphire Blue", "Ivory", "Nardo Gray"],
    features: ["Performance Tires", "Keyless Entry", "Heated Seats", "Digital Cockpit", "GPS Navigation"],
    rentalPricePerDay: 1803,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/sports-car/ferrari-812-superfast.jpg",
    description: "The 2023 Ferrari 812 Superfast combines elegance with performance. Enjoy premium features like Performance Tires and Keyless Entry while exploring new-york-city in this remarkable sports car.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 7212,
  },
  {
    id: "car-new-york-city-infiniti-8",
    make: "Infiniti",
    model: "QX60",
    year: 2020,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 363,
    colorOptions: ["Gunmetal Gray", "Sunset Orange", "Cement Gray"],
    features: ["Tri-Zone Climate Control", "Digital Cockpit", "LED Headlights", "Wireless Charging", "Tow Package", "Parking Sensors", "Power Tailgate", "Touchscreen Display", "GPS Navigation"],
    rentalPricePerDay: 545,
    currency: "USD",
    available: true,
    pickUpCity: "New York City",
    pickUpCountry: "United States",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/suv/infiniti-qx60.jpg",
    description: "The 2020 Infiniti QX60 combines elegance with performance. Enjoy premium features like Tri-Zone Climate Control and Digital Cockpit while exploring new-york-city in this remarkable suv.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2180,
  }
];
