// Auto-generated luxury car rentals for riga
// Country: Latvia, Region: Latvia
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const rigalatvialatviaCars: LuxuryRentalCar[] = [
  {
    id: "car-riga-porsche-1",
    make: "Porsche",
    model: "Cayenne E-Hybrid",
    year: 2021,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 537,
    colorOptions: ["Champagne", "British Racing Green", "Carbon Black", "Burgundy"],
    features: ["Keyless Entry", "Wireless Charging", "Leather Seats", "Remote Start", "Power Tailgate", "Blind Spot Monitoring", "LED Headlights", "Heated Seats", "Dual-Zone Climate Control", "Panoramic Roof"],
    rentalPricePerDay: 979,
    currency: undefined,
    available: false,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/convertible/porsche-cayenne-e-hybrid.jpg",
    description: "The 2021 Porsche Cayenne E-Hybrid combines elegance with performance. Enjoy premium features like Keyless Entry and Wireless Charging while exploring riga in this remarkable convertible.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2937,
  },
  {
    id: "car-riga-chevrolet-2",
    make: "Chevrolet",
    model: "Tahoe",
    year: 2019,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 409,
    colorOptions: ["Matte Gray", "Ruby Red", "Forest Green"],
    features: ["Keyless Entry", "Heads-Up Display", "Remote Start", "Tow Package", "Massage Seats"],
    rentalPricePerDay: 488,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/suv/chevrolet-tahoe.jpg",
    description: "The 2019 Chevrolet Tahoe combines elegance with performance. Enjoy premium features like Keyless Entry and Heads-Up Display while exploring riga in this remarkable suv.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 976,
  },
  {
    id: "car-riga-porsche-3",
    make: "Porsche",
    model: "911 Carrera",
    year: 2022,
    type: "Coupe",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 406,
    colorOptions: ["Carbon Black", "Sapphire Blue", "Canyon Red", "Ivory", "Nardo Gray"],
    features: ["360-Degree Camera", "Roof Rack", "Fog Lights", "Android Auto", "Running Boards", "Touchscreen Display"],
    rentalPricePerDay: 662,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/coupe/porsche-911-carrera.jpg",
    description: "Turn heads in riga with the sophisticated 2022 Porsche 911 Carrera. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1986,
  },
  {
    id: "car-riga-aston-martin-4",
    make: "Aston Martin",
    model: "Vantage Roadster",
    year: 2019,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 490,
    colorOptions: ["Lava Orange", "Alpine White", "British Racing Green", "Matte Gray"],
    features: ["Heads-Up Display", "Remote Start", "Keyless Entry", "Massage Seats", "Lane Keep Assist", "Tri-Zone Climate Control", "Sport Suspension", "Convertible Roof", "360-Degree Camera", "Apple CarPlay"],
    rentalPricePerDay: 783,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/coupe/aston-martin-vantage-roadster.jpg",
    description: "Discover riga in style with the 2019 Aston Martin Vantage Roadster. With 490 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3132,
  },
  {
    id: "car-riga-aston-martin-5",
    make: "Aston Martin",
    model: "DB11 Volante",
    year: 2020,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 545,
    colorOptions: ["Canyon Red", "Forest Green", "Moonlight Silver", "Ice Blue"],
    features: ["Sport Suspension", "All-Wheel Drive", "Digital Cockpit", "Leather Seats", "Android Auto", "Driver Attention Monitoring", "Four-Wheel Drive", "Touchscreen Display"],
    rentalPricePerDay: 1070,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/convertible/aston-martin-db11-volante.jpg",
    description: "Experience the luxury and power of the 2020 Aston Martin DB11 Volante. This stunning convertible offers an unforgettable driving experience in riga.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2140,
  },
  {
    id: "car-riga-bmw-6",
    make: "BMW",
    model: "M8",
    year: 2021,
    type: "Convertible",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 549,
    colorOptions: ["Ivory", "Nardo Gray", "Cement Gray", "Moonlight Silver", "Bronze"],
    features: ["Running Boards", "Four-Wheel Drive", "Tow Package", "Keyless Entry", "Roof Rack", "Touchscreen Display", "Premium Sound System"],
    rentalPricePerDay: 885,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/convertible/bmw-m8.jpg",
    description: "Discover riga in style with the 2021 BMW M8. With 549 horsepower and premium features, this convertible is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2655,
  },
  {
    id: "car-riga-porsche-7",
    make: "Porsche",
    model: "Panamera Turbo",
    year: 2021,
    type: "Hybrid",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 504,
    colorOptions: ["Metallic Silver", "Lava Orange", "Midnight Blue", "Matte Gray", "Nardo Gray"],
    features: ["GPS Navigation", "Tri-Zone Climate Control", "Adaptive Cruise Control", "All-Wheel Drive", "Apple CarPlay", "Massage Seats", "Performance Tires", "Lane Keep Assist", "Bluetooth"],
    rentalPricePerDay: 899,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/hybrid/porsche-panamera-turbo.jpg",
    description: "Turn heads in riga with the sophisticated 2021 Porsche Panamera Turbo. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1798,
  },
  {
    id: "car-riga-jaguar-8",
    make: "Jaguar",
    model: "XJ Portfolio",
    year: 2019,
    type: "Convertible",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 405,
    colorOptions: ["Ocean Teal", "British Racing Green", "Canyon Red", "Sunset Orange"],
    features: ["Third-Row Seating", "Wi-Fi Hotspot", "Rear Entertainment System", "Dual-Zone Climate Control", "Performance Tires", "Sunroof"],
    rentalPricePerDay: 740,
    currency: undefined,
    available: false,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/convertible/jaguar-xj-portfolio.jpg",
    description: "Elevate your riga experience with the prestigious 2019 Jaguar XJ Portfolio. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2220,
  },
  {
    id: "car-riga-lucid-9",
    make: "Lucid",
    model: "Air Pure",
    year: 2021,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 405,
    colorOptions: ["Alpine White", "Sunset Orange", "Lava Orange", "Moonlight Silver", "Bronze"],
    features: ["Lane Keep Assist", "Wi-Fi Hotspot", "Massage Seats", "Panoramic Roof", "LED Headlights"],
    rentalPricePerDay: 457,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/sedan/lucid-air-pure.jpg",
    description: "The 2021 Lucid Air Pure combines elegance with performance. Enjoy premium features like Lane Keep Assist and Wi-Fi Hotspot while exploring riga in this remarkable sedan.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1828,
  },
  {
    id: "car-riga-nissan-10",
    make: "Nissan",
    model: "Premium",
    year: 2019,
    type: "Sports Car",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 567,
    colorOptions: ["Nardo Gray", "Emerald Green", "Sunset Orange", "Ruby Red", "Carbon Black"],
    features: ["LED Headlights", "Panoramic Roof", "Launch Control", "Wi-Fi Hotspot", "Digital Cockpit"],
    rentalPricePerDay: 1185,
    currency: undefined,
    available: false,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/sports-car/nissan-premium.jpg",
    description: "Turn heads in riga with the sophisticated 2019 Nissan Premium. This exceptional sports car offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4740,
  },
  {
    id: "car-riga-mercedes-benz-11",
    make: "Mercedes-Benz",
    model: "AMG GT",
    year: 2021,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 313,
    colorOptions: ["Burgundy", "Ruby Red", "Glacier White"],
    features: ["Electric Adjustable Seats", "LED Headlights", "Driver Attention Monitoring", "Sunroof", "Satellite Radio", "Convertible Roof", "Fog Lights"],
    rentalPricePerDay: 739,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/suv/mercedes-benz-amg-gt.jpg",
    description: "Turn heads in riga with the sophisticated 2021 Mercedes-Benz AMG GT. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1478,
  },
  {
    id: "car-riga-bmw-12",
    make: "BMW",
    model: "X5",
    year: 2023,
    type: "Hybrid",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 540,
    colorOptions: ["British Racing Green", "Matte Gray", "Ruby Red", "Champagne"],
    features: ["Bluetooth", "Voice Control", "Sunroof", "Sport Suspension", "Wi-Fi Hotspot", "Rear Entertainment System", "Remote Start"],
    rentalPricePerDay: 692,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/hybrid/bmw-x5.jpg",
    description: "The 2023 BMW X5 combines elegance with performance. Enjoy premium features like Bluetooth and Voice Control while exploring riga in this remarkable hybrid.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1384,
  },
  {
    id: "car-riga-mercedes-benz-13",
    make: "Mercedes-Benz",
    model: "G-Class",
    year: 2022,
    type: "Hybrid",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 526,
    colorOptions: ["Burgundy", "Ocean Teal", "Pearl White"],
    features: ["Satellite Radio", "Voice Control", "Heads-Up Display", "Automatic Emergency Braking", "Launch Control", "Heated Seats", "Lane Keep Assist", "Touchscreen Display"],
    rentalPricePerDay: 701,
    currency: undefined,
    available: false,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/hybrid/mercedes-benz-g-class.jpg",
    description: "Experience the luxury and power of the 2022 Mercedes-Benz G-Class. This stunning hybrid offers an unforgettable driving experience in riga.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2804,
  },
  {
    id: "car-riga-porsche-14",
    make: "Porsche",
    model: "718 Cayman",
    year: 2019,
    type: "Sports Car",
    seats: 2,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 639,
    colorOptions: ["Emerald Green", "Forest Green", "Alpine White", "Moonlight Silver", "Gunmetal Gray"],
    features: ["Sport Suspension", "Night Vision", "Third-Row Seating", "Adjustable Ride Height", "Remote Start", "Roof Rack"],
    rentalPricePerDay: 1665,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-718-cayman.jpg",
    description: "Discover riga in style with the 2019 Porsche 718 Cayman. With 639 horsepower and premium features, this sports car is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 4995,
  },
  {
    id: "car-riga-ferrari-15",
    make: "Ferrari",
    model: "Portofino M",
    year: 2019,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 475,
    colorOptions: ["Cement Gray", "Diamond Black", "Rose Gold", "Carbon Black"],
    features: ["360-Degree Camera", "Wireless Charging", "Ventilated Seats", "Driver Attention Monitoring", "Keyless Entry", "Roof Rack", "Power Tailgate", "Push-Button Start", "Wi-Fi Hotspot"],
    rentalPricePerDay: 1099,
    currency: undefined,
    available: false,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/hybrid/ferrari-portofino-m.jpg",
    description: "Experience the luxury and power of the 2019 Ferrari Portofino M. This stunning hybrid offers an unforgettable driving experience in riga.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4396,
  },
  {
    id: "car-riga-toyota-16",
    make: "Toyota",
    model: "Prius",
    year: 2023,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 456,
    colorOptions: ["Forest Green", "Pearl White", "Midnight Blue", "Steel Blue"],
    features: ["Dual-Zone Climate Control", "Tri-Zone Climate Control", "Ventilated Seats", "Digital Cockpit", "Tow Package", "Fog Lights", "Keyless Entry", "Wi-Fi Hotspot"],
    rentalPricePerDay: 572,
    currency: undefined,
    available: true,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/hybrid/toyota-prius.jpg",
    description: "Turn heads in riga with the sophisticated 2023 Toyota Prius. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2288,
  },
  {
    id: "car-riga-chrysler-17",
    make: "Chrysler",
    model: "Cordoba",
    year: 2021,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 355,
    colorOptions: ["Ocean Teal", "Ivory", "Matte Gray"],
    features: ["Bluetooth", "Driver Attention Monitoring", "Apple CarPlay", "Voice Control", "Tow Package", "Cross Traffic Alert", "Dual-Zone Climate Control", "Night Vision"],
    rentalPricePerDay: 356,
    currency: undefined,
    available: false,
    pickUpCity: "Riga",
    pickUpCountry: "Latvia",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/sedan/chrysler-cordoba.jpg",
    description: "Elevate your riga experience with the prestigious 2021 Chrysler Cordoba. This high-performance sedan delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1424,
  }
];
