// Auto-generated luxury car rentals for santorini
// Country: Greece, Region: Greek Islands
// This file is auto-generated. Do not edit manually.

// Generated on: 2025-06-08T04:09:39.126Z

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const santorinigreecegreekIslandsCars: LuxuryRentalCar[] = [
  {
    id: "car-santorini-lamborghini-1",
    make: "Lamborghini",
    model: "Huracán EVO Spyder",
    year: 2023,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 603,
    colorOptions: ["Sunset Orange", "Bronze", "Ice Blue"],
    features: ["Leather Seats", "Dual-Zone Climate Control", "Premium Sound System", "Bluetooth", "Running Boards", "Power Tailgate", "Cross Traffic Alert", "Driver Attention Monitoring"],
    rentalPricePerDay: 1729,
    currency: "EUR",
    available: false,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/sports-car/lamborghini-huracán-evo-spyder.jpg",
    description: "Experience the luxury and power of the 2023 Lamborghini Huracán EVO Spyder. This stunning sports car offers an unforgettable driving experience in santorini.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 6916,
  },
  {
    id: "car-santorini-polestar-2",
    make: "Polestar",
    model: "Polestar 6",
    year: 2020,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 483,
    colorOptions: ["Rose Gold", "Diamond Black", "Metallic Silver"],
    features: ["Heated Seats", "Fog Lights", "Adaptive Cruise Control", "Rear Entertainment System", "Adjustable Ride Height", "Four-Wheel Drive", "Sunroof"],
    rentalPricePerDay: 595,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/electric/polestar-polestar-6.jpg",
    description: "The 2020 Polestar Polestar 6 combines elegance with performance. Enjoy premium features like Heated Seats and Fog Lights while exploring santorini in this remarkable electric.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1785,
  },
  {
    id: "car-santorini-mercedes-benz-3",
    make: "Mercedes-Benz",
    model: "AMG GT",
    year: 2019,
    type: "Limousine",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 401,
    colorOptions: ["Sunset Orange", "Ice Blue", "Graphite", "Amethyst Purple"],
    features: ["Driver Attention Monitoring", "Running Boards", "Four-Wheel Drive", "Massage Seats", "Cross Traffic Alert", "Adjustable Ride Height", "Remote Start"],
    rentalPricePerDay: 1051,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/limousine/mercedes-benz-amg-gt.jpg",
    description: "Discover santorini in style with the 2019 Mercedes-Benz AMG GT. With 401 horsepower and premium features, this limousine is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 4204,
  },
  {
    id: "car-santorini-volvo-4",
    make: "Volvo",
    model: "S60 T8",
    year: 2021,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 437,
    colorOptions: ["Alpine White", "Amethyst Purple", "Ivory"],
    features: ["Launch Control", "Cross Traffic Alert", "Sunroof", "Power Tailgate", "Wi-Fi Hotspot"],
    rentalPricePerDay: 311,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/sedan/volvo-s60-t8.jpg",
    description: "Discover santorini in style with the 2021 Volvo S60 T8. With 437 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1244,
  },
  {
    id: "car-santorini-lucid-5",
    make: "Lucid",
    model: "Air Touring",
    year: 2019,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 627,
    colorOptions: ["Cement Gray", "Rose Gold", "Steel Blue", "Lava Orange"],
    features: ["Premium Sound System", "Electric Adjustable Seats", "Launch Control", "Dual-Zone Climate Control", "Heated Seats", "Adjustable Ride Height", "Blind Spot Monitoring"],
    rentalPricePerDay: 532,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/electric/lucid-air-touring.jpg",
    description: "The 2019 Lucid Air Touring combines elegance with performance. Enjoy premium features like Premium Sound System and Electric Adjustable Seats while exploring santorini in this remarkable electric.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1064,
  },
  {
    id: "car-santorini-toyota-6",
    make: "Toyota",
    model: "C-HR Hybrid",
    year: 2023,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 369,
    colorOptions: ["Forest Green", "Ruby Red", "Sunset Orange"],
    features: ["Panoramic Roof", "Fog Lights", "Driver Attention Monitoring", "Parking Sensors", "Ambient Lighting", "Convertible Roof"],
    rentalPricePerDay: 424,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/suv/toyota-c-hr-hybrid.jpg",
    description: "Experience the luxury and power of the 2023 Toyota C-HR Hybrid. This stunning suv offers an unforgettable driving experience in santorini.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1272,
  },
  {
    id: "car-santorini-rolls-royce-7",
    make: "Rolls-Royce",
    model: "Ghost",
    year: 2019,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 437,
    colorOptions: ["Matte Gray", "British Racing Green", "Copper", "Pearl White"],
    features: ["Panoramic Roof", "Heads-Up Display", "Fog Lights", "Blind Spot Monitoring", "Android Auto", "Performance Tires"],
    rentalPricePerDay: 1352,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-ghost.jpg",
    description: "Experience the luxury and power of the 2019 Rolls-Royce Ghost. This stunning limousine offers an unforgettable driving experience in santorini.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 5408,
  },
  {
    id: "car-santorini-lexus-8",
    make: "Lexus",
    model: "LC 500h",
    year: 2023,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 518,
    colorOptions: ["Sapphire Blue", "Champagne", "Steel Blue", "Diamond Black", "Rose Gold"],
    features: ["Apple CarPlay", "Blind Spot Monitoring", "Fog Lights", "Driver Attention Monitoring", "Keyless Entry", "All-Wheel Drive", "Heads-Up Display", "Remote Start"],
    rentalPricePerDay: 570,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/hybrid/lexus-lc-500h.jpg",
    description: "Turn heads in santorini with the sophisticated 2023 Lexus LC 500h. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2280,
  },
  {
    id: "car-santorini-porsche-9",
    make: "Porsche",
    model: "911 Carrera",
    year: 2023,
    type: "Sports Car",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 649,
    colorOptions: ["Carbon Black", "Canyon Red", "Ruby Red", "Cement Gray", "Amethyst Purple"],
    features: ["Night Vision", "Parking Sensors", "Launch Control", "Sport Suspension", "Electric Adjustable Seats", "Wireless Charging"],
    rentalPricePerDay: 1406,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/sports-car/porsche-911-carrera.jpg",
    description: "The 2023 Porsche 911 Carrera combines elegance with performance. Enjoy premium features like Night Vision and Parking Sensors while exploring santorini in this remarkable sports car.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 5624,
  },
  {
    id: "car-santorini-aston-martin-10",
    make: "Aston Martin",
    model: "Vantage Roadster",
    year: 2021,
    type: "Hybrid",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 561,
    colorOptions: ["Midnight Blue", "Graphite", "Bronze", "Copper"],
    features: ["Lane Keep Assist", "Heated Seats", "Driver Attention Monitoring", "Automatic Emergency Braking", "Voice Control", "Tri-Zone Climate Control"],
    rentalPricePerDay: 834,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/hybrid/aston-martin-vantage-roadster.jpg",
    description: "Discover santorini in style with the 2021 Aston Martin Vantage Roadster. With 561 horsepower and premium features, this hybrid is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2502,
  },
  {
    id: "car-santorini-mercedes-benz-11",
    make: "Mercedes-Benz",
    model: "C63 AMG",
    year: 2023,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 499,
    colorOptions: ["Champagne", "Steel Blue", "Ocean Teal", "Glacier White"],
    features: ["Satellite Radio", "Android Auto", "360-Degree Camera", "Four-Wheel Drive", "Driver Attention Monitoring", "Apple CarPlay", "Convertible Roof", "Power Tailgate"],
    rentalPricePerDay: 513,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/coupe/mercedes-benz-c63-amg.jpg",
    description: "Discover santorini in style with the 2023 Mercedes-Benz C63 AMG. With 499 horsepower and premium features, this coupe is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1539,
  },
  {
    id: "car-santorini-aston-martin-12",
    make: "Aston Martin",
    model: "DBS Volante",
    year: 2023,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 571,
    colorOptions: ["Sapphire Blue", "British Racing Green", "Emerald Green"],
    features: ["Electric Adjustable Seats", "Bluetooth", "Panoramic Roof", "Lane Keep Assist", "Ventilated Seats", "Driver Attention Monitoring", "Sport Suspension", "Four-Wheel Drive", "Parking Sensors"],
    rentalPricePerDay: 717,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/hybrid/aston-martin-dbs-volante.jpg",
    description: "Discover santorini in style with the 2023 Aston Martin DBS Volante. With 571 horsepower and premium features, this hybrid is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1434,
  },
  {
    id: "car-santorini-ford-13",
    make: "Ford",
    model: "F-450 Super Duty",
    year: 2023,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 370,
    colorOptions: ["Burgundy", "Sunset Orange", "Emerald Green", "Midnight Blue"],
    features: ["Ambient Lighting", "Satellite Radio", "Massage Seats", "Driver Attention Monitoring", "Remote Start"],
    rentalPricePerDay: 548,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/suv/ford-f-450-super-duty.jpg",
    description: "Discover santorini in style with the 2023 Ford F-450 Super Duty. With 370 horsepower and premium features, this suv is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1096,
  },
  {
    id: "car-santorini-mercedes-benz-14",
    make: "Mercedes-Benz",
    model: "EQB",
    year: 2019,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 517,
    colorOptions: ["Sapphire Blue", "Bronze", "Cement Gray", "Graphite", "Pearl White"],
    features: ["Panoramic Roof", "Four-Wheel Drive", "Running Boards", "Launch Control", "Apple CarPlay", "Ventilated Seats", "360-Degree Camera", "Wi-Fi Hotspot", "GPS Navigation"],
    rentalPricePerDay: 671,
    currency: "EUR",
    available: false,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/hybrid/mercedes-benz-eqb.jpg",
    description: "Elevate your santorini experience with the prestigious 2019 Mercedes-Benz EQB. This high-performance hybrid delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1342,
  },
  {
    id: "car-santorini-corvette-15",
    make: "Corvette",
    model: "C4 Corvette",
    year: 2022,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 545,
    colorOptions: ["Ice Blue", "Ivory", "Midnight Blue", "Bronze", "Matte Black"],
    features: ["LED Headlights", "Running Boards", "Panoramic Roof", "Adaptive Cruise Control", "Convertible Roof", "Sport Suspension", "Power Tailgate"],
    rentalPricePerDay: 1002,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/corvette-c4-corvette.jpg",
    description: "The 2022 Corvette C4 Corvette combines elegance with performance. Enjoy premium features like LED Headlights and Running Boards while exploring santorini in this remarkable sports car.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 4008,
  },
  {
    id: "car-santorini-lamborghini-16",
    make: "Lamborghini",
    model: "Urus",
    year: 2020,
    type: "SUV",
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 452,
    colorOptions: ["Diamond Black", "Glacier White", "Forest Green", "Cement Gray"],
    features: ["Sunroof", "Sport Suspension", "Voice Control", "360-Degree Camera", "Third-Row Seating", "Adjustable Ride Height", "Power Tailgate", "Android Auto", "Four-Wheel Drive"],
    rentalPricePerDay: 882,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/suv/lamborghini-urus.jpg",
    description: "Elevate your santorini experience with the prestigious 2020 Lamborghini Urus. This high-performance suv delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 2646,
  },
  {
    id: "car-santorini-ford-17",
    make: "Ford",
    model: "Maverick",
    year: 2021,
    type: "SUV",
    seats: 7,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 439,
    colorOptions: ["Matte Black", "Bronze"],
    features: ["Dual-Zone Climate Control", "Power Tailgate", "Four-Wheel Drive", "Sport Suspension", "Roof Rack", "Ventilated Seats", "Touchscreen Display"],
    rentalPricePerDay: 514,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/suv/ford-maverick.jpg",
    description: "Experience the luxury and power of the 2021 Ford Maverick. This stunning suv offers an unforgettable driving experience in santorini.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1028,
  },
  {
    id: "car-santorini-rolls-royce-18",
    make: "Rolls-Royce",
    model: "Dawn Black Badge",
    year: 2020,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 425,
    colorOptions: ["Sunset Orange", "Cement Gray", "Lava Orange", "Rose Gold"],
    features: ["Leather Seats", "Running Boards", "Heated Seats", "Ventilated Seats", "Touchscreen Display", "Backup Camera", "Tow Package"],
    rentalPricePerDay: 1362,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-dawn-black-badge.jpg",
    description: "The 2020 Rolls-Royce Dawn Black Badge combines elegance with performance. Enjoy premium features like Leather Seats and Running Boards while exploring santorini in this remarkable limousine.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 5448,
  },
  {
    id: "car-santorini-infiniti-19",
    make: "Infiniti",
    model: "QX30S",
    year: 2019,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 454,
    colorOptions: ["Copper", "Champagne", "Metallic Silver", "Matte Gray"],
    features: ["Launch Control", "Touchscreen Display", "Driver Attention Monitoring", "Premium Sound System", "GPS Navigation", "Tri-Zone Climate Control", "All-Wheel Drive", "Ventilated Seats", "Third-Row Seating"],
    rentalPricePerDay: 443,
    currency: "EUR",
    available: true,
    pickUpCity: "Santorini",
    pickUpCountry: "Greece",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/suv/infiniti-qx30s.jpg",
    description: "Turn heads in santorini with the sophisticated 2019 Infiniti QX30S. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 886,
  }
];
