import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const skagwayunitedStatesalaskaCars: LuxuryRentalCar[] = [
  {
    id: "car-skagway-mclaren-1",
    make: "McLaren",
    model: "Artura",
    year: 2023,
    type: "Coupe",
    seats: 5,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 536,
    colorOptions: ["Rose Gold", "Matte Black", "Alpine White"],
    features: [
      "Third-Row Seating",
      "Blind Spot Monitoring",
      "Fog Lights",
      "Cross Traffic Alert",
      "Voice Control",
      "Ambient Lighting",
    ],
    rentalPricePerDay: 886,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://paragon-trails-car-images.com/coupe/mclaren-artura.jpg",
    description:
      "The 2023 McLaren Artura combines elegance with performance. Enjoy premium features like Third-Row Seating and Blind Spot Monitoring while exploring skagway in this remarkable coupe.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 3544,
  },
  {
    id: "car-skagway-lincoln-2",
    make: "Lincoln",
    model: "Nautilus",
    year: 2022,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 410,
    colorOptions: ["Pearl White", "Ice Blue", "Burgundy"],
    features: [
      "Keyless Entry",
      "Digital Cockpit",
      "Voice Control",
      "Wireless Charging",
      "Parking Sensors",
      "Automatic Emergency Braking",
      "Leather Seats",
    ],
    rentalPricePerDay: 446,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Cruise Port",
    imageUrl:
      "https://paragon-trails-car-images.com/sedan/lincoln-nautilus.jpg",
    description:
      "Turn heads in skagway with the sophisticated 2022 Lincoln Nautilus. This exceptional sedan offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1784,
  },
  {
    id: "car-skagway-bentley-3",
    make: "Bentley",
    model: "Bentayga",
    year: 2019,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 566,
    colorOptions: ["Ivory", "Pearl White", "Steel Blue", "Forest Green"],
    features: [
      "Sport Suspension",
      "Sunroof",
      "Lane Keep Assist",
      "Apple CarPlay",
      "Ambient Lighting",
      "Satellite Radio",
      "Ventilated Seats",
    ],
    rentalPricePerDay: 940,
    currency: "USD",
    available: false,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Airport Curbside",
    imageUrl:
      "https://paragon-trails-car-images.com/hybrid/bentley-bentayga.jpg",
    description:
      "The 2019 Bentley Bentayga combines elegance with performance. Enjoy premium features like Sport Suspension and Sunroof while exploring skagway in this remarkable hybrid.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 3760,
  },
];
