// Auto-generated luxury car rentals for southampton
// Country: England, Region: 
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const southamptonCars: LuxuryRentalCar[] = [
  {
    id: "car-southampton-rolls-royce-1",
    make: "Rolls-Royce",
    model: "Wraith Coupe",
    year: 2019,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 351,
    colorOptions: ["Ice Blue", "Glacier White", "Ocean Teal"],
    features: ["360-Degree Camera", "Panoramic Roof", "Fog Lights", "Rear Entertainment System", "Cross Traffic Alert", "Parking Sensors"],
    rentalPricePerDay: 953,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/suv/rolls-royce-wraith-coupe.jpg",
    description: "Experience the luxury and power of the 2019 Rolls-Royce Wraith Coupe. This stunning suv offers an unforgettable driving experience in southampton.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 3812,
  },
  {
    id: "car-southampton-aston-martin-2",
    make: "Aston Martin",
    model: "Valhalla AMR Pro",
    year: 2023,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 473,
    colorOptions: ["Steel Blue", "Alpine White", "Pearl White"],
    features: ["Adaptive Cruise Control", "Night Vision", "Power Tailgate", "All-Wheel Drive", "GPS Navigation", "360-Degree Camera", "Adjustable Ride Height"],
    rentalPricePerDay: 900,
    currency: "USD",
    available: false,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/hybrid/aston-martin-valhalla-amr-pro.jpg",
    description: "Experience the luxury and power of the 2023 Aston Martin Valhalla AMR Pro. This stunning hybrid offers an unforgettable driving experience in southampton.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 3600,
  },
  {
    id: "car-southampton-lamborghini-3",
    make: "Lamborghini",
    model: "Aventador Roadster",
    year: 2023,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 484,
    colorOptions: ["British Racing Green", "Cement Gray", "Bronze", "Champagne"],
    features: ["Launch Control", "Ambient Lighting", "Voice Control", "Tow Package", "Dual-Zone Climate Control", "Panoramic Roof"],
    rentalPricePerDay: 871,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/coupe/lamborghini-aventador-roadster.jpg",
    description: "Turn heads in southampton with the sophisticated 2023 Lamborghini Aventador Roadster. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 3484,
  },
  {
    id: "car-southampton-lincoln-4",
    make: "Lincoln",
    model: "MKT",
    year: 2019,
    type: "Limousine",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 451,
    colorOptions: ["Alpine White", "Matte Black", "Amethyst Purple", "Ice Blue"],
    features: ["Wireless Charging", "Launch Control", "Sport Suspension", "All-Wheel Drive", "Electric Adjustable Seats", "Lane Keep Assist", "Touchscreen Display", "Blind Spot Monitoring", "Parking Sensors"],
    rentalPricePerDay: 993,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Residential Address",
    imageUrl: "https://images.unsplash.com/limousine/lincoln-mkt.jpg",
    description: "Experience the luxury and power of the 2019 Lincoln MKT. This stunning limousine offers an unforgettable driving experience in southampton.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1986,
  },
  {
    id: "car-southampton-maserati-5",
    make: "Maserati",
    model: "Levante Trofeo",
    year: 2021,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 537,
    colorOptions: ["Sapphire Blue", "Matte Gray", "Metallic Silver", "Canyon Red", "Alpine White"],
    features: ["Dual-Zone Climate Control", "Blind Spot Monitoring", "Night Vision", "Leather Seats", "Lane Keep Assist"],
    rentalPricePerDay: 785,
    currency: "USD",
    available: false,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/coupe/maserati-levante-trofeo.jpg",
    description: "The 2021 Maserati Levante Trofeo combines elegance with performance. Enjoy premium features like Dual-Zone Climate Control and Blind Spot Monitoring while exploring southampton in this remarkable coupe.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 2355,
  },
  {
    id: "car-southampton-lexus-6",
    make: "Lexus",
    model: "LX 570",
    year: 2023,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 440,
    colorOptions: ["Sapphire Blue", "Gunmetal Gray", "Matte Black"],
    features: ["Night Vision", "Backup Camera", "Bluetooth", "Driver Attention Monitoring", "Heated Seats", "Electric Adjustable Seats"],
    rentalPricePerDay: 767,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/hybrid/lexus-lx-570.jpg",
    description: "Turn heads in southampton with the sophisticated 2023 Lexus LX 570. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2301,
  },
  {
    id: "car-southampton-cadillac-7",
    make: "Cadillac",
    model: "XT5-V Sport",
    year: 2021,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 447,
    colorOptions: ["Nardo Gray", "Pearl White", "Sunset Orange", "Alpine White", "Bronze"],
    features: ["Running Boards", "Launch Control", "Digital Cockpit", "Panoramic Roof", "Massage Seats"],
    rentalPricePerDay: 467,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/suv/cadillac-xt5-v-sport.jpg",
    description: "Experience the luxury and power of the 2021 Cadillac XT5-V Sport. This stunning suv offers an unforgettable driving experience in southampton.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1401,
  },
  {
    id: "car-southampton-volkswagen-8",
    make: "Volkswagen",
    model: "ID.5",
    year: 2019,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 479,
    colorOptions: ["Sapphire Blue", "Canyon Red", "Champagne", "Ice Blue"],
    features: ["LED Headlights", "Cross Traffic Alert", "Apple CarPlay", "Tow Package"],
    rentalPricePerDay: 679,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Dealer Lot",
    imageUrl: "https://images.unsplash.com/electric/volkswagen-id.5.jpg",
    description: "Elevate your southampton experience with the prestigious 2019 Volkswagen ID.5. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1358,
  },
  {
    id: "car-southampton-ferrari-9",
    make: "Ferrari",
    model: "812 Superfast",
    year: 2021,
    type: "Convertible",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 419,
    colorOptions: ["Burgundy", "Steel Blue", "Diamond Black"],
    features: ["Tri-Zone Climate Control", "Voice Control", "Electric Adjustable Seats", "Wireless Charging", "Ambient Lighting", "Bluetooth", "Push-Button Start", "Rear Entertainment System", "Four-Wheel Drive"],
    rentalPricePerDay: 1247,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/convertible/ferrari-812-superfast.jpg",
    description: "Elevate your southampton experience with the prestigious 2021 Ferrari 812 Superfast. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 2494,
  },
  {
    id: "car-southampton-honda-10",
    make: "Honda",
    model: "Passport",
    year: 2023,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 456,
    colorOptions: ["Champagne", "Alpine White", "Ice Blue", "Glacier White"],
    features: ["Voice Control", "Adaptive Cruise Control", "Running Boards", "Convertible Roof", "Wi-Fi Hotspot", "Parking Sensors", "Bluetooth", "Blind Spot Monitoring", "Keyless Entry"],
    rentalPricePerDay: 666,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/hybrid/honda-passport.jpg",
    description: "Discover southampton in style with the 2023 Honda Passport. With 456 horsepower and premium features, this hybrid is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1332,
  },
  {
    id: "car-southampton-polestar-11",
    make: "Polestar",
    model: "Polestar 5",
    year: 2022,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 358,
    colorOptions: ["Moonlight Silver", "Cement Gray", "Copper", "Bronze"],
    features: ["Touchscreen Display", "Cross Traffic Alert", "Panoramic Roof", "Heads-Up Display", "360-Degree Camera", "Electric Adjustable Seats"],
    rentalPricePerDay: 357,
    currency: "USD",
    available: true,
    pickUpCity: "Southampton",
    pickUpCountry: "England",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/sedan/polestar-polestar-5.jpg",
    description: "Discover southampton in style with the 2022 Polestar Polestar 5. With 358 horsepower and premium features, this sedan is the perfect companion for your journey.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 1428,
  }
];
