// Auto-generated luxury car rentals for st-petersburg
// Country: Russia, Region: Russia
// This file is auto-generated. Do not edit manually.

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const stPetersburgrussiarussiaCars: LuxuryRentalCar[] = [
  {
    id: "car-st-petersburg-lucid-1",
    make: "Lucid",
    model: "Air Pure",
    year: 2021,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 590,
    colorOptions: ["Ruby Red", "Sunset Orange", "Midnight Blue"],
    features: ["LED Headlights", "Automatic Emergency Braking", "Heads-Up Display", "Cross Traffic Alert", "GPS Navigation", "Launch Control", "Wireless Charging"],
    rentalPricePerDay: 39348,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/electric/lucid-air-pure.jpg",
    description: "Turn heads in st-petersburg with the sophisticated 2021 Lucid Air Pure. This exceptional electric offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 157392,
  },
  {
    id: "car-st-petersburg-ford-2",
    make: "Ford",
    model: "F-250 Super Duty",
    year: 2020,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 548,
    colorOptions: ["British Racing Green", "Matte Gray", "Diamond Black", "Copper", "Graphite"],
    features: ["Keyless Entry", "Ambient Lighting", "Digital Cockpit", "Launch Control", "Rear Entertainment System", "Night Vision", "Cross Traffic Alert"],
    rentalPricePerDay: 78694,
    currency: "RUB",
    available: false,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/sports-car/ford-f-250-super-duty.jpg",
    description: "Experience the luxury and power of the 2020 Ford F-250 Super Duty. This stunning sports car offers an unforgettable driving experience in st-petersburg.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 314776,
  },
  {
    id: "car-st-petersburg-rolls-royce-3",
    make: "Rolls-Royce",
    model: "Wraith",
    year: 2022,
    type: "Convertible",
    seats: 2,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 535,
    colorOptions: ["Matte Gray", "Canyon Red", "Ivory"],
    features: ["Night Vision", "Android Auto", "Voice Control", "Panoramic Roof", "Leather Seats", "Launch Control", "Satellite Radio", "Massage Seats"],
    rentalPricePerDay: 84938,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/convertible/rolls-royce-wraith.jpg",
    description: "Elevate your st-petersburg experience with the prestigious 2022 Rolls-Royce Wraith. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 339752,
  },
  {
    id: "car-st-petersburg-bentley-4",
    make: "Bentley",
    model: "Azure",
    year: 2022,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 439,
    colorOptions: ["Ocean Teal", "Ivory", "Ice Blue", "Ruby Red", "Canyon Red"],
    features: ["Adaptive Cruise Control", "Dual-Zone Climate Control", "Heads-Up Display", "Keyless Entry", "Premium Sound System", "Automatic Emergency Braking"],
    rentalPricePerDay: 84852,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/convertible/bentley-azure.jpg",
    description: "Elevate your st-petersburg experience with the prestigious 2022 Bentley Azure. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 169704,
  },
  {
    id: "car-st-petersburg-lexus-5",
    make: "Lexus",
    model: "UX 200",
    year: 2023,
    type: "Limousine",
    seats: 6,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 359,
    colorOptions: ["Glacier White", "Steel Blue", "Ruby Red", "Midnight Blue"],
    features: ["Remote Start", "Sunroof", "Roof Rack", "Touchscreen Display", "Automatic Emergency Braking"],
    rentalPricePerDay: 75380,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Convention Center",
    imageUrl: "https://images.unsplash.com/limousine/lexus-ux-200.jpg",
    description: "Discover st-petersburg in style with the 2023 Lexus UX 200. With 359 horsepower and premium features, this limousine is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 301520,
  },
  {
    id: "car-st-petersburg-bmw-6",
    make: "BMW",
    model: "M4",
    year: 2020,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 573,
    colorOptions: ["Cement Gray", "Lava Orange"],
    features: ["Push-Button Start", "Adaptive Cruise Control", "Backup Camera", "LED Headlights", "Keyless Entry", "Rear Entertainment System", "Electric Adjustable Seats"],
    rentalPricePerDay: 47242,
    currency: "RUB",
    available: false,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/electric/bmw-m4.jpg",
    description: "Elevate your st-petersburg experience with the prestigious 2020 BMW M4. This high-performance electric delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 188968,
  },
  {
    id: "car-st-petersburg-mercedes-benz-7",
    make: "Mercedes-Benz",
    model: "G-Class",
    year: 2022,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 461,
    colorOptions: ["Sunset Orange", "Gunmetal Gray", "Graphite"],
    features: ["Lane Keep Assist", "Fog Lights", "Push-Button Start", "Roof Rack", "Adaptive Cruise Control", "Sunroof", "Sport Suspension", "Parking Sensors"],
    rentalPricePerDay: 37750,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/coupe/mercedes-benz-g-class.jpg",
    description: "Turn heads in st-petersburg with the sophisticated 2022 Mercedes-Benz G-Class. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 75500,
  },
  {
    id: "car-st-petersburg-bmw-8",
    make: "BMW",
    model: "iX7",
    year: 2023,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 475,
    colorOptions: ["Steel Blue", "Alpine White", "Forest Green"],
    features: ["Panoramic Roof", "Power Tailgate", "Adjustable Ride Height", "All-Wheel Drive", "Performance Tires"],
    rentalPricePerDay: 47136,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/electric/bmw-ix7.jpg",
    description: "Turn heads in st-petersburg with the sophisticated 2023 BMW iX7. This exceptional electric offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 141408,
  },
  {
    id: "car-st-petersburg-mercedes-benz-9",
    make: "Mercedes-Benz",
    model: "C63 AMG",
    year: 2019,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 413,
    colorOptions: ["Glacier White", "Cement Gray", "Carbon Black"],
    features: ["Leather Seats", "Touchscreen Display", "Apple CarPlay", "Premium Sound System", "Driver Attention Monitoring", "Launch Control"],
    rentalPricePerDay: 37819,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/coupe/mercedes-benz-c63-amg.jpg",
    description: "Turn heads in st-petersburg with the sophisticated 2019 Mercedes-Benz C63 AMG. This exceptional coupe offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 113457,
  },
  {
    id: "car-st-petersburg-mercedes-benz-10",
    make: "Mercedes-Benz",
    model: "EQS",
    year: 2019,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 414,
    colorOptions: ["Burgundy", "Champagne", "Diamond Black"],
    features: ["Running Boards", "Wireless Charging", "Digital Cockpit", "Dual-Zone Climate Control", "All-Wheel Drive", "Voice Control"],
    rentalPricePerDay: 37812,
    currency: "RUB",
    available: false,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/coupe/mercedes-benz-eqs.jpg",
    description: "Experience the luxury and power of the 2019 Mercedes-Benz EQS. This stunning coupe offers an unforgettable driving experience in st-petersburg.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 113436,
  },
  {
    id: "car-st-petersburg-lincoln-11",
    make: "Lincoln",
    model: "MKS",
    year: 2022,
    type: "Limousine",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 404,
    colorOptions: ["Amethyst Purple", "Emerald Green", "Graphite", "Ivory", "Ice Blue"],
    features: ["Dual-Zone Climate Control", "Sport Suspension", "Power Tailgate", "Night Vision", "Driver Attention Monitoring", "Tri-Zone Climate Control", "Four-Wheel Drive", "Fog Lights"],
    rentalPricePerDay: 62801,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/limousine/lincoln-mks.jpg",
    description: "Turn heads in st-petersburg with the sophisticated 2022 Lincoln MKS. This exceptional limousine offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 251204,
  },
  {
    id: "car-st-petersburg-volkswagen-12",
    make: "Volkswagen",
    model: "CC",
    year: 2022,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 582,
    colorOptions: ["Amethyst Purple", "Ocean Teal", "Nardo Gray"],
    features: ["GPS Navigation", "Automatic Emergency Braking", "Launch Control", "Roof Rack", "Android Auto", "Four-Wheel Drive", "Touchscreen Display", "Tow Package", "Driver Attention Monitoring", "Premium Sound System"],
    rentalPricePerDay: 39405,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Hotel Lobby",
    imageUrl: "https://images.unsplash.com/electric/volkswagen-cc.jpg",
    description: "Experience the luxury and power of the 2022 Volkswagen CC. This stunning electric offers an unforgettable driving experience in st-petersburg.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 157620,
  },
  {
    id: "car-st-petersburg-lexus-13",
    make: "Lexus",
    model: "RX",
    year: 2021,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 328,
    colorOptions: ["Bronze", "Emerald Green", "Gunmetal Gray", "Graphite"],
    features: ["Third-Row Seating", "Voice Control", "Android Auto", "Tri-Zone Climate Control", "Heated Seats", "Fog Lights", "Satellite Radio"],
    rentalPricePerDay: 42541,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/suv/lexus-rx.jpg",
    description: "Experience the luxury and power of the 2021 Lexus RX. This stunning suv offers an unforgettable driving experience in st-petersburg.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 127623,
  },
  {
    id: "car-st-petersburg-aston-martin-14",
    make: "Aston Martin",
    model: "DBX",
    year: 2021,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 565,
    colorOptions: ["Carbon Black", "Alpine White"],
    features: ["Voice Control", "Night Vision", "Adjustable Ride Height", "Performance Tires", "Heated Seats", "Sunroof"],
    rentalPricePerDay: 59057,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/hybrid/aston-martin-dbx.jpg",
    description: "Experience the luxury and power of the 2021 Aston Martin DBX. This stunning hybrid offers an unforgettable driving experience in st-petersburg.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 177171,
  },
  {
    id: "car-st-petersburg-rolls-royce-15",
    make: "Rolls-Royce",
    model: "Wraith Coupe",
    year: 2022,
    type: "Limousine",
    seats: 6,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 398,
    colorOptions: ["Lava Orange", "Carbon Black", "British Racing Green", "Bronze", "Moonlight Silver"],
    features: ["LED Headlights", "Automatic Emergency Braking", "Power Tailgate", "Four-Wheel Drive", "Wi-Fi Hotspot", "Satellite Radio", "Parking Sensors", "Push-Button Start", "Driver Attention Monitoring"],
    rentalPricePerDay: 113161,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/limousine/rolls-royce-wraith-coupe.jpg",
    description: "Elevate your st-petersburg experience with the prestigious 2022 Rolls-Royce Wraith Coupe. This high-performance limousine delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 339483,
  },
  {
    id: "car-st-petersburg-maserati-16",
    make: "Maserati",
    model: "Alfieri",
    year: 2020,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 522,
    colorOptions: ["Graphite", "Amethyst Purple", "Gunmetal Gray"],
    features: ["Massage Seats", "LED Headlights", "Digital Cockpit", "Dual-Zone Climate Control", "Wireless Charging", "Launch Control"],
    rentalPricePerDay: 117928,
    currency: "RUB",
    available: false,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/sports-car/maserati-alfieri.jpg",
    description: "Turn heads in st-petersburg with the sophisticated 2020 Maserati Alfieri. This exceptional sports car offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 235856,
  },
  {
    id: "car-st-petersburg-porsche-17",
    make: "Porsche",
    model: "911",
    year: 2022,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 324,
    colorOptions: ["Sunset Orange", "Gunmetal Gray", "Ocean Teal", "Alpine White"],
    features: ["Dual-Zone Climate Control", "Backup Camera", "Heated Seats", "Ambient Lighting", "Touchscreen Display", "Night Vision", "Tri-Zone Climate Control", "Roof Rack", "Tow Package"],
    rentalPricePerDay: 53046,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/suv/porsche-911.jpg",
    description: "The 2022 Porsche 911 combines elegance with performance. Enjoy premium features like Dual-Zone Climate Control and Backup Camera while exploring st-petersburg in this remarkable suv.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 212184,
  },
  {
    id: "car-st-petersburg-ferrari-18",
    make: "Ferrari",
    model: "F12 Berlinetta",
    year: 2020,
    type: "Coupe",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 418,
    colorOptions: ["Steel Blue", "Canyon Red"],
    features: ["Premium Sound System", "Wi-Fi Hotspot", "Leather Seats", "Massage Seats", "Adjustable Ride Height"],
    rentalPricePerDay: 56670,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/coupe/ferrari-f12-berlinetta.jpg",
    description: "Elevate your st-petersburg experience with the prestigious 2020 Ferrari F12 Berlinetta. This high-performance coupe delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 113340,
  },
  {
    id: "car-st-petersburg-mercedes-benz-19",
    make: "Mercedes-Benz",
    model: "CLS",
    year: 2020,
    type: "Convertible",
    seats: 4,
    transmission: "Manual",
    fuelType: "Petrol",
    horsepower: 395,
    colorOptions: ["Matte Black", "Carbon Black", "Pearl White"],
    features: ["Panoramic Roof", "Backup Camera", "Four-Wheel Drive", "Tri-Zone Climate Control", "Heads-Up Display", "Massage Seats"],
    rentalPricePerDay: 56648,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/convertible/mercedes-benz-cls.jpg",
    description: "Elevate your st-petersburg experience with the prestigious 2020 Mercedes-Benz CLS. This high-performance convertible delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 169944,
  },
  {
    id: "car-st-petersburg-maybach-20",
    make: "Maybach",
    model: "S 680",
    year: 2021,
    type: "Limousine",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 450,
    colorOptions: ["Lava Orange", "Glacier White", "British Racing Green", "Matte Black", "Ocean Teal"],
    features: ["Roof Rack", "Launch Control", "Tow Package", "Bluetooth", "GPS Navigation", "Wireless Charging", "Performance Tires", "Cross Traffic Alert", "Leather Seats"],
    rentalPricePerDay: 62993,
    currency: "RUB",
    available: false,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/limousine/maybach-s-680.jpg",
    description: "Experience the luxury and power of the 2021 Maybach S 680. This stunning limousine offers an unforgettable driving experience in st-petersburg.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 251972,
  },
  {
    id: "car-st-petersburg-kia-21",
    make: "Kia",
    model: "K5",
    year: 2021,
    type: "Electric",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 588,
    colorOptions: ["Sunset Orange", "Ruby Red", "Gunmetal Gray", "Copper", "Glacier White"],
    features: ["Touchscreen Display", "Panoramic Roof", "Running Boards", "Backup Camera", "Wi-Fi Hotspot", "Push-Button Start", "Voice Control", "Electric Adjustable Seats"],
    rentalPricePerDay: 39449,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Airport Curbside",
    imageUrl: "https://images.unsplash.com/electric/kia-k5.jpg",
    description: "Discover st-petersburg in style with the 2021 Kia K5. With 588 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 78898,
  },
  {
    id: "car-st-petersburg-lexus-22",
    make: "Lexus",
    model: "IS 350",
    year: 2020,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 427,
    colorOptions: ["Burgundy", "Moonlight Silver", "Diamond Black", "Bronze"],
    features: ["Adaptive Cruise Control", "Ventilated Seats", "Tow Package", "Sport Suspension", "Push-Button Start", "Running Boards", "LED Headlights", "Cross Traffic Alert"],
    rentalPricePerDay: 42407,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "VIP Terminal",
    imageUrl: "https://images.unsplash.com/suv/lexus-is-350.jpg",
    description: "Turn heads in st-petersburg with the sophisticated 2020 Lexus IS 350. This exceptional suv offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 169628,
  },
  {
    id: "car-st-petersburg-cadillac-23",
    make: "Cadillac",
    model: "CT5-V",
    year: 2023,
    type: "Sedan",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 388,
    colorOptions: ["Carbon Black", "Lava Orange", "Ruby Red"],
    features: ["Dual-Zone Climate Control", "Ventilated Seats", "Four-Wheel Drive", "GPS Navigation", "Sunroof", "Convertible Roof", "Electric Adjustable Seats", "Voice Control"],
    rentalPricePerDay: 23710,
    currency: "RUB",
    available: true,
    pickUpCity: "St Petersburg",
    pickUpCountry: "Russia",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/sedan/cadillac-ct5-v.jpg",
    description: "Experience the luxury and power of the 2023 Cadillac CT5-V. This stunning sedan offers an unforgettable driving experience in st-petersburg.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 94840,
  }
];
