// Auto-generated luxury car rentals for sydney
// Country: Australia, Region: Australia
// This file is auto-generated. Do not edit manually.

// Generated on: 2025-06-08T04:09:39.129Z

import { LuxuryRentalCar } from "@/lib/interfaces/services/rentals";

export const sydneyaustraliaaustraliaCars: LuxuryRentalCar[] = [
  {
    id: "car-sydney-hyundai-1",
    make: "Hyundai",
    model: "Santa Fe Hybrid",
    year: 2019,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 521,
    colorOptions: ["Midnight Blue", "Metallic Silver", "Alpine White"],
    features: ["Third-Row Seating", "Satellite Radio", "Four-Wheel Drive", "Launch Control"],
    rentalPricePerDay: 823,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/hybrid/hyundai-santa-fe-hybrid.jpg",
    description: "Experience the luxury and power of the 2019 Hyundai Santa Fe Hybrid. This stunning hybrid offers an unforgettable driving experience in sydney.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1646,
  },
  {
    id: "car-sydney-lamborghini-2",
    make: "Lamborghini",
    model: "Gallardo Spyder",
    year: 2021,
    type: "Convertible",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 472,
    colorOptions: ["Forest Green", "Ice Blue", "Diamond Black", "Matte Black", "Moonlight Silver"],
    features: ["Dual-Zone Climate Control", "Lane Keep Assist", "Leather Seats", "Driver Attention Monitoring", "Android Auto", "Launch Control", "Roof Rack", "Keyless Entry", "Sport Suspension"],
    rentalPricePerDay: 1721,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/convertible/lamborghini-gallardo-spyder.jpg",
    description: "The 2021 Lamborghini Gallardo Spyder combines elegance with performance. Enjoy premium features like Dual-Zone Climate Control and Lane Keep Assist while exploring sydney in this remarkable convertible.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 6884,
  },
  {
    id: "car-sydney-chevrolet-3",
    make: "Chevrolet",
    model: "Silverado 3500HD",
    year: 2023,
    type: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuelType: "Diesel",
    horsepower: 443,
    colorOptions: ["Steel Blue", "Matte Gray", "Diamond Black", "Carbon Black"],
    features: ["Ambient Lighting", "Rear Entertainment System", "Voice Control", "Adjustable Ride Height", "Satellite Radio", "Tri-Zone Climate Control", "GPS Navigation", "Heads-Up Display"],
    rentalPricePerDay: 830,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "University Campus",
    imageUrl: "https://images.unsplash.com/suv/chevrolet-silverado-3500hd.jpg",
    description: "Discover sydney in style with the 2023 Chevrolet Silverado 3500HD. With 443 horsepower and premium features, this suv is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2490,
  },
  {
    id: "car-sydney-mclaren-4",
    make: "McLaren",
    model: "600LT",
    year: 2021,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 525,
    colorOptions: ["Pearl White", "Ice Blue", "Midnight Blue"],
    features: ["Satellite Radio", "Bluetooth", "GPS Navigation", "LED Headlights", "Dual-Zone Climate Control"],
    rentalPricePerDay: 1514,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Car Rental Center",
    imageUrl: "https://images.unsplash.com/hybrid/mclaren-600lt.jpg",
    description: "Experience the luxury and power of the 2021 McLaren 600LT. This stunning hybrid offers an unforgettable driving experience in sydney.",
    insuranceIncluded: true,
    minimumRentalAge: 30,
    depositAmount: 6056,
  },
  {
    id: "car-sydney-mercedes-benz-5",
    make: "Mercedes-Benz",
    model: "SLS AMG",
    year: 2019,
    type: "Electric",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 550,
    colorOptions: ["British Racing Green", "Diamond Black", "Lava Orange"],
    features: ["Bluetooth", "Heads-Up Display", "Remote Start", "Roof Rack", "Night Vision", "Power Tailgate", "Electric Adjustable Seats", "Panoramic Roof", "Launch Control"],
    rentalPricePerDay: 1037,
    currency: "AUD",
    available: false,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Downtown Office",
    imageUrl: "https://images.unsplash.com/electric/mercedes-benz-sls-amg.jpg",
    description: "Discover sydney in style with the 2019 Mercedes-Benz SLS AMG. With 550 horsepower and premium features, this electric is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2074,
  },
  {
    id: "car-sydney-volkswagen-6",
    make: "Volkswagen",
    model: "Arteon",
    year: 2023,
    type: "Electric",
    seats: 4,
    transmission: "Automatic",
    fuelType: "Electric",
    horsepower: 540,
    colorOptions: ["Midnight Blue", "Ice Blue", "Lava Orange"],
    features: ["Remote Start", "Rear Entertainment System", "Android Auto", "Ventilated Seats", "Touchscreen Display", "Voice Control"],
    rentalPricePerDay: 786,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Main Terminal",
    imageUrl: "https://images.unsplash.com/electric/volkswagen-arteon.jpg",
    description: "The 2023 Volkswagen Arteon combines elegance with performance. Enjoy premium features like Remote Start and Rear Entertainment System while exploring sydney in this remarkable electric.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2358,
  },
  {
    id: "car-sydney-audi-7",
    make: "Audi",
    model: "Q5L",
    year: 2019,
    type: "Limousine",
    seats: 5,
    transmission: "Manual",
    fuelType: "Diesel",
    horsepower: 379,
    colorOptions: ["Carbon Black", "Ice Blue", "Moonlight Silver"],
    features: ["Satellite Radio", "GPS Navigation", "Touchscreen Display", "Running Boards", "Leather Seats"],
    rentalPricePerDay: 1487,
    currency: "AUD",
    available: false,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Train Station",
    imageUrl: "https://images.unsplash.com/limousine/audi-q5l.jpg",
    description: "Elevate your sydney experience with the prestigious 2019 Audi Q5L. This high-performance limousine delivers an incomparable driving experience with premium comfort.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 4461,
  },
  {
    id: "car-sydney-hyundai-8",
    make: "Hyundai",
    model: "Santa Fe Hybrid",
    year: 2020,
    type: "Hybrid",
    seats: 3,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 478,
    colorOptions: ["Graphite", "Rose Gold", "Alpine White"],
    features: ["Touchscreen Display", "Android Auto", "Massage Seats", "Adaptive Cruise Control"],
    rentalPricePerDay: 944,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Cruise Port",
    imageUrl: "https://images.unsplash.com/hybrid/hyundai-santa-fe-hybrid.jpg",
    description: "Turn heads in sydney with the sophisticated 2020 Hyundai Santa Fe Hybrid. This exceptional hybrid offers unparalleled luxury and performance for discerning drivers.",
    insuranceIncluded: true,
    minimumRentalAge: 25,
    depositAmount: 3776,
  },
  {
    id: "car-sydney-corvette-9",
    make: "Corvette",
    model: "C6 Grand Sport",
    year: 2023,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 689,
    colorOptions: ["Ivory", "Moonlight Silver", "Matte Gray", "Gunmetal Gray"],
    features: ["GPS Navigation", "Convertible Roof", "Panoramic Roof", "LED Headlights", "Ventilated Seats", "Launch Control"],
    rentalPricePerDay: 1684,
    currency: "AUD",
    available: false,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/sports-car/corvette-c6-grand-sport.jpg",
    description: "Discover sydney in style with the 2023 Corvette C6 Grand Sport. With 689 horsepower and premium features, this sports car is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 5052,
  },
  {
    id: "car-sydney-lamborghini-10",
    make: "Lamborghini",
    model: "Gallardo LP 570-4",
    year: 2023,
    type: "Sports Car",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 616,
    colorOptions: ["Cement Gray", "Midnight Blue", "Canyon Red"],
    features: ["Power Tailgate", "Bluetooth", "Four-Wheel Drive", "Driver Attention Monitoring", "LED Headlights", "Night Vision"],
    rentalPricePerDay: 2764,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://images.unsplash.com/sports-car/lamborghini-gallardo-lp-570-4.jpg",
    description: "Experience the luxury and power of the 2023 Lamborghini Gallardo LP 570-4. This stunning sports car offers an unforgettable driving experience in sydney.",
    insuranceIncluded: false,
    minimumRentalAge: 30,
    depositAmount: 11056,
  },
  {
    id: "car-sydney-bmw-11",
    make: "BMW",
    model: "i4 M50",
    year: 2021,
    type: "Hybrid",
    seats: 2,
    transmission: "Automatic",
    fuelType: "Hybrid",
    horsepower: 382,
    colorOptions: ["Metallic Silver", "Canyon Red", "British Racing Green"],
    features: ["Ventilated Seats", "Touchscreen Display", "Driver Attention Monitoring", "Apple CarPlay", "Backup Camera"],
    rentalPricePerDay: 1014,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Bus Terminal",
    imageUrl: "https://images.unsplash.com/hybrid/bmw-i4-m50.jpg",
    description: "Discover sydney in style with the 2021 BMW i4 M50. With 382 horsepower and premium features, this hybrid is the perfect companion for your journey.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 2028,
  },
  {
    id: "car-sydney-range-rover-12",
    make: "Range Rover",
    model: "Range Rover Defender 110",
    year: 2023,
    type: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    horsepower: 375,
    colorOptions: ["Steel Blue", "Alpine White", "Cement Gray"],
    features: ["Launch Control", "Heated Seats", "Cross Traffic Alert", "Performance Tires", "Parking Sensors", "Touchscreen Display", "Tow Package", "Running Boards"],
    rentalPricePerDay: 790,
    currency: "AUD",
    available: true,
    pickUpCity: "Sydney",
    pickUpCountry: "Australia",
    pickUpLocation: "Shopping Mall",
    imageUrl: "https://images.unsplash.com/suv/range-rover-range-rover-defender-110.jpg",
    description: "Experience the luxury and power of the 2023 Range Rover Range Rover Defender 110. This stunning suv offers an unforgettable driving experience in sydney.",
    insuranceIncluded: false,
    minimumRentalAge: 25,
    depositAmount: 1580,
  }
];
