import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Cozy Cloud Inn
export const theCozyCloudInnRooms: RoomOption[] = [
  {
    id: "hotel-san-francisco-7-room-6-Single-None",
    name: "Standard Single Suite",
    description: "Our Standard-themed single suite offers compact luxury, panoramic with a pleasant outlook, and including climate control for your comfort, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 75,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-san-francisco-7-room-6-King-MountainView",
    name: "Signature King Studio",
    description: "Discover the charm of this Signature-themed king studio, complete with exquisite ambiance, stunning with panoramic views of the surrounding mountains, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 185,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-san-francisco-7-room-6-King-CityView",
    name: "Luxury King Apartment",
    description: "Our retro Luxury-themed apartment offers with a view of the city's cultural landmarks, palatial comfort, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 144,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-san-francisco-7-room-6-SofaBed-MountainView",
    name: "Horizon Sofa Bed Studio",
    description: "A broad sofa bed studio designed for spacious comfort, with where the mountains touch the sky and offering a unique blend of style and comfort, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 122,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-san-francisco-7-room-6-King-GardenView",
    name: "Superior King Apartment",
    description: "A large-scale king retreat with serene garden views, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 154,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-san-francisco-7-room-6-Double-None",
    name: "Premium Double Apartment",
    description: "Step into a ample double apartment that combines Premium-themed with breathtaking with a pleasant outlook, complemented by equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 91,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
