import { Yacht } from "@/lib/interfaces/services/rentals";

export const bermudabermudacaribbeanYachts: Yacht[] = [
  {
    id: "yacht-bermuda-motor-0",
    name: "Mediterranean Gem",
    brand: "Horizon",
    model: "Horizon 61",
    yearBuilt: 2012,
    lengthInMeters: 27,
    beamInMeters: 5.4,
    draftInMeters: 2.7,
    cruisingSpeedKnots: 10,
    maxSpeedKnots: 22,
    fuelCapacityLiters: 13500,
    waterCapacityLiters: 8100,
    engines: ["1 x Volvo Penta 8V 1355"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 11,
      guestsOvernight: 9,
      cabins: 3,
      crew: 3,
      bathrooms: 5,
    },
    amenities: ["Kitchen", "BBQ Grill", "Dining Area", "Heated Deck"],
    entertainment: ["Satellite TV", "Streaming Services", "Projector"],
    waterToys: ["Scuba Diving Gear", "Kneeboard", "Fishing Equipment"],
    location: {
      city: "Bermuda",
      country: "Bermuda",
      region: "Caribbean",
      homePort: "Simpson Bay Marina",
    },
    availableSeasons: ["Winter"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["Breakfast Only", "À La Carte"],
    description:
      "Discover the beauty of bermuda's waters aboard the elegant Mediterranean Gem, a 2012 motor yacht featuring spacious accommodation for 9 guests overnight or 11 for day charters.",
    images: [
      "https://paragon-trails-yacht-images.com/motor/bermuda-mediterranean-gem-1.jpg",
      "https://paragon-trails-yacht-images.com/motor/bermuda-mediterranean-gem-2.jpg",
      "https://paragon-trails-yacht-images.com/motor/bermuda-mediterranean-gem-3.jpg",
      "https://paragon-trails-yacht-images.com/motor/bermuda-mediterranean-gem-4.jpg",
      "https://paragon-trails-yacht-images.com/motor/bermuda-mediterranean-gem-5.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 8695,
      perWeek: 51735.25,
      currency: "BMD",
      includes: ["Kitchen", "BBQ Grill", "Dining Area"],
      excludes: ["Heated Deck"],
    },
    safetyFeatures: [
      "Emergency Steering",
      "Fog Horn",
      "Emergency Beacon",
      "Flares",
    ],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-bermuda-super-1",
    name: "Silver Horizon",
    brand: "Fountaine Pajot",
    model: "Fountaine Pajot 28",
    yearBuilt: 2005,
    lengthInMeters: 64,
    beamInMeters: 12.8,
    draftInMeters: 6.4,
    cruisingSpeedKnots: 12,
    maxSpeedKnots: 19,
    fuelCapacityLiters: 32000,
    waterCapacityLiters: 19200,
    engines: ["1 x Volvo Penta 14V 1992"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 21,
      guestsOvernight: 22,
      cabins: 10,
      crew: 10,
      bathrooms: 10,
    },
    amenities: [
      "Outdoor Shower",
      "Wi-Fi",
      "Air Conditioning",
      "Heated Deck",
      "Jacuzzi",
    ],
    entertainment: ["Board Games", "Bluetooth Speakers", "Media Library"],
    waterToys: ["Kayaks", "Water Skis"],
    location: {
      city: "Bermuda",
      country: "Bermuda",
      region: "Caribbean",
      homePort: "Rodney Bay Marina",
    },
    availableSeasons: ["Winter", "Spring", "Fall"],
    charterType: "private",
    crewIncluded: true,
    cateringOptions: ["Provisioning Only"],
    description:
      "Experience luxury and comfort aboard the Silver Horizon, a stunning 64m super yacht available for charter in bermuda. Perfect for day trips or extended voyages.",
    images: [
      "https://paragon-trails-yacht-images.com/super/bermuda-silver-horizon-1.jpg",
      "https://paragon-trails-yacht-images.com/super/bermuda-silver-horizon-2.jpg",
      "https://paragon-trails-yacht-images.com/super/bermuda-silver-horizon-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 99887,
      perWeek: 594327.65,
      currency: "BMD",
      includes: ["Outdoor Shower"],
      excludes: [
        "Outdoor Shower",
        "Wi-Fi",
        "Air Conditioning",
        "Heated Deck",
        "Jacuzzi",
      ],
    },
    safetyFeatures: ["Searchlight", "Navigation Lights", "Flares", "EPIRB"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-bermuda-super-2",
    name: "Wave Dancer",
    brand: "Swan",
    model: "Swan 30",
    yearBuilt: 2010,
    lengthInMeters: 61,
    beamInMeters: 12.2,
    draftInMeters: 6.1,
    cruisingSpeedKnots: 18,
    maxSpeedKnots: 25,
    fuelCapacityLiters: 30500,
    waterCapacityLiters: 18300,
    engines: ["1 x MAN 24V 1258"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 26,
      guestsOvernight: 19,
      cabins: 8,
      crew: 11,
      bathrooms: 10,
    },
    amenities: ["Jacuzzi", "Wi-Fi"],
    entertainment: ["Media Library", "Bluetooth Speakers", "Onboard Cinema"],
    waterToys: ["Scuba Diving Gear", "Water Skis", "Paddleboards", "Kayaks"],
    location: {
      city: "Bermuda",
      country: "Bermuda",
      region: "Caribbean",
      homePort: "Yacht Haven Grande",
    },
    availableSeasons: ["Summer"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["All-Inclusive", "Local Cuisine Packages"],
    description:
      "Charter the impressive Wave Dancer in bermuda and enjoy its 3 luxury amenities and 4 water toys for an exceptional yachting experience.",
    images: [
      "https://paragon-trails-yacht-images.com/super/bermuda-wave-dancer-1.jpg",
      "https://paragon-trails-yacht-images.com/super/bermuda-wave-dancer-2.jpg",
      "https://paragon-trails-yacht-images.com/super/bermuda-wave-dancer-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 176925,
      perWeek: 1052703.75,
      currency: "BMD",
      includes: ["Jacuzzi", "Wi-Fi"],
      excludes: ["Jacuzzi", "Wi-Fi"],
    },
    safetyFeatures: ["Life Jackets", "Emergency Radio", "Emergency Beacon"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-bermuda-catamaran-3",
    name: "Caribbean Pearl",
    brand: "Baglietto",
    model: "Baglietto 69",
    yearBuilt: 2013,
    lengthInMeters: 12,
    beamInMeters: 2.4,
    draftInMeters: 1.2,
    cruisingSpeedKnots: 10,
    maxSpeedKnots: 16,
    fuelCapacityLiters: 6000,
    waterCapacityLiters: 3600,
    engines: ["2 x Cummins 25V 1352"],
    hullType: "catamaran",
    yachtType: "catamaran",
    capacity: {
      guestsDay: 10,
      guestsOvernight: 9,
      cabins: 3,
      crew: 2,
      bathrooms: 3,
    },
    amenities: [
      "Bar",
      "Swim Platform",
      "Kitchen",
      "Air Conditioning",
      "BBQ Grill",
    ],
    entertainment: ["Media Library"],
    waterToys: ["Scuba Diving Gear", "Inflatable Slide", "Seabob"],
    location: {
      city: "Bermuda",
      country: "Bermuda",
      region: "Caribbean",
      homePort: "Yacht Haven Grande",
    },
    availableSeasons: ["Summer", "Spring"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["Self-Catering"],
    description:
      "The Caribbean Pearl is a magnificent catamaran yacht built by Baglietto offering exceptional amenities and impeccable service for an unforgettable sailing experience in bermuda.",
    images: [
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-caribbean-pearl-1.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-caribbean-pearl-2.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-caribbean-pearl-3.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-caribbean-pearl-4.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 11871,
      perWeek: 70632.45,
      currency: "BMD",
      includes: ["Bar", "Swim Platform", "Kitchen"],
      excludes: ["BBQ Grill"],
    },
    safetyFeatures: ["Radar", "Navigation Lights", "Searchlight"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-bermuda-sailing-4",
    name: "Oceanis",
    brand: "Princess",
    model: "Princess 23",
    yearBuilt: 2014,
    lengthInMeters: 17,
    beamInMeters: 3.4,
    draftInMeters: 1.7,
    cruisingSpeedKnots: 12,
    maxSpeedKnots: 21,
    fuelCapacityLiters: 8500,
    waterCapacityLiters: 5100,
    engines: ["1 x MTU 27V 1647"],
    hullType: "monohull",
    yachtType: "sailing",
    capacity: {
      guestsDay: 8,
      guestsOvernight: 7,
      cabins: 2,
      crew: 1,
      bathrooms: 4,
    },
    amenities: ["Dining Area", "Hot Tub", "Air Conditioning", "Kitchen"],
    entertainment: ["Satellite TV", "Game Console"],
    waterToys: ["Jet Ski", "Towable Tubes"],
    location: {
      city: "Bermuda",
      country: "Bermuda",
      region: "Caribbean",
      homePort: "Yacht Haven Grande",
    },
    availableSeasons: ["Winter"],
    charterType: "private",
    crewIncluded: true,
    cateringOptions: ["Breakfast Only", "BBQ Onboard"],
    description:
      "Oceanis combines performance and luxury in a stunning 17m sailing yacht. With its professional crew of 1, you'll experience the ultimate sailing vacation.",
    images: [
      "https://paragon-trails-yacht-images.com/sailing/bermuda-oceanis-1.jpg",
      "https://paragon-trails-yacht-images.com/sailing/bermuda-oceanis-2.jpg",
      "https://paragon-trails-yacht-images.com/sailing/bermuda-oceanis-3.jpg",
      "https://paragon-trails-yacht-images.com/sailing/bermuda-oceanis-4.jpg",
      "https://paragon-trails-yacht-images.com/sailing/bermuda-oceanis-5.jpg",
    ],
    featured: true,
    pricing: {
      perDay: 4138,
      perWeek: 24621.1,
      currency: "BMD",
      includes: ["Dining Area", "Hot Tub"],
      excludes: ["Dining Area", "Hot Tub", "Air Conditioning", "Kitchen"],
    },
    safetyFeatures: [
      "Navigation Lights",
      "Radar",
      "Searchlight",
      "Life Jackets",
      "EPIRB",
    ],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-bermuda-catamaran-5",
    name: "Azure Blue",
    brand: "Ferretti",
    model: "Ferretti 13",
    yearBuilt: 2017,
    lengthInMeters: 14,
    beamInMeters: 2.8,
    draftInMeters: 1.4,
    cruisingSpeedKnots: 16,
    maxSpeedKnots: 21,
    fuelCapacityLiters: 7000,
    waterCapacityLiters: 4200,
    engines: ["1 x Cummins 10V 1988"],
    hullType: "catamaran",
    yachtType: "catamaran",
    capacity: {
      guestsDay: 8,
      guestsOvernight: 11,
      cabins: 4,
      crew: 3,
      bathrooms: 5,
    },
    amenities: [
      "Sauna",
      "BBQ Grill",
      "Air Conditioning",
      "Laundry Service",
      "Bar",
      "Indoor Lounge",
    ],
    entertainment: [
      "Surround Sound System",
      "Bluetooth Speakers",
      "Karaoke System",
    ],
    waterToys: ["E-Foil", "Snorkeling Gear", "Inflatable Slide", "Seabob"],
    location: {
      city: "Bermuda",
      country: "Bermuda",
      region: "Caribbean",
      homePort: "Yacht Haven Grande",
    },
    availableSeasons: ["Spring", "Winter"],
    charterType: "private",
    crewIncluded: true,
    cateringOptions: ["Full-Service Catering", "Self-Catering"],
    description:
      "Experience luxury and comfort aboard the Azure Blue, a stunning 14m catamaran yacht available for charter in bermuda. Perfect for day trips or extended voyages.",
    images: [
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-azure-blue-1.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-azure-blue-2.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-azure-blue-3.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-azure-blue-4.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/bermuda-azure-blue-5.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 8616,
      perWeek: 51265.2,
      currency: "BMD",
      includes: ["Sauna", "BBQ Grill", "Air Conditioning"],
      excludes: [
        "Sauna",
        "BBQ Grill",
        "Air Conditioning",
        "Laundry Service",
        "Bar",
        "Indoor Lounge",
      ],
    },
    safetyFeatures: [
      "Navigation Lights",
      "First Aid Kit",
      "Emergency Radio",
      "GPS Tracking",
    ],
    accessibilityFeatures: ["Easy Boarding", "Accessible Cabin"],
  },
  {
    id: "yacht-bermuda-gulet-6",
    name: "Coastal Serenity",
    brand: "Feadship",
    model: "Feadship 71",
    yearBuilt: 2000,
    lengthInMeters: 18,
    beamInMeters: 3.6,
    draftInMeters: 1.8,
    cruisingSpeedKnots: 12,
    maxSpeedKnots: 26,
    fuelCapacityLiters: 9000,
    waterCapacityLiters: 5400,
    engines: ["1 x MAN 18V 1495"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 16,
      guestsOvernight: 15,
      cabins: 5,
      crew: 3,
      bathrooms: 5,
    },
    amenities: ["Indoor Lounge", "Swim Platform", "Heated Deck"],
    entertainment: ["Board Games"],
    waterToys: ["Inflatable Slide", "Windsurf", "Jet Ski", "Floating Island"],
    location: {
      city: "Bermuda",
      country: "Bermuda",
      region: "Caribbean",
      homePort: "Port Louis Marina",
    },
    availableSeasons: ["Year-Round", "Fall"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["All-Inclusive"],
    description:
      "Charter the impressive Coastal Serenity in bermuda and enjoy its 3 luxury amenities and 5 water toys for an exceptional yachting experience.",
    images: [
      "https://paragon-trails-yacht-images.com/gulet/bermuda-coastal-serenity-1.jpg",
      "https://paragon-trails-yacht-images.com/gulet/bermuda-coastal-serenity-2.jpg",
      "https://paragon-trails-yacht-images.com/gulet/bermuda-coastal-serenity-3.jpg",
      "https://paragon-trails-yacht-images.com/gulet/bermuda-coastal-serenity-4.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 8536,
      perWeek: 50789.2,
      currency: "BMD",
      includes: ["Indoor Lounge", "Swim Platform"],
      excludes: ["Indoor Lounge", "Swim Platform", "Heated Deck"],
    },
    safetyFeatures: ["EPIRB", "Radar", "Life Jackets"],
    accessibilityFeatures: [],
  },
];
