import { Yacht } from "@/lib/interfaces/services/rentals";

export const cartagenacolombiacaribbeanYachts: Yacht[] = [
  {
    id: "yacht-cartagena-super-0",
    name: "Caribbean Pearl",
    brand: "Sunseeker",
    model: "Sunseeker 77",
    yearBuilt: 2014,
    lengthInMeters: 68,
    beamInMeters: 13.6,
    draftInMeters: 6.8,
    cruisingSpeedKnots: 16,
    maxSpeedKnots: 25,
    fuelCapacityLiters: 34000,
    waterCapacityLiters: 20400,
    engines: ["2 x Volvo Penta 18V 1150"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 24,
      guestsOvernight: 22,
      cabins: 11,
      crew: 10,
      bathrooms: 13,
    },
    amenities: ["Heated Deck", "Outdoor Shower", "Jacuzzi", "Dining Area", "Sauna"],
    entertainment: ["Game Console"],
    waterToys: ["Paddleboards", "Jet Ski", "Kayaks", "Floating Island", "Kneeboard"],
    location: {
      city: "cartagena",
      country: "Colombia",
      region: "Caribbean",
      homePort: "Yacht Haven Grande",
    },
    availableSeasons: ["Year-Round", "Spring"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["Chef Onboard"],
    description: "Caribbean Pearl combines performance and luxury in a stunning 68m super yacht. With its professional crew of 10, you'll experience the ultimate sailing vacation.",
    images: ["https://paragon-trails-yacht-images.com/super/cartagena-caribbean-pearl-1.jpg", "https://paragon-trails-yacht-images.com/super/cartagena-caribbean-pearl-2.jpg", "https://paragon-trails-yacht-images.com/super/cartagena-caribbean-pearl-3.jpg", "https://paragon-trails-yacht-images.com/super/cartagena-caribbean-pearl-4.jpg"],
    featured: false,
    pricing: {
      perDay: 185681,
      perWeek: 1104801.95,
      currency: "COP",
      includes: ["Heated Deck", "Outdoor Shower"],
      excludes: ["Sauna"],
    },
    safetyFeatures: ["Life Rafts", "Flares", "Radar"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-cartagena-motor-1",
    name: "Golden Voyage",
    brand: "Oyster",
    model: "Oyster 52",
    yearBuilt: 2019,
    lengthInMeters: 34,
    beamInMeters: 6.8,
    draftInMeters: 3.4,
    cruisingSpeedKnots: 17,
    maxSpeedKnots: 22,
    fuelCapacityLiters: 17000,
    waterCapacityLiters: 10200,
    engines: ["2 x MAN 26V 1794"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 13,
      guestsOvernight: 6,
      cabins: 4,
      crew: 4,
      bathrooms: 6,
    },
    amenities: ["Sauna", "Wi-Fi", "Air Conditioning", "Stabilizers", "Bar", "Sun Deck"],
    entertainment: ["Onboard Cinema", "Surround Sound System", "Game Console"],
    waterToys: ["E-Foil", "Water Skis"],
    location: {
      city: "cartagena",
      country: "Colombia",
      region: "Caribbean",
      homePort: "Rodney Bay Marina",
    },
    availableSeasons: ["Fall", "Spring"],
    charterType: "private",
    crewIncluded: false,
    cateringOptions: ["Full-Service Catering"],
    description: "Golden Voyage combines performance and luxury in a stunning 34m motor yacht. With its professional crew of 4, you'll experience the ultimate sailing vacation.",
    images: ["https://paragon-trails-yacht-images.com/motor/cartagena-golden-voyage-1.jpg", "https://paragon-trails-yacht-images.com/motor/cartagena-golden-voyage-2.jpg", "https://paragon-trails-yacht-images.com/motor/cartagena-golden-voyage-3.jpg", "https://paragon-trails-yacht-images.com/motor/cartagena-golden-voyage-4.jpg"],
    featured: false,
    pricing: {
      perDay: 6445,
      perWeek: 38347.75,
      currency: "COP",
      includes: ["Sauna", "Wi-Fi", "Air Conditioning"],
      excludes: ["Sauna", "Wi-Fi", "Air Conditioning", "Stabilizers", "Bar", "Sun Deck"],
    },
    safetyFeatures: ["Life Jackets", "Navigation Lights"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-cartagena-super-2",
    name: "Sapphire Seas",
    brand: "Horizon",
    model: "Horizon 5",
    yearBuilt: 2010,
    lengthInMeters: 93,
    beamInMeters: 18.6,
    draftInMeters: 9.3,
    cruisingSpeedKnots: 18,
    maxSpeedKnots: 29,
    fuelCapacityLiters: 46500,
    waterCapacityLiters: 27900,
    engines: ["1 x Cummins 16V 1125"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 16,
      guestsOvernight: 20,
      cabins: 7,
      crew: 15,
      bathrooms: 7,
    },
    amenities: ["Swim Platform", "Sun Deck", "Kitchen", "Dining Area", "Heated Deck"],
    entertainment: ["Surround Sound System", "Streaming Services"],
    waterToys: ["Jet Ski", "Fishing Equipment"],
    location: {
      city: "cartagena",
      country: "Colombia",
      region: "Caribbean",
      homePort: "Gustavia Harbor",
    },
    availableSeasons: ["Fall", "Winter"],
    charterType: "private",
    crewIncluded: true,
    cateringOptions: ["Full-Service Catering"],
    description: "Discover the beauty of cartagena's waters aboard the elegant Sapphire Seas, a 2010 super yacht featuring spacious accommodation for 20 guests overnight or 16 for day charters.",
    images: ["https://paragon-trails-yacht-images.com/super/cartagena-sapphire-seas-1.jpg", "https://paragon-trails-yacht-images.com/super/cartagena-sapphire-seas-2.jpg", "https://paragon-trails-yacht-images.com/super/cartagena-sapphire-seas-3.jpg"],
    featured: false,
    pricing: {
      perDay: 109232,
      perWeek: 649930.4,
      currency: "COP",
      includes: ["Swim Platform", "Sun Deck"],
      excludes: ["Swim Platform", "Sun Deck", "Kitchen", "Dining Area", "Heated Deck"],
    },
    safetyFeatures: ["EPIRB", "Radar", "Fire Extinguishers"],
    accessibilityFeatures: ["Accessible Cabin"],
  },
  {
    id: "yacht-cartagena-motor-3",
    name: "Royal Wave",
    brand: "Ferretti",
    model: "Ferretti 39",
    yearBuilt: 2001,
    lengthInMeters: 38,
    beamInMeters: 7.6,
    draftInMeters: 3.8,
    cruisingSpeedKnots: 12,
    maxSpeedKnots: 22,
    fuelCapacityLiters: 19000,
    waterCapacityLiters: 11400,
    engines: ["1 x Cummins 14V 1641"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 13,
      guestsOvernight: 8,
      cabins: 4,
      crew: 3,
      bathrooms: 4,
    },
    amenities: ["Hot Tub", "BBQ Grill", "Stabilizers", "Wi-Fi"],
    entertainment: ["Projector", "Board Games", "Streaming Services"],
    waterToys: ["Windsurf", "Towable Tubes", "Wakeboard", "Paddleboards"],
    location: {
      city: "cartagena",
      country: "Colombia",
      region: "Caribbean",
      homePort: "Yacht Haven Grande",
    },
    availableSeasons: ["Fall"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["Local Cuisine Packages", "All-Inclusive"],
    description: "Discover the beauty of cartagena's waters aboard the elegant Royal Wave, a 2001 motor yacht featuring spacious accommodation for 8 guests overnight or 13 for day charters.",
    images: ["https://paragon-trails-yacht-images.com/motor/cartagena-royal-wave-1.jpg", "https://paragon-trails-yacht-images.com/motor/cartagena-royal-wave-2.jpg", "https://paragon-trails-yacht-images.com/motor/cartagena-royal-wave-3.jpg"],
    featured: false,
    pricing: {
      perDay: 9631,
      perWeek: 57304.45,
      currency: "COP",
      includes: ["Hot Tub"],
      excludes: ["Hot Tub", "BBQ Grill", "Stabilizers", "Wi-Fi"],
    },
    safetyFeatures: ["Radar", "Emergency Beacon", "Navigation Lights", "First Aid Kit", "EPIRB"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-cartagena-gulet-4",
    name: "Golden Voyage",
    brand: "Westport",
    model: "Westport 4",
    yearBuilt: 2018,
    lengthInMeters: 23,
    beamInMeters: 4.6,
    draftInMeters: 2.3,
    cruisingSpeedKnots: 11,
    maxSpeedKnots: 25,
    fuelCapacityLiters: 11500,
    waterCapacityLiters: 6900,
    engines: ["1 x Cummins 20V 1198"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 15,
      guestsOvernight: 12,
      cabins: 7,
      crew: 3,
      bathrooms: 7,
    },
    amenities: ["Sun Deck", "Indoor Lounge", "Bar", "Swim Platform"],
    entertainment: ["Projector", "Satellite TV"],
    waterToys: ["Windsurf", "Kneeboard"],
    location: {
      city: "cartagena",
      country: "Colombia",
      region: "Caribbean",
      homePort: "Yacht Haven Grande",
    },
    availableSeasons: ["Winter", "Fall"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["All-Inclusive"],
    description: "Charter the impressive Golden Voyage in cartagena and enjoy its 6 luxury amenities and 2 water toys for an exceptional yachting experience.",
    images: ["https://paragon-trails-yacht-images.com/gulet/cartagena-golden-voyage-1.jpg", "https://paragon-trails-yacht-images.com/gulet/cartagena-golden-voyage-2.jpg", "https://paragon-trails-yacht-images.com/gulet/cartagena-golden-voyage-3.jpg"],
    featured: false,
    pricing: {
      perDay: 5969,
      perWeek: 35515.549999999996,
      currency: "COP",
      includes: ["Sun Deck"],
      excludes: ["Sun Deck", "Indoor Lounge", "Bar", "Swim Platform"],
    },
    safetyFeatures: ["Fog Horn", "Emergency Steering", "First Aid Kit", "Flares"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-cartagena-sailing-5",
    name: "Pacific Explorer",
    brand: "Ferretti",
    model: "Ferretti 4",
    yearBuilt: 2004,
    lengthInMeters: 25,
    beamInMeters: 5,
    draftInMeters: 2.5,
    cruisingSpeedKnots: 15,
    maxSpeedKnots: 29,
    fuelCapacityLiters: 12500,
    waterCapacityLiters: 7500,
    engines: ["1 x MAN 10V 1000"],
    hullType: "monohull",
    yachtType: "sailing",
    capacity: {
      guestsDay: 10,
      guestsOvernight: 4,
      cabins: 3,
      crew: 1,
      bathrooms: 4,
    },
    amenities: ["Stabilizers", "Jacuzzi", "Sun Deck"],
    entertainment: ["Onboard Cinema", "Satellite TV", "Streaming Services"],
    waterToys: ["E-Foil", "Kayaks"],
    location: {
      city: "cartagena",
      country: "Colombia",
      region: "Caribbean",
      homePort: "Rodney Bay Marina",
    },
    availableSeasons: ["Summer", "Spring"],
    charterType: "shared",
    crewIncluded: false,
    cateringOptions: ["No Catering"],
    description: "Discover the beauty of cartagena's waters aboard the elegant Pacific Explorer, a 2004 sailing yacht featuring spacious accommodation for 4 guests overnight or 10 for day charters.",
    images: ["https://paragon-trails-yacht-images.com/sailing/cartagena-pacific-explorer-1.jpg", "https://paragon-trails-yacht-images.com/sailing/cartagena-pacific-explorer-2.jpg", "https://paragon-trails-yacht-images.com/sailing/cartagena-pacific-explorer-3.jpg", "https://paragon-trails-yacht-images.com/sailing/cartagena-pacific-explorer-4.jpg", "https://paragon-trails-yacht-images.com/sailing/cartagena-pacific-explorer-5.jpg"],
    featured: false,
    pricing: {
      perDay: 3691,
      perWeek: 21961.45,
      currency: "COP",
      includes: ["Stabilizers", "Jacuzzi"],
      excludes: ["Stabilizers", "Jacuzzi", "Sun Deck"],
    },
    safetyFeatures: ["Emergency Steering", "Fog Horn", "Flares", "First Aid Kit"],
    accessibilityFeatures: [],
  }
];
