import { Yacht } from "@/lib/interfaces/services/rentals";

export const dubaiunitedArabEmiratesmiddleEastYachts: Yacht[] = [
  {
    id: "yacht-dubai-gulet-0",
    name: "Adriatic Splendor",
    brand: "Benetti",
    model: "Benetti 73",
    yearBuilt: 2012,
    lengthInMeters: 16,
    beamInMeters: 3.2,
    draftInMeters: 1.6,
    cruisingSpeedKnots: 13,
    maxSpeedKnots: 21,
    fuelCapacityLiters: 8000,
    waterCapacityLiters: 4800,
    engines: ["2 x Cummins 21V 1604"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 12,
      guestsOvernight: 9,
      cabins: 4,
      crew: 4,
      bathrooms: 6,
    },
    amenities: ["Dining Area", "Indoor Lounge", "Wi-Fi", "Stabilizers", "Bar", "Tender Garage"],
    entertainment: ["Karaoke System"],
    waterToys: ["Wakeboard", "Inflatable Slide", "Scuba Diving Gear", "Kayaks"],
    location: {
      city: "dubai",
      country: "United Arab Emirates",
      region: "Middle East",
      homePort: "Marina Porto Arabia",
    },
    availableSeasons: ["Fall"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["No Catering"],
    description: "Experience luxury and comfort aboard the Adriatic Splendor, a stunning 16m gulet yacht available for charter in dubai. Perfect for day trips or extended voyages.",
    images: ["https://paragon-trails-yacht-images.com/gulet/dubai-adriatic-splendor-1.jpg", "https://paragon-trails-yacht-images.com/gulet/dubai-adriatic-splendor-2.jpg", "https://paragon-trails-yacht-images.com/gulet/dubai-adriatic-splendor-3.jpg", "https://paragon-trails-yacht-images.com/gulet/dubai-adriatic-splendor-4.jpg"],
    featured: false,
    pricing: {
      perDay: 6413,
      perWeek: 38157.35,
      currency: "AED",
      includes: ["Dining Area", "Indoor Lounge", "Wi-Fi"],
      excludes: ["Tender Garage"],
    },
    safetyFeatures: ["GPS Tracking", "Life Jackets", "Life Rafts", "First Aid Kit", "Navigation Lights"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-dubai-sailing-1",
    name: "Wave Dancer",
    brand: "Sunreef",
    model: "Sunreef 92",
    yearBuilt: 2003,
    lengthInMeters: 21,
    beamInMeters: 4.2,
    draftInMeters: 2.1,
    cruisingSpeedKnots: 11,
    maxSpeedKnots: 16,
    fuelCapacityLiters: 10500,
    waterCapacityLiters: 6300,
    engines: ["1 x MTU 24V 1734"],
    hullType: "monohull",
    yachtType: "sailing",
    capacity: {
      guestsDay: 11,
      guestsOvernight: 4,
      cabins: 2,
      crew: 1,
      bathrooms: 3,
    },
    amenities: ["Bar", "Swim Platform", "Kitchen", "BBQ Grill"],
    entertainment: ["DJ Equipment"],
    waterToys: ["Kneeboard", "E-Foil", "Towable Tubes"],
    location: {
      city: "dubai",
      country: "United Arab Emirates",
      region: "Middle East",
      homePort: "Dubai Marina",
    },
    availableSeasons: ["Year-Round", "Summer"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["Provisioning Only"],
    description: "The Wave Dancer is a magnificent sailing yacht built by Sunreef offering exceptional amenities and impeccable service for an unforgettable sailing experience in dubai.",
    images: ["https://paragon-trails-yacht-images.com/sailing/dubai-wave-dancer-1.jpg", "https://paragon-trails-yacht-images.com/sailing/dubai-wave-dancer-2.jpg", "https://paragon-trails-yacht-images.com/sailing/dubai-wave-dancer-3.jpg"],
    featured: false,
    pricing: {
      perDay: 6639,
      perWeek: 39502.049999999996,
      currency: "AED",
      includes: ["Bar"],
      excludes: ["Bar", "Swim Platform", "Kitchen", "BBQ Grill"],
    },
    safetyFeatures: ["EPIRB", "Life Rafts", "Fire Extinguishers"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-dubai-gulet-2",
    name: "Mediterranean Gem",
    brand: "Heesen",
    model: "Heesen 4",
    yearBuilt: 2002,
    lengthInMeters: 28,
    beamInMeters: 5.6,
    draftInMeters: 2.8,
    cruisingSpeedKnots: 19,
    maxSpeedKnots: 25,
    fuelCapacityLiters: 14000,
    waterCapacityLiters: 8400,
    engines: ["2 x Cummins 23V 1266"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 17,
      guestsOvernight: 14,
      cabins: 6,
      crew: 5,
      bathrooms: 7,
    },
    amenities: ["Swim Platform", "Outdoor Shower", "Jacuzzi", "Stabilizers", "Sun Deck", "Bar"],
    entertainment: ["Projector", "Streaming Services", "Media Library"],
    waterToys: ["Water Skis", "E-Foil", "Kayaks"],
    location: {
      city: "dubai",
      country: "United Arab Emirates",
      region: "Middle East",
      homePort: "Dubai Marina",
    },
    availableSeasons: ["Spring"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["All-Inclusive", "No Catering"],
    description: "Charter the impressive Mediterranean Gem in dubai and enjoy its 6 luxury amenities and 4 water toys for an exceptional yachting experience.",
    images: ["https://paragon-trails-yacht-images.com/gulet/dubai-mediterranean-gem-1.jpg", "https://paragon-trails-yacht-images.com/gulet/dubai-mediterranean-gem-2.jpg", "https://paragon-trails-yacht-images.com/gulet/dubai-mediterranean-gem-3.jpg"],
    featured: false,
    pricing: {
      perDay: 7376,
      perWeek: 43887.2,
      currency: "AED",
      includes: ["Swim Platform", "Outdoor Shower", "Jacuzzi"],
      excludes: ["Swim Platform", "Outdoor Shower", "Jacuzzi", "Stabilizers", "Sun Deck", "Bar"],
    },
    safetyFeatures: ["EPIRB", "Emergency Radio", "First Aid Kit", "GPS Tracking"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-dubai-super-3",
    name: "Serenity Now",
    brand: "Ferretti",
    model: "Ferretti 93",
    yearBuilt: 2010,
    lengthInMeters: 84,
    beamInMeters: 16.8,
    draftInMeters: 8.4,
    cruisingSpeedKnots: 17,
    maxSpeedKnots: 25,
    fuelCapacityLiters: 42000,
    waterCapacityLiters: 25200,
    engines: ["1 x MTU 21V 1567"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 18,
      guestsOvernight: 21,
      cabins: 7,
      crew: 12,
      bathrooms: 8,
    },
    amenities: ["Air Conditioning", "Bar", "Tender Garage", "Stabilizers", "Dining Area", "Jacuzzi", "Outdoor Shower"],
    entertainment: ["Bluetooth Speakers", "Media Library"],
    waterToys: ["Paddleboards", "Kneeboard", "Windsurf", "Scuba Diving Gear"],
    location: {
      city: "dubai",
      country: "United Arab Emirates",
      region: "Middle East",
      homePort: "Dubai Marina",
    },
    availableSeasons: ["Winter", "Year-Round"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["No Catering", "Picnic-Style"],
    description: "Discover the beauty of dubai's waters aboard the elegant Serenity Now, a 2010 super yacht featuring spacious accommodation for 21 guests overnight or 18 for day charters.",
    images: ["https://paragon-trails-yacht-images.com/super/dubai-serenity-now-1.jpg", "https://paragon-trails-yacht-images.com/super/dubai-serenity-now-2.jpg", "https://paragon-trails-yacht-images.com/super/dubai-serenity-now-3.jpg", "https://paragon-trails-yacht-images.com/super/dubai-serenity-now-4.jpg", "https://paragon-trails-yacht-images.com/super/dubai-serenity-now-5.jpg"],
    featured: false,
    pricing: {
      perDay: 135503,
      perWeek: 806242.85,
      currency: "AED",
      includes: ["Air Conditioning", "Bar"],
      excludes: ["Air Conditioning", "Bar", "Tender Garage", "Stabilizers", "Dining Area", "Jacuzzi", "Outdoor Shower"],
    },
    safetyFeatures: ["GPS Tracking", "Radar", "Flares"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-dubai-super-4",
    name: "Crystal Blue",
    brand: "Azimut",
    model: "Azimut 88",
    yearBuilt: 2005,
    lengthInMeters: 67,
    beamInMeters: 13.4,
    draftInMeters: 6.7,
    cruisingSpeedKnots: 18,
    maxSpeedKnots: 31,
    fuelCapacityLiters: 33500,
    waterCapacityLiters: 20100,
    engines: ["1 x Cummins 18V 1484"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 29,
      guestsOvernight: 19,
      cabins: 11,
      crew: 18,
      bathrooms: 11,
    },
    amenities: ["Indoor Lounge", "Sun Deck", "Hot Tub"],
    entertainment: ["Media Library"],
    waterToys: ["Floating Island", "Inflatable Slide", "Towable Tubes", "Fishing Equipment"],
    location: {
      city: "dubai",
      country: "United Arab Emirates",
      region: "Middle East",
      homePort: "Dubai Marina",
    },
    availableSeasons: ["Winter"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["Chef Onboard"],
    description: "Charter the impressive Crystal Blue in dubai and enjoy its 3 luxury amenities and 4 water toys for an exceptional yachting experience.",
    images: ["https://paragon-trails-yacht-images.com/super/dubai-crystal-blue-1.jpg", "https://paragon-trails-yacht-images.com/super/dubai-crystal-blue-2.jpg", "https://paragon-trails-yacht-images.com/super/dubai-crystal-blue-3.jpg", "https://paragon-trails-yacht-images.com/super/dubai-crystal-blue-4.jpg", "https://paragon-trails-yacht-images.com/super/dubai-crystal-blue-5.jpg"],
    featured: false,
    pricing: {
      perDay: 112537,
      perWeek: 669595.15,
      currency: "AED",
      includes: ["Indoor Lounge", "Sun Deck", "Hot Tub"],
      excludes: ["Indoor Lounge", "Sun Deck", "Hot Tub"],
    },
    safetyFeatures: ["Navigation Lights", "Emergency Steering", "Emergency Beacon"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-dubai-motor-5",
    name: "Atlantic Breeze",
    brand: "Riva",
    model: "Riva 47",
    yearBuilt: 2006,
    lengthInMeters: 38,
    beamInMeters: 7.6,
    draftInMeters: 3.8,
    cruisingSpeedKnots: 10,
    maxSpeedKnots: 22,
    fuelCapacityLiters: 19000,
    waterCapacityLiters: 11400,
    engines: ["1 x Volvo Penta 19V 1775"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 11,
      guestsOvernight: 9,
      cabins: 4,
      crew: 3,
      bathrooms: 5,
    },
    amenities: ["Jacuzzi", "Hot Tub", "Sauna", "Bar", "Air Conditioning"],
    entertainment: ["Karaoke System"],
    waterToys: ["Paddleboards", "Wakeboard", "Kneeboard", "Scuba Diving Gear"],
    location: {
      city: "dubai",
      country: "United Arab Emirates",
      region: "Middle East",
      homePort: "Marina Porto Arabia",
    },
    availableSeasons: ["Summer"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["Chef Onboard"],
    description: "Charter the impressive Atlantic Breeze in dubai and enjoy its 6 luxury amenities and 5 water toys for an exceptional yachting experience.",
    images: ["https://paragon-trails-yacht-images.com/motor/dubai-atlantic-breeze-1.jpg", "https://paragon-trails-yacht-images.com/motor/dubai-atlantic-breeze-2.jpg", "https://paragon-trails-yacht-images.com/motor/dubai-atlantic-breeze-3.jpg", "https://paragon-trails-yacht-images.com/motor/dubai-atlantic-breeze-4.jpg", "https://paragon-trails-yacht-images.com/motor/dubai-atlantic-breeze-5.jpg"],
    featured: false,
    pricing: {
      perDay: 12714,
      perWeek: 75648.3,
      currency: "AED",
      includes: ["Jacuzzi", "Hot Tub", "Sauna"],
      excludes: ["Air Conditioning"],
    },
    safetyFeatures: ["Navigation Lights", "Searchlight", "Emergency Radio"],
    accessibilityFeatures: [],
  }
];
