import { Yacht } from "@/lib/interfaces/services/rentals";

export const kyotojapanasiaPacificYachts: Yacht[] = [
  {
    id: "yacht-kyoto-sailing-0",
    name: "Aegean Beauty",
    brand: "Sanlorenzo",
    model: "Sanlorenzo 28",
    yearBuilt: 2002,
    lengthInMeters: 26,
    beamInMeters: 5.2,
    draftInMeters: 2.6,
    cruisingSpeedKnots: 13,
    maxSpeedKnots: 27,
    fuelCapacityLiters: 13000,
    waterCapacityLiters: 7800,
    engines: ["1 x Volvo Penta 18V 1250"],
    hullType: "monohull",
    yachtType: "sailing",
    capacity: {
      guestsDay: 9,
      guestsOvernight: 6,
      cabins: 2,
      crew: 1,
      bathrooms: 4,
    },
    amenities: ["BBQ Grill", "Hot Tub", "Bar", "Outdoor Shower", "Stabilizers"],
    entertainment: ["Media Library", "Satellite TV", "Bluetooth Speakers"],
    waterToys: ["Floating Island", "Inflatable Slide", "E-Foil"],
    location: {
      city: "Kyoto",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Marina Bay",
    },
    availableSeasons: ["Year-Round", "Spring"],
    charterType: "shared",
    crewIncluded: false,
    cateringOptions: ["Full-Service Catering", "À La Carte"],
    description:
      "Experience luxury and comfort aboard the Aegean Beauty, a stunning 26m sailing yacht available for charter in kyoto. Perfect for day trips or extended voyages.",
    images: [
      "https://paragon-trails-yacht-images.com/sailing/kyoto-aegean-beauty-1.jpg",
      "https://paragon-trails-yacht-images.com/sailing/kyoto-aegean-beauty-2.jpg",
      "https://paragon-trails-yacht-images.com/sailing/kyoto-aegean-beauty-3.jpg",
      "https://paragon-trails-yacht-images.com/sailing/kyoto-aegean-beauty-4.jpg",
      "https://paragon-trails-yacht-images.com/sailing/kyoto-aegean-beauty-5.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 3217,
      perWeek: 19141.149999999998,
      currency: "JPY",
      includes: ["BBQ Grill", "Hot Tub"],
      excludes: ["Stabilizers"],
    },
    safetyFeatures: ["EPIRB", "Flares", "Life Jackets"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-kyoto-sailing-1",
    name: "Oceanis",
    brand: "Lürssen",
    model: "Lürssen 51",
    yearBuilt: 2017,
    lengthInMeters: 16,
    beamInMeters: 3.2,
    draftInMeters: 1.6,
    cruisingSpeedKnots: 13,
    maxSpeedKnots: 23,
    fuelCapacityLiters: 8000,
    waterCapacityLiters: 4800,
    engines: ["1 x MTU 23V 1775"],
    hullType: "monohull",
    yachtType: "sailing",
    capacity: {
      guestsDay: 7,
      guestsOvernight: 6,
      cabins: 2,
      crew: 2,
      bathrooms: 2,
    },
    amenities: ["Stabilizers", "Laundry Service", "Outdoor Shower"],
    entertainment: ["Projector", "Bluetooth Speakers", "Streaming Services"],
    waterToys: ["Paddleboards", "Windsurf"],
    location: {
      city: "Kyoto",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Sydney Harbour",
    },
    availableSeasons: ["Year-Round", "Winter"],
    charterType: "weekly",
    crewIncluded: false,
    cateringOptions: ["À La Carte", "Breakfast Only"],
    description:
      "Oceanis combines performance and luxury in a stunning 16m sailing yacht. With its professional crew of 2, you'll experience the ultimate sailing vacation.",
    images: [
      "https://paragon-trails-yacht-images.com/sailing/kyoto-oceanis-1.jpg",
      "https://paragon-trails-yacht-images.com/sailing/kyoto-oceanis-2.jpg",
      "https://paragon-trails-yacht-images.com/sailing/kyoto-oceanis-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 6464,
      perWeek: 38460.799999999996,
      currency: "JPY",
      includes: ["Stabilizers", "Laundry Service", "Outdoor Shower"],
      excludes: ["Stabilizers", "Laundry Service", "Outdoor Shower"],
    },
    safetyFeatures: ["Searchlight", "GPS Tracking", "Fire Extinguishers"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-kyoto-catamaran-2",
    name: "Ruby Tides",
    brand: "Benetti",
    model: "Benetti 78",
    yearBuilt: 2010,
    lengthInMeters: 24,
    beamInMeters: 4.8,
    draftInMeters: 2.4,
    cruisingSpeedKnots: 10,
    maxSpeedKnots: 15,
    fuelCapacityLiters: 12000,
    waterCapacityLiters: 7200,
    engines: ["1 x Caterpillar 20V 1899"],
    hullType: "catamaran",
    yachtType: "catamaran",
    capacity: {
      guestsDay: 14,
      guestsOvernight: 11,
      cabins: 4,
      crew: 3,
      bathrooms: 6,
    },
    amenities: ["Sun Deck", "Heated Deck", "Dining Area"],
    entertainment: ["Projector", "Board Games", "Surround Sound System"],
    waterToys: [
      "Scuba Diving Gear",
      "Kneeboard",
      "Snorkeling Gear",
      "Towable Tubes",
    ],
    location: {
      city: "Kyoto",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Marina Bay",
    },
    availableSeasons: ["Fall", "Year-Round"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["Self-Catering", "Full-Service Catering"],
    description:
      "Discover the beauty of kyoto's waters aboard the elegant Ruby Tides, a 2010 catamaran yacht featuring spacious accommodation for 11 guests overnight or 14 for day charters.",
    images: [
      "https://paragon-trails-yacht-images.com/catamaran/kyoto-ruby-tides-1.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/kyoto-ruby-tides-2.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/kyoto-ruby-tides-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 11036,
      perWeek: 65664.2,
      currency: "JPY",
      includes: ["Sun Deck", "Heated Deck"],
      excludes: ["Dining Area"],
    },
    safetyFeatures: [
      "Life Rafts",
      "Emergency Beacon",
      "GPS Tracking",
      "First Aid Kit",
    ],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-kyoto-motor-3",
    name: "Azure Dreams",
    brand: "Wally",
    model: "Wally 97",
    yearBuilt: 2006,
    lengthInMeters: 32,
    beamInMeters: 6.4,
    draftInMeters: 3.2,
    cruisingSpeedKnots: 10,
    maxSpeedKnots: 19,
    fuelCapacityLiters: 16000,
    waterCapacityLiters: 9600,
    engines: ["1 x MAN 27V 1366"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 12,
      guestsOvernight: 6,
      cabins: 4,
      crew: 4,
      bathrooms: 4,
    },
    amenities: ["Bar", "Tender Garage", "Heated Deck", "Air Conditioning"],
    entertainment: ["Surround Sound System"],
    waterToys: [
      "Paddleboards",
      "Scuba Diving Gear",
      "Seabob",
      "Towable Tubes",
      "Water Skis",
    ],
    location: {
      city: "Kyoto",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Sentosa Cove",
    },
    availableSeasons: ["Summer", "Fall", "Winter"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["Breakfast Only", "Local Cuisine Packages"],
    description:
      "The Azure Dreams is a magnificent motor yacht built by Wally offering exceptional amenities and impeccable service for an unforgettable sailing experience in kyoto.",
    images: [
      "https://paragon-trails-yacht-images.com/motor/kyoto-azure-dreams-1.jpg",
      "https://paragon-trails-yacht-images.com/motor/kyoto-azure-dreams-2.jpg",
      "https://paragon-trails-yacht-images.com/motor/kyoto-azure-dreams-3.jpg",
      "https://paragon-trails-yacht-images.com/motor/kyoto-azure-dreams-4.jpg",
    ],
    featured: true,
    pricing: {
      perDay: 11243,
      perWeek: 66895.84999999999,
      currency: "JPY",
      includes: ["Bar", "Tender Garage"],
      excludes: ["Air Conditioning"],
    },
    safetyFeatures: ["Emergency Beacon", "Fog Horn", "Radar"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-kyoto-gulet-4",
    name: "Infinity Seas",
    brand: "Swan",
    model: "Swan 28",
    yearBuilt: 2006,
    lengthInMeters: 15,
    beamInMeters: 3,
    draftInMeters: 1.5,
    cruisingSpeedKnots: 16,
    maxSpeedKnots: 21,
    fuelCapacityLiters: 7500,
    waterCapacityLiters: 4500,
    engines: ["2 x Cummins 13V 1791"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 13,
      guestsOvernight: 15,
      cabins: 6,
      crew: 4,
      bathrooms: 6,
    },
    amenities: [
      "Heated Deck",
      "Jacuzzi",
      "Indoor Lounge",
      "Laundry Service",
      "Kitchen",
    ],
    entertainment: ["Onboard Cinema"],
    waterToys: ["Water Skis", "Paddleboards", "E-Foil", "Floating Island"],
    location: {
      city: "Kyoto",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Abell Point Marina",
    },
    availableSeasons: ["Fall", "Summer"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["À La Carte"],
    description:
      "Charter the impressive Infinity Seas in kyoto and enjoy its 6 luxury amenities and 4 water toys for an exceptional yachting experience.",
    images: [
      "https://paragon-trails-yacht-images.com/gulet/kyoto-infinity-seas-1.jpg",
      "https://paragon-trails-yacht-images.com/gulet/kyoto-infinity-seas-2.jpg",
      "https://paragon-trails-yacht-images.com/gulet/kyoto-infinity-seas-3.jpg",
      "https://paragon-trails-yacht-images.com/gulet/kyoto-infinity-seas-4.jpg",
      "https://paragon-trails-yacht-images.com/gulet/kyoto-infinity-seas-5.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 3930,
      perWeek: 23383.5,
      currency: "JPY",
      includes: ["Heated Deck"],
      excludes: [
        "Heated Deck",
        "Jacuzzi",
        "Indoor Lounge",
        "Laundry Service",
        "Kitchen",
      ],
    },
    safetyFeatures: [
      "Searchlight",
      "First Aid Kit",
      "EPIRB",
      "Emergency Radio",
      "Fire Extinguishers",
    ],
    accessibilityFeatures: [],
  },
];
