import { Yacht } from "@/lib/interfaces/services/rentals";

export const losAngelesunitedStateswestCoastUsaYachts: Yacht[] = [
  {
    id: "yacht-los-angeles-gulet-0",
    name: "Ruby Tides",
    brand: "Perini Navi",
    model: "Perini Navi 36",
    yearBuilt: 2001,
    lengthInMeters: 29,
    beamInMeters: 5.8,
    draftInMeters: 2.9,
    cruisingSpeedKnots: 13,
    maxSpeedKnots: 21,
    fuelCapacityLiters: 14500,
    waterCapacityLiters: 8700,
    engines: ["1 x Caterpillar 27V 1518"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 18,
      guestsOvernight: 13,
      cabins: 6,
      crew: 3,
      bathrooms: 7,
    },
    amenities: ["Indoor Lounge", "Hot Tub", "Bar", "Outdoor Shower"],
    entertainment: ["Satellite TV", "Surround Sound System", "Karaoke System"],
    waterToys: ["Towable Tubes", "Floating Island", "Water Skis"],
    location: {
      city: "los-angeles",
      country: "United States",
      region: "West Coast USA",
      homePort: "Marina del Rey",
    },
    availableSeasons: ["Spring"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["Provisioning Only"],
    description: "Charter the impressive Ruby Tides in los-angeles and enjoy its 4 luxury amenities and 5 water toys for an exceptional yachting experience.",
    images: ["https://paragon-trails-yacht-images.com/gulet/los-angeles-ruby-tides-1.jpg", "https://paragon-trails-yacht-images.com/gulet/los-angeles-ruby-tides-2.jpg", "https://paragon-trails-yacht-images.com/gulet/los-angeles-ruby-tides-3.jpg", "https://paragon-trails-yacht-images.com/gulet/los-angeles-ruby-tides-4.jpg"],
    featured: true,
    pricing: {
      perDay: 8607,
      perWeek: 51211.65,
      currency: "USD",
      includes: ["Indoor Lounge", "Hot Tub"],
      excludes: ["Indoor Lounge", "Hot Tub", "Bar", "Outdoor Shower"],
    },
    safetyFeatures: ["Searchlight", "Fog Horn", "EPIRB", "Life Rafts"],
    accessibilityFeatures: ["Elevator"],
  },
  {
    id: "yacht-los-angeles-catamaran-1",
    name: "Ruby Tides",
    brand: "Amels",
    model: "Amels 68",
    yearBuilt: 2011,
    lengthInMeters: 22,
    beamInMeters: 4.4,
    draftInMeters: 2.2,
    cruisingSpeedKnots: 17,
    maxSpeedKnots: 27,
    fuelCapacityLiters: 11000,
    waterCapacityLiters: 6600,
    engines: ["1 x Cummins 24V 1250"],
    hullType: "catamaran",
    yachtType: "catamaran",
    capacity: {
      guestsDay: 13,
      guestsOvernight: 9,
      cabins: 4,
      crew: 2,
      bathrooms: 5,
    },
    amenities: ["Sun Deck", "Hot Tub", "Stabilizers", "BBQ Grill", "Heated Deck", "Kitchen"],
    entertainment: ["Streaming Services", "Media Library"],
    waterToys: ["Paddleboards", "Water Skis"],
    location: {
      city: "los-angeles",
      country: "United States",
      region: "West Coast USA",
      homePort: "Newport",
    },
    availableSeasons: ["Year-Round", "Fall", "Spring"],
    charterType: "private",
    crewIncluded: false,
    cateringOptions: ["Local Cuisine Packages", "BBQ Onboard"],
    description: "Charter the impressive Ruby Tides in los-angeles and enjoy its 6 luxury amenities and 2 water toys for an exceptional yachting experience.",
    images: ["https://paragon-trails-yacht-images.com/catamaran/los-angeles-ruby-tides-1.jpg", "https://paragon-trails-yacht-images.com/catamaran/los-angeles-ruby-tides-2.jpg", "https://paragon-trails-yacht-images.com/catamaran/los-angeles-ruby-tides-3.jpg", "https://paragon-trails-yacht-images.com/catamaran/los-angeles-ruby-tides-4.jpg", "https://paragon-trails-yacht-images.com/catamaran/los-angeles-ruby-tides-5.jpg"],
    featured: false,
    pricing: {
      perDay: 11868,
      perWeek: 70614.59999999999,
      currency: "USD",
      includes: ["Sun Deck", "Hot Tub", "Stabilizers"],
      excludes: ["Sun Deck", "Hot Tub", "Stabilizers", "BBQ Grill", "Heated Deck", "Kitchen"],
    },
    safetyFeatures: ["Fog Horn", "Flares", "Life Rafts", "Fire Extinguishers"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-los-angeles-catamaran-2",
    name: "Coastal Serenity",
    brand: "Westport",
    model: "Westport 33",
    yearBuilt: 2013,
    lengthInMeters: 13,
    beamInMeters: 2.6,
    draftInMeters: 1.3,
    cruisingSpeedKnots: 14,
    maxSpeedKnots: 22,
    fuelCapacityLiters: 6500,
    waterCapacityLiters: 3900,
    engines: ["1 x Volvo Penta 14V 1691"],
    hullType: "catamaran",
    yachtType: "catamaran",
    capacity: {
      guestsDay: 13,
      guestsOvernight: 9,
      cabins: 5,
      crew: 3,
      bathrooms: 6,
    },
    amenities: ["Outdoor Shower", "Stabilizers", "Indoor Lounge"],
    entertainment: ["Board Games"],
    waterToys: ["Inflatable Slide", "Kneeboard", "Scuba Diving Gear", "Fishing Equipment", "Snorkeling Gear"],
    location: {
      city: "los-angeles",
      country: "United States",
      region: "West Coast USA",
      homePort: "Newport",
    },
    availableSeasons: ["Spring", "Winter"],
    charterType: "private",
    crewIncluded: false,
    cateringOptions: ["All-Inclusive"],
    description: "The Coastal Serenity is a magnificent catamaran yacht built by Westport offering exceptional amenities and impeccable service for an unforgettable sailing experience in los-angeles.",
    images: ["https://paragon-trails-yacht-images.com/catamaran/los-angeles-coastal-serenity-1.jpg", "https://paragon-trails-yacht-images.com/catamaran/los-angeles-coastal-serenity-2.jpg", "https://paragon-trails-yacht-images.com/catamaran/los-angeles-coastal-serenity-3.jpg", "https://paragon-trails-yacht-images.com/catamaran/los-angeles-coastal-serenity-4.jpg", "https://paragon-trails-yacht-images.com/catamaran/los-angeles-coastal-serenity-5.jpg"],
    featured: false,
    pricing: {
      perDay: 8027,
      perWeek: 47760.65,
      currency: "USD",
      includes: ["Outdoor Shower", "Stabilizers"],
      excludes: ["Outdoor Shower", "Stabilizers", "Indoor Lounge"],
    },
    safetyFeatures: ["Fog Horn", "EPIRB", "Life Rafts", "Life Jackets"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-los-angeles-mega-3",
    name: "Indigo Seas",
    brand: "Lagoon",
    model: "Lagoon 81",
    yearBuilt: 2000,
    lengthInMeters: 54,
    beamInMeters: 10.8,
    draftInMeters: 5.4,
    cruisingSpeedKnots: 13,
    maxSpeedKnots: 24,
    fuelCapacityLiters: 27000,
    waterCapacityLiters: 16200,
    engines: ["2 x MAN 8V 1598"],
    hullType: "monohull",
    yachtType: "mega",
    capacity: {
      guestsDay: 19,
      guestsOvernight: 9,
      cabins: 5,
      crew: 7,
      bathrooms: 7,
    },
    amenities: ["BBQ Grill", "Outdoor Shower", "Swim Platform", "Kitchen", "Sun Deck"],
    entertainment: ["Board Games"],
    waterToys: ["Paddleboards", "Water Skis"],
    location: {
      city: "los-angeles",
      country: "United States",
      region: "West Coast USA",
      homePort: "Fort Lauderdale",
    },
    availableSeasons: ["Spring"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["Local Cuisine Packages"],
    description: "Charter the impressive Indigo Seas in los-angeles and enjoy its 5 luxury amenities and 2 water toys for an exceptional yachting experience.",
    images: ["https://paragon-trails-yacht-images.com/mega/los-angeles-indigo-seas-1.jpg", "https://paragon-trails-yacht-images.com/mega/los-angeles-indigo-seas-2.jpg", "https://paragon-trails-yacht-images.com/mega/los-angeles-indigo-seas-3.jpg"],
    featured: false,
    pricing: {
      perDay: 27255,
      perWeek: 162167.25,
      currency: "USD",
      includes: ["BBQ Grill"],
      excludes: ["Sun Deck"],
    },
    safetyFeatures: ["Life Jackets", "Emergency Beacon", "Radar"],
    accessibilityFeatures: [],
  }
];
