import { Yacht } from "@/lib/interfaces/services/rentals";

export const maltamaltamediterraneanYachts: Yacht[] = [
  {
    id: "yacht-malta-super-0",
    name: "Sovereign Waters",
    brand: "Westport",
    model: "Westport 2",
    yearBuilt: 2015,
    lengthInMeters: 82,
    beamInMeters: 16.4,
    draftInMeters: 8.2,
    cruisingSpeedKnots: 18,
    maxSpeedKnots: 29,
    fuelCapacityLiters: 41000,
    waterCapacityLiters: 24600,
    engines: ["1 x MTU 16V 1752"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 27,
      guestsOvernight: 13,
      cabins: 11,
      crew: 12,
      bathrooms: 11,
    },
    amenities: ["Swim Platform", "Kitchen", "Sun Deck", "Indoor Lounge", "Dining Area"],
    entertainment: ["Onboard Cinema", "Game Console"],
    waterToys: ["Seabob", "Jet Ski", "Inflatable Slide"],
    location: {
      city: "malta",
      country: "Malta",
      region: "Mediterranean",
      homePort: "Marina di Portofino",
    },
    availableSeasons: ["Year-Round", "Spring", "Winter"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["Chef Onboard"],
    description: "Experience luxury and comfort aboard the Sovereign Waters, a stunning 82m super yacht available for charter in malta. Perfect for day trips or extended voyages.",
    images: ["https://paragon-trails-yacht-images.com/super/malta-sovereign-waters-1.jpg", "https://paragon-trails-yacht-images.com/super/malta-sovereign-waters-2.jpg", "https://paragon-trails-yacht-images.com/super/malta-sovereign-waters-3.jpg", "https://paragon-trails-yacht-images.com/super/malta-sovereign-waters-4.jpg", "https://paragon-trails-yacht-images.com/super/malta-sovereign-waters-5.jpg"],
    featured: true,
    pricing: {
      perDay: 177780,
      perWeek: 1057791,
      currency: "EUR",
      includes: ["Swim Platform", "Kitchen", "Sun Deck"],
      excludes: ["Dining Area"],
    },
    safetyFeatures: ["Searchlight", "Navigation Lights", "EPIRB"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-malta-super-1",
    name: "Indigo Seas",
    brand: "Sunseeker",
    model: "Sunseeker 53",
    yearBuilt: 2017,
    lengthInMeters: 76,
    beamInMeters: 15.2,
    draftInMeters: 7.6,
    cruisingSpeedKnots: 18,
    maxSpeedKnots: 30,
    fuelCapacityLiters: 38000,
    waterCapacityLiters: 22800,
    engines: ["1 x MTU 21V 1596"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 17,
      guestsOvernight: 17,
      cabins: 11,
      crew: 13,
      bathrooms: 12,
    },
    amenities: ["Sauna", "Laundry Service", "Heated Deck", "Outdoor Shower", "Kitchen", "Bar"],
    entertainment: ["Game Console"],
    waterToys: ["Water Skis", "E-Foil", "Towable Tubes"],
    location: {
      city: "malta",
      country: "Malta",
      region: "Mediterranean",
      homePort: "Antibes",
    },
    availableSeasons: ["Winter"],
    charterType: "private",
    crewIncluded: true,
    cateringOptions: ["À La Carte"],
    description: "Charter the impressive Indigo Seas in malta and enjoy its 7 luxury amenities and 3 water toys for an exceptional yachting experience.",
    images: ["https://paragon-trails-yacht-images.com/super/malta-indigo-seas-1.jpg", "https://paragon-trails-yacht-images.com/super/malta-indigo-seas-2.jpg", "https://paragon-trails-yacht-images.com/super/malta-indigo-seas-3.jpg", "https://paragon-trails-yacht-images.com/super/malta-indigo-seas-4.jpg"],
    featured: true,
    pricing: {
      perDay: 78552,
      perWeek: 467384.39999999997,
      currency: "EUR",
      includes: ["Sauna", "Laundry Service", "Heated Deck"],
      excludes: ["Sauna", "Laundry Service", "Heated Deck", "Outdoor Shower", "Kitchen", "Bar"],
    },
    safetyFeatures: ["EPIRB", "Emergency Steering", "Searchlight"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-malta-sailing-2",
    name: "Serenity Now",
    brand: "Feadship",
    model: "Feadship 79",
    yearBuilt: 2008,
    lengthInMeters: 25,
    beamInMeters: 5,
    draftInMeters: 2.5,
    cruisingSpeedKnots: 10,
    maxSpeedKnots: 20,
    fuelCapacityLiters: 12500,
    waterCapacityLiters: 7500,
    engines: ["1 x MTU 19V 1242"],
    hullType: "monohull",
    yachtType: "sailing",
    capacity: {
      guestsDay: 8,
      guestsOvernight: 7,
      cabins: 3,
      crew: 2,
      bathrooms: 5,
    },
    amenities: ["Bar", "Swim Platform"],
    entertainment: ["Karaoke System", "Game Console", "Onboard Cinema"],
    waterToys: ["Kayaks", "Kneeboard", "Inflatable Slide", "E-Foil"],
    location: {
      city: "malta",
      country: "Malta",
      region: "Mediterranean",
      homePort: "Porto Cervo",
    },
    availableSeasons: ["Summer", "Year-Round"],
    charterType: "private",
    crewIncluded: true,
    cateringOptions: ["Full-Service Catering"],
    description: "Discover the beauty of malta's waters aboard the elegant Serenity Now, a 2008 sailing yacht featuring spacious accommodation for 7 guests overnight or 8 for day charters.",
    images: ["https://paragon-trails-yacht-images.com/sailing/malta-serenity-now-1.jpg", "https://paragon-trails-yacht-images.com/sailing/malta-serenity-now-2.jpg", "https://paragon-trails-yacht-images.com/sailing/malta-serenity-now-3.jpg", "https://paragon-trails-yacht-images.com/sailing/malta-serenity-now-4.jpg", "https://paragon-trails-yacht-images.com/sailing/malta-serenity-now-5.jpg"],
    featured: false,
    pricing: {
      perDay: 3435,
      perWeek: 20438.25,
      currency: "EUR",
      includes: ["Bar", "Swim Platform"],
      excludes: ["Swim Platform"],
    },
    safetyFeatures: ["GPS Tracking", "Searchlight"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-malta-motor-3",
    name: "Caribbean Pearl",
    brand: "Oyster",
    model: "Oyster 83",
    yearBuilt: 2009,
    lengthInMeters: 21,
    beamInMeters: 4.2,
    draftInMeters: 2.1,
    cruisingSpeedKnots: 10,
    maxSpeedKnots: 21,
    fuelCapacityLiters: 10500,
    waterCapacityLiters: 6300,
    engines: ["1 x Volvo Penta 16V 1613"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 11,
      guestsOvernight: 9,
      cabins: 4,
      crew: 4,
      bathrooms: 4,
    },
    amenities: ["Wi-Fi", "Kitchen", "Outdoor Shower", "Stabilizers"],
    entertainment: ["Projector", "Karaoke System"],
    waterToys: ["E-Foil", "Kneeboard"],
    location: {
      city: "malta",
      country: "Malta",
      region: "Mediterranean",
      homePort: "Port Vauban",
    },
    availableSeasons: ["Year-Round", "Fall"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["No Catering", "Full-Service Catering"],
    description: "Discover the beauty of malta's waters aboard the elegant Caribbean Pearl, a 2009 motor yacht featuring spacious accommodation for 9 guests overnight or 11 for day charters.",
    images: ["https://paragon-trails-yacht-images.com/motor/malta-caribbean-pearl-1.jpg", "https://paragon-trails-yacht-images.com/motor/malta-caribbean-pearl-2.jpg", "https://paragon-trails-yacht-images.com/motor/malta-caribbean-pearl-3.jpg", "https://paragon-trails-yacht-images.com/motor/malta-caribbean-pearl-4.jpg"],
    featured: false,
    pricing: {
      perDay: 7429,
      perWeek: 44202.549999999996,
      currency: "EUR",
      includes: ["Wi-Fi", "Kitchen"],
      excludes: ["Wi-Fi", "Kitchen", "Outdoor Shower", "Stabilizers"],
    },
    safetyFeatures: ["Searchlight", "First Aid Kit"],
    accessibilityFeatures: [],
  }
];
