import { Yacht } from "@/lib/interfaces/services/rentals";

export const parisfrancenorthernEuropeYachts: Yacht[] = [
  {
    id: "yacht-paris-motor-0",
    name: "Sovereign Waters",
    brand: "Fountaine Pajot",
    model: "Fountaine Pajot 30",
    yearBuilt: 2008,
    lengthInMeters: 37,
    beamInMeters: 7.4,
    draftInMeters: 3.7,
    cruisingSpeedKnots: 14,
    maxSpeedKnots: 20,
    fuelCapacityLiters: 18500,
    waterCapacityLiters: 11100,
    engines: ["1 x MAN 22V 1052"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 12,
      guestsOvernight: 8,
      cabins: 4,
      crew: 2,
      bathrooms: 4,
    },
    amenities: ["Jacuzzi", "BBQ Grill", "Kitchen", "Tender Garage"],
    entertainment: ["Onboard Cinema"],
    waterToys: ["Fishing Equipment", "Seabob", "Jet Ski", "Scuba Diving Gear"],
    location: {
      city: "Paris",
      country: "France",
      region: "Northern Europe",
      homePort: "Port of Amsterdam",
    },
    availableSeasons: ["Winter", "Spring", "Summer"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["Self-Catering"],
    description:
      "The Sovereign Waters is a magnificent motor yacht built by Fountaine Pajot offering exceptional amenities and impeccable service for an unforgettable sailing experience in paris.",
    images: [
      "https://paragon-trails-yacht-images.com/motor/paris-sovereign-waters-1.jpg",
      "https://paragon-trails-yacht-images.com/motor/paris-sovereign-waters-2.jpg",
      "https://paragon-trails-yacht-images.com/motor/paris-sovereign-waters-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 6898,
      perWeek: 41043.1,
      currency: "EUR",
      includes: ["Jacuzzi"],
      excludes: ["Tender Garage"],
    },
    safetyFeatures: ["Navigation Lights", "Flares"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-paris-mega-1",
    name: "Aquamarine",
    brand: "Wally",
    model: "Wally 64",
    yearBuilt: 2014,
    lengthInMeters: 44,
    beamInMeters: 8.8,
    draftInMeters: 4.4,
    cruisingSpeedKnots: 10,
    maxSpeedKnots: 16,
    fuelCapacityLiters: 22000,
    waterCapacityLiters: 13200,
    engines: ["1 x MAN 26V 1638"],
    hullType: "monohull",
    yachtType: "mega",
    capacity: {
      guestsDay: 13,
      guestsOvernight: 8,
      cabins: 6,
      crew: 6,
      bathrooms: 6,
    },
    amenities: ["Bar", "Hot Tub", "Sauna", "Sun Deck"],
    entertainment: ["DJ Equipment", "Game Console"],
    waterToys: ["Fishing Equipment", "Seabob"],
    location: {
      city: "Paris",
      country: "France",
      region: "Northern Europe",
      homePort: "Stockholm Marina",
    },
    availableSeasons: ["Winter"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["BBQ Onboard"],
    description:
      "The Aquamarine is a magnificent mega yacht built by Wally offering exceptional amenities and impeccable service for an unforgettable sailing experience in paris.",
    images: [
      "https://paragon-trails-yacht-images.com/mega/paris-aquamarine-1.jpg",
      "https://paragon-trails-yacht-images.com/mega/paris-aquamarine-2.jpg",
      "https://paragon-trails-yacht-images.com/mega/paris-aquamarine-3.jpg",
      "https://paragon-trails-yacht-images.com/mega/paris-aquamarine-4.jpg",
      "https://paragon-trails-yacht-images.com/mega/paris-aquamarine-5.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 36364,
      perWeek: 216365.8,
      currency: "EUR",
      includes: ["Bar"],
      excludes: ["Bar", "Hot Tub", "Sauna", "Sun Deck"],
    },
    safetyFeatures: [
      "Life Rafts",
      "Emergency Beacon",
      "Fire Extinguishers",
      "Fog Horn",
      "First Aid Kit",
    ],
    accessibilityFeatures: ["Wheelchair Ramp", "Accessible Cabin"],
  },
  {
    id: "yacht-paris-gulet-2",
    name: "Indigo Seas",
    brand: "Sunseeker",
    model: "Sunseeker 78",
    yearBuilt: 2000,
    lengthInMeters: 33,
    beamInMeters: 6.6,
    draftInMeters: 3.3,
    cruisingSpeedKnots: 14,
    maxSpeedKnots: 27,
    fuelCapacityLiters: 16500,
    waterCapacityLiters: 9900,
    engines: ["2 x Cummins 15V 1005"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 11,
      guestsOvernight: 14,
      cabins: 6,
      crew: 4,
      bathrooms: 8,
    },
    amenities: ["Stabilizers", "Bar", "Air Conditioning"],
    entertainment: ["Onboard Cinema", "Projector"],
    waterToys: ["Towable Tubes", "Fishing Equipment"],
    location: {
      city: "Paris",
      country: "France",
      region: "Northern Europe",
      homePort: "Stockholm Marina",
    },
    availableSeasons: ["Winter"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["BBQ Onboard"],
    description:
      "Discover the beauty of paris's waters aboard the elegant Indigo Seas, a 2000 gulet yacht featuring spacious accommodation for 14 guests overnight or 11 for day charters.",
    images: [
      "https://paragon-trails-yacht-images.com/gulet/paris-indigo-seas-1.jpg",
      "https://paragon-trails-yacht-images.com/gulet/paris-indigo-seas-2.jpg",
      "https://paragon-trails-yacht-images.com/gulet/paris-indigo-seas-3.jpg",
      "https://paragon-trails-yacht-images.com/gulet/paris-indigo-seas-4.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 7692,
      perWeek: 45767.4,
      currency: "EUR",
      includes: ["Stabilizers", "Bar", "Air Conditioning"],
      excludes: ["Air Conditioning"],
    },
    safetyFeatures: [
      "Emergency Beacon",
      "Fog Horn",
      "Life Rafts",
      "Life Jackets",
    ],
    accessibilityFeatures: ["Accessible Cabin"],
  },
  {
    id: "yacht-paris-catamaran-3",
    name: "Adriatic Queen",
    brand: "Westport",
    model: "Westport 29",
    yearBuilt: 2010,
    lengthInMeters: 16,
    beamInMeters: 3.2,
    draftInMeters: 1.6,
    cruisingSpeedKnots: 13,
    maxSpeedKnots: 27,
    fuelCapacityLiters: 8000,
    waterCapacityLiters: 4800,
    engines: ["1 x MAN 24V 1676"],
    hullType: "catamaran",
    yachtType: "catamaran",
    capacity: {
      guestsDay: 15,
      guestsOvernight: 8,
      cabins: 3,
      crew: 3,
      bathrooms: 4,
    },
    amenities: ["Bar", "Heated Deck", "Sun Deck", "Stabilizers"],
    entertainment: ["Karaoke System", "Board Games"],
    waterToys: ["Kayaks", "Paddleboards"],
    location: {
      city: "Paris",
      country: "France",
      region: "Northern Europe",
      homePort: "Port of Amsterdam",
    },
    availableSeasons: ["Spring", "Year-Round"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["No Catering"],
    description:
      "Adriatic Queen combines performance and luxury in a stunning 16m catamaran yacht. With its professional crew of 3, you'll experience the ultimate sailing vacation.",
    images: [
      "https://paragon-trails-yacht-images.com/catamaran/paris-adriatic-queen-1.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/paris-adriatic-queen-2.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/paris-adriatic-queen-3.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/paris-adriatic-queen-4.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/paris-adriatic-queen-5.jpg",
    ],
    featured: true,
    pricing: {
      perDay: 7804,
      perWeek: 46433.799999999996,
      currency: "EUR",
      includes: ["Bar"],
      excludes: ["Bar", "Heated Deck", "Sun Deck", "Stabilizers"],
    },
    safetyFeatures: [
      "Fog Horn",
      "Life Rafts",
      "Searchlight",
      "Emergency Beacon",
    ],
    accessibilityFeatures: [],
  },
];
