import { Yacht } from "@/lib/interfaces/services/rentals";

export const stPetersburgrussianorthernEuropeYachts: Yacht[] = [
  {
    id: "yacht-st-petersburg-super-0",
    name: "Baltic Star",
    brand: "Swan",
    model: "Swan 74",
    yearBuilt: 2015,
    lengthInMeters: 97,
    beamInMeters: 19.4,
    draftInMeters: 9.7,
    cruisingSpeedKnots: 19,
    maxSpeedKnots: 29,
    fuelCapacityLiters: 48500,
    waterCapacityLiters: 29100,
    engines: ["1 x MAN 19V 1643"],
    hullType: "monohull",
    yachtType: "super",
    capacity: {
      guestsDay: 21,
      guestsOvernight: 21,
      cabins: 9,
      crew: 17,
      bathrooms: 11,
    },
    amenities: [
      "Swim Platform",
      "Tender Garage",
      "Dining Area",
      "Indoor Lounge",
      "Heated Deck",
      "BBQ Grill",
    ],
    entertainment: ["Media Library"],
    waterToys: [
      "Towable Tubes",
      "Kayaks",
      "Wakeboard",
      "Windsurf",
      "Inflatable Slide",
    ],
    location: {
      city: "St-petersburg",
      country: "Russia",
      region: "Northern Europe",
      homePort: "Stockholm Marina",
    },
    availableSeasons: ["Year-Round", "Summer"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["Self-Catering"],
    description:
      "The Baltic Star is a magnificent super yacht built by Swan offering exceptional amenities and impeccable service for an unforgettable sailing experience in st-petersburg.",
    images: [
      "https://paragon-trails-yacht-images.com/super/st-petersburg-baltic-star-1.jpg",
      "https://paragon-trails-yacht-images.com/super/st-petersburg-baltic-star-2.jpg",
      "https://paragon-trails-yacht-images.com/super/st-petersburg-baltic-star-3.jpg",
      "https://paragon-trails-yacht-images.com/super/st-petersburg-baltic-star-4.jpg",
    ],
    featured: true,
    pricing: {
      perDay: 181208,
      perWeek: 1078187.5999999999,
      currency: "RUB",
      includes: ["Swim Platform", "Tender Garage", "Dining Area"],
      excludes: [
        "Swim Platform",
        "Tender Garage",
        "Dining Area",
        "Indoor Lounge",
        "Heated Deck",
        "BBQ Grill",
      ],
    },
    safetyFeatures: [
      "Emergency Radio",
      "Fog Horn",
      "EPIRB",
      "Searchlight",
      "Navigation Lights",
    ],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-st-petersburg-motor-1",
    name: "Oceanis",
    brand: "Heesen",
    model: "Heesen 65",
    yearBuilt: 2012,
    lengthInMeters: 35,
    beamInMeters: 7,
    draftInMeters: 3.5,
    cruisingSpeedKnots: 14,
    maxSpeedKnots: 20,
    fuelCapacityLiters: 17500,
    waterCapacityLiters: 10500,
    engines: ["2 x MAN 24V 1936"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 11,
      guestsOvernight: 6,
      cabins: 3,
      crew: 2,
      bathrooms: 5,
    },
    amenities: ["Indoor Lounge", "Heated Deck", "Dining Area"],
    entertainment: ["Surround Sound System", "Projector"],
    waterToys: ["Towable Tubes", "E-Foil", "Floating Island", "Paddleboards"],
    location: {
      city: "St-petersburg",
      country: "Russia",
      region: "Northern Europe",
      homePort: "Stockholm Marina",
    },
    availableSeasons: ["Fall", "Year-Round"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["Full-Service Catering", "Local Cuisine Packages"],
    description:
      "Experience luxury and comfort aboard the Oceanis, a stunning 35m motor yacht available for charter in st-petersburg. Perfect for day trips or extended voyages.",
    images: [
      "https://paragon-trails-yacht-images.com/motor/st-petersburg-oceanis-1.jpg",
      "https://paragon-trails-yacht-images.com/motor/st-petersburg-oceanis-2.jpg",
      "https://paragon-trails-yacht-images.com/motor/st-petersburg-oceanis-3.jpg",
    ],
    featured: true,
    pricing: {
      perDay: 12401,
      perWeek: 73785.95,
      currency: "RUB",
      includes: ["Indoor Lounge", "Heated Deck", "Dining Area"],
      excludes: ["Dining Area"],
    },
    safetyFeatures: ["First Aid Kit", "Life Rafts", "Fire Extinguishers"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-st-petersburg-sailing-2",
    name: "Adriatic Splendor",
    brand: "Baglietto",
    model: "Baglietto 43",
    yearBuilt: 2002,
    lengthInMeters: 18,
    beamInMeters: 3.6,
    draftInMeters: 1.8,
    cruisingSpeedKnots: 17,
    maxSpeedKnots: 28,
    fuelCapacityLiters: 9000,
    waterCapacityLiters: 5400,
    engines: ["1 x Volvo Penta 26V 1898"],
    hullType: "monohull",
    yachtType: "sailing",
    capacity: {
      guestsDay: 9,
      guestsOvernight: 4,
      cabins: 2,
      crew: 2,
      bathrooms: 2,
    },
    amenities: [
      "Wi-Fi",
      "Heated Deck",
      "Outdoor Shower",
      "Swim Platform",
      "Hot Tub",
    ],
    entertainment: ["Satellite TV"],
    waterToys: ["Windsurf", "Water Skis", "Snorkeling Gear", "Jet Ski"],
    location: {
      city: "St-petersburg",
      country: "Russia",
      region: "Northern Europe",
      homePort: "Port of Amsterdam",
    },
    availableSeasons: ["Summer", "Spring"],
    charterType: "shared",
    crewIncluded: false,
    cateringOptions: ["Full-Service Catering"],
    description:
      "Adriatic Splendor combines performance and luxury in a stunning 18m sailing yacht. With its professional crew of 2, you'll experience the ultimate sailing vacation.",
    images: [
      "https://paragon-trails-yacht-images.com/sailing/st-petersburg-adriatic-splendor-1.jpg",
      "https://paragon-trails-yacht-images.com/sailing/st-petersburg-adriatic-splendor-2.jpg",
      "https://paragon-trails-yacht-images.com/sailing/st-petersburg-adriatic-splendor-3.jpg",
      "https://paragon-trails-yacht-images.com/sailing/st-petersburg-adriatic-splendor-4.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 6374,
      perWeek: 37925.299999999996,
      currency: "RUB",
      includes: ["Wi-Fi", "Heated Deck"],
      excludes: ["Hot Tub"],
    },
    safetyFeatures: ["GPS Tracking", "Life Jackets", "EPIRB", "Radar"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-st-petersburg-motor-3",
    name: "Crystal Blue",
    brand: "Feadship",
    model: "Feadship 71",
    yearBuilt: 2013,
    lengthInMeters: 30,
    beamInMeters: 6,
    draftInMeters: 3,
    cruisingSpeedKnots: 14,
    maxSpeedKnots: 25,
    fuelCapacityLiters: 15000,
    waterCapacityLiters: 9000,
    engines: ["1 x Caterpillar 20V 1981"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 10,
      guestsOvernight: 6,
      cabins: 3,
      crew: 3,
      bathrooms: 4,
    },
    amenities: ["Sun Deck", "Dining Area", "Heated Deck", "Bar"],
    entertainment: ["Bluetooth Speakers"],
    waterToys: ["Towable Tubes", "E-Foil", "Windsurf"],
    location: {
      city: "St-petersburg",
      country: "Russia",
      region: "Northern Europe",
      homePort: "Port of Amsterdam",
    },
    availableSeasons: ["Summer", "Spring"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["Picnic-Style", "Provisioning Only"],
    description:
      "Experience luxury and comfort aboard the Crystal Blue, a stunning 30m motor yacht available for charter in st-petersburg. Perfect for day trips or extended voyages.",
    images: [
      "https://paragon-trails-yacht-images.com/motor/st-petersburg-crystal-blue-1.jpg",
      "https://paragon-trails-yacht-images.com/motor/st-petersburg-crystal-blue-2.jpg",
      "https://paragon-trails-yacht-images.com/motor/st-petersburg-crystal-blue-3.jpg",
      "https://paragon-trails-yacht-images.com/motor/st-petersburg-crystal-blue-4.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 8386,
      perWeek: 49896.7,
      currency: "RUB",
      includes: ["Sun Deck", "Dining Area", "Heated Deck"],
      excludes: ["Bar"],
    },
    safetyFeatures: ["Radar", "Navigation Lights", "Emergency Beacon"],
    accessibilityFeatures: ["Easy Boarding"],
  },
];
