import { Yacht } from "@/lib/interfaces/services/rentals";

export const tokyojapanasiaPacificYachts: Yacht[] = [
  {
    id: "yacht-tokyo-mega-0",
    name: "Mediterranean Gem",
    brand: "Feadship",
    model: "Feadship 52",
    yearBuilt: 2011,
    lengthInMeters: 52,
    beamInMeters: 10.4,
    draftInMeters: 5.2,
    cruisingSpeedKnots: 17,
    maxSpeedKnots: 22,
    fuelCapacityLiters: 26000,
    waterCapacityLiters: 15600,
    engines: ["1 x Volvo Penta 21V 1296"],
    hullType: "monohull",
    yachtType: "mega",
    capacity: {
      guestsDay: 15,
      guestsOvernight: 10,
      cabins: 4,
      crew: 8,
      bathrooms: 5,
    },
    amenities: [
      "Dining Area",
      "Hot Tub",
      "Swim Platform",
      "Sun Deck",
      "Heated Deck",
      "Air Conditioning",
    ],
    entertainment: ["DJ Equipment"],
    waterToys: ["Water Skis", "Seabob", "Kayaks", "Towable Tubes", "Windsurf"],
    location: {
      city: "Tokyo",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Sentosa Cove",
    },
    availableSeasons: ["Winter"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["Picnic-Style"],
    description:
      "Mediterranean Gem combines performance and luxury in a stunning 52m mega yacht. With its professional crew of 8, you'll experience the ultimate sailing vacation.",
    images: [
      "https://paragon-trails-yacht-images.com/mega/tokyo-mediterranean-gem-1.jpg",
      "https://paragon-trails-yacht-images.com/mega/tokyo-mediterranean-gem-2.jpg",
      "https://paragon-trails-yacht-images.com/mega/tokyo-mediterranean-gem-3.jpg",
      "https://paragon-trails-yacht-images.com/mega/tokyo-mediterranean-gem-4.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 23091,
      perWeek: 137391.44999999998,
      currency: "JPY",
      includes: ["Dining Area", "Hot Tub", "Swim Platform"],
      excludes: ["Air Conditioning"],
    },
    safetyFeatures: ["Life Jackets", "Fire Extinguishers", "EPIRB"],
    accessibilityFeatures: ["Handrails", "Accessible Bathroom"],
  },
  {
    id: "yacht-tokyo-gulet-1",
    name: "Sapphire Seas",
    brand: "Swan",
    model: "Swan 35",
    yearBuilt: 2001,
    lengthInMeters: 30,
    beamInMeters: 6,
    draftInMeters: 3,
    cruisingSpeedKnots: 11,
    maxSpeedKnots: 25,
    fuelCapacityLiters: 15000,
    waterCapacityLiters: 9000,
    engines: ["1 x Volvo Penta 13V 1066"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 16,
      guestsOvernight: 13,
      cabins: 4,
      crew: 3,
      bathrooms: 5,
    },
    amenities: [
      "Kitchen",
      "Outdoor Shower",
      "Swim Platform",
      "Tender Garage",
      "Heated Deck",
    ],
    entertainment: ["Board Games"],
    waterToys: ["E-Foil", "Kayaks", "Kneeboard", "Paddleboards"],
    location: {
      city: "Tokyo",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Marina Bay",
    },
    availableSeasons: ["Year-Round"],
    charterType: "weekly",
    crewIncluded: true,
    cateringOptions: ["Chef Onboard"],
    description:
      "The Sapphire Seas is a magnificent gulet yacht built by Swan offering exceptional amenities and impeccable service for an unforgettable sailing experience in tokyo.",
    images: [
      "https://paragon-trails-yacht-images.com/gulet/tokyo-sapphire-seas-1.jpg",
      "https://paragon-trails-yacht-images.com/gulet/tokyo-sapphire-seas-2.jpg",
      "https://paragon-trails-yacht-images.com/gulet/tokyo-sapphire-seas-3.jpg",
      "https://paragon-trails-yacht-images.com/gulet/tokyo-sapphire-seas-4.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 3849,
      perWeek: 22901.55,
      currency: "JPY",
      includes: ["Kitchen", "Outdoor Shower"],
      excludes: [
        "Kitchen",
        "Outdoor Shower",
        "Swim Platform",
        "Tender Garage",
        "Heated Deck",
      ],
    },
    safetyFeatures: [
      "Emergency Beacon",
      "Fire Extinguishers",
      "Navigation Lights",
      "Searchlight",
    ],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-tokyo-sailing-2",
    name: "Silver Horizon",
    brand: "Sunreef",
    model: "Sunreef 0",
    yearBuilt: 2004,
    lengthInMeters: 29,
    beamInMeters: 5.8,
    draftInMeters: 2.9,
    cruisingSpeedKnots: 14,
    maxSpeedKnots: 20,
    fuelCapacityLiters: 14500,
    waterCapacityLiters: 8700,
    engines: ["1 x MTU 17V 1062"],
    hullType: "monohull",
    yachtType: "sailing",
    capacity: {
      guestsDay: 11,
      guestsOvernight: 7,
      cabins: 2,
      crew: 2,
      bathrooms: 3,
    },
    amenities: ["Dining Area", "Heated Deck", "Outdoor Shower", "Kitchen"],
    entertainment: ["Streaming Services"],
    waterToys: ["Inflatable Slide", "Paddleboards"],
    location: {
      city: "Tokyo",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Abell Point Marina",
    },
    availableSeasons: ["Summer", "Fall"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["No Catering", "BBQ Onboard"],
    description:
      "The Silver Horizon is a magnificent sailing yacht built by Sunreef offering exceptional amenities and impeccable service for an unforgettable sailing experience in tokyo.",
    images: [
      "https://paragon-trails-yacht-images.com/sailing/tokyo-silver-horizon-1.jpg",
      "https://paragon-trails-yacht-images.com/sailing/tokyo-silver-horizon-2.jpg",
      "https://paragon-trails-yacht-images.com/sailing/tokyo-silver-horizon-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 8468,
      perWeek: 50384.6,
      currency: "JPY",
      includes: ["Dining Area", "Heated Deck"],
      excludes: ["Kitchen"],
    },
    safetyFeatures: ["Emergency Beacon", "Radar", "Fire Extinguishers"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-tokyo-mega-3",
    name: "Sea Spirit",
    brand: "Pershing",
    model: "Pershing 70",
    yearBuilt: 2011,
    lengthInMeters: 47,
    beamInMeters: 9.4,
    draftInMeters: 4.7,
    cruisingSpeedKnots: 17,
    maxSpeedKnots: 23,
    fuelCapacityLiters: 23500,
    waterCapacityLiters: 14100,
    engines: ["1 x MAN 15V 1124"],
    hullType: "monohull",
    yachtType: "mega",
    capacity: {
      guestsDay: 14,
      guestsOvernight: 11,
      cabins: 6,
      crew: 6,
      bathrooms: 8,
    },
    amenities: ["Outdoor Shower", "Air Conditioning", "Sauna", "Indoor Lounge"],
    entertainment: ["Streaming Services"],
    waterToys: ["Floating Island", "E-Foil", "Fishing Equipment"],
    location: {
      city: "Tokyo",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Abell Point Marina",
    },
    availableSeasons: ["Year-Round", "Summer"],
    charterType: "weekly",
    crewIncluded: false,
    cateringOptions: ["No Catering", "BBQ Onboard"],
    description:
      "Discover the beauty of tokyo's waters aboard the elegant Sea Spirit, a 2011 mega yacht featuring spacious accommodation for 11 guests overnight or 14 for day charters.",
    images: [
      "https://paragon-trails-yacht-images.com/mega/tokyo-sea-spirit-1.jpg",
      "https://paragon-trails-yacht-images.com/mega/tokyo-sea-spirit-2.jpg",
      "https://paragon-trails-yacht-images.com/mega/tokyo-sea-spirit-3.jpg",
      "https://paragon-trails-yacht-images.com/mega/tokyo-sea-spirit-4.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 44965,
      perWeek: 267541.75,
      currency: "JPY",
      includes: ["Outdoor Shower"],
      excludes: ["Indoor Lounge"],
    },
    safetyFeatures: ["Emergency Steering", "EPIRB", "Life Rafts"],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-tokyo-gulet-4",
    name: "Sea Spirit",
    brand: "Azimut",
    model: "Azimut 0",
    yearBuilt: 2008,
    lengthInMeters: 31,
    beamInMeters: 6.2,
    draftInMeters: 3.1,
    cruisingSpeedKnots: 12,
    maxSpeedKnots: 20,
    fuelCapacityLiters: 15500,
    waterCapacityLiters: 9300,
    engines: ["1 x Volvo Penta 19V 1955"],
    hullType: "monohull",
    yachtType: "gulet",
    capacity: {
      guestsDay: 17,
      guestsOvernight: 13,
      cabins: 5,
      crew: 4,
      bathrooms: 7,
    },
    amenities: [
      "Bar",
      "Sun Deck",
      "Outdoor Shower",
      "Air Conditioning",
      "Hot Tub",
    ],
    entertainment: ["Surround Sound System", "Game Console"],
    waterToys: ["Inflatable Slide", "E-Foil", "Towable Tubes", "Seabob"],
    location: {
      city: "Tokyo",
      country: "Japan",
      region: "Asia Pacific",
      homePort: "Sentosa Cove",
    },
    availableSeasons: ["Winter"],
    charterType: "day",
    crewIncluded: true,
    cateringOptions: ["Provisioning Only"],
    description:
      "The Sea Spirit is a magnificent gulet yacht built by Azimut offering exceptional amenities and impeccable service for an unforgettable sailing experience in tokyo.",
    images: [
      "https://paragon-trails-yacht-images.com/gulet/tokyo-sea-spirit-1.jpg",
      "https://paragon-trails-yacht-images.com/gulet/tokyo-sea-spirit-2.jpg",
      "https://paragon-trails-yacht-images.com/gulet/tokyo-sea-spirit-3.jpg",
    ],
    featured: true,
    pricing: {
      perDay: 6414,
      perWeek: 38163.299999999996,
      currency: "JPY",
      includes: ["Bar", "Sun Deck", "Outdoor Shower"],
      excludes: [
        "Bar",
        "Sun Deck",
        "Outdoor Shower",
        "Air Conditioning",
        "Hot Tub",
      ],
    },
    safetyFeatures: [
      "GPS Tracking",
      "EPIRB",
      "Searchlight",
      "Emergency Beacon",
    ],
    accessibilityFeatures: [],
  },
];
