import { Yacht } from "@/lib/interfaces/services/rentals";

export const victoriacanadaalaskaYachts: Yacht[] = [
  {
    id: "yacht-victoria-catamaran-0",
    name: "Azure Dreams",
    brand: "Amels",
    model: "Amels 17",
    yearBuilt: 2012,
    lengthInMeters: 12,
    beamInMeters: 2.4,
    draftInMeters: 1.2,
    cruisingSpeedKnots: 18,
    maxSpeedKnots: 27,
    fuelCapacityLiters: 6000,
    waterCapacityLiters: 3600,
    engines: ["2 x MAN 13V 1714"],
    hullType: "catamaran",
    yachtType: "catamaran",
    capacity: {
      guestsDay: 11,
      guestsOvernight: 10,
      cabins: 5,
      crew: 2,
      bathrooms: 5,
    },
    amenities: [
      "Indoor Lounge",
      "Stabilizers",
      "Air Conditioning",
      "Heated Deck",
      "Kitchen",
      "Sauna",
      "Wi-Fi",
    ],
    entertainment: ["Streaming Services", "Bluetooth Speakers"],
    waterToys: ["Windsurf", "Jet Ski", "Scuba Diving Gear"],
    location: {
      city: "Victoria",
      country: "Canada",
      region: "Alaska",
      homePort: "Newport",
    },
    availableSeasons: ["Year-Round"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["Breakfast Only", "Chef Onboard"],
    description:
      "Discover the beauty of victoria's waters aboard the elegant Azure Dreams, a 2012 catamaran yacht featuring spacious accommodation for 10 guests overnight or 11 for day charters.",
    images: [
      "https://paragon-trails-yacht-images.com/catamaran/victoria-azure-dreams-1.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/victoria-azure-dreams-2.jpg",
      "https://paragon-trails-yacht-images.com/catamaran/victoria-azure-dreams-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 10741,
      perWeek: 63908.95,
      currency: "CAD",
      includes: ["Indoor Lounge"],
      excludes: [
        "Indoor Lounge",
        "Stabilizers",
        "Air Conditioning",
        "Heated Deck",
        "Kitchen",
        "Sauna",
        "Wi-Fi",
      ],
    },
    safetyFeatures: [
      "GPS Tracking",
      "Life Jackets",
      "Emergency Steering",
      "Emergency Beacon",
    ],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-victoria-mega-1",
    name: "Ocean Majesty",
    brand: "Sunreef",
    model: "Sunreef 68",
    yearBuilt: 2013,
    lengthInMeters: 44,
    beamInMeters: 8.8,
    draftInMeters: 4.4,
    cruisingSpeedKnots: 13,
    maxSpeedKnots: 20,
    fuelCapacityLiters: 22000,
    waterCapacityLiters: 13200,
    engines: ["1 x MAN 26V 1237"],
    hullType: "monohull",
    yachtType: "mega",
    capacity: {
      guestsDay: 15,
      guestsOvernight: 11,
      cabins: 6,
      crew: 7,
      bathrooms: 7,
    },
    amenities: [
      "Kitchen",
      "Swim Platform",
      "Wi-Fi",
      "Heated Deck",
      "Outdoor Shower",
      "Dining Area",
    ],
    entertainment: ["Bluetooth Speakers", "Board Games", "Media Library"],
    waterToys: ["Jet Ski", "Kneeboard"],
    location: {
      city: "Victoria",
      country: "Canada",
      region: "Alaska",
      homePort: "Fort Lauderdale",
    },
    availableSeasons: ["Summer"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["À La Carte", "All-Inclusive"],
    description:
      "Ocean Majesty combines performance and luxury in a stunning 44m mega yacht. With its professional crew of 7, you'll experience the ultimate sailing vacation.",
    images: [
      "https://paragon-trails-yacht-images.com/mega/victoria-ocean-majesty-1.jpg",
      "https://paragon-trails-yacht-images.com/mega/victoria-ocean-majesty-2.jpg",
      "https://paragon-trails-yacht-images.com/mega/victoria-ocean-majesty-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 24207,
      perWeek: 144031.65,
      currency: "CAD",
      includes: ["Kitchen", "Swim Platform", "Wi-Fi"],
      excludes: [
        "Kitchen",
        "Swim Platform",
        "Wi-Fi",
        "Heated Deck",
        "Outdoor Shower",
        "Dining Area",
      ],
    },
    safetyFeatures: [
      "GPS Tracking",
      "Searchlight",
      "First Aid Kit",
      "Life Rafts",
      "Fire Extinguishers",
    ],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-victoria-mega-2",
    name: "Sapphire Seas",
    brand: "Perini Navi",
    model: "Perini Navi 58",
    yearBuilt: 2001,
    lengthInMeters: 56,
    beamInMeters: 11.2,
    draftInMeters: 5.6,
    cruisingSpeedKnots: 12,
    maxSpeedKnots: 18,
    fuelCapacityLiters: 28000,
    waterCapacityLiters: 16800,
    engines: ["1 x Caterpillar 17V 1610"],
    hullType: "monohull",
    yachtType: "mega",
    capacity: {
      guestsDay: 12,
      guestsOvernight: 11,
      cabins: 6,
      crew: 8,
      bathrooms: 6,
    },
    amenities: ["Jacuzzi", "Indoor Lounge", "Laundry Service", "Sauna"],
    entertainment: ["Game Console", "DJ Equipment", "Satellite TV"],
    waterToys: ["Kayaks", "Snorkeling Gear", "Water Skis", "Scuba Diving Gear"],
    location: {
      city: "Victoria",
      country: "Canada",
      region: "Alaska",
      homePort: "Charleston Harbor",
    },
    availableSeasons: ["Winter"],
    charterType: "private",
    crewIncluded: true,
    cateringOptions: ["Chef Onboard"],
    description:
      "Sapphire Seas combines performance and luxury in a stunning 56m mega yacht. With its professional crew of 8, you'll experience the ultimate sailing vacation.",
    images: [
      "https://paragon-trails-yacht-images.com/mega/victoria-sapphire-seas-1.jpg",
      "https://paragon-trails-yacht-images.com/mega/victoria-sapphire-seas-2.jpg",
      "https://paragon-trails-yacht-images.com/mega/victoria-sapphire-seas-3.jpg",
    ],
    featured: false,
    pricing: {
      perDay: 24879,
      perWeek: 148030.05,
      currency: "CAD",
      includes: ["Jacuzzi", "Indoor Lounge", "Laundry Service"],
      excludes: ["Sauna"],
    },
    safetyFeatures: [
      "Navigation Lights",
      "Fire Extinguishers",
      "Emergency Beacon",
    ],
    accessibilityFeatures: [],
  },
  {
    id: "yacht-victoria-motor-3",
    name: "Coastal Serenity",
    brand: "Westport",
    model: "Westport 30",
    yearBuilt: 2002,
    lengthInMeters: 35,
    beamInMeters: 7,
    draftInMeters: 3.5,
    cruisingSpeedKnots: 14,
    maxSpeedKnots: 25,
    fuelCapacityLiters: 17500,
    waterCapacityLiters: 10500,
    engines: ["2 x Volvo Penta 14V 1755"],
    hullType: "monohull",
    yachtType: "motor",
    capacity: {
      guestsDay: 9,
      guestsOvernight: 8,
      cabins: 3,
      crew: 2,
      bathrooms: 5,
    },
    amenities: ["Kitchen", "Bar", "Air Conditioning"],
    entertainment: ["Karaoke System", "Onboard Cinema"],
    waterToys: ["Fishing Equipment", "Kneeboard", "Jet Ski"],
    location: {
      city: "Victoria",
      country: "Canada",
      region: "Alaska",
      homePort: "Newport",
    },
    availableSeasons: ["Spring", "Year-Round"],
    charterType: "shared",
    crewIncluded: true,
    cateringOptions: ["Full-Service Catering"],
    description:
      "Experience luxury and comfort aboard the Coastal Serenity, a stunning 35m motor yacht available for charter in victoria. Perfect for day trips or extended voyages.",
    images: [
      "https://paragon-trails-yacht-images.com/motor/victoria-coastal-serenity-1.jpg",
      "https://paragon-trails-yacht-images.com/motor/victoria-coastal-serenity-2.jpg",
      "https://paragon-trails-yacht-images.com/motor/victoria-coastal-serenity-3.jpg",
    ],
    featured: true,
    pricing: {
      perDay: 11946,
      perWeek: 71078.7,
      currency: "CAD",
      includes: ["Kitchen", "Bar"],
      excludes: ["Air Conditioning"],
    },
    safetyFeatures: [
      "Radar",
      "Life Jackets",
      "First Aid Kit",
      "Emergency Radio",
    ],
    accessibilityFeatures: ["Accessible Cabin", "Elevator"],
  },
];
