import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Mallorca Island Resort
export const mallorcaIslandResortRooms: RoomOption[] = [
  {
    id: "hotel-barcelona-3-room-2-Double-CityView",
    name: "Premium Double Loft",
    description: "Our Premium-themed double loft offers refreshing luxury, panoramic featuring a blend of modern and historic architecture, and featuring premium bath amenities, inspired by decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 113,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-barcelona-3-room-2-King-OceanView",
    name: "Modern King Loft",
    description: "This elegant king accommodation offers where you can enjoy stunning sunsets over the water, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 201,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-barcelona-3-room-2-Twin-MountainView",
    name: "Modern Twin Room",
    description: "A broad twin retreat with panoramic views of the mountain landscape, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 109,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-barcelona-3-room-2-SofaBed-MountainView",
    name: "Tranquility Sofa Bed Penthouse",
    description: "Step into a artistic sofa bed penthouse that combines Tranquility-themed with breathtaking where you can gaze at the towering peaks, complemented by with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 121,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-barcelona-3-room-2-Single-OceanView",
    name: "Deluxe Single Suite",
    description: "This ornate single accommodation offers where you can hear the soothing sound of the sea, decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 119,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-barcelona-3-room-2-Queen-None",
    name: "Horizon Queen Villa",
    description: "Horizon-themed queen villa with a pleasant outlook, decorated with local artistic influences and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 122,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-barcelona-3-room-2-SofaBed-OceanView",
    name: "Executive Sofa Bed Studio",
    description: "A relaxing sofa bed retreat with a private balcony overlooking the sea, designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 121,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-barcelona-3-room-2-Double-OceanView",
    name: "Horizon Double Penthouse",
    description: "Unwind in this open-concept double penthouse where you can relax to the sound of the waves, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 122,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  }
];
