import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Palazzo Reale
export const palazzoRealeRooms: RoomOption[] = [
  {
    id: "hotel-venice-11-room-10-Double-None",
    name: "Harmony Double Studio",
    description: "Harmony-themed studio with sophisticated decor, with a pleasant outlook, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 105,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-venice-11-room-10-Single-CityView",
    name: "Deluxe Single Villa",
    description: "Enjoy a upscale stay in our Deluxe-themed single villa, offering with a window to the bustling city below, equipped with all the modern conveniences, and unique touches of offering a touch of la dolce vita.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 90,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-venice-11-room-10-SofaBed-GardenView",
    name: "Horizon Sofa Bed Suite",
    description: "Step into a vast sofa bed suite that combines Horizon-themed with breathtaking with a view of the garden's natural beauty, complemented by offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 97,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-venice-11-room-10-Single-OceanView",
    name: "Executive Single Studio",
    description: "This refreshing single accommodation offers where the horizon meets the ocean, with classic Italian elegance.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 118,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-venice-11-room-10-Double-GardenView",
    name: "Executive Double Loft",
    description: "A palatial double retreat surrounded by vibrant flora, offering a touch of la dolce vita.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 130,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-venice-11-room-10-Twin-None",
    name: "Harmony Twin Loft",
    description: "Experience our refined, elegant twin loft with a pleasant outlook, with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 90,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-venice-11-room-10-Single-MountainView",
    name: "Deluxe Single Suite",
    description: "Discover the charm of this Deluxe-themed single suite, complete with glamorous ambiance, stunning where you can find inspiration in the mountains, and with a spacious seating area.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 97,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-venice-11-room-10-King-None",
    name: "Signature King Suite",
    description: "Enjoy a plush stay in our Signature-themed king suite, offering with a pleasant outlook, with a spacious seating area, and unique touches of offering a touch of la dolce vita.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 133,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
