import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Aosta Valley Retreat
export const theAostaValleyRetreatRooms: RoomOption[] = [
  {
    id: "hotel-venice-1-room-0-Queen-CityView",
    name: "Deluxe Queen Villa",
    description: "Step into a modern queen villa that combines Deluxe-themed with breathtaking where city lights twinkle at night, complemented by featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 235,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-venice-1-room-0-Twin-MountainView",
    name: "Horizon Twin Penthouse",
    description: "Horizon-themed twin penthouse with a view of the mountains' serene beauty, offering a touch of la dolce vita and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 198,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-venice-1-room-0-Single-GardenView",
    name: "Classic Single Room",
    description: "Discover the charm of this Classic-themed single room, complete with palatial ambiance, stunning with a view of the garden's vibrant colors, and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 160,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-venice-1-room-0-Queen-GardenView",
    name: "Deluxe Queen Room",
    description: "Our open-concept Deluxe-themed room offers with a view of the garden's lush greenery, large-scale comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 252,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-venice-1-room-0-Queen-None",
    name: "Tranquility Queen Studio",
    description: "Indulge in the cozy atmosphere of our queen studio, with spectacular with a pleasant outlook, offering a touch of la dolce vita, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 198,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-venice-1-room-0-SofaBed-None",
    name: "Classic Sofa Bed Loft",
    description: "This tranquil sofa bed accommodation offers with a pleasant outlook, with classic Italian elegance.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 149,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-venice-1-room-0-Queen-MountainView",
    name: "Classic Queen Studio",
    description: "Enjoy a intimate stay in our Classic-themed queen studio, offering where the mountains touch the sky, with a spacious seating area, and unique touches of with classic Italian elegance.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 253,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
