import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Harbor House
export const theHarborHouseRooms: RoomOption[] = [
  {
    id: "hotel-cartagena-5-room-4-SofaBed-CityView",
    name: "Andean Sofa Bed Room",
    description: "Experience our serene, industrial sofa bed room offering panoramic city vistas, including climate control for your comfort.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 2171974843,
    currency: "COP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-cartagena-5-room-4-King-MountainView",
    name: "Executive King Suite",
    description: "Enjoy a classic stay in our Executive-themed king suite, offering with a view of the rugged mountain landscape, offering a unique blend of style and comfort, and unique touches of featuring handcrafted local motifs.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Visual Aids", "Wheelchair Accessible"],
    pricePerNight: 3543793722,
    currency: "COP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-cartagena-5-room-4-King-OceanView",
    name: "Superior King Apartment",
    description: "Discover the charm of this Superior-themed king apartment, complete with futuristic ambiance, stunning where you can relax to the sound of the waves, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 4357830569,
    currency: "COP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-cartagena-5-room-4-Double-OceanView",
    name: "Coffee Double Room",
    description: "Indulge in the gentle atmosphere of our double room, with spectacular with a private balcony overlooking the sea, featuring handcrafted local motifs, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 3057739115,
    currency: "COP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-cartagena-5-room-4-Queen-CityView",
    name: "Medellín Queen Loft",
    description: "Our peaceful Medellín-themed loft offers with a view of the city's cultural landmarks, regal comfort, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 2651581057,
    currency: "COP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-cartagena-5-room-4-SofaBed-MountainView",
    name: "Classic Sofa Bed Penthouse",
    description: "A large-scale sofa bed penthouse designed for majestic comfort, with where you can escape to the mountains and equipped with all the modern conveniences, reflecting featuring handcrafted local motifs.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 2601481843,
    currency: "COP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-cartagena-5-room-4-Queen-OceanView",
    name: "Deluxe Queen Loft",
    description: "Our sophisticated Deluxe-themed loft offers overlooking the sparkling ocean waves, eclectic comfort, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 3101650891,
    currency: "COP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-cartagena-5-room-4-King-CityView",
    name: "Andean King Suite",
    description: "This stylish king accommodation offers with stunning views of the city skyline, offering a lively and welcoming space.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 3220175472,
    currency: "COP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-cartagena-5-room-4-King-None",
    name: "Premium King Penthouse",
    description: "This well-proportioned king accommodation offers with a pleasant outlook, offering a lively and welcoming space.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 3154413969,
    currency: "COP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-cartagena-5-room-4-Twin-None",
    name: "Executive Twin Room",
    description: "Indulge in the sumptuous atmosphere of our twin room, with spectacular with a pleasant outlook, with vibrant colors and tropical accents, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 1901240737,
    currency: "COP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  }
];
