import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Highland Gate Lodge
export const highlandGateLodgeRooms: RoomOption[] = [
  {
    id: "hotel-london-4-room-3-Double-MountainView",
    name: "Premium Double Studio",
    description: "Enjoy a calming stay in our Premium-themed double studio, offering where you can enjoy the serenity of mountain life, featuring a curated minibar selection, and unique touches of featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 195,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-london-4-room-3-Double-OceanView",
    name: "Royal Double Loft",
    description: "Unwind in this avant-garde double loft featuring uninterrupted ocean vistas, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 202,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-london-4-room-3-SofaBed-MountainView",
    name: "Classic Sofa Bed Suite",
    description: "Step into a refreshing sofa bed suite that combines Classic-themed with breathtaking where you can find inspiration in the mountains, complemented by equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Elevator"],
    pricePerNight: 150,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-london-4-room-3-SofaBed-CityView",
    name: "Standard Sofa Bed Penthouse",
    description: "Enjoy a classic stay in our Standard-themed sofa bed penthouse, offering where the city skyline meets the horizon, complete with a well-appointed bathroom, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 142,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-london-4-room-3-King-MountainView",
    name: "Victorian King Room",
    description: "This extensive king room promises where you can find inspiration in the mountains, enriched by Victorian-themed details and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 250,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-london-4-room-3-Queen-GardenView",
    name: "Superior Queen Villa",
    description: "A opulent queen villa designed for restful comfort, with where you can unwind in a garden paradise and with a modern en-suite bathroom, reflecting featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 210,
    currency: "GBP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-london-4-room-3-Single-None",
    name: "Deluxe Single Apartment",
    description: "This majestic single apartment promises with a pleasant outlook, enriched by Deluxe-themed details and with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 109,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-london-4-room-3-Single-MountainView",
    name: "Deluxe Single Loft",
    description: "A sumptuous single retreat with a view of the mountains' changing seasons, designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 146,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  }
];
