// Auto-generated file for london hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const londonHotels: Hotel[] = [
  {
    id: "hotel-london-1",
    name: "The King's Arms",
    address: "42 Church Pl",
    rating: 3,
    accommodationType: "Motel",
    amenities: ["Free Wi-Fi", "Swimming Pool", "Business Center", "Room Service", "Restaurant"],
    accessibilityFeatures: ["Assistive Listening Devices", "Tactile Maps", "Accessible Shower"],
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 14,
    isPetFriendly: false,
    currency: "GBP",
    contact: {
      contactEmail: "hello@theking'sarms.com",
      contactPhone: "+742 423-860-6851",
    },
    policies: {
      cancellation: "Free cancellation up to 14 days before check-in; 50% refund for cancellations made within 14 days.",
      smoking: "Allowed",
    },
    isPopular: true,
  },
  {
    id: "hotel-london-2",
    name: "Kent Countryside Inn",
    address: "182 Queen St",
    rating: 4,
    accommodationType: "Luxury Villa",
    amenities: ["Bar", "Free Wi-Fi", "Non-Smoking Rooms", "Business Center", "Laundry Service", "Room Service", "24-Hour Front Desk", "Conference Room", "Airport Shuttle", "Swimming Pool"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 21,
    isPetFriendly: false,
    currency: "GBP",
    contact: {
      contactEmail: "contact@kentcountrysideinn.com",
      contactPhone: "+732 749-172-4992",
    },
    policies: {
      cancellation: "Full refund if cancelled within 48 hours of booking, minus service fees.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  },
  {
    id: "hotel-london-3",
    name: "Oxford University Hotel",
    address: "118 Little Bridge Ave",
    rating: 4,
    accommodationType: "Glamping Resort",
    amenities: ["Bar", "Business Center", "Conference Room", "Restaurant", "Room Service", "24-Hour Front Desk", "Parking"],
    accessibilityFeatures: ["Large Print Materials", "Visual Aids"],
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 58,
    isPetFriendly: false,
    currency: "GBP",
    contact: {
      contactEmail: "support@oxforduniversityhotel.com",
      contactPhone: "+348 689-429-2030",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    isPopular: true,
  },
  {
    id: "hotel-london-4",
    name: "Highland Gate Lodge",
    address: "156 Victoria Way",
    rating: 4,
    accommodationType: "Eco-Lodge",
    amenities: ["Free Wi-Fi", "Swimming Pool", "Restaurant", "Fitness Center", "Business Center", "24-Hour Front Desk", "Laundry Service", "Spa", "Bar", "Airport Shuttle"],
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 18,
    isPetFriendly: false,
    currency: "GBP",
    contact: {
      contactEmail: "ask@highlandgatelodge.com",
      contactPhone: "+448 536-260-6701",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Not Allowed",
    },
    isPopular: true,
  },
  {
    id: "hotel-london-5",
    name: "The Yorkshire Heritage Inn",
    address: "272 London St",
    rating: 3,
    accommodationType: "Luxury Villa",
    amenities: ["Fitness Center", "Laundry Service", "Free Wi-Fi", "Conference Room", "Parking", "Swimming Pool", "Room Service", "Spa", "Bar", "Airport Shuttle"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids"],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 36,
    isPetFriendly: true,
    currency: "GBP",
    contact: {
      contactEmail: "help@theyorkshireheritageinn.com",
      contactPhone: "+121 113-885-2961",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-london-6",
    name: "The Canterbury Tales Inn",
    address: "163 Queen Way",
    rating: 3,
    accommodationType: "Resort",
    amenities: ["Swimming Pool", "Conference Room", "Parking", "Fitness Center", "Airport Shuttle", "Laundry Service", "Spa"],
    accessibilityFeatures: ["Braille Signage", "Accessible Shower"],
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 51,
    isPetFriendly: true,
    currency: "GBP",
    contact: {
      contactEmail: "clientservices@thecanterburytalesinn.com",
      contactPhone: "+679 204-285-3801",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Not Allowed",
    },
    isPopular: true,
  }
];
