import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for York Minster Suites
export const yorkMinsterSuitesRooms: RoomOption[] = [
  {
    id: "hotel-london-2-room-1-Queen-GardenView",
    name: "Classic Queen Room",
    description: "This soothing queen accommodation offers with a view of the garden's seasonal changes, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 141,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-london-2-room-1-SofaBed-GardenView",
    name: "Piccadilly Sofa Bed Villa",
    description: "Unwind in this grandiose sofa bed villa where you can enjoy the beauty of nature, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 110,
    currency: "GBP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-london-2-room-1-SofaBed-None",
    name: "Classic Sofa Bed Villa",
    description: "A sophisticated sofa bed villa designed for minimalist comfort, with with a pleasant outlook and including climate control for your comfort, reflecting created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 85,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-london-2-room-1-Queen-OceanView",
    name: "Signature Queen Loft",
    description: "Experience our chic, regal queen loft where the horizon meets the ocean, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 168,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-london-2-room-1-Single-CityView",
    name: "Standard Single Suite",
    description: "Indulge in the tranquil atmosphere of our single suite, with spectacular with a view of the city's waterfront, decorated with local artistic influences, and with a spacious seating area.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 89,
    currency: "GBP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  }
];
