import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Canvas & Quill Hotel
export const canvasQuillHotelRooms: RoomOption[] = [
  {
    id: "hotel-zanzibar-3-room-2-SofaBed-OceanView",
    name: "Signature Sofa Bed Studio",
    description: "Signature-themed sofa bed studio with a view of the tranquil sea, featuring thoughtful design elements and including climate control for your comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 1515159026,
    currency: "TZS",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-zanzibar-3-room-2-Double-OceanView",
    name: "Modern Double Studio",
    description: "Indulge in the fashionable atmosphere of our double studio, with spectacular where you can watch the waves roll in, featuring thoughtful design elements, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 1983428346,
    currency: "TZS",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-zanzibar-3-room-2-Double-GardenView",
    name: "Deluxe Double Suite",
    description: "Relax in our inviting inviting double suite featuring with a view of the garden's tranquil pathways, along with with a luxurious soaking tub and designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 1686743559,
    currency: "TZS",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-zanzibar-3-room-2-Single-GardenView",
    name: "Classic Single Villa",
    description: "This intimate single villa promises where you can enjoy the serenity of a garden retreat, enriched by Classic-themed details and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Hearing Support"],
    pricePerNight: 1285064045,
    currency: "TZS",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-zanzibar-3-room-2-Double-None",
    name: "Classic Double Room",
    description: "Enjoy a extensive stay in our Classic-themed double room, offering with a pleasant outlook, featuring premium bath amenities, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 1327859980,
    currency: "TZS",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-zanzibar-3-room-2-Twin-MountainView",
    name: "Premium Twin Studio",
    description: "Premium-themed twin studio with panoramic views of the surrounding mountains, designed for ultimate comfort and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 1646274776,
    currency: "TZS",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-zanzibar-3-room-2-Double-CityView",
    name: "Standard Double Loft",
    description: "Enjoy a rustic stay in our Standard-themed double loft, offering with a view of the city's cultural landmarks, including climate control for your comfort, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 1621205749,
    currency: "TZS",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  }
];
