import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Imperial Pavilion
export const theImperialPavilionRooms: RoomOption[] = [
  {
    id: "hotel-prague-1-room-0-Double-OceanView",
    name: "Classic Double Penthouse",
    description: "Classic-themed double penthouse with a view of the sandy beaches, featuring thoughtful design elements and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 77168,
    currency: "CZK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-prague-1-room-0-Double-None",
    name: "Tranquility Double Loft",
    description: "This stylish double loft promises with a pleasant outlook, enriched by Tranquility-themed details and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 63444,
    currency: "CZK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-prague-1-room-0-Double-GardenView",
    name: "Standard Double Room",
    description: "Our broad Standard-themed room offers with serene garden views, prestigious comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 64630,
    currency: "CZK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-prague-1-room-0-Single-MountainView",
    name: "Harmony Single Penthouse",
    description: "Relax in our deluxe sumptuous single penthouse featuring where the mountains touch the sky, along with with a private balcony or terrace and created with both style and function in mind.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 54705,
    currency: "CZK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-prague-1-room-0-Single-GardenView",
    name: "Harmony Single Suite",
    description: "Experience our restful, indulgent single suite with a view of the garden's seasonal changes, with a spacious seating area.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 53687,
    currency: "CZK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
