import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Guimarães Castle Inn
export const guimaresCastleInnRooms: RoomOption[] = [
  {
    id: "hotel-lisbon-5-room-4-SofaBed-CityView",
    name: "Classic Sofa Bed Penthouse",
    description: "Indulge in the extravagant atmosphere of our sofa bed penthouse, with spectacular showcasing the urban landscape, offering a unique cultural experience with a touch of luxury, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 172,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-lisbon-5-room-4-King-OceanView",
    name: "Porto King Room",
    description: "This ample king accommodation offers where you can watch the waves roll in, featuring traditional Portuguese tiles and decor.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 338,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-lisbon-5-room-4-Double-CityView",
    name: "Saudade Double Suite",
    description: "Experience our roomy, well-proportioned double suite offering panoramic city vistas, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 177,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-lisbon-5-room-4-King-GardenView",
    name: "Saudade King Penthouse",
    description: "Our Saudade-themed king penthouse offers elegant luxury, panoramic where you can relax in a garden haven, and with a modern en-suite bathroom, inspired by with a blend of historic charm and modern amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 297,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-lisbon-5-room-4-King-CityView",
    name: "Azulejo King Loft",
    description: "Relax in our regal generous king loft featuring with stunning views of the city skyline, along with with a spacious work area and offering a unique cultural experience with a touch of luxury.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 254,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-lisbon-5-room-4-Single-OceanView",
    name: "Premium Single Penthouse",
    description: "Experience our sizable, grandiose single penthouse where the ocean meets the sky, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 196,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-lisbon-5-room-4-Single-GardenView",
    name: "Deluxe Single Room",
    description: "Our refined Deluxe-themed room offers with a view of colorful flower beds, plush comfort, and with high-speed internet access.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 171,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-lisbon-5-room-4-Queen-None",
    name: "Executive Queen Room",
    description: "Our extensive Executive-themed room offers with a pleasant outlook, ornate comfort, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 207,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-lisbon-5-room-4-Double-None",
    name: "Saudade Double Villa",
    description: "Saudade-themed villa with glamorous decor, with a pleasant outlook, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 162,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  }
];
