import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Emerald Triangle Lodge
export const theEmeraldTriangleLodgeRooms: RoomOption[] = [
  {
    id: "hotel-bangkok-6-room-5-Double-OceanView",
    name: "Jasmine Double Loft",
    description: "Experience our airy, comfortable double loft where you can feel the ocean breeze, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 160510,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-bangkok-6-room-5-Queen-OceanView",
    name: "Siam Queen Studio",
    description: "This inviting queen studio promises with a view of the sandy beaches, enriched by Siam-themed details and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 185025,
    currency: "THB",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-bangkok-6-room-5-Twin-OceanView",
    name: "Classic Twin Apartment",
    description: "A minimalist twin retreat with the sound of the ocean as your backdrop, featuring traditional Thai craftsmanship.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 161882,
    currency: "THB",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-bangkok-6-room-5-King-CityView",
    name: "Deluxe King Loft",
    description: "This vintage king loft promises where the city skyline meets the horizon, enriched by Deluxe-themed details and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 209946,
    currency: "THB",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-bangkok-6-room-5-Double-MountainView",
    name: "Tropical Double Loft",
    description: "Enjoy a glamorous stay in our Tropical-themed double loft, offering where the mountains touch the sky, complete with a well-appointed bathroom, and unique touches of blending Thai elegance with modern comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 153817,
    currency: "THB",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  }
];
