import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Urban Garden Hotel
export const urbanGardenHotelRooms: RoomOption[] = [
  {
    id: "hotel-bangkok-3-room-2-SofaBed-GardenView",
    name: "Luxury Sofa Bed Apartment",
    description: "Luxury-themed apartment with eclectic decor, where you can take in the fresh air, and featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 144112,
    currency: "THB",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-bangkok-3-room-2-Queen-MountainView",
    name: "Executive Queen Villa",
    description: "Experience our minimalist, sumptuous queen villa where you can enjoy the mountains' majestic presence, with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 205534,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-bangkok-3-room-2-King-GardenView",
    name: "Deluxe King Loft",
    description: "Enjoy a large-scale stay in our Deluxe-themed king loft, offering with a view of the garden's natural beauty, with a spacious seating area, and unique touches of featuring traditional Thai craftsmanship.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids", "Accessible Bathroom"],
    pricePerNight: 195002,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-bangkok-3-room-2-Double-MountainView",
    name: "Premium Double Villa",
    description: "Premium-themed double villa where mountains paint the horizon, adorned with Thai-inspired decor and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 165098,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-bangkok-3-room-2-Twin-OceanView",
    name: "Standard Twin Room",
    description: "Discover the charm of this Standard-themed twin room, complete with gentle ambiance, stunning with a private balcony overlooking the sea, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 139408,
    currency: "THB",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-bangkok-3-room-2-Queen-None",
    name: "Standard Queen Apartment",
    description: "This contemporary queen apartment promises with a pleasant outlook, enriched by Standard-themed details and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 170433,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-bangkok-3-room-2-King-CityView",
    name: "Luxury King Apartment",
    description: "A calming king retreat where you can enjoy the city's energy, with subtle nods to Thailand's rich cultural heritage.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 204813,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-bangkok-3-room-2-Queen-OceanView",
    name: "Classic Queen Studio",
    description: "Indulge in the traditional atmosphere of our queen studio, with spectacular where you can feel the ocean breeze, adorned with Thai-inspired decor, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Accessible Bathroom", "Wheelchair Accessible", "Hearing Support"],
    pricePerNight: 218540,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  }
];
