import { StaffCategory } from "@/lib/interfaces/people/staff";

export const aviationPersonnel: StaffCategory[] = [
  {
    category: "Pilots",
    profiles: [
      {
        name: "Captain Sarah Mitchell",
        certifications: [
          "FAA ATP",
          "Type Rated: Gulfstream G650",
          "Instrument Rated",
        ],
        languages: ["English", "French", "Spanish"],
        experienceYears: 15,
        qualifiedAircraft: ["Heavy Jets", "Midsize Jets"],
        specialTraining: [
          "VIP Protocol",
          "International Flight Operations",
          "Safety & Emergency Procedures",
        ],
        availability: "Full-time",
      },
      {
        name: "First Officer James Kim",
        certifications: [
          "FAA Commercial Pilot License",
          "Type Rated: Embraer Phenom 300",
          "Instrument Rated",
        ],
        languages: ["English", "Korean"],
        experienceYears: 8,
        qualifiedAircraft: ["Light Private Jets", "Midsize Jets"],
        specialTraining: ["Customer Service", "Advanced Navigation Systems"],
        availability: "Part-time",
      },
      {
        name: "Captain Elena Rossi",
        certifications: [
          "EASA ATPL",
          "Type Rated: Bombardier Global 7500",
          "Multi-Engine IFR",
        ],
        languages: ["English", "Italian", "German"],
        experienceYears: 18,
        qualifiedAircraft: ["Heavy Jets"],
        specialTraining: ["Anti-surveillance Maneuvers", "VIP Client Handling"],
        availability: "Full-time",
      },
      {
        name: "Helicopter Pilot Michael Chen",
        certifications: [
          "FAA Commercial Rotorcraft License",
          "Instrument Rated",
        ],
        languages: ["English", "Mandarin"],
        experienceYears: 10,
        qualifiedAircraft: ["Private Helicopters"],
        specialTraining: ["Mountain Flying", "Island Transfer Operations"],
        availability: "On-call",
      },
      {
        name: "Captain Anya Petrova",
        certifications: [
          "FAA ATP",
          "Type Rated: Bombardier Challenger 350",
          "Night & IFR",
        ],
        languages: ["English", "Russian"],
        experienceYears: 12,
        qualifiedAircraft: ["Midsize Jets", "Heavy Jets"],
        specialTraining: [
          "Security Protocols",
          "Cross-border Flight Coordination",
        ],
        availability: "Full-time",
      },
      {
        name: "First Officer Lucas Smith",
        certifications: [
          "FAA Commercial Pilot License",
          "Type Rated: Citation CJ4",
        ],
        languages: ["English"],
        experienceYears: 7,
        qualifiedAircraft: ["Light Private Jets"],
        specialTraining: ["Customer Service", "Fuel Efficiency Techniques"],
        availability: "Part-time",
      },
      {
        name: "Helicopter Pilot Sofia Garcia",
        certifications: [
          "FAA Commercial Rotorcraft License",
          "Mountain Flying Certified",
        ],
        languages: ["English", "Spanish"],
        experienceYears: 9,
        qualifiedAircraft: ["Private Helicopters"],
        specialTraining: ["Emergency Medical Flights", "Tourist Flight Safety"],
        availability: "On-call",
      },
      {
        name: "Captain Victor Hernandez",
        certifications: [
          "FAA ATP",
          "Type Rated: Dassault Falcon 8X",
          "Instrument Rated",
        ],
        languages: ["English", "Spanish", "Portuguese"],
        experienceYears: 16,
        qualifiedAircraft: ["Heavy Jets", "Midsize Jets"],
        specialTraining: [
          "Polar Route Navigation",
          "Desert Operations",
          "High Altitude Operations",
        ],
        availability: "Full-time",
      },
      {
        name: "First Officer Naomi Watkins",
        certifications: [
          "FAA Commercial Pilot License",
          "Type Rated: Cessna Citation Longitude",
          "Instrument Rated",
        ],
        languages: ["English", "Japanese"],
        experienceYears: 9,
        qualifiedAircraft: ["Midsize Jets", "Light Private Jets"],
        specialTraining: ["Oceanic Procedures", "Advanced Weather Navigation"],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Cabin Crew",
    profiles: [
      {
        name: "Lead Flight Attendant Olivia Green",
        certifications: [
          "Safety & Emergency Procedures",
          "First Aid Certified",
        ],
        languages: ["English", "French"],
        experienceYears: 12,
        qualifiedAircraft: ["Heavy Jets", "Midsize Jets"],
        specialTraining: [
          "VIP Service",
          "Cultural Sensitivity",
          "Gourmet Inflight Service",
        ],
        availability: "Full-time",
      },
      {
        name: "Flight Attendant Daniel Perez",
        certifications: ["Emergency Evacuation", "First Aid"],
        languages: ["English", "Spanish"],
        experienceYears: 6,
        qualifiedAircraft: ["Light Private Jets", "Midsize Jets"],
        specialTraining: [
          "Customer Service",
          "Inflight Entertainment Management",
        ],
        availability: "Part-time",
      },
      {
        name: "Helicopter Cabin Specialist Emma Johnson",
        certifications: ["Helicopter Safety", "First Aid"],
        languages: ["English"],
        experienceYears: 5,
        qualifiedAircraft: ["Private Helicopters"],
        specialTraining: [
          "Quick Boarding & Disembarkation",
          "Safety Protocols for Scenic Flights",
        ],
        availability: "On-call",
      },
      {
        name: "Senior Flight Attendant Marcus Lee",
        certifications: ["Inflight Safety", "First Aid", "Firefighting"],
        languages: ["English", "Chinese"],
        experienceYears: 14,
        qualifiedAircraft: ["Heavy Jets"],
        specialTraining: ["Executive Service", "Emergency Management"],
        availability: "Full-time",
      },
      {
        name: "Flight Attendant Rachel Kim",
        certifications: ["Customer Care", "First Aid"],
        languages: ["English", "Korean"],
        experienceYears: 4,
        qualifiedAircraft: ["Midsize Jets"],
        specialTraining: ["Passenger Comfort", "Safety Compliance"],
        availability: "Part-time",
      },
      {
        name: "Flight Attendant Jasmine Patel",
        certifications: ["Cabin Safety", "Advanced First Aid", "CPR"],
        languages: ["English", "Hindi", "Arabic"],
        experienceYears: 8,
        qualifiedAircraft: ["Heavy Jets", "Midsize Jets"],
        specialTraining: [
          "International Etiquette",
          "Cultural Protocol",
          "Fine Wine Service",
        ],
        availability: "Full-time",
      },
      {
        name: "Flight Attendant Thomas Laurent",
        certifications: ["Emergency Procedures", "First Aid", "Food Safety"],
        languages: ["English", "French", "German"],
        experienceYears: 9,
        qualifiedAircraft: ["Heavy Jets", "Light Private Jets"],
        specialTraining: [
          "Fine Dining Service",
          "High-profile Client Management",
        ],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Chefs",
    profiles: [
      {
        name: "Chef Antonio Marquez",
        certifications: ["Culinary Arts Diploma", "Food Safety & Hygiene"],
        specialties: ["Mediterranean Cuisine", "Vegan & Gluten-Free Options"],
        languages: ["English", "Spanish", "Italian"],
        experienceYears: 14,
        qualifiedAircraft: ["Heavy Jets", "Midsize Jets"],
        availability: "Full-time",
      },
      {
        name: "Chef Sophia Liu",
        certifications: ["Culinary School Graduate", "Nutrition Certification"],
        specialties: ["Asian Fusion", "Kosher & Halal Meals"],
        languages: ["English", "Mandarin"],
        experienceYears: 10,
        qualifiedAircraft: ["Light Private Jets", "Midsize Jets"],
        availability: "Part-time",
      },
      {
        name: "Chef Marcus Bennett",
        certifications: ["Professional Chef", "Allergen Management"],
        specialties: ["American Classic", "Organic & Farm-to-Table"],
        languages: ["English"],
        experienceYears: 12,
        qualifiedAircraft: ["Heavy Jets"],
        availability: "On-demand",
      },
      {
        name: "Chef Elena Duarte",
        certifications: ["Pastry Chef Certified", "Food Safety"],
        specialties: ["French Pastries", "Gluten-Free Desserts"],
        languages: ["English", "French"],
        experienceYears: 9,
        qualifiedAircraft: ["Midsize Jets"],
        availability: "Part-time",
      },
      {
        name: "Chef Marcus O'Connor",
        certifications: ["Culinary Arts", "Sustainable Cooking"],
        specialties: ["Seafood", "Farm-to-Table"],
        languages: ["English"],
        experienceYears: 11,
        qualifiedAircraft: ["Heavy Jets", "Midsize Jets"],
        availability: "On-demand",
      },
      {
        name: "Chef Hiroshi Tanaka",
        certifications: ["Master Chef", "Sushi Specialist", "Food Safety"],
        specialties: ["Japanese Cuisine", "Sushi & Sashimi", "Asian Fusion"],
        languages: ["English", "Japanese"],
        experienceYears: 15,
        qualifiedAircraft: ["Heavy Jets", "Midsize Jets"],
        availability: "On-demand",
      },
      {
        name: "Chef Isabella Romano",
        certifications: [
          "Culinary Institute Graduate",
          "Wine Pairing Specialist",
        ],
        specialties: [
          "Italian Cuisine",
          "Molecular Gastronomy",
          "Low-Altitude Adapted Recipes",
        ],
        languages: ["English", "Italian", "Spanish"],
        experienceYears: 12,
        qualifiedAircraft: ["Heavy Jets", "Midsize Jets"],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Ground Support",
    profiles: [
      {
        name: "Logistics Coordinator Jane Foster",
        certifications: ["Aviation Ground Operations"],
        languages: ["English", "French"],
        experienceYears: 8,
        responsibilities: [
          "Flight Scheduling",
          "Customer Liaison",
          "VIP Ground Services",
        ],
        availability: "Full-time",
      },
      {
        name: "Maintenance Supervisor Robert Delgado",
        certifications: ["Aircraft Maintenance Technician", "FAA Part 145"],
        languages: ["English", "Spanish"],
        experienceYears: 15,
        responsibilities: [
          "Aircraft Safety Checks",
          "Routine Maintenance",
          "Emergency Repairs",
        ],
        availability: "Full-time",
      },
      {
        name: "Ramp Agent Kevin Brooks",
        certifications: ["Ground Handling", "Safety Procedures"],
        languages: ["English"],
        experienceYears: 6,
        responsibilities: ["Baggage Handling", "Aircraft Marshaling"],
        availability: "Full-time",
      },
      {
        name: "Fuel Technician Linda Gomez",
        certifications: ["Fuel Handling & Safety"],
        languages: ["English", "Spanish"],
        experienceYears: 9,
        responsibilities: ["Aircraft Refueling", "Fuel Quality Control"],
        availability: "Full-time",
      },
      {
        name: "VIP Handler Cameron Williams",
        certifications: ["VIP Ground Operations", "Security Procedures"],
        languages: ["English", "Arabic"],
        experienceYears: 11,
        responsibilities: [
          "High-profile Client Management",
          "Discrete Transportation",
          "Expedited Customs",
        ],
        availability: "Full-time",
      },
      {
        name: "Baggage Specialist Diana Lopez",
        certifications: ["Secure Baggage Handling", "Inventory Management"],
        languages: ["English", "Spanish"],
        experienceYears: 7,
        responsibilities: [
          "Secure Luggage Transfer",
          "Fine Art & Valuables Handling",
          "Lost Luggage Resolution",
        ],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Flight Engineers",
    profiles: [
      {
        name: "Flight Engineer Thomas Grey",
        certifications: [
          "FAA Flight Engineer Certificate",
          "Multi-Engine Proficiency",
        ],
        languages: ["English"],
        experienceYears: 13,
        qualifiedAircraft: ["Heavy Jets"],
        specialTraining: ["Engine Diagnostics", "Emergency Procedures"],
        availability: "Full-time",
      },
      {
        name: "Flight Engineer Priya Singh",
        certifications: ["FAA Flight Engineer License"],
        languages: ["English", "Hindi"],
        experienceYears: 10,
        qualifiedAircraft: ["Midsize Jets"],
        specialTraining: ["Systems Monitoring", "Fuel Management"],
        availability: "Part-time",
      },
      {
        name: "Flight Engineer Omar Al-Farsi",
        certifications: [
          "FAA Flight Engineer Certificate",
          "Avionics Specialist",
        ],
        languages: ["English", "Arabic", "French"],
        experienceYears: 14,
        qualifiedAircraft: ["Heavy Jets"],
        specialTraining: ["Advanced Troubleshooting", "Hot Weather Operations"],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Safety Officers",
    profiles: [
      {
        name: "Safety Officer Mark Johnson",
        certifications: [
          "Aviation Safety Management Systems (SMS)",
          "Emergency Response",
        ],
        languages: ["English"],
        experienceYears: 20,
        responsibilities: ["Flight Safety Audits", "Crew Training"],
        availability: "Full-time",
      },
      {
        name: "Safety Officer Maria Hernandez",
        certifications: ["Safety Compliance", "Risk Management"],
        languages: ["English", "Spanish"],
        experienceYears: 12,
        responsibilities: ["Incident Investigations", "Regulatory Compliance"],
        availability: "Full-time",
      },
      {
        name: "Safety Officer David Chen",
        certifications: ["International Safety Standards", "IASA Compliance"],
        languages: ["English", "Mandarin", "Cantonese"],
        experienceYears: 15,
        responsibilities: [
          "Safety Audits",
          "Crew Training",
          "International Compliance",
        ],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Concierge Staff",
    profiles: [
      {
        name: "Concierge Alex Thompson",
        certifications: ["Customer Service Excellence", "VIP Protocol"],
        languages: ["English", "French"],
        experienceYears: 7,
        responsibilities: [
          "Client Requests",
          "Ground Transportation Coordination",
          "Luxury Accommodations",
        ],
        availability: "Full-time",
      },
      {
        name: "Concierge Sophie Martin",
        certifications: ["Customer Relations", "Event Planning"],
        languages: ["English", "German"],
        experienceYears: 5,
        responsibilities: [
          "Personalized Guest Services",
          "Dining Reservations",
        ],
        availability: "Part-time",
      },
      {
        name: "Executive Concierge Isabelle Dubois",
        certifications: ["Luxury Services", "High-end Client Relations"],
        languages: ["English", "French", "Italian", "Russian"],
        experienceYears: 10,
        responsibilities: [
          "Private Events Coordination",
          "Exclusive Access Arrangements",
          "Personalized Itineraries",
        ],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Aircraft Technicians",
    profiles: [
      {
        name: "Lead Technician Miguel Ortiz",
        certifications: ["A&P License", "Avionics Specialist", "FAA Part 145"],
        languages: ["English", "Spanish"],
        experienceYears: 18,
        specialties: ["Gulfstream Airframes", "Pratt & Whitney Engines"],
        availability: "Full-time",
      },
      {
        name: "Avionics Specialist Emily Zhang",
        certifications: [
          "FAA Certified Avionics Technician",
          "Electronics Engineering",
        ],
        languages: ["English", "Mandarin"],
        experienceYears: 12,
        specialties: [
          "Navigation Systems",
          "Communication Equipment",
          "Entertainment Systems",
        ],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Dispatchers",
    profiles: [
      {
        name: "Chief Dispatcher Nathan Taylor",
        certifications: [
          "FAA Aircraft Dispatcher License",
          "Flight Planning Specialist",
        ],
        languages: ["English"],
        experienceYears: 14,
        responsibilities: [
          "Route Planning",
          "Weather Monitoring",
          "Operational Control",
        ],
        availability: "Full-time",
      },
      {
        name: "International Dispatcher Anika Sharma",
        certifications: [
          "ICAO Flight Operations Officer",
          "International Flight Planning",
        ],
        languages: ["English", "Hindi", "Arabic"],
        experienceYears: 9,
        responsibilities: [
          "Transoceanic Flight Planning",
          "Overflight Permissions",
          "Landing Rights",
        ],
        availability: "Full-time",
      },
    ],
  },
  {
    category: "Medical Staff",
    profiles: [
      {
        name: "Flight Physician Dr. Richard Evans",
        certifications: [
          "Board Certified Emergency Medicine",
          "Aviation Medicine",
        ],
        languages: ["English", "German"],
        experienceYears: 15,
        specialties: [
          "In-flight Medical Emergencies",
          "Remote Medical Consultation",
        ],
        availability: "On-call",
      },
      {
        name: "Flight Nurse Samantha Wright",
        certifications: [
          "RN",
          "Flight Nurse Certification",
          "Advanced Cardiac Life Support",
        ],
        languages: ["English", "Spanish"],
        experienceYears: 10,
        specialties: [
          "Critical Care",
          "Emergency Response",
          "Altitude Physiology",
        ],
        availability: "On-call",
      },
    ],
  },
];
