import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Kunming Spring Hotel
export const kunmingSpringHotelRooms: RoomOption[] = [
  {
    id: "hotel-chengdu-1-room-0-Twin-CityView",
    name: "Executive Twin Loft",
    description: "Our restful Executive-themed loft offers with a view of iconic landmarks, pleasant comfort, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 8354,
    currency: "CNY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-chengdu-1-room-0-Single-None",
    name: "Dragon Single Loft",
    description: "A regal single retreat with a pleasant outlook, with classic Chinese artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 7104,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-chengdu-1-room-0-Queen-None",
    name: "Classic Queen Penthouse",
    description: "This stylish queen penthouse promises with a pleasant outlook, enriched by Classic-themed details and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 9878,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-chengdu-1-room-0-King-OceanView",
    name: "Premium King Suite",
    description: "Unwind in this soft king suite where you can hear the soothing sound of the sea, with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 16386,
    currency: "CNY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-chengdu-1-room-0-Twin-MountainView",
    name: "Premium Twin Suite",
    description: "Premium-themed suite with well-proportioned decor, with a view of the mountains' lush valleys, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 10235,
    currency: "CNY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-chengdu-1-room-0-Queen-OceanView",
    name: "Deluxe Queen Suite",
    description: "Relax in our soothing upscale queen suite featuring with a view of the ocean's horizon, along with complete with a well-appointed bathroom and with classic Chinese artistic influences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 13397,
    currency: "CNY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  }
];
