import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Rosemont Retreat
export const rosemontRetreatRooms: RoomOption[] = [
  {
    id: "hotel-miami-11-room-10-SofaBed-MountainView",
    name: "Standard Sofa Bed Apartment",
    description: "Standard-themed apartment with futuristic decor, with majestic mountain vistas, and with a spacious work area.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Elevator", "Hearing Support"],
    pricePerNight: 242,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-miami-11-room-10-SofaBed-CityView",
    name: "Deluxe Sofa Bed Penthouse",
    description: "Our artistic Deluxe-themed penthouse offers overlooking the vibrant cityscape, bohemian comfort, and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 183,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-miami-11-room-10-Single-None",
    name: "Pioneer Single Suite",
    description: "Our Pioneer-themed single suite offers palatial luxury, panoramic with a pleasant outlook, and with a spacious seating area, inspired by with rustic and modern influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator"],
    pricePerNight: 173,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-miami-11-room-10-King-GardenView",
    name: "Luxury King Room",
    description: "Indulge in the comfortable atmosphere of our king room, with spectacular offering a peaceful garden outlook, featuring sleek urban design elements, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 304,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-miami-11-room-10-King-OceanView",
    name: "Executive King Room",
    description: "Our Executive-themed king room offers snug luxury, panoramic where you can hear the soothing sound of the sea, and with blackout curtains for a perfect night's sleep, inspired by highlighting contemporary American style.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    accessibilityFeatures: ["Accessible Bathroom", "Wheelchair Accessible", "Visual Aids"],
    pricePerNight: 351,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-miami-11-room-10-Queen-MountainView",
    name: "Colonial Queen Loft",
    description: "A soothing queen retreat where you can enjoy the peace of the highlands, with rustic and modern influences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Hearing Support", "Wheelchair Accessible"],
    pricePerNight: 305,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-miami-11-room-10-King-CityView",
    name: "Manhattan King Penthouse",
    description: "A retro king retreat with a view of the city's cultural landmarks, with rustic and modern influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 338,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-miami-11-room-10-Queen-None",
    name: "Signature Queen Room",
    description: "Experience our avant-garde, voluminous queen room with a pleasant outlook, including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 243,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
