import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Bologna Culinary Hotel
export const theBolognaCulinaryHotelRooms: RoomOption[] = [
  {
    id: "hotel-amalfi-coast-5-room-4-Double-CityView",
    name: "Superior Double Penthouse",
    description: "Unwind in this pleasant double penthouse with a front-row seat to the city's heartbeat, with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 262,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-amalfi-coast-5-room-4-SofaBed-GardenView",
    name: "Tranquility Sofa Bed Apartment",
    description: "Relax in our stretching calming sofa bed apartment featuring where you can unwind in a garden paradise, along with featuring premium bath amenities and featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 215,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-amalfi-coast-5-room-4-SofaBed-None",
    name: "Executive Sofa Bed Loft",
    description: "Indulge in the open-concept atmosphere of our sofa bed loft, with spectacular with a pleasant outlook, decorated with local artistic influences, and with high-speed internet access.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Hearing Support", "Accessible Bathroom"],
    pricePerNight: 196,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-amalfi-coast-5-room-4-Twin-OceanView",
    name: "Horizon Twin Villa",
    description: "This pleasant twin villa promises with a view of the tranquil sea, enriched by Horizon-themed details and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 236,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-amalfi-coast-5-room-4-King-GardenView",
    name: "Tranquility King Room",
    description: "Relax in our extensive relaxing king room featuring surrounded by vibrant flora, along with with a private balcony or terrace and decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 391,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-amalfi-coast-5-room-4-Queen-CityView",
    name: "Signature Queen Apartment",
    description: "Our ornate Signature-themed apartment offers with a view of iconic landmarks, sophisticated comfort, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 292,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
