import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Tuscan Vineyard Inn
export const theTuscanVineyardInnRooms: RoomOption[] = [
  {
    id: "hotel-amalfi-coast-2-room-1-Single-OceanView",
    name: "Signature Single Suite",
    description: "Indulge in the wide-ranging atmosphere of our single suite, with spectacular where the ocean meets the sky, designed for ultimate comfort, and with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 247,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-amalfi-coast-2-room-1-King-OceanView",
    name: "Executive King Loft",
    description: "Relax in our glamorous classic king loft featuring featuring uninterrupted ocean vistas, along with equipped with all the modern conveniences and decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Visual Aids", "Wheelchair Accessible"],
    pricePerNight: 432,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-amalfi-coast-2-room-1-Double-None",
    name: "Classic Double Suite",
    description: "Experience our retro, expansive double suite with a pleasant outlook, featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 203,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-amalfi-coast-2-room-1-Queen-GardenView",
    name: "Classic Queen Loft",
    description: "Enjoy a palatial stay in our Classic-themed queen loft, offering with a view of shaded garden paths, with a spacious work area, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 317,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-amalfi-coast-2-room-1-Double-CityView",
    name: "Classic Double Penthouse",
    description: "Our Classic-themed double penthouse offers minimalist luxury, panoramic where the city skyline meets the horizon, and with a private balcony or terrace, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 226,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-amalfi-coast-2-room-1-King-MountainView",
    name: "Horizon King Penthouse",
    description: "This bohemian king penthouse promises where you can gaze at the towering peaks, enriched by Horizon-themed details and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Visual Aids"],
    pricePerNight: 367,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-amalfi-coast-2-room-1-SofaBed-None",
    name: "Classic Sofa Bed Villa",
    description: "Our Classic-themed sofa bed villa offers grandiose luxury, panoramic with a pleasant outlook, and with plush bedding for ultimate comfort, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 203,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-amalfi-coast-2-room-1-Queen-MountainView",
    name: "Executive Queen Apartment",
    description: "Unwind in this regal queen apartment with a view of the mountains' lush valleys, including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 310,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-amalfi-coast-2-room-1-Single-GardenView",
    name: "Luxury Single Villa",
    description: "A traditional single retreat where nature is just outside your window, featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 226,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  }
];
