// Auto-generated file for fort-kochi hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const fortKochiHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "communications@neemranaroyalhouse.com",
      contactPhone: "+496 789-449-2060",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-fort-kochi-1",
    name: "Neemrana Royal House",
    address: "137 Bandra Kurla Complex Marg",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 40,
    isPetFriendly: true,
    currency: "INR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "clientservices@vistarabayresidences.com",
      contactPhone: "+105 286-750-2884",
    },
    policies: {
      cancellation: "Full refund if cancelled within 48 hours of booking, minus service fees.",
      smoking: "Not Allowed",
    },
    id: "hotel-fort-kochi-2",
    name: "Vistara Bay Residences",
    address: "257 New Bandra Kurla Complex Path",
    rating: 4,
    accommodationType: "All-Inclusive Resort",
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 43,
    isPetFriendly: false,
    currency: "INR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "care@thebanyanhouse.com",
      contactPhone: "+805 391-677-7587",
    },
    policies: {
      cancellation: "Free cancellation within 24 hours of booking; after that, 25% fee applies.",
      smoking: "Allowed",
    },
    id: "hotel-fort-kochi-3",
    name: "The Banyan House",
    address: "213 Cross Bandra Kurla Complex Street",
    rating: 3,
    accommodationType: "Boutique Inn",
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 40,
    isPetFriendly: false,
    currency: "INR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "general@desertbloomlodge.com",
      contactPhone: "+481 560-394-4489",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-fort-kochi-4",
    name: "Desert Bloom Lodge",
    address: "161 Main Commercial Street Road",
    rating: 3,
    accommodationType: "Glamping Resort",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 53,
    isPetFriendly: true,
    currency: "INR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reachus@thesacredgangahotel.com",
      contactPhone: "+486 786-587-6397",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Allowed",
    },
    id: "hotel-fort-kochi-5",
    name: "The Sacred Ganga Hotel",
    address: "150 GT Connaught Place Marg",
    rating: 3,
    accommodationType: "Business Hotel",
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 13,
    isPetFriendly: false,
    currency: "INR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "feedback@thebanyanhouse.com",
      contactPhone: "+567 629-683-3294",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-fort-kochi-6",
    name: "The Banyan House",
    address: "202 SH MG Road Path",
    rating: 3,
    accommodationType: "Resort",
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 54,
    isPetFriendly: false,
    currency: "INR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "mail@monsoonmisthideaway.com",
      contactPhone: "+267 438-612-4308",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Allowed",
    },
    id: "hotel-fort-kochi-7",
    name: "Monsoon Mist Hideaway",
    address: "64 NH Marine Drive Street",
    rating: 4,
    accommodationType: "Luxury Lodge",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 14,
    isPetFriendly: true,
    currency: "INR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reachus@thepavilliongrand.com",
      contactPhone: "+486 635-526-4904",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-fort-kochi-8",
    name: "The Pavillion Grand",
    address: "6 GT Bandra Kurla Complex Vihar",
    rating: 4,
    accommodationType: "Eco-Lodge",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 36,
    isPetFriendly: true,
    currency: "INR",
    isPopular: false,
  },
  {
    id: "hotel-fort-kochi-9",
    name: "The Sacred Ganga Hotel",
    address: "2 Connaught Place Marg",
    rating: 3,
    accommodationType: "Luxury Villa",
    amenities: ["24-Hour Front Desk", "Free Wi-Fi", "Bar", "Conference Room", "Parking", "Swimming Pool", "Non-Smoking Rooms", "Airport Shuttle"],
    accessibilityFeatures: ["Accessible Pathways", "Assistive Listening Devices"],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 40,
    isPetFriendly: true,
    currency: "INR",
    contact: {
      contactEmail: "services@thesacredgangahotel.com",
      contactPhone: "+269 890-349-3732",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-fort-kochi-10",
    name: "Amber Fort Residency",
    address: "259 Cross Nehru Place Vihar",
    rating: 3,
    accommodationType: "Family Resort",
    amenities: ["Airport Shuttle", "24-Hour Front Desk", "Spa", "Business Center", "Laundry Service", "Free Wi-Fi", "Parking", "Swimming Pool", "Fitness Center"],
    accessibilityFeatures: ["Braille Signage"],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 15,
    isPetFriendly: false,
    currency: "INR",
    contact: {
      contactEmail: "help@amberfortresidency.com",
      contactPhone: "+688 670-938-4756",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-fort-kochi-11",
    name: "The Rajasthani Haveli",
    address: "112 Old Commercial Street Street",
    rating: 4,
    accommodationType: "Chalet",
    amenities: ["Bar", "Laundry Service", "Business Center", "24-Hour Front Desk", "Parking", "Conference Room", "Restaurant", "Spa"],
    accessibilityFeatures: ["Visual Aids", "Accessible Parking", "Hearing Support"],
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 17,
    isPetFriendly: false,
    currency: "INR",
    contact: {
      contactEmail: "feedback@therajasthanihaveli.com",
      contactPhone: "+209 557-800-5920",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  }
];
