import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Rajasthani Haveli
export const theRajasthaniHaveliRooms: RoomOption[] = [
  {
    id: "hotel-fort-kochi-11-room-10-Single-CityView",
    name: "Signature Single Villa",
    description: "Experience our sumptuous, comfortable single villa with a front-row seat to the city's heartbeat, with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 15612,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-fort-kochi-11-room-10-Double-OceanView",
    name: "Tranquility Double Suite",
    description: "Our Tranquility-themed double suite offers gentle luxury, panoramic where the ocean meets the sky, and with plush bedding for ultimate comfort, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 22332,
    currency: "INR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-fort-kochi-11-room-10-King-None",
    name: "Serenity King Loft",
    description: "Our Serenity-themed king loft offers ornate luxury, panoramic with a pleasant outlook, and offering a unique blend of style and comfort, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 24238,
    currency: "INR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-fort-kochi-11-room-10-SofaBed-GardenView",
    name: "Tranquility Sofa Bed Penthouse",
    description: "Unwind in this serene sofa bed penthouse where you can enjoy the garden's peaceful atmosphere, featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 15554,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-fort-kochi-11-room-10-Single-None",
    name: "Classic Single Loft",
    description: "Indulge in the commodious atmosphere of our single loft, with spectacular with a pleasant outlook, created with both style and function in mind, and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 13962,
    currency: "INR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-fort-kochi-11-room-10-Twin-CityView",
    name: "Classic Twin Apartment",
    description: "Our Classic-themed twin apartment offers lavish luxury, panoramic where the city skyline meets the horizon, and with a private balcony or terrace, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 17529,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-fort-kochi-11-room-10-Twin-None",
    name: "Classic Twin Apartment",
    description: "Enjoy a intimate stay in our Classic-themed twin apartment, offering with a pleasant outlook, with high-speed internet access, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 16220,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-fort-kochi-11-room-10-Double-None",
    name: "Serenity Double Loft",
    description: "Relax in our roomy open-concept double loft featuring with a pleasant outlook, along with complete with a well-appointed bathroom and decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 17460,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-fort-kochi-11-room-10-Double-CityView",
    name: "Premium Double Room",
    description: "Unwind in this contemporary double room where you can watch the city wake up, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 19836,
    currency: "INR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  }
];
