import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Concrete Garden
export const theConcreteGardenRooms: RoomOption[] = [
  {
    id: "hotel-monaco-6-room-5-SofaBed-CityView",
    name: "Classic Sofa Bed Apartment",
    description: "Classic-themed apartment with inviting decor, with stunning views of the city skyline, and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 79,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-monaco-6-room-5-Twin-CityView",
    name: "Modern Twin Villa",
    description: "Our compact Modern-themed villa offers with a window to the bustling city below, spacious comfort, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 81,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-monaco-6-room-5-Double-OceanView",
    name: "Modern Double Loft",
    description: "Enjoy a rustic stay in our Modern-themed double loft, offering overlooking the sparkling ocean waves, featuring premium bath amenities, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 107,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-monaco-6-room-5-King-GardenView",
    name: "Premium King Apartment",
    description: "This elegant king apartment promises where you can enjoy the tranquility of nature, enriched by Premium-themed details and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 136,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-monaco-6-room-5-SofaBed-None",
    name: "Standard Sofa Bed Studio",
    description: "A regal sofa bed retreat with a pleasant outlook, decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 72,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-monaco-6-room-5-Queen-OceanView",
    name: "Serenity Queen Villa",
    description: "Serenity-themed villa with avant-garde decor, where the ocean meets the sky, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 126,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-monaco-6-room-5-King-CityView",
    name: "Harmony King Loft",
    description: "Harmony-themed king loft with a backdrop of city parks and green spaces, featuring thoughtful design elements and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 121,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
