import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Gelsenkirchen City View
export const gelsenkirchenCityViewRooms: RoomOption[] = [
  {
    id: "hotel-kiel-7-room-6-Single-CityView",
    name: "Standard Single Penthouse",
    description: "Standard-themed single penthouse where the city comes alive at dusk, designed for ultimate comfort and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 140,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-kiel-7-room-6-SofaBed-GardenView",
    name: "Horizon Sofa Bed Villa",
    description: "Horizon-themed sofa bed villa with a view of the garden's seasonal changes, designed for ultimate comfort and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 195,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-kiel-7-room-6-Double-CityView",
    name: "Deluxe Double Suite",
    description: "Deluxe-themed suite with wide-ranging decor, with a view of the city's waterfront, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom", "Elevator"],
    pricePerNight: 185,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-kiel-7-room-6-Single-MountainView",
    name: "Signature Single Suite",
    description: "Discover the charm of this Signature-themed single suite, complete with serene ambiance, stunning with a view of the mountains' rugged terrain, and with a spacious work area.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 189,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  }
];
