import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Hannover Park Hotel
export const hannoverParkHotelRooms: RoomOption[] = [
  {
    id: "hotel-kiel-7-room-6-Queen-CityView",
    name: "Serenity Queen Loft",
    description: "Discover the charm of this Serenity-themed queen loft, complete with gentle ambiance, stunning where you can enjoy the city's energy, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 253,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-kiel-7-room-6-Twin-None",
    name: "Superior Twin Room",
    description: "This soft twin accommodation offers with a pleasant outlook, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 174,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-kiel-7-room-6-Single-OceanView",
    name: "Modern Single Loft",
    description: "Enjoy a glamorous stay in our Modern-themed single loft, offering with a view of the ocean's changing tides, with high-speed internet access, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 227,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-kiel-7-room-6-King-GardenView",
    name: "Premium King Suite",
    description: "Our Premium-themed king suite offers open-concept luxury, panoramic offering a peaceful garden outlook, and offering a unique blend of style and comfort, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 357,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-kiel-7-room-6-Queen-OceanView",
    name: "Premium Queen Suite",
    description: "Experience our palatial, tranquil queen suite where you can enjoy the ocean's beauty, with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 334,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-kiel-7-room-6-Single-None",
    name: "Tranquility Single Villa",
    description: "Indulge in the vintage atmosphere of our single villa, with spectacular with a pleasant outlook, decorated with local artistic influences, and featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 183,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-kiel-7-room-6-Single-CityView",
    name: "Modern Single Villa",
    description: "Experience our soft, regal single villa offering panoramic city vistas, with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 193,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-kiel-7-room-6-Double-MountainView",
    name: "Signature Double Apartment",
    description: "Experience our palatial, stylish double apartment with panoramic views of the mountain landscape, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 269,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-kiel-7-room-6-Queen-None",
    name: "Superior Queen Apartment",
    description: "Superior-themed apartment with vast decor, with a pleasant outlook, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Elevator", "Visual Aids"],
    pricePerNight: 275,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  }
];
