import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Nuremberg Castle Hotel
export const nurembergCastleHotelRooms: RoomOption[] = [
  {
    id: "hotel-kiel-11-room-10-SofaBed-CityView",
    name: "Signature Sofa Bed Villa",
    description: "A stretching sofa bed villa designed for generous comfort, with with a view of iconic landmarks and including climate control for your comfort, reflecting featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 191,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-kiel-11-room-10-Single-None",
    name: "Superior Single Villa",
    description: "Discover the charm of this Superior-themed single villa, complete with airy ambiance, stunning with a pleasant outlook, and with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 164,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-kiel-11-room-10-SofaBed-None",
    name: "Superior Sofa Bed Studio",
    description: "Experience our deluxe, relaxing sofa bed studio with a pleasant outlook, equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 191,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-kiel-11-room-10-King-GardenView",
    name: "Signature King Villa",
    description: "Our Signature-themed king villa offers generous luxury, panoramic with a view of the garden's peaceful ambiance, and with a spacious work area, inspired by decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 301,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-kiel-11-room-10-Twin-OceanView",
    name: "Standard Twin Apartment",
    description: "Standard-themed twin apartment with a view of the ocean's changing tides, decorated with local artistic influences and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 262,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-kiel-11-room-10-SofaBed-GardenView",
    name: "Executive Sofa Bed Room",
    description: "Discover the charm of this Executive-themed sofa bed room, complete with vintage ambiance, stunning with a view of tranquil water features, and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 236,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  }
];
