import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Urban Garden Hotel
export const urbanGardenHotelRooms: RoomOption[] = [
  {
    id: "hotel-kiel-7-room-6",
    name: "Horizon Sofa Bed Villa",
    description:
      "This tasteful sofa bed accommodation offers where you can relax in a natural oasis, featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Jacuzzi Tub",
      "Fireplace",
      "Connecting Rooms",
      "Complimentary Bottled Water",
      "Outdoor Furniture",
    ],
    pricePerNight: 219,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-kiel-7-room-6",
    name: "Classic Twin Studio",
    description:
      "Our Classic-themed twin studio offers minimalist luxury, panoramic where the ocean meets the sky, and equipped with all the modern conveniences, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Soundproofing",
      "Mini Bar",
      "Connecting Rooms",
      "Fitness Equipment",
    ],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 253,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-kiel-7-room-6",
    name: "Luxury King Penthouse",
    description:
      "Our extensive Luxury-themed penthouse offers where you can enjoy the city's energy, pleasant comfort, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Dining Table",
      "Kitchenette",
      "Flat-Screen TV",
      "Fireplace",
    ],
    pricePerNight: 378,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-kiel-7-room-6",
    name: "Tranquility Queen Penthouse",
    description:
      "Enjoy a chic stay in our Tranquility-themed queen penthouse, offering with a view of the ocean's changing tides, with high-speed internet access, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Kitchenette",
      "Refrigerator",
      "Seating Area",
      "Family Room",
      "Ironing Facilities",
      "Connecting Rooms",
    ],
    pricePerNight: 322,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
];
