import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Artigas City Hotel
export const artigasCityHotelRooms: RoomOption[] = [
  {
    id: "hotel-montevideo-6-room-5-Double-GardenView",
    name: "Colonia Double Studio",
    description: "Our intimate Colonia-themed studio offers with a view of the garden's natural beauty, majestic comfort, and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Hearing Support", "Accessible Bathroom"],
    pricePerNight: 378504,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-montevideo-6-room-5-Queen-MountainView",
    name: "Premium Queen Penthouse",
    description: "Relax in our ornate room-filled queen penthouse featuring with a view of the mountains' natural beauty, along with with a modern en-suite bathroom and highlighting relaxed South American style.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 496085,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-montevideo-6-room-5-Single-OceanView",
    name: "Signature Single Villa",
    description: "Relax in our majestic classic single villa featuring with a view of the tranquil sea, along with with a spacious seating area and featuring warm, earthy tones.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 353499,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-montevideo-6-room-5-Twin-GardenView",
    name: "Charrúa Twin Studio",
    description: "Experience our well-proportioned, elegant twin studio with a view of the garden's seasonal changes, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 331738,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-montevideo-6-room-5-King-OceanView",
    name: "Classic King Loft",
    description: "Our Classic-themed king loft offers deluxe luxury, panoramic with a view of the endless blue, and with plush bedding for ultimate comfort, inspired by offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 541908,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-montevideo-6-room-5-Single-CityView",
    name: "Standard Single Penthouse",
    description: "Indulge in the cozy atmosphere of our single penthouse, with spectacular with a view of iconic landmarks, blending colonial charm with modern simplicity, and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 296440,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-montevideo-6-room-5-Queen-None",
    name: "Colonia Queen Apartment",
    description: "A tasteful queen apartment designed for intimate comfort, with with a pleasant outlook and with blackout curtains for a perfect night's sleep, reflecting blending colonial charm with modern simplicity.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 355812,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  }
];
