import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Heritage View
export const heritageViewRooms: RoomOption[] = [
  {
    id: "hotel-montevideo-7-room-6-Twin-GardenView",
    name: "Deluxe Twin Loft",
    description: "Our ornate Deluxe-themed loft offers where you can enjoy the serenity of a garden retreat, welcoming comfort, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 226749,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-montevideo-7-room-6-SofaBed-OceanView",
    name: "Colonia Sofa Bed Room",
    description: "Indulge in the palatial atmosphere of our sofa bed room, with spectacular with a view of the tranquil sea, blending colonial charm with modern simplicity, and with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 276824,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-montevideo-7-room-6-SofaBed-CityView",
    name: "Classic Sofa Bed Penthouse",
    description: "A open-concept sofa bed retreat showcasing the urban landscape, featuring warm, earthy tones.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 211288,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-montevideo-7-room-6-Double-CityView",
    name: "Premium Double Apartment",
    description: "This cozy double accommodation offers with a window to the bustling city below, offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 245440,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-montevideo-7-room-6-King-OceanView",
    name: "Signature King Loft",
    description: "This minimalist king loft promises with a view of the endless blue, enriched by Signature-themed details and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 397253,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-montevideo-7-room-6-Double-OceanView",
    name: "Executive Double Loft",
    description: "Executive-themed loft with peaceful decor, where the horizon meets the ocean, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 320658,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-montevideo-7-room-6-Twin-None",
    name: "Luxury Twin Room",
    description: "Unwind in this bohemian twin room with a pleasant outlook, including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 221856,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-montevideo-7-room-6-Single-None",
    name: "Executive Single Loft",
    description: "Unwind in this calming single loft with a pleasant outlook, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 177035,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
