import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Melo Historic Inn
export const meloHistoricInnRooms: RoomOption[] = [
  {
    id: "hotel-montevideo-3-room-2-Double-None",
    name: "Montevideo Double Studio",
    description: "Indulge in the refreshing atmosphere of our double studio, with spectacular with a pleasant outlook, offering a cozy yet elegant atmosphere, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids"],
    pricePerNight: 345061,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-montevideo-3-room-2-Double-CityView",
    name: "Luxury Double Suite",
    description: "Luxury-themed suite with eclectic decor, with a view of iconic landmarks, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 337405,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-montevideo-3-room-2-Queen-CityView",
    name: "Gaucho Queen Penthouse",
    description: "Unwind in this eclectic queen penthouse with a view of iconic landmarks, featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 409027,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-montevideo-3-room-2-Double-OceanView",
    name: "Colonia Double Apartment",
    description: "Enjoy a large-scale stay in our Colonia-themed double apartment, offering with a private balcony overlooking the sea, with a luxurious soaking tub, and unique touches of offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 409502,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-montevideo-3-room-2-SofaBed-GardenView",
    name: "Atlantic Breeze Sofa Bed Loft",
    description: "Our Atlantic Breeze-themed sofa bed loft offers comfortable luxury, panoramic with a view of the garden's peaceful ambiance, and with carefully selected furnishings, inspired by highlighting relaxed South American style.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Elevator", "Accessible Bathroom"],
    pricePerNight: 356252,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  }
];
