import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Montevideo Bay Hotel
export const montevideoBayHotelRooms: RoomOption[] = [
  {
    id: "hotel-montevideo-1-room-0-Double-None",
    name: "Estancia Double Loft",
    description: "A contemporary double retreat with a pleasant outlook, offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 229703,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-montevideo-1-room-0-SofaBed-OceanView",
    name: "Superior Sofa Bed Studio",
    description: "Superior-themed sofa bed studio with a view of the ocean's changing tides, blending colonial charm with modern simplicity and with a spacious seating area.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 285264,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-montevideo-1-room-0-Single-OceanView",
    name: "Superior Single Villa",
    description: "Step into a lavish single villa that combines Superior-themed with breathtaking with breathtaking sea views, complemented by with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 241700,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-montevideo-1-room-0-Twin-CityView",
    name: "Colonia Twin Villa",
    description: "A cozy twin retreat with a backdrop of city parks and green spaces, featuring warm, earthy tones.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 234601,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-montevideo-1-room-0-Twin-None",
    name: "Signature Twin Penthouse",
    description: "A cozy twin penthouse designed for open-concept comfort, with with a pleasant outlook and with a modern en-suite bathroom, reflecting blending colonial charm with modern simplicity.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 209279,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-montevideo-1-room-0-Queen-OceanView",
    name: "Premium Queen Apartment",
    description: "Step into a tranquil queen apartment that combines Premium-themed with breathtaking with the sound of the ocean as your backdrop, complemented by with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 332445,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-montevideo-1-room-0-Single-MountainView",
    name: "Signature Single Suite",
    description: "Step into a sleek single suite that combines Signature-themed with breathtaking where you can enjoy the tranquility of the mountains, complemented by including climate control for your comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 205616,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-montevideo-1-room-0-Twin-MountainView",
    name: "Premium Twin Villa",
    description: "A elegant twin retreat with a view of snow-capped peaks, offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 242179,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-montevideo-1-room-0-King-GardenView",
    name: "Signature King Penthouse",
    description: "A expansive king penthouse designed for sophisticated comfort, with with a view of colorful flower beds and with plush bedding for ultimate comfort, reflecting offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 349518,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  }
];
