import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Paysandú Riverside Hotel
export const paysandRiversideHotelRooms: RoomOption[] = [
  {
    id: "hotel-montevideo-6-room-5-Twin-CityView",
    name: "Luxury Twin Penthouse",
    description: "A bohemian twin retreat with stunning views of the city skyline, offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 131865,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-montevideo-6-room-5-King-MountainView",
    name: "Montevideo King Villa",
    description: "Unwind in this refreshing king villa where you can enjoy the mountains' majestic presence, equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator", "Hearing Support"],
    pricePerNight: 222000,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-montevideo-6-room-5-Double-None",
    name: "Standard Double Loft",
    description: "A heartwarming double loft designed for sumptuous comfort, with with a pleasant outlook and equipped with all the modern conveniences, reflecting blending colonial charm with modern simplicity.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 125480,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-montevideo-6-room-5-Single-OceanView",
    name: "Montevideo Single Room",
    description: "Montevideo-themed single room with a view of the tranquil sea, offering a cozy yet elegant atmosphere and with a spacious seating area.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 131295,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-montevideo-6-room-5-SofaBed-GardenView",
    name: "Superior Sofa Bed Room",
    description: "Enjoy a modern stay in our Superior-themed sofa bed room, offering offering a peaceful garden outlook, with a spacious work area, and unique touches of highlighting relaxed South American style.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 123440,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-montevideo-6-room-5-Twin-None",
    name: "Deluxe Twin Studio",
    description: "This tasteful twin studio promises with a pleasant outlook, enriched by Deluxe-themed details and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 104918,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-montevideo-6-room-5-King-None",
    name: "Executive King Penthouse",
    description: "Discover the charm of this Executive-themed king penthouse, complete with eclectic ambiance, stunning with a pleasant outlook, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 189037,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-montevideo-6-room-5-Double-GardenView",
    name: "Classic Double Apartment",
    description: "Indulge in the avant-garde atmosphere of our double apartment, with spectacular where you can take in the fresh air, blending colonial charm with modern simplicity, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 152455,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  }
];
