import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Charrúa Inn
export const theCharraInnRooms: RoomOption[] = [
  {
    id: "hotel-montevideo-4-room-3-SofaBed-OceanView",
    name: "Charrúa Sofa Bed Apartment",
    description: "Our intimate Charrúa-themed apartment offers where the horizon meets the ocean, pleasant comfort, and with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 526627,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-montevideo-4-room-3-Queen-None",
    name: "Executive Queen Suite",
    description: "Experience our industrial, glamorous queen suite with a pleasant outlook, with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 465100,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-montevideo-4-room-3-Single-None",
    name: "Premium Single Loft",
    description: "Our Premium-themed single loft offers minimalist luxury, panoramic with a pleasant outlook, and with high-speed internet access, inspired by featuring warm, earthy tones.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids"],
    pricePerNight: 340416,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-montevideo-4-room-3-Twin-MountainView",
    name: "Atlantic Breeze Twin Apartment",
    description: "Enjoy a majestic stay in our Atlantic Breeze-themed twin apartment, offering with a view of the mountains' breathtaking sunsets, featuring a curated minibar selection, and unique touches of blending colonial charm with modern simplicity.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Elevator", "Accessible Bathroom", "Visual Aids"],
    pricePerNight: 499005,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-montevideo-4-room-3-Double-GardenView",
    name: "Classic Double Penthouse",
    description: "Relax in our sleek roomy double penthouse featuring where nature is just outside your window, along with with a spacious seating area and offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Visual Aids", "Hearing Support"],
    pricePerNight: 464454,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-montevideo-4-room-3-King-GardenView",
    name: "Classic King Studio",
    description: "Unwind in this exquisite king studio where you can enjoy the sights and sounds of nature, featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 680157,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
