import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Harbor House
export const theHarborHouseRooms: RoomOption[] = [
  {
    id: "hotel-montevideo-5-room-4",
    name: "Classic Single Studio",
    description: "Indulge in the indulgent atmosphere of our single studio, with spectacular where you can watch the city wake up, offering a cozy yet elegant atmosphere, and including climate control for your comfort.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Jacuzzi Tub", "Bathtub", "Smoke Detector", "Family Room"],
    pricePerNight: 179,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-montevideo-5-room-4",
    name: "Montevideo Twin Loft",
    description: "Unwind in this traditional twin loft overlooking lush garden landscapes, featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Smoke Detector", "Flat-Screen TV", "Books", "Connecting Rooms", "Kitchenette"],
    pricePerNight: 207,
    currency: "UYU",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-montevideo-5-room-4",
    name: "Charrúa Double Penthouse",
    description: "Enjoy a wide-ranging stay in our Charrúa-themed double penthouse, offering with a view of the city's waterfront, with a spacious seating area, and unique touches of highlighting relaxed South American style.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Books", "Connecting Rooms", "Jacuzzi Tub", "Board Games", "Accessible Room", "Flat-Screen TV"],
    pricePerNight: 232,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-montevideo-5-room-4",
    name: "Montevideo Sofa Bed Room",
    description: "Our Montevideo-themed sofa bed room offers soothing luxury, panoramic where you can find solace in nature's embrace, and with carefully selected furnishings, inspired by offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Ironing Facilities", "Connecting Rooms", "Refrigerator", "Kitchenette", "Mini Bar"],
    accessibilityFeatures: ["Elevator", "Visual Aids"],
    pricePerNight: 188,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-montevideo-5-room-4",
    name: "Charrúa Sofa Bed Suite",
    description: "Our Charrúa-themed sofa bed suite offers comfy luxury, panoramic with a view of the ocean's horizon, and featuring a curated minibar selection, inspired by offering a cozy yet elegant atmosphere.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping", "Non-Smoking Room", "Television", "Air Conditioning", "Pet Friendly", "Refrigerator", "Ironing Facilities", "Connecting Rooms", "Bathtub", "Seating Area"],
    pricePerNight: 245,
    currency: "UYU",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  }
];
