import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Pine Valley Retreat
export const pineValleyRetreatRooms: RoomOption[] = [
  {
    id: "hotel-fort-lauderdale-11-room-10-King-GardenView",
    name: "Standard King Apartment",
    description: "Standard-themed apartment with snug decor, where you can take in the fresh air, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 282,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-fort-lauderdale-11-room-10-Queen-OceanView",
    name: "Classic Queen Apartment",
    description: "Enjoy a indulgent stay in our Classic-themed queen apartment, offering with a view of the ocean's horizon, with a spacious seating area, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 253,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-fort-lauderdale-11-room-10-Queen-CityView",
    name: "Harmony Queen Villa",
    description: "A rustic queen retreat with a backdrop of city parks and green spaces, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 204,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-fort-lauderdale-11-room-10-King-MountainView",
    name: "Premium King Villa",
    description: "Premium-themed king villa with a view of the mountains' serene beauty, decorated with local artistic influences and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 319,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-fort-lauderdale-11-room-10-King-CityView",
    name: "Classic King Suite",
    description: "This deluxe king accommodation offers where the city comes alive at dusk, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 268,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-fort-lauderdale-11-room-10-Twin-OceanView",
    name: "Deluxe Twin Penthouse",
    description: "Unwind in this avant-garde twin penthouse with a view of the tranquil sea, with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 211,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  }
];
