import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Dancing Dragonfly
export const theDancingDragonflyRooms: RoomOption[] = [
  {
    id: "hotel-fort-lauderdale-7-room-6-Double-CityView",
    name: "Deluxe Double Studio",
    description: "Deluxe-themed double studio with a view of the city's cultural landmarks, designed for ultimate comfort and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 241,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-fort-lauderdale-7-room-6-Queen-GardenView",
    name: "Deluxe Queen Penthouse",
    description: "Relax in our indulgent homey queen penthouse featuring where nature is just outside your window, along with with a luxurious soaking tub and decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 303,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-fort-lauderdale-7-room-6-Twin-CityView",
    name: "Signature Twin Room",
    description: "A expansive twin room designed for peaceful comfort, with where you can enjoy the city's energy and with a luxurious soaking tub, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids", "Accessible Bathroom"],
    pricePerNight: 227,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-fort-lauderdale-7-room-6-Single-MountainView",
    name: "Luxury Single Penthouse",
    description: "A modern single retreat where you can experience the beauty of nature, featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 263,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-fort-lauderdale-7-room-6-Double-None",
    name: "Standard Double Room",
    description: "This airy double room promises with a pleasant outlook, enriched by Standard-themed details and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 262,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-fort-lauderdale-7-room-6-Single-GardenView",
    name: "Standard Single Penthouse",
    description: "Step into a pleasant single penthouse that combines Standard-themed with breathtaking with a view of the garden's natural beauty, complemented by with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 221,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  }
];
