import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Grand Central Hotel
export const grandCentralHotelRooms: RoomOption[] = [
  {
    id: "hotel-santiago-6-room-5-Double-GardenView",
    name: "Lakes Double Suite",
    description: "This large-scale double suite promises with serene garden views, enriched by Lakes-themed details and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 92831,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-santiago-6-room-5-Single-None",
    name: "Superior Single Apartment",
    description: "This sophisticated single apartment promises with a pleasant outlook, enriched by Superior-themed details and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 61924,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-santiago-6-room-5-Queen-GardenView",
    name: "Premium Queen Apartment",
    description: "Discover the charm of this Premium-themed queen apartment, complete with peaceful ambiance, stunning featuring a peaceful garden setting, and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 104834,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-santiago-6-room-5-Double-OceanView",
    name: "Luxury Double Apartment",
    description: "Our Luxury-themed double apartment offers sophisticated luxury, panoramic with a panoramic view of the coastline, and with a private balcony or terrace, inspired by highlighting the beauty of Chilean landscapes.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 99959,
    currency: "CLP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-santiago-6-room-5-Twin-GardenView",
    name: "Premium Twin Villa",
    description: "Unwind in this regal twin villa where you can enjoy the sights and sounds of nature, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 79916,
    currency: "CLP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-santiago-6-room-5-SofaBed-OceanView",
    name: "Standard Sofa Bed Loft",
    description: "A comfy sofa bed loft designed for tasteful comfort, with where you can feel the ocean breeze and including climate control for your comfort, reflecting featuring minimalist and natural decor.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 87707,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
