import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Pacific Coast Suites
export const thePacificCoastSuitesRooms: RoomOption[] = [
  {
    id: "hotel-santiago-1-room-0-Queen-MountainView",
    name: "Deluxe Queen Penthouse",
    description: "Our wide-ranging Deluxe-themed penthouse offers with a view of the mountains' changing seasons, peaceful comfort, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 204387616,
    currency: "CLP",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-santiago-1-room-0-King-GardenView",
    name: "Executive King Villa",
    description: "This traditional king villa promises where you can unwind in a garden paradise, enriched by Executive-themed details and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 195201373,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-santiago-1-room-0-Double-CityView",
    name: "Luxury Double Villa",
    description: "Relax in our commodious rustic double villa featuring where you can enjoy the city's energy, along with featuring premium bath amenities and offering serene and refined interiors.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 158447859,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-santiago-1-room-0-Twin-CityView",
    name: "Patagonia Twin Room",
    description: "A vintage twin retreat with a view of the city's waterfront, highlighting the beauty of Chilean landscapes.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 121602211,
    currency: "CLP",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-santiago-1-room-0-King-CityView",
    name: "Superior King Apartment",
    description: "Enjoy a elegant stay in our Superior-themed king apartment, offering where the city comes alive at dusk, including climate control for your comfort, and unique touches of featuring minimalist and natural decor.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom", "Elevator"],
    pricePerNight: 207831962,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-santiago-1-room-0-Single-GardenView",
    name: "Torres del Paine Single Apartment",
    description: "Discover the charm of this Torres del Paine-themed single apartment, complete with generous ambiance, stunning where you can enjoy the sights and sounds of nature, and with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 113834051,
    currency: "CLP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-santiago-1-room-0-Queen-GardenView",
    name: "Viña Queen Villa",
    description: "This soothing queen accommodation offers overlooking lush garden landscapes, featuring minimalist and natural decor.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 169353299,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-santiago-1-room-0-King-None",
    name: "Superior King Room",
    description: "Our large-scale Superior-themed room offers with a pleasant outlook, intimate comfort, and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 186712808,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
