import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Torres del Paine Hotel
export const theTorresDelPaineHotelRooms: RoomOption[] = [
  {
    id: "hotel-santiago-9-room-8-Double-None",
    name: "Luxury Double Loft",
    description: "Luxury-themed double loft with a pleasant outlook, blending Andean and coastal influences and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 66057855,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-santiago-9-room-8-Double-OceanView",
    name: "Viña Double Apartment",
    description: "Experience our regal, broad double apartment with the sound of the ocean as your backdrop, with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 82980711,
    currency: "CLP",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-santiago-9-room-8-King-GardenView",
    name: "Atacama King Suite",
    description: "Unwind in this well-proportioned king suite featuring a peaceful garden setting, with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 110788172,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-santiago-9-room-8-King-OceanView",
    name: "Atacama King Apartment",
    description: "Atacama-themed king apartment with a private balcony overlooking the sea, offering serene and refined interiors and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 127840541,
    currency: "CLP",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-santiago-9-room-8-Single-GardenView",
    name: "Andes Single Suite",
    description: "Our vast Andes-themed suite offers with a view of blooming flowers and greenery, sumptuous comfort, and including climate control for your comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 57472846,
    currency: "CLP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-santiago-9-room-8-Queen-CityView",
    name: "Deluxe Queen Villa",
    description: "Relax in our tranquil soothing queen villa featuring featuring a blend of modern and historic architecture, along with with a private balcony or terrace and blending Andean and coastal influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 91776231,
    currency: "CLP",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  }
];
