import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Cozy Cuckoo
export const theCozyCuckooRooms: RoomOption[] = [
  {
    id: "hotel-new-orleans-11-room-10-SofaBed-MountainView",
    name: "Premium Sofa Bed Suite",
    description: "A cozy sofa bed suite designed for plush comfort, with with a view of the mountains' breathtaking sunsets and including climate control for your comfort, reflecting decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Wheelchair Accessible", "Accessible Bathroom"],
    pricePerNight: 116,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-new-orleans-11-room-10-Single-MountainView",
    name: "Classic Single Room",
    description: "Experience our relaxing, commodious single room with a view of the rugged mountain landscape, with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 101,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-new-orleans-11-room-10-Twin-OceanView",
    name: "Executive Twin Studio",
    description: "Unwind in this soothing twin studio where you can watch the waves roll in, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 113,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-new-orleans-11-room-10-Double-OceanView",
    name: "Modern Double Penthouse",
    description: "Our Modern-themed double penthouse offers comfy luxury, panoramic where you can relax to the sound of the waves, and with carefully selected furnishings, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 117,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-new-orleans-11-room-10-Single-GardenView",
    name: "Premium Single Villa",
    description: "A palatial single retreat with a view of manicured lawns and gardens, created with both style and function in mind.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 86,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-new-orleans-11-room-10-King-MountainView",
    name: "Serenity King Villa",
    description: "This broad king villa promises where mountains paint the horizon, enriched by Serenity-themed details and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 171,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  }
];
