import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Jolly Jackrabbit
export const theJollyJackrabbitRooms: RoomOption[] = [
  {
    id: "hotel-new-orleans-5-room-4-Double-GardenView",
    name: "Horizon Double Loft",
    description: "Discover the charm of this Horizon-themed double loft, complete with intimate ambiance, stunning with a view of colorful flower beds, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 274,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-new-orleans-5-room-4-Double-OceanView",
    name: "Tranquility Double Villa",
    description: "Our Tranquility-themed double villa offers rustic luxury, panoramic where you can enjoy stunning sunsets over the water, and with plush bedding for ultimate comfort, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 303,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-new-orleans-5-room-4-Queen-None",
    name: "Serenity Queen Studio",
    description: "Step into a comfy queen studio that combines Serenity-themed with breathtaking with a pleasant outlook, complemented by with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 289,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-new-orleans-5-room-4-Twin-OceanView",
    name: "Deluxe Twin Suite",
    description: "Unwind in this comfortable twin suite where you can watch the waves roll in, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 285,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  }
];
