import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Velvet Fox
export const theVelvetFoxRooms: RoomOption[] = [
  {
    id: "hotel-new-orleans-7-room-6-King-None",
    name: "Classic King Studio",
    description: "Relax in our stretching roomy king studio featuring with a pleasant outlook, along with featuring premium bath amenities and decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 268,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-new-orleans-7-room-6-Queen-GardenView",
    name: "Premium Queen Room",
    description: "Enjoy a voluminous stay in our Premium-themed queen room, offering with a view of shaded garden paths, with a private balcony or terrace, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 270,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-new-orleans-7-room-6-Double-CityView",
    name: "Signature Double Loft",
    description: "A soothing double loft designed for regal comfort, with where you can enjoy the city's energy and with blackout curtains for a perfect night's sleep, reflecting featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 209,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-new-orleans-7-room-6-Single-None",
    name: "Classic Single Villa",
    description: "Enjoy a sleek stay in our Classic-themed single villa, offering with a pleasant outlook, with a luxurious soaking tub, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 159,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-new-orleans-7-room-6-Double-GardenView",
    name: "Harmony Double Suite",
    description: "Experience our minimalist, sizable double suite surrounded by vibrant flora, with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 233,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-new-orleans-7-room-6-Queen-OceanView",
    name: "Luxury Queen Suite",
    description: "Discover the charm of this Luxury-themed queen suite, complete with sophisticated ambiance, stunning where you can enjoy stunning sunsets over the water, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 306,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-new-orleans-7-room-6-Twin-OceanView",
    name: "Standard Twin Penthouse",
    description: "Standard-themed twin penthouse where you can watch the waves roll in, featuring thoughtful design elements and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 246,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-new-orleans-7-room-6-King-GardenView",
    name: "Superior King Studio",
    description: "Enjoy a sizable stay in our Superior-themed king studio, offering where you can enjoy the sights and sounds of nature, with carefully selected furnishings, and unique touches of featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 328,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-new-orleans-7-room-6-King-CityView",
    name: "Deluxe King Studio",
    description: "A sleek king retreat showcasing the urban landscape, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 338,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-new-orleans-7-room-6-SofaBed-MountainView",
    name: "Classic Sofa Bed Villa",
    description: "Experience our broad, futuristic sofa bed villa where you can enjoy the mountains' majestic presence, with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 241,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  }
];
