// Auto-generated file for kyoto hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const kyotoHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "office@hiroshimaatomicdomehotel.com",
      contactPhone: "+370 113-407-1585",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-kyoto-1",
    name: "Hiroshima Atomic Dome Hotel",
    address: "Akihabara Koji 180",
    rating: 4,
    accommodationType: "Extended Stay Hotel",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 11,
    isPetFriendly: false,
    currency: "JPY",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "services@kochiriverview.com",
      contactPhone: "+114 738-826-4343",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-kyoto-2",
    name: "Kochi River View",
    address: "Shin Shinjuku Banchi 258",
    rating: 4,
    accommodationType: "Luxury Hotel",
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 11,
    isPetFriendly: false,
    currency: "JPY",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "welcome@yamagatacherryhotel.com",
      contactPhone: "+186 104-913-8203",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-kyoto-3",
    name: "Yamagata Cherry Hotel",
    address: "Hon Aoyama Dori 102",
    rating: 4,
    accommodationType: "Luxury Lodge",
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 40,
    isPetFriendly: true,
    currency: "JPY",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "support@hikarihotel.com",
      contactPhone: "+540 861-244-8208",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-kyoto-4",
    name: "Hikari Hotel",
    address: "Minami Ginza Dori 23",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 44,
    isPetFriendly: false,
    currency: "JPY",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "communications@yamaguchicoastalhotel.com",
      contactPhone: "+352 811-935-2564",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Not Allowed",
    },
    id: "hotel-kyoto-5",
    name: "Yamaguchi Coastal Hotel",
    address: "Shinjuku Koji 251",
    rating: 4,
    accommodationType: "Eco-Lodge",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 36,
    isPetFriendly: false,
    currency: "JPY",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "inquiries@osakaserenity.com",
      contactPhone: "+701 741-638-7305",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Designated Areas",
    },
    id: "hotel-kyoto-6",
    name: "Osaka Serenity",
    address: "Hon Ginza Dori 99",
    rating: 4,
    accommodationType: "Luxury Hotel",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 25,
    isPetFriendly: false,
    currency: "JPY",
    isPopular: true,
  },
  {
    id: "hotel-kyoto-7",
    name: "Tottori Sand Dunes Hotel",
    address: "Ueno Banchi 63",
    rating: 4,
    accommodationType: "Boutique Resort",
    amenities: ["Spa", "Laundry Service", "Free Wi-Fi", "Airport Shuttle", "Conference Room", "Non-Smoking Rooms", "Room Service", "Restaurant", "Business Center", "Parking"],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 43,
    isPetFriendly: false,
    currency: "JPY",
    contact: {
      contactEmail: "general@tottorisandduneshotel.com",
      contactPhone: "+617 292-233-9559",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    isPopular: true,
  },
  {
    id: "hotel-kyoto-8",
    name: "Okinawa Coral Hotel",
    address: "Ueno Dori 6",
    rating: 3,
    accommodationType: "Eco-Lodge",
    amenities: ["Free Wi-Fi", "Bar", "Airport Shuttle", "Business Center", "Spa", "24-Hour Front Desk", "Laundry Service", "Restaurant", "Parking"],
    accessibilityFeatures: ["Wheelchair Accessible", "Tactile Maps", "Elevator"],
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 35,
    isPetFriendly: false,
    currency: "JPY",
    contact: {
      contactEmail: "hi@okinawacoralhotel.com",
      contactPhone: "+687 420-344-7448",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-kyoto-9",
    name: "Kamakura Zen Hotel",
    address: "Minami Ueno Dori 55",
    rating: 4,
    accommodationType: "Chalet",
    amenities: ["Parking", "Business Center", "Conference Room", "Free Wi-Fi", "24-Hour Front Desk", "Room Service", "Laundry Service", "Spa", "Swimming Pool", "Fitness Center"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Alarm", "Assistive Listening Devices"],
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 59,
    isPetFriendly: false,
    currency: "JPY",
    contact: {
      contactEmail: "ask@kamakurazenhotel.com",
      contactPhone: "+355 551-496-5271",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  }
];
