import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Okinawa Beachfront Hotel
export const okinawaBeachfrontHotelRooms: RoomOption[] = [
  {
    id: "hotel-kyoto-4-room-3-Queen-OceanView",
    name: "Bamboo Queen Villa",
    description: "This classic queen accommodation offers with a view of the ocean's changing tides, combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 7004192,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-kyoto-4-room-3-Queen-None",
    name: "Standard Queen Room",
    description: "Experience our sophisticated, large-scale queen room with a pleasant outlook, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 5520848,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-kyoto-4-room-3-SofaBed-GardenView",
    name: "Standard Sofa Bed Apartment",
    description: "Relax in our lavish elegant sofa bed apartment featuring with a view of blooming flowers and greenery, along with offering a unique blend of style and comfort and combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 4245561,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-kyoto-4-room-3-Queen-GardenView",
    name: "Superior Queen Room",
    description: "A snug queen room designed for comfortable comfort, with where you can find solace in nature's embrace and including climate control for your comfort, reflecting combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 5714322,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-kyoto-4-room-3-Queen-MountainView",
    name: "Standard Queen Villa",
    description: "This generous queen accommodation offers with a view of the mountains' serene beauty, offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 6803800,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-kyoto-4-room-3-Twin-GardenView",
    name: "Deluxe Twin Studio",
    description: "Deluxe-themed studio with welcoming decor, with a view of the garden's seasonal changes, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 5065417,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-kyoto-4-room-3-Single-GardenView",
    name: "Superior Single Apartment",
    description: "Unwind in this cozy single apartment with serene garden views, equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 4426930,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  }
];
