import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Osaka Serenity
export const osakaSerenityRooms: RoomOption[] = [
  {
    id: "hotel-kyoto-6-room-5-SofaBed-None",
    name: "Standard Sofa Bed Studio",
    description: "This contemporary sofa bed studio promises with a pleasant outlook, enriched by Standard-themed details and featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 5291226,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-kyoto-6-room-5-Single-MountainView",
    name: "Zen Single Apartment",
    description: "Relax in our calming extravagant single apartment featuring where you can find inspiration in the mountains, along with with plush bedding for ultimate comfort and offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 5808662,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-kyoto-6-room-5-Double-OceanView",
    name: "Imperial Double Apartment",
    description: "Unwind in this welcoming double apartment with breathtaking sea views, with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids"],
    pricePerNight: 7531165,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-kyoto-6-room-5-King-CityView",
    name: "Signature King Room",
    description: "Experience our majestic, palatial king room featuring a blend of modern and historic architecture, with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 9136991,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-kyoto-6-room-5-King-MountainView",
    name: "Executive King Room",
    description: "This classic king accommodation offers featuring awe-inspiring mountain scenery, offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 9597284,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-kyoto-6-room-5-Single-None",
    name: "Premium Single Room",
    description: "Enjoy a lavish stay in our Premium-themed single room, offering with a pleasant outlook, complete with a well-appointed bathroom, and unique touches of combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 4292014,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  }
];
