import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Outback Lodge
export const theOutbackLodgeRooms: RoomOption[] = [
  {
    id: "hotel-sydney-4-room-3-Single-GardenView",
    name: "Oceanic Single Loft",
    description: "A refined single loft designed for relaxing comfort, with where you can unwind in a garden paradise and including climate control for your comfort, reflecting featuring airy, sun-drenched interiors.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 195,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-sydney-4-room-3-King-None",
    name: "Koala King Apartment",
    description: "This avant-garde king accommodation offers with a pleasant outlook, featuring airy, sun-drenched interiors.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 299,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-sydney-4-room-3-Twin-OceanView",
    name: "Executive Twin Loft",
    description: "Step into a prestigious twin loft that combines Executive-themed with breathtaking where you can hear the soothing sound of the sea, complemented by with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 267,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-sydney-4-room-3-Twin-GardenView",
    name: "Superior Twin Loft",
    description: "Our pleasant Superior-themed loft offers with a view of colorful flower beds, prestigious comfort, and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 260,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-sydney-4-room-3-Double-GardenView",
    name: "Coral Reef Double Room",
    description: "Unwind in this roomy double room offering a peaceful garden outlook, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 278,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-sydney-4-room-3-SofaBed-CityView",
    name: "Premium Sofa Bed Loft",
    description: "Premium-themed loft with retro decor, overlooking the vibrant cityscape, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 248,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-sydney-4-room-3-Double-CityView",
    name: "Superior Double Room",
    description: "Experience our homey, welcoming double room with a view of iconic landmarks, with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 239,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-sydney-4-room-3-Queen-OceanView",
    name: "Executive Queen Studio",
    description: "Executive-themed studio with modern decor, with the sound of the ocean as your backdrop, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids"],
    pricePerNight: 329,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-sydney-4-room-3-Queen-None",
    name: "Oceanic Queen Loft",
    description: "Oceanic-themed queen loft with a pleasant outlook, blending natural textures with modern style and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 288,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  }
];
