import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Scenic View Inn
export const theScenicViewInnRooms: RoomOption[] = [
  {
    id: "hotel-quito-7-room-6-Twin-OceanView",
    name: "Deluxe Twin Suite",
    description: "Deluxe-themed twin suite where you can hear the soothing sound of the sea, designed for ultimate comfort and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 279,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-quito-7-room-6-SofaBed-CityView",
    name: "Signature Sofa Bed Villa",
    description: "Discover the charm of this Signature-themed sofa bed villa, complete with traditional ambiance, stunning with stunning views of the city skyline, and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 245,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-quito-7-room-6-Double-OceanView",
    name: "Executive Double Studio",
    description: "A well-proportioned double studio designed for upscale comfort, with where you can enjoy stunning sunsets over the water and with a spacious work area, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 341,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-quito-7-room-6-King-CityView",
    name: "Tranquility King Loft",
    description: "Experience our elegant, grandiose king loft where the city comes alive at dusk, with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 377,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-quito-7-room-6-Queen-MountainView",
    name: "Deluxe Queen Penthouse",
    description: "Our Deluxe-themed queen penthouse offers classic luxury, panoramic where you can take in the fresh mountain air, and featuring premium bath amenities, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 354,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-quito-7-room-6-Queen-OceanView",
    name: "Serenity Queen Loft",
    description: "Serenity-themed loft with welcoming decor, where you can relax to the sound of the waves, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 351,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
