import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Hotel National, Moscow
export const hotelNationalMoscowRooms: RoomOption[] = [
  {
    id: "hotel-st-petersburg-6-room-5-Single-OceanView",
    name: "Deluxe Single Penthouse",
    description: "A comfy single penthouse designed for plush comfort, with where you can enjoy stunning sunsets over the water and with a modern en-suite bathroom, reflecting created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 16838,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-st-petersburg-6-room-5-Single-MountainView",
    name: "Standard Single Suite",
    description: "This upscale single accommodation offers with a view of the mountains' serene beauty, designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 15310,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-st-petersburg-6-room-5-Twin-None",
    name: "Signature Twin Studio",
    description: "Signature-themed twin studio with a pleasant outlook, featuring thoughtful design elements and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 14062,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-st-petersburg-6-room-5-Single-CityView",
    name: "Modern Single Studio",
    description: "Relax in our rustic grandiose single studio featuring with a view of iconic landmarks, along with complete with a well-appointed bathroom and featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 14112,
    currency: "RUB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-st-petersburg-6-room-5-SofaBed-OceanView",
    name: "Premium Sofa Bed Suite",
    description: "Our Premium-themed sofa bed suite offers traditional luxury, panoramic where the horizon meets the ocean, and with blackout curtains for a perfect night's sleep, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 19468,
    currency: "RUB",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
