import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Érd Danube Bend Hotel
export const rdDanubeBendHotelRooms: RoomOption[] = [
  {
    id: "hotel-budapest-3-room-2-Single-MountainView",
    name: "Signature Single Penthouse",
    description: "Relax in our welcoming stretching single penthouse featuring with a view of the mountains' lush valleys, along with with a private balcony or terrace and designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 16063795,
    currency: "HUF",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-budapest-3-room-2-SofaBed-CityView",
    name: "Superior Sofa Bed Room",
    description: "Experience our fashionable, snug sofa bed room with stunning views of the city skyline, with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 16578839,
    currency: "HUF",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-budapest-3-room-2-Twin-GardenView",
    name: "Standard Twin Penthouse",
    description: "Our Standard-themed twin penthouse offers stylish luxury, panoramic with serene garden views, and complete with a well-appointed bathroom, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 15175968,
    currency: "HUF",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-budapest-3-room-2-King-None",
    name: "Premium King Villa",
    description: "Premium-themed king villa with a pleasant outlook, featuring thoughtful design elements and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 23292129,
    currency: "HUF",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-budapest-3-room-2-Double-OceanView",
    name: "Tranquility Double Loft",
    description: "Unwind in this fashionable double loft with breathtaking sea views, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 21332165,
    currency: "HUF",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-budapest-3-room-2-SofaBed-GardenView",
    name: "Signature Sofa Bed Suite",
    description: "A soft sofa bed suite designed for open-concept comfort, with offering a peaceful garden outlook and with a spacious work area, reflecting featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 17658360,
    currency: "HUF",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-budapest-3-room-2-Queen-None",
    name: "Premium Queen Apartment",
    description: "Relax in our intimate traditional queen apartment featuring with a pleasant outlook, along with with a luxurious soaking tub and decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 17577389,
    currency: "HUF",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
