import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Lotus Heritage Hotel
export const theLotusHeritageHotelRooms: RoomOption[] = [
  {
    id: "hotel-jaipur-5-room-4-Double-CityView",
    name: "Lotus Double Loft",
    description: "Our modern Lotus-themed loft offers showcasing the urban landscape, rustic comfort, and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 1982096,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-jaipur-5-room-4-Twin-None",
    name: "Executive Twin Studio",
    description: "A regal twin studio designed for room-filled comfort, with with a pleasant outlook and including climate control for your comfort, reflecting offering vibrant colors and luxurious details.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids", "Wheelchair Accessible"],
    pricePerNight: 1385244,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-jaipur-5-room-4-King-MountainView",
    name: "Superior King Penthouse",
    description: "Our roomy Superior-themed penthouse offers with majestic mountain vistas, traditional comfort, and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 2794724,
    currency: "INR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-jaipur-5-room-4-Single-CityView",
    name: "Bollywood Single Apartment",
    description: "A opulent single apartment designed for sleek comfort, with where the city skyline meets the horizon and with high-speed internet access, reflecting blending traditional Indian motifs with modern comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 1361404,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-jaipur-5-room-4-King-GardenView",
    name: "Bollywood King Studio",
    description: "Indulge in the wide-ranging atmosphere of our king studio, with spectacular featuring a peaceful garden setting, offering vibrant colors and luxurious details, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 2661929,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-jaipur-5-room-4-Single-None",
    name: "Premium Single Room",
    description: "Our majestic Premium-themed room offers with a pleasant outlook, broad comfort, and with a spacious work area.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 1453211,
    currency: "INR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-jaipur-5-room-4-Double-GardenView",
    name: "Signature Double Room",
    description: "Our Signature-themed double room offers soothing luxury, panoramic where you can unwind in a garden paradise, and with blackout curtains for a perfect night's sleep, inspired by blending traditional Indian motifs with modern comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 1727712,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-jaipur-5-room-4-Queen-GardenView",
    name: "Premium Queen Loft",
    description: "Unwind in this plush queen loft with a view of colorful flower beds, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 2487828,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-jaipur-5-room-4-Twin-OceanView",
    name: "Holi Twin Studio",
    description: "This soothing twin accommodation offers where you can hear the soothing sound of the sea, highlighting cultural depth and warmth.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 2072321,
    currency: "INR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-jaipur-5-room-4-Double-MountainView",
    name: "Deluxe Double Loft",
    description: "Our serene Deluxe-themed loft offers where you can escape to the mountains, contemporary comfort, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 2066640,
    currency: "INR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  }
];
