// Auto-generated file for qaqortoq hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const qaqortoqHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "reception@pinehillvista.com",
      contactPhone: "+488 365-467-1147",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Not Allowed",
    },
    id: "hotel-qaqortoq-1",
    name: "Pinehill Vista",
    address: "83 King Court",
    rating: 3,
    accommodationType: "Business Hotel",
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 23,
    isPetFriendly: false,
    currency: "DKK",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "clientservices@pinehillvista.com",
      contactPhone: "+189 633-748-2249",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Allowed",
    },
    id: "hotel-qaqortoq-2",
    name: "Pinehill Vista",
    address: "254 Hilltop Blvd",
    rating: 4,
    accommodationType: "Boutique Hotel",
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 24,
    isPetFriendly: false,
    currency: "DKK",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "services@quantumstayplaza.com",
      contactPhone: "+466 106-576-2944",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    id: "hotel-qaqortoq-3",
    name: "Quantum Stay Plaza",
    address: "15 Lower Sunset Terrace",
    rating: 3,
    accommodationType: "All-Inclusive Resort",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 15,
    isPetFriendly: false,
    currency: "DKK",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "services@glacierwindlodge.com",
      contactPhone: "+663 126-438-8628",
    },
    policies: {
      cancellation: "Free cancellation up to 14 days before check-in; 50% refund for cancellations made within 14 days.",
      smoking: "Not Allowed",
    },
    id: "hotel-qaqortoq-4",
    name: "Glacierwind Lodge",
    address: "236 Lower Central Road",
    rating: 4,
    accommodationType: "Luxury Villa",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 23,
    isPetFriendly: false,
    currency: "DKK",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "services@astrolinesuites.com",
      contactPhone: "+175 686-874-9214",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-qaqortoq-5",
    name: "Astroline Suites",
    address: "260 Old Park Avenue",
    rating: 3,
    accommodationType: "Luxury Hotel",
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 16,
    isPetFriendly: false,
    currency: "DKK",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "care@thepearlbreakhotel.com",
      contactPhone: "+435 752-871-7463",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Not Allowed",
    },
    id: "hotel-qaqortoq-6",
    name: "The Pearl Break Hotel",
    address: "244 Sunset Street",
    rating: 4,
    accommodationType: "Spa Hotel",
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 14,
    isPetFriendly: false,
    currency: "DKK",
    isPopular: false,
  },
  {
    id: "hotel-qaqortoq-7",
    name: "The Monarch Hall",
    address: "265 Upper Central Court",
    rating: 4,
    accommodationType: "Eco-Lodge",
    amenities: ["Conference Room", "Free Wi-Fi", "Room Service", "Fitness Center", "Restaurant", "Spa"],
    accessibilityFeatures: ["Accessible Pathways", "Visual Alarm", "Large Print Materials"],
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 43,
    isPetFriendly: true,
    currency: "DKK",
    contact: {
      contactEmail: "hi@themonarchhall.com",
      contactPhone: "+625 776-249-8590",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-qaqortoq-8",
    name: "Mosswood Hideaway",
    address: "161 Queen Street",
    rating: 3,
    accommodationType: "Hostel",
    amenities: ["Restaurant", "Conference Room", "Fitness Center", "Spa", "Non-Smoking Rooms", "Swimming Pool", "Laundry Service", "Airport Shuttle", "Parking", "Free Wi-Fi"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids"],
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 59,
    isPetFriendly: false,
    currency: "DKK",
    contact: {
      contactEmail: "info@mosswoodhideaway.com",
      contactPhone: "+831 868-586-8565",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    isPopular: true,
  },
  {
    id: "hotel-qaqortoq-9",
    name: "The Concrete Garden",
    address: "17 King Street",
    rating: 4,
    accommodationType: "Luxury Hotel",
    amenities: ["Conference Room", "Non-Smoking Rooms", "Room Service", "Bar", "24-Hour Front Desk", "Business Center"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 18,
    isPetFriendly: false,
    currency: "DKK",
    contact: {
      contactEmail: "care@theconcretegarden.com",
      contactPhone: "+66 653-996-2222",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  }
];
