import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Prestige Hotel
export const thePrestigeHotelRooms: RoomOption[] = [
  {
    id: "hotel-melbourne-3-room-2",
    name: "Deluxe Twin Villa",
    description:
      "Experience our serene, deluxe twin villa where the city comes alive at dusk, with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Balcony",
      "Fireplace",
      "Outdoor Furniture",
      "Jacuzzi Tub",
      "Dining Table",
      "In-Room Safe",
    ],
    pricePerNight: 115,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-melbourne-3-room-2",
    name: "Deluxe King Studio",
    description:
      "Deluxe-themed studio with spacious decor, with a pleasant outlook, and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Luggage Rack",
      "Jacuzzi Tub",
      "Bathtub",
      "In-Room Safe",
    ],
    pricePerNight: 152,
    currency: "AUD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
];
