// Auto-generated file for amsterdam motorcycle rentals
// City: amsterdam, Country: Netherlands, Region: Netherlands

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const amsterdamnetherlandsnetherlandsMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-amsterdam-bmw-1",
    make: "BMW",
    model: "C400GT",
    year: 2020,
    type: "dual-sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "LED Headlights", "Phone Mount", "Keyless Ignition"],
    rentalPricePerDay: 140,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Safety Gear Required", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-amsterdam-victory-2",
    make: "Victory",
    model: "Kingpin",
    year: 2023,
    type: "adventure",
    engineSize: "250cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)", "Keyless Ignition", "Comfort Seat", "Saddlebags"],
    rentalPricePerDay: 130,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Security Deposit Required", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-amsterdam-can-am-3",
    make: "Can-Am",
    model: "Spyder ST",
    year: 2021,
    type: "scooter",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Metallic Green",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Traction Control", "Quick Shifter", "GPS Navigation"],
    rentalPricePerDay: 98,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Tourist District",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Emergency Contact Information", "Helmet Required", "Rider Training Course Completion", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-amsterdam-moto-guzzi-4",
    make: "Moto Guzzi",
    model: "MGX-21",
    year: 2022,
    type: "cruiser",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["USB Charging", "Anti-lock Braking System (ABS)", "Riding Modes", "Bluetooth Audio", "Phone Mount"],
    rentalPricePerDay: 112,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Proof of Residency", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-amsterdam-bajaj-5",
    make: "Bajaj",
    model: "Dominar 400",
    year: 2019,
    type: "cruiser",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Bluetooth Audio", "USB Charging", "Backrest"],
    rentalPricePerDay: 53,
    currency: "EUR",
    available: false,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Proof of Residency", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-amsterdam-husqvarna-6",
    make: "Husqvarna",
    model: "FE 501s",
    year: 2022,
    type: "cafe racer",
    engineSize: "500cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Tire Pressure Monitoring System (TPMS)", "Saddlebags", "Traction Control", "ABS"],
    rentalPricePerDay: 145,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Proof of Residency", "Two-Wheel Experience"],
    location: "",
  },
  {
    id: "motorcycle-amsterdam-bajaj-7",
    make: "Bajaj",
    model: "CT100",
    year: 2021,
    type: "scooter",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 2,
    hasStorage: true,
    features: ["LED Headlights"],
    rentalPricePerDay: 112,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Minimum Age 21", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-amsterdam-bmw-8",
    make: "BMW",
    model: "K1600GTL",
    year: 2020,
    type: "touring",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust"],
    rentalPricePerDay: 104,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-amsterdam-moto-guzzi-9",
    make: "Moto Guzzi",
    model: "Stelvio",
    year: 2022,
    type: "adventure",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control"],
    rentalPricePerDay: 121,
    depositAmount: 242,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "RV Park / Campground",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Helmet Required", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-amsterdam-bmw-10",
    make: "BMW",
    model: "F900XR",
    year: 2020,
    type: "adventure",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Custom Exhaust", "Tire Pressure Monitoring System (TPMS)", "LED Headlights"],
    rentalPricePerDay: 106,
    depositAmount: 424,
    currency: "EUR",
    available: false,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Convention Center",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Proof of Residency", "Minimum Age 21"],
  },
  {
    id: "motorcycle-amsterdam-suzuki-11",
    make: "Suzuki",
    model: "GSX-R125",
    year: 2020,
    type: "sport",
    engineSize: "750cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: false,
    features: ["USB Charging", "Riding Modes", "Performance Tires", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 54,
    depositAmount: 216,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Tourist District",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Security Deposit Required"],
  },
  {
    id: "motorcycle-amsterdam-moto-guzzi-12",
    make: "Moto Guzzi",
    model: "California Touring 1400 Touring Special Edition 2024",
    year: 2022,
    type: "touring",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Windshield", "Saddlebags", "Riding Modes", "Custom Exhaust", "GPS Navigation"],
    rentalPricePerDay: 116,
    depositAmount: 464,
    currency: "EUR",
    available: false,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Car Rental Lot",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Insurance Required"],
  },
  {
    id: "motorcycle-amsterdam-cfmoto-13",
    make: "CFMoto",
    model: "700CL-X Sport",
    year: 2021,
    type: "dirt bike",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Adjustable Suspension"],
    rentalPricePerDay: 120,
    depositAmount: 480,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "RV Park / Campground",
    dropOffCity: "boston",
    dropOffCountry: "United States",
    dropOffLocation: "Transit Hub",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Insurance Required"],
  },
  {
    id: "motorcycle-amsterdam-honda-14",
    make: "Honda",
    model: "CBR954RR",
    year: 2022,
    type: "touring",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Bluetooth Audio", "Custom Exhaust"],
    rentalPricePerDay: 90,
    depositAmount: 270,
    currency: "EUR",
    available: false,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Shopping Center",
    dropOffCity: "coorg",
    dropOffCountry: "India",
    dropOffLocation: "Tourist District",
    requirements: ["Minimum Age 21", "Valid Motorcycle License", "Signed Waiver", "Security Deposit Required", "Insurance Required"],
  },
  {
    id: "motorcycle-amsterdam-aprilia-15",
    make: "Aprilia",
    model: "RS 660 Limited Edition",
    year: 2021,
    type: "cruiser",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["LED Headlights", "Backrest"],
    rentalPricePerDay: 159,
    depositAmount: 477,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "RV Park / Campground",
    requirements: ["Valid Motorcycle License", "Local Riding Permit"],
  },
  {
    id: "motorcycle-amsterdam-can-am-16",
    make: "Can-Am",
    model: "Ryker 900",
    year: 2020,
    type: "scooter",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Comfort Seat", "Heated Grips", "Custom Exhaust", "Security System"],
    rentalPricePerDay: 89,
    depositAmount: 356,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Hotel Pickup",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Rider Training Course Completion"],
  },
  {
    id: "motorcycle-amsterdam-honda-17",
    make: "Honda",
    model: "CRF450L",
    year: 2020,
    type: "cafe racer",
    engineSize: "750cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Adjustable Suspension"],
    rentalPricePerDay: 59,
    depositAmount: 236,
    currency: "EUR",
    available: true,
    pickUpCity: "Amsterdam",
    pickUpCountry: "Netherlands",
    pickUpLocation: "Residential Area",
    dropOffCity: "cozumel",
    dropOffCountry: "Mexico",
    dropOffLocation: "University Area",
    requirements: ["Two-Wheel Experience", "Security Deposit Required", "Valid Motorcycle License", "Signed Waiver"],
  }
];
