import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const aucklandnewZealandasiaPacificMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-auckland-moto-guzzi-1",
    make: "Moto Guzzi",
    model: "Audace",
    year: 2021,
    type: "standard",
    engineSize: "750cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Saddlebags", "Windshield", "Backrest", "Heated Grips"],
    rentalPricePerDay: 187,
    currency: "NZD",
    available: false,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "Transit Hub",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/standard/moto-guzzi-audace.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Signed Waiver",
      "Local Riding Permit",
    ],
    availability: false,
    location: "Transit Hub",
  },
  {
    id: "motorcycle-auckland-triumph-2",
    make: "Triumph",
    model: "Speed Triple",
    year: 2022,
    type: "dual-sport",
    engineSize: "125cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips"],
    rentalPricePerDay: 112,
    currency: "NZD",
    available: true,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "Downtown",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/dual-sport/triumph-speed-triple.jpg",
    requirements: ["Valid Motorcycle License", "Insurance Required"],
    availability: true,
    location: "Downtown",
  },
  {
    id: "motorcycle-auckland-cfmoto-3",
    make: "CFMoto",
    model: "700CL-X",
    year: 2021,
    type: "cruiser",
    engineSize: "750cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Backrest", "Cruise Control", "Bluetooth Audio"],
    rentalPricePerDay: 138,
    currency: "NZD",
    available: false,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "Convention Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/cfmoto-700cl-x.jpg",
    requirements: [
      "Security Deposit Required",
      "Valid Motorcycle License",
      "Minimum Age 21",
    ],
    availability: false,
    location: "Convention Center",
  },
  {
    id: "motorcycle-auckland-gasgas-4",
    make: "GasGas",
    model: "EX 250F",
    year: 2020,
    type: "touring",
    engineSize: "650cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Windshield"],
    rentalPricePerDay: 119,
    currency: "NZD",
    available: false,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/gasgas-ex-250f.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Insurance Required",
      "Credit Card Required",
      "Security Deposit Required",
    ],
    availability: false,
    location: "Motorcycle Dealership",
  },
  {
    id: "motorcycle-auckland-benelli-5",
    make: "Benelli",
    model: "TRK502",
    year: 2023,
    type: "touring",
    engineSize: "750cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 1,
    hasStorage: true,
    features: [
      "Cruise Control",
      "Custom Exhaust",
      "Windshield",
      "GPS Navigation",
    ],
    rentalPricePerDay: 62,
    currency: "NZD",
    available: true,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "Car Rental Lot",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/benelli-trk502.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Minimum Age 21",
      "Credit Card Required",
      "Insurance Required",
      "No DUI Record",
    ],
    availability: true,
    location: "Car Rental Lot",
  },
  {
    id: "motorcycle-auckland-victory-6",
    make: "Victory",
    model: "Magnum",
    year: 2019,
    type: "dual-sport",
    engineSize: "250cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: [
      "GPS Navigation",
      "ABS",
      "Heated Grips",
      "Bluetooth Audio",
      "Cruise Control",
    ],
    rentalPricePerDay: 194,
    currency: "NZD",
    available: true,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "Shopping Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/dual-sport/victory-magnum.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Minimum Age 21",
      "Credit Card Required",
    ],
    availability: true,
    location: "Shopping Center",
  },
  {
    id: "motorcycle-auckland-bajaj-7",
    make: "Bajaj",
    model: "Avenger Street 160",
    year: 2021,
    type: "scooter",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips"],
    rentalPricePerDay: 123,
    currency: "NZD",
    available: false,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "University Area",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/bajaj-avenger-street-160.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Helmet Required",
      "Credit Card Required",
      "Two-Wheel Experience",
      "Signed Waiver",
    ],
    availability: false,
    location: "University Area",
  },
  {
    id: "motorcycle-auckland-royal-enfield-8",
    make: "Royal Enfield",
    model: "Himalayan",
    year: 2021,
    type: "cruiser",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Saddlebags", "Phone Mount", "Security System"],
    rentalPricePerDay: 161,
    currency: "NZD",
    available: true,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "Car Rental Lot",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/royal-enfield-himalayan.jpg",
    requirements: [
      "International Driving Permit (for foreign renters)",
      "Helmet Required",
      "Valid Motorcycle License",
      "Minimum Age 21",
      "Two-Wheel Experience",
    ],
    availability: true,
    location: "Car Rental Lot",
  },
  {
    id: "motorcycle-auckland-royal-enfield-9",
    make: "Royal Enfield",
    model: "Super Meteor 650",
    year: 2023,
    type: "touring",
    engineSize: "900cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Custom Exhaust", "Windshield", "Bluetooth Audio", "Backrest"],
    rentalPricePerDay: 99,
    currency: "NZD",
    available: true,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "University Area",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/royal-enfield-super-meteor-650.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Security Deposit Required",
      "Helmet Required",
      "Local Riding Permit",
      "Insurance Required",
      "Minimum Age 21",
    ],
    availability: true,
    location: "University Area",
  },
  {
    id: "motorcycle-auckland-triumph-10",
    make: "Triumph",
    model: "Bonneville",
    year: 2021,
    type: "cruiser",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["ABS", "Saddlebags", "Backrest"],
    rentalPricePerDay: 108,
    currency: "NZD",
    available: true,
    pickUpCity: "Auckland",
    pickUpCountry: "New Zealand",
    pickUpLocation: "University Area",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/triumph-bonneville.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Minimum Age 21",
      "Two-Wheel Experience",
      "Security Deposit Required",
      "Credit Card Required",
      "Signed Waiver",
    ],
    availability: true,
    location: "University Area",
  },
];
