import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const baliindonesiaasiaPacificMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-bali-victory-1",
    make: "Victory",
    model: "Hammer",
    year: 2021,
    type: "cruiser",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 2,
    hasStorage: true,
    features: ["ABS"],
    rentalPricePerDay: 145,
    currency: "IDR",
    available: false,
    pickUpCity: "bali",
    pickUpCountry: "Indonesia",
    pickUpLocation: "Marina",
    dropOffCity: "st-thomas",
    dropOffCountry: "U.S. Virgin Islands",
    dropOffLocation: "Downtown",
    imageUrl: "https://paragon-trails-motorcycle-images.com/cruiser/victory-hammer.jpg",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Security Deposit Required", "Two-Wheel Experience"],
    availability: false,
    location: "Marina",
  },
  {
    id: "motorcycle-bali-bmw-2",
    make: "BMW",
    model: "S1000RR",
    year: 2020,
    type: "scooter",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Bluetooth Audio", "Backrest", "Custom Exhaust"],
    rentalPricePerDay: 182,
    currency: "IDR",
    available: true,
    pickUpCity: "bali",
    pickUpCountry: "Indonesia",
    pickUpLocation: "Airport",
    dropOffCity: "st-petersburg",
    dropOffCountry: "Russia",
    dropOffLocation: "Transit Hub",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/bmw-s1000rr.jpg",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Local Riding Permit", "Credit Card Required"],
    availability: true,
    location: "Airport",
  },
  {
    id: "motorcycle-bali-honda-3",
    make: "Honda",
    model: "Shadow",
    year: 2022,
    type: "scooter",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["GPS Navigation"],
    rentalPricePerDay: 184,
    currency: "IDR",
    available: false,
    pickUpCity: "bali",
    pickUpCountry: "Indonesia",
    pickUpLocation: "Tourist District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/honda-shadow.jpg",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Two-Wheel Experience", "Credit Card Required"],
    availability: false,
    location: "Tourist District",
  },
  {
    id: "motorcycle-bali-yamaha-4",
    make: "Yamaha",
    model: "Bolt",
    year: 2019,
    type: "cruiser",
    engineSize: "900cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control", "GPS Navigation", "Windshield"],
    rentalPricePerDay: 172,
    currency: "IDR",
    available: false,
    pickUpCity: "bali",
    pickUpCountry: "Indonesia",
    pickUpLocation: "Shopping District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/cruiser/yamaha-bolt.jpg",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Credit Card Required"],
    availability: false,
    location: "Shopping District",
  },
  {
    id: "motorcycle-bali-victory-5",
    make: "Victory",
    model: "Hammer",
    year: 2023,
    type: "scooter",
    engineSize: "650cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Custom Exhaust", "Cruise Control", "Helmet Included"],
    rentalPricePerDay: 150,
    currency: "IDR",
    available: true,
    pickUpCity: "bali",
    pickUpCountry: "Indonesia",
    pickUpLocation: "Airport",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/victory-hammer.jpg",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Two-Wheel Experience", "Experience with Manual Transmission"],
    availability: true,
    location: "Airport",
  },
  {
    id: "motorcycle-bali-indian-6",
    make: "Indian",
    model: "Scout",
    year: 2020,
    type: "sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Backrest", "Custom Exhaust"],
    rentalPricePerDay: 171,
    currency: "IDR",
    available: true,
    pickUpCity: "bali",
    pickUpCountry: "Indonesia",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://paragon-trails-motorcycle-images.com/sport/indian-scout.jpg",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "No DUI Record", "Signed Waiver"],
    availability: true,
    location: "Transit Hub",
  },
  {
    id: "motorcycle-bali-husqvarna-7",
    make: "Husqvarna",
    model: "701 Enduro",
    year: 2019,
    type: "sport",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Backrest", "Custom Exhaust"],
    rentalPricePerDay: 182,
    currency: "IDR",
    available: false,
    pickUpCity: "bali",
    pickUpCountry: "Indonesia",
    pickUpLocation: "Shopping District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/sport/husqvarna-701-enduro.jpg",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Security Deposit Required", "No DUI Record"],
    availability: false,
    location: "Shopping District",
  }
];
