import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const barcelonaspainmediterraneanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-barcelona-royal-enfield-1",
    make: "Royal Enfield",
    model: "Hunter",
    year: 2021,
    type: "dual-sport",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Phone Mount", "Bluetooth Audio", "Custom Exhaust"],
    rentalPricePerDay: 163,
    currency: "EUR",
    available: false,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "Downtown",
    dropOffCity: "hong-kong",
    dropOffCountry: "China",
    dropOffLocation: "Entertainment District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/dual-sport/royal-enfield-hunter.jpg",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Signed Waiver"],
    availability: false,
    location: "Downtown",
  },
  {
    id: "motorcycle-barcelona-ducati-2",
    make: "Ducati",
    model: "SuperSport",
    year: 2019,
    type: "custom",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags", "Security System", "USB Charging", "Bluetooth Audio"],
    rentalPricePerDay: 115,
    currency: "EUR",
    available: true,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "City Center",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/ducati-supersport.jpg",
    requirements: ["Insurance Required", "Minimum Age 21", "No DUI Record", "Valid Motorcycle License", "Local Riding Permit"],
    availability: true,
    location: "City Center",
  },
  {
    id: "motorcycle-barcelona-ktm-3",
    make: "KTM",
    model: "1290 Super Duke",
    year: 2022,
    type: "dual-sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Phone Mount"],
    rentalPricePerDay: 171,
    currency: "EUR",
    available: true,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "Downtown",
    imageUrl: "https://paragon-trails-motorcycle-images.com/dual-sport/ktm-1290-super-duke.jpg",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Signed Waiver", "Local Riding Permit"],
    availability: true,
    location: "Downtown",
  },
  {
    id: "motorcycle-barcelona-victory-4",
    make: "Victory",
    model: "Octane",
    year: 2023,
    type: "sport",
    engineSize: "125cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Backrest"],
    rentalPricePerDay: 82,
    currency: "EUR",
    available: false,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "Tourist District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/sport/victory-octane.jpg",
    requirements: ["No DUI Record", "Valid Motorcycle License", "Security Deposit Required", "Signed Waiver"],
    availability: false,
    location: "Tourist District",
  },
  {
    id: "motorcycle-barcelona-royal-enfield-5",
    make: "Royal Enfield",
    model: "Continental GT",
    year: 2021,
    type: "custom",
    engineSize: "750cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Bluetooth Audio", "Cruise Control", "Saddlebags", "GPS Navigation"],
    rentalPricePerDay: 106,
    currency: "EUR",
    available: true,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "Marina",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/royal-enfield-continental-gt.jpg",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Credit Card Required", "Insurance Required"],
    availability: true,
    location: "Marina",
  },
  {
    id: "motorcycle-barcelona-harley-davidson-6",
    make: "Harley-Davidson",
    model: "Road Glide",
    year: 2021,
    type: "sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Backrest"],
    rentalPricePerDay: 137,
    currency: "EUR",
    available: true,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "Convention Center",
    imageUrl: "https://paragon-trails-motorcycle-images.com/sport/harley-davidson-road-glide.jpg",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Minimum Age 21", "No DUI Record", "Credit Card Required", "Signed Waiver"],
    availability: true,
    location: "Convention Center",
  },
  {
    id: "motorcycle-barcelona-ducati-7",
    make: "Ducati",
    model: "Multistrada",
    year: 2022,
    type: "dual-sport",
    engineSize: "500cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Custom Exhaust", "Heated Grips", "Windshield"],
    rentalPricePerDay: 141,
    currency: "EUR",
    available: true,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "Shopping District",
    dropOffCity: "helsinki",
    dropOffCountry: "Finland",
    dropOffLocation: "Entertainment District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/dual-sport/ducati-multistrada.jpg",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Signed Waiver"],
    availability: true,
    location: "Shopping District",
  },
  {
    id: "motorcycle-barcelona-victory-8",
    make: "Victory",
    model: "Cross Country",
    year: 2023,
    type: "custom",
    engineSize: "900cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Windshield", "Helmet Included"],
    rentalPricePerDay: 141,
    currency: "EUR",
    available: true,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "Near Beach",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/victory-cross-country.jpg",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Experience with Manual Transmission", "Helmet Required", "International Driving Permit (for foreign renters)"],
    availability: true,
    location: "Near Beach",
  },
  {
    id: "motorcycle-barcelona-indian-9",
    make: "Indian",
    model: "Chieftain",
    year: 2021,
    type: "cruiser",
    engineSize: "500cc",
    transmission: "automatic",
    color: "Orange",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Cruise Control", "Helmet Included", "Windshield", "Custom Exhaust"],
    rentalPricePerDay: 172,
    currency: "EUR",
    available: false,
    pickUpCity: "barcelona",
    pickUpCountry: "Spain",
    pickUpLocation: "Downtown",
    imageUrl: "https://paragon-trails-motorcycle-images.com/cruiser/indian-chieftain.jpg",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Security Deposit Required", "Experience with Manual Transmission", "International Driving Permit (for foreign renters)"],
    availability: false,
    location: "Downtown",
  }
];
