import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const berlingermanynorthernEuropeMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-berlin-suzuki-1",
    make: "Suzuki",
    model: "GSX-R1000",
    year: 2019,
    type: "sport",
    engineSize: "250cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation"],
    rentalPricePerDay: 122,
    currency: "EUR",
    available: false,
    pickUpCity: "berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Marina",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/sport/suzuki-gsx-r1000.jpg",
    requirements: [],
    availability: false,
    location: "Marina",
  },
  {
    id: "motorcycle-berlin-moto-guzzi-2",
    make: "Moto Guzzi",
    model: "V7",
    year: 2022,
    type: "touring",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags"],
    rentalPricePerDay: 185,
    currency: "EUR",
    available: true,
    pickUpCity: "berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Entertainment District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/moto-guzzi-v7.jpg",
    requirements: [],
    availability: true,
    location: "Entertainment District",
  },
  {
    id: "motorcycle-berlin-harley-davidson-3",
    make: "Harley-Davidson",
    model: "Softail",
    year: 2019,
    type: "cruiser",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Saddlebags"],
    rentalPricePerDay: 121,
    currency: "EUR",
    available: false,
    pickUpCity: "berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Near Beach",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/harley-davidson-softail.jpg",
    requirements: [],
    availability: false,
    location: "Near Beach",
  },
  {
    id: "motorcycle-berlin-harley-davidson-4",
    make: "Harley-Davidson",
    model: "Electra Glide",
    year: 2023,
    type: "standard",
    engineSize: "250cc",
    transmission: "automatic",
    color: "White",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Security System"],
    rentalPricePerDay: 71,
    currency: "EUR",
    available: true,
    pickUpCity: "berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Marina",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/standard/harley-davidson-electra-glide.jpg",
    requirements: [],
    availability: true,
    location: "Marina",
  },
  {
    id: "motorcycle-berlin-ducati-5",
    make: "Ducati",
    model: "Diavel",
    year: 2021,
    type: "touring",
    engineSize: "750cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control", "Phone Mount", "Backrest", "Helmet Included"],
    rentalPricePerDay: 77,
    currency: "EUR",
    available: true,
    pickUpCity: "berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Convention Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/ducati-diavel.jpg",
    requirements: [],
    availability: true,
    location: "Convention Center",
  },
  {
    id: "motorcycle-berlin-honda-6",
    make: "Honda",
    model: "CRF450L",
    year: 2019,
    type: "dual-sport",
    engineSize: "750cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Bluetooth Audio"],
    rentalPricePerDay: 109,
    currency: "EUR",
    available: true,
    pickUpCity: "berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Transit Hub",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/dual-sport/honda-crf450l.jpg",
    requirements: [],
    availability: true,
    location: "Transit Hub",
  },
  {
    id: "motorcycle-berlin-honda-7",
    make: "Honda",
    model: "CRF450L",
    year: 2020,
    type: "standard",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Custom Exhaust", "Saddlebags", "ABS", "Windshield"],
    rentalPricePerDay: 170,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Entertainment District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/standard/honda-crf450l.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Minimum Age 21",
      "Two-Wheel Experience",
      "Credit Card Required",
      "Security Deposit Required",
      "No DUI Record",
    ],
    availability: false,
    location: "Entertainment District",
  },
  {
    id: "motorcycle-berlin-ducati-8",
    make: "Ducati",
    model: "Scrambler",
    year: 2022,
    type: "standard",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["USB Charging", "Bluetooth Audio", "Security System"],
    rentalPricePerDay: 120,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Convention Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/standard/ducati-scrambler.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Security Deposit Required",
      "Insurance Required",
      "Minimum Age 21",
    ],
    availability: false,
    location: "Convention Center",
  },
  {
    id: "motorcycle-berlin-husqvarna-9",
    make: "Husqvarna",
    model: "TE 300i",
    year: 2022,
    type: "standard",
    engineSize: "250cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Bluetooth Audio"],
    rentalPricePerDay: 135,
    currency: "EUR",
    available: false,
    pickUpCity: "Berlin",
    pickUpCountry: "Germany",
    pickUpLocation: "Shopping District",
    dropOffCity: "sitka",
    dropOffCountry: "United States",
    dropOffLocation: "City Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/standard/husqvarna-te-300i.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Local Riding Permit",
      "Helmet Required",
    ],
    availability: false,
    location: "Shopping District",
  },
];
