import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const bostonunitedStateseastCoastUsaMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-boston-kawasaki-1",
    make: "Kawasaki",
    model: "KLR 650",
    year: 2023,
    type: "scooter",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation"],
    rentalPricePerDay: 91,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/kawasaki-klr-650.jpg",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Minimum Age 21", "Local Riding Permit", "Insurance Required", "Credit Card Required"],
    availability: true,
    location: "Train Station",
  },
  {
    id: "motorcycle-boston-ktm-2",
    make: "KTM",
    model: "1290 Super Duke",
    year: 2019,
    type: "custom",
    engineSize: "650cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags", "ABS", "GPS Navigation", "Cruise Control"],
    rentalPricePerDay: 133,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "Residential Area",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/ktm-1290-super-duke.jpg",
    requirements: ["Minimum Age 21", "Credit Card Required", "Valid Motorcycle License"],
    availability: true,
    location: "Residential Area",
  },
  {
    id: "motorcycle-boston-indian-3",
    make: "Indian",
    model: "Challenger",
    year: 2020,
    type: "touring",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 2,
    hasStorage: false,
    features: ["USB Charging", "Bluetooth Audio"],
    rentalPricePerDay: 67,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    imageUrl: "https://paragon-trails-motorcycle-images.com/touring/indian-challenger.jpg",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Signed Waiver"],
    availability: true,
    location: "Train Station",
  },
  {
    id: "motorcycle-boston-suzuki-4",
    make: "Suzuki",
    model: "GSX-S750",
    year: 2021,
    type: "cruiser",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Heated Grips", "ABS"],
    rentalPricePerDay: 141,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "https://paragon-trails-motorcycle-images.com/cruiser/suzuki-gsx-s750.jpg",
    requirements: ["Experience with Manual Transmission", "Credit Card Required", "Valid Motorcycle License"],
    availability: true,
    location: "RV Park / Campground",
  },
  {
    id: "motorcycle-boston-ktm-5",
    make: "KTM",
    model: "890 Adventure R",
    year: 2020,
    type: "scooter",
    engineSize: "500cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Phone Mount", "Helmet Included"],
    rentalPricePerDay: 168,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "University Area",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/ktm-890-adventure-r.jpg",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Security Deposit Required"],
    availability: true,
    location: "University Area",
  },
  {
    id: "motorcycle-boston-aprilia-6",
    make: "Aprilia",
    model: "Tuareg 660",
    year: 2023,
    type: "cruiser",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Phone Mount", "Custom Exhaust", "ABS", "Security System"],
    rentalPricePerDay: 175,
    currency: "USD",
    available: false,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "University Area",
    imageUrl: "https://paragon-trails-motorcycle-images.com/cruiser/aprilia-tuareg-660.jpg",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Minimum Age 21"],
    availability: false,
    location: "University Area",
  },
  {
    id: "motorcycle-boston-bajaj-7",
    make: "Bajaj",
    model: "Pulsar NS200",
    year: 2023,
    type: "cruiser",
    engineSize: "750cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Helmet Included", "Backrest", "Phone Mount"],
    rentalPricePerDay: 161,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "Shopping Center",
    imageUrl: "https://paragon-trails-motorcycle-images.com/cruiser/bajaj-pulsar-ns200.jpg",
    requirements: ["International Driving Permit (for foreign renters)", "Valid Motorcycle License", "Signed Waiver"],
    availability: true,
    location: "Shopping Center",
  },
  {
    id: "motorcycle-boston-triumph-8",
    make: "Triumph",
    model: "Rocket 3",
    year: 2019,
    type: "standard",
    engineSize: "250cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Security System", "Backrest", "Helmet Included"],
    rentalPricePerDay: 110,
    currency: "USD",
    available: false,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "https://paragon-trails-motorcycle-images.com/standard/triumph-rocket-3.jpg",
    requirements: ["Valid Motorcycle License", "Insurance Required", "No DUI Record"],
    availability: false,
    location: "Motorcycle Dealership",
  },
  {
    id: "motorcycle-boston-zero-9",
    make: "Zero",
    model: "DSR/X",
    year: 2020,
    type: "custom",
    engineSize: "500cc",
    transmission: "automatic",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: true,
    features: ["ABS", "Backrest"],
    rentalPricePerDay: 134,
    currency: "USD",
    available: false,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "City Center",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/zero-dsr/x.jpg",
    requirements: ["Credit Card Required", "Valid Motorcycle License", "Local Riding Permit"],
    availability: false,
    location: "City Center",
  },
  {
    id: "motorcycle-boston-honda-10",
    make: "Honda",
    model: "CB500X",
    year: 2019,
    type: "dual-sport",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Helmet Included", "Security System", "Cruise Control", "Bluetooth Audio", "Saddlebags"],
    rentalPricePerDay: 97,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "Motorcycle Dealership",
    dropOffCity: "santiago",
    dropOffCountry: "Chile",
    dropOffLocation: "Tourist District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/dual-sport/honda-cb500x.jpg",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Credit Card Required"],
    availability: true,
    location: "Motorcycle Dealership",
  },
  {
    id: "motorcycle-boston-yamaha-11",
    make: "Yamaha",
    model: "Tracer 9 GT",
    year: 2020,
    type: "custom",
    engineSize: "650cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Bluetooth Audio", "Saddlebags"],
    rentalPricePerDay: 118,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/yamaha-tracer-9-gt.jpg",
    requirements: ["Valid Motorcycle License", "Local Riding Permit"],
    availability: true,
    location: "Car Rental Lot",
  },
  {
    id: "motorcycle-boston-triumph-12",
    make: "Triumph",
    model: "Rocket 3",
    year: 2022,
    type: "touring",
    engineSize: "500cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 2,
    hasStorage: false,
    features: ["ABS", "USB Charging"],
    rentalPricePerDay: 182,
    currency: "USD",
    available: true,
    pickUpCity: "Boston",
    pickUpCountry: "United States",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "https://paragon-trails-motorcycle-images.com/touring/triumph-rocket-3.jpg",
    requirements: ["Signed Waiver", "International Driving Permit (for foreign renters)", "Valid Motorcycle License", "Two-Wheel Experience"],
    availability: true,
    location: "Harley-Davidson Dealership",
  }
];
