import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const charlestonunitedStateseastCoastUsaMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-charleston-yamaha-1",
    make: "Yamaha",
    model: "MT-07",
    year: 2021,
    type: "sport",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust"],
    rentalPricePerDay: 152,
    currency: "USD",
    available: true,
    pickUpCity: "charleston",
    pickUpCountry: "United States",
    pickUpLocation: "Transit Hub",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/sport/yamaha-mt-07.jpg",
    requirements: [],
    availability: true,
    location: "Transit Hub",
  },
  {
    id: "motorcycle-charleston-harley-davidson-2",
    make: "Harley-Davidson",
    model: "Road King",
    year: 2023,
    type: "scooter",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: true,
    features: ["USB Charging", "Bluetooth Audio", "Saddlebags", "Windshield"],
    rentalPricePerDay: 90,
    currency: "USD",
    available: true,
    pickUpCity: "charleston",
    pickUpCountry: "United States",
    pickUpLocation: "Airport",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/harley-davidson-road-king.jpg",
    requirements: [],
    availability: true,
    location: "Airport",
  },
  {
    id: "motorcycle-charleston-husqvarna-3",
    make: "Husqvarna",
    model: "701 Enduro",
    year: 2020,
    type: "custom",
    engineSize: "500cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: [],
    rentalPricePerDay: 80,
    currency: "USD",
    available: true,
    pickUpCity: "charleston",
    pickUpCountry: "United States",
    pickUpLocation: "City Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/custom/husqvarna-701-enduro.jpg",
    requirements: [],
    availability: true,
    location: "City Center",
  },
  {
    id: "motorcycle-charleston-indian-4",
    make: "Indian",
    model: "Roadmaster",
    year: 2022,
    type: "cruiser",
    engineSize: "900cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Bluetooth Audio", "ABS", "Windshield"],
    rentalPricePerDay: 98,
    currency: "USD",
    available: true,
    pickUpCity: "charleston",
    pickUpCountry: "United States",
    pickUpLocation: "Marina",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/indian-roadmaster.jpg",
    requirements: [],
    availability: true,
    location: "Marina",
  },
  {
    id: "motorcycle-charleston-ducati-5",
    make: "Ducati",
    model: "Monster",
    year: 2022,
    type: "scooter",
    engineSize: "250cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Backrest", "Cruise Control", "Security System"],
    rentalPricePerDay: 180,
    currency: "USD",
    available: false,
    pickUpCity: "Charleston",
    pickUpCountry: "United States",
    pickUpLocation: "Airport",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/ducati-monster.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Experience with Manual Transmission",
      "Local Riding Permit",
    ],
    availability: false,
    location: "Airport",
  },
  {
    id: "motorcycle-charleston-honda-6",
    make: "Honda",
    model: "Gold Wing",
    year: 2019,
    type: "sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 1,
    hasStorage: false,
    features: [
      "USB Charging",
      "Bluetooth Audio",
      "Saddlebags",
      "Security System",
    ],
    rentalPricePerDay: 148,
    currency: "USD",
    available: false,
    pickUpCity: "Charleston",
    pickUpCountry: "United States",
    pickUpLocation: "Tourist District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/sport/honda-gold-wing.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Signed Waiver",
      "Experience with Manual Transmission",
      "Local Riding Permit",
    ],
    availability: false,
    location: "Tourist District",
  },
  {
    id: "motorcycle-charleston-yamaha-7",
    make: "Yamaha",
    model: "MT-07",
    year: 2023,
    type: "custom",
    engineSize: "1000cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Cruise Control", "USB Charging"],
    rentalPricePerDay: 90,
    currency: "USD",
    available: true,
    pickUpCity: "Charleston",
    pickUpCountry: "United States",
    pickUpLocation: "Airport",
    dropOffCity: "kyoto",
    dropOffCountry: "Japan",
    dropOffLocation: "Tourist District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/custom/yamaha-mt-07.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Minimum Age 21",
      "Signed Waiver",
      "Security Deposit Required",
    ],
    availability: true,
    location: "Airport",
  },
];
