// Auto-generated file for dubai motorcycle rentals
// City: dubai, Country: United Arab Emirates, Region: Middle East

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const dubaiunitedArabEmiratesmiddleEastMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-dubai-suzuki-1",
    make: "Suzuki",
    model: "GSX-R125",
    year: 2023,
    type: "cruiser",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust", "Keyless Ignition"],
    rentalPricePerDay: 552,
    currency: "AED",
    available: false,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Signed Waiver", "No DUI Record", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-bmw-2",
    make: "BMW",
    model: "R1250RS",
    year: 2021,
    type: "cruiser",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Helmet Included"],
    rentalPricePerDay: 448,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Helmet Required", "Experience with Manual Transmission", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-dubai-moto-guzzi-3",
    make: "Moto Guzzi",
    model: "Eldorado",
    year: 2020,
    type: "dirt bike",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Windshield", "Anti-lock Braking System (ABS)", "Backrest", "Heated Grips"],
    rentalPricePerDay: 355,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Credit Card Required", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-moto-guzzi-4",
    make: "Moto Guzzi",
    model: "Bellagio",
    year: 2021,
    type: "cafe racer",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Traction Control"],
    rentalPricePerDay: 245,
    currency: "AED",
    available: false,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-dubai-ducati-5",
    make: "Ducati",
    model: "Multistrada V4",
    year: 2020,
    type: "sport",
    engineSize: "500cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips", "Custom Exhaust", "Cruise Control"],
    rentalPricePerDay: 261,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Local Riding Permit", "Credit Card Required", "Rider Training Course Completion", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-dubai-kawasaki-6",
    make: "Kawasaki",
    model: "KX250F",
    year: 2023,
    type: "cafe racer",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Saddlebags"],
    rentalPricePerDay: 538,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Rider Training Course Completion", "Credit Card Required", "Emergency Contact Information", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-indian-7",
    make: "Indian",
    model: "Chief Super Chief Bobber Twenty Limited Dark Horse 2024",
    year: 2020,
    type: "sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips", "Security System"],
    rentalPricePerDay: 445,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Proof of Residency", "No DUI Record", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-dubai-bajaj-8",
    make: "Bajaj",
    model: "Pulsar AS200",
    year: 2020,
    type: "standard",
    engineSize: "650cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["ABS", "Backrest", "USB Charging", "Traction Control"],
    rentalPricePerDay: 559,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Security Deposit Required", "Emergency Contact Information"],
    location: "",
  },
  {
    id: "motorcycle-dubai-honda-9",
    make: "Honda",
    model: "CBR150R",
    year: 2019,
    type: "dirt bike",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Comfort Seat", "LED Headlights", "Keyless Ignition", "Performance Tires"],
    rentalPricePerDay: 548,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-dubai-harley-davidson-10",
    make: "Harley-Davidson",
    model: "Street Bob",
    year: 2022,
    type: "cruiser",
    engineSize: "125cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Performance Tires", "Custom Exhaust", "Helmet Included"],
    rentalPricePerDay: 400,
    currency: "AED",
    available: false,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Helmet Required", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-ktm-11",
    make: "KTM",
    model: "890 Adventure R Rally",
    year: 2023,
    type: "custom",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Quick Shifter"],
    rentalPricePerDay: 534,
    currency: "AED",
    available: false,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Rider Training Course Completion", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-dubai-royal-enfield-12",
    make: "Royal Enfield",
    model: "Thunderbird X 500X",
    year: 2021,
    type: "dual-sport",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Metallic Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included", "Tire Pressure Monitoring System (TPMS)", "Bluetooth Audio", "Custom Exhaust", "Saddlebags"],
    rentalPricePerDay: 467,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Insurance Required", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-dubai-victory-13",
    make: "Victory",
    model: "Vegas",
    year: 2021,
    type: "sport",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Tire Pressure Monitoring System (TPMS)", "USB Charging", "Custom Exhaust", "GPS Navigation"],
    rentalPricePerDay: 297,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Insurance Required", "Credit Card Required", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-dubai-suzuki-14",
    make: "Suzuki",
    model: "SV650",
    year: 2023,
    type: "sport",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips"],
    rentalPricePerDay: 285,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "International Driving Permit (for foreign renters)", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-victory-15",
    make: "Victory",
    model: "Vision",
    year: 2019,
    type: "touring",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["USB Charging", "Security System", "Cruise Control", "Windshield"],
    rentalPricePerDay: 280,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-dubai-ktm-16",
    make: "KTM",
    model: "890 Adventure R Rally Pro S Special Edition 2027",
    year: 2020,
    type: "dual-sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Keyless Ignition"],
    rentalPricePerDay: 358,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Transit Hub",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-dubai-royal-enfield-17",
    make: "Royal Enfield",
    model: "Super Meteor 650",
    year: 2020,
    type: "dual-sport",
    engineSize: "750cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Tire Pressure Monitoring System (TPMS)", "Phone Mount", "Quick Shifter", "Saddlebags"],
    rentalPricePerDay: 265,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-ktm-18",
    make: "KTM",
    model: "890 Adventure R Rally Pro S Special Edition 2025",
    year: 2023,
    type: "standard",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Quick Shifter", "USB Charging", "Saddlebags"],
    rentalPricePerDay: 521,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "No DUI Record", "Helmet Required", "Minimum Age 21", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-honda-19",
    make: "Honda",
    model: "CBR1100XX",
    year: 2019,
    type: "sport",
    engineSize: "125cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags"],
    rentalPricePerDay: 263,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-dubai-gasgas-20",
    make: "GasGas",
    model: "EC 300",
    year: 2019,
    type: "cafe racer",
    engineSize: "500cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Riding Modes"],
    rentalPricePerDay: 400,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Transit Hub",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Signed Waiver", "Two-Wheel Experience", "Minimum Age 21", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-kawasaki-21",
    make: "Kawasaki",
    model: "Ninja 1000",
    year: 2022,
    type: "dirt bike",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Windshield", "LED Headlights"],
    rentalPricePerDay: 471,
    currency: "AED",
    available: false,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["No DUI Record", "Valid Motorcycle License", "Experience with Manual Transmission", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-dubai-harley-davidson-22",
    make: "Harley-Davidson",
    model: "LiveWire",
    year: 2021,
    type: "scooter",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Saddlebags", "Quick Shifter", "Keyless Ignition", "Adjustable Suspension", "Performance Tires"],
    rentalPricePerDay: 370,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Helmet Required", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-dubai-kawasaki-23",
    make: "Kawasaki",
    model: "Ninja ZX-10R",
    year: 2023,
    type: "custom",
    engineSize: "250cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 2,
    hasStorage: false,
    features: ["GPS Navigation", "Helmet Included"],
    rentalPricePerDay: 409,
    depositAmount: 1636,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Hotel Pickup",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Credit Card Required", "Rider Training Course Completion", "Experience with Manual Transmission", "Local Riding Permit"],
  },
  {
    id: "motorcycle-dubai-indian-24",
    make: "Indian",
    model: "Chief Super Chief Limited",
    year: 2020,
    type: "cruiser",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Phone Mount", "Performance Tires", "Bluetooth Audio", "Backrest", "Windshield"],
    rentalPricePerDay: 346,
    depositAmount: 1038,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Hotel Pickup",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Insurance Required"],
  },
  {
    id: "motorcycle-dubai-harley-davidson-25",
    make: "Harley-Davidson",
    model: "Street Glide Special",
    year: 2019,
    type: "touring",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Traction Control"],
    rentalPricePerDay: 313,
    depositAmount: 939,
    currency: "AED",
    available: true,
    pickUpCity: "Dubai",
    pickUpCountry: "United Arab Emirates",
    pickUpLocation: "Motorcycle Dealership",
    dropOffCity: "venice",
    dropOffCountry: "Italy",
    dropOffLocation: "Airport",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Security Deposit Required", "Two-Wheel Experience"],
  }
];
