import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const dublinirelandnorthernEuropeMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-dublin-harley-davidson-1",
    make: "Harley-Davidson",
    model: "Breakout",
    year: 2020,
    type: "touring",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Backrest"],
    rentalPricePerDay: 144,
    currency: "EUR",
    available: true,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "Airport",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/harley-davidson-breakout.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Experience with Manual Transmission",
      "Signed Waiver",
      "International Driving Permit (for foreign renters)",
      "Minimum Age 21",
    ],
    availability: true,
    location: "Airport",
  },
  {
    id: "motorcycle-dublin-ducati-2",
    make: "Ducati",
    model: "Multistrada",
    year: 2019,
    type: "scooter",
    engineSize: "650cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control"],
    rentalPricePerDay: 97,
    currency: "EUR",
    available: true,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "Downtown",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/ducati-multistrada.jpg",
    requirements: [
      "Valid Motorcycle License",
      "No DUI Record",
      "International Driving Permit (for foreign renters)",
      "Insurance Required",
      "Helmet Required",
    ],
    availability: true,
    location: "Downtown",
  },
  {
    id: "motorcycle-dublin-zero-3",
    make: "Zero",
    model: "SR/F",
    year: 2022,
    type: "cruiser",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Bluetooth Audio", "Heated Grips"],
    rentalPricePerDay: 68,
    currency: "EUR",
    available: true,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "City Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/zero-sr/f.jpg",
    requirements: [
      "Security Deposit Required",
      "Experience with Manual Transmission",
      "Helmet Required",
      "Valid Motorcycle License",
    ],
    availability: true,
    location: "City Center",
  },
  {
    id: "motorcycle-dublin-can-am-4",
    make: "Can-Am",
    model: "Spyder F3",
    year: 2019,
    type: "scooter",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Security System"],
    rentalPricePerDay: 123,
    currency: "EUR",
    available: false,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "University Area",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/can-am-spyder-f3.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Local Riding Permit",
      "Helmet Required",
      "Credit Card Required",
    ],
    availability: false,
    location: "University Area",
  },
  {
    id: "motorcycle-dublin-husqvarna-5",
    make: "Husqvarna",
    model: "Svartpilen 401",
    year: 2022,
    type: "scooter",
    engineSize: "900cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Bluetooth Audio", "USB Charging"],
    rentalPricePerDay: 102,
    currency: "EUR",
    available: true,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "Tourist District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/husqvarna-svartpilen-401.jpg",
    requirements: ["Helmet Required", "Valid Motorcycle License"],
    availability: true,
    location: "Tourist District",
  },
  {
    id: "motorcycle-dublin-indian-6",
    make: "Indian",
    model: "Pursuit",
    year: 2022,
    type: "touring",
    engineSize: "750cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips"],
    rentalPricePerDay: 88,
    currency: "EUR",
    available: true,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "Airport",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/indian-pursuit.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Minimum Age 21",
      "Signed Waiver",
    ],
    availability: true,
    location: "Airport",
  },
  {
    id: "motorcycle-dublin-cfmoto-7",
    make: "CFMoto",
    model: "300SS",
    year: 2020,
    type: "custom",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["ABS", "Heated Grips"],
    rentalPricePerDay: 66,
    currency: "EUR",
    available: false,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "University Area",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/custom/cfmoto-300ss.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Local Riding Permit",
      "Credit Card Required",
      "Experience with Manual Transmission",
      "Minimum Age 21",
    ],
    availability: false,
    location: "University Area",
  },
  {
    id: "motorcycle-dublin-zero-8",
    make: "Zero",
    model: "S",
    year: 2021,
    type: "standard",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: [
      "Bluetooth Audio",
      "Phone Mount",
      "Backrest",
      "GPS Navigation",
      "Helmet Included",
    ],
    rentalPricePerDay: 94,
    currency: "EUR",
    available: true,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "Car Rental Lot",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/standard/zero-s.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Experience with Manual Transmission",
      "Security Deposit Required",
      "Local Riding Permit",
      "Credit Card Required",
    ],
    availability: true,
    location: "Car Rental Lot",
  },
  {
    id: "motorcycle-dublin-cfmoto-9",
    make: "CFMoto",
    model: "700CL-X",
    year: 2020,
    type: "dual-sport",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included", "Windshield"],
    rentalPricePerDay: 71,
    currency: "EUR",
    available: false,
    pickUpCity: "Dublin",
    pickUpCountry: "Ireland",
    pickUpLocation: "Downtown",
    dropOffCity: "melbourne",
    dropOffCountry: "Australia",
    dropOffLocation: "RV Park / Campground",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/dual-sport/cfmoto-700cl-x.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Helmet Required",
      "Experience with Manual Transmission",
      "Signed Waiver",
    ],
    availability: false,
    location: "Downtown",
  },
];
