// Auto-generated file for dubrovnik motorcycle rentals
// City: dubrovnik, Country: Croatia, Region: Croatian Coast

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const dubrovnikcroatiacroatianCoastMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-dubrovnik-victory-1",
    make: "Victory",
    model: "Gunner",
    year: 2020,
    type: "touring",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Performance Tires", "Heated Grips", "Custom Exhaust", "GPS Navigation"],
    rentalPricePerDay: 139,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "",
    requirements: ["Security Deposit Required", "Proof of Residency", "Signed Waiver", "Minimum Age 21", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-dubrovnik-ktm-2",
    make: "KTM",
    model: "890 Adventure R Rally Pro S Special Edition 2030",
    year: 2023,
    type: "cruiser",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Quick Shifter", "Phone Mount"],
    rentalPricePerDay: 73,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Experience with Manual Transmission", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-dubrovnik-victory-3",
    make: "Victory",
    model: "Gunner",
    year: 2019,
    type: "adventure",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["GPS Navigation", "Comfort Seat", "Keyless Ignition", "Custom Exhaust"],
    rentalPricePerDay: 92,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Two-Wheel Experience", "No DUI Record"],
    location: "",
  },
  {
    id: "motorcycle-dubrovnik-benelli-4",
    make: "Benelli",
    model: "TNT600i",
    year: 2022,
    type: "dirt bike",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Cruise Control", "Quick Shifter", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 95,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["No DUI Record", "Valid Motorcycle License", "Local Riding Permit", "Insurance Required", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-dubrovnik-triumph-5",
    make: "Triumph",
    model: "Tiger 900 GT Pro",
    year: 2020,
    type: "dirt bike",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Security System"],
    rentalPricePerDay: 87,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Transit Hub",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-dubrovnik-bajaj-6",
    make: "Bajaj",
    model: "V15",
    year: 2022,
    type: "standard",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Backrest", "Quick Shifter"],
    rentalPricePerDay: 152,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-dubrovnik-victory-7",
    make: "Victory",
    model: "Judge",
    year: 2019,
    type: "cafe racer",
    engineSize: "125cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Security System", "Adjustable Suspension", "ABS"],
    rentalPricePerDay: 127,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Local Riding Permit", "No DUI Record"],
    location: "",
  },
  {
    id: "motorcycle-dubrovnik-indian-8",
    make: "Indian",
    model: "Dark Horse",
    year: 2019,
    type: "scooter",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Metallic Brown",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)", "USB Charging", "Performance Tires"],
    rentalPricePerDay: 86,
    depositAmount: 344,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "RV Park / Campground",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Minimum Age 21", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-dubrovnik-bajaj-9",
    make: "Bajaj",
    model: "Pulsar 220F",
    year: 2023,
    type: "standard",
    engineSize: "250cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Traction Control", "Windshield"],
    rentalPricePerDay: 82,
    depositAmount: 246,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "City Center",
    dropOffCity: "san-francisco",
    dropOffCountry: "United States",
    dropOffLocation: "Train Station",
    requirements: ["Two-Wheel Experience", "Credit Card Required", "No DUI Record", "Valid Motorcycle License"],
  },
  {
    id: "motorcycle-dubrovnik-triumph-10",
    make: "Triumph",
    model: "Street Triple 765",
    year: 2021,
    type: "dual-sport",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Tire Pressure Monitoring System (TPMS)", "Security System"],
    rentalPricePerDay: 107,
    depositAmount: 428,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Train Station",
    dropOffCity: "vancouver",
    dropOffCountry: "Canada",
    dropOffLocation: "Residential Area",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "International Driving Permit (for foreign renters)"],
  },
  {
    id: "motorcycle-dubrovnik-bajaj-11",
    make: "Bajaj",
    model: "Dominar 400",
    year: 2023,
    type: "sport",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Riding Modes", "Heated Grips"],
    rentalPricePerDay: 63,
    depositAmount: 126,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Local Motorcycle Club",
    dropOffCity: "galveston",
    dropOffCountry: "United States",
    dropOffLocation: "Residential Area",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "International Driving Permit (for foreign renters)"],
  },
  {
    id: "motorcycle-dubrovnik-gasgas-12",
    make: "GasGas",
    model: "EC 450F",
    year: 2022,
    type: "cruiser",
    engineSize: "250cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included", "Saddlebags", "Backrest", "Tire Pressure Monitoring System (TPMS)", "Heated Grips"],
    rentalPricePerDay: 100,
    depositAmount: 200,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Harley-Davidson Dealership",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Safety Gear Required", "Credit Card Required", "Emergency Contact Information", "Two-Wheel Experience"],
  },
  {
    id: "motorcycle-dubrovnik-bajaj-13",
    make: "Bajaj",
    model: "V12",
    year: 2019,
    type: "scooter",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Cruise Control", "Helmet Included", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 126,
    depositAmount: 252,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Train Station",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "No DUI Record"],
  },
  {
    id: "motorcycle-dubrovnik-aprilia-14",
    make: "Aprilia",
    model: "Tuareg 660",
    year: 2019,
    type: "cruiser",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Matte White",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Anti-lock Braking System (ABS)", "GPS Navigation"],
    rentalPricePerDay: 132,
    depositAmount: 396,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Two-Wheel Experience", "International Driving Permit (for foreign renters)", "Credit Card Required"],
  },
  {
    id: "motorcycle-dubrovnik-suzuki-15",
    make: "Suzuki",
    model: "GSX-R500",
    year: 2022,
    type: "standard",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Phone Mount", "LED Headlights", "Anti-lock Braking System (ABS)", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 146,
    depositAmount: 584,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "City Center",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Emergency Contact Information", "Insurance Required", "Local Riding Permit"],
  },
  {
    id: "motorcycle-dubrovnik-aprilia-16",
    make: "Aprilia",
    model: "RSV4",
    year: 2019,
    type: "sport",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["USB Charging", "Tire Pressure Monitoring System (TPMS)", "LED Headlights", "Custom Exhaust"],
    rentalPricePerDay: 85,
    depositAmount: 255,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Harley-Davidson Dealership",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Credit Card Required", "Two-Wheel Experience"],
  }
];
