import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const dubrovnikcroatiamediterraneanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-dubrovnik-ducati-1",
    make: "Ducati",
    model: "Streetfighter V4",
    year: 2020,
    type: "scooter",
    engineSize: "650cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Cruise Control", "Bluetooth Audio"],
    rentalPricePerDay: 177,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Airport",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/ducati-streetfighter-v4.jpg",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Helmet Required"],
    availability: false,
    location: "Airport",
  },
  {
    id: "motorcycle-dubrovnik-kawasaki-2",
    make: "Kawasaki",
    model: "Ninja",
    year: 2019,
    type: "sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags", "Heated Grips"],
    rentalPricePerDay: 187,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "https://paragon-trails-motorcycle-images.com/sport/kawasaki-ninja.jpg",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Signed Waiver"],
    availability: true,
    location: "Motorcycle Dealership",
  },
  {
    id: "motorcycle-dubrovnik-royal-enfield-3",
    make: "Royal Enfield",
    model: "Bullet",
    year: 2022,
    type: "touring",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Phone Mount", "Helmet Included", "Cruise Control"],
    rentalPricePerDay: 74,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Downtown",
    imageUrl: "https://paragon-trails-motorcycle-images.com/touring/royal-enfield-bullet.jpg",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Insurance Required", "Local Riding Permit"],
    availability: false,
    location: "Downtown",
  },
  {
    id: "motorcycle-dubrovnik-royal-enfield-4",
    make: "Royal Enfield",
    model: "Meteor",
    year: 2021,
    type: "cruiser",
    engineSize: "750cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["USB Charging", "Security System", "Heated Grips", "GPS Navigation"],
    rentalPricePerDay: 71,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Downtown",
    imageUrl: "https://paragon-trails-motorcycle-images.com/cruiser/royal-enfield-meteor.jpg",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Signed Waiver", "International Driving Permit (for foreign renters)", "Minimum Age 21"],
    availability: false,
    location: "Downtown",
  },
  {
    id: "motorcycle-dubrovnik-yamaha-5",
    make: "Yamaha",
    model: "Tenere 700",
    year: 2021,
    type: "custom",
    engineSize: "750cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Phone Mount", "Backrest"],
    rentalPricePerDay: 181,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Convention Center",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/yamaha-tenere-700.jpg",
    requirements: ["Helmet Required", "Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Security Deposit Required"],
    availability: false,
    location: "Convention Center",
  },
  {
    id: "motorcycle-dubrovnik-victory-6",
    make: "Victory",
    model: "Vision",
    year: 2021,
    type: "standard",
    engineSize: "125cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust"],
    rentalPricePerDay: 51,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Transit Hub",
    imageUrl: "https://paragon-trails-motorcycle-images.com/standard/victory-vision.jpg",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Minimum Age 21", "Security Deposit Required"],
    availability: true,
    location: "Transit Hub",
  },
  {
    id: "motorcycle-dubrovnik-harley-davidson-7",
    make: "Harley-Davidson",
    model: "Softail",
    year: 2020,
    type: "standard",
    engineSize: "650cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Windshield", "Cruise Control"],
    rentalPricePerDay: 139,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "University Area",
    imageUrl: "https://paragon-trails-motorcycle-images.com/standard/harley-davidson-softail.jpg",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Minimum Age 21"],
    availability: true,
    location: "University Area",
  },
  {
    id: "motorcycle-dubrovnik-benelli-8",
    make: "Benelli",
    model: "302S",
    year: 2020,
    type: "scooter",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["USB Charging", "Phone Mount", "Bluetooth Audio", "Saddlebags"],
    rentalPricePerDay: 129,
    currency: "EUR",
    available: true,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Downtown",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/benelli-302s.jpg",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Experience with Manual Transmission"],
    availability: true,
    location: "Downtown",
  },
  {
    id: "motorcycle-dubrovnik-aprilia-9",
    make: "Aprilia",
    model: "Caponord",
    year: 2019,
    type: "scooter",
    engineSize: "250cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust", "ABS", "Heated Grips"],
    rentalPricePerDay: 186,
    currency: "EUR",
    available: false,
    pickUpCity: "Dubrovnik",
    pickUpCountry: "Croatia",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/aprilia-caponord.jpg",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Minimum Age 21"],
    availability: false,
    location: "Harley-Davidson Dealership",
  }
];
