// Auto-generated file for florence motorcycle rentals
// City: florence, Country: Italy, Region: Mediterranean

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const florenceitalymediterraneanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-florence-cfmoto-1",
    make: "CFMoto",
    model: "650MT",
    year: 2022,
    type: "custom",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Metallic Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Custom Exhaust", "Backrest", "Comfort Seat", "Bluetooth Audio", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 123,
    currency: "EUR",
    available: false,
    pickUpCity: "Florence",
    pickUpCountry: "Italy",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-florence-indian-2",
    make: "Indian",
    model: "Chief",
    year: 2019,
    type: "standard",
    engineSize: "125cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["ABS", "GPS Navigation", "Comfort Seat", "Riding Modes", "Windshield"],
    rentalPricePerDay: 103,
    currency: "EUR",
    available: true,
    pickUpCity: "Florence",
    pickUpCountry: "Italy",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "No DUI Record"],
    location: "",
  },
  {
    id: "motorcycle-florence-royal-enfield-3",
    make: "Royal Enfield",
    model: "Interceptor 650",
    year: 2023,
    type: "custom",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Tire Pressure Monitoring System (TPMS)", "ABS", "USB Charging", "Adjustable Suspension", "Bluetooth Audio"],
    rentalPricePerDay: 155,
    currency: "EUR",
    available: true,
    pickUpCity: "Florence",
    pickUpCountry: "Italy",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "No DUI Record"],
    location: "",
  },
  {
    id: "motorcycle-florence-bmw-4",
    make: "BMW",
    model: "K1600",
    year: 2023,
    type: "sport",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Metallic Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["LED Headlights", "Traction Control", "USB Charging"],
    rentalPricePerDay: 158,
    currency: "EUR",
    available: true,
    pickUpCity: "Florence",
    pickUpCountry: "Italy",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Local Riding Permit", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-florence-royal-enfield-5",
    make: "Royal Enfield",
    model: "Thunderbird X 650X Special Edition 2026",
    year: 2022,
    type: "adventure",
    engineSize: "250cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Keyless Ignition", "Cruise Control", "Bluetooth Audio", "Quick Shifter", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 110,
    currency: "EUR",
    available: false,
    pickUpCity: "Florence",
    pickUpCountry: "Italy",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Credit Card Required", "Emergency Contact Information"],
    location: "",
  },
  {
    id: "motorcycle-florence-honda-6",
    make: "Honda",
    model: "CRF450L",
    year: 2022,
    type: "dual-sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Tire Pressure Monitoring System (TPMS)", "Comfort Seat", "USB Charging"],
    rentalPricePerDay: 183,
    depositAmount: 732,
    currency: "EUR",
    available: false,
    pickUpCity: "Florence",
    pickUpCountry: "Italy",
    pickUpLocation: "Train Station",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "International Driving Permit (for foreign renters)"],
  },
  {
    id: "motorcycle-florence-suzuki-7",
    make: "Suzuki",
    model: "GSX-R750",
    year: 2019,
    type: "standard",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Keyless Ignition", "Adjustable Suspension", "Comfort Seat", "GPS Navigation", "Performance Tires"],
    rentalPricePerDay: 170,
    depositAmount: 680,
    currency: "EUR",
    available: false,
    pickUpCity: "Florence",
    pickUpCountry: "Italy",
    pickUpLocation: "City Center",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Rider Training Course Completion"],
  },
  {
    id: "motorcycle-florence-indian-8",
    make: "Indian",
    model: "Chief Super Chief Bobber Twenty Limited Dark Horse 2026",
    year: 2020,
    type: "touring",
    engineSize: "650cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["GPS Navigation", "LED Headlights", "Heated Grips", "Helmet Included"],
    rentalPricePerDay: 123,
    depositAmount: 492,
    currency: "EUR",
    available: false,
    pickUpCity: "Florence",
    pickUpCountry: "Italy",
    pickUpLocation: "Motorcycle Dealership",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Security Deposit Required", "Insurance Required"],
  }
];
