// Auto-generated file for hong-kong motorcycle rentals
// City: hong-kong, Country: China, Region: 

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const hongKongchinaMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-hong-kong-victory-1",
    make: "Victory",
    model: "Hammer S",
    year: 2019,
    type: "cafe racer",
    engineSize: "250cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Comfort Seat", "Performance Tires", "GPS Navigation", "Riding Modes"],
    rentalPricePerDay: 1059,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Rider Training Course Completion", "Two-Wheel Experience", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-kawasaki-2",
    make: "Kawasaki",
    model: "Concours",
    year: 2020,
    type: "cafe racer",
    engineSize: "125cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Heated Grips", "Performance Tires"],
    rentalPricePerDay: 1110,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["No DUI Record", "Valid Motorcycle License", "Minimum Age 21", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-harley-davidson-3",
    make: "Harley-Davidson",
    model: "Street Glide",
    year: 2021,
    type: "dual-sport",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 762,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Two-Wheel Experience", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-aprilia-4",
    make: "Aprilia",
    model: "RS 660 Limited Edition",
    year: 2022,
    type: "cafe racer",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Saddlebags", "Custom Exhaust", "USB Charging"],
    rentalPricePerDay: 730,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-royal-enfield-5",
    make: "Royal Enfield",
    model: "Thunderbird X 650X Special Edition 2024",
    year: 2022,
    type: "scooter",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Keyless Ignition", "Windshield", "Helmet Included"],
    rentalPricePerDay: 712,
    currency: "CNY",
    available: false,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Minimum Age 21", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-ducati-6",
    make: "Ducati",
    model: "Scrambler Full Throttle",
    year: 2022,
    type: "sport",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["LED Headlights", "Saddlebags", "Backrest"],
    rentalPricePerDay: 850,
    currency: "CNY",
    available: false,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-ktm-7",
    make: "KTM",
    model: "890 Adventure R Rally Pro S Special Edition 2030",
    year: 2020,
    type: "standard",
    engineSize: "250cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Traction Control", "Windshield", "Comfort Seat", "GPS Navigation"],
    rentalPricePerDay: 603,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Proof of Residency", "Security Deposit Required", "Local Riding Permit", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-husqvarna-8",
    make: "Husqvarna",
    model: "701 Supermoto",
    year: 2021,
    type: "adventure",
    engineSize: "500cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Backrest", "Security System"],
    rentalPricePerDay: 1052,
    currency: "CNY",
    available: false,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Credit Card Required", "No DUI Record"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-indian-9",
    make: "Indian",
    model: "Dark Horse",
    year: 2020,
    type: "dual-sport",
    engineSize: "250cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)", "Helmet Included", "Keyless Ignition", "GPS Navigation", "Saddlebags"],
    rentalPricePerDay: 1089,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-hong-kong-honda-10",
    make: "Honda",
    model: "CB650F",
    year: 2019,
    type: "dirt bike",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Tire Pressure Monitoring System (TPMS)", "Windshield"],
    rentalPricePerDay: 432,
    depositAmount: 864,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Motorcycle Dealership",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Security Deposit Required"],
  },
  {
    id: "motorcycle-hong-kong-kawasaki-11",
    make: "Kawasaki",
    model: "Z400",
    year: 2019,
    type: "adventure",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["USB Charging", "Comfort Seat", "Anti-lock Braking System (ABS)", "Cruise Control"],
    rentalPricePerDay: 611,
    depositAmount: 2444,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Shopping Center",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Minimum Age 21"],
  },
  {
    id: "motorcycle-hong-kong-victory-12",
    make: "Victory",
    model: "Vegas",
    year: 2019,
    type: "scooter",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Metallic Yellow",
    seatCapacity: 1,
    hasStorage: true,
    features: ["GPS Navigation", "Adjustable Suspension", "Saddlebags", "Heated Grips"],
    rentalPricePerDay: 564,
    depositAmount: 2256,
    currency: "CNY",
    available: false,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "RV Park / Campground",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Emergency Contact Information", "Rider Training Course Completion", "Local Riding Permit"],
  },
  {
    id: "motorcycle-hong-kong-cfmoto-13",
    make: "CFMoto",
    model: "700CL-X Sport",
    year: 2021,
    type: "custom",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 2,
    hasStorage: true,
    features: ["USB Charging", "Traction Control"],
    rentalPricePerDay: 565,
    depositAmount: 1130,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Harley-Davidson Dealership",
    dropOffCity: "san-juan",
    dropOffCountry: "Puerto Rico",
    dropOffLocation: "Local Motorcycle Club",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Credit Card Required", "Two-Wheel Experience", "International Driving Permit (for foreign renters)"],
  },
  {
    id: "motorcycle-hong-kong-yamaha-14",
    make: "Yamaha",
    model: "YZF-R6",
    year: 2019,
    type: "dual-sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Comfort Seat", "Security System"],
    rentalPricePerDay: 821,
    depositAmount: 2463,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "RV Park / Campground",
    dropOffCity: "ho-chi-minh-city",
    dropOffCountry: "Vietnam",
    dropOffLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Experience with Manual Transmission", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-hong-kong-zero-15",
    make: "Zero",
    model: "SR/S Premium",
    year: 2019,
    type: "custom",
    engineSize: "650cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 2,
    hasStorage: false,
    features: ["LED Headlights", "Security System"],
    rentalPricePerDay: 990,
    depositAmount: 1980,
    currency: "CNY",
    available: false,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Convention Center",
    dropOffCity: "zanzibar",
    dropOffCountry: "Tanzania",
    dropOffLocation: "Shopping Center",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Two-Wheel Experience", "Safety Gear Required", "International Driving Permit (for foreign renters)"],
  },
  {
    id: "motorcycle-hong-kong-honda-16",
    make: "Honda",
    model: "CB500S",
    year: 2019,
    type: "scooter",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Saddlebags", "Cruise Control", "Custom Exhaust"],
    rentalPricePerDay: 1019,
    depositAmount: 3057,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Train Station",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Local Riding Permit", "Insurance Required"],
  },
  {
    id: "motorcycle-hong-kong-husqvarna-17",
    make: "Husqvarna",
    model: "FE 501",
    year: 2023,
    type: "dirt bike",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control", "Adjustable Suspension", "Traction Control", "Comfort Seat"],
    rentalPricePerDay: 901,
    depositAmount: 2703,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Residential Area",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Emergency Contact Information", "No DUI Record"],
  },
  {
    id: "motorcycle-hong-kong-zero-18",
    make: "Zero",
    model: "S",
    year: 2021,
    type: "cafe racer",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Anti-lock Braking System (ABS)", "GPS Navigation"],
    rentalPricePerDay: 395,
    depositAmount: 1185,
    currency: "CNY",
    available: true,
    pickUpCity: "Hong Kong",
    pickUpCountry: "China",
    pickUpLocation: "Tourist District",
    requirements: ["Valid Motorcycle License", "Safety Gear Required"],
  }
];
