// Auto-generated file for juneau motorcycle rentals
// City: juneau, Country: United States, Region: Alaska

// Generated on: 2025-06-08T04:09:39.210Z

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const juneauunitedStatesalaskaMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-juneau-suzuki-1",
    make: "Suzuki",
    model: "GSX-R400",
    year: 2019,
    type: "adventure",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Anti-lock Braking System (ABS)", "Traction Control"],
    rentalPricePerDay: 170,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-juneau-can-am-2",
    make: "Can-Am",
    model: "Spyder ST",
    year: 2020,
    type: "custom",
    engineSize: "250cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Comfort Seat"],
    rentalPricePerDay: 184,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Minimum Age 21", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-juneau-kawasaki-3",
    make: "Kawasaki",
    model: "Ninja",
    year: 2022,
    type: "standard",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Helmet Included", "Anti-lock Braking System (ABS)", "Tire Pressure Monitoring System (TPMS)", "Bluetooth Audio"],
    rentalPricePerDay: 164,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Insurance Required", "Credit Card Required", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-juneau-kawasaki-4",
    make: "Kawasaki",
    model: "Z125 Pro",
    year: 2020,
    type: "custom",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips"],
    rentalPricePerDay: 115,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Emergency Contact Information", "No DUI Record"],
    location: "",
  },
  {
    id: "motorcycle-juneau-indian-5",
    make: "Indian",
    model: "Chief Limited",
    year: 2019,
    type: "adventure",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["GPS Navigation"],
    rentalPricePerDay: 107,
    depositAmount: 214,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Two-Wheel Experience", "Rider Training Course Completion", "Safety Gear Required"],
  },
  {
    id: "motorcycle-juneau-ktm-6",
    make: "KTM",
    model: "1290 Super Duke",
    year: 2023,
    type: "dual-sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control", "Performance Tires", "Custom Exhaust", "Quick Shifter", "Heated Grips"],
    rentalPricePerDay: 184,
    depositAmount: 368,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Airport",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Security Deposit Required", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-juneau-can-am-7",
    make: "Can-Am",
    model: "Ryker 900",
    year: 2022,
    type: "dual-sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Performance Tires", "Helmet Included", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 78,
    depositAmount: 156,
    currency: "USD",
    available: false,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Residential Area",
    requirements: ["Experience with Manual Transmission", "Valid Motorcycle License", "Local Riding Permit"],
  },
  {
    id: "motorcycle-juneau-moto-guzzi-8",
    make: "Moto Guzzi",
    model: "Stelvio",
    year: 2023,
    type: "scooter",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Comfort Seat", "Quick Shifter", "ABS"],
    rentalPricePerDay: 119,
    depositAmount: 238,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    dropOffCity: "sydney",
    dropOffCountry: "Australia",
    dropOffLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Credit Card Required"],
  },
  {
    id: "motorcycle-juneau-suzuki-9",
    make: "Suzuki",
    model: "Hayabusa",
    year: 2019,
    type: "scooter",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Phone Mount"],
    rentalPricePerDay: 135,
    depositAmount: 270,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Insurance Required"],
  },
  {
    id: "motorcycle-juneau-indian-10",
    make: "Indian",
    model: "Chief Vintage",
    year: 2023,
    type: "cruiser",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Comfort Seat", "Heated Grips", "Windshield"],
    rentalPricePerDay: 194,
    depositAmount: 388,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Proof of Residency", "Security Deposit Required"],
  },
  {
    id: "motorcycle-juneau-suzuki-11",
    make: "Suzuki",
    model: "GSX-R125",
    year: 2023,
    type: "cafe racer",
    engineSize: "125cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Quick Shifter"],
    rentalPricePerDay: 108,
    depositAmount: 324,
    currency: "USD",
    available: false,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Transit Hub",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Helmet Required", "Two-Wheel Experience", "Signed Waiver"],
  },
  {
    id: "motorcycle-juneau-moto-guzzi-12",
    make: "Moto Guzzi",
    model: "California Touring 1400 Touring Special Edition 2024",
    year: 2022,
    type: "adventure",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["USB Charging", "Performance Tires"],
    rentalPricePerDay: 124,
    depositAmount: 496,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Insurance Required"],
  },
  {
    id: "motorcycle-juneau-bajaj-13",
    make: "Bajaj",
    model: "Pulsar AS200",
    year: 2019,
    type: "dirt bike",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Keyless Ignition", "Comfort Seat", "Quick Shifter", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 83,
    depositAmount: 249,
    currency: "USD",
    available: true,
    pickUpCity: "Juneau",
    pickUpCountry: "United States",
    pickUpLocation: "RV Park / Campground",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Helmet Required", "No DUI Record", "Signed Waiver"],
  }
];
