// Auto-generated file for lima motorcycle rentals
// City: lima, Country: Peru, Region: Peru

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const limaperuperuMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-lima-moto-guzzi-1",
    make: "Moto Guzzi",
    model: "MGX-21",
    year: 2022,
    type: "custom",
    engineSize: "125cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Phone Mount", "Helmet Included", "Tire Pressure Monitoring System (TPMS)", "Comfort Seat"],
    rentalPricePerDay: 393,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Rider Training Course Completion", "Minimum Age 21", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-lima-gasgas-2",
    make: "GasGas",
    model: "EC 300",
    year: 2023,
    type: "dual-sport",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control", "Security System", "Saddlebags", "Phone Mount", "LED Headlights"],
    rentalPricePerDay: 244,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Security Deposit Required", "Safety Gear Required", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-lima-kawasaki-3",
    make: "Kawasaki",
    model: "KLX140",
    year: 2023,
    type: "adventure",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["USB Charging", "Custom Exhaust"],
    rentalPricePerDay: 322,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Local Riding Permit", "Minimum Age 21", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-lima-kawasaki-4",
    make: "Kawasaki",
    model: "Concours",
    year: 2023,
    type: "cruiser",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags", "ABS", "Tire Pressure Monitoring System (TPMS)", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 481,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Experience with Manual Transmission", "Helmet Required", "Rider Training Course Completion", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-lima-bajaj-5",
    make: "Bajaj",
    model: "CT100",
    year: 2022,
    type: "custom",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["ABS", "Backrest", "Windshield", "Adjustable Suspension", "LED Headlights"],
    rentalPricePerDay: 426,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-lima-indian-6",
    make: "Indian",
    model: "Chief Super Chief Bobber Twenty Limited Dark Horse 2030",
    year: 2022,
    type: "scooter",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Helmet Included", "Performance Tires"],
    rentalPricePerDay: 278,
    currency: "PEN",
    available: false,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Safety Gear Required", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-lima-kawasaki-7",
    make: "Kawasaki",
    model: "Ninja ZX-10R",
    year: 2021,
    type: "standard",
    engineSize: "750cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["ABS", "GPS Navigation", "Phone Mount", "Saddlebags"],
    rentalPricePerDay: 318,
    depositAmount: 1272,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Car Rental Lot",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Local Riding Permit", "Credit Card Required", "Rider Training Course Completion"],
  },
  {
    id: "motorcycle-lima-triumph-8",
    make: "Triumph",
    model: "Tiger 900 GT Explorer",
    year: 2020,
    type: "cafe racer",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Quick Shifter"],
    rentalPricePerDay: 496,
    depositAmount: 992,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "University Area",
    dropOffCity: "bermuda",
    dropOffCountry: "Bermuda",
    dropOffLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Local Riding Permit"],
  },
  {
    id: "motorcycle-lima-moto-guzzi-9",
    make: "Moto Guzzi",
    model: "California Touring 1400",
    year: 2023,
    type: "custom",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["ABS", "LED Headlights", "Cruise Control", "Heated Grips", "Backrest"],
    rentalPricePerDay: 250,
    depositAmount: 500,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Airport",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Local Riding Permit", "Minimum Age 21", "Insurance Required"],
  },
  {
    id: "motorcycle-lima-aprilia-10",
    make: "Aprilia",
    model: "RS 125",
    year: 2023,
    type: "cruiser",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Saddlebags", "Phone Mount", "GPS Navigation"],
    rentalPricePerDay: 344,
    depositAmount: 1376,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Transit Hub",
    dropOffCity: "montevideo",
    dropOffCountry: "Uruguay",
    dropOffLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Two-Wheel Experience", "Credit Card Required"],
  },
  {
    id: "motorcycle-lima-harley-davidson-11",
    make: "Harley-Davidson",
    model: "Fat Boy",
    year: 2022,
    type: "scooter",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Anti-lock Braking System (ABS)", "Custom Exhaust", "Security System"],
    rentalPricePerDay: 269,
    depositAmount: 807,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "City Center",
    dropOffCity: "singapore",
    dropOffCountry: "Singapore",
    dropOffLocation: "Shopping Center",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Proof of Residency", "International Driving Permit (for foreign renters)", "Helmet Required"],
  },
  {
    id: "motorcycle-lima-moto-guzzi-12",
    make: "Moto Guzzi",
    model: "California Touring 1400 Touring Special Edition 2024",
    year: 2023,
    type: "touring",
    engineSize: "500cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Phone Mount"],
    rentalPricePerDay: 327,
    depositAmount: 654,
    currency: "PEN",
    available: false,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "City Center",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Security Deposit Required"],
  },
  {
    id: "motorcycle-lima-zero-13",
    make: "Zero",
    model: "DSR/X",
    year: 2020,
    type: "cruiser",
    engineSize: "500cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Adjustable Suspension", "Tire Pressure Monitoring System (TPMS)", "ABS", "Custom Exhaust"],
    rentalPricePerDay: 512,
    depositAmount: 2048,
    currency: "PEN",
    available: false,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "RV Park / Campground",
    dropOffCity: "miami",
    dropOffCountry: "United States",
    dropOffLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "International Driving Permit (for foreign renters)", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-lima-royal-enfield-14",
    make: "Royal Enfield",
    model: "Thunderbird X",
    year: 2023,
    type: "cruiser",
    engineSize: "750cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["USB Charging", "Saddlebags", "Comfort Seat"],
    rentalPricePerDay: 364,
    depositAmount: 1456,
    currency: "PEN",
    available: true,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "Transit Hub",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Credit Card Required", "Experience with Manual Transmission"],
  },
  {
    id: "motorcycle-lima-bajaj-15",
    make: "Bajaj",
    model: "Dominar 250",
    year: 2023,
    type: "touring",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Yellow",
    seatCapacity: 1,
    hasStorage: true,
    features: ["GPS Navigation", "Anti-lock Braking System (ABS)", "LED Headlights"],
    rentalPricePerDay: 294,
    depositAmount: 882,
    currency: "PEN",
    available: false,
    pickUpCity: "Lima",
    pickUpCountry: "Peru",
    pickUpLocation: "City Center",
    requirements: ["No DUI Record", "Helmet Required", "Experience with Manual Transmission", "Valid Motorcycle License", "Insurance Required"],
  }
];
