// Auto-generated file for malta motorcycle rentals
// City: malta, Country: Malta, Region: Mediterranean

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const maltamaltamediterraneanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-malta-indian-1",
    make: "Indian",
    model: "Chief Vintage",
    year: 2021,
    type: "touring",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Phone Mount", "Quick Shifter", "Custom Exhaust", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 157,
    currency: "EUR",
    available: true,
    pickUpCity: "Malta",
    pickUpCountry: "Malta",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Safety Gear Required", "Credit Card Required", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-malta-husqvarna-2",
    make: "Husqvarna",
    model: "701 Supermoto",
    year: 2020,
    type: "scooter",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["ABS", "Security System"],
    rentalPricePerDay: 138,
    currency: "EUR",
    available: false,
    pickUpCity: "Malta",
    pickUpCountry: "Malta",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Two-Wheel Experience", "Experience with Manual Transmission", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-malta-suzuki-3",
    make: "Suzuki",
    model: "GSX250R",
    year: 2021,
    type: "sport",
    engineSize: "125cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Heated Grips"],
    rentalPricePerDay: 111,
    currency: "EUR",
    available: true,
    pickUpCity: "Malta",
    pickUpCountry: "Malta",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-malta-suzuki-4",
    make: "Suzuki",
    model: "DR-Z400",
    year: 2023,
    type: "cruiser",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included", "Riding Modes", "Saddlebags", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 132,
    depositAmount: 264,
    currency: "EUR",
    available: true,
    pickUpCity: "Malta",
    pickUpCountry: "Malta",
    pickUpLocation: "RV Park / Campground",
    dropOffCity: "quebec-city",
    dropOffCountry: "Canada",
    dropOffLocation: "Shopping Center",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Helmet Required", "Local Riding Permit"],
  },
  {
    id: "motorcycle-malta-suzuki-5",
    make: "Suzuki",
    model: "GSX-R1000",
    year: 2020,
    type: "scooter",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["GPS Navigation"],
    rentalPricePerDay: 103,
    depositAmount: 412,
    currency: "EUR",
    available: true,
    pickUpCity: "Malta",
    pickUpCountry: "Malta",
    pickUpLocation: "Car Rental Lot",
    dropOffCity: "venice",
    dropOffCountry: "Italy",
    dropOffLocation: "Hotel Pickup",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Safety Gear Required", "Insurance Required", "Proof of Residency"],
  },
  {
    id: "motorcycle-malta-husqvarna-6",
    make: "Husqvarna",
    model: "FE 501s TE 300i",
    year: 2021,
    type: "dirt bike",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "White",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Saddlebags", "Custom Exhaust", "Helmet Included", "Heated Grips"],
    rentalPricePerDay: 101,
    depositAmount: 404,
    currency: "EUR",
    available: true,
    pickUpCity: "Malta",
    pickUpCountry: "Malta",
    pickUpLocation: "Airport",
    requirements: ["Safety Gear Required", "Valid Motorcycle License", "Signed Waiver"],
  }
];
