// Auto-generated file for milan motorcycle rentals
// City: milan, Country: Italy, Region: Mediterranean

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const milanitalymediterraneanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-milan-indian-1",
    make: "Indian",
    model: "Challenger",
    year: 2021,
    type: "cruiser",
    engineSize: "500cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Phone Mount", "Bluetooth Audio"],
    rentalPricePerDay: 136,
    currency: "EUR",
    available: false,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "No DUI Record", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-milan-honda-2",
    make: "Honda",
    model: "Rebel",
    year: 2022,
    type: "cruiser",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Keyless Ignition", "Phone Mount", "Saddlebags"],
    rentalPricePerDay: 131,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-milan-kawasaki-3",
    make: "Kawasaki",
    model: "Ninja ZX-6R",
    year: 2019,
    type: "cafe racer",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control", "Custom Exhaust", "LED Headlights", "ABS"],
    rentalPricePerDay: 108,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Signed Waiver", "Valid Motorcycle License", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-milan-suzuki-4",
    make: "Suzuki",
    model: "GSX250R",
    year: 2021,
    type: "scooter",
    engineSize: "750cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips", "Phone Mount", "USB Charging", "LED Headlights"],
    rentalPricePerDay: 90,
    depositAmount: 180,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Hotel Pickup",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Local Riding Permit"],
  },
  {
    id: "motorcycle-milan-gasgas-5",
    make: "GasGas",
    model: "EC 450F",
    year: 2020,
    type: "touring",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Comfort Seat", "ABS", "Performance Tires"],
    rentalPricePerDay: 115,
    depositAmount: 345,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Safety Gear Required"],
  },
  {
    id: "motorcycle-milan-bmw-6",
    make: "BMW",
    model: "F900XR",
    year: 2023,
    type: "cruiser",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included", "Security System", "Keyless Ignition", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 106,
    depositAmount: 318,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Shopping Center",
    dropOffCity: "buenos-aires",
    dropOffCountry: "Argentina",
    dropOffLocation: "Shopping Center",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Safety Gear Required"],
  }
];
