import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const milanitalymediterraneanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-milan-triumph-1",
    make: "Triumph",
    model: "Scrambler",
    year: 2022,
    type: "standard",
    engineSize: "125cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 2,
    hasStorage: false,
    features: ["USB Charging"],
    rentalPricePerDay: 135,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "City Center",
    dropOffCity: "santorini",
    dropOffCountry: "Greece",
    dropOffLocation: "Transit Hub",
    imageUrl: "https://paragon-trails-motorcycle-images.com/standard/triumph-scrambler.jpg",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "International Driving Permit (for foreign renters)"],
    availability: true,
    location: "City Center",
  },
  {
    id: "motorcycle-milan-zero-2",
    make: "Zero",
    model: "FXE",
    year: 2021,
    type: "scooter",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Windshield"],
    rentalPricePerDay: 97,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Train Station",
    dropOffCity: "nassau",
    dropOffCountry: "Bahamas",
    dropOffLocation: "Shopping Center",
    imageUrl: "https://paragon-trails-motorcycle-images.com/scooter/zero-fxe.jpg",
    requirements: ["Local Riding Permit", "Credit Card Required", "Insurance Required", "Valid Motorcycle License", "Minimum Age 21"],
    availability: true,
    location: "Train Station",
  },
  {
    id: "motorcycle-milan-zero-3",
    make: "Zero",
    model: "DSR/X",
    year: 2020,
    type: "cruiser",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Phone Mount"],
    rentalPricePerDay: 139,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "https://paragon-trails-motorcycle-images.com/cruiser/zero-dsr/x.jpg",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Helmet Required", "Minimum Age 21", "No DUI Record"],
    availability: true,
    location: "Hotel Pickup",
  },
  {
    id: "motorcycle-milan-husqvarna-4",
    make: "Husqvarna",
    model: "701 Enduro",
    year: 2020,
    type: "touring",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Windshield", "Cruise Control", "Helmet Included", "Heated Grips"],
    rentalPricePerDay: 124,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "University Area",
    dropOffCity: "boston",
    dropOffCountry: "United States",
    dropOffLocation: "Motorcycle Dealership",
    imageUrl: "https://paragon-trails-motorcycle-images.com/touring/husqvarna-701-enduro.jpg",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Security Deposit Required"],
    availability: true,
    location: "University Area",
  },
  {
    id: "motorcycle-milan-victory-5",
    make: "Victory",
    model: "Vision",
    year: 2021,
    type: "sport",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Phone Mount", "USB Charging", "Backrest"],
    rentalPricePerDay: 134,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Train Station",
    imageUrl: "https://paragon-trails-motorcycle-images.com/sport/victory-vision.jpg",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Minimum Age 21"],
    availability: true,
    location: "Train Station",
  },
  {
    id: "motorcycle-milan-zero-6",
    make: "Zero",
    model: "S",
    year: 2021,
    type: "dual-sport",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Heated Grips", "USB Charging", "Bluetooth Audio", "Cruise Control"],
    rentalPricePerDay: 155,
    currency: "EUR",
    available: true,
    pickUpCity: "Milan",
    pickUpCountry: "Italy",
    pickUpLocation: "Tourist District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/dual-sport/zero-s.jpg",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Two-Wheel Experience", "International Driving Permit (for foreign renters)", "Local Riding Permit"],
    availability: true,
    location: "Tourist District",
  }
];
