import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const newOrleansunitedStatescaribbeanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-new-orleans-harley-davidson-1",
    make: "Harley-Davidson",
    model: "Iron 883",
    year: 2021,
    type: "custom",
    engineSize: "500cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Security System"],
    rentalPricePerDay: 152,
    currency: "USD",
    available: true,
    pickUpCity: "New Orleans",
    pickUpCountry: "United States",
    pickUpLocation: "Tourist District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/harley-davidson-iron-883.jpg",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "International Driving Permit (for foreign renters)", "Security Deposit Required"],
    availability: true,
    location: "Tourist District",
  },
  {
    id: "motorcycle-new-orleans-royal-enfield-2",
    make: "Royal Enfield",
    model: "Interceptor 650",
    year: 2023,
    type: "dual-sport",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Security System", "Phone Mount", "Custom Exhaust", "USB Charging"],
    rentalPricePerDay: 116,
    currency: "USD",
    available: false,
    pickUpCity: "New Orleans",
    pickUpCountry: "United States",
    pickUpLocation: "Shopping Center",
    dropOffCity: "fort-lauderdale",
    dropOffCountry: "United States",
    dropOffLocation: "Airport",
    imageUrl: "https://paragon-trails-motorcycle-images.com/dual-sport/royal-enfield-interceptor-650.jpg",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Signed Waiver"],
    availability: false,
    location: "Shopping Center",
  },
  {
    id: "motorcycle-new-orleans-indian-3",
    make: "Indian",
    model: "Pursuit",
    year: 2023,
    type: "touring",
    engineSize: "500cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Heated Grips", "Helmet Included"],
    rentalPricePerDay: 77,
    currency: "USD",
    available: false,
    pickUpCity: "New Orleans",
    pickUpCountry: "United States",
    pickUpLocation: "Shopping Center",
    dropOffCity: "auckland",
    dropOffCountry: "New Zealand",
    dropOffLocation: "Car Rental Lot",
    imageUrl: "https://paragon-trails-motorcycle-images.com/touring/indian-pursuit.jpg",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Minimum Age 21"],
    availability: false,
    location: "Shopping Center",
  },
  {
    id: "motorcycle-new-orleans-harley-davidson-4",
    make: "Harley-Davidson",
    model: "Road Glide",
    year: 2020,
    type: "standard",
    engineSize: "750cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Bluetooth Audio", "Phone Mount", "Backrest", "Security System"],
    rentalPricePerDay: 123,
    currency: "USD",
    available: true,
    pickUpCity: "New Orleans",
    pickUpCountry: "United States",
    pickUpLocation: "RV Park / Campground",
    dropOffCity: "buenos-aires",
    dropOffCountry: "Argentina",
    dropOffLocation: "Hotel Pickup",
    imageUrl: "https://paragon-trails-motorcycle-images.com/standard/harley-davidson-road-glide.jpg",
    requirements: ["Valid Motorcycle License", "Helmet Required"],
    availability: true,
    location: "RV Park / Campground",
  },
  {
    id: "motorcycle-new-orleans-benelli-5",
    make: "Benelli",
    model: "302S",
    year: 2019,
    type: "sport",
    engineSize: "750cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: false,
    features: ["GPS Navigation", "Security System"],
    rentalPricePerDay: 153,
    currency: "USD",
    available: true,
    pickUpCity: "New Orleans",
    pickUpCountry: "United States",
    pickUpLocation: "Tourist District",
    imageUrl: "https://paragon-trails-motorcycle-images.com/sport/benelli-302s.jpg",
    requirements: ["Security Deposit Required", "Valid Motorcycle License", "Insurance Required"],
    availability: true,
    location: "Tourist District",
  },
  {
    id: "motorcycle-new-orleans-aprilia-6",
    make: "Aprilia",
    model: "Shiver",
    year: 2019,
    type: "custom",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Helmet Included", "Custom Exhaust"],
    rentalPricePerDay: 185,
    currency: "USD",
    available: true,
    pickUpCity: "New Orleans",
    pickUpCountry: "United States",
    pickUpLocation: "Residential Area",
    imageUrl: "https://paragon-trails-motorcycle-images.com/custom/aprilia-shiver.jpg",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Security Deposit Required"],
    availability: true,
    location: "Residential Area",
  }
];
