// Auto-generated file for panauti motorcycle rentals
// City: panauti, Country: Nepal, Region: Nepal

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const panautinepalnepalMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-panauti-ducati-1",
    make: "Ducati",
    model: "Scrambler Sixty2",
    year: 2023,
    type: "sport",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Metallic Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Tire Pressure Monitoring System (TPMS)", "GPS Navigation", "Comfort Seat"],
    rentalPricePerDay: 9674,
    currency: "NPR",
    available: false,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Security Deposit Required", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-panauti-zero-2",
    make: "Zero",
    model: "FX",
    year: 2019,
    type: "standard",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Riding Modes", "Keyless Ignition", "Windshield", "Performance Tires"],
    rentalPricePerDay: 15062,
    currency: "NPR",
    available: true,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "No DUI Record", "International Driving Permit (for foreign renters)", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-panauti-triumph-3",
    make: "Triumph",
    model: "Street Triple 765 RS",
    year: 2022,
    type: "custom",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Yellow",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Phone Mount", "Custom Exhaust", "GPS Navigation", "Cruise Control"],
    rentalPricePerDay: 13238,
    currency: "NPR",
    available: true,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Minimum Age 21", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-panauti-ktm-4",
    make: "KTM",
    model: "890 Adventure R Rally",
    year: 2022,
    type: "cruiser",
    engineSize: "500cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Bluetooth Audio", "Tire Pressure Monitoring System (TPMS)", "Saddlebags", "Backrest", "Custom Exhaust"],
    rentalPricePerDay: 11370,
    currency: "NPR",
    available: false,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Insurance Required", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-panauti-can-am-5",
    make: "Can-Am",
    model: "Ryker 900 ACE",
    year: 2023,
    type: "cafe racer",
    engineSize: "250cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: false,
    features: ["GPS Navigation", "Saddlebags", "ABS", "Security System"],
    rentalPricePerDay: 19284,
    depositAmount: 38568,
    currency: "NPR",
    available: true,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Residential Area",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Helmet Required", "Two-Wheel Experience"],
  },
  {
    id: "motorcycle-panauti-royal-enfield-6",
    make: "Royal Enfield",
    model: "Thunderbird X 650X Special Edition",
    year: 2021,
    type: "standard",
    engineSize: "125cc",
    transmission: "manual",
    color: "Matte White",
    seatCapacity: 1,
    hasStorage: false,
    features: ["LED Headlights", "Security System", "Saddlebags", "Comfort Seat"],
    rentalPricePerDay: 15712,
    depositAmount: 47136,
    currency: "NPR",
    available: true,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Motorcycle Dealership",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Experience with Manual Transmission", "Rider Training Course Completion", "Credit Card Required"],
  },
  {
    id: "motorcycle-panauti-bmw-7",
    make: "BMW",
    model: "F750GS",
    year: 2021,
    type: "custom",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Matte White",
    seatCapacity: 1,
    hasStorage: false,
    features: ["ABS", "Comfort Seat"],
    rentalPricePerDay: 16284,
    depositAmount: 48852,
    currency: "NPR",
    available: true,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Car Rental Lot",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Experience with Manual Transmission", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-panauti-aprilia-8",
    make: "Aprilia",
    model: "Tuono",
    year: 2020,
    type: "cafe racer",
    engineSize: "125cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)", "Saddlebags", "ABS"],
    rentalPricePerDay: 14520,
    depositAmount: 43560,
    currency: "NPR",
    available: false,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Two-Wheel Experience", "Signed Waiver"],
  },
  {
    id: "motorcycle-panauti-indian-9",
    make: "Indian",
    model: "Chief Super Chief Bobber Twenty Dark Horse",
    year: 2020,
    type: "standard",
    engineSize: "900cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Helmet Included"],
    rentalPricePerDay: 8743,
    depositAmount: 17486,
    currency: "NPR",
    available: false,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Car Rental Lot",
    dropOffCity: "dubrovnik",
    dropOffCountry: "Croatia",
    dropOffLocation: "Convention Center",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Safety Gear Required", "International Driving Permit (for foreign renters)"],
  },
  {
    id: "motorcycle-panauti-victory-10",
    make: "Victory",
    model: "Octane",
    year: 2023,
    type: "standard",
    engineSize: "250cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Bluetooth Audio", "Security System", "Riding Modes"],
    rentalPricePerDay: 18376,
    depositAmount: 36752,
    currency: "NPR",
    available: false,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Rider Training Course Completion", "Local Riding Permit"],
  },
  {
    id: "motorcycle-panauti-kawasaki-11",
    make: "Kawasaki",
    model: "Ninja ZX-10R",
    year: 2021,
    type: "dirt bike",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Saddlebags", "Cruise Control", "Phone Mount", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 13227,
    depositAmount: 39681,
    currency: "NPR",
    available: true,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Harley-Davidson Dealership",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "International Driving Permit (for foreign renters)", "No DUI Record"],
  },
  {
    id: "motorcycle-panauti-gasgas-12",
    make: "GasGas",
    model: "EC 350F",
    year: 2022,
    type: "sport",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Anti-lock Braking System (ABS)", "Heated Grips"],
    rentalPricePerDay: 19033,
    depositAmount: 57099,
    currency: "NPR",
    available: true,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Transit Hub",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Safety Gear Required", "Emergency Contact Information", "Helmet Required"],
  },
  {
    id: "motorcycle-panauti-kawasaki-13",
    make: "Kawasaki",
    model: "KX250F",
    year: 2022,
    type: "sport",
    engineSize: "500cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Performance Tires", "Cruise Control", "Comfort Seat"],
    rentalPricePerDay: 15189,
    depositAmount: 30378,
    currency: "NPR",
    available: true,
    pickUpCity: "Panauti",
    pickUpCountry: "Nepal",
    pickUpLocation: "Convention Center",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Rider Training Course Completion", "Proof of Residency"],
  }
];
