// Auto-generated file for philipsburg motorcycle rentals
// City: philipsburg, Country: Sint Maarten, Region: Sint Maarten

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const philipsburgsintMaartensintMaartenMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-philipsburg-benelli-1",
    make: "Benelli",
    model: "Leonardo 125",
    year: 2020,
    type: "scooter",
    engineSize: "650cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)", "Adjustable Suspension", "USB Charging", "Custom Exhaust", "Performance Tires"],
    rentalPricePerDay: 302,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Proof of Residency", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-can-am-2",
    make: "Can-Am",
    model: "Ryker",
    year: 2020,
    type: "cruiser",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Phone Mount", "Tire Pressure Monitoring System (TPMS)", "USB Charging"],
    rentalPricePerDay: 182,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["No DUI Record", "Helmet Required", "Experience with Manual Transmission", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-royal-enfield-3",
    make: "Royal Enfield",
    model: "Thunderbird X 650X Special Edition 2027",
    year: 2023,
    type: "dual-sport",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Comfort Seat", "Phone Mount", "GPS Navigation", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 207,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Proof of Residency", "Valid Motorcycle License", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-zero-4",
    make: "Zero",
    model: "SR/S",
    year: 2022,
    type: "dual-sport",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["LED Headlights", "Cruise Control", "Traction Control", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 137,
    currency: "ANG",
    available: false,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "International Driving Permit (for foreign renters)", "Security Deposit Required", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-suzuki-5",
    make: "Suzuki",
    model: "GSX-R1000",
    year: 2019,
    type: "cafe racer",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)", "USB Charging"],
    rentalPricePerDay: 142,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Signed Waiver", "Proof of Residency", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-bajaj-6",
    make: "Bajaj",
    model: "V15",
    year: 2020,
    type: "dirt bike",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Security System", "Helmet Included"],
    rentalPricePerDay: 244,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-benelli-7",
    make: "Benelli",
    model: "Leonardo 125",
    year: 2020,
    type: "standard",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Quick Shifter", "GPS Navigation", "Keyless Ignition", "Traction Control"],
    rentalPricePerDay: 214,
    currency: "ANG",
    available: false,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-victory-8",
    make: "Victory",
    model: "Vegas",
    year: 2021,
    type: "standard",
    engineSize: "650cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: true,
    features: ["ABS", "Tire Pressure Monitoring System (TPMS)", "Quick Shifter", "GPS Navigation", "Security System"],
    rentalPricePerDay: 118,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Helmet Required", "Emergency Contact Information"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-aprilia-9",
    make: "Aprilia",
    model: "SX 125",
    year: 2022,
    type: "sport",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 221,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Helmet Required", "Experience with Manual Transmission", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-philipsburg-aprilia-10",
    make: "Aprilia",
    model: "RS 660",
    year: 2022,
    type: "cruiser",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Windshield"],
    rentalPricePerDay: 125,
    depositAmount: 250,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Airport",
    dropOffCity: "singapore",
    dropOffCountry: "Singapore",
    dropOffLocation: "Local Motorcycle Club",
    requirements: ["Valid Motorcycle License", "Security Deposit Required"],
  },
  {
    id: "motorcycle-philipsburg-yamaha-11",
    make: "Yamaha",
    model: "Super Ténéré",
    year: 2020,
    type: "standard",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Quick Shifter", "Traction Control"],
    rentalPricePerDay: 167,
    depositAmount: 501,
    currency: "ANG",
    available: false,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Harley-Davidson Dealership",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Rider Training Course Completion"],
  },
  {
    id: "motorcycle-philipsburg-aprilia-12",
    make: "Aprilia",
    model: "RS 660 Limited Edition",
    year: 2019,
    type: "adventure",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Cruise Control"],
    rentalPricePerDay: 182,
    depositAmount: 546,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Tourist District",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Security Deposit Required", "Minimum Age 21", "International Driving Permit (for foreign renters)"],
  },
  {
    id: "motorcycle-philipsburg-bmw-13",
    make: "BMW",
    model: "C400GT",
    year: 2023,
    type: "adventure",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Traction Control", "Adjustable Suspension", "Windshield", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 102,
    depositAmount: 408,
    currency: "ANG",
    available: false,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Transit Hub",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Rider Training Course Completion"],
  },
  {
    id: "motorcycle-philipsburg-cfmoto-14",
    make: "CFMoto",
    model: "700CL-X Sport",
    year: 2021,
    type: "cafe racer",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Traction Control", "Riding Modes", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 122,
    depositAmount: 488,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Transit Hub",
    requirements: ["Two-Wheel Experience", "Valid Motorcycle License", "Minimum Age 21"],
  },
  {
    id: "motorcycle-philipsburg-moto-guzzi-15",
    make: "Moto Guzzi",
    model: "Stelvio",
    year: 2022,
    type: "standard",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Backrest", "Traction Control", "Heated Grips", "Adjustable Suspension"],
    rentalPricePerDay: 164,
    depositAmount: 492,
    currency: "ANG",
    available: false,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "RV Park / Campground",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Security Deposit Required"],
  },
  {
    id: "motorcycle-philipsburg-suzuki-16",
    make: "Suzuki",
    model: "GSX-R400",
    year: 2022,
    type: "dirt bike",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control"],
    rentalPricePerDay: 194,
    depositAmount: 776,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Hotel Pickup",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Local Riding Permit", "Helmet Required"],
  },
  {
    id: "motorcycle-philipsburg-kawasaki-17",
    make: "Kawasaki",
    model: "Ninja 1000",
    year: 2020,
    type: "sport",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Phone Mount", "Custom Exhaust", "Backrest", "Comfort Seat"],
    rentalPricePerDay: 225,
    depositAmount: 450,
    currency: "ANG",
    available: false,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Local Motorcycle Club",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Local Riding Permit", "No DUI Record", "Helmet Required"],
  },
  {
    id: "motorcycle-philipsburg-indian-18",
    make: "Indian",
    model: "Scout Sixty",
    year: 2020,
    type: "cruiser",
    engineSize: "250cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Quick Shifter", "Performance Tires"],
    rentalPricePerDay: 155,
    depositAmount: 465,
    currency: "ANG",
    available: true,
    pickUpCity: "Philipsburg",
    pickUpCountry: "Sint Maarten",
    pickUpLocation: "Convention Center",
    dropOffCity: "tahiti",
    dropOffCountry: "French Polynesia",
    dropOffLocation: "Local Motorcycle Club",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Two-Wheel Experience", "No DUI Record", "International Driving Permit (for foreign renters)"],
  }
];
