// Auto-generated file for portland motorcycle rentals
// City: portland, Country: United States, Region: Oregon

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const portlandunitedStatesoregonMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-portland-indian-1",
    make: "Indian",
    model: "Chief Vintage",
    year: 2023,
    type: "sport",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Quick Shifter", "Helmet Included", "Windshield"],
    rentalPricePerDay: 182,
    currency: "USD",
    available: false,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Local Riding Permit", "Signed Waiver", "Safety Gear Required", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-portland-royal-enfield-2",
    make: "Royal Enfield",
    model: "Thunderbird X 650X Special Edition 2023",
    year: 2023,
    type: "dual-sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Keyless Ignition"],
    rentalPricePerDay: 136,
    currency: "USD",
    available: false,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-portland-triumph-3",
    make: "Triumph",
    model: "Tiger",
    year: 2019,
    type: "adventure",
    engineSize: "500cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Adjustable Suspension"],
    rentalPricePerDay: 63,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Credit Card Required", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-portland-victory-4",
    make: "Victory",
    model: "Vision Tour",
    year: 2020,
    type: "cafe racer",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Security System"],
    rentalPricePerDay: 119,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Local Riding Permit", "Valid Motorcycle License", "Signed Waiver", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-portland-moto-guzzi-5",
    make: "Moto Guzzi",
    model: "California Touring 1400 Touring Special",
    year: 2022,
    type: "cafe racer",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Backrest", "Custom Exhaust", "Performance Tires", "Keyless Ignition", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 109,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Insurance Required", "Minimum Age 21", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-portland-ducati-6",
    make: "Ducati",
    model: "Streetfighter V4 SP2 S Lamborghini Speciale 2025",
    year: 2022,
    type: "standard",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["GPS Navigation", "Traction Control"],
    rentalPricePerDay: 109,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-portland-gasgas-7",
    make: "GasGas",
    model: "MC 125",
    year: 2023,
    type: "sport",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included", "Traction Control", "ABS", "Bluetooth Audio"],
    rentalPricePerDay: 123,
    currency: "USD",
    available: false,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Tourist District",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Local Riding Permit", "Signed Waiver", "No DUI Record", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-portland-royal-enfield-8",
    make: "Royal Enfield",
    model: "Thunderbird X 650X Special Edition 2025",
    year: 2021,
    type: "cafe racer",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Matte White",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)", "USB Charging"],
    rentalPricePerDay: 110,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "",
    requirements: ["Minimum Age 21", "Valid Motorcycle License", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-portland-harley-davidson-9",
    make: "Harley-Davidson",
    model: "CVO Street Bob",
    year: 2022,
    type: "standard",
    engineSize: "250cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Saddlebags", "Heated Grips", "GPS Navigation", "Windshield"],
    rentalPricePerDay: 150,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-portland-ktm-10",
    make: "KTM",
    model: "890 Adventure R",
    year: 2023,
    type: "custom",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte White",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Quick Shifter", "USB Charging", "ABS"],
    rentalPricePerDay: 154,
    depositAmount: 462,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Harley-Davidson Dealership",
    dropOffCity: "lisbon",
    dropOffCountry: "Portugal",
    dropOffLocation: "Local Motorcycle Club",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "No DUI Record", "Local Riding Permit"],
  },
  {
    id: "motorcycle-portland-ducati-11",
    make: "Ducati",
    model: "Multistrada 1260",
    year: 2020,
    type: "sport",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Windshield", "Traction Control", "Riding Modes"],
    rentalPricePerDay: 109,
    depositAmount: 218,
    currency: "USD",
    available: false,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Airport",
    dropOffCity: "puno",
    dropOffCountry: "Peru",
    dropOffLocation: "Convention Center",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Local Riding Permit"],
  },
  {
    id: "motorcycle-portland-kawasaki-12",
    make: "Kawasaki",
    model: "Z650",
    year: 2023,
    type: "sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Traction Control", "Windshield"],
    rentalPricePerDay: 140,
    depositAmount: 420,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Credit Card Required", "Local Riding Permit"],
  },
  {
    id: "motorcycle-portland-gasgas-13",
    make: "GasGas",
    model: "MC 125",
    year: 2020,
    type: "sport",
    engineSize: "900cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Backrest", "Heated Grips", "Security System", "Traction Control"],
    rentalPricePerDay: 98,
    depositAmount: 196,
    currency: "USD",
    available: false,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Car Rental Lot",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Minimum Age 21", "Rider Training Course Completion", "Helmet Required"],
  },
  {
    id: "motorcycle-portland-zero-14",
    make: "Zero",
    model: "S",
    year: 2022,
    type: "dual-sport",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Bluetooth Audio", "Traction Control", "Keyless Ignition", "Windshield", "Quick Shifter"],
    rentalPricePerDay: 95,
    depositAmount: 190,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Transit Hub",
    dropOffCity: "hong-kong",
    dropOffCountry: "China",
    dropOffLocation: "Shopping Center",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Rider Training Course Completion", "Proof of Residency", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-portland-yamaha-15",
    make: "Yamaha",
    model: "XSR900",
    year: 2020,
    type: "sport",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Bluetooth Audio"],
    rentalPricePerDay: 99,
    depositAmount: 297,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Train Station",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Credit Card Required"],
  },
  {
    id: "motorcycle-portland-aprilia-16",
    make: "Aprilia",
    model: "SX 125",
    year: 2022,
    type: "dual-sport",
    engineSize: "250cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips", "Traction Control"],
    rentalPricePerDay: 150,
    depositAmount: 600,
    currency: "USD",
    available: false,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Experience with Manual Transmission", "Safety Gear Required", "Emergency Contact Information", "Rider Training Course Completion"],
  },
  {
    id: "motorcycle-portland-kawasaki-17",
    make: "Kawasaki",
    model: "Z125 Pro",
    year: 2020,
    type: "dirt bike",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Security System", "Adjustable Suspension", "Performance Tires"],
    rentalPricePerDay: 113,
    depositAmount: 339,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "City Center",
    dropOffCity: "shanghai",
    dropOffCountry: "China",
    dropOffLocation: "Tourist District",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Local Riding Permit", "Insurance Required"],
  },
  {
    id: "motorcycle-portland-husqvarna-18",
    make: "Husqvarna",
    model: "FE 350s",
    year: 2022,
    type: "touring",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Helmet Included", "Tire Pressure Monitoring System (TPMS)", "Phone Mount", "Riding Modes", "ABS"],
    rentalPricePerDay: 138,
    depositAmount: 414,
    currency: "USD",
    available: true,
    pickUpCity: "Portland",
    pickUpCountry: "United States",
    pickUpLocation: "Shopping Center",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Rider Training Course Completion", "Local Riding Permit"],
  }
];
