// Auto-generated file for roatan motorcycle rentals
// City: roatan, Country: Honduras, Region: Caribbean

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const roatanhondurascaribbeanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-roatan-bmw-1",
    make: "BMW",
    model: "F900XR",
    year: 2022,
    type: "sport",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Cruise Control", "Saddlebags"],
    rentalPricePerDay: 3446,
    currency: "HNL",
    available: true,
    pickUpCity: "Roatan",
    pickUpCountry: "Honduras",
    pickUpLocation: "Transit Hub",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-roatan-moto-guzzi-2",
    make: "Moto Guzzi",
    model: "California Touring 1400 Touring Special Edition",
    year: 2022,
    type: "custom",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Performance Tires", "ABS", "Quick Shifter"],
    rentalPricePerDay: 2602,
    currency: "HNL",
    available: true,
    pickUpCity: "Roatan",
    pickUpCountry: "Honduras",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-roatan-cfmoto-3",
    make: "CFMoto",
    model: "650NK",
    year: 2020,
    type: "custom",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Bluetooth Audio"],
    rentalPricePerDay: 1619,
    currency: "HNL",
    available: true,
    pickUpCity: "Roatan",
    pickUpCountry: "Honduras",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Signed Waiver", "Helmet Required", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-roatan-indian-4",
    make: "Indian",
    model: "Scout Bobber",
    year: 2021,
    type: "cruiser",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Quick Shifter", "ABS", "Security System", "Traction Control"],
    rentalPricePerDay: 1944,
    depositAmount: 3888,
    currency: "HNL",
    available: true,
    pickUpCity: "Roatan",
    pickUpCountry: "Honduras",
    pickUpLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Local Riding Permit"],
  },
  {
    id: "motorcycle-roatan-husqvarna-5",
    make: "Husqvarna",
    model: "FE 501s TE 300i",
    year: 2020,
    type: "touring",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Performance Tires", "Anti-lock Braking System (ABS)", "Custom Exhaust"],
    rentalPricePerDay: 2735,
    depositAmount: 10940,
    currency: "HNL",
    available: false,
    pickUpCity: "Roatan",
    pickUpCountry: "Honduras",
    pickUpLocation: "Train Station",
    requirements: ["Insurance Required", "Emergency Contact Information", "Credit Card Required", "Valid Motorcycle License", "Signed Waiver"],
  },
  {
    id: "motorcycle-roatan-aprilia-6",
    make: "Aprilia",
    model: "RS 660 Factory",
    year: 2022,
    type: "scooter",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Adjustable Suspension"],
    rentalPricePerDay: 2961,
    depositAmount: 8883,
    currency: "HNL",
    available: true,
    pickUpCity: "Roatan",
    pickUpCountry: "Honduras",
    pickUpLocation: "Train Station",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Local Riding Permit"],
  }
];
