import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const romeitalymediterraneanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-rome-honda-1",
    make: "Honda",
    model: "Rebel",
    year: 2023,
    type: "cruiser",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Windshield", "Custom Exhaust"],
    rentalPricePerDay: 105,
    currency: "EUR",
    available: true,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Airport",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/honda-rebel.jpg",
    requirements: [],
    availability: true,
    location: "Airport",
  },
  {
    id: "motorcycle-rome-ktm-2",
    make: "KTM",
    model: "1290 Super Adventure",
    year: 2022,
    type: "touring",
    engineSize: "650cc",
    transmission: "automatic",
    color: "White",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included", "ABS", "GPS Navigation", "Windshield"],
    rentalPricePerDay: 66,
    currency: "EUR",
    available: false,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Shopping District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/ktm-1290-super-adventure.jpg",
    requirements: [],
    availability: false,
    location: "Shopping District",
  },
  {
    id: "motorcycle-rome-suzuki-3",
    make: "Suzuki",
    model: "Hayabusa",
    year: 2021,
    type: "sport",
    engineSize: "500cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: true,
    features: [],
    rentalPricePerDay: 58,
    currency: "EUR",
    available: true,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "City Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/sport/suzuki-hayabusa.jpg",
    requirements: [],
    availability: true,
    location: "City Center",
  },
  {
    id: "motorcycle-rome-ktm-4",
    make: "KTM",
    model: "690 SMC",
    year: 2023,
    type: "scooter",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: false,
    features: ["USB Charging"],
    rentalPricePerDay: 60,
    currency: "EUR",
    available: true,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Tourist District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/ktm-690-smc.jpg",
    requirements: [],
    availability: true,
    location: "Tourist District",
  },
  {
    id: "motorcycle-rome-kawasaki-5",
    make: "Kawasaki",
    model: "Z650",
    year: 2022,
    type: "touring",
    engineSize: "125cc",
    transmission: "automatic",
    color: "White",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Helmet Included", "Saddlebags"],
    rentalPricePerDay: 160,
    currency: "EUR",
    available: true,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Downtown",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/kawasaki-z650.jpg",
    requirements: [],
    availability: true,
    location: "Downtown",
  },
  {
    id: "motorcycle-rome-victory-6",
    make: "Victory",
    model: "High-Ball",
    year: 2022,
    type: "cruiser",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Heated Grips", "Cruise Control", "Phone Mount"],
    rentalPricePerDay: 74,
    currency: "EUR",
    available: true,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Transit Hub",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/victory-high-ball.jpg",
    requirements: [],
    availability: true,
    location: "Transit Hub",
  },
  {
    id: "motorcycle-rome-aprilia-7",
    make: "Aprilia",
    model: "Dorsoduro",
    year: 2022,
    type: "cruiser",
    engineSize: "125cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control", "Backrest", "USB Charging", "Phone Mount"],
    rentalPricePerDay: 143,
    currency: "EUR",
    available: true,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Marina",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/aprilia-dorsoduro.jpg",
    requirements: [],
    availability: true,
    location: "Marina",
  },
  {
    id: "motorcycle-rome-royal-enfield-8",
    make: "Royal Enfield",
    model: "Continental GT",
    year: 2023,
    type: "dual-sport",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Security System", "GPS Navigation", "ABS", "USB Charging"],
    rentalPricePerDay: 109,
    currency: "EUR",
    available: true,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Downtown",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/dual-sport/royal-enfield-continental-gt.jpg",
    requirements: [],
    availability: true,
    location: "Downtown",
  },
  {
    id: "motorcycle-rome-victory-9",
    make: "Victory",
    model: "Octane",
    year: 2023,
    type: "dual-sport",
    engineSize: "500cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["ABS"],
    rentalPricePerDay: 94,
    currency: "EUR",
    available: true,
    pickUpCity: "rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Tourist District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/dual-sport/victory-octane.jpg",
    requirements: [],
    availability: true,
    location: "Tourist District",
  },
  {
    id: "motorcycle-rome-kawasaki-10",
    make: "Kawasaki",
    model: "Z650",
    year: 2022,
    type: "touring",
    engineSize: "1400cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: false,
    features: [
      "Heated Grips",
      "Custom Exhaust",
      "GPS Navigation",
      "Bluetooth Audio",
    ],
    rentalPricePerDay: 163,
    currency: "EUR",
    available: false,
    pickUpCity: "Rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Transit Hub",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/kawasaki-z650.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Security Deposit Required",
      "Helmet Required",
      "Insurance Required",
    ],
    availability: false,
    location: "Transit Hub",
  },
  {
    id: "motorcycle-rome-victory-11",
    make: "Victory",
    model: "Gunner",
    year: 2023,
    type: "touring",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Backrest", "GPS Navigation", "Bluetooth Audio"],
    rentalPricePerDay: 86,
    currency: "EUR",
    available: false,
    pickUpCity: "Rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Shopping District",
    dropOffCity: "vancouver",
    dropOffCountry: "Canada",
    dropOffLocation: "Tourist District",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/victory-gunner.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Local Riding Permit",
      "International Driving Permit (for foreign renters)",
    ],
    availability: false,
    location: "Shopping District",
  },
  {
    id: "motorcycle-rome-yamaha-12",
    make: "Yamaha",
    model: "V Star",
    year: 2021,
    type: "cruiser",
    engineSize: "650cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Saddlebags", "Windshield", "Security System"],
    rentalPricePerDay: 169,
    currency: "EUR",
    available: true,
    pickUpCity: "Rome",
    pickUpCountry: "Italy",
    pickUpLocation: "Marina",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/cruiser/yamaha-v-star.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Credit Card Required",
      "Experience with Manual Transmission",
      "Signed Waiver",
      "Security Deposit Required",
    ],
    availability: true,
    location: "Marina",
  },
];
