import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const sanJuanpuertoRicocaribbeanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-san-juan-royal-enfield-1",
    make: "Royal Enfield",
    model: "Interceptor 650",
    year: 2020,
    type: "standard",
    engineSize: "125cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust", "Security System", "ABS", "Saddlebags"],
    rentalPricePerDay: 186,
    currency: "USD",
    available: true,
    pickUpCity: "san-juan",
    pickUpCountry: "Puerto Rico",
    pickUpLocation: "Convention Center",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/standard/royal-enfield-interceptor-650.jpg",
    requirements: [],
    availability: true,
    location: "Convention Center",
  },
  {
    id: "motorcycle-san-juan-harley-davidson-2",
    make: "Harley-Davidson",
    model: "Electra Glide",
    year: 2023,
    type: "scooter",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Backrest", "Helmet Included", "Phone Mount", "Saddlebags"],
    rentalPricePerDay: 101,
    currency: "USD",
    available: true,
    pickUpCity: "san-juan",
    pickUpCountry: "Puerto Rico",
    pickUpLocation: "Airport",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/harley-davidson-electra-glide.jpg",
    requirements: [],
    availability: true,
    location: "Airport",
  },
  {
    id: "motorcycle-san-juan-yamaha-3",
    make: "Yamaha",
    model: "MT-09",
    year: 2019,
    type: "scooter",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Helmet Included", "Heated Grips"],
    rentalPricePerDay: 70,
    currency: "USD",
    available: false,
    pickUpCity: "san-juan",
    pickUpCountry: "Puerto Rico",
    pickUpLocation: "Near Beach",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/scooter/yamaha-mt-09.jpg",
    requirements: [],
    availability: false,
    location: "Near Beach",
  },
  {
    id: "motorcycle-san-juan-triumph-4",
    make: "Triumph",
    model: "Thruxton",
    year: 2021,
    type: "standard",
    engineSize: "125cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust", "Windshield"],
    rentalPricePerDay: 152,
    currency: "USD",
    available: false,
    pickUpCity: "San-juan",
    pickUpCountry: "Puerto Rico",
    pickUpLocation: "Transit Hub",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/standard/triumph-thruxton.jpg",
    requirements: ["Valid Motorcycle License", "Insurance Required"],
    availability: false,
    location: "Transit Hub",
  },
  {
    id: "motorcycle-san-juan-harley-davidson-5",
    make: "Harley-Davidson",
    model: "Road Glide",
    year: 2023,
    type: "touring",
    engineSize: "650cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags", "Security System", "USB Charging"],
    rentalPricePerDay: 134,
    currency: "USD",
    available: true,
    pickUpCity: "San-juan",
    pickUpCountry: "Puerto Rico",
    pickUpLocation: "Airport",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/touring/harley-davidson-road-glide.jpg",
    requirements: [
      "Valid Motorcycle License",
      "Minimum Age 21",
      "Credit Card Required",
    ],
    availability: true,
    location: "Airport",
  },
  {
    id: "motorcycle-san-juan-husqvarna-6",
    make: "Husqvarna",
    model: "Svartpilen 401",
    year: 2020,
    type: "dual-sport",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Phone Mount", "Security System", "GPS Navigation"],
    rentalPricePerDay: 93,
    currency: "USD",
    available: false,
    pickUpCity: "San-juan",
    pickUpCountry: "Puerto Rico",
    pickUpLocation: "Downtown",
    imageUrl:
      "https://paragon-trails-motorcycle-images.com/dual-sport/husqvarna-svartpilen-401.jpg",
    requirements: [
      "No DUI Record",
      "Credit Card Required",
      "Valid Motorcycle License",
    ],
    availability: false,
    location: "Downtown",
  },
];
