// Auto-generated file for santiago motorcycle rentals
// City: santiago, Country: Chile, Region: South America

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const santiagochilesouthAmericaMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-santiago-ducati-1",
    make: "Ducati",
    model: "Streetfighter V4 SP2 S Lamborghini Speciale 2034",
    year: 2023,
    type: "scooter",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Bluetooth Audio", "Phone Mount"],
    rentalPricePerDay: 112343,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Insurance Required", "Safety Gear Required", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-santiago-yamaha-2",
    make: "Yamaha",
    model: "YZF-R6",
    year: 2023,
    type: "dirt bike",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Comfort Seat", "Quick Shifter", "Adjustable Suspension", "Performance Tires"],
    rentalPricePerDay: 53346,
    currency: "CLP",
    available: false,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Emergency Contact Information"],
    location: "",
  },
  {
    id: "motorcycle-santiago-suzuki-3",
    make: "Suzuki",
    model: "GSX-R300",
    year: 2023,
    type: "cafe racer",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included"],
    rentalPricePerDay: 50885,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Rider Training Course Completion", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-santiago-honda-4",
    make: "Honda",
    model: "CB500S",
    year: 2021,
    type: "dirt bike",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Performance Tires", "USB Charging", "Heated Grips", "GPS Navigation", "Windshield"],
    rentalPricePerDay: 65648,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Helmet Required", "Credit Card Required", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-santiago-harley-davidson-5",
    make: "Harley-Davidson",
    model: "Softail Slim",
    year: 2021,
    type: "scooter",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Helmet Included", "Anti-lock Braking System (ABS)", "Traction Control", "LED Headlights", "Custom Exhaust"],
    rentalPricePerDay: 91048,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Proof of Residency", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-santiago-bmw-6",
    make: "BMW",
    model: "F900XR",
    year: 2020,
    type: "dual-sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Adjustable Suspension", "Security System", "ABS", "Phone Mount"],
    rentalPricePerDay: 69735,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Minimum Age 21", "Experience with Manual Transmission", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-santiago-harley-davidson-7",
    make: "Harley-Davidson",
    model: "Softail Slim",
    year: 2022,
    type: "standard",
    engineSize: "650cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Adjustable Suspension", "Comfort Seat", "LED Headlights"],
    rentalPricePerDay: 95959,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-santiago-aprilia-8",
    make: "Aprilia",
    model: "RS 250",
    year: 2021,
    type: "cafe racer",
    engineSize: "250cc",
    transmission: "manual",
    color: "Metallic Yellow",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Comfort Seat", "Backrest", "Custom Exhaust", "Keyless Ignition", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 80386,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["No DUI Record", "Signed Waiver", "Valid Motorcycle License", "Insurance Required", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-santiago-moto-guzzi-9",
    make: "Moto Guzzi",
    model: "California Touring 1400 Touring Special Edition 2027",
    year: 2023,
    type: "custom",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Traction Control", "Heated Grips", "Keyless Ignition", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 94347,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["No DUI Record", "Proof of Residency", "Minimum Age 21", "Valid Motorcycle License", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-santiago-moto-guzzi-10",
    make: "Moto Guzzi",
    model: "MGX-21",
    year: 2022,
    type: "scooter",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags", "Backrest"],
    rentalPricePerDay: 106633,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Credit Card Required", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-santiago-husqvarna-11",
    make: "Husqvarna",
    model: "FE 501s TE 300i",
    year: 2023,
    type: "dual-sport",
    engineSize: "250cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Adjustable Suspension", "Saddlebags"],
    rentalPricePerDay: 61547,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-santiago-honda-12",
    make: "Honda",
    model: "CBR1000RR SP",
    year: 2023,
    type: "custom",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Cruise Control", "Bluetooth Audio"],
    rentalPricePerDay: 106618,
    currency: "CLP",
    available: false,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Security Deposit Required", "Safety Gear Required"],
    location: "",
  },
  {
    id: "motorcycle-santiago-zero-13",
    make: "Zero",
    model: "D",
    year: 2022,
    type: "adventure",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips", "LED Headlights"],
    rentalPricePerDay: 108263,
    currency: "CLP",
    available: false,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Minimum Age 21", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-santiago-bajaj-14",
    make: "Bajaj",
    model: "V15",
    year: 2022,
    type: "custom",
    engineSize: "750cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Keyless Ignition", "Saddlebags", "Riding Modes"],
    rentalPricePerDay: 64002,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-santiago-yamaha-15",
    make: "Yamaha",
    model: "XSR700",
    year: 2023,
    type: "custom",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Keyless Ignition", "Tire Pressure Monitoring System (TPMS)", "Phone Mount", "Windshield"],
    rentalPricePerDay: 70558,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-santiago-royal-enfield-16",
    make: "Royal Enfield",
    model: "Thunderbird X 650X Special Edition 2024",
    year: 2022,
    type: "adventure",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Matte White",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust", "GPS Navigation", "Quick Shifter", "Keyless Ignition", "Backrest"],
    rentalPricePerDay: 107460,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Emergency Contact Information", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-santiago-bmw-17",
    make: "BMW",
    model: "C400X",
    year: 2021,
    type: "cafe racer",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust", "ABS", "USB Charging"],
    rentalPricePerDay: 77108,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Helmet Required", "Rider Training Course Completion", "Two-Wheel Experience"],
    location: "",
  },
  {
    id: "motorcycle-santiago-yamaha-18",
    make: "Yamaha",
    model: "YZF-R1",
    year: 2019,
    type: "touring",
    engineSize: "500cc",
    transmission: "manual",
    color: "White",
    seatCapacity: 2,
    hasStorage: true,
    features: ["ABS", "Traction Control", "GPS Navigation"],
    rentalPricePerDay: 100897,
    currency: "CLP",
    available: false,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-santiago-ducati-19",
    make: "Ducati",
    model: "Diavel 1260 S",
    year: 2023,
    type: "touring",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Performance Tires", "Traction Control", "Tire Pressure Monitoring System (TPMS)", "LED Headlights", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 47561,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-santiago-ducati-20",
    make: "Ducati",
    model: "Streetfighter V4 SP2 S Lamborghini Speciale 2025",
    year: 2019,
    type: "scooter",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Traction Control", "Custom Exhaust", "LED Headlights"],
    rentalPricePerDay: 100064,
    currency: "CLP",
    available: false,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-santiago-moto-guzzi-21",
    make: "Moto Guzzi",
    model: "California",
    year: 2020,
    type: "sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Security System", "Comfort Seat", "Custom Exhaust", "Heated Grips", "Performance Tires"],
    rentalPricePerDay: 105804,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Proof of Residency", "Insurance Required", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-santiago-ktm-22",
    make: "KTM",
    model: "890 Adventure R Rally Pro S Special Edition 2023",
    year: 2023,
    type: "touring",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Performance Tires", "Comfort Seat"],
    rentalPricePerDay: 121391,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Emergency Contact Information", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-santiago-harley-davidson-23",
    make: "Harley-Davidson",
    model: "Street Bob",
    year: 2023,
    type: "sport",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Matte White",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust"],
    rentalPricePerDay: 75461,
    depositAmount: 150922,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "University Area",
    dropOffCity: "seattle",
    dropOffCountry: "United States",
    dropOffLocation: "Transit Hub",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Experience with Manual Transmission", "Emergency Contact Information", "Local Riding Permit"],
  },
  {
    id: "motorcycle-santiago-ducati-24",
    make: "Ducati",
    model: "Streetfighter V4 SP2 Lamborghini",
    year: 2021,
    type: "standard",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Matte White",
    seatCapacity: 2,
    hasStorage: false,
    features: ["ABS", "Heated Grips", "Quick Shifter", "Tire Pressure Monitoring System (TPMS)", "Keyless Ignition"],
    rentalPricePerDay: 76309,
    depositAmount: 152618,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Residential Area",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Safety Gear Required", "Credit Card Required", "Helmet Required"],
  },
  {
    id: "motorcycle-santiago-can-am-25",
    make: "Can-Am",
    model: "Ryker",
    year: 2022,
    type: "custom",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Custom Exhaust", "Bluetooth Audio"],
    rentalPricePerDay: 63184,
    depositAmount: 126368,
    currency: "CLP",
    available: true,
    pickUpCity: "Santiago",
    pickUpCountry: "Chile",
    pickUpLocation: "Airport",
    requirements: ["Security Deposit Required", "Proof of Residency", "Valid Motorcycle License"],
  }
];
