// Auto-generated file for skagway motorcycle rentals
// City: skagway, Country: United States, Region: Alaska

// Generated on: 2025-06-08T04:09:39.222Z

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const skagwayunitedStatesalaskaMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-skagway-harley-davidson-1",
    make: "Harley-Davidson",
    model: "Electra Glide",
    year: 2023,
    type: "sport",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Comfort Seat", "Custom Exhaust", "USB Charging", "Windshield"],
    rentalPricePerDay: 153,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Rider Training Course Completion", "Minimum Age 21", "No DUI Record", "Valid Motorcycle License", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-skagway-suzuki-2",
    make: "Suzuki",
    model: "GSX-R400",
    year: 2020,
    type: "touring",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Tire Pressure Monitoring System (TPMS)", "Quick Shifter"],
    rentalPricePerDay: 118,
    currency: "USD",
    available: false,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Local Riding Permit", "Helmet Required", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-skagway-benelli-3",
    make: "Benelli",
    model: "TNT899",
    year: 2023,
    type: "touring",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 2,
    hasStorage: true,
    features: ["LED Headlights", "Adjustable Suspension", "Traction Control", "Security System"],
    rentalPricePerDay: 165,
    currency: "USD",
    available: false,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Local Riding Permit", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-skagway-can-am-4",
    make: "Can-Am",
    model: "Ryker 900 Sport",
    year: 2023,
    type: "cafe racer",
    engineSize: "250cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation"],
    rentalPricePerDay: 176,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Safety Gear Required", "Minimum Age 21", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-skagway-bmw-5",
    make: "BMW",
    model: "K1600B",
    year: 2021,
    type: "dual-sport",
    engineSize: "125cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Windshield", "Phone Mount"],
    rentalPricePerDay: 68,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Security Deposit Required", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-skagway-indian-6",
    make: "Indian",
    model: "Chief Super Chief Bobber Dark Horse",
    year: 2022,
    type: "scooter",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Custom Exhaust", "Keyless Ignition", "LED Headlights", "Adjustable Suspension", "Saddlebags"],
    rentalPricePerDay: 60,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Safety Gear Required", "Experience with Manual Transmission", "Insurance Required", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-skagway-husqvarna-7",
    make: "Husqvarna",
    model: "FC 450",
    year: 2023,
    type: "cafe racer",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Windshield", "Cruise Control", "Riding Modes"],
    rentalPricePerDay: 132,
    depositAmount: 528,
    currency: "USD",
    available: false,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Harley-Davidson Dealership",
    dropOffCity: "hong-kong",
    dropOffCountry: "Hong Kong",
    dropOffLocation: "Tourist District",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Minimum Age 21", "Proof of Residency", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-skagway-yamaha-8",
    make: "Yamaha",
    model: "Tenere 700",
    year: 2019,
    type: "dirt bike",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Keyless Ignition"],
    rentalPricePerDay: 147,
    depositAmount: 294,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Motorcycle Dealership",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Experience with Manual Transmission"],
  },
  {
    id: "motorcycle-skagway-bmw-9",
    make: "BMW",
    model: "S1000RR",
    year: 2020,
    type: "scooter",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Keyless Ignition", "Phone Mount", "Bluetooth Audio", "Heated Grips", "Helmet Included"],
    rentalPricePerDay: 132,
    depositAmount: 396,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Harley-Davidson Dealership",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Credit Card Required", "No DUI Record", "Signed Waiver"],
  },
  {
    id: "motorcycle-skagway-suzuki-10",
    make: "Suzuki",
    model: "GSX-R300",
    year: 2020,
    type: "adventure",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Security System", "Anti-lock Braking System (ABS)", "Helmet Included"],
    rentalPricePerDay: 155,
    depositAmount: 310,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Transit Hub",
    dropOffCity: "juneau",
    dropOffCountry: "United States",
    dropOffLocation: "Car Rental Lot",
    requirements: ["Valid Motorcycle License", "Credit Card Required", "Safety Gear Required", "Emergency Contact Information", "Local Riding Permit"],
  },
  {
    id: "motorcycle-skagway-can-am-11",
    make: "Can-Am",
    model: "Ryker 900",
    year: 2021,
    type: "custom",
    engineSize: "500cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips", "Tire Pressure Monitoring System (TPMS)", "Cruise Control"],
    rentalPricePerDay: 147,
    depositAmount: 441,
    currency: "USD",
    available: false,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Hotel Pickup",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Safety Gear Required", "Proof of Residency", "Signed Waiver", "No DUI Record"],
  },
  {
    id: "motorcycle-skagway-kawasaki-12",
    make: "Kawasaki",
    model: "Ninja ZX-10R",
    year: 2021,
    type: "cafe racer",
    engineSize: "250cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Keyless Ignition", "Backrest"],
    rentalPricePerDay: 152,
    depositAmount: 608,
    currency: "USD",
    available: false,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Tourist District",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Safety Gear Required"],
  },
  {
    id: "motorcycle-skagway-honda-13",
    make: "Honda",
    model: "CRF450L",
    year: 2019,
    type: "sport",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Phone Mount", "Helmet Included", "Tire Pressure Monitoring System (TPMS)", "Cruise Control"],
    rentalPricePerDay: 112,
    depositAmount: 336,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Residential Area",
    dropOffCity: "vancouver",
    dropOffCountry: "Canada",
    dropOffLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Experience with Manual Transmission", "Signed Waiver"],
  },
  {
    id: "motorcycle-skagway-husqvarna-14",
    make: "Husqvarna",
    model: "FE 501s TE 300i",
    year: 2023,
    type: "cruiser",
    engineSize: "125cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Riding Modes"],
    rentalPricePerDay: 172,
    depositAmount: 688,
    currency: "USD",
    available: false,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Local Motorcycle Club",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Insurance Required", "Two-Wheel Experience", "Safety Gear Required", "Emergency Contact Information"],
  },
  {
    id: "motorcycle-skagway-benelli-15",
    make: "Benelli",
    model: "TNT1130",
    year: 2021,
    type: "cruiser",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Adjustable Suspension", "Performance Tires", "Anti-lock Braking System (ABS)", "Keyless Ignition"],
    rentalPricePerDay: 173,
    depositAmount: 519,
    currency: "USD",
    available: true,
    pickUpCity: "Skagway",
    pickUpCountry: "United States",
    pickUpLocation: "Convention Center",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Helmet Required"],
  }
];
