// Auto-generated file for st-thomas motorcycle rentals
// City: st-thomas, Country: U.S. Virgin Islands, Region: Caribbean

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const stThomasusVirginIslandscaribbeanMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-st-thomas-triumph-1",
    make: "Triumph",
    model: "Tiger 900 GT Low",
    year: 2022,
    type: "scooter",
    engineSize: "900cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["LED Headlights"],
    rentalPricePerDay: 91,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["International Driving Permit (for foreign renters)", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-triumph-2",
    make: "Triumph",
    model: "Tiger",
    year: 2019,
    type: "sport",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Phone Mount", "Security System", "LED Headlights", "Tire Pressure Monitoring System (TPMS)", "Traction Control"],
    rentalPricePerDay: 132,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Residential Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-can-am-3",
    make: "Can-Am",
    model: "Spyder RT Limited",
    year: 2020,
    type: "cruiser",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Metallic Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Windshield"],
    rentalPricePerDay: 127,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Security Deposit Required", "Valid Motorcycle License", "Helmet Required", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-aprilia-4",
    make: "Aprilia",
    model: "RS 660",
    year: 2020,
    type: "custom",
    engineSize: "650cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Performance Tires", "Comfort Seat", "Riding Modes", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 100,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Hotel Pickup",
    imageUrl: "",
    requirements: ["Emergency Contact Information", "Local Riding Permit", "Valid Motorcycle License", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-victory-5",
    make: "Victory",
    model: "Kingpin",
    year: 2023,
    type: "adventure",
    engineSize: "125cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Cruise Control", "Windshield", "GPS Navigation"],
    rentalPricePerDay: 166,
    currency: "USD",
    available: false,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Helmet Required", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-victory-6",
    make: "Victory",
    model: "Cross Roads",
    year: 2022,
    type: "cruiser",
    engineSize: "125cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Comfort Seat", "Windshield", "Helmet Included", "Custom Exhaust", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 88,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-cfmoto-7",
    make: "CFMoto",
    model: "300NK",
    year: 2019,
    type: "custom",
    engineSize: "250cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Windshield", "Phone Mount", "Heated Grips"],
    rentalPricePerDay: 131,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "International Driving Permit (for foreign renters)"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-harley-davidson-8",
    make: "Harley-Davidson",
    model: "CVO Street Glide",
    year: 2023,
    type: "cafe racer",
    engineSize: "125cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Backrest"],
    rentalPricePerDay: 109,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Signed Waiver", "Proof of Residency", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-indian-9",
    make: "Indian",
    model: "Pursuit",
    year: 2022,
    type: "scooter",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Bluetooth Audio", "Quick Shifter"],
    rentalPricePerDay: 171,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-bajaj-10",
    make: "Bajaj",
    model: "Avenger Street 160",
    year: 2023,
    type: "standard",
    engineSize: "750cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Helmet Included"],
    rentalPricePerDay: 106,
    currency: "USD",
    available: false,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Proof of Residency", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-honda-11",
    make: "Honda",
    model: "CBR125R",
    year: 2019,
    type: "custom",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Windshield", "Security System"],
    rentalPricePerDay: 57,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "Signed Waiver", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-moto-guzzi-12",
    make: "Moto Guzzi",
    model: "California Touring 1400 Touring Special Edition 2028",
    year: 2019,
    type: "cafe racer",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Traction Control"],
    rentalPricePerDay: 164,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Helmet Required", "No DUI Record", "International Driving Permit (for foreign renters)", "Valid Motorcycle License", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-aprilia-13",
    make: "Aprilia",
    model: "RS 660",
    year: 2021,
    type: "dual-sport",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: true,
    features: ["ABS", "Heated Grips", "Performance Tires", "Keyless Ignition", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 149,
    currency: "USD",
    available: false,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-kawasaki-14",
    make: "Kawasaki",
    model: "KX250",
    year: 2022,
    type: "touring",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Metallic Gray",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Traction Control", "Tire Pressure Monitoring System (TPMS)", "ABS"],
    rentalPricePerDay: 100,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Credit Card Required", "Experience with Manual Transmission", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-husqvarna-15",
    make: "Husqvarna",
    model: "FE 450s TE 300i",
    year: 2022,
    type: "sport",
    engineSize: "650cc",
    transmission: "automatic",
    color: "Green",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Quick Shifter", "Anti-lock Braking System (ABS)", "GPS Navigation", "Windshield"],
    rentalPricePerDay: 107,
    currency: "USD",
    available: false,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Rider Training Course Completion", "Two-Wheel Experience"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-bajaj-16",
    make: "Bajaj",
    model: "Pulsar 220F",
    year: 2020,
    type: "adventure",
    engineSize: "250cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Custom Exhaust", "USB Charging", "Windshield"],
    rentalPricePerDay: 187,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-suzuki-17",
    make: "Suzuki",
    model: "GSX-R600",
    year: 2019,
    type: "cruiser",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Tire Pressure Monitoring System (TPMS)", "Riding Modes", "Backrest", "Performance Tires", "Bluetooth Audio"],
    rentalPricePerDay: 148,
    currency: "USD",
    available: false,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Security Deposit Required", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-ducati-18",
    make: "Ducati",
    model: "Multistrada 950",
    year: 2019,
    type: "dirt bike",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Traction Control"],
    rentalPricePerDay: 180,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Transit Hub",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Two-Wheel Experience"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-harley-davidson-19",
    make: "Harley-Davidson",
    model: "Road King",
    year: 2021,
    type: "standard",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Anti-lock Braking System (ABS)", "Windshield", "Comfort Seat"],
    rentalPricePerDay: 109,
    currency: "USD",
    available: false,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Proof of Residency", "Credit Card Required", "Local Riding Permit", "Security Deposit Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-moto-guzzi-20",
    make: "Moto Guzzi",
    model: "Norge",
    year: 2023,
    type: "standard",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: false,
    features: ["ABS", "Traction Control"],
    rentalPricePerDay: 102,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Airport",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Safety Gear Required", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-moto-guzzi-21",
    make: "Moto Guzzi",
    model: "California Touring 1400",
    year: 2023,
    type: "adventure",
    engineSize: "500cc",
    transmission: "manual",
    color: "Red",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Security System", "Helmet Included", "Windshield", "Anti-lock Braking System (ABS)", "Heated Grips"],
    rentalPricePerDay: 144,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "No DUI Record", "Signed Waiver", "Two-Wheel Experience"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-benelli-22",
    make: "Benelli",
    model: "TNT135",
    year: 2020,
    type: "custom",
    engineSize: "1400cc",
    transmission: "automatic",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["GPS Navigation", "Helmet Included", "Keyless Ignition"],
    rentalPricePerDay: 97,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-triumph-23",
    make: "Triumph",
    model: "Thruxton",
    year: 2019,
    type: "sport",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Blue",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 174,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Rider Training Course Completion", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-suzuki-24",
    make: "Suzuki",
    model: "GSX-R250",
    year: 2022,
    type: "cafe racer",
    engineSize: "250cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Helmet Included"],
    rentalPricePerDay: 74,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "University Area",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Insurance Required", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-benelli-25",
    make: "Benelli",
    model: "502C",
    year: 2021,
    type: "cruiser",
    engineSize: "650cc",
    transmission: "manual",
    color: "Blue",
    seatCapacity: 2,
    hasStorage: true,
    features: ["USB Charging", "Saddlebags"],
    rentalPricePerDay: 124,
    currency: "USD",
    available: false,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-royal-enfield-26",
    make: "Royal Enfield",
    model: "Bullet",
    year: 2020,
    type: "standard",
    engineSize: "500cc",
    transmission: "manual",
    color: "Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Saddlebags", "GPS Navigation", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 78,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Helmet Required", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-st-thomas-honda-27",
    make: "Honda",
    model: "Rebel",
    year: 2021,
    type: "standard",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Adjustable Suspension", "ABS"],
    rentalPricePerDay: 104,
    depositAmount: 208,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Car Rental Lot",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "No DUI Record"],
  },
  {
    id: "motorcycle-st-thomas-ducati-28",
    make: "Ducati",
    model: "Scrambler Desert Sled",
    year: 2023,
    type: "sport",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Custom Exhaust", "Tire Pressure Monitoring System (TPMS)"],
    rentalPricePerDay: 155,
    depositAmount: 465,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Residential Area",
    requirements: ["International Driving Permit (for foreign renters)", "Local Riding Permit", "Signed Waiver", "Valid Motorcycle License"],
  },
  {
    id: "motorcycle-st-thomas-honda-29",
    make: "Honda",
    model: "CBR500X",
    year: 2020,
    type: "sport",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Metallic Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Bluetooth Audio", "Riding Modes", "GPS Navigation"],
    rentalPricePerDay: 105,
    depositAmount: 210,
    currency: "USD",
    available: true,
    pickUpCity: "St Thomas",
    pickUpCountry: "U.S. Virgin Islands",
    pickUpLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Proof of Residency"],
  }
];
