// Auto-generated file for stockholm motorcycle rentals
// City: stockholm, Country: Sweden, Region: Sweden

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const stockholmswedenswedenMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-stockholm-kawasaki-1",
    make: "Kawasaki",
    model: "Ninja 1000",
    year: 2023,
    type: "scooter",
    engineSize: "650cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Helmet Included", "Tire Pressure Monitoring System (TPMS)", "Custom Exhaust"],
    rentalPricePerDay: 848,
    currency: "SEK",
    available: false,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required", "Safety Gear Required", "Helmet Required", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-can-am-2",
    make: "Can-Am",
    model: "Spyder RT Limited",
    year: 2019,
    type: "standard",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Security System", "Riding Modes"],
    rentalPricePerDay: 777,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-bajaj-3",
    make: "Bajaj",
    model: "V12",
    year: 2021,
    type: "standard",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Yellow",
    seatCapacity: 1,
    hasStorage: true,
    features: ["GPS Navigation", "Anti-lock Braking System (ABS)", "Bluetooth Audio", "Heated Grips", "Helmet Included"],
    rentalPricePerDay: 1596,
    currency: "SEK",
    available: false,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Safety Gear Required", "Helmet Required", "International Driving Permit (for foreign renters)", "Local Riding Permit", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-ducati-4",
    make: "Ducati",
    model: "Streetfighter V4",
    year: 2023,
    type: "cafe racer",
    engineSize: "500cc",
    transmission: "automatic",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Tire Pressure Monitoring System (TPMS)", "Bluetooth Audio", "Phone Mount"],
    rentalPricePerDay: 1456,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Emergency Contact Information", "No DUI Record", "Helmet Required", "Two-Wheel Experience"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-bmw-5",
    make: "BMW",
    model: "C400X",
    year: 2020,
    type: "scooter",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Heated Grips", "Cruise Control"],
    rentalPricePerDay: 768,
    currency: "SEK",
    available: false,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Minimum Age 21", "Two-Wheel Experience", "Rider Training Course Completion", "Valid Motorcycle License"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-yamaha-6",
    make: "Yamaha",
    model: "YZF-R3",
    year: 2022,
    type: "scooter",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Traction Control", "Helmet Included"],
    rentalPricePerDay: 901,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Local Motorcycle Club",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "International Driving Permit (for foreign renters)", "Signed Waiver", "Two-Wheel Experience", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-ktm-7",
    make: "KTM",
    model: "890 Adventure R Rally Pro S Special Edition",
    year: 2020,
    type: "scooter",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Saddlebags", "Backrest", "Helmet Included", "Cruise Control"],
    rentalPricePerDay: 1545,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Experience with Manual Transmission", "No DUI Record", "Rider Training Course Completion"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-gasgas-8",
    make: "GasGas",
    model: "MC 125",
    year: 2019,
    type: "sport",
    engineSize: "1000cc",
    transmission: "automatic",
    color: "Brown",
    seatCapacity: 2,
    hasStorage: true,
    features: ["USB Charging", "LED Headlights"],
    rentalPricePerDay: 1114,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-suzuki-9",
    make: "Suzuki",
    model: "SV650",
    year: 2020,
    type: "standard",
    engineSize: "750cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Traction Control", "Quick Shifter", "Helmet Included", "Riding Modes"],
    rentalPricePerDay: 640,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Car Rental Lot",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "International Driving Permit (for foreign renters)", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-ducati-10",
    make: "Ducati",
    model: "Streetfighter V4 SP2 S Lamborghini Speciale 2032",
    year: 2020,
    type: "dirt bike",
    engineSize: "900cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Phone Mount", "Cruise Control", "ABS", "Comfort Seat"],
    rentalPricePerDay: 1261,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Two-Wheel Experience", "Helmet Required", "No DUI Record"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-triumph-11",
    make: "Triumph",
    model: "Street Scrambler",
    year: 2019,
    type: "cafe racer",
    engineSize: "500cc",
    transmission: "manual",
    color: "Orange",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Windshield"],
    rentalPricePerDay: 1461,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "City Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Emergency Contact Information", "Local Riding Permit"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-kawasaki-12",
    make: "Kawasaki",
    model: "Z650",
    year: 2023,
    type: "touring",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Metallic Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Cruise Control", "Quick Shifter"],
    rentalPricePerDay: 941,
    currency: "SEK",
    available: false,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Downtown",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Minimum Age 21", "Credit Card Required"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-husqvarna-13",
    make: "Husqvarna",
    model: "FE 501s",
    year: 2022,
    type: "dirt bike",
    engineSize: "500cc",
    transmission: "manual",
    color: "Metallic Yellow",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Custom Exhaust", "Quick Shifter", "Tire Pressure Monitoring System (TPMS)", "Heated Grips"],
    rentalPricePerDay: 797,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Motorcycle Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Experience with Manual Transmission"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-bmw-14",
    make: "BMW",
    model: "C400GT",
    year: 2021,
    type: "standard",
    engineSize: "250cc",
    transmission: "automatic",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Saddlebags"],
    rentalPricePerDay: 922,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Convention Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Rider Training Course Completion", "Security Deposit Required", "Emergency Contact Information"],
    location: "",
  },
  {
    id: "motorcycle-stockholm-suzuki-15",
    make: "Suzuki",
    model: "GSX-R750",
    year: 2021,
    type: "dual-sport",
    engineSize: "750cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Keyless Ignition", "Helmet Included"],
    rentalPricePerDay: 1484,
    depositAmount: 2968,
    currency: "SEK",
    available: false,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Local Motorcycle Club",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Experience with Manual Transmission"],
  },
  {
    id: "motorcycle-stockholm-kawasaki-16",
    make: "Kawasaki",
    model: "KX85",
    year: 2023,
    type: "dual-sport",
    engineSize: "650cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Custom Exhaust"],
    rentalPricePerDay: 883,
    depositAmount: 1766,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Motorcycle Dealership",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Local Riding Permit", "Rider Training Course Completion"],
  },
  {
    id: "motorcycle-stockholm-bmw-17",
    make: "BMW",
    model: "C400GT",
    year: 2022,
    type: "cruiser",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Metallic Silver",
    seatCapacity: 2,
    hasStorage: false,
    features: ["GPS Navigation"],
    rentalPricePerDay: 600,
    depositAmount: 1800,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Convention Center",
    requirements: ["Proof of Residency", "Valid Motorcycle License"],
  },
  {
    id: "motorcycle-stockholm-yamaha-18",
    make: "Yamaha",
    model: "Tracer 9 GT",
    year: 2020,
    type: "cafe racer",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Performance Tires"],
    rentalPricePerDay: 908,
    depositAmount: 3632,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "University Area",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Safety Gear Required", "Minimum Age 21"],
  },
  {
    id: "motorcycle-stockholm-triumph-19",
    make: "Triumph",
    model: "Tiger 900 GT Low",
    year: 2022,
    type: "cruiser",
    engineSize: "500cc",
    transmission: "manual",
    color: "Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Heated Grips", "Comfort Seat"],
    rentalPricePerDay: 768,
    depositAmount: 1536,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Downtown",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Proof of Residency", "International Driving Permit (for foreign renters)", "Credit Card Required"],
  },
  {
    id: "motorcycle-stockholm-royal-enfield-20",
    make: "Royal Enfield",
    model: "Thunderbird X 650X Special Edition 2024",
    year: 2019,
    type: "touring",
    engineSize: "1200cc",
    transmission: "manual",
    color: "Gray",
    seatCapacity: 2,
    hasStorage: false,
    features: ["GPS Navigation", "Comfort Seat", "Riding Modes", "Custom Exhaust", "Performance Tires"],
    rentalPricePerDay: 1631,
    depositAmount: 6524,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Transit Hub",
    dropOffCity: "dublin",
    dropOffCountry: "Ireland",
    dropOffLocation: "City Center",
    requirements: ["Valid Motorcycle License", "Helmet Required", "Proof of Residency", "Rider Training Course Completion", "Local Riding Permit"],
  },
  {
    id: "motorcycle-stockholm-harley-davidson-21",
    make: "Harley-Davidson",
    model: "CVO Road Glide",
    year: 2019,
    type: "dual-sport",
    engineSize: "1000cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Adjustable Suspension", "Comfort Seat", "Performance Tires", "Saddlebags"],
    rentalPricePerDay: 1506,
    depositAmount: 4518,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Tourist District",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Credit Card Required", "Minimum Age 21"],
  },
  {
    id: "motorcycle-stockholm-triumph-22",
    make: "Triumph",
    model: "Speed Triple",
    year: 2023,
    type: "custom",
    engineSize: "750cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Bluetooth Audio", "GPS Navigation", "Anti-lock Braking System (ABS)"],
    rentalPricePerDay: 690,
    depositAmount: 2070,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "Airport",
    dropOffCity: "mekong-delta",
    dropOffCountry: "Vietnam",
    dropOffLocation: "Train Station",
    requirements: ["Valid Motorcycle License", "Rider Training Course Completion", "Security Deposit Required", "No DUI Record", "Signed Waiver", "Minimum Age 21"],
  },
  {
    id: "motorcycle-stockholm-cfmoto-23",
    make: "CFMoto",
    model: "700CL-X",
    year: 2022,
    type: "touring",
    engineSize: "750cc",
    transmission: "manual",
    color: "Silver",
    seatCapacity: 2,
    hasStorage: true,
    features: ["GPS Navigation", "Windshield", "Performance Tires"],
    rentalPricePerDay: 910,
    depositAmount: 2730,
    currency: "SEK",
    available: true,
    pickUpCity: "Stockholm",
    pickUpCountry: "Sweden",
    pickUpLocation: "City Center",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Emergency Contact Information"],
  }
];
