// Auto-generated file for toronto motorcycle rentals
// City: toronto, Country: Canada, Region: East Coast Canada

import { Motorcycle } from "@/lib/interfaces/services/rentals";

export const torontocanadaeastCoastCanadaMotorcycles: Motorcycle[] = [
  {
    id: "motorcycle-toronto-ktm-1",
    make: "KTM",
    model: "1290 Super Adventure",
    year: 2022,
    type: "adventure",
    engineSize: "1200cc",
    transmission: "automatic",
    color: "Black",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Helmet Included", "Security System", "GPS Navigation"],
    rentalPricePerDay: 180,
    currency: "CAD",
    available: true,
    pickUpCity: "Toronto",
    pickUpCountry: "Canada",
    pickUpLocation: "RV Park / Campground",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency", "Rider Training Course Completion", "Signed Waiver"],
    location: "",
  },
  {
    id: "motorcycle-toronto-benelli-2",
    make: "Benelli",
    model: "Leonardo 250",
    year: 2022,
    type: "cruiser",
    engineSize: "125cc",
    transmission: "manual",
    color: "Metallic Orange",
    seatCapacity: 1,
    hasStorage: false,
    features: ["Helmet Included", "Custom Exhaust"],
    rentalPricePerDay: 84,
    currency: "CAD",
    available: true,
    pickUpCity: "Toronto",
    pickUpCountry: "Canada",
    pickUpLocation: "Harley-Davidson Dealership",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "No DUI Record", "Security Deposit Required", "Emergency Contact Information", "Minimum Age 21"],
    location: "",
  },
  {
    id: "motorcycle-toronto-ducati-3",
    make: "Ducati",
    model: "Panigale V4",
    year: 2020,
    type: "touring",
    engineSize: "250cc",
    transmission: "manual",
    color: "Metallic Green",
    seatCapacity: 1,
    hasStorage: false,
    features: ["ABS"],
    rentalPricePerDay: 237,
    currency: "CAD",
    available: true,
    pickUpCity: "Toronto",
    pickUpCountry: "Canada",
    pickUpLocation: "Shopping Center",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Local Riding Permit", "Security Deposit Required", "Credit Card Required", "Helmet Required"],
    location: "",
  },
  {
    id: "motorcycle-toronto-suzuki-4",
    make: "Suzuki",
    model: "GSX-R600",
    year: 2023,
    type: "standard",
    engineSize: "500cc",
    transmission: "manual",
    color: "Matte Black",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Bluetooth Audio", "USB Charging"],
    rentalPricePerDay: 187,
    currency: "CAD",
    available: true,
    pickUpCity: "Toronto",
    pickUpCountry: "Canada",
    pickUpLocation: "Train Station",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Proof of Residency"],
    location: "",
  },
  {
    id: "motorcycle-toronto-cfmoto-5",
    make: "CFMoto",
    model: "650NK",
    year: 2023,
    type: "custom",
    engineSize: "250cc",
    transmission: "manual",
    color: "Black",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Performance Tires", "Heated Grips"],
    rentalPricePerDay: 176,
    currency: "CAD",
    available: true,
    pickUpCity: "Toronto",
    pickUpCountry: "Canada",
    pickUpLocation: "Tourist District",
    imageUrl: "",
    requirements: ["Valid Motorcycle License", "Insurance Required"],
    location: "",
  },
  {
    id: "motorcycle-toronto-harley-davidson-6",
    make: "Harley-Davidson",
    model: "Electra Glide",
    year: 2020,
    type: "custom",
    engineSize: "900cc",
    transmission: "manual",
    color: "Metallic Red",
    seatCapacity: 2,
    hasStorage: false,
    features: ["Windshield", "Saddlebags", "Cruise Control", "Riding Modes"],
    rentalPricePerDay: 222,
    depositAmount: 888,
    currency: "CAD",
    available: true,
    pickUpCity: "Toronto",
    pickUpCountry: "Canada",
    pickUpLocation: "City Center",
    requirements: ["Valid Motorcycle License", "Signed Waiver", "Emergency Contact Information", "Rider Training Course Completion", "Credit Card Required"],
  },
  {
    id: "motorcycle-toronto-ducati-7",
    make: "Ducati",
    model: "SuperSport 950",
    year: 2023,
    type: "scooter",
    engineSize: "500cc",
    transmission: "automatic",
    color: "Red",
    seatCapacity: 1,
    hasStorage: true,
    features: ["Security System", "Keyless Ignition"],
    rentalPricePerDay: 227,
    depositAmount: 454,
    currency: "CAD",
    available: false,
    pickUpCity: "Toronto",
    pickUpCountry: "Canada",
    pickUpLocation: "Airport",
    requirements: ["Helmet Required", "Local Riding Permit", "Valid Motorcycle License", "Security Deposit Required", "International Driving Permit (for foreign renters)"],
  },
  {
    id: "motorcycle-toronto-honda-8",
    make: "Honda",
    model: "CBR1000RR-R Fireblade",
    year: 2020,
    type: "custom",
    engineSize: "1400cc",
    transmission: "manual",
    color: "Metallic Brown",
    seatCapacity: 2,
    hasStorage: true,
    features: ["Security System", "Custom Exhaust", "Performance Tires", "Heated Grips"],
    rentalPricePerDay: 115,
    depositAmount: 460,
    currency: "CAD",
    available: false,
    pickUpCity: "Toronto",
    pickUpCountry: "Canada",
    pickUpLocation: "Shopping Center",
    requirements: ["Valid Motorcycle License", "Two-Wheel Experience", "Signed Waiver", "International Driving Permit (for foreign renters)"],
  }
];
