import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Ryokan Harmony
export const ryokanHarmonyRooms: RoomOption[] = [
  {
    id: "hotel-yokohama-9-room-8-Twin-None",
    name: "Deluxe Twin Loft",
    description: "Unwind in this wide-ranging twin loft with a pleasant outlook, featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 4065903,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-yokohama-9-room-8-Queen-GardenView",
    name: "Executive Queen Villa",
    description: "Experience our classic, prestigious queen villa with a view of the garden's natural beauty, with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 6104812,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-yokohama-9-room-8-King-OceanView",
    name: "Harmony King Studio",
    description: "Enjoy a luxurious stay in our Harmony-themed king studio, offering where the ocean meets the sky, with blackout curtains for a perfect night's sleep, and unique touches of offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 8046500,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-yokohama-9-room-8-Single-GardenView",
    name: "Bamboo Single Loft",
    description: "Enjoy a commodious stay in our Bamboo-themed single loft, offering with a view of blooming flowers and greenery, with a modern en-suite bathroom, and unique touches of featuring traditional tatami elements.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 4557686,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-yokohama-9-room-8-SofaBed-None",
    name: "Luxury Sofa Bed Suite",
    description: "A soothing sofa bed retreat with a pleasant outlook, combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 4443422,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-yokohama-9-room-8-Twin-OceanView",
    name: "Standard Twin Penthouse",
    description: "Indulge in the deluxe atmosphere of our twin penthouse, with spectacular where you can feel the ocean breeze, combining modern luxury with Japanese tradition, and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 4933067,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-yokohama-9-room-8-Double-CityView",
    name: "Luxury Double Room",
    description: "Luxury-themed double room overlooking the vibrant cityscape, featuring traditional tatami elements and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 4981113,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-yokohama-9-room-8-Double-GardenView",
    name: "Premium Double Villa",
    description: "This chic double accommodation offers where you can enjoy the garden's seasonal blooms, offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 5193125,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  }
];
