import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Yamaguchi Coastal Hotel
export const yamaguchiCoastalHotelRooms: RoomOption[] = [
  {
    id: "hotel-yokohama-10-room-9-Double-CityView",
    name: "Standard Double Room",
    description: "Indulge in the refreshing atmosphere of our double room, with spectacular offering panoramic city vistas, featuring traditional tatami elements, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 2656775,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-yokohama-10-room-9-Single-CityView",
    name: "Executive Single Apartment",
    description: "Enjoy a calming stay in our Executive-themed single apartment, offering where you can watch the city wake up, including climate control for your comfort, and unique touches of featuring traditional tatami elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 2073290,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-yokohama-10-room-9-Twin-MountainView",
    name: "Imperial Twin Suite",
    description: "This stylish twin accommodation offers with majestic mountain vistas, with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 2673399,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-yokohama-10-room-9-Double-OceanView",
    name: "Imperial Double Villa",
    description: "Experience our comfy, majestic double villa where you can hear the soothing sound of the sea, with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 3007771,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-yokohama-10-room-9-King-MountainView",
    name: "Classic King Studio",
    description: "This refreshing king accommodation offers where you can enjoy the tranquility of the mountains, with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 4277705,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-yokohama-10-room-9-Queen-GardenView",
    name: "Luxury Queen Villa",
    description: "Indulge in the commodious atmosphere of our queen villa, with spectacular where you can enjoy the garden's seasonal blooms, featuring traditional tatami elements, and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 3263830,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-yokohama-10-room-9-Double-None",
    name: "Standard Double Studio",
    description: "Experience our sumptuous, comfortable double studio with a pleasant outlook, with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 2355457,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-yokohama-10-room-9-Single-OceanView",
    name: "Sakura Single Suite",
    description: "A tranquil single suite designed for soothing comfort, with with a panoramic view of the coastline and with plush bedding for ultimate comfort, reflecting featuring traditional tatami elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 2351923,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-yokohama-10-room-9-Double-MountainView",
    name: "Lotus Double Studio",
    description: "Lotus-themed double studio with panoramic views of the mountain landscape, offering the perfect balance of Eastern serenity and Western comfort and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 2964010,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
