import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Heritage Inn
export const theHeritageInnRooms: RoomOption[] = [
  {
    id: "hotel-vienna-7-room-6-Single-GardenView",
    name: "Luxury Single Villa",
    description: "Enjoy a homey stay in our Luxury-themed single villa, offering offering a peaceful garden outlook, with a luxurious soaking tub, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 179,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-vienna-7-room-6-SofaBed-None",
    name: "Deluxe Sofa Bed Studio",
    description: "Unwind in this open-concept sofa bed studio with a pleasant outlook, with high-speed internet access.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 183,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-vienna-7-room-6-Single-OceanView",
    name: "Executive Single Room",
    description: "Step into a minimalist single room that combines Executive-themed with breathtaking where you can enjoy the ocean's beauty, complemented by with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 230,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-vienna-7-room-6-Double-None",
    name: "Luxury Double Suite",
    description: "A refined double suite designed for plush comfort, with with a pleasant outlook and complete with a well-appointed bathroom, reflecting decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 216,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-vienna-7-room-6-Single-MountainView",
    name: "Tranquility Single Studio",
    description: "This stretching single studio promises with majestic mountain vistas, enriched by Tranquility-themed details and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 200,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-vienna-7-room-6-Twin-None",
    name: "Horizon Twin Apartment",
    description: "Relax in our pleasant gentle twin apartment featuring with a pleasant outlook, along with with high-speed internet access and designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 186,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-vienna-7-room-6-SofaBed-GardenView",
    name: "Luxury Sofa Bed Penthouse",
    description: "A traditional sofa bed retreat with a view of shaded garden paths, designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 232,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-vienna-7-room-6-Single-None",
    name: "Luxury Single Suite",
    description: "Indulge in the comfortable atmosphere of our single suite, with spectacular with a pleasant outlook, created with both style and function in mind, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Hearing Support", "Wheelchair Accessible", "Elevator"],
    pricePerNight: 166,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-vienna-7-room-6-SofaBed-MountainView",
    name: "Premium Sofa Bed Suite",
    description: "Indulge in the avant-garde atmosphere of our sofa bed suite, with spectacular with a view of snow-capped peaks, featuring thoughtful design elements, and with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 216,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  }
];
