import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Oceanview Inn
export const oceanviewInnRooms: RoomOption[] = [
  {
    id: "hotel-san-juan-9-room-8-SofaBed-None",
    name: "Modern Sofa Bed Studio",
    description: "Modern-themed studio with expansive decor, with a pleasant outlook, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 204,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-san-juan-9-room-8-King-MountainView",
    name: "Classic King Villa",
    description: "Experience our palatial, homey king villa with a view of the rugged mountain landscape, featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 438,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-san-juan-9-room-8-SofaBed-MountainView",
    name: "Premium Sofa Bed Studio",
    description: "Our Premium-themed sofa bed studio offers roomy luxury, panoramic with a view of the mountains' changing seasons, and with blackout curtains for a perfect night's sleep, inspired by decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 257,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-san-juan-9-room-8-Single-MountainView",
    name: "Luxury Single Room",
    description: "Our Luxury-themed single room offers ample luxury, panoramic where you can escape to the mountains, and with a spacious work area, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 259,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-san-juan-9-room-8-Double-CityView",
    name: "Superior Double Penthouse",
    description: "Discover the charm of this Superior-themed double penthouse, complete with pleasant ambiance, stunning where you can enjoy the city's energy, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 255,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-san-juan-9-room-8-Queen-None",
    name: "Classic Queen Penthouse",
    description: "This palatial queen accommodation offers with a pleasant outlook, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids", "Accessible Bathroom"],
    pricePerNight: 311,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-san-juan-9-room-8-Twin-OceanView",
    name: "Premium Twin Loft",
    description: "Enjoy a airy stay in our Premium-themed twin loft, offering where you can hear the soothing sound of the sea, with carefully selected furnishings, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 308,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-san-juan-9-room-8-Double-OceanView",
    name: "Signature Double Loft",
    description: "Signature-themed loft with lavish decor, where you can feel the ocean breeze, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 293,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-san-juan-9-room-8-King-None",
    name: "Deluxe King Villa",
    description: "Unwind in this avant-garde king villa with a pleasant outlook, including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 366,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  }
];
