import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Harbor House
export const theHarborHouseRooms: RoomOption[] = [
  {
    id: "hotel-rome-7-room-6-King-OceanView",
    name: "Modern King Villa",
    description: "A broad king retreat with the sound of the ocean as your backdrop, with classic Italian elegance.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 337,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-rome-7-room-6-SofaBed-MountainView",
    name: "Luxury Sofa Bed Room",
    description: "Our Luxury-themed sofa bed room offers comfy luxury, panoramic where the mountains touch the sky, and with a spacious work area, inspired by with classic Italian elegance.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 204,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-rome-7-room-6-Single-CityView",
    name: "Horizon Single Studio",
    description: "Experience our welcoming, plush single studio with a backdrop of city parks and green spaces, with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 179,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-rome-7-room-6-King-GardenView",
    name: "Executive King Suite",
    description: "This compact king accommodation offers where you can relax in a garden haven, with classic Italian elegance.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 300,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-rome-7-room-6-Queen-OceanView",
    name: "Standard Queen Studio",
    description: "A sleek queen retreat with a view of the ocean's horizon, offering a touch of la dolce vita.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 275,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-rome-7-room-6-Single-MountainView",
    name: "Premium Single Room",
    description: "This sophisticated single room promises with a view of the mountains' lush valleys, enriched by Premium-themed details and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 172,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-rome-7-room-6-Twin-CityView",
    name: "Harmony Twin Room",
    description: "Enjoy a grandiose stay in our Harmony-themed twin room, offering with a view of the city's waterfront, with blackout curtains for a perfect night's sleep, and unique touches of offering a touch of la dolce vita.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 175,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-rome-7-room-6-SofaBed-None",
    name: "Harmony Sofa Bed Loft",
    description: "Harmony-themed loft with stylish decor, with a pleasant outlook, and with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 169,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-rome-7-room-6-Twin-GardenView",
    name: "Classic Twin Suite",
    description: "Step into a inviting twin suite that combines Classic-themed with breathtaking where you can enjoy the garden's peaceful atmosphere, complemented by with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 189,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  }
];
