import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Villa d’Oro
export const villaDoroRooms: RoomOption[] = [
  {
    id: "hotel-rome-9-room-8-Double-None",
    name: "Serenity Double Suite",
    description: "Unwind in this fashionable double suite with a pleasant outlook, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 114,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-rome-9-room-8-Queen-CityView",
    name: "Serenity Queen Loft",
    description: "Relax in our calming stretching queen loft featuring with a window to the bustling city below, along with with a modern en-suite bathroom and featuring tasteful Mediterranean touches.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 131,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-rome-9-room-8-Double-MountainView",
    name: "Harmony Double Villa",
    description: "Step into a regal double villa that combines Harmony-themed with breathtaking with a view of the mountains' changing seasons, complemented by with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 139,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-rome-9-room-8-SofaBed-None",
    name: "Modern Sofa Bed Room",
    description: "Experience our chic, compact sofa bed room with a pleasant outlook, with high-speed internet access.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 95,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-rome-9-room-8-King-MountainView",
    name: "Standard King Penthouse",
    description: "Standard-themed penthouse with tranquil decor, where you can gaze at the towering peaks, and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 178,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-rome-9-room-8-SofaBed-GardenView",
    name: "Superior Sofa Bed Villa",
    description: "This comfortable sofa bed villa promises with a view of colorful flower beds, enriched by Superior-themed details and with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 100,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-rome-9-room-8-Queen-OceanView",
    name: "Tranquility Queen Villa",
    description: "A exquisite queen villa designed for serene comfort, with where you can relax to the sound of the waves and with a luxurious soaking tub, reflecting featuring tasteful Mediterranean touches.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 156,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-rome-9-room-8-Single-MountainView",
    name: "Superior Single Loft",
    description: "Our intimate Superior-themed loft offers where you can take in the fresh mountain air, spacious comfort, and with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 95,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-rome-9-room-8-Queen-None",
    name: "Modern Queen Villa",
    description: "Step into a sizable queen villa that combines Modern-themed with breathtaking with a pleasant outlook, complemented by featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Elevator", "Hearing Support", "Wheelchair Accessible"],
    pricePerNight: 113,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-rome-9-room-8-Queen-GardenView",
    name: "Deluxe Queen Room",
    description: "Indulge in the regal atmosphere of our queen room, with spectacular where you can enjoy the serenity of a garden retreat, inspired by Italian Renaissance design, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 153,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  }
];
