import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Blue Sky Lodge
export const blueSkyLodgeRooms: RoomOption[] = [
  {
    id: "hotel-galveston-7-room-6-King-MountainView",
    name: "Deluxe King Villa",
    description: "This comfortable king accommodation offers where you can gaze at the towering peaks, highlighting contemporary American style.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 334,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-galveston-7-room-6-SofaBed-MountainView",
    name: "Golden Gate Sofa Bed Loft",
    description: "A ornate sofa bed retreat where you can enjoy the tranquility of the mountains, offering a classic yet modern American experience.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 239,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-galveston-7-room-6-Queen-CityView",
    name: "Manhattan Queen Apartment",
    description: "Discover the charm of this Manhattan-themed queen apartment, complete with roomy ambiance, stunning overlooking the vibrant cityscape, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 279,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-galveston-7-room-6-Double-OceanView",
    name: "Heritage Double Penthouse",
    description: "Our Heritage-themed double penthouse offers luxurious luxury, panoramic where you can relax to the sound of the waves, and with high-speed internet access, inspired by featuring sleek urban design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Wheelchair Accessible", "Accessible Bathroom"],
    pricePerNight: 271,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-galveston-7-room-6-Queen-GardenView",
    name: "Executive Queen Studio",
    description: "Enjoy a room-filled stay in our Executive-themed queen studio, offering where you can enjoy the beauty of nature, offering a unique blend of style and comfort, and unique touches of offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids", "Hearing Support", "Accessible Bathroom"],
    pricePerNight: 254,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-galveston-7-room-6-Double-None",
    name: "Liberty Double Loft",
    description: "Relax in our stylish industrial double loft featuring with a pleasant outlook, along with complete with a well-appointed bathroom and offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 187,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-galveston-7-room-6-King-CityView",
    name: "Superior King Loft",
    description: "Our Superior-themed king loft offers inviting luxury, panoramic where the city skyline meets the horizon, and with a luxurious soaking tub, inspired by with rustic and modern influences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 310,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-galveston-7-room-6-Twin-CityView",
    name: "Colonial Twin Room",
    description: "Step into a luxurious twin room that combines Colonial-themed with breathtaking overlooking the vibrant cityscape, complemented by with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 208,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-galveston-7-room-6-SofaBed-None",
    name: "Pioneer Sofa Bed Loft",
    description: "Our Pioneer-themed sofa bed loft offers ornate luxury, panoramic with a pleasant outlook, and with high-speed internet access, inspired by offering a classic yet modern American experience.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 176,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-galveston-7-room-6-SofaBed-CityView",
    name: "Deluxe Sofa Bed Penthouse",
    description: "Unwind in this minimalist sofa bed penthouse with stunning views of the city skyline, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 179,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  }
];
