import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Oakwood Resort
export const oakwoodResortRooms: RoomOption[] = [
  {
    id: "hotel-galveston-3-room-2-King-CityView",
    name: "Manhattan King Penthouse",
    description: "Step into a intimate king penthouse that combines Manhattan-themed with breathtaking where the city skyline meets the horizon, complemented by equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids"],
    pricePerNight: 282,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-galveston-3-room-2-Twin-OceanView",
    name: "Signature Twin Studio",
    description: "A plush twin studio designed for elegant comfort, with where the ocean meets the sky and with a luxurious soaking tub, reflecting offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 211,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-galveston-3-room-2-SofaBed-OceanView",
    name: "Deluxe Sofa Bed Loft",
    description: "Enjoy a homey stay in our Deluxe-themed sofa bed loft, offering with breathtaking sea views, with plush bedding for ultimate comfort, and unique touches of featuring sleek urban design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 236,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-galveston-3-room-2-SofaBed-None",
    name: "Heritage Sofa Bed Loft",
    description: "This extensive sofa bed loft promises with a pleasant outlook, enriched by Heritage-themed details and with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids", "Wheelchair Accessible"],
    pricePerNight: 191,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-galveston-3-room-2-King-GardenView",
    name: "Luxury King Apartment",
    description: "This generous king apartment promises with a view of the garden's peaceful ambiance, enriched by Luxury-themed details and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 290,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-galveston-3-room-2-Double-GardenView",
    name: "Heritage Double Penthouse",
    description: "This plush double penthouse promises offering a peaceful garden outlook, enriched by Heritage-themed details and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 228,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-galveston-3-room-2-King-MountainView",
    name: "Signature King Apartment",
    description: "This tasteful king accommodation offers with a view of the mountains' natural beauty, with rustic and modern influences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 337,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  }
];
