import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Cozy Cove
export const theCozyCoveRooms: RoomOption[] = [
  {
    id: "hotel-galveston-12-room-11-Twin-CityView",
    name: "Signature Twin Loft",
    description: "Signature-themed twin loft where the city comes alive at dusk, with rustic and modern influences and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Elevator", "Visual Aids"],
    pricePerNight: 129,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-galveston-12-room-11-Queen-MountainView",
    name: "Golden Gate Queen Penthouse",
    description: "Indulge in the soft atmosphere of our queen penthouse, with spectacular where the mountains touch the sky, highlighting contemporary American style, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 177,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-galveston-12-room-11-King-CityView",
    name: "Deluxe King Penthouse",
    description: "Our prestigious Deluxe-themed penthouse offers with a backdrop of city parks and green spaces, soft comfort, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 170,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-galveston-12-room-11-Queen-CityView",
    name: "Deluxe Queen Apartment",
    description: "This commodious queen apartment promises where you can enjoy the city's energy, enriched by Deluxe-themed details and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 156,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-galveston-12-room-11-SofaBed-None",
    name: "Colonial Sofa Bed Room",
    description: "Unwind in this well-proportioned sofa bed room with a pleasant outlook, featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 108,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-galveston-12-room-11-Single-OceanView",
    name: "Liberty Single Loft",
    description: "Liberty-themed loft with heartwarming decor, overlooking the sparkling ocean waves, and with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 131,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-galveston-12-room-11-King-OceanView",
    name: "Liberty King Room",
    description: "This airy king room promises where the horizon meets the ocean, enriched by Liberty-themed details and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 215,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-galveston-12-room-11-SofaBed-GardenView",
    name: "Manhattan Sofa Bed Penthouse",
    description: "Indulge in the intimate atmosphere of our sofa bed penthouse, with spectacular with a view of shaded garden paths, offering a classic yet modern American experience, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 131,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-galveston-12-room-11-Twin-OceanView",
    name: "Luxury Twin Loft",
    description: "Luxury-themed loft with comfortable decor, with a view of the tranquil sea, and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 138,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
