import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Brandon Wheat City Hotel
export const brandonWheatCityHotelRooms: RoomOption[] = [
  {
    id: "hotel-vancouver-7-room-6-Queen-OceanView",
    name: "Luxury Queen Penthouse",
    description: "This opulent queen penthouse promises where you can feel the ocean breeze, enriched by Luxury-themed details and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 623,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-vancouver-7-room-6-King-None",
    name: "Standard King Loft",
    description: "Our Standard-themed king loft offers soothing luxury, panoramic with a pleasant outlook, and equipped with all the modern conveniences, inspired by inspired by the rugged beauty of Canadian landscapes.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 491,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-vancouver-7-room-6-Twin-MountainView",
    name: "Northern Lights Twin Apartment",
    description: "This prestigious twin accommodation offers with a view of the rugged mountain landscape, with cozy, nature-inspired themes.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 441,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-vancouver-7-room-6-SofaBed-GardenView",
    name: "Northern Lights Sofa Bed Apartment",
    description: "Experience our soothing, sizable sofa bed apartment where nature is just outside your window, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 374,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-vancouver-7-room-6-Double-MountainView",
    name: "Deluxe Double Studio",
    description: "Our Deluxe-themed double studio offers contemporary luxury, panoramic where you can enjoy the serenity of mountain life, and featuring a curated minibar selection, inspired by with cozy, nature-inspired themes.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids", "Accessible Bathroom"],
    pricePerNight: 494,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-vancouver-7-room-6-Double-OceanView",
    name: "Northern Lights Double Suite",
    description: "Indulge in the sizable atmosphere of our double suite, with spectacular where the horizon meets the ocean, blending urban sophistication with wilderness charm, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 436,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-vancouver-7-room-6-SofaBed-None",
    name: "Classic Sofa Bed Villa",
    description: "Indulge in the stylish atmosphere of our sofa bed villa, with spectacular with a pleasant outlook, with cozy, nature-inspired themes, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 304,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  }
];
