import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Mystic Meadow
export const theMysticMeadowRooms: RoomOption[] = [
  {
    id: "hotel-maui-7-room-6-Twin-None",
    name: "Manhattan Twin Loft",
    description: "Manhattan-themed loft with sumptuous decor, with a pleasant outlook, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 99,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-maui-7-room-6-SofaBed-GardenView",
    name: "Superior Sofa Bed Studio",
    description: "Discover the charm of this Superior-themed sofa bed studio, complete with extensive ambiance, stunning with a view of tranquil water features, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 109,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-maui-7-room-6-Double-GardenView",
    name: "Golden Gate Double Penthouse",
    description: "Enjoy a upscale stay in our Golden Gate-themed double penthouse, offering where you can unwind in a garden paradise, with a private balcony or terrace, and unique touches of highlighting contemporary American style.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 117,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-maui-7-room-6-Single-GardenView",
    name: "Luxury Single Villa",
    description: "Indulge in the gentle atmosphere of our single villa, with spectacular with a view of the garden's peaceful ambiance, offering a classic yet modern American experience, and featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 83,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-maui-7-room-6-King-OceanView",
    name: "Superior King Loft",
    description: "A vintage king loft designed for deluxe comfort, with with a private balcony overlooking the sea and complete with a well-appointed bathroom, reflecting featuring sleek urban design elements.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 166,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-maui-7-room-6-SofaBed-MountainView",
    name: "Superior Sofa Bed Apartment",
    description: "This artistic sofa bed accommodation offers where you can find inspiration in the mountains, offering a classic yet modern American experience.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 112,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-maui-7-room-6-Queen-CityView",
    name: "Golden Gate Queen Penthouse",
    description: "Unwind in this expansive queen penthouse where you can enjoy the city's energy, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 143,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-maui-7-room-6-Single-MountainView",
    name: "Golden Gate Single Apartment",
    description: "Indulge in the grandiose atmosphere of our single apartment, with spectacular with a view of the mountains' breathtaking sunsets, featuring sleek urban design elements, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 94,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-maui-7-room-6-Double-MountainView",
    name: "Standard Double Loft",
    description: "This modern double loft promises where you can experience the beauty of nature, enriched by Standard-themed details and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 122,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
