import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Metroline Hotel
export const metrolineHotelRooms: RoomOption[] = [
  {
    id: "hotel-belgrade-1-room-0-SofaBed-CityView",
    name: "Luxury Sofa Bed Suite",
    description: "Unwind in this welcoming sofa bed suite where you can watch the city wake up, with a spacious seating area.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 2345250,
    currency: "RSD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-belgrade-1-room-0-Double-None",
    name: "Modern Double Villa",
    description: "Our Modern-themed double villa offers tranquil luxury, panoramic with a pleasant outlook, and with a spacious work area, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 2118277,
    currency: "RSD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-belgrade-1-room-0-Single-OceanView",
    name: "Classic Single Loft",
    description: "A artistic single loft designed for minimalist comfort, with where the ocean meets the sky and equipped with all the modern conveniences, reflecting created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 2369740,
    currency: "RSD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-belgrade-1-room-0-Single-GardenView",
    name: "Signature Single Penthouse",
    description: "A extensive single retreat where you can find solace in nature's embrace, created with both style and function in mind.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 2204372,
    currency: "RSD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  }
];
