import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Coastal Inn
export const theCoastalInnRooms: RoomOption[] = [
  {
    id: "hotel-belgrade-9-room-8-Twin-OceanView",
    name: "Horizon Twin Loft",
    description: "This room-filled twin loft promises with a view of the tranquil sea, enriched by Horizon-themed details and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 1525130,
    currency: "RSD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-belgrade-9-room-8-Queen-None",
    name: "Tranquility Queen Room",
    description: "Experience our lavish, soft queen room with a pleasant outlook, with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids"],
    pricePerNight: 1511485,
    currency: "RSD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-belgrade-9-room-8-SofaBed-GardenView",
    name: "Harmony Sofa Bed Villa",
    description: "Enjoy a elegant stay in our Harmony-themed sofa bed villa, offering featuring a peaceful garden setting, featuring premium bath amenities, and unique touches of featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids"],
    pricePerNight: 1537150,
    currency: "RSD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-belgrade-9-room-8-Single-OceanView",
    name: "Classic Single Loft",
    description: "Unwind in this vintage single loft featuring uninterrupted ocean vistas, with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 1308646,
    currency: "RSD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  }
];
