import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Sunset Lodge
export const sunsetLodgeRooms: RoomOption[] = [
  {
    id: "hotel-glacier-bay-2-room-1",
    name: "Serenity Single Suite",
    description:
      "Our Serenity-themed single suite offers indulgent luxury, panoramic with a view of the city's cultural landmarks, and including climate control for your comfort, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Wake-Up Service",
      "Flat-Screen TV",
      "Board Games",
      "Fireplace",
      "Kitchenette",
    ],
    pricePerNight: 172,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-glacier-bay-2-room-1",
    name: "Horizon Twin Room",
    description:
      "Horizon-themed room with vintage decor, where you can enjoy the serenity of a garden retreat, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Kitchenette",
      "Mini Bar",
      "Bluetooth Speaker",
      "Jacuzzi Tub",
    ],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator"],
    pricePerNight: 223,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-glacier-bay-2-room-1",
    name: "Serenity Twin Apartment",
    description:
      "Step into a upscale twin apartment that combines Serenity-themed with breathtaking where you can take in the fresh mountain air, complemented by featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Seating Area",
      "Flat-Screen TV",
      "Mini Bar",
      "Accessible Room",
      "Refrigerator",
    ],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 247,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
];
