import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Great Wall Lodge
export const greatWallLodgeRooms: RoomOption[] = [
  {
    id: "hotel-shanghai-8-room-7-Twin-OceanView",
    name: "Premium Twin Studio",
    description: "Indulge in the intimate atmosphere of our twin studio, with spectacular with a view of the tranquil sea, offering a refined and harmonious ambiance, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 13213,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-shanghai-8-room-7-Queen-MountainView",
    name: "Silk Queen Villa",
    description: "Relax in our generous welcoming queen villa featuring with panoramic views of the mountain landscape, along with offering a unique blend of style and comfort and with classic Chinese artistic influences.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 16562,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-shanghai-8-room-7-King-GardenView",
    name: "Dragon King Penthouse",
    description: "Dragon-themed penthouse with artistic decor, where you can escape to a green sanctuary, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 15928,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-shanghai-8-room-7-Queen-CityView",
    name: "Deluxe Queen Studio",
    description: "Indulge in the exquisite atmosphere of our queen studio, with spectacular showcasing the urban landscape, featuring elegant calligraphy and silk accents, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 12426,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  }
];
