import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Zhengzhou Shaolin Temple Hotel
export const zhengzhouShaolinTempleHotelRooms: RoomOption[] = [
  {
    id: "hotel-shanghai-5-room-4-Twin-None",
    name: "Standard Twin Apartment",
    description: "Indulge in the exquisite atmosphere of our twin apartment, with spectacular with a pleasant outlook, offering a refined and harmonious ambiance, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 4547,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-shanghai-5-room-4-Queen-OceanView",
    name: "Luxury Queen Studio",
    description: "Our Luxury-themed queen studio offers pleasant luxury, panoramic where you can feel the ocean breeze, and with plush bedding for ultimate comfort, inspired by featuring elegant calligraphy and silk accents.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 8082,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-shanghai-5-room-4-Queen-GardenView",
    name: "Superior Queen Suite",
    description: "Discover the charm of this Superior-themed queen suite, complete with airy ambiance, stunning where you can unwind in a garden paradise, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    accessibilityFeatures: ["Hearing Support", "Accessible Bathroom"],
    pricePerNight: 7073,
    currency: "CNY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-shanghai-5-room-4-Double-OceanView",
    name: "Deluxe Double Apartment",
    description: "This industrial double apartment promises with a view of the endless blue, enriched by Deluxe-themed details and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids", "Elevator"],
    pricePerNight: 6809,
    currency: "CNY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-shanghai-5-room-4-King-OceanView",
    name: "Luxury King Studio",
    description: "Discover the charm of this Luxury-themed king studio, complete with homey ambiance, stunning with a private balcony overlooking the sea, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 9124,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-shanghai-5-room-4-Double-None",
    name: "Classic Double Penthouse",
    description: "Classic-themed double penthouse with a pleasant outlook, offering a refined and harmonious ambiance and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 4577,
    currency: "CNY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  }
];
