import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Villa Fontana Retreat
export const villaFontanaRetreatRooms: RoomOption[] = [
  {
    id: "hotel-malta-4-room-3-Queen-OceanView",
    name: "Superior Queen Room",
    description: "Indulge in the cozy atmosphere of our queen room, with spectacular with a view of the ocean's changing tides, offering a unique island experience with a touch of luxury, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 186,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-malta-4-room-3-Single-CityView",
    name: "Valletta Single Room",
    description: "This comfortable single accommodation offers overlooking the vibrant cityscape, offering a unique island experience with a touch of luxury.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 102,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-malta-4-room-3-SofaBed-None",
    name: "Azure Window Sofa Bed Studio",
    description: "Indulge in the traditional atmosphere of our sofa bed studio, with spectacular with a pleasant outlook, with a blend of historic charm and modern amenities, and with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 100,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-malta-4-room-3-Double-OceanView",
    name: "Classic Double Suite",
    description: "A peaceful double retreat where you can enjoy stunning sunsets over the water, blending traditional Maltese style with contemporary design.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 169,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-malta-4-room-3-King-OceanView",
    name: "Luzzu King Penthouse",
    description: "Discover the charm of this Luzzu-themed king penthouse, complete with pleasant ambiance, stunning with breathtaking sea views, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids", "Hearing Support", "Wheelchair Accessible"],
    pricePerNight: 218,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-malta-4-room-3-Twin-OceanView",
    name: "Superior Twin Apartment",
    description: "Unwind in this comfy twin apartment with a private balcony overlooking the sea, featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 130,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-malta-4-room-3-Queen-None",
    name: "Mdina Queen Apartment",
    description: "Our exquisite Mdina-themed apartment offers with a pleasant outlook, upscale comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 141,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-malta-4-room-3-SofaBed-CityView",
    name: "Premium Sofa Bed Loft",
    description: "Our Premium-themed sofa bed loft offers room-filled luxury, panoramic where you can watch the city wake up, and equipped with all the modern conveniences, inspired by with a blend of historic charm and modern amenities.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 129,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-malta-4-room-3-Queen-MountainView",
    name: "Maltese Lace Queen Room",
    description: "Maltese Lace-themed room with regal decor, where you can enjoy the serenity of mountain life, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 183,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
