import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Tierra del Fuego Lodge
export const theTierraDelFuegoLodgeRooms: RoomOption[] = [
  {
    id: "hotel-buenos-aires-8-room-7-Single-CityView",
    name: "Serenity Single Apartment",
    description: "Experience our intimate, broad single apartment with a view of the city's waterfront, with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 23872,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-buenos-aires-8-room-7-Queen-OceanView",
    name: "Premium Queen Villa",
    description: "Premium-themed villa with majestic decor, with breathtaking sea views, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 45160,
    currency: "ARS",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-buenos-aires-8-room-7-Twin-OceanView",
    name: "Signature Twin Loft",
    description: "Our restful Signature-themed loft offers where you can feel the ocean breeze, comfortable comfort, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 34193,
    currency: "ARS",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-buenos-aires-8-room-7-Twin-GardenView",
    name: "Standard Twin Villa",
    description: "Our Standard-themed twin villa offers vast luxury, panoramic overlooking lush garden landscapes, and featuring premium bath amenities, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 26909,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-buenos-aires-8-room-7-Double-OceanView",
    name: "Executive Double Suite",
    description: "Executive-themed double suite overlooking the sparkling ocean waves, featuring thoughtful design elements and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 38141,
    currency: "ARS",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-buenos-aires-8-room-7-King-CityView",
    name: "Executive King Loft",
    description: "A tasteful king loft designed for intimate comfort, with offering panoramic city vistas and offering a unique blend of style and comfort, reflecting created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 43888,
    currency: "ARS",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  }
];
