import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Hiroshima Atomic Dome Hotel
export const hiroshimaAtomicDomeHotelRooms: RoomOption[] = [
  {
    id: "hotel-hokkaido-5-room-4-Twin-OceanView",
    name: "Luxury Twin Apartment",
    description: "Indulge in the opulent atmosphere of our twin apartment, with spectacular with breathtaking sea views, featuring traditional tatami elements, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 3163099,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-hokkaido-5-room-4-Double-CityView",
    name: "Luxury Double Apartment",
    description: "Discover the charm of this Luxury-themed double apartment, complete with sophisticated ambiance, stunning with a view of iconic landmarks, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 3128640,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-hokkaido-5-room-4-Single-GardenView",
    name: "Harmony Single Penthouse",
    description: "Indulge in the futuristic atmosphere of our single penthouse, with spectacular with a view of the garden's seasonal changes, combining modern luxury with Japanese tradition, and featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 2635893,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-hokkaido-5-room-4-Queen-OceanView",
    name: "Harmony Queen Apartment",
    description: "Enjoy a traditional stay in our Harmony-themed queen apartment, offering where the ocean meets the sky, with a luxurious soaking tub, and unique touches of offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 4496623,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-hokkaido-5-room-4-Twin-GardenView",
    name: "Lotus Twin Studio",
    description: "Indulge in the plush atmosphere of our twin studio, with spectacular where you can enjoy the garden's peaceful atmosphere, with minimalist Japanese aesthetics, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 2633180,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-hokkaido-5-room-4-Double-GardenView",
    name: "Bamboo Double Room",
    description: "Discover the charm of this Bamboo-themed double room, complete with large-scale ambiance, stunning with a view of manicured lawns and gardens, and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 3138920,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  }
];
