import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Sapporo Snow Suites
export const sapporoSnowSuitesRooms: RoomOption[] = [
  {
    id: "hotel-hokkaido-11-room-10-Queen-None",
    name: "Executive Queen Room",
    description: "A stylish queen room designed for calming comfort, with with a pleasant outlook and with a spacious seating area, reflecting with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 2962594,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-hokkaido-11-room-10-Queen-CityView",
    name: "Bamboo Queen Apartment",
    description: "Relax in our calming retro queen apartment featuring with a view of iconic landmarks, along with with a spacious work area and with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 2737031,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-hokkaido-11-room-10-Single-GardenView",
    name: "Standard Single Room",
    description: "Standard-themed single room where you can enjoy the garden's peaceful atmosphere, combining modern luxury with Japanese tradition and with high-speed internet access.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 2004094,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-hokkaido-11-room-10-King-None",
    name: "Executive King Apartment",
    description: "Indulge in the roomy atmosphere of our king apartment, with spectacular with a pleasant outlook, with minimalist Japanese aesthetics, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 2860533,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-hokkaido-11-room-10-Double-OceanView",
    name: "Imperial Double Villa",
    description: "Step into a open-concept double villa that combines Imperial-themed with breathtaking with a view of the sandy beaches, complemented by with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 3183967,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  }
];
