// Auto-generated file for dublin hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const dublinHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "welcome@limerickriversidehotel.com",
      contactPhone: "+555 913-174-3460",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-dublin-1",
    name: "Limerick Riverside Hotel",
    address: "70 Patrick Avenue",
    rating: 4,
    accommodationType: "Luxury Lodge",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 53,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "general@killarneygrand.com",
      contactPhone: "+234 958-895-9266",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-dublin-2",
    name: "Killarney Grand",
    address: "25 New Kildare Lane",
    rating: 3,
    accommodationType: "Luxury Lodge",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 11,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reachus@limerickriversidehotel.com",
      contactPhone: "+317 995-308-3031",
    },
    policies: {
      cancellation: "Free cancellation up to 14 days before check-in; 50% refund for cancellations made within 14 days.",
      smoking: "Not Allowed",
    },
    id: "hotel-dublin-3",
    name: "Limerick Riverside Hotel",
    address: "219 Lower Cork Drive",
    rating: 3,
    accommodationType: "Chalet",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 29,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "support@theemeraldislehotel.com",
      contactPhone: "+628 281-329-5538",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Designated Areas",
    },
    id: "hotel-dublin-4",
    name: "The Emerald Isle Hotel",
    address: "196 Upper Wicklow Drive",
    rating: 3,
    accommodationType: "Spa Hotel",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 53,
    isPetFriendly: true,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "services@thearanislandsretreat.com",
      contactPhone: "+708 959-164-5121",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Designated Areas",
    },
    id: "hotel-dublin-5",
    name: "The Aran Islands Retreat",
    address: "273 Kildare Street",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 51,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "clientservices@theconnemaragrand.com",
      contactPhone: "+561 955-754-6145",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Allowed",
    },
    id: "hotel-dublin-6",
    name: "The Connemara Grand",
    address: "57 Cork Street",
    rating: 3,
    accommodationType: "Family Resort",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 10,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "ask@thecliffsofmoherlodge.com",
      contactPhone: "+798 171-483-4028",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-dublin-7",
    name: "The Cliffs of Moher Lodge",
    address: "29 Cork Street",
    rating: 3,
    accommodationType: "Resort",
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 48,
    isPetFriendly: true,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "info@dinglepeninsularetreat.com",
      contactPhone: "+220 119-246-1032",
    },
    policies: {
      cancellation: "Free cancellation within 24 hours of booking; after that, 25% fee applies.",
      smoking: "Not Allowed",
    },
    id: "hotel-dublin-8",
    name: "Dingle Peninsula Retreat",
    address: "239 Town Dawson Drive",
    rating: 3,
    accommodationType: "Boutique Inn",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 26,
    isPetFriendly: true,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "welcome@theburrenheritagehotel.com",
      contactPhone: "+409 654-148-9475",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Allowed",
    },
    id: "hotel-dublin-9",
    name: "The Burren Heritage Hotel",
    address: "128 Wicklow Street",
    rating: 4,
    accommodationType: "Boutique Resort",
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 46,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "support@killarneygrand.com",
      contactPhone: "+506 554-839-7605",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-dublin-10",
    name: "Killarney Grand",
    address: "156 Cork Road",
    rating: 4,
    accommodationType: "Bed and Breakfast",
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 17,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    id: "hotel-dublin-11",
    name: "The Giant's Causeway Hotel",
    address: "10 Main O'Connell Street",
    rating: 4,
    accommodationType: "Resort",
    amenities: ["24-Hour Front Desk", "Airport Shuttle", "Non-Smoking Rooms", "Restaurant", "Parking", "Spa", "Room Service", "Conference Room"],
    accessibilityFeatures: ["Visual Aids", "Sign Language Interpretation"],
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 44,
    isPetFriendly: false,
    currency: "EUR",
    contact: {
      contactEmail: "ask@thegiant'scausewayhotel.com",
      contactPhone: "+826 643-111-6389",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-dublin-12",
    name: "Dublin Castle Hotel",
    address: "203 Lower O'Connell Street",
    rating: 3,
    accommodationType: "Hotel",
    amenities: ["Conference Room", "Restaurant", "Free Wi-Fi", "Bar", "Non-Smoking Rooms", "Spa", "24-Hour Front Desk", "Laundry Service", "Swimming Pool", "Room Service"],
    accessibilityFeatures: ["Assistive Listening Devices", "Elevator", "Large Print Materials"],
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 32,
    isPetFriendly: false,
    currency: "EUR",
    contact: {
      contactEmail: "inquiries@dublincastlehotel.com",
      contactPhone: "+433 136-698-9348",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-dublin-13",
    name: "The Connemara Grand",
    address: "266 Main Cork Drive",
    rating: 3,
    accommodationType: "Serviced Apartment",
    amenities: ["Free Wi-Fi", "Swimming Pool", "Non-Smoking Rooms", "Room Service", "Airport Shuttle", "Fitness Center", "Bar"],
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 39,
    isPetFriendly: true,
    currency: "EUR",
    contact: {
      contactEmail: "care@theconnemaragrand.com",
      contactPhone: "+288 674-664-8735",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Designated Areas",
    },
    isPopular: true,
  }
];
