import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Emerald Isle Hotel
export const theEmeraldIsleHotelRooms: RoomOption[] = [
  {
    id: "hotel-dublin-4-room-3-SofaBed-MountainView",
    name: "Premium Sofa Bed Suite",
    description: "Unwind in this welcoming sofa bed suite where you can find inspiration in the mountains, featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 106,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-dublin-4-room-3-Single-None",
    name: "Signature Single Loft",
    description: "This bohemian single accommodation offers with a pleasant outlook, offering a unique Irish experience with a touch of elegance.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 65,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-dublin-4-room-3-Queen-CityView",
    name: "Shamrock Queen Apartment",
    description: "Step into a contemporary queen apartment that combines Shamrock-themed with breathtaking with a view of iconic landmarks, complemented by with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 109,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-dublin-4-room-3-King-CityView",
    name: "Emerald Isle King Apartment",
    description: "Relax in our room-filled lavish king apartment featuring where city lights twinkle at night, along with with a luxurious soaking tub and featuring cozy interiors with Irish-inspired decor.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 133,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-dublin-4-room-3-Queen-None",
    name: "Celtic Queen Apartment",
    description: "This traditional queen accommodation offers with a pleasant outlook, offering a unique Irish experience with a touch of elegance.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 105,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-dublin-4-room-3-King-GardenView",
    name: "Guinness King Loft",
    description: "A opulent king retreat with a view of the garden's tranquil pathways, with a warm and inviting atmosphere and modern amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 148,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-dublin-4-room-3-Single-OceanView",
    name: "Aran Single Suite",
    description: "Step into a vintage single suite that combines Aran-themed with breathtaking with a view of the sandy beaches, complemented by with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 94,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-dublin-4-room-3-Twin-None",
    name: "Luxury Twin Loft",
    description: "Discover the charm of this Luxury-themed twin loft, complete with elegant ambiance, stunning with a pleasant outlook, and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Visual Aids", "Elevator"],
    pricePerNight: 85,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-dublin-4-room-3-King-None",
    name: "Shamrock King Suite",
    description: "A generous king suite designed for vintage comfort, with with a pleasant outlook and equipped with all the modern conveniences, reflecting featuring cozy interiors with Irish-inspired decor.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 124,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  }
];
