import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Khách Sạn Vịnh Xanh
export const khchSnVnhXanhRooms: RoomOption[] = [
  {
    id: "hotel-mekong-delta-8-room-7-Twin-MountainView",
    name: "Executive Twin Penthouse",
    description: "A lavish twin retreat with panoramic views of the mountain landscape, featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Accessible Bathroom", "Hearing Support"],
    pricePerNight: 4964217,
    currency: "VND",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-mekong-delta-8-room-7-Double-GardenView",
    name: "Executive Double Room",
    description: "This bohemian double room promises with serene garden views, enriched by Executive-themed details and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 5528857,
    currency: "VND",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-mekong-delta-8-room-7-Queen-MountainView",
    name: "Superior Queen Villa",
    description: "This fashionable queen villa promises with a view of the mountains' natural beauty, enriched by Superior-themed details and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 7911431,
    currency: "VND",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-mekong-delta-8-room-7-King-OceanView",
    name: "Serenity King Villa",
    description: "This refined king accommodation offers with a view of the ocean's horizon, featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 9501154,
    currency: "VND",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-mekong-delta-8-room-7-Queen-CityView",
    name: "Harmony Queen Apartment",
    description: "Harmony-themed queen apartment with a front-row seat to the city's heartbeat, designed for ultimate comfort and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 6851197,
    currency: "VND",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-mekong-delta-8-room-7-SofaBed-None",
    name: "Deluxe Sofa Bed Apartment",
    description: "Our regal Deluxe-themed apartment offers with a pleasant outlook, grandiose comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 4036431,
    currency: "VND",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-mekong-delta-8-room-7-Twin-CityView",
    name: "Modern Twin Apartment",
    description: "Unwind in this palatial twin apartment with a view of the city's cultural landmarks, with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 4287542,
    currency: "VND",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-mekong-delta-8-room-7-Single-None",
    name: "Premium Single Suite",
    description: "Premium-themed suite with broad decor, with a pleasant outlook, and with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 3700412,
    currency: "VND",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-mekong-delta-8-room-7-SofaBed-OceanView",
    name: "Executive Sofa Bed Suite",
    description: "Unwind in this broad sofa bed suite where you can enjoy stunning sunsets over the water, with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 5937677,
    currency: "VND",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-mekong-delta-8-room-7-SofaBed-MountainView",
    name: "Serenity Sofa Bed Loft",
    description: "This upscale sofa bed loft promises with a view of the mountains' rugged terrain, enriched by Serenity-themed details and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 5501556,
    currency: "VND",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  }
];
