import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Pixie Hollow Suites
export const pixieHollowSuitesRooms: RoomOption[] = [
  {
    id: "hotel-boston-8-room-7-Queen-OceanView",
    name: "Executive Queen Loft",
    description: "This comfortable queen loft promises with breathtaking sea views, enriched by Executive-themed details and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 285,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-boston-8-room-7-Queen-MountainView",
    name: "Manhattan Queen Room",
    description: "Experience our lavish, roomy queen room with panoramic views of the surrounding mountains, with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 325,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-boston-8-room-7-SofaBed-CityView",
    name: "Luxury Sofa Bed Loft",
    description: "Experience our soothing, refined sofa bed loft where the city comes alive at dusk, featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 192,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-boston-8-room-7-Single-OceanView",
    name: "Superior Single Apartment",
    description: "This calming single apartment promises where the ocean meets the sky, enriched by Superior-themed details and with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids"],
    pricePerNight: 219,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-boston-8-room-7-Single-CityView",
    name: "Signature Single Apartment",
    description: "Discover the charm of this Signature-themed single apartment, complete with serene ambiance, stunning overlooking the vibrant cityscape, and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 174,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-boston-8-room-7-King-None",
    name: "Classic King Apartment",
    description: "A tranquil king apartment designed for expansive comfort, with with a pleasant outlook and with plush bedding for ultimate comfort, reflecting with rustic and modern influences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 302,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  }
];
