import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Azure Hotel & Art Studio
export const azureHotelArtStudioRooms: RoomOption[] = [
  {
    id: "hotel-philipsburg-8-room-7-Twin-CityView",
    name: "Superior Twin Villa",
    description: "Unwind in this gentle twin villa where the city comes alive at dusk, with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 308,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-philipsburg-8-room-7-Single-OceanView",
    name: "Superior Single Studio",
    description: "Step into a calming single studio that combines Superior-themed with breathtaking where the horizon meets the ocean, complemented by with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 304,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-philipsburg-8-room-7-King-GardenView",
    name: "Executive King Villa",
    description: "Our Executive-themed king villa offers lavish luxury, panoramic featuring a peaceful garden setting, and complete with a well-appointed bathroom, inspired by with tropical and nautical themes.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 473,
    currency: "ANG",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-philipsburg-8-room-7-Twin-MountainView",
    name: "Classic Twin Suite",
    description: "This inviting twin suite promises where you can gaze at the towering peaks, enriched by Classic-themed details and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 351,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-philipsburg-8-room-7-Double-GardenView",
    name: "Luxury Double Penthouse",
    description: "Enjoy a stylish stay in our Luxury-themed double penthouse, offering offering a peaceful garden outlook, featuring a curated minibar selection, and unique touches of with tropical and nautical themes.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Accessible Bathroom", "Hearing Support", "Elevator"],
    pricePerNight: 338,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-philipsburg-8-room-7-King-None",
    name: "Deluxe King Penthouse",
    description: "A calming king penthouse designed for deluxe comfort, with with a pleasant outlook and with a modern en-suite bathroom, reflecting blending Caribbean warmth with laid-back luxury.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 447,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  }
];
