// Auto-generated file for philipsburg hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const philipsburgHotels: Hotel[] = [
  {
    id: "hotel-philipsburg-1",
    name: "Riu Palace St. Martin",
    address: "286 Welfare Drive",
    rating: 3,
    accommodationType: "Boutique Resort",
    amenities: ["Bar", "Room Service", "Laundry Service", "Conference Room", "Airport Shuttle"],
    accessibilityFeatures: ["Visual Aids", "Hearing Loop", "Accessible Parking"],
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 41,
    isPetFriendly: false,
    currency: "ANG",
    contact: {
      contactEmail: "services@riupalacest.martin.com",
      contactPhone: "+710 825-791-6767",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Designated Areas",
    },
    isPopular: true,
  },
  {
    id: "hotel-philipsburg-2",
    name: "Azure Hotel & Art Studio",
    address: "196 Airport Little Bay Way",
    rating: 4,
    accommodationType: "Business Hotel",
    amenities: ["24-Hour Front Desk", "Restaurant", "Spa", "Non-Smoking Rooms", "Conference Room", "Fitness Center", "Swimming Pool", "Free Wi-Fi", "Airport Shuttle", "Parking"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Visual Alarm"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 32,
    isPetFriendly: false,
    currency: "ANG",
    contact: {
      contactEmail: "hello@azurehotel&artstudio.com",
      contactPhone: "+845 191-301-4840",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-philipsburg-3",
    name: "Secrets St. Martin Resort & Spa",
    address: "16 Back Drive",
    rating: 3,
    accommodationType: "Extended Stay Hotel",
    amenities: ["Conference Room", "Spa", "Bar", "Fitness Center", "Airport Shuttle", "Non-Smoking Rooms"],
    accessibilityFeatures: ["Grab Bars"],
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 46,
    isPetFriendly: true,
    currency: "ANG",
    contact: {
      contactEmail: "admin@secretsst.martinresort&spa.com",
      contactPhone: "+797 586-783-1792",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-philipsburg-4",
    name: "Mercure St. Martin Marina",
    address: "63 Front Beacon Hill Way",
    rating: 3,
    accommodationType: "Spa Hotel",
    amenities: ["Parking", "24-Hour Front Desk", "Free Wi-Fi", "Swimming Pool", "Business Center", "Spa"],
    accessibilityFeatures: ["Tactile Maps"],
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 18,
    isPetFriendly: false,
    currency: "ANG",
    contact: {
      contactEmail: "connect@mercurest.martinmarina.com",
      contactPhone: "+230 920-431-5774",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-philipsburg-5",
    name: "The Orient Bay Retreat",
    address: "46 Simpson Bay Street",
    rating: 3,
    accommodationType: "Extended Stay Hotel",
    amenities: ["Free Wi-Fi", "Non-Smoking Rooms", "Room Service", "Swimming Pool", "Fitness Center", "Laundry Service", "Restaurant", "Bar"],
    accessibilityFeatures: ["Visual Alarm", "Sign Language Interpretation"],
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 55,
    isPetFriendly: false,
    currency: "ANG",
    contact: {
      contactEmail: "care@theorientbayretreat.com",
      contactPhone: "+847 553-116-1051",
    },
    policies: {
      cancellation: "Full refund if cancelled within 48 hours of booking, minus service fees.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  }
];
