import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Oceans Edge Hotel
export const oceansEdgeHotelRooms: RoomOption[] = [
  {
    id: "hotel-philipsburg-1-room-0-SofaBed-CityView",
    name: "Marigot Sofa Bed Penthouse",
    description: "A roomy sofa bed penthouse designed for luxurious comfort, with offering panoramic city vistas and offering a unique blend of style and comfort, reflecting offering a vibrant island-inspired experience.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 666,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-philipsburg-1-room-0-Queen-MountainView",
    name: "Classic Queen Suite",
    description: "Step into a rustic queen suite that combines Classic-themed with breathtaking with panoramic views of the mountain landscape, complemented by featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Elevator", "Wheelchair Accessible"],
    pricePerNight: 1023,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-philipsburg-1-room-0-Queen-GardenView",
    name: "Lagoon Queen Suite",
    description: "Unwind in this minimalist queen suite with serene garden views, with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Hearing Support"],
    pricePerNight: 805,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-philipsburg-1-room-0-SofaBed-MountainView",
    name: "Luxury Sofa Bed Villa",
    description: "A well-proportioned sofa bed retreat featuring awe-inspiring mountain scenery, featuring bright, cheerful decor.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 727,
    currency: "ANG",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-philipsburg-1-room-0-Twin-OceanView",
    name: "Classic Twin Apartment",
    description: "Unwind in this intimate twin apartment with breathtaking sea views, with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 804,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-philipsburg-1-room-0-SofaBed-None",
    name: "Executive Sofa Bed Penthouse",
    description: "Our glamorous Executive-themed penthouse offers with a pleasant outlook, contemporary comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 586,
    currency: "ANG",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-philipsburg-1-room-0-Double-MountainView",
    name: "Island Breeze Double Loft",
    description: "Step into a sumptuous double loft that combines Island Breeze-themed with breathtaking with panoramic views of the surrounding mountains, complemented by with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids", "Accessible Bathroom"],
    pricePerNight: 759,
    currency: "ANG",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-philipsburg-1-room-0-Twin-GardenView",
    name: "Lagoon Twin Studio",
    description: "A bohemian twin studio designed for expansive comfort, with where you can enjoy the garden's peaceful atmosphere and with blackout curtains for a perfect night's sleep, reflecting blending Caribbean warmth with laid-back luxury.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 677,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-philipsburg-1-room-0-Single-GardenView",
    name: "Seashell Single Penthouse",
    description: "Unwind in this cozy single penthouse with a view of blooming flowers and greenery, with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 614,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-philipsburg-1-room-0-SofaBed-OceanView",
    name: "Signature Sofa Bed Penthouse",
    description: "Our Signature-themed sofa bed penthouse offers stylish luxury, panoramic where you can hear the soothing sound of the sea, and with a luxurious soaking tub, inspired by offering a vibrant island-inspired experience.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 819,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  }
];
