import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Ambassador
export const theAmbassadorRooms: RoomOption[] = [
  {
    id: "hotel-philipsburg-7-room-6-Twin-None",
    name: "Standard Twin Villa",
    description: "Indulge in the comfortable atmosphere of our twin villa, with spectacular with a pleasant outlook, offering a vibrant island-inspired experience, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 742,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-philipsburg-7-room-6-Double-OceanView",
    name: "Classic Double Room",
    description: "A elegant double room designed for sizable comfort, with with a view of the tranquil sea and with high-speed internet access, reflecting blending Caribbean warmth with laid-back luxury.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 1067,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-philipsburg-7-room-6-Single-OceanView",
    name: "Standard Single Penthouse",
    description: "Relax in our tranquil intimate single penthouse featuring where the horizon meets the ocean, along with with a spacious seating area and with tropical and nautical themes.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Elevator", "Wheelchair Accessible", "Accessible Bathroom"],
    pricePerNight: 799,
    currency: "ANG",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-philipsburg-7-room-6-Queen-None",
    name: "Marigot Queen Studio",
    description: "Experience our glamorous, well-proportioned queen studio with a pleasant outlook, equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 1012,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-philipsburg-7-room-6-Queen-CityView",
    name: "Caribbean Charm Queen Room",
    description: "Enjoy a plush stay in our Caribbean Charm-themed queen room, offering where city lights twinkle at night, with a private balcony or terrace, and unique touches of blending Caribbean warmth with laid-back luxury.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 1099,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-philipsburg-7-room-6-SofaBed-MountainView",
    name: "Superior Sofa Bed Apartment",
    description: "This sophisticated sofa bed accommodation offers featuring awe-inspiring mountain scenery, with tropical and nautical themes.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 919,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-philipsburg-7-room-6-Double-GardenView",
    name: "Signature Double Room",
    description: "This bohemian double accommodation offers where you can enjoy the tranquility of nature, blending Caribbean warmth with laid-back luxury.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 984,
    currency: "ANG",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-philipsburg-7-room-6-Single-CityView",
    name: "Signature Single Suite",
    description: "Relax in our soft relaxing single suite featuring where you can enjoy the city's energy, along with complete with a well-appointed bathroom and blending Caribbean warmth with laid-back luxury.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 707,
    currency: "ANG",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  }
];
