import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Cherry Blossom Lodge
export const cherryBlossomLodgeRooms: RoomOption[] = [
  {
    id: "hotel-takayama-8-room-7-Twin-OceanView",
    name: "Premium Twin Villa",
    description: "This intimate twin accommodation offers where you can relax to the sound of the waves, with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Elevator", "Wheelchair Accessible"],
    pricePerNight: 3035316,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-takayama-8-room-7-Double-MountainView",
    name: "Standard Double Villa",
    description: "A grandiose double villa designed for homey comfort, with where you can find inspiration in the mountains and with a spacious seating area, reflecting with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 3721300,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-takayama-8-room-7-King-MountainView",
    name: "Premium King Loft",
    description: "Our regal Premium-themed loft offers overlooking spectacular mountain ranges, sizable comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 4458504,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-takayama-8-room-7-Single-None",
    name: "Fuji Single Penthouse",
    description: "Discover the charm of this Fuji-themed single penthouse, complete with broad ambiance, stunning with a pleasant outlook, and with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Accessible Bathroom", "Wheelchair Accessible"],
    pricePerNight: 2390152,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-takayama-8-room-7-Single-OceanView",
    name: "Premium Single Suite",
    description: "A chic single suite designed for airy comfort, with where you can feel the ocean breeze and with a private balcony or terrace, reflecting with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 2683898,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-takayama-8-room-7-Twin-CityView",
    name: "Signature Twin Apartment",
    description: "Step into a intimate twin apartment that combines Signature-themed with breathtaking where you can watch the city wake up, complemented by with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 2570016,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-takayama-8-room-7-Twin-None",
    name: "Deluxe Twin Loft",
    description: "Deluxe-themed twin loft with a pleasant outlook, featuring traditional tatami elements and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 2557579,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-takayama-8-room-7-Queen-None",
    name: "Deluxe Queen Studio",
    description: "Relax in our stretching welcoming queen studio featuring with a pleasant outlook, along with with blackout curtains for a perfect night's sleep and with minimalist Japanese aesthetics.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 3363216,
    currency: "JPY",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-takayama-8-room-7-Twin-MountainView",
    name: "Imperial Twin Loft",
    description: "Relax in our majestic restful twin loft featuring where you can escape to the mountains, along with equipped with all the modern conveniences and combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Elevator", "Hearing Support"],
    pricePerNight: 3048307,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-takayama-8-room-7-King-GardenView",
    name: "Standard King Studio",
    description: "A elegant king retreat where you can enjoy the beauty of nature, featuring traditional tatami elements.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 4244847,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  }
];
