import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Geisha Pavilion
export const theGeishaPavilionRooms: RoomOption[] = [
  {
    id: "hotel-takayama-12-room-11-SofaBed-None",
    name: "Classic Sofa Bed Loft",
    description: "Enjoy a upscale stay in our Classic-themed sofa bed loft, offering with a pleasant outlook, with high-speed internet access, and unique touches of offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 2021766,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-takayama-12-room-11-Twin-GardenView",
    name: "Sakura Twin Room",
    description: "Our Sakura-themed twin room offers room-filled luxury, panoramic with a view of the garden's tranquil pathways, and with a luxurious soaking tub, inspired by offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 2386405,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-takayama-12-room-11-King-GardenView",
    name: "Superior King Suite",
    description: "A wide-ranging king suite designed for airy comfort, with surrounded by vibrant flora and with high-speed internet access, reflecting offering the perfect balance of Eastern serenity and Western comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Visual Aids", "Elevator", "Wheelchair Accessible"],
    pricePerNight: 3500573,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-takayama-12-room-11-Single-CityView",
    name: "Imperial Single Villa",
    description: "Discover the charm of this Imperial-themed single villa, complete with welcoming ambiance, stunning where you can watch the city wake up, and with a spacious seating area.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 1828183,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-takayama-12-room-11-SofaBed-CityView",
    name: "Signature Sofa Bed Loft",
    description: "This snug sofa bed loft promises showcasing the urban landscape, enriched by Signature-themed details and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 2128424,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-takayama-12-room-11-Queen-GardenView",
    name: "Premium Queen Penthouse",
    description: "A plush queen penthouse designed for restful comfort, with where you can relax in a garden haven and with a spacious seating area, reflecting combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 3419662,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-takayama-12-room-11-Single-OceanView",
    name: "Executive Single Penthouse",
    description: "A modern single penthouse designed for eclectic comfort, with where you can relax to the sound of the waves and featuring a curated minibar selection, reflecting combining modern luxury with Japanese tradition.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 2343512,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-takayama-12-room-11-Double-None",
    name: "Fuji Double Apartment",
    description: "Indulge in the ornate atmosphere of our double apartment, with spectacular with a pleasant outlook, featuring traditional tatami elements, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 2101965,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-takayama-12-room-11-King-OceanView",
    name: "Zen King Studio",
    description: "Zen-themed king studio where the ocean meets the sky, combining modern luxury with Japanese tradition and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 4309733,
    currency: "JPY",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  }
];
