import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Castello di Sogno
export const castelloDiSognoRooms: RoomOption[] = [
  {
    id: "hotel-milan-1-room-0-King-MountainView",
    name: "Premium King Studio",
    description: "Step into a artistic king studio that combines Premium-themed with breathtaking where you can gaze at the towering peaks, complemented by offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 324,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-milan-1-room-0-SofaBed-GardenView",
    name: "Deluxe Sofa Bed Studio",
    description: "A soothing sofa bed retreat with a view of tranquil water features, with classic Italian elegance.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 173,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-milan-1-room-0-Twin-GardenView",
    name: "Standard Twin Suite",
    description: "Experience our tranquil, roomy twin suite where you can relax in a natural oasis, with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 176,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-milan-1-room-0-Twin-MountainView",
    name: "Standard Twin Penthouse",
    description: "A refreshing twin retreat with majestic mountain vistas, with classic Italian elegance.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 200,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-milan-1-room-0-Queen-MountainView",
    name: "Signature Queen Loft",
    description: "Signature-themed loft with restful decor, with a view of the rugged mountain landscape, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 255,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-milan-1-room-0-SofaBed-MountainView",
    name: "Standard Sofa Bed Loft",
    description: "Standard-themed sofa bed loft with a view of the mountains' natural beauty, featuring tasteful Mediterranean touches and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 211,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
