import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Molise Heritage Hotel
export const theMoliseHeritageHotelRooms: RoomOption[] = [
  {
    id: "hotel-milan-2-room-1-Twin-CityView",
    name: "Standard Twin Villa",
    description: "A soothing twin villa designed for traditional comfort, with where the city skyline meets the horizon and with plush bedding for ultimate comfort, reflecting offering a touch of la dolce vita.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 78,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-milan-2-room-1-Double-GardenView",
    name: "Superior Double Studio",
    description: "Superior-themed double studio where you can enjoy the serenity of a garden retreat, featuring tasteful Mediterranean touches and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 90,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-milan-2-room-1-Twin-GardenView",
    name: "Deluxe Twin Studio",
    description: "Deluxe-themed studio with minimalist decor, where you can enjoy the beauty of nature, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 92,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-milan-2-room-1-SofaBed-None",
    name: "Serenity Sofa Bed Penthouse",
    description: "Experience our compact, soothing sofa bed penthouse with a pleasant outlook, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 85,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-milan-2-room-1-Queen-OceanView",
    name: "Tranquility Queen Penthouse",
    description: "Enjoy a compact stay in our Tranquility-themed queen penthouse, offering where you can enjoy the ocean's beauty, with blackout curtains for a perfect night's sleep, and unique touches of featuring tasteful Mediterranean touches.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 145,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-milan-2-room-1-Single-None",
    name: "Signature Single Studio",
    description: "Our Signature-themed single studio offers artistic luxury, panoramic with a pleasant outlook, and with a spacious work area, inspired by with classic Italian elegance.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 66,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-milan-2-room-1-King-OceanView",
    name: "Standard King Apartment",
    description: "A compact king retreat with a panoramic view of the coastline, with classic Italian elegance.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 155,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-milan-2-room-1-Twin-MountainView",
    name: "Harmony Twin Loft",
    description: "Enjoy a generous stay in our Harmony-themed twin loft, offering where the mountains touch the sky, including climate control for your comfort, and unique touches of featuring tasteful Mediterranean touches.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 91,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-milan-2-room-1-Single-MountainView",
    name: "Superior Single Studio",
    description: "This ample single accommodation offers with a view of the mountains' rugged terrain, offering a touch of la dolce vita.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 91,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  }
];
