// Auto-generated file for florence hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const florenceHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "communications@thenaplesbayhotel.com",
      contactPhone: "+818 714-493-7213",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Allowed",
    },
    id: "hotel-florence-1",
    name: "The Naples Bay Hotel",
    address: "131 Hilltop St",
    rating: 4,
    accommodationType: "Extended Stay Hotel",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 17,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "clientservices@thetuscanvineyardinn.com",
      contactPhone: "+385 655-496-4553",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-florence-2",
    name: "The Tuscan Vineyard Inn",
    address: "166 Broadway Ave",
    rating: 4,
    accommodationType: "All-Inclusive Resort",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 53,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "general@palazzomedici.com",
      contactPhone: "+286 646-350-2189",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-florence-3",
    name: "Palazzo Medici",
    address: "160 Broadway St",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 18,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "team@thecapriislandretreat.com",
      contactPhone: "+799 362-608-2298",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Not Allowed",
    },
    id: "hotel-florence-4",
    name: "The Capri Island Retreat",
    address: "70 Broadway Street",
    rating: 3,
    accommodationType: "Extended Stay Hotel",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 28,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "feedback@hotelsanmarco.com",
      contactPhone: "+832 375-220-3419",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Designated Areas",
    },
    id: "hotel-florence-5",
    name: "Hotel San Marco",
    address: "212 East Queen St",
    rating: 4,
    accommodationType: "Eco-Lodge",
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 14,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "connect@ilpalazzohotel.com",
      contactPhone: "+638 393-478-8450",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-florence-6",
    name: "Il Palazzo Hotel",
    address: "89 East Queen Avenue",
    rating: 4,
    accommodationType: "Family Resort",
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 53,
    isPetFriendly: true,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "care@lafontanaresort.com",
      contactPhone: "+780 703-602-8452",
    },
    policies: {
      cancellation: "Free cancellation within 24 hours of booking; after that, 25% fee applies.",
      smoking: "Designated Areas",
    },
    id: "hotel-florence-7",
    name: "La Fontana Resort",
    address: "112 Riverside Court",
    rating: 4,
    accommodationType: "Glamping Resort",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 33,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reception@trattoriainn.com",
      contactPhone: "+39 208-364-9711",
    },
    policies: {
      cancellation: "Free cancellation up to 14 days before check-in; 50% refund for cancellations made within 14 days.",
      smoking: "Not Allowed",
    },
    id: "hotel-florence-8",
    name: "Trattoria Inn",
    address: "294 Park Avenue",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 47,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "inquiries@hotelbellanapoli.com",
      contactPhone: "+568 323-808-8125",
    },
    policies: {
      cancellation: "Full refund if cancelled within 48 hours of booking, minus service fees.",
      smoking: "Not Allowed",
    },
    id: "hotel-florence-9",
    name: "Hotel Bella Napoli",
    address: "280 Sunset Court",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 42,
    isPetFriendly: false,
    currency: "EUR",
    isPopular: true,
  },
  {
    id: "hotel-florence-10",
    name: "The Emilia-Romagna Heritage Hotel",
    address: "7 Main Court",
    rating: 4,
    accommodationType: "Serviced Apartment",
    amenities: ["Parking", "Restaurant", "Free Wi-Fi", "24-Hour Front Desk", "Spa", "Room Service"],
    accessibilityFeatures: ["Grab Bars"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 18,
    isPetFriendly: true,
    currency: "EUR",
    contact: {
      contactEmail: "hello@theemilia-romagnaheritagehotel.com",
      contactPhone: "+494 231-810-9089",
    },
    policies: {
      cancellation: "Full refund if cancelled within 48 hours of booking, minus service fees.",
      smoking: "Allowed",
    },
    isPopular: true,
  },
  {
    id: "hotel-florence-11",
    name: "Hotel San Marco",
    address: "34 Riverside St",
    rating: 3,
    accommodationType: "Luxury Lodge",
    amenities: ["Airport Shuttle", "Fitness Center", "Room Service", "Bar", "Swimming Pool", "Spa", "Restaurant"],
    accessibilityFeatures: ["Accessible Bathroom", "Hearing Loop", "Assistive Listening Devices"],
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 24,
    isPetFriendly: false,
    currency: "EUR",
    contact: {
      contactEmail: "inquiries@hotelsanmarco.com",
      contactPhone: "+632 244-943-4163",
    },
    policies: {
      cancellation: "Full refund if cancelled within 48 hours of booking, minus service fees.",
      smoking: "Allowed",
    },
    isPopular: true,
  },
  {
    id: "hotel-florence-12",
    name: "Il Palazzo Hotel",
    address: "273 Central Place",
    rating: 4,
    accommodationType: "Vacation Rental",
    amenities: ["Fitness Center", "Bar", "24-Hour Front Desk", "Non-Smoking Rooms", "Restaurant"],
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 46,
    isPetFriendly: false,
    currency: "EUR",
    contact: {
      contactEmail: "team@ilpalazzohotel.com",
      contactPhone: "+710 656-256-7494",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  }
];
