import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Prestige Hotel
export const thePrestigeHotelRooms: RoomOption[] = [
  {
    id: "hotel-florence-6-room-5-King-MountainView",
    name: "Superior King Villa",
    description: "Indulge in the refined atmosphere of our king villa, with spectacular where you can find inspiration in the mountains, featuring tasteful Mediterranean touches, and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 176,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-florence-6-room-5-Single-OceanView",
    name: "Deluxe Single Room",
    description: "This soothing single accommodation offers where you can enjoy the ocean's beauty, inspired by Italian Renaissance design.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 107,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-florence-6-room-5-SofaBed-None",
    name: "Modern Sofa Bed Villa",
    description: "A serene sofa bed villa designed for regal comfort, with with a pleasant outlook and complete with a well-appointed bathroom, reflecting inspired by Italian Renaissance design.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 84,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-florence-6-room-5-Single-GardenView",
    name: "Superior Single Penthouse",
    description: "A fashionable single retreat with a view of the garden's tranquil pathways, featuring tasteful Mediterranean touches.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Wheelchair Accessible", "Hearing Support"],
    pricePerNight: 87,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-florence-6-room-5-Twin-OceanView",
    name: "Harmony Twin Room",
    description: "Relax in our indulgent glamorous twin room featuring where you can enjoy the ocean's beauty, along with equipped with all the modern conveniences and inspired by Italian Renaissance design.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 112,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-florence-6-room-5-Twin-None",
    name: "Modern Twin Room",
    description: "A sizable twin retreat with a pleasant outlook, with classic Italian elegance.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 92,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-florence-6-room-5-Double-CityView",
    name: "Superior Double Suite",
    description: "A chic double retreat with a view of the city's waterfront, inspired by Italian Renaissance design.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 111,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-florence-6-room-5-Queen-CityView",
    name: "Premium Queen Apartment",
    description: "Discover the charm of this Premium-themed queen apartment, complete with palatial ambiance, stunning featuring a blend of modern and historic architecture, and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 131,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  }
];
