import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Urban Garden Hotel
export const urbanGardenHotelRooms: RoomOption[] = [
  {
    id: "hotel-florence-10-room-9-Twin-None",
    name: "Classic Twin Studio",
    description: "This prestigious twin accommodation offers with a pleasant outlook, inspired by Italian Renaissance design.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom", "Elevator"],
    pricePerNight: 154,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-florence-10-room-9-King-None",
    name: "Premium King Apartment",
    description: "Our Premium-themed king apartment offers sizable luxury, panoramic with a pleasant outlook, and featuring a curated minibar selection, inspired by with classic Italian elegance.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 222,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-florence-10-room-9-SofaBed-None",
    name: "Executive Sofa Bed Apartment",
    description: "Experience our well-proportioned, roomy sofa bed apartment with a pleasant outlook, with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Visual Aids", "Wheelchair Accessible", "Elevator"],
    pricePerNight: 157,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-florence-10-room-9-SofaBed-GardenView",
    name: "Standard Sofa Bed Villa",
    description: "This futuristic sofa bed accommodation offers offering a peaceful garden outlook, offering a touch of la dolce vita.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Wheelchair Accessible", "Accessible Bathroom"],
    pricePerNight: 194,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-florence-10-room-9-Double-GardenView",
    name: "Executive Double Penthouse",
    description: "A glamorous double retreat where you can enjoy the beauty of nature, with classic Italian elegance.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 192,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-florence-10-room-9-SofaBed-OceanView",
    name: "Standard Sofa Bed Suite",
    description: "This grandiose sofa bed accommodation offers with a panoramic view of the coastline, with classic Italian elegance.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Accessible Bathroom", "Wheelchair Accessible", "Elevator"],
    pricePerNight: 221,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-florence-10-room-9-Single-GardenView",
    name: "Harmony Single Suite",
    description: "This extravagant single accommodation offers where you can take in the fresh air, inspired by Italian Renaissance design.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 157,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
