import { Host } from "@/lib/interfaces/people/homestay";

export const amalfiCoastHomestays: Host[] = [
  {
    name: "Randy Carter",
    background: "Local chef specializing in traditional cuisines",
    maxGuests: 4,
    languages: ["English", "Czech", "Italian"],
    curfew: "22:00 PM",
    isPopular: false,
    guestPolicy: [
      "LGBTQ+ friendly",
      "Suitable for digital nomads",
      "Senior-friendly accommodations",
      "Ideal for solo travelers",
    ],
    hostingStyle: "social",
    houseRules: [
      "Lock the door when leaving the house",
      "No food in the bedrooms",
      "Remove shoes when entering the home",
      "Respect shared spaces",
      "Please clean up after yourself in common areas",
      "Notify host if you'll be arriving after 10 PM",
    ],
    location: {
      city: "Amalfi Coast",
      region: "Mediterranean",
      country: "Italy",
      coordinates: { lat: 40.05124778692015, lng: -0.0931177178465985 },
    },
    availability: {
      checkInTime: "12:00 PM",
      checkOutTime: "10:00 AM",
    },
    email: "randy.carter@paragontrailshomestays.com",
    phoneNumber: "+74-578-1826",
    isVerified: true,
    rating: 4.8,
    reviewCount: 38,
    quote:
      "Staying with me means experiencing amalfi-coast like a local. I love sharing the hidden gems of our beautiful city with my guests.",
    stayType: "heritage-stay",
  },
  {
    name: "Ravi Jennings",
    background:
      "Digital nomad who settled in the city after falling in love with it",
    maxGuests: 2,
    languages: ["English", "German", "Danish", "Polish"],
    curfew: "13:00 AM",
    isPopular: true,
    guestPolicy: [
      "Not suitable for infants (under 2 years)",
      "Ideal for solo travelers",
      "Suitable for digital nomads",
      "No parties or events",
    ],
    hostingStyle: "social",
    houseRules: [
      "Laundry available on weekends only",
      "Recycle according to local guidelines",
      "Wi-Fi password will be provided upon arrival",
      "Kitchen closed after 8 PM",
      "Quiet hours after 10 PM",
    ],
    location: {
      city: "Amalfi Coast",
      region: "Mediterranean",
      country: "Italy",
      coordinates: { lat: 40.03560661024433, lng: -0.02846459737169034 },
    },
    availability: {
      checkInTime: "13:00 PM",
      checkOutTime: "12:00 AM",
      calendarLink: "https://calendar.example.com/availability",
    },
    email: "ravi.jennings@paragontrailshomestays.com",
    isVerified: true,
    rating: 4.8,
    reviewCount: 76,
    quote:
      "My home is your home in amalfi-coast. I look forward to making your stay memorable and authentic.",
    stayType: "pet-friendly-stay",
  },
  {
    name: "Angela Reeves",
    background: "Artist who loves sharing local cultural insights",
    maxGuests: 4,
    languages: ["English", "Greek", "Dutch", "Russian"],
    curfew: "22:00 PM",
    isPopular: false,
    guestPolicy: ["No parties or events", "Great for couples"],
    hostingStyle: "private",
    houseRules: [
      "No smoking indoors",
      "Notify host if you'll be arriving after 10 PM",
      "No loud music after 9 PM",
      "Recycle according to local guidelines",
      "Remove shoes when entering the home",
    ],
    location: {
      city: "Amalfi Coast",
      region: "Mediterranean",
      country: "Italy",
      coordinates: { lat: 39.96484829344243, lng: -0.0764977658734814 },
    },
    availability: {
      checkInTime: "14:00 PM",
      checkOutTime: "11:00 AM",
    },
    email: "angela.reeves@paragontrailshomestays.com",
    phoneNumber: "+3-731-7921",
    isVerified: true,
    rating: 4.9,
    reviewCount: 44,
    quote:
      "Welcome to my amalfi-coast home! I believe in creating a warm, welcoming environment for all my guests.",
    stayType: "villa-stay",
  },
  {
    name: "Jeffrey Jansen",
    background: "Former tour guide with extensive knowledge of local history",
    maxGuests: 4,
    languages: ["English", "Danish", "Swedish"],
    curfew: "23:00 PM",
    isPopular: false,
    guestPolicy: [
      "Accessible for guests with mobility issues",
      "Not suitable for infants (under 2 years)",
    ],
    hostingStyle: "hands-on",
    houseRules: [
      "Quiet hours after 10 PM",
      "No loud music after 9 PM",
      "No outside guests without permission",
    ],
    location: {
      city: "Amalfi Coast",
      region: "Mediterranean",
      country: "Italy",
      coordinates: { lat: 39.96095655098867, lng: 0.09488835713702601 },
    },
    availability: {
      checkInTime: "17:00 PM",
      checkOutTime: "10:00 AM",
      calendarLink: "https://calendar.example.com/availability",
    },
    email: "jeffrey.jansen@paragontrailshomestays.com",
    phoneNumber: "+6-1024-10400",
    isVerified: true,
    rating: 4.1,
    reviewCount: 15,
    quote:
      "Life in amalfi-coast has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
    stayType: "farm-stay",
  },
  {
    name: "Mateo Singh",
    background: "Expat who has lived in the city for over a decade",
    maxGuests: 4,
    languages: ["English", "Norwegian", "Swedish"],
    curfew: "21:00 PM",
    isPopular: true,
    guestPolicy: [
      "No children under 12",
      "No parties or events",
      "Not suitable for infants (under 2 years)",
    ],
    hostingStyle: "private",
    houseRules: [
      "Please clean up after yourself in common areas",
      "Quiet hours after 10 PM",
      "Wi-Fi password will be provided upon arrival",
      "Kitchen closed after 8 PM",
      "Respect shared spaces",
      "No smoking indoors",
    ],
    location: {
      city: "Amalfi Coast",
      region: "Mediterranean",
      country: "Italy",
      coordinates: { lat: 40.085226249992836, lng: -0.04015232771160107 },
    },
    availability: {
      checkInTime: "12:00 PM",
      checkOutTime: "9:00 AM",
    },
    email: "mateo.singh@paragontrailshomestays.com",
    phoneNumber: "+18-354-2253",
    isVerified: true,
    rating: 4.7,
    reviewCount: 61,
    quote:
      "Staying with me means experiencing amalfi-coast like a local. I love sharing the hidden gems of our beautiful city with my guests.",
    stayType: "eco-stay",
  },
  {
    name: "Lucas Hunter",
    background: "Long-time resident and community organizer",
    maxGuests: 1,
    languages: ["English", "Finnish", "German"],
    curfew: "14:00 AM",
    isPopular: false,
    guestPolicy: ["Family-friendly environment", "Children welcome"],
    hostingStyle: "hands-on",
    houseRules: [
      "Respect shared spaces",
      "No pets allowed",
      "Notify host if you'll be arriving after 10 PM",
      "No loud music after 9 PM",
      "Breakfast is self-serve between 7-9 AM",
    ],
    location: {
      city: "Amalfi Coast",
      region: "Mediterranean",
      country: "Italy",
      coordinates: { lat: 39.97206411199678, lng: 0.012067839472953243 },
    },
    availability: {
      checkInTime: "14:00 PM",
      checkOutTime: "12:00 AM",
      calendarLink: "https://calendar.example.com/availability",
    },
    email: "lucas.hunter@paragontrailshomestays.com",
    phoneNumber: "+65-367-8517",
    isVerified: true,
    rating: 4.7,
    reviewCount: 47,
    quote:
      "Welcome to my amalfi-coast home! I believe in creating a warm, welcoming environment for all my guests.",
    stayType: "heritage-stay",
  },
  {
    name: "Avery Hawkins",
    background: "Expat who has lived in the city for over a decade",
    maxGuests: 6,
    languages: ["English", "Czech", "Finnish"],
    curfew: "14:00 AM",
    isPopular: false,
    guestPolicy: [
      "Suitable for business travelers",
      "Senior-friendly accommodations",
    ],
    hostingStyle: "private",
    houseRules: [
      "Wi-Fi password will be provided upon arrival",
      "Lock the door when leaving the house",
      "No smoking indoors",
      "No food in the bedrooms",
      "No loud music after 9 PM",
    ],
    location: {
      city: "Amalfi Coast",
      region: "Mediterranean",
      country: "Italy",
      coordinates: { lat: 39.9005020758603, lng: -0.06462426883312596 },
    },
    availability: {
      checkInTime: "16:00 PM",
      checkOutTime: "10:00 AM",
    },
    email: "avery.hawkins@paragontrailshomestays.com",
    isVerified: true,
    rating: 4,
    reviewCount: 31,
    quote:
      "Staying with me means experiencing amalfi-coast like a local. I love sharing the hidden gems of our beautiful city with my guests.",
    stayType: "shared-room",
  },
];
