// Homestay data for amalfi-coast
// This file is auto-generated. Do not edit manually.

import { Host } from "@/lib/interfaces/people/homestay";

export const amalfiCoastHomestays: Host[] = [
      {
        name: "Michelle Russell",
        background: "Digital nomad who settled in the city after falling in love with it",
        maxGuests: 5,
        languages: ["English", "Chinese", "Japanese"],
        curfew: "13:00 AM",
        isPopular: true,
        guestPolicy: ["Smoking allowed in designated areas only", "Family-friendly environment"],
        hostingStyle: "family-oriented",
        houseRules: ["Wi-Fi password will be provided upon arrival", "Notify host if you'll be arriving after 10 PM", "Please clean up after yourself in common areas", "No food in the bedrooms"],
        location: {
          city: "Amalfi Coast",
          region: "Southern Italy",
          country: "Italy",
          coordinates: { lat: 39.96660281490629, lng: 0.06858032401498063 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "michelle.russell@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.6,
        reviewCount: 99,
        quote: "Staying with me means experiencing amalfi-coast like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "culinary-homestay",
      }
,
      {
        name: "Hiroshi Porter",
        background: "Yoga instructor offering morning sessions",
        maxGuests: 3,
        languages: ["English", "French", "Arabic"],
        curfew: "22:00 PM",
        isPopular: false,
        guestPolicy: ["Not suitable for infants (under 2 years)", "Family-friendly environment", "Ideal for solo travelers", "Suitable for digital nomads"],
        hostingStyle: "private",
        houseRules: ["No smoking indoors", "Kitchen closed after 8 PM", "Notify host if you'll be arriving after 10 PM", "Remove shoes when entering the home", "No loud music after 9 PM", "Quiet hours after 10 PM"],
        location: {
          city: "Amalfi Coast",
          region: "Southern Italy",
          country: "Italy",
          coordinates: { lat: 40.057325290896515, lng: -0.05727099073197244 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "hiroshi.porter@paragontrailshomestays.com",
        phoneNumber: "+89-205-8409",
        isVerified: true,
        rating: 4.5,
        reviewCount: 54,
        quote: "My home is your home in amalfi-coast. I look forward to making your stay memorable and authentic.",
        stayType: "spiritual-or-wellness-retreat",
      },
      {
        name: "Cynthia Bennett",
        background: "Long-time resident and community organizer",
        maxGuests: 2,
        languages: ["English", "Japanese", "German", "Portuguese"],
        curfew: "22:00 PM",
        isPopular: true,
        guestPolicy: ["Perfect for long-term stays", "Great for couples", "Smoking allowed in designated areas only"],
        hostingStyle: "family-oriented",
        houseRules: ["Wi-Fi password will be provided upon arrival", "No food in the bedrooms", "Please clean up after yourself in common areas", "Recycle according to local guidelines", "Pets welcome", "Respect shared spaces"],
        location: {
          city: "Amalfi Coast",
          region: "Southern Italy",
          country: "Italy",
          coordinates: { lat: 40.0316975886222, lng: 0.08153714532695774 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "cynthia.bennett@paragontrailshomestays.com",
        phoneNumber: "+80-864-8659",
        isVerified: true,
        rating: 4.3,
        reviewCount: 33,
        quote: "I've lived in amalfi-coast all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "guest-suite",
      },
      {
        name: "Mateo Smith",
        background: "Local musician involved in the cultural scene",
        maxGuests: 1,
        languages: ["English", "German", "Spanish"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Family-friendly environment", "LGBTQ+ friendly", "Not suitable for infants (under 2 years)"],
        hostingStyle: "private",
        houseRules: ["Recycle according to local guidelines", "Quiet hours after 10 PM", "Respect shared spaces", "No food in the bedrooms", "Kitchen closed after 8 PM"],
        location: {
          city: "Amalfi Coast",
          region: "Southern Italy",
          country: "Italy",
          coordinates: { lat: 39.98718025238965, lng: -0.09530033657885038 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "mateo.smith@paragontrailshomestays.com",
        phoneNumber: "+56-579-7940",
        isVerified: true,
        rating: 4.6,
        reviewCount: 18,
        quote: "Life in amalfi-coast has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "villa-stay",
      }
,
      {
        name: "Harold Nguyen",
        background: "Long-time resident and community organizer",
        maxGuests: 3,
        languages: ["English", "Italian", "Russian"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["Pet-friendly accommodation", "Accessible for guests with mobility issues", "Not suitable for infants (under 2 years)"],
        hostingStyle: "private",
        houseRules: ["Pets welcome", "Kitchen closed after 8 PM", "Recycle according to local guidelines", "Remove shoes when entering the home", "Respect shared spaces", "Quiet hours after 10 PM"],
        location: {
          city: "Amalfi Coast",
          region: "Southern Italy",
          country: "Italy",
          coordinates: { lat: 39.91730274368163, lng: 0.07948348411493009 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "harold.nguyen@paragontrailshomestays.com",
        isVerified: true,
        rating: 4,
        reviewCount: 19,
        quote: "Welcome to my amalfi-coast home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "culinary-homestay",
      }
,
      {
        name: "Nomsa Morales",
        background: "Digital nomad who settled in the city after falling in love with it",
        maxGuests: 6,
        languages: ["English", "Italian", "Chinese", "French"],
        curfew: "13:00 AM",
        isPopular: true,
        guestPolicy: ["No parties or events", "Perfect for long-term stays", "No children under 12", "Accessible for guests with mobility issues"],
        hostingStyle: "laid-back",
        houseRules: ["Remove shoes when entering the home", "No pets allowed", "Notify host if you'll be arriving after 10 PM"],
        location: {
          city: "Amalfi Coast",
          region: "Southern Italy",
          country: "Italy",
          coordinates: { lat: 40.05917577801953, lng: 0.0896532529582432 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "nomsa.morales@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.8,
        reviewCount: 98,
        quote: "Staying with me means experiencing amalfi-coast like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "spiritual-or-wellness-retreat",
      },
      {
        name: "Sophia Wright",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 5,
        languages: ["English", "Spanish", "Chinese"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["Family-friendly environment", "LGBTQ+ friendly", "Suitable for digital nomads", "Pet-friendly accommodation"],
        hostingStyle: "private",
        houseRules: ["Notify host if you'll be arriving after 10 PM", "No food in the bedrooms", "Quiet hours after 10 PM"],
        location: {
          city: "Amalfi Coast",
          region: "Southern Italy",
          country: "Italy",
          coordinates: { lat: 40.04009061527915, lng: -0.007189094177763922 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "sophia.wright@paragontrailshomestays.com",
        phoneNumber: "+63-505-2067",
        isVerified: true,
        rating: 3.7,
        reviewCount: 18,
        quote: "Welcome to my amalfi-coast home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "heritage-stay",
      },
      {
        name: "Alice Jansen",
        background: "Entrepreneur running a local business",
        maxGuests: 1,
        languages: ["English", "Japanese", "Portuguese"],
        curfew: "24:00 PM",
        isPopular: true,
        guestPolicy: ["Suitable for business travelers", "Perfect for long-term stays", "Accessible for guests with mobility issues", "No children under 12"],
        hostingStyle: "hands-on",
        houseRules: ["No smoking indoors", "Kitchen closed after 8 PM", "Please conserve water and electricity", "Laundry available on weekends only", "Lock the door when leaving the house"],
        location: {
          city: "Amalfi Coast",
          region: "Southern Italy",
          country: "Italy",
          coordinates: { lat: 40.04663524544501, lng: -0.03212132066716977 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "11:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "alice.jansen@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.6,
        reviewCount: 30,
        quote: "I've lived in amalfi-coast all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "urban-apartment-stay",
      }

];
