// Homestay data for bali
// This file is auto-generated. Do not edit manually.

// Genderated on: 2025-06-08T04:09:39.248Z

// City: bali
// Region: Indonesia
// Country: Indonesia

import { Host } from "@/lib/interfaces/people/homestay";

export const baliHomestays: Host[] = [
      {
        name: "Skylar Brown",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 6,
        languages: ["English", "Arabic", "German", "Russian"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["Ideal for solo travelers", "No parties or events", "Not suitable for infants (under 2 years)"],
        hostingStyle: "social",
        houseRules: ["Respect shared spaces", "Please conserve water and electricity", "Pets welcome", "Lock the door when leaving the house", "Please clean up after yourself in common areas"],
        location: {
          city: "Bali",
          region: "Indonesia",
          country: "Indonesia",
          coordinates: { lat: 40.0722571463668, lng: -0.09647726254557357 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "skylar.brown@paragontrailshomestays.com",
        phoneNumber: "+84-149-4572",
        isVerified: true,
        rating: 3.9,
        reviewCount: 93,
        quote: "My home is your home in bali. I look forward to making your stay memorable and authentic.",
        stayType: "academic-homestay",
      }
,
      {
        name: "Dorothy Wang",
        background: "Retired schoolteacher passionate about sharing local traditions",
        maxGuests: 2,
        languages: ["English", "Arabic", "Spanish"],
        curfew: "13:00 AM",
        isPopular: true,
        guestPolicy: ["Not suitable for infants (under 2 years)", "Ideal for solo travelers", "No children under 12", "Suitable for digital nomads"],
        hostingStyle: "laid-back",
        houseRules: ["Lock the door when leaving the house", "Quiet hours after 10 PM", "Recycle according to local guidelines", "Wi-Fi password will be provided upon arrival", "No smoking indoors"],
        location: {
          city: "Bali",
          region: "Indonesia",
          country: "Indonesia",
          coordinates: { lat: 40.04901699298478, lng: 0.03528463824468281 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "dorothy.wang@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.7,
        reviewCount: 8,
        quote: "Life in bali has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "host-family-stay",
      },
      {
        name: "Adeline Graham",
        background: "Local musician involved in the cultural scene",
        maxGuests: 2,
        languages: ["English", "Spanish", "Italian"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "No parties or events", "Senior-friendly accommodations", "Suitable for digital nomads"],
        hostingStyle: "hands-on",
        houseRules: ["Please conserve water and electricity", "No smoking indoors", "Laundry available on weekends only", "Breakfast is self-serve between 7-9 AM", "Notify host if you'll be arriving after 10 PM", "Quiet hours after 10 PM"],
        location: {
          city: "Bali",
          region: "Indonesia",
          country: "Indonesia",
          coordinates: { lat: 40.06108890055772, lng: -0.025496027326246826 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "adeline.graham@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.9,
        reviewCount: 92,
        quote: "My home is your home in bali. I look forward to making your stay memorable and authentic.",
        stayType: "self-catering",
      },
      {
        name: "Grace Martin",
        background: "Language teacher who enjoys helping visitors learn the local tongue",
        maxGuests: 4,
        languages: ["English", "Spanish", "Arabic"],
        curfew: "14:00 AM",
        isPopular: true,
        guestPolicy: ["Smoking allowed in designated areas only", "Children welcome"],
        hostingStyle: "laid-back",
        houseRules: ["No food in the bedrooms", "Notify host if you'll be arriving after 10 PM", "Remove shoes when entering the home", "Wi-Fi password will be provided upon arrival", "No pets allowed", "Please clean up after yourself in common areas"],
        location: {
          city: "Bali",
          region: "Indonesia",
          country: "Indonesia",
          coordinates: { lat: 39.95948566097996, lng: 0.035851885592846106 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "grace.martin@paragontrailshomestays.com",
        phoneNumber: "+73-612-4444",
        isVerified: true,
        rating: 4.4,
        reviewCount: 96,
        quote: "Welcome to my bali home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "entire-home",
      }
,
      {
        name: "Savannah Wright",
        background: "Language teacher who enjoys helping visitors learn the local tongue",
        maxGuests: 1,
        languages: ["English", "Japanese", "Russian"],
        curfew: "13:00 AM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "Great for couples", "No parties or events", "Smoking allowed in designated areas only"],
        hostingStyle: "social",
        houseRules: ["No food in the bedrooms", "Laundry available on weekends only", "Breakfast is self-serve between 7-9 AM", "Quiet hours after 10 PM", "Pets welcome"],
        location: {
          city: "Bali",
          region: "Indonesia",
          country: "Indonesia",
          coordinates: { lat: 40.07962781953076, lng: 0.0849216478694726 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "savannah.wright@paragontrailshomestays.com",
        phoneNumber: "+39-907-5853",
        isVerified: true,
        rating: 3.5,
        reviewCount: 66,
        quote: "Staying with me means experiencing bali like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "self-catering",
      }
,
      {
        name: "Charlotte Graham",
        background: "Local musician involved in the cultural scene",
        maxGuests: 3,
        languages: ["English", "Spanish", "French"],
        curfew: "13:00 AM",
        isPopular: true,
        guestPolicy: ["Smoking allowed in designated areas only", "LGBTQ+ friendly", "No parties or events", "Great for couples"],
        hostingStyle: "hands-on",
        houseRules: ["No pets allowed", "Pets welcome", "Recycle according to local guidelines", "Remove shoes when entering the home", "No loud music after 9 PM"],
        location: {
          city: "Bali",
          region: "Indonesia",
          country: "Indonesia",
          coordinates: { lat: 40.06959638338129, lng: -0.010666408979933498 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "charlotte.graham@paragontrailshomestays.com",
        phoneNumber: "+78-211-9308",
        isVerified: false,
        rating: 4.9,
        reviewCount: 81,
        quote: "Life in bali has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "shared-room",
      },
      {
        name: "Sofia Carter",
        background: "Artist who loves sharing local cultural insights",
        maxGuests: 6,
        languages: ["English", "Japanese", "Spanish"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Ideal for solo travelers", "Family-friendly environment", "No parties or events"],
        hostingStyle: "family-oriented",
        houseRules: ["Kitchen closed after 8 PM", "Notify host if you'll be arriving after 10 PM", "Quiet hours after 10 PM", "No smoking indoors", "Remove shoes when entering the home"],
        location: {
          city: "Bali",
          region: "Indonesia",
          country: "Indonesia",
          coordinates: { lat: 40.095178544656775, lng: 0.06585029398317493 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "11:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "sofia.carter@paragontrailshomestays.com",
        phoneNumber: "+5-455-2229",
        isVerified: true,
        rating: 4.1,
        reviewCount: 66,
        quote: "Life in bali has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "pet-friendly-stay",
      }
,
      {
        name: "Patricia King",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 1,
        languages: ["English", "Japanese", "Italian"],
        curfew: "24:00 PM",
        isPopular: true,
        guestPolicy: ["Ideal for solo travelers", "Senior-friendly accommodations"],
        hostingStyle: "social",
        houseRules: ["Please clean up after yourself in common areas", "Remove shoes when entering the home", "No smoking indoors", "Breakfast is self-serve between 7-9 AM", "No outside guests without permission"],
        location: {
          city: "Bali",
          region: "Indonesia",
          country: "Indonesia",
          coordinates: { lat: 39.91803947455277, lng: 0.039427408945489045 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "patricia.king@paragontrailshomestays.com",
        phoneNumber: "+36-447-6605",
        isVerified: false,
        rating: 4.9,
        reviewCount: 40,
        quote: "Welcome to my bali home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "volunteer-stay",
      }

];
