// Homestay data for boston
// This file is auto-generated. Do not edit manually.

import { Host } from "@/lib/interfaces/people/homestay";

export const bostonHomestays: Host[] = [
      {
        name: "Isabella Kim",
        background: "Language teacher who enjoys helping visitors learn the local tongue",
        maxGuests: 4,
        languages: ["English", "Spanish", "Japanese", "German"],
        curfew: "21:00 PM",
        isPopular: true,
        guestPolicy: ["Suitable for business travelers", "Senior-friendly accommodations", "Family-friendly environment"],
        hostingStyle: "hands-on",
        houseRules: ["Please conserve water and electricity", "Laundry available on weekends only", "Wi-Fi password will be provided upon arrival", "Breakfast is self-serve between 7-9 AM", "No outside guests without permission", "No loud music after 9 PM"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 40.0209296596823, lng: -0.08589633866609839 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "isabella.kim@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.7,
        reviewCount: 38,
        quote: "Life in boston has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "urban-apartment-stay",
      },
      {
        name: "Andrew Baker",
        background: "Local musician involved in the cultural scene",
        maxGuests: 4,
        languages: ["English", "French", "Japanese"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Senior-friendly accommodations", "Smoking allowed in designated areas only"],
        hostingStyle: "laid-back",
        houseRules: ["Wi-Fi password will be provided upon arrival", "Remove shoes when entering the home", "No smoking indoors", "Notify host if you'll be arriving after 10 PM", "Respect shared spaces", "Laundry available on weekends only"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 39.97560814872375, lng: 0.007467185915153468 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "andrew.baker@paragontrailshomestays.com",
        phoneNumber: "+43-819-7784",
        isVerified: true,
        rating: 3.8,
        reviewCount: 60,
        quote: "I've lived in boston all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "academic-homestay",
      },
      {
        name: "Angela Palmer",
        background: "Local historian researching regional traditions",
        maxGuests: 4,
        languages: ["English", "Japanese", "Chinese"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Suitable for business travelers", "Suitable for digital nomads", "Not suitable for infants (under 2 years)"],
        hostingStyle: "private",
        houseRules: ["Lock the door when leaving the house", "Laundry available on weekends only", "Respect shared spaces", "Wi-Fi password will be provided upon arrival", "Please clean up after yourself in common areas", "Please conserve water and electricity"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 40.097306554627366, lng: -0.00517870019555669 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "angela.palmer@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.7,
        reviewCount: 92,
        quote: "My home is your home in boston. I look forward to making your stay memorable and authentic.",
        stayType: "language-immersion",
      }
,
      {
        name: "Albert Wilson",
        background: "Local historian researching regional traditions",
        maxGuests: 5,
        languages: ["English", "Russian", "Arabic"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["No parties or events", "Pet-friendly accommodation", "Suitable for business travelers", "Senior-friendly accommodations"],
        hostingStyle: "laid-back",
        houseRules: ["Remove shoes when entering the home", "Breakfast is self-serve between 7-9 AM", "Recycle according to local guidelines", "Quiet hours after 10 PM", "Please conserve water and electricity", "Wi-Fi password will be provided upon arrival"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 40.05709584135169, lng: -0.09300815220718608 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "11:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "albert.wilson@paragontrailshomestays.com",
        phoneNumber: "+19-671-5541",
        isVerified: true,
        rating: 4.1,
        reviewCount: 32,
        quote: "I've lived in boston all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "cottage-stay",
      },
      {
        name: "Thandiwe Lee",
        background: "Environmental activist working on local sustainability projects",
        maxGuests: 1,
        languages: ["English", "Spanish", "Chinese"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Smoking allowed in designated areas only", "Suitable for business travelers"],
        hostingStyle: "hands-on",
        houseRules: ["Respect shared spaces", "Lock the door when leaving the house", "No smoking indoors", "No pets allowed", "Pets welcome"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 40.06097268500593, lng: 0.006918071155622305 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "thandiwe.lee@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.9,
        reviewCount: 58,
        quote: "Welcome to my boston home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "culinary-homestay",
      }
,
      {
        name: "Ryan Montgomery",
        background: "Entrepreneur running a local business",
        maxGuests: 2,
        languages: ["English", "Russian", "French"],
        curfew: "22:00 PM",
        isPopular: true,
        guestPolicy: ["Family-friendly environment", "No children under 12", "No parties or events"],
        hostingStyle: "social",
        houseRules: ["No outside guests without permission", "Please clean up after yourself in common areas", "Laundry available on weekends only", "Recycle according to local guidelines"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 40.09710390023527, lng: -0.0005469012806633283 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "ryan.montgomery@paragontrailshomestays.com",
        phoneNumber: "+93-142-6865",
        isVerified: true,
        rating: 3.8,
        reviewCount: 69,
        quote: "Life in boston has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "entire-home",
      },
      {
        name: "Carol Wang",
        background: "Retired schoolteacher passionate about sharing local traditions",
        maxGuests: 1,
        languages: ["English", "Spanish", "Arabic"],
        curfew: "22:00 PM",
        isPopular: true,
        guestPolicy: ["Great for couples", "Senior-friendly accommodations", "Suitable for digital nomads"],
        hostingStyle: "family-oriented",
        houseRules: ["Please conserve water and electricity", "Laundry available on weekends only", "Recycle according to local guidelines", "Kitchen closed after 8 PM"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 40.077087538546394, lng: 0.08348457614636443 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "carol.wang@paragontrailshomestays.com",
        phoneNumber: "+64-467-10885",
        isVerified: true,
        rating: 4.5,
        reviewCount: 22,
        quote: "Welcome to my boston home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "art-or-craft-stay",
      },
      {
        name: "Barbara Khan",
        background: "Artist who loves sharing local cultural insights",
        maxGuests: 3,
        languages: ["English", "Japanese", "Spanish"],
        curfew: "22:00 PM",
        isPopular: false,
        guestPolicy: ["Pet-friendly accommodation", "Senior-friendly accommodations", "Not suitable for infants (under 2 years)"],
        hostingStyle: "family-oriented",
        houseRules: ["Kitchen closed after 8 PM", "Wi-Fi password will be provided upon arrival", "Quiet hours after 10 PM", "No food in the bedrooms", "Recycle according to local guidelines"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 39.94669133243469, lng: 0.06785721384121671 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "barbara.khan@paragontrailshomestays.com",
        phoneNumber: "+5-577-7004",
        isVerified: true,
        rating: 4.4,
        reviewCount: 18,
        quote: "I've lived in boston all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "art-or-craft-stay",
      }
,
      {
        name: "Lucas Gonzalez",
        background: "Environmental activist working on local sustainability projects",
        maxGuests: 6,
        languages: ["English", "Arabic", "Spanish", "Chinese"],
        curfew: "14:00 AM",
        isPopular: true,
        guestPolicy: ["Ideal for solo travelers", "Children welcome", "Senior-friendly accommodations", "No parties or events"],
        hostingStyle: "private",
        houseRules: ["Please conserve water and electricity", "Wi-Fi password will be provided upon arrival", "Please clean up after yourself in common areas"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 39.91699817039493, lng: -0.06925882083262112 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "lucas.gonzalez@paragontrailshomestays.com",
        phoneNumber: "+45-193-4845",
        isVerified: false,
        rating: 3.8,
        reviewCount: 18,
        quote: "My home is your home in boston. I look forward to making your stay memorable and authentic.",
        stayType: "academic-homestay",
      },
      {
        name: "Priya Ali",
        background: "Entrepreneur running a local business",
        maxGuests: 2,
        languages: ["English", "Japanese", "Arabic"],
        curfew: "13:00 AM",
        isPopular: true,
        guestPolicy: ["Accessible for guests with mobility issues", "Suitable for digital nomads", "Suitable for business travelers", "No parties or events"],
        hostingStyle: "social",
        houseRules: ["No pets allowed", "Breakfast is self-serve between 7-9 AM", "Pets welcome"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 39.98636513280239, lng: 0.08487985651180169 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "priya.ali@paragontrailshomestays.com",
        phoneNumber: "+9-189-2910",
        isVerified: true,
        rating: 4.1,
        reviewCount: 67,
        quote: "Life in boston has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "eco-stay",
      }
,
      {
        name: "Noah Parker",
        background: "Entrepreneur running a local business",
        maxGuests: 3,
        languages: ["English", "Russian", "Italian"],
        curfew: "22:00 PM",
        isPopular: false,
        guestPolicy: ["Accessible for guests with mobility issues", "Pet-friendly accommodation", "Ideal for solo travelers"],
        hostingStyle: "social",
        houseRules: ["Please conserve water and electricity", "No smoking indoors", "Kitchen closed after 8 PM", "Breakfast is self-serve between 7-9 AM"],
        location: {
          city: "Boston",
          region: "Massachusetts",
          country: "United States",
          coordinates: { lat: 39.92293068634332, lng: -0.039572529404964835 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "noah.parker@paragontrailshomestays.com",
        phoneNumber: "+26-412-3140",
        isVerified: true,
        rating: 4.9,
        reviewCount: 16,
        quote: "Staying with me means experiencing boston like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "cottage-stay",
      }

];
