import { Homestay } from "@/lib/interfaces/people/homestay";

export const buenos-airesHomestays: Homestay[] = [
  {
    hosts: [
      {
        name: "Diego da Costa",
        background: "Long-time resident and community organizer",
        maxGuests: 5,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "15:00 AM",
        isPopular: true,
        guestPolicy: ["Senior-friendly accommodations", "Family-friendly environment", "Smoking allowed in designated areas only", "Not suitable for infants (under 2 years)"],
        hostingStyle: "private",
        houseRules: ["Please conserve water and electricity", "No smoking indoors", "Remove shoes when entering the home"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 39.96093131575646, lng: 0.04179837867813613 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "11:00 AM",
        },
        email: "diego.da costa@example.com",
        phoneNumber: "+63-884-5064",
        isVerified: true,
        rating: 4.9,
        reviewCount: 17,
        quote: "My home is your home in buenos-aires. I look forward to making your stay memorable and authentic.",
        stayType: "farm-stay",
      },
      {
        name: "Benjamin Silva",
        background: "Long-time resident and community organizer",
        maxGuests: 4,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "14:00 AM",
        isPopular: true,
        guestPolicy: ["Family-friendly environment", "Suitable for digital nomads", "No children under 12", "Great for couples"],
        hostingStyle: "laid-back",
        houseRules: ["Recycle according to local guidelines", "Wi-Fi password will be provided upon arrival", "Lock the door when leaving the house", "Notify host if you'll be arriving after 10 PM"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 39.951603944417016, lng: -0.05513642914142536 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "benjamin.silva@example.com",
        phoneNumber: "+74-479-6917",
        isVerified: false,
        rating: 3.7,
        reviewCount: 21,
        quote: "Life in buenos-aires has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "pet-friendly-stay",
      },
      {
        name: "Ravi Taylor",
        background: "University professor with expertise in local culture",
        maxGuests: 4,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "13:00 AM",
        isPopular: true,
        guestPolicy: ["No parties or events", "Not suitable for infants (under 2 years)", "Senior-friendly accommodations", "Accessible for guests with mobility issues"],
        hostingStyle: "private",
        houseRules: ["Breakfast is self-serve between 7-9 AM", "Lock the door when leaving the house", "Kitchen closed after 8 PM", "Please conserve water and electricity"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 40.08027896561987, lng: -0.07861029408884557 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "ravi.taylor@example.com",
        phoneNumber: "+20-131-6488",
        isVerified: true,
        rating: 3.6,
        reviewCount: 58,
        quote: "I've lived in buenos-aires all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "self-catering",
      }
    ]
  },
  {
    hosts: [
      {
        name: "Benjamin Rodriguez",
        background: "University professor with expertise in local culture",
        maxGuests: 5,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["Suitable for business travelers", "LGBTQ+ friendly", "Family-friendly environment"],
        hostingStyle: "private",
        houseRules: ["Please conserve water and electricity", "No loud music after 9 PM", "No outside guests without permission"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 40.05228959273591, lng: 0.04521113141774538 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "benjamin.rodriguez@example.com",
        phoneNumber: "+11-740-9036",
        isVerified: true,
        rating: 4.8,
        reviewCount: 50,
        quote: "I've lived in buenos-aires all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "pet-friendly-stay",
      },
      {
        name: "Priya Jackson",
        background: "University professor with expertise in local culture",
        maxGuests: 2,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "Suitable for business travelers"],
        hostingStyle: "family-oriented",
        houseRules: ["No loud music after 9 PM", "Wi-Fi password will be provided upon arrival", "Laundry available on weekends only", "Kitchen closed after 8 PM", "Notify host if you'll be arriving after 10 PM", "Lock the door when leaving the house"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 39.99745388386395, lng: 0.04264515921234255 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "priya.jackson@example.com",
        phoneNumber: "+52-604-10549",
        isVerified: false,
        rating: 4.3,
        reviewCount: 74,
        quote: "Staying with me means experiencing buenos-aires like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "private-room-in-home",
      },
      {
        name: "Elijah Lopez",
        background: "Artist who loves sharing local cultural insights",
        maxGuests: 2,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Suitable for digital nomads", "Ideal for solo travelers"],
        hostingStyle: "family-oriented",
        houseRules: ["Notify host if you'll be arriving after 10 PM", "Recycle according to local guidelines", "Lock the door when leaving the house", "No food in the bedrooms", "Breakfast is self-serve between 7-9 AM", "Laundry available on weekends only"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 39.9412321046323, lng: 0.09047919623453105 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "elijah.lopez@example.com",
        phoneNumber: "+3-476-9273",
        isVerified: true,
        rating: 4.2,
        reviewCount: 37,
        quote: "Welcome to my buenos-aires home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "language-immersion",
      }
    ]
  },
  {
    hosts: [
      {
        name: "Sophia da Costa",
        background: "Artist who loves sharing local cultural insights",
        maxGuests: 1,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["Smoking allowed in designated areas only", "Perfect for long-term stays"],
        hostingStyle: "social",
        houseRules: ["Pets welcome", "Kitchen closed after 8 PM", "Please clean up after yourself in common areas", "Lock the door when leaving the house", "Breakfast is self-serve between 7-9 AM"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 39.963292448784834, lng: -0.03822028062802745 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "sophia.da costa@example.com",
        isVerified: true,
        rating: 3.6,
        reviewCount: 82,
        quote: "Welcome to my buenos-aires home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "volunteer-stay",
      },
      {
        name: "Elijah Davis",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 4,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "21:00 PM",
        isPopular: true,
        guestPolicy: ["Senior-friendly accommodations", "Accessible for guests with mobility issues", "Ideal for solo travelers", "No children under 12"],
        hostingStyle: "hands-on",
        houseRules: ["No pets allowed", "Pets welcome", "No smoking indoors"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 40.058361506245255, lng: -0.07660784676868655 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "elijah.davis@example.com",
        isVerified: true,
        rating: 4.9,
        reviewCount: 58,
        quote: "Life in buenos-aires has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "spiritual-or-wellness-retreat",
      },
      {
        name: "Ravi Singh",
        background: "Entrepreneur running a local business",
        maxGuests: 3,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Suitable for business travelers", "Pet-friendly accommodation"],
        hostingStyle: "social",
        houseRules: ["No loud music after 9 PM", "No pets allowed", "No smoking indoors"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 40.03286825140735, lng: -0.055029411228889824 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "ravi.singh@example.com",
        phoneNumber: "+76-753-4649",
        isVerified: true,
        rating: 4.8,
        reviewCount: 8,
        quote: "I've lived in buenos-aires all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "host-family-stay",
      }
    ]
  },
  {
    hosts: [
      {
        name: "Mei Wang",
        background: "Local historian researching regional traditions",
        maxGuests: 3,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "22:00 PM",
        isPopular: true,
        guestPolicy: ["Smoking allowed in designated areas only", "Pet-friendly accommodation", "Not suitable for infants (under 2 years)", "Great for couples"],
        hostingStyle: "laid-back",
        houseRules: ["Pets welcome", "Laundry available on weekends only", "Recycle according to local guidelines", "Breakfast is self-serve between 7-9 AM", "Remove shoes when entering the home"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 39.97022823224307, lng: -0.057609164161354844 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "mei.wang@example.com",
        phoneNumber: "+32-109-7398",
        isVerified: true,
        rating: 4.5,
        reviewCount: 94,
        quote: "My home is your home in buenos-aires. I look forward to making your stay memorable and authentic.",
        stayType: "farm-stay",
      },
      {
        name: "Elena da Costa",
        background: "Local historian researching regional traditions",
        maxGuests: 6,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "13:00 AM",
        isPopular: true,
        guestPolicy: ["Not suitable for infants (under 2 years)", "Senior-friendly accommodations", "No children under 12", "Family-friendly environment"],
        hostingStyle: "hands-on",
        houseRules: ["No pets allowed", "Lock the door when leaving the house", "Wi-Fi password will be provided upon arrival", "Notify host if you'll be arriving after 10 PM", "Please conserve water and electricity", "Remove shoes when entering the home"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 39.900358450909465, lng: 0.004667455976424956 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "11:00 AM",
        },
        email: "elena.da costa@example.com",
        phoneNumber: "+28-1088-6054",
        isVerified: true,
        rating: 3.6,
        reviewCount: 32,
        quote: "My home is your home in buenos-aires. I look forward to making your stay memorable and authentic.",
        stayType: "pet-friendly-stay",
      },
      {
        name: "Ana Moore",
        background: "Digital nomad who settled in the city after falling in love with it",
        maxGuests: 5,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Suitable for business travelers", "Suitable for digital nomads"],
        hostingStyle: "hands-on",
        houseRules: ["Respect shared spaces", "Breakfast is self-serve between 7-9 AM", "Notify host if you'll be arriving after 10 PM", "Lock the door when leaving the house", "Laundry available on weekends only"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 40.000422844821706, lng: 0.09138620134423445 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "ana.moore@example.com",
        isVerified: true,
        rating: 4.8,
        reviewCount: 41,
        quote: "I've lived in buenos-aires all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "language-immersion",
      }
    ]
  },
  {
    hosts: [
      {
        name: "Yuki Martin",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 3,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Smoking allowed in designated areas only", "Children welcome", "Perfect for long-term stays"],
        hostingStyle: "private",
        houseRules: ["Notify host if you'll be arriving after 10 PM", "Lock the door when leaving the house", "Breakfast is self-serve between 7-9 AM", "Remove shoes when entering the home"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 40.008220448332395, lng: -0.037399023690180444 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "yuki.martin@example.com",
        phoneNumber: "+53-261-7610",
        isVerified: true,
        rating: 4.5,
        reviewCount: 65,
        quote: "I've lived in buenos-aires all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "volunteer-stay",
      },
      {
        name: "Noah Moore",
        background: "Language teacher who enjoys helping visitors learn the local tongue",
        maxGuests: 1,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "13:00 AM",
        isPopular: false,
        guestPolicy: ["Suitable for digital nomads", "Pet-friendly accommodation"],
        hostingStyle: "laid-back",
        houseRules: ["Lock the door when leaving the house", "Quiet hours after 10 PM", "Kitchen closed after 8 PM", "Remove shoes when entering the home", "Please conserve water and electricity"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 39.93691548780002, lng: 0.0014001904419027184 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "noah.moore@example.com",
        phoneNumber: "+5-226-9419",
        isVerified: true,
        rating: 3.8,
        reviewCount: 73,
        quote: "I've lived in buenos-aires all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "eco-stay",
      },
      {
        name: "Layla Martinez",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 2,
        languages: ["Indonesian", "Hindi", "Bengali", "Japanese", "English"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Perfect for long-term stays", "Great for couples"],
        hostingStyle: "social",
        houseRules: ["No smoking indoors", "Please conserve water and electricity", "Laundry available on weekends only", "No pets allowed", "Respect shared spaces"],
        location: {
          city: "buenos-aires",
          country: "undefined",
          coordinates: { lat: 40.01789846534405, lng: 0.06425746450138284 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "11:00 AM",
        },
        email: "layla.martinez@example.com",
        phoneNumber: "+92-849-9897",
        isVerified: true,
        rating: 3.6,
        reviewCount: 15,
        quote: "Welcome to my buenos-aires home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "eco-stay",
      }
    ]
  }
];
