// Homestay data for copenhagen
// This file is auto-generated. Do not edit manually.

import { Host } from "@/lib/interfaces/people/homestay";

export const copenhagenHomestays: Host[] = [
      {
        name: "Aria Gonzalez",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 4,
        languages: ["English", "Italian", "Danish", "Norwegian"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "Accessible for guests with mobility issues", "No children under 12"],
        hostingStyle: "social",
        houseRules: ["Laundry available on weekends only", "No pets allowed", "Notify host if you'll be arriving after 10 PM"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 39.9765437916637, lng: 0.011225740195229997 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "aria.gonzalez@paragontrailshomestays.com",
        phoneNumber: "+91-942-7491",
        isVerified: true,
        rating: 4.9,
        reviewCount: 103,
        quote: "I've lived in copenhagen all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "entire-home",
      },
      {
        name: "Willie Wallace",
        background: "Retired schoolteacher passionate about sharing local traditions",
        maxGuests: 4,
        languages: ["English", "Swedish", "Italian"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["Senior-friendly accommodations", "Perfect for long-term stays", "Suitable for business travelers"],
        hostingStyle: "private",
        houseRules: ["Wi-Fi password will be provided upon arrival", "Recycle according to local guidelines", "Notify host if you'll be arriving after 10 PM"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 39.987733747841624, lng: -0.08931824779527138 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "willie.wallace@paragontrailshomestays.com",
        phoneNumber: "+4-1015-8868",
        isVerified: true,
        rating: 3.9,
        reviewCount: 79,
        quote: "My home is your home in copenhagen. I look forward to making your stay memorable and authentic.",
        stayType: "art-or-craft-stay",
      },
      {
        name: "Mia Dixon",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 3,
        languages: ["English", "Norwegian", "French"],
        curfew: "13:00 AM",
        isPopular: false,
        guestPolicy: ["Suitable for business travelers", "Pet-friendly accommodation", "Smoking allowed in designated areas only", "Suitable for digital nomads"],
        hostingStyle: "laid-back",
        houseRules: ["Breakfast is self-serve between 7-9 AM", "Wi-Fi password will be provided upon arrival", "No pets allowed", "No smoking indoors", "Notify host if you'll be arriving after 10 PM", "Laundry available on weekends only"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 40.05793010909341, lng: -0.05485277359465917 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "mia.dixon@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.5,
        reviewCount: 88,
        quote: "My home is your home in copenhagen. I look forward to making your stay memorable and authentic.",
        stayType: "language-immersion",
      }
,
      {
        name: "Alexander Day",
        background: "Yoga instructor offering morning sessions",
        maxGuests: 6,
        languages: ["English", "French", "Spanish"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["Pet-friendly accommodation", "Suitable for business travelers", "Perfect for long-term stays"],
        hostingStyle: "hands-on",
        houseRules: ["Quiet hours after 10 PM", "Please clean up after yourself in common areas", "No outside guests without permission", "No smoking indoors"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 39.965095852402, lng: -0.004723562468516157 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "alexander.day@paragontrailshomestays.com",
        phoneNumber: "+60-240-2544",
        isVerified: true,
        rating: 4.6,
        reviewCount: 14,
        quote: "Life in copenhagen has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "eco-stay",
      },
      {
        name: "Terry Harris",
        background: "Retired schoolteacher passionate about sharing local traditions",
        maxGuests: 5,
        languages: ["English", "Greek", "Italian", "Portuguese"],
        curfew: "23:00 PM",
        isPopular: true,
        guestPolicy: ["Great for couples", "Perfect for long-term stays"],
        hostingStyle: "hands-on",
        houseRules: ["No smoking indoors", "Remove shoes when entering the home", "Laundry available on weekends only", "Quiet hours after 10 PM", "No pets allowed", "Please clean up after yourself in common areas"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 40.02057741980039, lng: -0.013645002769462525 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "11:00 AM",
        },
        email: "terry.harris@paragontrailshomestays.com",
        phoneNumber: "+49-816-10007",
        isVerified: false,
        rating: 4.4,
        reviewCount: 34,
        quote: "Life in copenhagen has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "eco-stay",
      }
,
      {
        name: "Skylar Suzuki",
        background: "Environmental activist working on local sustainability projects",
        maxGuests: 6,
        languages: ["English", "Swedish", "Russian", "Finnish"],
        curfew: "22:00 PM",
        isPopular: true,
        guestPolicy: ["Smoking allowed in designated areas only", "Senior-friendly accommodations", "No parties or events", "Great for couples"],
        hostingStyle: "family-oriented",
        houseRules: ["No smoking indoors", "Notify host if you'll be arriving after 10 PM", "Please clean up after yourself in common areas", "Respect shared spaces", "Breakfast is self-serve between 7-9 AM", "Recycle according to local guidelines"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 39.98841862121594, lng: 0.03927133203361324 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "skylar.suzuki@paragontrailshomestays.com",
        phoneNumber: "+76-338-5368",
        isVerified: true,
        rating: 3.6,
        reviewCount: 98,
        quote: "I've lived in copenhagen all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "traditional-homestay",
      },
      {
        name: "Kenneth Chen",
        background: "Local musician involved in the cultural scene",
        maxGuests: 5,
        languages: ["English", "Norwegian", "Italian"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["No parties or events", "Ideal for solo travelers", "Smoking allowed in designated areas only", "Children welcome"],
        hostingStyle: "private",
        houseRules: ["Please conserve water and electricity", "Lock the door when leaving the house", "No food in the bedrooms", "Wi-Fi password will be provided upon arrival", "Quiet hours after 10 PM", "No outside guests without permission"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 39.90146675112304, lng: 0.03608795951532953 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "11:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "kenneth.chen@paragontrailshomestays.com",
        phoneNumber: "+22-640-4079",
        isVerified: false,
        rating: 4.3,
        reviewCount: 6,
        quote: "Staying with me means experiencing copenhagen like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "heritage-stay",
      }
,
      {
        name: "Lucas Gonzalez",
        background: "Local musician involved in the cultural scene",
        maxGuests: 5,
        languages: ["English", "Dutch", "Danish"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Not suitable for infants (under 2 years)", "No children under 12"],
        hostingStyle: "family-oriented",
        houseRules: ["Wi-Fi password will be provided upon arrival", "Kitchen closed after 8 PM", "Notify host if you'll be arriving after 10 PM", "Recycle according to local guidelines", "Laundry available on weekends only", "Quiet hours after 10 PM"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 40.066520024984165, lng: 0.09076754004987558 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "lucas.gonzalez@paragontrailshomestays.com",
        phoneNumber: "+65-458-2673",
        isVerified: true,
        rating: 3.7,
        reviewCount: 58,
        quote: "I've lived in copenhagen all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "spiritual-or-wellness-retreat",
      },
      {
        name: "Katherine Fletcher",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 2,
        languages: ["English", "French", "Spanish"],
        curfew: "15:00 AM",
        isPopular: true,
        guestPolicy: ["Children welcome", "Accessible for guests with mobility issues"],
        hostingStyle: "social",
        houseRules: ["No outside guests without permission", "Kitchen closed after 8 PM", "Please clean up after yourself in common areas", "Remove shoes when entering the home"],
        location: {
          city: "Copenhagen",
          region: "Northern Europe",
          country: "Denmark",
          coordinates: { lat: 40.09415258402423, lng: 0.00012769149836215632 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "katherine.fletcher@paragontrailshomestays.com",
        phoneNumber: "+93-338-2669",
        isVerified: false,
        rating: 3.9,
        reviewCount: 95,
        quote: "Life in copenhagen has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "language-immersion",
      }

];
