// Homestay data for cozumel
// This file is auto-generated. Do not edit manually.

import { Host } from "@/lib/interfaces/people/homestay";

export const cozumelHomestays: Host[] = [
      {
        name: "Diego Campbell",
        background: "Artist who loves sharing local cultural insights",
        maxGuests: 5,
        languages: ["English", "Arabic", "French"],
        curfew: "24:00 PM",
        isPopular: true,
        guestPolicy: ["Suitable for business travelers", "Perfect for long-term stays", "Family-friendly environment", "Accessible for guests with mobility issues"],
        hostingStyle: "private",
        houseRules: ["No pets allowed", "Respect shared spaces", "Laundry available on weekends only", "Quiet hours after 10 PM", "No food in the bedrooms", "Lock the door when leaving the house"],
        location: {
          city: "Cozumel",
          region: "Mexico",
          country: "Mexico",
          coordinates: { lat: 39.92713911846518, lng: 0.04162689354950952 },
        },
        availability: {
          checkInTime: "15:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "diego.campbell@paragontrailshomestays.com",
        phoneNumber: "+90-513-9262",
        isVerified: true,
        rating: 4.6,
        reviewCount: 100,
        quote: "Life in cozumel has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "guest-suite",
      },
      {
        name: "Antonio King",
        background: "Yoga instructor offering morning sessions",
        maxGuests: 6,
        languages: ["English", "French", "Japanese"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Suitable for business travelers", "Perfect for long-term stays"],
        hostingStyle: "family-oriented",
        houseRules: ["Lock the door when leaving the house", "Kitchen closed after 8 PM", "Please conserve water and electricity", "Remove shoes when entering the home"],
        location: {
          city: "Cozumel",
          region: "Mexico",
          country: "Mexico",
          coordinates: { lat: 39.91389125790378, lng: 0.07016555448229306 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "antonio.king@paragontrailshomestays.com",
        phoneNumber: "+29-238-2525",
        isVerified: true,
        rating: 4.2,
        reviewCount: 84,
        quote: "Life in cozumel has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "villa-stay",
      }
,
      {
        name: "Vincent Crawford",
        background: "Entrepreneur running a local business",
        maxGuests: 4,
        languages: ["English", "Arabic", "German"],
        curfew: "24:00 PM",
        isPopular: true,
        guestPolicy: ["Suitable for digital nomads", "Pet-friendly accommodation"],
        hostingStyle: "social",
        houseRules: ["Remove shoes when entering the home", "Kitchen closed after 8 PM", "No pets allowed", "No smoking indoors", "Please conserve water and electricity"],
        location: {
          city: "Cozumel",
          region: "Mexico",
          country: "Mexico",
          coordinates: { lat: 40.07627865161879, lng: 0.028239577951546135 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "vincent.crawford@paragontrailshomestays.com",
        phoneNumber: "+13-495-7438",
        isVerified: true,
        rating: 4,
        reviewCount: 37,
        quote: "I've lived in cozumel all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "villa-stay",
      },
      {
        name: "Thandiwe Douglas",
        background: "Entrepreneur running a local business",
        maxGuests: 4,
        languages: ["English", "German", "Russian"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Suitable for digital nomads", "LGBTQ+ friendly", "No parties or events"],
        hostingStyle: "laid-back",
        houseRules: ["Recycle according to local guidelines", "Please clean up after yourself in common areas", "No food in the bedrooms", "Remove shoes when entering the home", "No loud music after 9 PM"],
        location: {
          city: "Cozumel",
          region: "Mexico",
          country: "Mexico",
          coordinates: { lat: 39.92190526750827, lng: -0.002206290020104834 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "thandiwe.douglas@paragontrailshomestays.com",
        phoneNumber: "+56-884-4978",
        isVerified: false,
        rating: 3.8,
        reviewCount: 101,
        quote: "I've lived in cozumel all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "self-catering",
      }
,
      {
        name: "Matthew West",
        background: "Long-time resident and community organizer",
        maxGuests: 4,
        languages: ["English", "German", "French"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Senior-friendly accommodations", "Not suitable for infants (under 2 years)", "Ideal for solo travelers", "Perfect for long-term stays"],
        hostingStyle: "private",
        houseRules: ["Remove shoes when entering the home", "No smoking indoors", "Quiet hours after 10 PM", "No outside guests without permission", "Notify host if you'll be arriving after 10 PM", "Please conserve water and electricity"],
        location: {
          city: "Cozumel",
          region: "Mexico",
          country: "Mexico",
          coordinates: { lat: 40.010357362849625, lng: 0.06961942167299756 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "matthew.west@paragontrailshomestays.com",
        phoneNumber: "+39-181-6880",
        isVerified: true,
        rating: 3.7,
        reviewCount: 59,
        quote: "Welcome to my cozumel home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "private-room-in-home",
      },
      {
        name: "Maya Anderson",
        background: "Entrepreneur running a local business",
        maxGuests: 6,
        languages: ["English", "Italian", "Russian"],
        curfew: "22:00 PM",
        isPopular: false,
        guestPolicy: ["Smoking allowed in designated areas only", "Suitable for digital nomads", "Family-friendly environment", "Pet-friendly accommodation"],
        hostingStyle: "laid-back",
        houseRules: ["No food in the bedrooms", "Remove shoes when entering the home", "No loud music after 9 PM", "Please clean up after yourself in common areas", "No outside guests without permission"],
        location: {
          city: "Cozumel",
          region: "Mexico",
          country: "Mexico",
          coordinates: { lat: 39.96540624439148, lng: 0.08080521966478524 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "maya.anderson@paragontrailshomestays.com",
        isVerified: true,
        rating: 4,
        reviewCount: 103,
        quote: "Life in cozumel has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "private-room-in-home",
      }

];
