// Homestay data for fort-lauderdale
// This file is auto-generated. Do not edit manually.

import { Host } from "@/lib/interfaces/people/homestay";

export const fortLauderdaleHomestays: Host[] = [
      {
        name: "Kennedy Holloway",
        background: "Yoga instructor offering morning sessions",
        maxGuests: 6,
        languages: ["English", "Quechua", "Aymara", "French"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["Great for couples", "No parties or events"],
        hostingStyle: "laid-back",
        houseRules: ["No smoking indoors", "No outside guests without permission", "Lock the door when leaving the house", "Breakfast is self-serve between 7-9 AM"],
        location: {
          city: "Fort Lauderdale",
          region: "Caribbean",
          country: "United States",
          coordinates: { lat: 40.03251678118707, lng: -0.010552515084140526 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "kennedy.holloway@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.4,
        reviewCount: 75,
        quote: "Welcome to my fort-lauderdale home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "entire-home",
      }
,
      {
        name: "Emily Brooks",
        background: "Digital nomad who settled in the city after falling in love with it",
        maxGuests: 6,
        languages: ["English", "Haitian", "Portuguese"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["Children welcome", "Family-friendly environment"],
        hostingStyle: "social",
        houseRules: ["Kitchen closed after 8 PM", "Respect shared spaces", "No loud music after 9 PM", "Lock the door when leaving the house", "No smoking indoors", "Pets welcome"],
        location: {
          city: "Fort Lauderdale",
          region: "Caribbean",
          country: "United States",
          coordinates: { lat: 39.94209653200588, lng: 0.029191260844940586 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "emily.brooks@paragontrailshomestays.com",
        phoneNumber: "+87-692-1561",
        isVerified: true,
        rating: 4.2,
        reviewCount: 14,
        quote: "Staying with me means experiencing fort-lauderdale like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "host-family-stay",
      }
,
      {
        name: "Audrey Miller",
        background: "Yoga instructor offering morning sessions",
        maxGuests: 6,
        languages: ["English", "Portuguese", "Spanish"],
        curfew: "21:00 PM",
        isPopular: true,
        guestPolicy: ["Senior-friendly accommodations", "Family-friendly environment", "Suitable for digital nomads", "Accessible for guests with mobility issues"],
        hostingStyle: "social",
        houseRules: ["Please clean up after yourself in common areas", "Quiet hours after 10 PM", "No pets allowed"],
        location: {
          city: "Fort Lauderdale",
          region: "Caribbean",
          country: "United States",
          coordinates: { lat: 40.04728207035353, lng: 0.04133026165002568 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "audrey.miller@paragontrailshomestays.com",
        phoneNumber: "+35-758-9648",
        isVerified: true,
        rating: 3.6,
        reviewCount: 98,
        quote: "Welcome to my fort-lauderdale home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "bed-and-breakfast",
      },
      {
        name: "Aisha Murray",
        background: "Local historian researching regional traditions",
        maxGuests: 6,
        languages: ["English", "French", "Haitian"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "Pet-friendly accommodation", "Great for couples", "Accessible for guests with mobility issues"],
        hostingStyle: "laid-back",
        houseRules: ["No outside guests without permission", "Pets welcome", "No loud music after 9 PM", "No smoking indoors"],
        location: {
          city: "Fort Lauderdale",
          region: "Caribbean",
          country: "United States",
          coordinates: { lat: 39.96184268329128, lng: -0.03052753351577496 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "aisha.murray@paragontrailshomestays.com",
        phoneNumber: "+15-175-7948",
        isVerified: true,
        rating: 4,
        reviewCount: 94,
        quote: "Staying with me means experiencing fort-lauderdale like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "heritage-stay",
      }
,
      {
        name: "Oliver Young",
        background: "University professor with expertise in local culture",
        maxGuests: 5,
        languages: ["English", "French", "Guarani"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Suitable for business travelers", "Perfect for long-term stays", "Great for couples"],
        hostingStyle: "family-oriented",
        houseRules: ["No outside guests without permission", "Quiet hours after 10 PM", "Remove shoes when entering the home", "Laundry available on weekends only", "Pets welcome", "Respect shared spaces"],
        location: {
          city: "Fort Lauderdale",
          region: "Caribbean",
          country: "United States",
          coordinates: { lat: 40.07230147127925, lng: 0.05522585734227109 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "oliver.young@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.3,
        reviewCount: 101,
        quote: "Staying with me means experiencing fort-lauderdale like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "spiritual-or-wellness-retreat",
      },
      {
        name: "Lerato Dixon",
        background: "Retired schoolteacher passionate about sharing local traditions",
        maxGuests: 5,
        languages: ["English", "Aymara", "French", "Guarani"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Pet-friendly accommodation", "Suitable for business travelers", "Not suitable for infants (under 2 years)"],
        hostingStyle: "laid-back",
        houseRules: ["Kitchen closed after 8 PM", "Please conserve water and electricity", "Breakfast is self-serve between 7-9 AM", "Quiet hours after 10 PM"],
        location: {
          city: "Fort Lauderdale",
          region: "Caribbean",
          country: "United States",
          coordinates: { lat: 40.09103985928021, lng: -0.0043249339584368884 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "lerato.dixon@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.5,
        reviewCount: 101,
        quote: "Staying with me means experiencing fort-lauderdale like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "urban-apartment-stay",
      },
      {
        name: "Christine Dixon",
        background: "University professor with expertise in local culture",
        maxGuests: 2,
        languages: ["English", "Haitian", "French", "Guarani"],
        curfew: "21:00 PM",
        isPopular: false,
        guestPolicy: ["Great for couples", "Accessible for guests with mobility issues", "Suitable for digital nomads", "Perfect for long-term stays"],
        hostingStyle: "family-oriented",
        houseRules: ["No pets allowed", "Kitchen closed after 8 PM", "No loud music after 9 PM", "Laundry available on weekends only"],
        location: {
          city: "Fort Lauderdale",
          region: "Caribbean",
          country: "United States",
          coordinates: { lat: 39.97120671865924, lng: 0.013068111811208191 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "11:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "christine.dixon@paragontrailshomestays.com",
        phoneNumber: "+45-113-2732",
        isVerified: true,
        rating: 4.5,
        reviewCount: 76,
        quote: "Life in fort-lauderdale has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "urban-apartment-stay",
      }

];
