// Homestay data for london
// This file is auto-generated. Do not edit manually.

import { Host } from "@/lib/interfaces/people/homestay";

export const londonHomestays: Host[] = [
      {
        name: "Jacob Rodriguez",
        background: "Local historian researching regional traditions",
        maxGuests: 1,
        languages: ["English", "Chinese", "Arabic"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["No parties or events", "Smoking allowed in designated areas only"],
        hostingStyle: "social",
        houseRules: ["Kitchen closed after 8 PM", "Please clean up after yourself in common areas", "No pets allowed", "Lock the door when leaving the house", "No food in the bedrooms"],
        location: {
          city: "London",
          region: "England",
          country: "United Kingdom",
          coordinates: { lat: 40.06345483494203, lng: -0.08218198175292996 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "jacob.rodriguez@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.8,
        reviewCount: 25,
        quote: "My home is your home in london. I look forward to making your stay memorable and authentic.",
        stayType: "bed-and-breakfast",
      },
      {
        name: "Wei Russell",
        background: "University professor with expertise in local culture",
        maxGuests: 2,
        languages: ["English", "German", "Chinese", "French"],
        curfew: "21:00 PM",
        isPopular: false,
        guestPolicy: ["No children under 12", "Family-friendly environment", "Perfect for long-term stays"],
        hostingStyle: "private",
        houseRules: ["Laundry available on weekends only", "Recycle according to local guidelines", "Kitchen closed after 8 PM", "Remove shoes when entering the home", "No smoking indoors"],
        location: {
          city: "London",
          region: "England",
          country: "United Kingdom",
          coordinates: { lat: 40.01575991319785, lng: -0.048959437021912106 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "11:00 AM",
        },
        email: "wei.russell@paragontrailshomestays.com",
        phoneNumber: "+15-948-10495",
        isVerified: true,
        rating: 4.5,
        reviewCount: 43,
        quote: "Welcome to my london home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "shared-room",
      },
      {
        name: "Nora Taylor",
        background: "Local historian researching regional traditions",
        maxGuests: 5,
        languages: ["English", "Russian", "Portuguese", "Arabic"],
        curfew: "21:00 PM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "Senior-friendly accommodations", "Accessible for guests with mobility issues", "Suitable for business travelers"],
        hostingStyle: "family-oriented",
        houseRules: ["Recycle according to local guidelines", "Laundry available on weekends only", "Respect shared spaces", "Kitchen closed after 8 PM", "Notify host if you'll be arriving after 10 PM"],
        location: {
          city: "London",
          region: "England",
          country: "United Kingdom",
          coordinates: { lat: 39.95221695133881, lng: 0.0949754663274141 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "nora.taylor@paragontrailshomestays.com",
        phoneNumber: "+81-359-8966",
        isVerified: true,
        rating: 3.7,
        reviewCount: 31,
        quote: "Welcome to my london home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "host-family-stay",
      }
,
      {
        name: "Ralph Foster",
        background: "Local musician involved in the cultural scene",
        maxGuests: 6,
        languages: ["English", "Russian", "Arabic"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Not suitable for infants (under 2 years)", "Family-friendly environment"],
        hostingStyle: "hands-on",
        houseRules: ["Recycle according to local guidelines", "No pets allowed", "Wi-Fi password will be provided upon arrival"],
        location: {
          city: "London",
          region: "England",
          country: "United Kingdom",
          coordinates: { lat: 40.07716218902663, lng: 0.02271604844496733 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "ralph.foster@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.8,
        reviewCount: 6,
        quote: "I've lived in london all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "volunteer-stay",
      }
,
      {
        name: "Betty Gardner",
        background: "Local musician involved in the cultural scene",
        maxGuests: 6,
        languages: ["English", "French", "Portuguese"],
        curfew: "21:00 PM",
        isPopular: false,
        guestPolicy: ["Children welcome", "Ideal for solo travelers", "Accessible for guests with mobility issues"],
        hostingStyle: "private",
        houseRules: ["Please clean up after yourself in common areas", "No loud music after 9 PM", "No pets allowed", "No food in the bedrooms", "Pets welcome", "Please conserve water and electricity"],
        location: {
          city: "London",
          region: "England",
          country: "United Kingdom",
          coordinates: { lat: 40.01896305762228, lng: -0.06472638391594093 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "betty.gardner@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.5,
        reviewCount: 22,
        quote: "Life in london has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "host-family-stay",
      },
      {
        name: "Samantha Russell",
        background: "Yoga instructor offering morning sessions",
        maxGuests: 6,
        languages: ["English", "Chinese", "Portuguese", "German"],
        curfew: "13:00 AM",
        isPopular: false,
        guestPolicy: ["Pet-friendly accommodation", "No parties or events"],
        hostingStyle: "laid-back",
        houseRules: ["No outside guests without permission", "Recycle according to local guidelines", "Remove shoes when entering the home"],
        location: {
          city: "London",
          region: "England",
          country: "United Kingdom",
          coordinates: { lat: 39.9288498573121, lng: -0.048566313475940516 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "samantha.russell@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.6,
        reviewCount: 5,
        quote: "Life in london has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "heritage-stay",
      },
      {
        name: "Samantha Gibson",
        background: "Artist who loves sharing local cultural insights",
        maxGuests: 1,
        languages: ["English", "French", "Spanish"],
        curfew: "23:00 PM",
        isPopular: true,
        guestPolicy: ["Children welcome", "Suitable for business travelers", "Smoking allowed in designated areas only"],
        hostingStyle: "family-oriented",
        houseRules: ["No pets allowed", "Kitchen closed after 8 PM", "Breakfast is self-serve between 7-9 AM"],
        location: {
          city: "London",
          region: "England",
          country: "United Kingdom",
          coordinates: { lat: 40.06787486928543, lng: -0.09631962226901969 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "11:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "samantha.gibson@paragontrailshomestays.com",
        phoneNumber: "+21-1078-4409",
        isVerified: true,
        rating: 3.6,
        reviewCount: 82,
        quote: "My home is your home in london. I look forward to making your stay memorable and authentic.",
        stayType: "entire-home",
      }

];
