// Homestay data for los-angeles
// This file is auto-generated. Do not edit manually.

// Genderated on: 2025-06-08T04:09:39.253Z

// City: los-angeles
// Region: California
// Country: United States

import { Host } from "@/lib/interfaces/people/homestay";

export const losAngelesHomestays: Host[] = [
      {
        name: "Kyle Hunter",
        background: "Local historian researching regional traditions",
        maxGuests: 4,
        languages: ["English", "Spanish", "French"],
        curfew: "21:00 PM",
        isPopular: true,
        guestPolicy: ["Senior-friendly accommodations", "LGBTQ+ friendly", "Perfect for long-term stays"],
        hostingStyle: "private",
        houseRules: ["Kitchen closed after 8 PM", "No loud music after 9 PM", "Quiet hours after 10 PM"],
        location: {
          city: "Los Angeles",
          region: "California",
          country: "United States",
          coordinates: { lat: 40.062871590928175, lng: 0.0965115032964754 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "kyle.hunter@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.5,
        reviewCount: 35,
        quote: "I've lived in los-angeles all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "cottage-stay",
      },
      {
        name: "Elizabeth Clark",
        background: "Long-time resident and community organizer",
        maxGuests: 1,
        languages: ["English", "Japanese", "French"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["No children under 12", "Perfect for long-term stays"],
        hostingStyle: "social",
        houseRules: ["Wi-Fi password will be provided upon arrival", "No pets allowed", "Recycle according to local guidelines", "No smoking indoors", "Pets welcome", "Please conserve water and electricity"],
        location: {
          city: "Los Angeles",
          region: "California",
          country: "United States",
          coordinates: { lat: 40.08995661645463, lng: 0.058131561710008356 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "elizabeth.clark@paragontrailshomestays.com",
        phoneNumber: "+10-716-4303",
        isVerified: true,
        rating: 4.8,
        reviewCount: 59,
        quote: "My home is your home in los-angeles. I look forward to making your stay memorable and authentic.",
        stayType: "eco-stay",
      },
      {
        name: "Jordan Gonzalez",
        background: "Local musician involved in the cultural scene",
        maxGuests: 5,
        languages: ["English", "Chinese", "Arabic", "Spanish"],
        curfew: "13:00 AM",
        isPopular: false,
        guestPolicy: ["Perfect for long-term stays", "Suitable for business travelers", "Accessible for guests with mobility issues"],
        hostingStyle: "private",
        houseRules: ["Lock the door when leaving the house", "Kitchen closed after 8 PM", "Recycle according to local guidelines", "Wi-Fi password will be provided upon arrival"],
        location: {
          city: "Los Angeles",
          region: "California",
          country: "United States",
          coordinates: { lat: 40.051911694672626, lng: 0.013086898689990537 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "jordan.gonzalez@paragontrailshomestays.com",
        phoneNumber: "+15-1046-7329",
        isVerified: true,
        rating: 4.2,
        reviewCount: 38,
        quote: "I've lived in los-angeles all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "cottage-stay",
      }
,
      {
        name: "Brenda Murray",
        background: "Expat who has lived in the city for over a decade",
        maxGuests: 4,
        languages: ["English", "Russian", "Japanese"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "Children welcome", "Suitable for digital nomads", "Smoking allowed in designated areas only"],
        hostingStyle: "laid-back",
        houseRules: ["Notify host if you'll be arriving after 10 PM", "No outside guests without permission", "Laundry available on weekends only"],
        location: {
          city: "Los Angeles",
          region: "California",
          country: "United States",
          coordinates: { lat: 39.97411594581058, lng: -0.01625005686666539 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "brenda.murray@paragontrailshomestays.com",
        phoneNumber: "+54-1044-8369",
        isVerified: false,
        rating: 3.8,
        reviewCount: 35,
        quote: "Life in los-angeles has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "heritage-stay",
      },
      {
        name: "Aria Dixon",
        background: "Local musician involved in the cultural scene",
        maxGuests: 4,
        languages: ["English", "Japanese", "French", "Russian"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Not suitable for infants (under 2 years)", "Children welcome", "Pet-friendly accommodation", "Family-friendly environment"],
        hostingStyle: "social",
        houseRules: ["Kitchen closed after 8 PM", "No outside guests without permission", "No loud music after 9 PM", "Breakfast is self-serve between 7-9 AM"],
        location: {
          city: "Los Angeles",
          region: "California",
          country: "United States",
          coordinates: { lat: 39.93503035300694, lng: -0.00835594824975261 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "aria.dixon@paragontrailshomestays.com",
        phoneNumber: "+6-449-4241",
        isVerified: true,
        rating: 4,
        reviewCount: 68,
        quote: "Staying with me means experiencing los-angeles like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "self-catering",
      },
      {
        name: "Ellie Nguyen",
        background: "Organic farmer with a small plot on the outskirts of town",
        maxGuests: 2,
        languages: ["English", "German", "Russian"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["Senior-friendly accommodations", "Great for couples"],
        hostingStyle: "social",
        houseRules: ["Recycle according to local guidelines", "Wi-Fi password will be provided upon arrival", "No loud music after 9 PM"],
        location: {
          city: "Los Angeles",
          region: "California",
          country: "United States",
          coordinates: { lat: 39.94131596027609, lng: -0.036171046927221215 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "ellie.nguyen@paragontrailshomestays.com",
        phoneNumber: "+65-270-10182",
        isVerified: true,
        rating: 4,
        reviewCount: 30,
        quote: "Life in los-angeles has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "spiritual-or-wellness-retreat",
      }

];
