import { Homestay } from "@/lib/interfaces/people/homestay";

export const nassauHomestays: Homestay[] = [
  {
    hosts: [
      {
        name: "Thabo Martin",
        background: "University professor with expertise in local culture",
        maxGuests: 1,
        languages: ["English", "Haitian", "Guarani"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Not suitable for infants (under 2 years)", "Suitable for digital nomads", "No parties or events"],
        hostingStyle: "hands-on",
        houseRules: ["Laundry available on weekends only", "No smoking indoors", "No outside guests without permission"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 39.9634243879517, lng: -0.07490258582156094 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "thabo.martin@example.com",
        isVerified: false,
        rating: 3.7,
        reviewCount: 104,
        quote: "My home is your home in nassau. I look forward to making your stay memorable and authentic.",
        stayType: "Traditional Homestay",
      }
    ]
  },
  {
    hosts: [
      {
        name: "Samantha Khan",
        background: "Local historian researching regional traditions",
        maxGuests: 6,
        languages: ["English", "Aymara", "French"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Ideal for solo travelers", "Suitable for digital nomads"],
        hostingStyle: "hands-on",
        houseRules: ["No outside guests without permission", "Notify host if you'll be arriving after 10 PM", "Kitchen closed after 8 PM", "Please clean up after yourself in common areas", "No smoking indoors", "Remove shoes when entering the home"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 39.97006419578766, lng: 0.07474308524432435 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "samantha.khan@example.com",
        phoneNumber: "+56-376-1928",
        isVerified: true,
        rating: 3.6,
        reviewCount: 80,
        quote: "Welcome to my nassau home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "Eco Stay",
      },
      {
        name: "Wei West",
        background: "University professor with expertise in local culture",
        maxGuests: 6,
        languages: ["English", "Portuguese", "Aymara"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Great for couples", "Smoking allowed in designated areas only"],
        hostingStyle: "social",
        houseRules: ["Kitchen closed after 8 PM", "Notify host if you'll be arriving after 10 PM", "Remove shoes when entering the home"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 40.03450463473588, lng: -0.05593972414062214 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "10:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "wei.west@example.com",
        phoneNumber: "+29-787-8193",
        isVerified: false,
        rating: 3.9,
        reviewCount: 50,
        quote: "I've lived in nassau all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "Shared Room",
      },
      {
        name: "Hassan Baker",
        background: "Local musician involved in the cultural scene",
        maxGuests: 3,
        languages: ["English", "Haitian", "Portuguese"],
        curfew: "14:00 AM",
        isPopular: true,
        guestPolicy: ["Perfect for long-term stays", "LGBTQ+ friendly", "Ideal for solo travelers", "Suitable for business travelers"],
        hostingStyle: "hands-on",
        houseRules: ["Recycle according to local guidelines", "Wi-Fi password will be provided upon arrival", "No loud music after 9 PM", "Remove shoes when entering the home"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 40.021648440181906, lng: 0.011415763763935466 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "hassan.baker@example.com",
        phoneNumber: "+46-451-10203",
        isVerified: true,
        rating: 3.6,
        reviewCount: 44,
        quote: "My home is your home in nassau. I look forward to making your stay memorable and authentic.",
        stayType: "Pet Friendly Stay",
      }
    ]
  },
  {
    hosts: [
      {
        name: "Joseph Fisher",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 6,
        languages: ["English", "Haitian", "Aymara"],
        curfew: "15:00 AM",
        isPopular: true,
        guestPolicy: ["No children under 12", "Senior-friendly accommodations", "Smoking allowed in designated areas only"],
        hostingStyle: "hands-on",
        houseRules: ["Wi-Fi password will be provided upon arrival", "Quiet hours after 10 PM", "Please conserve water and electricity", "No outside guests without permission", "Lock the door when leaving the house", "No pets allowed"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 39.90646395217073, lng: -0.04593478158377038 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "joseph.fisher@example.com",
        isVerified: false,
        rating: 3.6,
        reviewCount: 76,
        quote: "Staying with me means experiencing nassau like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "Private Room In Home",
      },
      {
        name: "Brandon Bennett",
        background: "Retired schoolteacher passionate about sharing local traditions",
        maxGuests: 2,
        languages: ["English", "Spanish", "Aymara"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Smoking allowed in designated areas only", "Great for couples", "Not suitable for infants (under 2 years)", "Suitable for business travelers"],
        hostingStyle: "laid-back",
        houseRules: ["Wi-Fi password will be provided upon arrival", "Pets welcome", "Respect shared spaces", "Kitchen closed after 8 PM", "No outside guests without permission"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 40.03142401716377, lng: 0.06950480751971258 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "11:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "brandon.bennett@example.com",
        phoneNumber: "+64-798-5972",
        isVerified: true,
        rating: 5,
        reviewCount: 32,
        quote: "Life in nassau has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "Language Immersion",
      },
      {
        name: "Brooklyn Griffin",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 1,
        languages: ["English", "French", "Quechua", "Aymara"],
        curfew: "13:00 AM",
        isPopular: false,
        guestPolicy: ["No children under 12", "Not suitable for infants (under 2 years)", "Great for couples", "No parties or events"],
        hostingStyle: "laid-back",
        houseRules: ["No outside guests without permission", "Laundry available on weekends only", "Pets welcome", "Please clean up after yourself in common areas", "Wi-Fi password will be provided upon arrival", "Remove shoes when entering the home"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 40.07146268263229, lng: 0.06278460619541568 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "brooklyn.griffin@example.com",
        isVerified: true,
        rating: 4.3,
        reviewCount: 100,
        quote: "Welcome to my nassau home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "Shared Room",
      }
    ]
  },
  {
    hosts: [
      {
        name: "Riley Campbell",
        background: "Artist who loves sharing local cultural insights",
        maxGuests: 1,
        languages: ["English", "Spanish", "Guarani", "French"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["Senior-friendly accommodations", "Ideal for solo travelers"],
        hostingStyle: "social",
        houseRules: ["No smoking indoors", "Lock the door when leaving the house", "Remove shoes when entering the home", "Breakfast is self-serve between 7-9 AM"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 39.92313302201655, lng: 0.012329170065634942 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "riley.campbell@example.com",
        phoneNumber: "+100-842-2492",
        isVerified: true,
        rating: 4.1,
        reviewCount: 26,
        quote: "Staying with me means experiencing nassau like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "Volunteer Stay",
      },
      {
        name: "Ryan Edwards",
        background: "Digital nomad who settled in the city after falling in love with it",
        maxGuests: 4,
        languages: ["English", "Spanish", "Portuguese", "Guarani"],
        curfew: "14:00 AM",
        isPopular: true,
        guestPolicy: ["LGBTQ+ friendly", "Suitable for digital nomads", "No children under 12", "Smoking allowed in designated areas only"],
        hostingStyle: "private",
        houseRules: ["Wi-Fi password will be provided upon arrival", "No food in the bedrooms", "Notify host if you'll be arriving after 10 PM", "No pets allowed", "Please clean up after yourself in common areas", "Remove shoes when entering the home"],
        location: {
          city: "Nassau",
          region: "Caribbean",
          country: "Bahamas",
          coordinates: { lat: 40.00178373118816, lng: -0.026514911019636905 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "ryan.edwards@example.com",
        phoneNumber: "+31-756-4674",
        isVerified: true,
        rating: 3.6,
        reviewCount: 64,
        quote: "My home is your home in nassau. I look forward to making your stay memorable and authentic.",
        stayType: "Shared Room",
      }
    ]
  }
];
