// Homestay data for skagway
// This file is auto-generated. Do not edit manually.

import { Host } from "@/lib/interfaces/people/homestay";

export const skagwayHomestays: Host[] = [
      {
        name: "Joseph Chen",
        background: "Organic farmer with a small plot on the outskirts of town",
        maxGuests: 2,
        languages: ["English", "French", "German"],
        curfew: "13:00 AM",
        isPopular: false,
        guestPolicy: ["Pet-friendly accommodation", "No children under 12", "Suitable for business travelers"],
        hostingStyle: "private",
        houseRules: ["Wi-Fi password will be provided upon arrival", "Lock the door when leaving the house", "No outside guests without permission", "Quiet hours after 10 PM"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 40.01774360826805, lng: -0.04122282080222326 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "11:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "joseph.chen@paragontrailshomestays.com",
        phoneNumber: "+22-939-10928",
        isVerified: true,
        rating: 4.6,
        reviewCount: 66,
        quote: "I've lived in skagway all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "cottage-stay",
      },
      {
        name: "William Harper",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 6,
        languages: ["English", "Arabic", "Portuguese"],
        curfew: "15:00 AM",
        isPopular: true,
        guestPolicy: ["Great for couples", "Suitable for digital nomads", "Smoking allowed in designated areas only"],
        hostingStyle: "family-oriented",
        houseRules: ["Please conserve water and electricity", "Recycle according to local guidelines", "No outside guests without permission", "Lock the door when leaving the house"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 40.01599994926632, lng: -0.010722561341393669 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "11:00 AM",
        },
        email: "william.harper@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.1,
        reviewCount: 44,
        quote: "Life in skagway has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "private-room-in-home",
      },
      {
        name: "Roger Williams",
        background: "Environmental activist working on local sustainability projects",
        maxGuests: 1,
        languages: ["English", "Spanish", "Russian", "French"],
        curfew: "22:00 PM",
        isPopular: false,
        guestPolicy: ["Perfect for long-term stays", "Ideal for solo travelers", "Senior-friendly accommodations"],
        hostingStyle: "family-oriented",
        houseRules: ["Notify host if you'll be arriving after 10 PM", "Laundry available on weekends only", "Recycle according to local guidelines", "No loud music after 9 PM"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 40.09896364249938, lng: 0.0809378216824524 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "roger.williams@paragontrailshomestays.com",
        phoneNumber: "+55-841-4897",
        isVerified: true,
        rating: 3.7,
        reviewCount: 67,
        quote: "Welcome to my skagway home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "private-room-in-home",
      }
,
      {
        name: "Bobby Lewis",
        background: "Retired schoolteacher passionate about sharing local traditions",
        maxGuests: 3,
        languages: ["English", "Japanese", "German"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "Pet-friendly accommodation", "Accessible for guests with mobility issues", "Ideal for solo travelers"],
        hostingStyle: "private",
        houseRules: ["Wi-Fi password will be provided upon arrival", "Respect shared spaces", "Laundry available on weekends only", "Please conserve water and electricity", "Breakfast is self-serve between 7-9 AM", "Remove shoes when entering the home"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 39.910822552458455, lng: 0.04583584253077663 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "bobby.lewis@paragontrailshomestays.com",
        phoneNumber: "+46-964-8074",
        isVerified: true,
        rating: 4.6,
        reviewCount: 35,
        quote: "Life in skagway has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "urban-apartment-stay",
      }
,
      {
        name: "Kyle Crawford",
        background: "Local musician involved in the cultural scene",
        maxGuests: 3,
        languages: ["English", "Spanish", "Russian", "Japanese"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Perfect for long-term stays", "No children under 12"],
        hostingStyle: "laid-back",
        houseRules: ["Notify host if you'll be arriving after 10 PM", "Recycle according to local guidelines", "Breakfast is self-serve between 7-9 AM", "No loud music after 9 PM", "Please clean up after yourself in common areas"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 39.988998414026376, lng: -0.06876529792118183 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "kyle.crawford@paragontrailshomestays.com",
        phoneNumber: "+67-755-1250",
        isVerified: true,
        rating: 4.5,
        reviewCount: 70,
        quote: "I've lived in skagway all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "language-immersion",
      },
      {
        name: "Ali Gibson",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 5,
        languages: ["English", "Arabic", "Chinese"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Ideal for solo travelers", "Pet-friendly accommodation", "Great for couples", "Accessible for guests with mobility issues"],
        hostingStyle: "private",
        houseRules: ["Please conserve water and electricity", "Kitchen closed after 8 PM", "Please clean up after yourself in common areas", "Respect shared spaces", "Recycle according to local guidelines", "No loud music after 9 PM"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 39.98406837291541, lng: 0.025539059675903253 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "ali.gibson@paragontrailshomestays.com",
        phoneNumber: "+66-887-8476",
        isVerified: true,
        rating: 3.8,
        reviewCount: 44,
        quote: "My home is your home in skagway. I look forward to making your stay memorable and authentic.",
        stayType: "art-or-craft-stay",
      }
,
      {
        name: "Sebastian Jones",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 1,
        languages: ["English", "Portuguese", "Arabic", "Chinese"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["No children under 12", "Great for couples"],
        hostingStyle: "private",
        houseRules: ["Pets welcome", "Kitchen closed after 8 PM", "Breakfast is self-serve between 7-9 AM", "No pets allowed"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 40.0910450237419, lng: -0.0866683081284533 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "sebastian.jones@paragontrailshomestays.com",
        phoneNumber: "+33-535-4918",
        isVerified: true,
        rating: 3.7,
        reviewCount: 36,
        quote: "Welcome to my skagway home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "traditional-homestay",
      },
      {
        name: "Amelia Hernandez",
        background: "Local historian researching regional traditions",
        maxGuests: 5,
        languages: ["English", "French", "Russian"],
        curfew: "21:00 PM",
        isPopular: false,
        guestPolicy: ["Suitable for digital nomads", "Pet-friendly accommodation"],
        hostingStyle: "private",
        houseRules: ["Kitchen closed after 8 PM", "Remove shoes when entering the home", "Recycle according to local guidelines", "No food in the bedrooms", "Notify host if you'll be arriving after 10 PM"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 40.06922641001942, lng: 0.023767204233587386 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "amelia.hernandez@paragontrailshomestays.com",
        isVerified: false,
        rating: 4.2,
        reviewCount: 55,
        quote: "My home is your home in skagway. I look forward to making your stay memorable and authentic.",
        stayType: "academic-homestay",
      }
,
      {
        name: "Maria Kowalski",
        background: "Long-time resident and community organizer",
        maxGuests: 6,
        languages: ["English", "Italian", "Chinese"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Children welcome", "No children under 12", "Accessible for guests with mobility issues"],
        hostingStyle: "family-oriented",
        houseRules: ["No pets allowed", "No smoking indoors", "Lock the door when leaving the house"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 40.00069269152391, lng: 0.08992224525088047 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "maria.kowalski@paragontrailshomestays.com",
        phoneNumber: "+25-766-10613",
        isVerified: false,
        rating: 4.6,
        reviewCount: 85,
        quote: "Staying with me means experiencing skagway like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "art-or-craft-stay",
      },
      {
        name: "Bella Baker",
        background: "Language teacher who enjoys helping visitors learn the local tongue",
        maxGuests: 5,
        languages: ["English", "Japanese", "Italian"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Smoking allowed in designated areas only", "No parties or events"],
        hostingStyle: "laid-back",
        houseRules: ["Quiet hours after 10 PM", "Respect shared spaces", "Please conserve water and electricity"],
        location: {
          city: "Skagway",
          region: "Alaska",
          country: "United States",
          coordinates: { lat: 39.99090170007695, lng: -0.07261861236648293 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "bella.baker@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.9,
        reviewCount: 32,
        quote: "My home is your home in skagway. I look forward to making your stay memorable and authentic.",
        stayType: "villa-stay",
      }

];
