// Homestay data for st-thomas
// This file is auto-generated. Do not edit manually.

// Genderated on: 2025-06-08T04:09:39.259Z

// City: st-thomas
// Region: US Virgin Islands
// Country: US Virgin Islands

import { Host } from "@/lib/interfaces/people/homestay";

export const stThomasHomestays: Host[] = [
      {
        name: "Bella Holloway",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 5,
        languages: ["English", "Italian", "Japanese"],
        curfew: "23:00 PM",
        isPopular: false,
        guestPolicy: ["Accessible for guests with mobility issues", "Not suitable for infants (under 2 years)", "Suitable for business travelers", "No parties or events"],
        hostingStyle: "hands-on",
        houseRules: ["Please conserve water and electricity", "No smoking indoors", "No pets allowed", "No food in the bedrooms"],
        location: {
          city: "St Thomas",
          region: "US Virgin Islands",
          country: "US Virgin Islands",
          coordinates: { lat: 39.905083938334435, lng: 0.03314692586679785 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "bella.holloway@paragontrailshomestays.com",
        phoneNumber: "+25-718-1238",
        isVerified: true,
        rating: 4.3,
        reviewCount: 69,
        quote: "Welcome to my st-thomas home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "traditional-homestay",
      },
      {
        name: "Donna Campbell",
        background: "Digital nomad who settled in the city after falling in love with it",
        maxGuests: 2,
        languages: ["English", "French", "Russian", "Japanese"],
        curfew: "13:00 AM",
        isPopular: false,
        guestPolicy: ["Accessible for guests with mobility issues", "Ideal for solo travelers", "Smoking allowed in designated areas only", "Family-friendly environment"],
        hostingStyle: "social",
        houseRules: ["No outside guests without permission", "No loud music after 9 PM", "Notify host if you'll be arriving after 10 PM", "No smoking indoors", "Wi-Fi password will be provided upon arrival"],
        location: {
          city: "St Thomas",
          region: "US Virgin Islands",
          country: "US Virgin Islands",
          coordinates: { lat: 39.979313616061745, lng: -0.049899517523290894 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "donna.campbell@paragontrailshomestays.com",
        phoneNumber: "+39-192-4601",
        isVerified: true,
        rating: 3.7,
        reviewCount: 15,
        quote: "Life in st-thomas has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "farm-stay",
      },
      {
        name: "Amelia Ellis",
        background: "Environmental activist working on local sustainability projects",
        maxGuests: 6,
        languages: ["English", "Russian", "Portuguese", "German"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["No parties or events", "Perfect for long-term stays", "Senior-friendly accommodations"],
        hostingStyle: "hands-on",
        houseRules: ["Breakfast is self-serve between 7-9 AM", "No pets allowed", "Please clean up after yourself in common areas"],
        location: {
          city: "St Thomas",
          region: "US Virgin Islands",
          country: "US Virgin Islands",
          coordinates: { lat: 39.900797330230134, lng: -0.011310915444134123 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "amelia.ellis@paragontrailshomestays.com",
        phoneNumber: "+36-1046-9991",
        isVerified: true,
        rating: 4,
        reviewCount: 60,
        quote: "Life in st-thomas has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "academic-homestay",
      }
,
      {
        name: "Mason Thomas",
        background: "Language teacher who enjoys helping visitors learn the local tongue",
        maxGuests: 6,
        languages: ["English", "French", "Chinese"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "No children under 12"],
        hostingStyle: "social",
        houseRules: ["Please conserve water and electricity", "Recycle according to local guidelines", "Laundry available on weekends only", "No loud music after 9 PM"],
        location: {
          city: "St Thomas",
          region: "US Virgin Islands",
          country: "US Virgin Islands",
          coordinates: { lat: 39.906837129054594, lng: 0.08076566457556084 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "mason.thomas@paragontrailshomestays.com",
        phoneNumber: "+90-400-4748",
        isVerified: true,
        rating: 3.9,
        reviewCount: 16,
        quote: "My home is your home in st-thomas. I look forward to making your stay memorable and authentic.",
        stayType: "eco-stay",
      }
,
      {
        name: "Antonio Dunn",
        background: "Retired schoolteacher passionate about sharing local traditions",
        maxGuests: 5,
        languages: ["English", "German", "Portuguese", "French"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["No parties or events", "Great for couples", "Senior-friendly accommodations", "Smoking allowed in designated areas only"],
        hostingStyle: "laid-back",
        houseRules: ["No smoking indoors", "No outside guests without permission", "Quiet hours after 10 PM"],
        location: {
          city: "St Thomas",
          region: "US Virgin Islands",
          country: "US Virgin Islands",
          coordinates: { lat: 40.00962923772095, lng: -0.028293002770859138 },
        },
        availability: {
          checkInTime: "12:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "antonio.dunn@paragontrailshomestays.com",
        phoneNumber: "+42-1057-6951",
        isVerified: true,
        rating: 4.6,
        reviewCount: 55,
        quote: "Welcome to my st-thomas home! I believe in creating a warm, welcoming environment for all my guests.",
        stayType: "traditional-homestay",
      }
,
      {
        name: "Nicole Lewis",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 6,
        languages: ["English", "French", "Arabic", "Japanese"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Accessible for guests with mobility issues", "Great for couples", "Perfect for long-term stays", "Pet-friendly accommodation"],
        hostingStyle: "family-oriented",
        houseRules: ["No pets allowed", "No outside guests without permission", "Pets welcome", "Please clean up after yourself in common areas", "Laundry available on weekends only", "No food in the bedrooms"],
        location: {
          city: "St Thomas",
          region: "US Virgin Islands",
          country: "US Virgin Islands",
          coordinates: { lat: 40.097886899171534, lng: 0.06383057731953931 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "nicole.lewis@paragontrailshomestays.com",
        phoneNumber: "+72-458-5881",
        isVerified: true,
        rating: 3.9,
        reviewCount: 92,
        quote: "I've lived in st-thomas all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "self-catering",
      },
      {
        name: "Albert Gonzalez",
        background: "Yoga instructor offering morning sessions",
        maxGuests: 1,
        languages: ["English", "French", "Spanish", "Russian"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["Children welcome", "Ideal for solo travelers", "Suitable for business travelers"],
        hostingStyle: "hands-on",
        houseRules: ["Please conserve water and electricity", "Lock the door when leaving the house", "No outside guests without permission", "No pets allowed", "No loud music after 9 PM", "Respect shared spaces"],
        location: {
          city: "St Thomas",
          region: "US Virgin Islands",
          country: "US Virgin Islands",
          coordinates: { lat: 39.95496728226553, lng: 0.03111711469593384 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "albert.gonzalez@paragontrailshomestays.com",
        phoneNumber: "+17-551-10898",
        isVerified: true,
        rating: 4.7,
        reviewCount: 67,
        quote: "Staying with me means experiencing st-thomas like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "guest-suite",
      }
,
      {
        name: "Harper Knight",
        background: "University professor with expertise in local culture",
        maxGuests: 4,
        languages: ["English", "German", "Russian", "Arabic"],
        curfew: "21:00 PM",
        isPopular: false,
        guestPolicy: ["No children under 12", "Children welcome"],
        hostingStyle: "private",
        houseRules: ["Remove shoes when entering the home", "No loud music after 9 PM", "Please clean up after yourself in common areas", "No smoking indoors", "Lock the door when leaving the house", "Quiet hours after 10 PM"],
        location: {
          city: "St Thomas",
          region: "US Virgin Islands",
          country: "US Virgin Islands",
          coordinates: { lat: 40.077165322356194, lng: -0.017527793787424167 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "11:00 AM",
        },
        email: "harper.knight@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.4,
        reviewCount: 80,
        quote: "My home is your home in st-thomas. I look forward to making your stay memorable and authentic.",
        stayType: "culinary-homestay",
      }

];
