// Homestay data for victoria
// This file is auto-generated. Do not edit manually.

import { Host } from "@/lib/interfaces/people/homestay";

export const victoriaHomestays: Host[] = [
      {
        name: "Johnny Hawkins",
        background: "Local musician involved in the cultural scene",
        maxGuests: 4,
        languages: ["English", "Portuguese", "Japanese", "French"],
        curfew: "14:00 AM",
        isPopular: true,
        guestPolicy: ["Senior-friendly accommodations", "No parties or events", "Family-friendly environment"],
        hostingStyle: "laid-back",
        houseRules: ["Laundry available on weekends only", "No outside guests without permission", "No food in the bedrooms", "Breakfast is self-serve between 7-9 AM", "Quiet hours after 10 PM", "No smoking indoors"],
        location: {
          city: "Victoria",
          region: "British Columbia",
          country: "Canada",
          coordinates: { lat: 40.02541225453171, lng: 0.0009903146382349848 },
        },
        availability: {
          checkInTime: "16:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "johnny.hawkins@paragontrailshomestays.com",
        phoneNumber: "+47-681-4769",
        isVerified: true,
        rating: 4,
        reviewCount: 50,
        quote: "I've lived in victoria all my life and know all the best spots. Can't wait to share my city with you!",
        stayType: "eco-stay",
      },
      {
        name: "Jane Johnson",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 2,
        languages: ["English", "German", "Arabic"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Accessible for guests with mobility issues", "Not suitable for infants (under 2 years)"],
        hostingStyle: "laid-back",
        houseRules: ["Recycle according to local guidelines", "Please conserve water and electricity", "Respect shared spaces", "No food in the bedrooms", "No pets allowed", "Kitchen closed after 8 PM"],
        location: {
          city: "Victoria",
          region: "British Columbia",
          country: "Canada",
          coordinates: { lat: 40.01682307892439, lng: -0.009669107064229632 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "9:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "jane.johnson@paragontrailshomestays.com",
        phoneNumber: "+8-820-2230",
        isVerified: true,
        rating: 4.2,
        reviewCount: 63,
        quote: "Staying with me means experiencing victoria like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "volunteer-stay",
      }
,
      {
        name: "Jesse Reed",
        background: "Former tour guide with extensive knowledge of local history",
        maxGuests: 2,
        languages: ["English", "French", "Italian"],
        curfew: "15:00 AM",
        isPopular: false,
        guestPolicy: ["LGBTQ+ friendly", "No children under 12", "Suitable for digital nomads"],
        hostingStyle: "hands-on",
        houseRules: ["Quiet hours after 10 PM", "Laundry available on weekends only", "Lock the door when leaving the house", "Notify host if you'll be arriving after 10 PM", "Respect shared spaces"],
        location: {
          city: "Victoria",
          region: "British Columbia",
          country: "Canada",
          coordinates: { lat: 39.941224609227675, lng: 0.028676348428268744 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "10:00 AM",
        },
        email: "jesse.reed@paragontrailshomestays.com",
        phoneNumber: "+61-910-4256",
        isVerified: true,
        rating: 4,
        reviewCount: 60,
        quote: "Life in victoria has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "heritage-stay",
      },
      {
        name: "Frank Day",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 1,
        languages: ["English", "Russian", "Arabic"],
        curfew: "15:00 AM",
        isPopular: true,
        guestPolicy: ["LGBTQ+ friendly", "Suitable for digital nomads"],
        hostingStyle: "private",
        houseRules: ["Remove shoes when entering the home", "Lock the door when leaving the house", "Laundry available on weekends only", "Pets welcome", "No pets allowed"],
        location: {
          city: "Victoria",
          region: "British Columbia",
          country: "Canada",
          coordinates: { lat: 39.9471399265596, lng: -0.08156187741572891 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "12:00 AM",
        },
        email: "frank.day@paragontrailshomestays.com",
        isVerified: true,
        rating: 4.3,
        reviewCount: 74,
        quote: "Staying with me means experiencing victoria like a local. I love sharing the hidden gems of our beautiful city with my guests.",
        stayType: "self-catering",
      },
      {
        name: "Brenda Douglas",
        background: "Local chef specializing in traditional cuisines",
        maxGuests: 5,
        languages: ["English", "Arabic", "Italian"],
        curfew: "24:00 PM",
        isPopular: false,
        guestPolicy: ["Accessible for guests with mobility issues", "Family-friendly environment", "Ideal for solo travelers"],
        hostingStyle: "social",
        houseRules: ["Laundry available on weekends only", "Recycle according to local guidelines", "No food in the bedrooms", "Respect shared spaces", "No loud music after 9 PM", "No smoking indoors"],
        location: {
          city: "Victoria",
          region: "British Columbia",
          country: "Canada",
          coordinates: { lat: 39.910681614650265, lng: -0.06175923273245259 },
        },
        availability: {
          checkInTime: "14:00 PM",
          checkOutTime: "12:00 AM",
          calendarLink: "https://calendar.example.com/availability",
        },
        email: "brenda.douglas@paragontrailshomestays.com",
        phoneNumber: "+66-1057-9630",
        isVerified: true,
        rating: 4.4,
        reviewCount: 93,
        quote: "My home is your home in victoria. I look forward to making your stay memorable and authentic.",
        stayType: "urban-apartment-stay",
      }
,
      {
        name: "Aisha Brown",
        background: "Language teacher who enjoys helping visitors learn the local tongue",
        maxGuests: 2,
        languages: ["English", "Chinese", "Japanese"],
        curfew: "21:00 PM",
        isPopular: true,
        guestPolicy: ["Children welcome", "Suitable for business travelers", "Smoking allowed in designated areas only"],
        hostingStyle: "laid-back",
        houseRules: ["Quiet hours after 10 PM", "Pets welcome", "No smoking indoors", "Please clean up after yourself in common areas", "No pets allowed"],
        location: {
          city: "Victoria",
          region: "British Columbia",
          country: "Canada",
          coordinates: { lat: 40.060769681617316, lng: 0.06004115922738365 },
        },
        availability: {
          checkInTime: "13:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "aisha.brown@paragontrailshomestays.com",
        phoneNumber: "+55-699-10089",
        isVerified: true,
        rating: 4.2,
        reviewCount: 72,
        quote: "My home is your home in victoria. I look forward to making your stay memorable and authentic.",
        stayType: "language-immersion",
      },
      {
        name: "Abigail Mason",
        background: "Local musician involved in the cultural scene",
        maxGuests: 4,
        languages: ["English", "Spanish", "Chinese"],
        curfew: "14:00 AM",
        isPopular: false,
        guestPolicy: ["Senior-friendly accommodations", "Children welcome", "Suitable for business travelers", "Pet-friendly accommodation"],
        hostingStyle: "private",
        houseRules: ["Recycle according to local guidelines", "Remove shoes when entering the home", "No smoking indoors", "Quiet hours after 10 PM", "Please clean up after yourself in common areas"],
        location: {
          city: "Victoria",
          region: "British Columbia",
          country: "Canada",
          coordinates: { lat: 39.93048400297169, lng: 0.00783881100063541 },
        },
        availability: {
          checkInTime: "17:00 PM",
          checkOutTime: "9:00 AM",
        },
        email: "abigail.mason@paragontrailshomestays.com",
        isVerified: true,
        rating: 3.7,
        reviewCount: 92,
        quote: "Life in victoria has its own rhythm. Stay with me to experience the true pulse of this amazing place.",
        stayType: "language-immersion",
      }

];
