import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Oceanview Inn
export const oceanviewInnRooms: RoomOption[] = [
  {
    id: "hotel-paris-11-room-10-Single-OceanView",
    name: "Classic Single Villa",
    description: "Experience our tranquil, airy single villa where the horizon meets the ocean, featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator", "Hearing Support"],
    pricePerNight: 93,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-paris-11-room-10-SofaBed-CityView",
    name: "Horizon Sofa Bed Room",
    description: "Our stretching Horizon-themed room offers with a view of iconic landmarks, sophisticated comfort, and with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 81,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-paris-11-room-10-Queen-CityView",
    name: "Premium Queen Penthouse",
    description: "A bohemian queen penthouse designed for inviting comfort, with where city lights twinkle at night and with a private balcony or terrace, reflecting featuring chic Parisian-inspired decor.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 106,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-paris-11-room-10-Single-None",
    name: "Harmony Single Studio",
    description: "Discover the charm of this Harmony-themed single studio, complete with pleasant ambiance, stunning with a pleasant outlook, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 75,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-paris-11-room-10-Double-MountainView",
    name: "Serenity Double Apartment",
    description: "Enjoy a heartwarming stay in our Serenity-themed double apartment, offering with a view of the mountains' breathtaking sunsets, with high-speed internet access, and unique touches of where elegance meets Parisian style.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 112,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-paris-11-room-10-Single-GardenView",
    name: "Modern Single Studio",
    description: "This serene single studio promises where nature is just outside your window, enriched by Modern-themed details and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 77,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  }
];
