import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Loire Valley Lodge
export const theLoireValleyLodgeRooms: RoomOption[] = [
  {
    id: "hotel-paris-1-room-0-Twin-GardenView",
    name: "Harmony Twin Penthouse",
    description: "A chic twin penthouse designed for broad comfort, with where you can enjoy the garden's seasonal blooms and with high-speed internet access, reflecting featuring chic Parisian-inspired decor.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 179,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-paris-1-room-0-Double-None",
    name: "Signature Double Studio",
    description: "Unwind in this open-concept double studio with a pleasant outlook, with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 178,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-paris-1-room-0-Single-GardenView",
    name: "Harmony Single Penthouse",
    description: "Indulge in the intimate atmosphere of our single penthouse, with spectacular with a view of the garden's peaceful ambiance, blending French sophistication and modern comfort, and with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 155,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-paris-1-room-0-SofaBed-GardenView",
    name: "Deluxe Sofa Bed Loft",
    description: "Unwind in this intimate sofa bed loft where you can find solace in nature's embrace, with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 184,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-paris-1-room-0-Queen-CityView",
    name: "Signature Queen Suite",
    description: "A opulent queen retreat with stunning views of the city skyline, where elegance meets Parisian style.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 212,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 8,
  }
];
