// Auto-generated file for skagway hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const skagwayHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "hi@thepalms.com",
      contactPhone: "+157 154-777-9108",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Allowed",
    },
    id: "hotel-skagway-1",
    name: "The Palms",
    address: "20 Lincoln Ave",
    rating: 4,
    accommodationType: "Hotel",
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 15,
    isPetFriendly: true,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "customerservice@sunsetlodge.com",
      contactPhone: "+222 329-457-8155",
    },
    policies: {
      cancellation: "Free cancellation within 24 hours of booking; after that, 25% fee applies.",
      smoking: "Allowed",
    },
    id: "hotel-skagway-2",
    name: "Sunset Lodge",
    address: "202 S Elm Ave",
    rating: 4,
    accommodationType: "Spa Hotel",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 10,
    isPetFriendly: false,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "welcome@eaglecresthotel.com",
      contactPhone: "+315 935-631-7280",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    id: "hotel-skagway-3",
    name: "Eagle Crest Hotel",
    address: "67 Cedar Ter",
    rating: 4,
    accommodationType: "Boutique Resort",
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 17,
    isPetFriendly: true,
    currency: "USD",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reception@themetropolitan.com",
      contactPhone: "+120 868-818-2612",
    },
    policies: {
      cancellation: "Free cancellation within 24 hours of booking; after that, 25% fee applies.",
      smoking: "Designated Areas",
    },
    id: "hotel-skagway-4",
    name: "The Metropolitan",
    address: "60 Washington Trl",
    rating: 4,
    accommodationType: "Bed and Breakfast",
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 32,
    isPetFriendly: false,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "admin@thepalms.com",
      contactPhone: "+38 128-903-4570",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Designated Areas",
    },
    id: "hotel-skagway-5",
    name: "The Palms",
    address: "143 Maple Blvd",
    rating: 4,
    accommodationType: "Business Hotel",
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 57,
    isPetFriendly: true,
    currency: "USD",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "welcome@themetropolitan.com",
      contactPhone: "+729 691-232-3590",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-skagway-6",
    name: "The Metropolitan",
    address: "6 Maple Sq",
    rating: 4,
    accommodationType: "Glamping Resort",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 35,
    isPetFriendly: true,
    currency: "USD",
    isPopular: false,
  },
  {
    id: "hotel-skagway-7",
    name: "Oakwood Resort",
    address: "222 Sunset Sq",
    rating: 4,
    accommodationType: "All-Inclusive Resort",
    amenities: ["Restaurant", "24-Hour Front Desk", "Spa", "Conference Room", "Fitness Center"],
    accessibilityFeatures: ["Elevator"],
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 13,
    isPetFriendly: true,
    currency: "USD",
    contact: {
      contactEmail: "clientservices@oakwoodresort.com",
      contactPhone: "+344 845-829-3620",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-skagway-8",
    name: "Liberty Suites",
    address: "15 New Broadway Ave",
    rating: 3,
    accommodationType: "Bed and Breakfast",
    amenities: ["Swimming Pool", "Room Service", "24-Hour Front Desk", "Parking", "Restaurant", "Non-Smoking Rooms", "Fitness Center", "Laundry Service", "Airport Shuttle"],
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 59,
    isPetFriendly: false,
    currency: "USD",
    contact: {
      contactEmail: "help@libertysuites.com",
      contactPhone: "+362 704-156-1508",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-skagway-9",
    name: "Oakwood Resort",
    address: "65 Washington Ln",
    rating: 4,
    accommodationType: "Vacation Rental",
    amenities: ["Spa", "Fitness Center", "Restaurant", "24-Hour Front Desk", "Bar", "Laundry Service", "Non-Smoking Rooms"],
    accessibilityFeatures: ["Assistive Listening Devices", "Accessible Shower"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 36,
    isPetFriendly: false,
    currency: "USD",
    contact: {
      contactEmail: "team@oakwoodresort.com",
      contactPhone: "+755 422-978-1661",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    isPopular: false,
  }
];
