import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Snuggly Seahorse
export const theSnugglySeahorseRooms: RoomOption[] = [
  {
    id: "hotel-skagway-2-room-1-King-CityView",
    name: "Deluxe King Apartment",
    description: "Our pleasant Deluxe-themed apartment offers with stunning views of the city skyline, stylish comfort, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 152,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-skagway-2-room-1-Double-GardenView",
    name: "Manhattan Double Suite",
    description: "A contemporary double suite designed for commodious comfort, with where nature is just outside your window and with a spacious work area, reflecting highlighting contemporary American style.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 112,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-skagway-2-room-1-King-OceanView",
    name: "Heritage King Villa",
    description: "Indulge in the chic atmosphere of our king villa, with spectacular with a view of the tranquil sea, offering a classic yet modern American experience, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 165,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-skagway-2-room-1-Queen-GardenView",
    name: "Standard Queen Apartment",
    description: "A stylish queen retreat where you can take in the fresh air, offering a classic yet modern American experience.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 116,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-skagway-2-room-1-Double-MountainView",
    name: "Heritage Double Room",
    description: "Unwind in this prestigious double room where you can escape to the mountains, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 107,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-skagway-2-room-1-SofaBed-MountainView",
    name: "Standard Sofa Bed Suite",
    description: "Unwind in this restful sofa bed suite with majestic mountain vistas, with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Elevator", "Accessible Bathroom", "Hearing Support"],
    pricePerNight: 98,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-skagway-2-room-1-Twin-OceanView",
    name: "Heritage Twin Apartment",
    description: "Our intimate Heritage-themed apartment offers with the sound of the ocean as your backdrop, sleek comfort, and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 101,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-skagway-2-room-1-Single-MountainView",
    name: "Manhattan Single Villa",
    description: "Step into a generous single villa that combines Manhattan-themed with breathtaking where you can escape to the mountains, complemented by featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 89,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-skagway-2-room-1-Twin-MountainView",
    name: "Deluxe Twin Penthouse",
    description: "Discover the charm of this Deluxe-themed twin penthouse, complete with retro ambiance, stunning where you can find inspiration in the mountains, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 109,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-skagway-2-room-1-SofaBed-OceanView",
    name: "Golden Gate Sofa Bed Studio",
    description: "Enjoy a calming stay in our Golden Gate-themed sofa bed studio, offering with a view of the tranquil sea, with a modern en-suite bathroom, and unique touches of with rustic and modern influences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 108,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  }
];
