import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Ambassador
export const theAmbassadorRooms: RoomOption[] = [
  {
    id: "hotel-st-thomas-8-room-7-King-MountainView",
    name: "Executive King Room",
    description: "Executive-themed king room where you can escape to the mountains, created with both style and function in mind and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Visual Aids", "Wheelchair Accessible", "Hearing Support"],
    pricePerNight: 375,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-st-thomas-8-room-7-Twin-None",
    name: "Horizon Twin Suite",
    description: "A large-scale twin suite designed for chic comfort, with with a pleasant outlook and featuring a curated minibar selection, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Visual Aids"],
    pricePerNight: 171,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-st-thomas-8-room-7-SofaBed-MountainView",
    name: "Classic Sofa Bed Suite",
    description: "Experience our contemporary, refreshing sofa bed suite with a view of the mountains' natural beauty, with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 228,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-st-thomas-8-room-7-Single-CityView",
    name: "Executive Single Suite",
    description: "Indulge in the extensive atmosphere of our single suite, with spectacular with a view of the city's waterfront, designed for ultimate comfort, and with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 178,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-st-thomas-8-room-7-Single-GardenView",
    name: "Modern Single Room",
    description: "Discover the charm of this Modern-themed single room, complete with roomy ambiance, stunning with a view of blooming flowers and greenery, and with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Visual Aids", "Wheelchair Accessible"],
    pricePerNight: 178,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-st-thomas-8-room-7-King-GardenView",
    name: "Tranquility King Villa",
    description: "This contemporary king accommodation offers where you can enjoy the serenity of a garden retreat, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids", "Accessible Bathroom"],
    pricePerNight: 323,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-st-thomas-8-room-7-King-None",
    name: "Harmony King Studio",
    description: "Relax in our indulgent eclectic king studio featuring with a pleasant outlook, along with equipped with all the modern conveniences and decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 263,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-st-thomas-8-room-7-Double-GardenView",
    name: "Premium Double Penthouse",
    description: "This large-scale double accommodation offers surrounded by vibrant flora, featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 226,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-st-thomas-8-room-7-Queen-MountainView",
    name: "Harmony Queen Apartment",
    description: "Discover the charm of this Harmony-themed queen apartment, complete with glamorous ambiance, stunning with a view of the rugged mountain landscape, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 276,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-st-thomas-8-room-7-SofaBed-None",
    name: "Deluxe Sofa Bed Apartment",
    description: "Enjoy a well-proportioned stay in our Deluxe-themed sofa bed apartment, offering with a pleasant outlook, with a private balcony or terrace, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 162,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  }
];
