import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Kamloops Thompson Hotel
export const kamloopsThompsonHotelRooms: RoomOption[] = [
  {
    id: "hotel-quebec-city-1-room-0-Single-CityView",
    name: "Classic Single Studio",
    description: "Step into a rustic single studio that combines Classic-themed with breathtaking where you can watch the city wake up, complemented by featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom"],
    pricePerNight: 113,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-quebec-city-1-room-0-Single-GardenView",
    name: "Deluxe Single Suite",
    description: "A soft single suite designed for airy comfort, with where you can relax in a natural oasis and with high-speed internet access, reflecting created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 134,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-quebec-city-1-room-0-SofaBed-MountainView",
    name: "Classic Sofa Bed Studio",
    description: "Step into a industrial sofa bed studio that combines Classic-themed with breathtaking where mountains paint the horizon, complemented by with a spacious seating area.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 154,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-quebec-city-1-room-0-Queen-OceanView",
    name: "Horizon Queen Villa",
    description: "Our Horizon-themed queen villa offers deluxe luxury, panoramic where you can enjoy stunning sunsets over the water, and offering a unique blend of style and comfort, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 217,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-quebec-city-1-room-0-Single-MountainView",
    name: "Classic Single Penthouse",
    description: "This retro single accommodation offers with a view of the mountains' changing seasons, designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 137,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-quebec-city-1-room-0-King-None",
    name: "Superior King Loft",
    description: "Indulge in the sizable atmosphere of our king loft, with spectacular with a pleasant outlook, created with both style and function in mind, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 179,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  }
];
