import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Northern Lights Inn
export const theNorthernLightsInnRooms: RoomOption[] = [
  {
    id: "hotel-quebec-city-11-room-10-Queen-CityView",
    name: "Harmony Queen Villa",
    description: "Relax in our elegant minimalist queen villa featuring showcasing the urban landscape, along with with plush bedding for ultimate comfort and created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 342,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-quebec-city-11-room-10-King-CityView",
    name: "Superior King Studio",
    description: "Step into a refreshing king studio that combines Superior-themed with breathtaking where city lights twinkle at night, complemented by featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 385,
    currency: "CAD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-quebec-city-11-room-10-Single-OceanView",
    name: "Standard Single Loft",
    description: "Indulge in the vast atmosphere of our single loft, with spectacular with a private balcony overlooking the sea, designed for ultimate comfort, and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 256,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-quebec-city-11-room-10-King-MountainView",
    name: "Tranquility King Villa",
    description: "Discover the charm of this Tranquility-themed king villa, complete with upscale ambiance, stunning where you can gaze at the towering peaks, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 454,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-quebec-city-11-room-10-Double-None",
    name: "Classic Double Room",
    description: "Our Classic-themed double room offers comfortable luxury, panoramic with a pleasant outlook, and featuring a curated minibar selection, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 291,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-quebec-city-11-room-10-Queen-GardenView",
    name: "Classic Queen Studio",
    description: "Classic-themed studio with ample decor, where nature is just outside your window, and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 402,
    currency: "CAD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
