import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for NovaLink Hotel & Lounge
export const novalinkHotelLoungeRooms: RoomOption[] = [
  {
    id: "hotel-svaneti-region-2-room-1-Double-MountainView",
    name: "Deluxe Double Loft",
    description: "Unwind in this regal double loft where you can enjoy the peace of the highlands, with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 917,
    currency: "GEL",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-svaneti-region-2-room-1-SofaBed-None",
    name: "Harmony Sofa Bed Suite",
    description: "Indulge in the modern atmosphere of our sofa bed suite, with spectacular with a pleasant outlook, decorated with local artistic influences, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 633,
    currency: "GEL",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-svaneti-region-2-room-1-Queen-MountainView",
    name: "Luxury Queen Apartment",
    description: "Luxury-themed queen apartment where you can enjoy the mountains' majestic presence, designed for ultimate comfort and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 974,
    currency: "GEL",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-svaneti-region-2-room-1-Twin-CityView",
    name: "Executive Twin Studio",
    description: "Our tasteful Executive-themed studio offers with a front-row seat to the city's heartbeat, vintage comfort, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 674,
    currency: "GEL",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-svaneti-region-2-room-1-Queen-CityView",
    name: "Superior Queen Loft",
    description: "Relax in our stylish luxurious queen loft featuring featuring a blend of modern and historic architecture, along with featuring premium bath amenities and featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 830,
    currency: "GEL",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-svaneti-region-2-room-1-Double-OceanView",
    name: "Harmony Double Suite",
    description: "Relax in our wide-ranging welcoming double suite featuring where the horizon meets the ocean, along with with a spacious seating area and designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 842,
    currency: "GEL",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-svaneti-region-2-room-1-King-GardenView",
    name: "Premium King Loft",
    description: "Our voluminous Premium-themed loft offers where you can take in the fresh air, intimate comfort, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 1006,
    currency: "GEL",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-svaneti-region-2-room-1-Twin-None",
    name: "Tranquility Twin Room",
    description: "Unwind in this lavish twin room with a pleasant outlook, featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 635,
    currency: "GEL",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-svaneti-region-2-room-1-SofaBed-OceanView",
    name: "Serenity Sofa Bed Loft",
    description: "Indulge in the stretching atmosphere of our sofa bed loft, with spectacular where you can enjoy stunning sunsets over the water, designed for ultimate comfort, and featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Elevator", "Accessible Bathroom"],
    pricePerNight: 847,
    currency: "GEL",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  }
];
