import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Evergreen Court
export const theEvergreenCourtRooms: RoomOption[] = [
  {
    id: "hotel-portland-5-room-4-King-GardenView",
    name: "Golden Gate King Loft",
    description: "Our Golden Gate-themed king loft offers intimate luxury, panoramic where you can enjoy the sights and sounds of nature, and featuring a curated minibar selection, inspired by highlighting contemporary American style.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 225,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-portland-5-room-4-Queen-None",
    name: "Signature Queen Room",
    description: "Our Signature-themed queen room offers open-concept luxury, panoramic with a pleasant outlook, and with carefully selected furnishings, inspired by featuring sleek urban design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Accessible Bathroom", "Hearing Support"],
    pricePerNight: 177,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-portland-5-room-4-Single-CityView",
    name: "Heritage Single Suite",
    description: "Unwind in this soothing single suite with a window to the bustling city below, with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 113,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-portland-5-room-4-Twin-None",
    name: "Executive Twin Loft",
    description: "Our vast Executive-themed loft offers with a pleasant outlook, upscale comfort, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Visual Aids", "Wheelchair Accessible"],
    pricePerNight: 118,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-portland-5-room-4-Twin-GardenView",
    name: "Superior Twin Villa",
    description: "This soothing twin villa promises where you can unwind in a garden paradise, enriched by Superior-themed details and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 139,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-portland-5-room-4-Double-None",
    name: "Standard Double Penthouse",
    description: "Standard-themed double penthouse with a pleasant outlook, with rustic and modern influences and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 138,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-portland-5-room-4-Single-OceanView",
    name: "Superior Single Room",
    description: "A heartwarming single retreat with a view of the ocean's horizon, featuring sleek urban design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 152,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-portland-5-room-4-King-OceanView",
    name: "Luxury King Loft",
    description: "This restful king accommodation offers where the horizon meets the ocean, highlighting contemporary American style.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 230,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-portland-5-room-4-Single-None",
    name: "Superior Single Apartment",
    description: "Our Superior-themed single apartment offers chic luxury, panoramic with a pleasant outlook, and with a luxurious soaking tub, inspired by offering a classic yet modern American experience.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 102,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  }
];
