import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Sunset Villa
export const sunsetVillaRooms: RoomOption[] = [
  {
    id: "hotel-dubai-10-room-9-Double-CityView",
    name: "Pearl Double Room",
    description: "A majestic double room designed for retro comfort, with featuring a blend of modern and historic architecture and including climate control for your comfort, reflecting offering lavish comfort and grandeur.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids"],
    pricePerNight: 3909,
    currency: "AED",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-dubai-10-room-9-Double-None",
    name: "Executive Double Studio",
    description: "Relax in our ample vintage double studio featuring with a pleasant outlook, along with offering a unique blend of style and comfort and featuring opulent Arabian-inspired decor.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 3457,
    currency: "AED",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-dubai-10-room-9-Queen-GardenView",
    name: "Premium Queen Suite",
    description: "Enjoy a soft stay in our Premium-themed queen suite, offering where you can enjoy the garden's peaceful atmosphere, with high-speed internet access, and unique touches of featuring opulent Arabian-inspired decor.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 4372,
    currency: "AED",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-dubai-10-room-9-SofaBed-None",
    name: "Classic Sofa Bed Suite",
    description: "Discover the charm of this Classic-themed sofa bed suite, complete with voluminous ambiance, stunning with a pleasant outlook, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 3143,
    currency: "AED",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-dubai-10-room-9-Twin-OceanView",
    name: "Mirage Twin Room",
    description: "Mirage-themed room with opulent decor, with a view of the sandy beaches, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 3828,
    currency: "AED",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-dubai-10-room-9-King-OceanView",
    name: "Classic King Apartment",
    description: "A comfy king apartment designed for fashionable comfort, with with a view of the sandy beaches and including climate control for your comfort, reflecting blending traditional motifs with futuristic luxury.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 5900,
    currency: "AED",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  }
];
