import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Olympia Zeus Hotel
export const olympiaZeusHotelRooms: RoomOption[] = [
  {
    id: "hotel-mykonos-1-room-0-Twin-OceanView",
    name: "Premium Twin Loft",
    description: "This voluminous twin accommodation offers with breathtaking sea views, featuring Aegean-inspired decor with blue and white tones.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    accessibilityFeatures: ["Wheelchair Accessible", "Visual Aids", "Elevator"],
    pricePerNight: 213,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-mykonos-1-room-0-Queen-CityView",
    name: "Signature Queen Apartment",
    description: "Relax in our upscale extravagant queen apartment featuring with stunning views of the city skyline, along with with carefully selected furnishings and offering a serene and relaxing atmosphere with Mediterranean charm.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Visual Aids", "Wheelchair Accessible"],
    pricePerNight: 242,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-mykonos-1-room-0-Single-OceanView",
    name: "Deluxe Single Villa",
    description: "Unwind in this opulent single villa with a view of the endless blue, with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 196,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-mykonos-1-room-0-SofaBed-MountainView",
    name: "Mykonos Sofa Bed Loft",
    description: "Discover the charm of this Mykonos-themed sofa bed loft, complete with generous ambiance, stunning where you can gaze at the towering peaks, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 209,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-mykonos-1-room-0-King-None",
    name: "Aegean King Loft",
    description: "Relax in our peaceful relaxing king loft featuring with a pleasant outlook, along with equipped with all the modern conveniences and featuring Aegean-inspired decor with blue and white tones.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 220,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-mykonos-1-room-0-Queen-OceanView",
    name: "Santorini Queen Villa",
    description: "Enjoy a well-proportioned stay in our Santorini-themed queen villa, offering where you can enjoy stunning sunsets over the water, with blackout curtains for a perfect night's sleep, and unique touches of offering a serene and relaxing atmosphere with Mediterranean charm.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 279,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-mykonos-1-room-0-SofaBed-GardenView",
    name: "Standard Sofa Bed Loft",
    description: "Indulge in the eclectic atmosphere of our sofa bed loft, with spectacular where you can enjoy the beauty of nature, featuring Aegean-inspired decor with blue and white tones, and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 170,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-mykonos-1-room-0-King-MountainView",
    name: "Aegean King Studio",
    description: "A broad king retreat with a view of the mountains' rugged terrain, featuring Aegean-inspired decor with blue and white tones.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 301,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-mykonos-1-room-0-Single-GardenView",
    name: "Luxury Single Loft",
    description: "Luxury-themed loft with sophisticated decor, where you can find solace in nature's embrace, and including climate control for your comfort.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 160,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-mykonos-1-room-0-Single-CityView",
    name: "Superior Single Suite",
    description: "Our Superior-themed single suite offers extravagant luxury, panoramic with a view of iconic landmarks, and including climate control for your comfort, inspired by blending traditional style with luxurious amenities.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 156,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  }
];
