// Auto-generated file for panauti hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const panautiHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "info@maisonétoile.com",
      contactPhone: "+664 339-170-3432",
    },
    policies: {
      cancellation: "Free cancellation up to 48 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-panauti-1",
    name: "Maison Étoile",
    address: "73 Central Rd",
    rating: 3,
    accommodationType: "Eco-Lodge",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 22,
    isPetFriendly: false,
    currency: "NPR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hello@saltwindshoresinn.com",
      contactPhone: "+422 380-407-1534",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Designated Areas",
    },
    id: "hotel-panauti-2",
    name: "Saltwind Shores Inn",
    address: "175 West Queen Place",
    rating: 3,
    accommodationType: "Hostel",
    checkInTime: "13:00",
    checkOutTime: "11:00",
    roomsAvailable: 24,
    isPetFriendly: true,
    currency: "NPR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reachus@thelegacycorner.com",
      contactPhone: "+877 930-528-6010",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-panauti-3",
    name: "The Legacy Corner",
    address: "205 Liberty Terrace",
    rating: 4,
    accommodationType: "Boutique Inn",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 49,
    isPetFriendly: false,
    currency: "NPR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "admin@thecoastalinn.com",
      contactPhone: "+11 499-616-5666",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-panauti-4",
    name: "The Coastal Inn",
    address: "29 North Central Ave",
    rating: 3,
    accommodationType: "Motel",
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 38,
    isPetFriendly: false,
    currency: "NPR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "admin@midnightframeinn.com",
      contactPhone: "+304 336-257-4662",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-panauti-5",
    name: "Midnight Frame Inn",
    address: "115 North Park St",
    rating: 4,
    accommodationType: "Motel",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 59,
    isPetFriendly: true,
    currency: "NPR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "services@galleryrowhotel.com",
      contactPhone: "+755 783-854-9041",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Allowed",
    },
    id: "hotel-panauti-6",
    name: "Gallery Row Hotel",
    address: "99 Lower Park Blvd",
    rating: 4,
    accommodationType: "Motel",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 56,
    isPetFriendly: false,
    currency: "NPR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reachus@galleryrowhotel.com",
      contactPhone: "+479 862-547-8331",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Designated Areas",
    },
    id: "hotel-panauti-7",
    name: "Gallery Row Hotel",
    address: "8 King Avenue",
    rating: 4,
    accommodationType: "Luxury Hotel",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 42,
    isPetFriendly: false,
    currency: "NPR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "mail@tidebreakresort.com",
      contactPhone: "+251 530-677-8985",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    id: "hotel-panauti-8",
    name: "Tidebreak Resort",
    address: "184 Sunset Court",
    rating: 3,
    accommodationType: "Spa Hotel",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 55,
    isPetFriendly: true,
    currency: "NPR",
    isPopular: false,
  },
  {
    id: "hotel-panauti-9",
    name: "Forestlight Cabins",
    address: "214 Lower Riverside Way",
    rating: 3,
    accommodationType: "Spa Hotel",
    amenities: ["Bar", "Non-Smoking Rooms", "Fitness Center", "Free Wi-Fi", "Restaurant", "24-Hour Front Desk"],
    accessibilityFeatures: ["Hearing Loop", "Wheelchair Accessible"],
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 11,
    isPetFriendly: false,
    currency: "NPR",
    contact: {
      contactEmail: "reachus@forestlightcabins.com",
      contactPhone: "+199 626-970-5825",
    },
    policies: {
      cancellation: "Free cancellation up to 72 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Designated Areas",
    },
    isPopular: true,
  },
  {
    id: "hotel-panauti-10",
    name: "The Riverside Retreat",
    address: "281 New Queen St",
    rating: 3,
    accommodationType: "Hostel",
    amenities: ["Room Service", "Fitness Center", "Spa", "Swimming Pool", "Airport Shuttle"],
    accessibilityFeatures: ["Hearing Loop", "Elevator"],
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 25,
    isPetFriendly: false,
    currency: "NPR",
    contact: {
      contactEmail: "feedback@theriversideretreat.com",
      contactPhone: "+554 638-883-9545",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-panauti-11",
    name: "The ZeroPoint Retreat",
    address: "178 King Drive",
    rating: 3,
    accommodationType: "All-Inclusive Resort",
    amenities: ["Airport Shuttle", "Parking", "24-Hour Front Desk", "Fitness Center", "Laundry Service", "Spa", "Non-Smoking Rooms", "Conference Room"],
    accessibilityFeatures: ["Hearing Support"],
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 56,
    isPetFriendly: false,
    currency: "NPR",
    contact: {
      contactEmail: "admin@thezeropointretreat.com",
      contactPhone: "+207 966-977-7550",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Allowed",
    },
    isPopular: true,
  }
];
