import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Maison Étoile
export const maisontoileRooms: RoomOption[] = [
  {
    id: "hotel-panauti-1-room-0-Twin-CityView",
    name: "Deluxe Twin Loft",
    description: "Our spacious Deluxe-themed loft offers with a view of the city's cultural landmarks, comfortable comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids", "Elevator"],
    pricePerNight: 1728099,
    currency: "NPR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-panauti-1-room-0-Single-CityView",
    name: "Classic Single Apartment",
    description: "Step into a vast single apartment that combines Classic-themed with breathtaking overlooking the vibrant cityscape, complemented by with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 1340365,
    currency: "NPR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-panauti-1-room-0-Twin-OceanView",
    name: "Deluxe Twin Suite",
    description: "Enjoy a extravagant stay in our Deluxe-themed twin suite, offering with a private balcony overlooking the sea, with a private balcony or terrace, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 1829945,
    currency: "NPR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-panauti-1-room-0-Double-CityView",
    name: "Harmony Double Apartment",
    description: "This broad double accommodation offers with a window to the bustling city below, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 1868159,
    currency: "NPR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-panauti-1-room-0-Single-GardenView",
    name: "Classic Single Suite",
    description: "Unwind in this well-proportioned single suite where you can take in the fresh air, with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Accessible Bathroom", "Visual Aids"],
    pricePerNight: 1485263,
    currency: "NPR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-panauti-1-room-0-Double-OceanView",
    name: "Deluxe Double Apartment",
    description: "Deluxe-themed apartment with vast decor, where you can enjoy stunning sunsets over the water, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 2118551,
    currency: "NPR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-panauti-1-room-0-Queen-None",
    name: "Standard Queen Loft",
    description: "Standard-themed loft with elegant decor, with a pleasant outlook, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 2075958,
    currency: "NPR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-panauti-1-room-0-King-MountainView",
    name: "Classic King Loft",
    description: "Unwind in this classic king loft featuring awe-inspiring mountain scenery, featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids"],
    pricePerNight: 3044603,
    currency: "NPR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
