import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Apex Edinburgh Suites
export const apexEdinburghSuitesRooms: RoomOption[] = [
  {
    id: "hotel-southampton-12-room-11-Double-OceanView",
    name: "Signature Double Villa",
    description: "Our Signature-themed double villa offers stretching luxury, panoramic with a view of the ocean's horizon, and with carefully selected furnishings, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator"],
    pricePerNight: 105,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-southampton-12-room-11-SofaBed-CityView",
    name: "Classic Sofa Bed Loft",
    description: "Experience our restful, ornate sofa bed loft where you can enjoy the city's energy, with a private balcony or terrace.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 87,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-southampton-12-room-11-Single-GardenView",
    name: "Luxury Single Villa",
    description: "Discover the charm of this Luxury-themed single villa, complete with refreshing ambiance, stunning where you can escape to a green sanctuary, and with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 81,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-southampton-12-room-11-Double-MountainView",
    name: "Royal Double Apartment",
    description: "Indulge in the large-scale atmosphere of our double apartment, with spectacular with a view of the mountains' breathtaking sunsets, created with both style and function in mind, and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator", "Hearing Support"],
    pricePerNight: 93,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-southampton-12-room-11-SofaBed-None",
    name: "Victorian Sofa Bed Penthouse",
    description: "Relax in our majestic sizable sofa bed penthouse featuring with a pleasant outlook, along with equipped with all the modern conveniences and created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 76,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-southampton-12-room-11-Queen-GardenView",
    name: "Classic Queen Room",
    description: "Our futuristic Classic-themed room offers where you can escape to a green sanctuary, retro comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 118,
    currency: "GBP",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-southampton-12-room-11-Twin-GardenView",
    name: "Piccadilly Twin Studio",
    description: "Step into a palatial twin studio that combines Piccadilly-themed with breathtaking where you can unwind in a garden paradise, complemented by with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 82,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-southampton-12-room-11-Queen-MountainView",
    name: "Signature Queen Room",
    description: "Step into a chic queen room that combines Signature-themed with breathtaking overlooking spectacular mountain ranges, complemented by with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 129,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  }
];
