import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Bamboo Horizon Resort
export const bambooHorizonResortRooms: RoomOption[] = [
  {
    id: "hotel-southampton-2-room-1-Single-GardenView",
    name: "Deluxe Single Loft",
    description: "Indulge in the extensive atmosphere of our single loft, with spectacular where you can enjoy the tranquility of nature, featuring thoughtful design elements, and with carefully selected furnishings.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 166,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-southampton-2-room-1-King-GardenView",
    name: "Executive King Studio",
    description: "Our sleek Executive-themed studio offers surrounded by vibrant flora, stretching comfort, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 353,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-southampton-2-room-1-Twin-OceanView",
    name: "Standard Twin Suite",
    description: "Discover the charm of this Standard-themed twin suite, complete with deluxe ambiance, stunning with a view of the sandy beaches, and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 231,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-southampton-2-room-1-SofaBed-MountainView",
    name: "Executive Sofa Bed Loft",
    description: "Indulge in the luxurious atmosphere of our sofa bed loft, with spectacular where you can enjoy the peace of the highlands, decorated with local artistic influences, and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 217,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-southampton-2-room-1-Double-GardenView",
    name: "Luxury Double Room",
    description: "This contemporary double accommodation offers where nature is just outside your window, decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 217,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-southampton-2-room-1-Queen-None",
    name: "Standard Queen Loft",
    description: "Our Standard-themed queen loft offers traditional luxury, panoramic with a pleasant outlook, and featuring a curated minibar selection, inspired by decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 249,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-southampton-2-room-1-Twin-GardenView",
    name: "Standard Twin Studio",
    description: "Enjoy a calming stay in our Standard-themed twin studio, offering with a view of the garden's tranquil pathways, with blackout curtains for a perfect night's sleep, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Accessible Bathroom", "Hearing Support"],
    pricePerNight: 206,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  }
];
