// Auto-generated file for southampton hotels
import { Hotel } from "@/lib/interfaces/services/rentals";

export const southamptonHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "info@theregenthotel.com",
      contactPhone: "+148 538-953-6156",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-southampton-1",
    name: "The Regent Hotel",
    address: "241 George Blvd",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 24,
    isPetFriendly: true,
    currency: "GBP",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "welcome@theabbeycourt.com",
      contactPhone: "+854 953-481-4282",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Not Allowed",
    },
    id: "hotel-southampton-2",
    name: "The Abbey Court",
    address: "223 High Drive",
    rating: 3,
    accommodationType: "Boutique Resort",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 16,
    isPetFriendly: false,
    currency: "GBP",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "feedback@theregenthotel.com",
      contactPhone: "+803 383-542-6353",
    },
    policies: {
      cancellation: "50% refund for cancellations made at least 7 days before check-in.",
      smoking: "Not Allowed",
    },
    id: "hotel-southampton-3",
    name: "The Regent Hotel",
    address: "59 North Station St",
    rating: 4,
    accommodationType: "Boutique Hotel",
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 44,
    isPetFriendly: true,
    currency: "GBP",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "feedback@royalcrescenthotel.com",
      contactPhone: "+167 470-519-3484",
    },
    policies: {
      cancellation: "No refunds for cancellations.",
      smoking: "Designated Areas",
    },
    id: "hotel-southampton-4",
    name: "Royal Crescent Hotel",
    address: "26 New George Blvd",
    rating: 4,
    accommodationType: "Extended Stay Hotel",
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 38,
    isPetFriendly: false,
    currency: "GBP",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "office@windsorhouse.com",
      contactPhone: "+633 854-650-5356",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-southampton-5",
    name: "Windsor House",
    address: "80 Upper Victoria Blvd",
    rating: 3,
    accommodationType: "Boutique Hotel",
    checkInTime: "15:00",
    checkOutTime: "10:00",
    roomsAvailable: 35,
    isPetFriendly: false,
    currency: "GBP",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "contact@hampshirehall.com",
      contactPhone: "+726 883-212-3411",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Not Allowed",
    },
    id: "hotel-southampton-6",
    name: "Hampshire Hall",
    address: "108 London Drive",
    rating: 4,
    accommodationType: "Serviced Apartment",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 53,
    isPetFriendly: true,
    currency: "GBP",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "mail@theabbeycourt.com",
      contactPhone: "+111 646-307-6949",
    },
    policies: {
      cancellation: "Cancellation fee equivalent to one night's stay if cancelled less than 48 hours before check-in.",
      smoking: "Designated Areas",
    },
    id: "hotel-southampton-7",
    name: "The Abbey Court",
    address: "41 Queen Road",
    rating: 4,
    accommodationType: "Guesthouse",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 17,
    isPetFriendly: true,
    currency: "GBP",
    isPopular: false,
  },
  {
    id: "hotel-southampton-8",
    name: "Greenwich Grand",
    address: "158 East Station St",
    rating: 3,
    accommodationType: "All-Inclusive Resort",
    amenities: ["Bar", "Parking", "Conference Room", "Laundry Service", "Swimming Pool", "Room Service", "Business Center", "Restaurant", "Free Wi-Fi", "24-Hour Front Desk"],
    accessibilityFeatures: ["Sign Language Interpretation"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 18,
    isPetFriendly: false,
    currency: "GBP",
    contact: {
      contactEmail: "care@greenwichgrand.com",
      contactPhone: "+799 639-594-6898",
    },
    policies: {
      cancellation: "Flexible cancellation policy: free cancellation up to 12 hours before check-in.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-southampton-9",
    name: "The Mayfair Inn",
    address: "102 West George Ave",
    rating: 3,
    accommodationType: "Eco-Lodge",
    amenities: ["Non-Smoking Rooms", "24-Hour Front Desk", "Bar", "Parking", "Airport Shuttle", "Spa", "Free Wi-Fi"],
    checkInTime: "13:00",
    checkOutTime: "12:00",
    roomsAvailable: 46,
    isPetFriendly: false,
    currency: "GBP",
    contact: {
      contactEmail: "office@themayfairinn.com",
      contactPhone: "+541 441-148-8781",
    },
    policies: {
      cancellation: "Free cancellation within 24 hours of booking; after that, 25% fee applies.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  },
  {
    id: "hotel-southampton-10",
    name: "Windsor House",
    address: "249 Queen Street",
    rating: 4,
    accommodationType: "Hostel",
    amenities: ["Free Wi-Fi", "Swimming Pool", "Parking", "Airport Shuttle", "Business Center", "Laundry Service", "Fitness Center"],
    accessibilityFeatures: ["Accessible Shower"],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    roomsAvailable: 19,
    isPetFriendly: true,
    currency: "GBP",
    contact: {
      contactEmail: "contact@windsorhouse.com",
      contactPhone: "+260 846-126-3441",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Designated Areas",
    },
    isPopular: false,
  }
];
