import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Windsor House
export const windsorHouseRooms: RoomOption[] = [
  {
    id: "hotel-southampton-6-room-5",
    name: "Westminster Twin Room",
    description:
      "Step into a well-proportioned twin room that combines Westminster-themed with breathtaking offering a peaceful garden outlook, complemented by with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Fitness Equipment",
      "In-Room Safe",
      "Jacuzzi Tub",
      "Connecting Rooms",
      "Bluetooth Speaker",
      "Seating Area",
    ],
    accessibilityFeatures: ["Wheelchair Accessible", "Hearing Support"],
    pricePerNight: 112,
    currency: "GBP",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-southampton-6-room-5",
    name: "Piccadilly Twin Room",
    description:
      "Indulge in the inviting atmosphere of our twin room, with spectacular featuring a blend of modern and historic architecture, created with both style and function in mind, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: [
      "Desk",
      "Free Wi-Fi",
      "Room Service",
      "Hair Dryer",
      "Toiletries",
      "Microwave",
      "Shower",
      "Heating",
      "Coffee Maker",
      "Slippers",
      "Bathrobe",
      "Room Service",
      "Alarm Clock",
      "Desk Lamp",
      "Daily Housekeeping",
      "Non-Smoking Room",
      "Television",
      "Air Conditioning",
      "Balcony",
      "Ironing Facilities",
      "Mini Bar",
      "Dining Table",
    ],
    pricePerNight: 101,
    currency: "GBP",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
];
