// Auto-generated file for bali hotels
// Do not edit manually, use scripts/generate-hotels.mjs to update

// Generated on: 2025-06-08T04:09:38.918Z

import { Hotel } from "@/lib/interfaces/services/rentals";

export const baliHotels: Hotel[] = [
  {
    amenities: [],
    contact: {
      contactEmail: "admin@shangri-lahotel,jakarta.com",
      contactPhone: "+581 337-272-4356",
    },
    policies: {
      cancellation: "Free cancellation up to 24 hours before check-in. If cancelled later, the first night will be charged.",
      smoking: "Allowed",
    },
    id: "hotel-bali-1",
    name: "Shangri-La Hotel, Jakarta",
    address: "231 Jalan Ubud Lorong",
    rating: 4,
    accommodationType: "Family Resort",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    roomsAvailable: 11,
    isPetFriendly: false,
    currency: "IDR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "connect@amanjiwo.com",
      contactPhone: "+219 981-437-7463",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Designated Areas",
    },
    id: "hotel-bali-2",
    name: "Amanjiwo",
    address: "68 Jalan Jalan Malioboro Lorong",
    rating: 3,
    accommodationType: "Luxury Lodge",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 44,
    isPetFriendly: false,
    currency: "IDR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "office@kayumanisjimbaranprivateestate.com",
      contactPhone: "+725 855-646-8652",
    },
    policies: {
      cancellation: "Free cancellation up to 14 days before check-in; 50% refund for cancellations made within 14 days.",
      smoking: "Designated Areas",
    },
    id: "hotel-bali-3",
    name: "Kayumanis Jimbaran Private Estate",
    address: "249 Jalan Gatot Subroto Boulevard",
    rating: 4,
    accommodationType: "Eco-Lodge",
    checkInTime: "13:00",
    checkOutTime: "10:00",
    roomsAvailable: 41,
    isPetFriendly: false,
    currency: "IDR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "info@theapurvakempinskibali.com",
      contactPhone: "+261 481-255-6677",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Allowed",
    },
    id: "hotel-bali-4",
    name: "The Apurva Kempinski Bali",
    address: "188 Lorong Jalan Hayam Wuruk Gang",
    rating: 4,
    accommodationType: "Serviced Apartment",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 56,
    isPetFriendly: true,
    currency: "IDR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "care@yogyakartaheritagelodge.com",
      contactPhone: "+74 190-383-5720",
    },
    policies: {
      cancellation: "Cancellation made less than 3 days before check-in will incur a 75% charge.",
      smoking: "Not Allowed",
    },
    id: "hotel-bali-5",
    name: "Yogyakarta Heritage Lodge",
    address: "126 Gang Jalan Hayam Wuruk Boulevard",
    rating: 3,
    accommodationType: "Extended Stay Hotel",
    checkInTime: "16:00",
    checkOutTime: "11:00",
    roomsAvailable: 45,
    isPetFriendly: false,
    currency: "IDR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hello@fairmontjakarta.com",
      contactPhone: "+442 425-447-7350",
    },
    policies: {
      cancellation: "Partial refund available if cancelled more than 5 days in advance.",
      smoking: "Designated Areas",
    },
    id: "hotel-bali-6",
    name: "Fairmont Jakarta",
    address: "115 Kecamatan Jalan Gatot Subroto Gang",
    rating: 3,
    accommodationType: "Glamping Resort",
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 51,
    isPetFriendly: false,
    currency: "IDR",
    isPopular: false,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "communications@thegigglinggecko.com",
      contactPhone: "+12 100-189-5953",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Not Allowed",
    },
    id: "hotel-bali-7",
    name: "The Giggling Gecko",
    address: "28 Kecamatan Jalan Malioboro Gang",
    rating: 3,
    accommodationType: "Luxury Hotel",
    checkInTime: "14:00",
    checkOutTime: "10:00",
    roomsAvailable: 44,
    isPetFriendly: false,
    currency: "IDR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "reachus@thesilkysarong.com",
      contactPhone: "+119 489-295-8096",
    },
    policies: {
      cancellation: "Full refund if cancelled within 48 hours of booking, minus service fees.",
      smoking: "Designated Areas",
    },
    id: "hotel-bali-8",
    name: "The Silky Sarong",
    address: "8 Jalan Thamrin Gang",
    rating: 3,
    accommodationType: "Extended Stay Hotel",
    checkInTime: "16:00",
    checkOutTime: "10:00",
    roomsAvailable: 52,
    isPetFriendly: false,
    currency: "IDR",
    isPopular: true,
  },
  {
    amenities: [],
    contact: {
      contactEmail: "hi@mandarinorientaljakarta.com",
      contactPhone: "+290 594-607-3128",
    },
    policies: {
      cancellation: "No cancellation fee if rebooking within 30 days; otherwise, fees apply.",
      smoking: "Not Allowed",
    },
    id: "hotel-bali-9",
    name: "Mandarin Oriental Jakarta",
    address: "45 Jalan Diponegoro Gang",
    rating: 3,
    accommodationType: "All-Inclusive Resort",
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 58,
    isPetFriendly: true,
    currency: "IDR",
    isPopular: false,
  },
  {
    id: "hotel-bali-10",
    name: "Four Seasons Resort Bali",
    address: "191 Jalan Malioboro Gang",
    rating: 4,
    accommodationType: "Spa Hotel",
    amenities: ["Spa", "Room Service", "Conference Room", "Restaurant", "Fitness Center", "Parking"],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    roomsAvailable: 59,
    isPetFriendly: false,
    currency: "IDR",
    contact: {
      contactEmail: "contact@fourseasonsresortbali.com",
      contactPhone: "+573 188-822-2272",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-bali-11",
    name: "InterContinental Bali Resort",
    address: "161 Jalan Ubud Boulevard",
    rating: 4,
    accommodationType: "Hotel",
    amenities: ["Room Service", "Airport Shuttle", "Restaurant", "Free Wi-Fi", "Spa", "Non-Smoking Rooms"],
    accessibilityFeatures: ["Accessible Shower"],
    checkInTime: "16:00",
    checkOutTime: "12:00",
    roomsAvailable: 48,
    isPetFriendly: false,
    currency: "IDR",
    contact: {
      contactEmail: "clientservices@intercontinentalbaliresort.com",
      contactPhone: "+154 278-194-6631",
    },
    policies: {
      cancellation: "Non-refundable; full amount charged at time of booking.",
      smoking: "Not Allowed",
    },
    isPopular: false,
  },
  {
    id: "hotel-bali-12",
    name: "The Borneo Jungle Lodge",
    address: "253 Jalan Legian Lorong",
    rating: 3,
    accommodationType: "Boutique Resort",
    amenities: ["Fitness Center", "Restaurant", "Swimming Pool", "Business Center", "Parking", "24-Hour Front Desk", "Bar", "Non-Smoking Rooms", "Laundry Service"],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    roomsAvailable: 20,
    isPetFriendly: false,
    currency: "IDR",
    contact: {
      contactEmail: "support@theborneojunglelodge.com",
      contactPhone: "+205 797-158-5953",
    },
    policies: {
      cancellation: "Free cancellation up to 7 days before arrival; no refund after that.",
      smoking: "Allowed",
    },
    isPopular: false,
  }
];
