import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Kayumanis Jimbaran Private Estate
export const kayumanisJimbaranPrivateEstateRooms: RoomOption[] = [
  {
    id: "hotel-bali-3-room-2-Queen-OceanView",
    name: "Bali Queen Room",
    description: "A lavish queen room designed for serene comfort, with where you can enjoy the ocean's beauty and featuring premium bath amenities, reflecting decorated with handcrafted local motifs.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    accessibilityFeatures: ["Elevator", "Visual Aids"],
    pricePerNight: 96717054885,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-bali-3-room-2-Queen-MountainView",
    name: "Premium Queen Apartment",
    description: "A lavish queen retreat overlooking spectacular mountain ranges, decorated with handcrafted local motifs.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 88928633360,
    currency: "IDR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-bali-3-room-2-Single-GardenView",
    name: "Island Breeze Single Studio",
    description: "Enjoy a well-proportioned stay in our Island Breeze-themed single studio, offering with a view of the garden's vibrant colors, featuring premium bath amenities, and unique touches of blending tropical elements with luxurious comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 50253682014,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-bali-3-room-2-Double-OceanView",
    name: "Signature Double Studio",
    description: "Our peaceful Signature-themed studio offers with a view of the endless blue, restful comfort, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 78522282613,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-bali-3-room-2-Double-CityView",
    name: "Deluxe Double Loft",
    description: "This luxurious double loft promises with a front-row seat to the city's heartbeat, enriched by Deluxe-themed details and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 62167687145,
    currency: "IDR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-bali-3-room-2-Single-None",
    name: "Executive Single Villa",
    description: "Discover the charm of this Executive-themed single villa, complete with sophisticated ambiance, stunning with a pleasant outlook, and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 42630587783,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-bali-3-room-2-Twin-MountainView",
    name: "Superior Twin Penthouse",
    description: "Enjoy a tasteful stay in our Superior-themed twin penthouse, offering overlooking spectacular mountain ranges, including climate control for your comfort, and unique touches of featuring Balinese art and natural materials.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 65235243216,
    currency: "IDR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-bali-3-room-2-SofaBed-None",
    name: "Garuda Sofa Bed Room",
    description: "A lavish sofa bed room designed for cozy comfort, with with a pleasant outlook and equipped with all the modern conveniences, reflecting featuring Balinese art and natural materials.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 49915516524,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  }
];
