import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Prestige Hotel
export const thePrestigeHotelRooms: RoomOption[] = [
  {
    id: "hotel-bali-2-room-1-Single-OceanView",
    name: "Bali Single Penthouse",
    description: "Bali-themed single penthouse where you can hear the soothing sound of the sea, highlighting island-inspired tranquility and with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 53041304502,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-bali-2-room-1-King-None",
    name: "Premium King Suite",
    description: "Premium-themed king suite with a pleasant outlook, featuring Balinese art and natural materials and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 75768221890,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-bali-2-room-1-Queen-OceanView",
    name: "Executive Queen Loft",
    description: "Enjoy a bohemian stay in our Executive-themed queen loft, offering with a private balcony overlooking the sea, with blackout curtains for a perfect night's sleep, and unique touches of decorated with handcrafted local motifs.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 77667760141,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-bali-2-room-1-Twin-CityView",
    name: "Classic Twin Villa",
    description: "Indulge in the vintage atmosphere of our twin villa, with spectacular where you can watch the city wake up, decorated with handcrafted local motifs, and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 46306066039,
    currency: "IDR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-bali-2-room-1-Double-OceanView",
    name: "Superior Double Loft",
    description: "Experience our stretching, welcoming double loft where the horizon meets the ocean, with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 66730615305,
    currency: "IDR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  }
];
