import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Pattaya Ocean View Hotel
export const pattayaOceanViewHotelRooms: RoomOption[] = [
  {
    id: "hotel-ayutthaya-5-room-4-Single-CityView",
    name: "Premium Single Suite",
    description: "Enjoy a room-filled stay in our Premium-themed single suite, offering with stunning views of the city skyline, complete with a well-appointed bathroom, and unique touches of adorned with Thai-inspired decor.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 243083,
    currency: "THB",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-ayutthaya-5-room-4-SofaBed-MountainView",
    name: "Orchid Sofa Bed Suite",
    description: "A deluxe sofa bed suite designed for retro comfort, with with a view of the rugged mountain landscape and with carefully selected furnishings, reflecting adorned with Thai-inspired decor.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 285089,
    currency: "THB",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-ayutthaya-5-room-4-King-OceanView",
    name: "Jasmine King Penthouse",
    description: "Jasmine-themed king penthouse where you can hear the soothing sound of the sea, with subtle nods to Thailand's rich cultural heritage and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 448854,
    currency: "THB",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-ayutthaya-5-room-4-Single-OceanView",
    name: "Siam Single Apartment",
    description: "Enjoy a wide-ranging stay in our Siam-themed single apartment, offering featuring uninterrupted ocean vistas, with a luxurious soaking tub, and unique touches of adorned with Thai-inspired decor.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 253346,
    currency: "THB",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-ayutthaya-5-room-4-Queen-MountainView",
    name: "Signature Queen Penthouse",
    description: "Our soothing Signature-themed penthouse offers with panoramic views of the mountain landscape, roomy comfort, and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 406115,
    currency: "THB",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-ayutthaya-5-room-4-Double-CityView",
    name: "Signature Double Penthouse",
    description: "This glamorous double accommodation offers with a window to the bustling city below, with subtle nods to Thailand's rich cultural heritage.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 284520,
    currency: "THB",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-ayutthaya-5-room-4-Single-MountainView",
    name: "Deluxe Single Penthouse",
    description: "Discover the charm of this Deluxe-themed single penthouse, complete with comfortable ambiance, stunning with a view of the rugged mountain landscape, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 280800,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-ayutthaya-5-room-4-King-CityView",
    name: "Luxury King Penthouse",
    description: "A elegant king penthouse designed for stylish comfort, with with a view of the city's waterfront and with a spacious work area, reflecting blending Thai elegance with modern comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 429585,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-ayutthaya-5-room-4-King-None",
    name: "Superior King Villa",
    description: "A bohemian king retreat with a pleasant outlook, with subtle nods to Thailand's rich cultural heritage.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 399270,
    currency: "THB",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-ayutthaya-5-room-4-Single-None",
    name: "Thai Single Villa",
    description: "Relax in our fashionable soothing single villa featuring with a pleasant outlook, along with equipped with all the modern conveniences and with subtle nods to Thailand's rich cultural heritage.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 205954,
    currency: "THB",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  }
];
