import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Prestige Hotel
export const thePrestigeHotelRooms: RoomOption[] = [
  {
    id: "hotel-athens-3-room-2-King-OceanView",
    name: "Horizon King Suite",
    description: "A sizable king retreat with a view of the ocean's changing tides, featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 165,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-athens-3-room-2-Twin-OceanView",
    name: "Classic Twin Room",
    description: "Step into a artistic twin room that combines Classic-themed with breathtaking where the horizon meets the ocean, complemented by with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 106,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-athens-3-room-2-Twin-None",
    name: "Executive Twin Villa",
    description: "Enjoy a ornate stay in our Executive-themed twin villa, offering with a pleasant outlook, with a spacious work area, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 73,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-athens-3-room-2-SofaBed-OceanView",
    name: "Premium Sofa Bed Villa",
    description: "Discover the charm of this Premium-themed sofa bed villa, complete with sophisticated ambiance, stunning with a panoramic view of the coastline, and with a spacious work area.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 109,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-athens-3-room-2-SofaBed-None",
    name: "Luxury Sofa Bed Penthouse",
    description: "A large-scale sofa bed penthouse designed for bohemian comfort, with with a pleasant outlook and with a luxurious soaking tub, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 70,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-athens-3-room-2-SofaBed-CityView",
    name: "Classic Sofa Bed Apartment",
    description: "A broad sofa bed apartment designed for vast comfort, with where city lights twinkle at night and featuring premium bath amenities, reflecting featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids"],
    pricePerNight: 83,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-athens-3-room-2-Queen-GardenView",
    name: "Horizon Queen Studio",
    description: "Step into a opulent queen studio that combines Horizon-themed with breathtaking with a view of tranquil water features, complemented by with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 116,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-athens-3-room-2-Single-None",
    name: "Harmony Single Suite",
    description: "Enjoy a soothing stay in our Harmony-themed single suite, offering with a pleasant outlook, featuring premium bath amenities, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 73,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-athens-3-room-2-Twin-GardenView",
    name: "Signature Twin Suite",
    description: "This stylish twin suite promises surrounded by vibrant flora, enriched by Signature-themed details and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 81,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  }
];
