import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Arendal Archipelago Suites
export const arendalArchipelagoSuitesRooms: RoomOption[] = [
  {
    id: "hotel-oslo-3-room-2-Single-OceanView",
    name: "Harmony Single Studio",
    description: "Enjoy a sumptuous stay in our Harmony-themed single studio, offering with a view of the ocean's horizon, with plush bedding for ultimate comfort, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 22017,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-oslo-3-room-2-Double-OceanView",
    name: "Standard Double Loft",
    description: "Experience our luxurious, intimate double loft where you can enjoy stunning sunsets over the water, with high-speed internet access.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 26993,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-oslo-3-room-2-Single-GardenView",
    name: "Classic Single Studio",
    description: "Indulge in the wide-ranging atmosphere of our single studio, with spectacular with a view of shaded garden paths, designed for ultimate comfort, and with high-speed internet access.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 20690,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-oslo-3-room-2-Queen-GardenView",
    name: "Harmony Queen Studio",
    description: "Enjoy a calming stay in our Harmony-themed queen studio, offering featuring a peaceful garden setting, with a private balcony or terrace, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 32310,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  }
];
