import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Halden Fortress View
export const haldenFortressViewRooms: RoomOption[] = [
  {
    id: "hotel-oslo-10-room-9-Single-MountainView",
    name: "Superior Single Villa",
    description: "Superior-themed villa with expansive decor, where the mountains touch the sky, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 12099,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-oslo-10-room-9-Single-CityView",
    name: "Classic Single Villa",
    description: "Experience our roomy, traditional single villa where the city comes alive at dusk, offering a unique blend of style and comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 9022,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-oslo-10-room-9-SofaBed-MountainView",
    name: "Deluxe Sofa Bed Room",
    description: "Deluxe-themed sofa bed room with a view of the mountains' breathtaking sunsets, created with both style and function in mind and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 13095,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-oslo-10-room-9-King-CityView",
    name: "Classic King Villa",
    description: "Indulge in the exquisite atmosphere of our king villa, with spectacular with stunning views of the city skyline, designed for ultimate comfort, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 16771,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-oslo-10-room-9-Single-None",
    name: "Harmony Single Apartment",
    description: "This pleasant single accommodation offers with a pleasant outlook, decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 9644,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-oslo-10-room-9-Queen-OceanView",
    name: "Standard Queen Loft",
    description: "Standard-themed loft with indulgent decor, with a view of the tranquil sea, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 16636,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-oslo-10-room-9-Twin-OceanView",
    name: "Deluxe Twin Penthouse",
    description: "Enjoy a eclectic stay in our Deluxe-themed twin penthouse, offering with a view of the ocean's horizon, featuring premium bath amenities, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Accessible Bathroom", "Elevator", "Hearing Support"],
    pricePerNight: 12935,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  }
];
