import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Kautokeino Sami Cultural Inn
export const kautokeinoSamiCulturalInnRooms: RoomOption[] = [
  {
    id: "hotel-oslo-9-room-8-King-MountainView",
    name: "Serenity King Loft",
    description: "A classic king retreat where you can experience the beauty of nature, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 43706,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-oslo-9-room-8-King-OceanView",
    name: "Luxury King Penthouse",
    description: "Our extensive Luxury-themed penthouse offers overlooking the sparkling ocean waves, comfortable comfort, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 47478,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-oslo-9-room-8-King-CityView",
    name: "Signature King Villa",
    description: "A comfy king retreat with a view of the city's cultural landmarks, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 38501,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-oslo-9-room-8-SofaBed-MountainView",
    name: "Deluxe Sofa Bed Loft",
    description: "Relax in our calming traditional sofa bed loft featuring with a view of the mountains' rugged terrain, along with with a spacious work area and decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 31497,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-oslo-9-room-8-Double-OceanView",
    name: "Signature Double Suite",
    description: "Unwind in this futuristic double suite overlooking the sparkling ocean waves, featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 35214,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-oslo-9-room-8-Twin-MountainView",
    name: "Signature Twin Loft",
    description: "Our Signature-themed twin loft offers sumptuous luxury, panoramic with a view of the mountains' rugged terrain, and including climate control for your comfort, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 27234,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-oslo-9-room-8-Twin-OceanView",
    name: "Standard Twin Suite",
    description: "This opulent twin suite promises where the horizon meets the ocean, enriched by Standard-themed details and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 32798,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-oslo-9-room-8-King-None",
    name: "Harmony King Suite",
    description: "Enjoy a palatial stay in our Harmony-themed king suite, offering with a pleasant outlook, with blackout curtains for a perfect night's sleep, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 34136,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-oslo-9-room-8-King-GardenView",
    name: "Classic King Room",
    description: "This compact king room promises where you can enjoy the beauty of nature, enriched by Classic-themed details and equipped with all the modern conveniences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 44351,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  }
];
