import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Ålesund Art Nouveau Inn
export const lesundArtNouveauInnRooms: RoomOption[] = [
  {
    id: "hotel-oslo-7-room-6-Twin-OceanView",
    name: "Premium Twin Apartment",
    description: "Experience our spacious, stylish twin apartment featuring uninterrupted ocean vistas, with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 26681,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-oslo-7-room-6-Twin-None",
    name: "Classic Twin Penthouse",
    description: "Discover the charm of this Classic-themed twin penthouse, complete with lavish ambiance, stunning with a pleasant outlook, and with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 21078,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-oslo-7-room-6-Queen-None",
    name: "Horizon Queen Loft",
    description: "Horizon-themed loft with inviting decor, with a pleasant outlook, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 28278,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-oslo-7-room-6-Single-CityView",
    name: "Deluxe Single Studio",
    description: "Deluxe-themed studio with extravagant decor, offering panoramic city vistas, and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 17582,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-oslo-7-room-6-SofaBed-OceanView",
    name: "Premium Sofa Bed Penthouse",
    description: "Experience our cozy, rustic sofa bed penthouse with a panoramic view of the coastline, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 23661,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-oslo-7-room-6-Twin-CityView",
    name: "Luxury Twin Apartment",
    description: "Experience our classic, traditional twin apartment offering panoramic city vistas, featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 20367,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-oslo-7-room-6-Double-CityView",
    name: "Signature Double Suite",
    description: "Enjoy a eclectic stay in our Signature-themed double suite, offering where the city comes alive at dusk, with blackout curtains for a perfect night's sleep, and unique touches of created with both style and function in mind.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 24849,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-oslo-7-room-6-Double-GardenView",
    name: "Tranquility Double Room",
    description: "Relax in our compact sizable double room featuring where you can find solace in nature's embrace, along with including climate control for your comfort and decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 26571,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  }
];
