import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Sortland Blue Town Hotel
export const sortlandBlueTownHotelRooms: RoomOption[] = [
  {
    id: "hotel-oslo-2-room-1-SofaBed-None",
    name: "Deluxe Sofa Bed Suite",
    description: "Our avant-garde Deluxe-themed suite offers with a pleasant outlook, room-filled comfort, and with blackout curtains for a perfect night's sleep.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Elevator"],
    pricePerNight: 17361,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-oslo-2-room-1-Single-MountainView",
    name: "Standard Single Studio",
    description: "Relax in our plush sophisticated single studio featuring where you can find inspiration in the mountains, along with complete with a well-appointed bathroom and decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 16479,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 8,
  },
  {
    id: "hotel-oslo-2-room-1-Single-OceanView",
    name: "Luxury Single Room",
    description: "Enjoy a vast stay in our Luxury-themed single room, offering with a view of the sandy beaches, with a spacious seating area, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 18899,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-oslo-2-room-1-Double-MountainView",
    name: "Luxury Double Villa",
    description: "This spacious double accommodation offers with a view of the mountains' serene beauty, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 23129,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-oslo-2-room-1-Double-OceanView",
    name: "Executive Double Penthouse",
    description: "Enjoy a glamorous stay in our Executive-themed double penthouse, offering where you can enjoy stunning sunsets over the water, with plush bedding for ultimate comfort, and unique touches of designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Visual Aids", "Accessible Bathroom", "Elevator"],
    pricePerNight: 24694,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-oslo-2-room-1-King-CityView",
    name: "Signature King Suite",
    description: "This futuristic king suite promises overlooking the vibrant cityscape, enriched by Signature-themed details and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 25182,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-oslo-2-room-1-Queen-None",
    name: "Classic Queen Apartment",
    description: "Indulge in the airy atmosphere of our queen apartment, with spectacular with a pleasant outlook, featuring thoughtful design elements, and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 22772,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-oslo-2-room-1-Single-None",
    name: "Harmony Single Room",
    description: "Discover the charm of this Harmony-themed single room, complete with eclectic ambiance, stunning with a pleasant outlook, and with high-speed internet access.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 13222,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-oslo-2-room-1-SofaBed-CityView",
    name: "Executive Sofa Bed Suite",
    description: "Unwind in this avant-garde sofa bed suite with a window to the bustling city below, with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 16833,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  }
];
