import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Trondheim Viking Harbor Hotel
export const trondheimVikingHarborHotelRooms: RoomOption[] = [
  {
    id: "hotel-oslo-4-room-3-Twin-CityView",
    name: "Serenity Twin Room",
    description: "Experience our wide-ranging, commodious twin room featuring a blend of modern and historic architecture, including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    pricePerNight: 19879,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-oslo-4-room-3-Queen-None",
    name: "Luxury Queen Studio",
    description: "This wide-ranging queen accommodation offers with a pleasant outlook, designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Wheelchair Accessible"],
    pricePerNight: 24180,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-oslo-4-room-3-King-OceanView",
    name: "Serenity King Villa",
    description: "Unwind in this majestic king villa with the sound of the ocean as your backdrop, with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 39211,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-oslo-4-room-3-Double-GardenView",
    name: "Horizon Double Studio",
    description: "Horizon-themed double studio where you can escape to a green sanctuary, created with both style and function in mind and with a private balcony or terrace.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 25791,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-oslo-4-room-3-Queen-MountainView",
    name: "Superior Queen Room",
    description: "Relax in our futuristic intimate queen room featuring overlooking spectacular mountain ranges, along with including climate control for your comfort and featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 35513,
    currency: "NOK",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-oslo-4-room-3-Twin-OceanView",
    name: "Harmony Twin Studio",
    description: "Step into a classic twin studio that combines Harmony-themed with breathtaking where you can enjoy the ocean's beauty, complemented by with a luxurious soaking tub.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    accessibilityFeatures: ["Hearing Support"],
    pricePerNight: 26938,
    currency: "NOK",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
