import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Hvar Island Retreat
export const hvarIslandRetreatRooms: RoomOption[] = [
  {
    id: "hotel-dubrovnik-5-room-4-SofaBed-GardenView",
    name: "Deluxe Sofa Bed Loft",
    description: "Deluxe-themed loft with restful decor, with a view of the garden's peaceful ambiance, and with a luxurious soaking tub.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 175,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-dubrovnik-5-room-4-Queen-OceanView",
    name: "Premium Queen Penthouse",
    description: "This comfy queen penthouse promises where the horizon meets the ocean, enriched by Premium-themed details and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 273,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 6,
  },
  {
    id: "hotel-dubrovnik-5-room-4-SofaBed-OceanView",
    name: "Superior Sofa Bed Studio",
    description: "A snug sofa bed retreat overlooking the sparkling ocean waves, blending traditional Croatian style with contemporary design.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 207,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-dubrovnik-5-room-4-King-None",
    name: "Superior King Apartment",
    description: "A extensive king apartment designed for stretching comfort, with with a pleasant outlook and with a modern en-suite bathroom, reflecting blending traditional Croatian style with contemporary design.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator", "Accessible Bathroom"],
    pricePerNight: 225,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-dubrovnik-5-room-4-SofaBed-None",
    name: "Deluxe Sofa Bed Suite",
    description: "Our Deluxe-themed sofa bed suite offers traditional luxury, panoramic with a pleasant outlook, and featuring premium bath amenities, inspired by featuring coastal-inspired decor with Mediterranean influences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 141,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-dubrovnik-5-room-4-Twin-None",
    name: "Classic Twin Room",
    description: "Classic-themed twin room with a pleasant outlook, offering a unique Adriatic experience with a touch of luxury and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 165,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-dubrovnik-5-room-4-Double-OceanView",
    name: "Dubrovnik Double Penthouse",
    description: "Dubrovnik-themed double penthouse with a view of the sandy beaches, offering a unique Adriatic experience with a touch of luxury and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 208,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-dubrovnik-5-room-4-Twin-OceanView",
    name: "Standard Twin Apartment",
    description: "Step into a soft twin apartment that combines Standard-themed with breathtaking with the sound of the ocean as your backdrop, complemented by with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Wheelchair Accessible", "Elevator"],
    pricePerNight: 198,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-dubrovnik-5-room-4-Single-CityView",
    name: "Standard Single Room",
    description: "Experience our indulgent, exquisite single room where you can watch the city wake up, with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 163,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
