import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Apeldoorn Green Suites
export const apeldoornGreenSuitesRooms: RoomOption[] = [
  {
    id: "hotel-amsterdam-2-room-1-Double-MountainView",
    name: "Premium Double Villa",
    description: "Premium-themed double villa with a view of the mountains' serene beauty, featuring modern design with Dutch influences and with a spacious work area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 157,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-amsterdam-2-room-1-Double-GardenView",
    name: "Deluxe Double Penthouse",
    description: "Deluxe-themed penthouse with comfortable decor, where you can enjoy the tranquility of nature, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 144,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-amsterdam-2-room-1-King-GardenView",
    name: "Standard King Suite",
    description: "Standard-themed king suite with a view of blooming flowers and greenery, with canal-inspired decor and cozy ambiance and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 211,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-amsterdam-2-room-1-SofaBed-GardenView",
    name: "Premium Sofa Bed Loft",
    description: "Premium-themed sofa bed loft with a view of the garden's lush greenery, with canal-inspired decor and cozy ambiance and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower"],
    accessibilityFeatures: ["Hearing Support", "Accessible Bathroom", "Wheelchair Accessible"],
    pricePerNight: 127,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-amsterdam-2-room-1-Twin-None",
    name: "Superior Twin Apartment",
    description: "A serene twin retreat with a pleasant outlook, blending minimalist style with comfortable amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 117,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-amsterdam-2-room-1-Single-CityView",
    name: "Polder Single Villa",
    description: "Polder-themed single villa with a window to the bustling city below, offering a unique Dutch experience with a contemporary twist and with a modern en-suite bathroom.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 101,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-amsterdam-2-room-1-Queen-None",
    name: "Polder Queen Apartment",
    description: "Our comfy Polder-themed apartment offers with a pleasant outlook, glamorous comfort, and featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 144,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  },
  {
    id: "hotel-amsterdam-2-room-1-Single-GardenView",
    name: "Canal Single Suite",
    description: "Enjoy a comfy stay in our Canal-themed single suite, offering where you can find solace in nature's embrace, with plush bedding for ultimate comfort, and unique touches of blending minimalist style with comfortable amenities.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 104,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
