import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Nijmegen River View
export const nijmegenRiverViewRooms: RoomOption[] = [
  {
    id: "hotel-amsterdam-7-room-6-Twin-CityView",
    name: "Deluxe Twin Villa",
    description: "Our Deluxe-themed twin villa offers classic luxury, panoramic where the city comes alive at dusk, and with plush bedding for ultimate comfort, inspired by featuring modern design with Dutch influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 101,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-amsterdam-7-room-6-King-None",
    name: "Polder King Suite",
    description: "This indulgent king accommodation offers with a pleasant outlook, offering a unique Dutch experience with a contemporary twist.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 150,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-amsterdam-7-room-6-Twin-None",
    name: "Polder Twin Loft",
    description: "Discover the charm of this Polder-themed twin loft, complete with homey ambiance, stunning with a pleasant outlook, and with high-speed internet access.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 93,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-amsterdam-7-room-6-Queen-None",
    name: "Executive Queen Room",
    description: "Experience our soft, classic queen room with a pleasant outlook, with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    pricePerNight: 136,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  },
  {
    id: "hotel-amsterdam-7-room-6-Double-OceanView",
    name: "Luxury Double Room",
    description: "Enjoy a refined stay in our Luxury-themed double room, offering with the sound of the ocean as your backdrop, equipped with all the modern conveniences, and unique touches of with canal-inspired decor and cozy ambiance.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 141,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-amsterdam-7-room-6-Double-None",
    name: "Deluxe Double Loft",
    description: "Deluxe-themed double loft with a pleasant outlook, with canal-inspired decor and cozy ambiance and complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 96,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-amsterdam-7-room-6-Queen-GardenView",
    name: "Polder Queen Room",
    description: "Polder-themed queen room with a view of the garden's vibrant colors, blending minimalist style with comfortable amenities and featuring a curated minibar selection.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 140,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-amsterdam-7-room-6-King-MountainView",
    name: "Classic King Loft",
    description: "A compact king retreat with panoramic views of the surrounding mountains, blending minimalist style with comfortable amenities.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 186,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 7,
  },
  {
    id: "hotel-amsterdam-7-room-6-Single-OceanView",
    name: "Delft Blue Single Room",
    description: "Relax in our stretching futuristic single room featuring with a panoramic view of the coastline, along with offering a unique blend of style and comfort and offering a unique Dutch experience with a contemporary twist.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 114,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  }
];
