import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Volendam Seaside Hotel
export const volendamSeasideHotelRooms: RoomOption[] = [
  {
    id: "hotel-amsterdam-1-room-0-SofaBed-None",
    name: "Premium Sofa Bed Villa",
    description: "Enjoy a tranquil stay in our Premium-themed sofa bed villa, offering with a pleasant outlook, with a luxurious soaking tub, and unique touches of blending minimalist style with comfortable amenities.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 169,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-amsterdam-1-room-0-Twin-MountainView",
    name: "Deluxe Twin Apartment",
    description: "This eclectic twin accommodation offers with majestic mountain vistas, offering a unique Dutch experience with a contemporary twist.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 223,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-amsterdam-1-room-0-Twin-None",
    name: "Luxury Twin Studio",
    description: "A deluxe twin retreat with a pleasant outlook, offering a unique Dutch experience with a contemporary twist.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 202,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-amsterdam-1-room-0-SofaBed-GardenView",
    name: "Standard Sofa Bed Apartment",
    description: "Step into a vast sofa bed apartment that combines Standard-themed with breathtaking where you can enjoy the serenity of a garden retreat, complemented by featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 234,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-amsterdam-1-room-0-SofaBed-MountainView",
    name: "Executive Sofa Bed Room",
    description: "Enjoy a regal stay in our Executive-themed sofa bed room, offering overlooking spectacular mountain ranges, equipped with all the modern conveniences, and unique touches of with canal-inspired decor and cozy ambiance.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 215,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-amsterdam-1-room-0-Queen-OceanView",
    name: "Superior Queen Loft",
    description: "Enjoy a spacious stay in our Superior-themed queen loft, offering where the ocean meets the sky, including climate control for your comfort, and unique touches of with canal-inspired decor and cozy ambiance.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 295,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 2,
  },
  {
    id: "hotel-amsterdam-1-room-0-King-MountainView",
    name: "Windmill King Studio",
    description: "A majestic king studio designed for grandiose comfort, with with a view of the mountains' changing seasons and including climate control for your comfort, reflecting with canal-inspired decor and cozy ambiance.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 358,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-amsterdam-1-room-0-Twin-OceanView",
    name: "Windmill Twin Villa",
    description: "A gentle twin retreat where you can feel the ocean breeze, offering a unique Dutch experience with a contemporary twist.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 265,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-amsterdam-1-room-0-King-None",
    name: "Standard King Villa",
    description: "Indulge in the well-proportioned atmosphere of our king villa, with spectacular with a pleasant outlook, featuring modern design with Dutch influences, and with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 297,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 2,
  }
];
