import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Coastal Breeze Hotel
export const theCoastalBreezeHotelRooms: RoomOption[] = [
  {
    id: "hotel-los-angeles-6-room-5-Single-OceanView",
    name: "Superior Single Penthouse",
    description: "A refined single penthouse designed for refined comfort, with where you can enjoy the ocean's beauty and with a spacious seating area, reflecting decorated with local artistic influences.",
    occupancy: {
      adults: 1,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 136,
    currency: "USD",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-los-angeles-6-room-5-Twin-CityView",
    name: "Harmony Twin Suite",
    description: "A regal twin suite designed for elegant comfort, with showcasing the urban landscape and featuring premium bath amenities, reflecting designed for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 145,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-los-angeles-6-room-5-Queen-None",
    name: "Signature Queen Studio",
    description: "Unwind in this regal queen studio with a pleasant outlook, complete with a well-appointed bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 176,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 2,
  },
  {
    id: "hotel-los-angeles-6-room-5-Single-MountainView",
    name: "Serenity Single Room",
    description: "Our Serenity-themed single room offers generous luxury, panoramic with a view of the mountains' changing seasons, and with plush bedding for ultimate comfort, inspired by designed for ultimate comfort.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 147,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-los-angeles-6-room-5-King-None",
    name: "Classic King Room",
    description: "Classic-themed king room with a pleasant outlook, created with both style and function in mind and with carefully selected furnishings.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 182,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  }
];
