import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for The Harbor View Suites
export const theHarborViewSuitesRooms: RoomOption[] = [
  {
    id: "hotel-los-angeles-12-room-11-Twin-GardenView",
    name: "Executive Twin Suite",
    description: "A stylish twin suite designed for elegant comfort, with with a view of colorful flower beds and with blackout curtains for a perfect night's sleep, reflecting decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 123,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 6,
  },
  {
    id: "hotel-los-angeles-12-room-11-King-MountainView",
    name: "Horizon King Suite",
    description: "Our broad Horizon-themed suite offers with a view of the mountains' lush valleys, vintage comfort, and offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 226,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-los-angeles-12-room-11-Queen-GardenView",
    name: "Luxury Queen Villa",
    description: "Enjoy a deluxe stay in our Luxury-themed queen villa, offering overlooking lush garden landscapes, with blackout curtains for a perfect night's sleep, and unique touches of decorated with local artistic influences.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe"],
    accessibilityFeatures: ["Accessible Bathroom", "Hearing Support", "Wheelchair Accessible"],
    pricePerNight: 162,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-los-angeles-12-room-11-King-None",
    name: "Superior King Room",
    description: "Step into a upscale king room that combines Superior-themed with breathtaking with a pleasant outlook, complemented by offering a unique blend of style and comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 165,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-los-angeles-12-room-11-Twin-CityView",
    name: "Standard Twin Room",
    description: "Standard-themed twin room with a view of iconic landmarks, designed for ultimate comfort and including climate control for your comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 124,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-los-angeles-12-room-11-Double-CityView",
    name: "Tranquility Double Studio",
    description: "This generous double accommodation offers with a window to the bustling city below, created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    accessibilityFeatures: ["Wheelchair Accessible", "Hearing Support"],
    pricePerNight: 129,
    currency: "USD",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 5,
  },
  {
    id: "hotel-los-angeles-12-room-11-Twin-MountainView",
    name: "Executive Twin Loft",
    description: "Our Executive-themed twin loft offers intimate luxury, panoramic where you can experience the beauty of nature, and with carefully selected furnishings, inspired by featuring thoughtful design elements.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 146,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 8,
  },
  {
    id: "hotel-los-angeles-12-room-11-Double-GardenView",
    name: "Harmony Double Villa",
    description: "Our Harmony-themed double villa offers comfy luxury, panoramic where you can enjoy the serenity of a garden retreat, and complete with a well-appointed bathroom, inspired by created with both style and function in mind.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 131,
    currency: "USD",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-los-angeles-12-room-11-King-OceanView",
    name: "Executive King Suite",
    description: "Experience our opulent, indulgent king suite where you can watch the waves roll in, including climate control for your comfort.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp", "Daily Housekeeping"],
    pricePerNight: 240,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 3,
  },
  {
    id: "hotel-los-angeles-12-room-11-SofaBed-None",
    name: "Executive Sofa Bed Villa",
    description: "A comfy sofa bed retreat with a pleasant outlook, featuring thoughtful design elements.",
    occupancy: {
      adults: 1,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 115,
    currency: "USD",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 9,
  }
];
