import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Rhodes Old Town Lodge
export const rhodesOldTownLodgeRooms: RoomOption[] = [
  {
    id: "hotel-santorini-4-room-3-SofaBed-None",
    name: "Luxury Sofa Bed Studio",
    description: "This large-scale sofa bed studio promises with a pleasant outlook, enriched by Luxury-themed details and equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 142,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-santorini-4-room-3-Twin-CityView",
    name: "Standard Twin Penthouse",
    description: "Unwind in this room-filled twin penthouse showcasing the urban landscape, with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    accessibilityFeatures: ["Wheelchair Accessible", "Hearing Support", "Elevator"],
    pricePerNight: 164,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-santorini-4-room-3-Queen-GardenView",
    name: "Santorini Queen Studio",
    description: "Our open-concept Santorini-themed studio offers where you can enjoy the serenity of a garden retreat, open-concept comfort, and with plush bedding for ultimate comfort.",
    occupancy: {
      adults: 2,
      children: 1,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service"],
    pricePerNight: 229,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 7,
  },
  {
    id: "hotel-santorini-4-room-3-Double-CityView",
    name: "Classic Double Studio",
    description: "Unwind in this sumptuous double studio where you can watch the city wake up, with a modern en-suite bathroom.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer"],
    pricePerNight: 169,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 4,
  },
  {
    id: "hotel-santorini-4-room-3-King-CityView",
    name: "Premium King Room",
    description: "Enjoy a room-filled stay in our Premium-themed king room, offering with stunning views of the city skyline, with blackout curtains for a perfect night's sleep, and unique touches of offering a serene and relaxing atmosphere with Mediterranean charm.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock"],
    pricePerNight: 274,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 9,
  },
  {
    id: "hotel-santorini-4-room-3-Twin-MountainView",
    name: "Luxury Twin Loft",
    description: "Enjoy a modern stay in our Luxury-themed twin loft, offering overlooking spectacular mountain ranges, featuring a curated minibar selection, and unique touches of with classic Greek architectural elements and modern comforts.",
    occupancy: {
      adults: 2,
      children: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker"],
    pricePerNight: 201,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 4,
  },
  {
    id: "hotel-santorini-4-room-3-Single-MountainView",
    name: "Standard Single Suite",
    description: "Our refreshing Standard-themed suite offers where you can gaze at the towering peaks, calming comfort, and featuring premium bath amenities.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 151,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 5,
  },
  {
    id: "hotel-santorini-4-room-3-Queen-OceanView",
    name: "Aegean Queen Penthouse",
    description: "Aegean-themed queen penthouse with a view of the ocean's changing tides, with classic Greek architectural elements and modern comforts and with a spacious work area.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 235,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: false,
    availableCount: 1,
  }
];
