import { RoomOption } from "@/lib/interfaces/services/rentals";

// Room options for Santorini Caldera View
export const santoriniCalderaViewRooms: RoomOption[] = [
  {
    id: "hotel-santorini-9-room-8-Double-None",
    name: "Mykonos Double Apartment",
    description: "A broad double apartment designed for modern comfort, with with a pleasant outlook and including climate control for your comfort, reflecting with classic Greek architectural elements and modern comforts.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Double",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    accessibilityFeatures: ["Hearing Support", "Visual Aids"],
    pricePerNight: 90,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 3,
  },
  {
    id: "hotel-santorini-9-room-8-Double-CityView",
    name: "Classic Double Loft",
    description: "Classic-themed loft with extensive decor, with a view of iconic landmarks, and with a spacious seating area.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Double",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service"],
    pricePerNight: 103,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-santorini-9-room-8-SofaBed-MountainView",
    name: "Aegean Sofa Bed Villa",
    description: "Experience our opulent, avant-garde sofa bed villa with a view of the mountains' serene beauty, equipped with all the modern conveniences.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating"],
    pricePerNight: 99,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-santorini-9-room-8-Twin-GardenView",
    name: "Classic Twin Apartment",
    description: "Relax in our refreshing pleasant twin apartment featuring where you can enjoy the sights and sounds of nature, along with with plush bedding for ultimate comfort and offering a serene and relaxing atmosphere with Mediterranean charm.",
    occupancy: {
      adults: 2,
      maxGuests: 2,
    },
    bedType: "Twin",
    view: "Garden View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries"],
    pricePerNight: 93,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 10,
  },
  {
    id: "hotel-santorini-9-room-8-SofaBed-CityView",
    name: "Executive Sofa Bed Loft",
    description: "A sophisticated sofa bed loft designed for intimate comfort, with where you can enjoy the city's energy and equipped with all the modern conveniences, reflecting with classic Greek architectural elements and modern comforts.",
    occupancy: {
      adults: 1,
      maxGuests: 2,
    },
    bedType: "Sofa Bed",
    view: "City View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    pricePerNight: 93,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-santorini-9-room-8-Queen-OceanView",
    name: "Deluxe Queen Suite",
    description: "Enjoy a indulgent stay in our Deluxe-themed queen suite, offering where you can relax to the sound of the waves, with a spacious work area, and unique touches of featuring Aegean-inspired decor with blue and white tones.",
    occupancy: {
      adults: 2,
      children: 0,
      maxGuests: 2,
    },
    bedType: "Queen",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers"],
    pricePerNight: 133,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: false,
    availableCount: 10,
  },
  {
    id: "hotel-santorini-9-room-8-King-OceanView",
    name: "Santorini King Apartment",
    description: "Unwind in this sumptuous king apartment with a view of the endless blue, featuring premium bath amenities.",
    occupancy: {
      adults: 2,
      maxGuests: 3,
    },
    bedType: "King",
    view: "Ocean View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave", "Shower", "Heating", "Coffee Maker", "Slippers", "Bathrobe", "Room Service", "Alarm Clock", "Desk Lamp"],
    pricePerNight: 144,
    currency: "EUR",
    refundable: true,
    breakfastIncluded: true,
    availableCount: 1,
  },
  {
    id: "hotel-santorini-9-room-8-Single-MountainView",
    name: "Premium Single Loft",
    description: "This open-concept single loft promises where you can enjoy the tranquility of the mountains, enriched by Premium-themed details and featuring a curated minibar selection.",
    occupancy: {
      adults: 1,
      children: 2,
      maxGuests: 1,
    },
    bedType: "Single",
    view: "Mountain View",
    amenities: ["Desk", "Free Wi-Fi", "Room Service", "Hair Dryer", "Toiletries", "Microwave"],
    accessibilityFeatures: ["Accessible Bathroom"],
    pricePerNight: 88,
    currency: "EUR",
    refundable: false,
    breakfastIncluded: true,
    availableCount: 2,
  }
];
